### ISSUE TITLE
rtags wipes buffer on find-file

### ISSUE THREAD

**Issue by dmakarov** [Andersbakken/rtags#1000]
### Please mark appropriate
 - [ ] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [X ] rtags.el

### Problem description
rtags deletes the content of an entire buffer

#### Expected behavior
Expect to have a normal buffer with file content.

#### Actual behavior
When a file is loaded into Emacs buffer c/cc++ with find-file rtags deletes the entire content of buffer so that the buffer is literally empty.  The content can be restored with a single undo operation.

### Environment
- Your operating system: MacOS 10.12.5

- LLVM/Clang version: 4.0.1

This started to happen after update to the most recent rtags 20170705.144

**Comment by harindu95** [comment]
I have the same issue.

**Comment by dmakarov** [comment]
No, for me it doesn't matter whether rdm is running or not.  I just checked, it happens when I start emacs, and when it loads files that were open in the previous session.  It also happens when find-file a c/c++ file, despite that rdm is running.

**Comment by dmakarov** [comment]
An additional detail: the problem occurs for rtags 2.10, the latest stable version installed by `brew install rtags`.  I uninstalled the stable version, and installed the `--HEAD` version built from source, i.e. `brew install rtags --HEAD`.  Now the problem is resolved.  I don't know if you want to fix this, or close the issue -- either way is fine for me.  Although, I would prefer to use a stable rtags version and have it working with the latest rtags emacs package.

**Comment by harindu95** [comment]
I am using version: 2.10.117 from the git repo. It didn't solve the issue for me. Bu as I said I have a workaround. It's your choice

**Comment by tddsg** [comment]
I upgrade my Emacs packages today and encountered the same issue that all my C/C++ file are wiped out just after opening. How did you manage to fix that?

**Comment by tddsg** [comment]
I ended up with a shameless fixed by replacing all the content of the latest file `rtags.el` with the predecessor version in this revision: https://github.com/Andersbakken/rtags/commit/005e5569366b519850f0ae5b78f618f4d67d8785

**Comment by dmakarov** [comment]
Maybe as a fix, cut a new release of rtags? Then brew upgrade will pick up the new release of rtags, and it should work with the most recent version of emacs rtags package. Currently the stable release 2.10 of rtags is incompatible with the most recent version of emacs rtags package available through elpa.

**Comment by dmakarov** [comment]
However a proper fix should be to never allow rtags package to modify a buffer unless a modification is an expected result of a well-defined command. No matter how far the emacs rtags package diverged from rdm version the former should not change an emacs buffer when a c/c++ file is opened.

**Comment by Andersbakken** [comment]
Sorry about this one. Bad bug :-( Should be fixed now.
