### ISSUE TITLE
libc++ headers not found

### ISSUE THREAD

**Issue by clauniel** [Andersbakken/rtags#1001]
### Please mark appropriate
 - [x] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description
Rtags does not find libc headers. Giving for example /../lib64/gcc/x86_64-pc-linux-gnu/7.1.1/../../../../include/c++/7.1.1/cstdlib:75:15: fatal error: 'stdlib.h' file not found

Same happens for stddef.h etc etc.

I looked through some older issues and tried including /usr/lib/clang using --isystem for rdm, which does not help the probem.

I recompiled Rtags passing -DLIBCLANG_LIBDIR=/usr/lib/clang/4.0.1/include with no success.

clang -v shows the following include paths:

#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /usr/bin/../lib/clang/4.0.1/include
 /usr/include
End of search list.

I can jump to definitions, but I don't get syntax error messages.

### Environment
- Your operating system: Arch Linux

- LLVM/Clang version: 4.0.1

**Comment by Dushistov** [comment]
@clauniel 

I also use Arch Linux, I start `rdm` in such way:
```sh
nice ./bin/rdm -v -v -j4  --isystem /usr/include/c++/7.1.1 --isystem /usr/bin/../lib/clang/4.0.1/include --isystem /usr/include   2>&1 | tee /tmp/rdm.log
```
with this command line args, I can jump from `printf` to `stdio.h`

**Comment by clauniel** [comment]
@Dushistov Thanks!

**Comment by Andersbakken** [comment]
Note that passing -v -v to rdm makes it output rather large amounts of text
to your log file and likely this slows it down somewhat.

Anders

**Comment by Andersbakken** [comment]
Btw. I don't run arch but I installed it in virtualbox and did the following: 

pacman -S wget clang llvm/extra cmake gcc 
wget https://andersbakken.github.io/rtags-releases/rtags-2.11.tar.gz
tar xvfz rtags-2.11.tar.gz
cd rtags-2.11
./configure 
make
./bin/rdm &
./bin/rc -J 

And it was able to find the appropriate headers without passing any switches to rdm. Are you guys installing clang in a different way? I'm not that familiar with arch?

**Comment by clauniel** [comment]
@Andersbakken After a recent update to clang I am also unable to reproduce the problem.

**Comment by Andersbakken** [comment]
Maybe the arch clang package moved the headers around. It's kinda
heuristic-based. I guess most arch people update frequently so maybe it
won't be a problem. Let me know if it starts happening again.

Anders
