### ISSUE TITLE
Source tar URLs are broken

### ISSUE THREAD

**Issue by FinnG** [Andersbakken/rtags#1003]
### Problem description
I tried to install the rtags emacs plugin using `M-x rtags-install` but the following rtags source links are broken:

https://andersbakken.github.io/rtags-releases/rtags-2.10.tar.bz2
https://andersbakken.github.io/rtags-releases/rtags-2.10.tar.gz

This (unsurprisingly) causes the `install-rtags.sh` script to fail in the following manner:
```
gfg@quark ~/.emacs.d/elpa/rtags-20170710.214 $ ./install-rtags.sh 
+ FILE=rtags-2.10.tar.bz2
+ URL=https://andersbakken.github.io/rtags-releases/rtags-2.10.tar.bz2
+ ARGS='--progress -L -o rtags-2.10.tar.bz2'
+ CMAKEARGS=
+ '[' -e rtags-2.10.tar.bz2 ']'
+ ARGS='--progress -L -o rtags-2.10.tar.bz2 https://andersbakken.github.io/rtags-releases/rtags-2.10.tar.bz2'
+ echo 'Downloading rtags from https://andersbakken.github.io/rtags-releases/rtags-2.10.tar.bz2'
Downloading rtags from https://andersbakken.github.io/rtags-releases/rtags-2.10.tar.bz2
+ curl --progress -L -o rtags-2.10.tar.bz2 https://andersbakken.github.io/rtags-releases/rtags-2.10.tar.bzcurl --progress -L -o rtags-2.10.tar.bz2 https://andersbakken.github.io/rtags-releases/rtags-2.10.tar.bz22
################################################################################################################################ 100.0%
+ tar xfj rtags-2.10.tar.bz2
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
+ echo 'Failed to untar rtags-2.10.tar.bz2'
Failed to untar rtags-2.10.tar.bz2
+ rm rtags-2.10.tar.bz2
+ exit 2
```

These links are also the links provided in the [Building Rtags](https://github.com/Andersbakken/rtags#building-rtags) section of the README.org file.

**Comment by Glaeqen** [comment]
curl downloads "page doesn't exist" html file as rtags....tar.bz2 ;p

**Comment by FinnG** [comment]
:D I didn't actually look at the content of the `rtags-2.10.tar.bz2`, but that doesn't surprise me!

What I'm doing for the time being is building from source which all still works fine - it's a bit frustrating as all I did was update all my emacs packages and this stopped working.

**Comment by Andersbakken** [comment]
Oops. I just updated the version to 2.11 and forgot to update the readme. Should be fixed now.

**Comment by Andersbakken** [comment]
Note that the first commit didn't fix it entirely. The release process apparently needs some love.

**Comment by FinnG** [comment]
Thanks for the patch. Is there a GitHub issue describing what needs work? I might have some time to look at it if you like.

**Comment by Andersbakken** [comment]
Sorry about the delay. There isn't really. I just added a little script that does it. It's not that complicated, only a 3 files that need to be updated.
