### ISSUE TITLE
Add xref support (new Emacs25 standard API)

### ISSUE THREAD

**Issue by jwalt** [Andersbakken/rtags#1004]
I have created a standalone implementation of an rtags backend for the new Emacs25 ```xref.el``` API.  

 https://gist.github.com/jwalt/d821c70082b4974c26c8fc15f190d930

It is almost a perfect match, except that ```xref.el``` assumes an apropos search to be via regex, while ```rc -a -F``` only supports basic wildcards (```-Z``` does not apply to ```-F```). The code linked above transforms a small subset of regexes into wildcard form, which I think is useful enough for the time being.

This solution also addresses #600 in a way.

Please feel free to include or adapt that file in rtags.

**Comment by Andersbakken** [comment]
Looks awesome. Do you want to file a PR to make the authorship more clear? Note also that I made -Z work for -F just now but it performs somewhat poorly.

**Comment by eas** [comment]
Hi, this looks really great! I don't see it in the package though. Are there plans to integrate?

**Comment by rileyrg** [comment]
Just a little beep here. Into the rtags package or melpa would be great.

**Comment by Andersbakken** [comment]
I just added this now. Sorry about the long delay.
