### ISSUE TITLE
add a note in the README *not to build* the project in /tmp as it is filtered 

### ISSUE THREAD

**Issue by RomanShestakov** [Andersbakken/rtags#1008]
### Please mark appropriate
 - [ ] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [x ] rtags.el

### Problem description
spent few hours trying to understand why the given in README example to navigate for rtags project doesn't work. Turned out that because I built it in /tmp and /tmp is being auto-filtered so indexing doesnt' work. Would make sense to point this out in the README to save somebody time.

#### Expected behavior
Describe what you expected to happen.

#### Actual behavior
Describe what actually happened.

### Environment
- Your operating system:

- LLVM/Clang version:

### Feature request

Describe the feature we should add to **RTags**.

**Comment by Andersbakken** [comment]
I can see that one being hard to debug :-) 

I added a little section in the install document.

**Comment by Andersbakken** [comment]
I also made it so that rdm will print something on stderr when it happens.

**Comment by RomanShestakov** [comment]
thank you very much!
