### ISSUE TITLE
Bad macro arguments in src/rct/rct.cmake

### ISSUE THREAD

**Issue by previt** [Andersbakken/rtags#1009]
### Please mark appropriate
 - [] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description
When I tried to configure rtags with CMake I kept getting this error:

CMake Error at src/rct/rct.cmake:90 (pkg_search_module):
   pkg_search_module Macro invoked with incorrect arguments for macro named:
   pkg_search_module
 Call Stack (most recent call first):
   src/CMakeLists.txt:107 (include)

#### Expected behavior
Describe what you expected to happen.

#### Actual behavior
Describe what actually happened.

### Environment
- Your operating system: Fedora 

- LLVM/Clang version:

### Feature request
Remove the mistake in file src/rct/rct.cmake, line 90:
`(pkg_search_module ZLIB)`
 should be 
`(pkg_search_module ZLIB zlib)`
Works like a charm.

**Comment by Andersbakken** [comment]
Sorry. This took me a while. Fixed now. Thanks.
