### ISSUE TITLE
Feature request: ability of cloning an index

### ISSUE THREAD

**Issue by asenac** [Andersbakken/rtags#1010]
### Feature request

Sometimes my workflow involves creating a new git worktree for a branch, which content I have already indexed with RTags. I would love to be able to, with a simple command, clone the current index but replace the file paths to point to the files in the new worktree. Currently I need to index the new worktree from scratch which takes a lot of time. I presume that by having this ability of cloning the index I could save a lot of processing time every day.

Thanks!

**Comment by Andersbakken** [comment]
I can see why this is a useful thing but it isn't that easy. RTags manages the dirtiness of its database with timestamps and even if I put in the functionality to change the fileids etc in the database it would be a little tricky to consider it not dirty. It's certainly possible. I'll try to think of a way to achieve this.

**Comment by cslux** [comment]
Related to #1006
