### ISSUE TITLE
Error when cloning repo

### ISSUE THREAD

**Issue by rajukv** [Andersbakken/rtags#1012]
### Please mark appropriate
 - [ ] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description
$ git clone --recursive https://github.com/Andersbakken/rtags.git
Cloning into 'rtags'...
remote: Counting objects: 38181, done.
remote: Compressing objects: 100% (72/72), done.
remote: Total 38181 (delta 58), reused 67 (delta 33), pack-reused 38076
Receiving objects: 100% (38181/38181), 23.83 MiB | 972.00 KiB/s, done.
Resolving deltas: 100% (24007/24007), done.
Submodule 'src/lua' (https://github.com/LuaDist/lua.git) registered for path 'src/lua'
Submodule 'src/rct' (https://github.com/Andersbakken/rct) registered for path 'src/rct'
Submodule 'src/selene' (https://github.com/jeremyong/Selene.git) registered for path 'src/selene'
Cloning into '/home/rajukv/code/rtags/src/lua'...
remote: Counting objects: 1056, done.        
remote: Total 1056 (delta 0), reused 0 (delta 0), pack-reused 1056        
Receiving objects: 100% (1056/1056), 914.06 KiB | 437.00 KiB/s, done.
Resolving deltas: 100% (721/721), done.
Cloning into '/home/rajukv/code/rtags/src/rct'...
remote: Counting objects: 5795, done.        
remote: Compressing objects: 100% (4/4), done.        
remote: Total 5795 (delta 0), reused 1 (delta 0), pack-reused 5791        
Receiving objects: 100% (5795/5795), 1.73 MiB | 640.00 KiB/s, done.
Resolving deltas: 100% (4127/4127), done.
Cloning into '/home/rajukv/code/rtags/src/selene'...
remote: Counting objects: 1343, done.        
remote: Total 1343 (delta 0), reused 0 (delta 0), pack-reused 1342        
Receiving objects: 100% (1343/1343), 329.13 KiB | 189.00 KiB/s, done.
Resolving deltas: 100% (807/807), done.
Submodule path 'src/lua': checked out '98648514bf7c15d12ccb56222a85e06bfcf9317f'
error: Server does not allow request for unadvertised object abdb60b81b65feea57eea3412caed9dd98a90a18
Fetched in submodule path 'src/rct', but it did not contain abdb60b81b65feea57eea3412caed9dd98a90a18. Direct fetching of that commit failed.

#### Expected behavior
Describe what you expected to happen.

#### Actual behavior
Describe what actually happened.

### Environment
- Your operating system:
Debian sid(unstable)

- LLVM/Clang version:

### Feature request

Describe the feature we should add to **RTags**.

**Comment by RykoL** [comment]
I can confirm this issue. Seems like rtc is referncing a non existing commit.

**Comment by eduardtm** [comment]
meanwhile, you can do git clone --recursive --branch v2.10 https://github.com/Andersbakken/rtags.git for the latest stable

**Comment by Andersbakken** [comment]
Oops. Fixed now.

**Comment by rajukv** [comment]
verified the fix. Closing the issue
