### ISSUE TITLE
Is it missing rtags 2.11 release? 

### ISSUE THREAD

**Issue by jetm** [Andersbakken/rtags#1013]
### Please mark appropriate
 - [X] rtags (rdm/rc/rp)
 
### Problem description
I maintain rtags package in Arch Linux. Someone told me that this package is outdated because there is 2.11 release: https://andersbakken.github.io/rtags-releases/rtags-2.11.tar.bz2. I wonder if that is right and in GitHub is missing rtags 2.11 release?

Note: It seems emacs rtags from melpa now use 2.11 as well.

**Comment by Andersbakken** [comment]
Oops. Right you are. I forgot to push the tag.

Sorry about that.

Anders

**Comment by Andersbakken** [comment]
Should be fixed now.

**Comment by jetm** [comment]
@Andersbakken: Thank you. I have updated rtags package in Arch Linux.

**Comment by Andersbakken** [comment]
Thanks.
