### ISSUE TITLE
Build failing due to C++11 feature

### ISSUE THREAD

**Issue by stuglaser** [Andersbakken/rtags#1015]
The build for rtags is currently failing due to using a C++11 feature (`string::erase(const iterators)`), but not setting C++11 compile flags.

The CI system has recognized this failure too: https://travis-ci.org/Andersbakken/rtags/jobs/257881603

**Comment by jeffpollock9** [comment]
Not failing due to a missing `-std=c++11` flag - you can see it being set here: https://travis-ci.org/Andersbakken/rtags/jobs/257881603#L1043

**Comment by stuglaser** [comment]
You're right, it's not the c++11 flag.  It seems to be related to libstdc++ not keeping up with C++11: https://stackoverflow.com/questions/15987893/c11-erase-using-a-const-iterator

I hacked around it by changing String.h to this:

```
    template <typename It>
    iterator erase(It begin, It end)
    {
        return mString.erase(begin, end);
    }
```

...which is not very satisfying, but works for me.

**Comment by Andersbakken** [comment]
I added a compile test for this which I think should take care of it. Please reopen if the problem remains.

**Comment by jeffpollock9** [comment]
@Andersbakken works for me now - thanks!

**Comment by Andersbakken** [comment]
Glad to hear. Thanks.
