### ISSUE TITLE
Support increasing project for huge source repo

### ISSUE THREAD

**Issue by sunlin7** [Andersbakken/rtags#1017]
### Please mark appropriate
 - [x] rtags (rdm/rc/rp)

### Feature request

Support increasing project for huge source repo, eg: chromium. 

When I try rtags with source code of chromium , the rdm seems never stop after 1 day.

So if the rtags support increasing project, I can start from a part of chromium, add more part when necessary.

**Comment by nickdiego** [comment]
Hi @sunlin7 ,
How did you feed compilation commands into Rdm ?

These days, [I implemented a tool](https://github.com/nickdiego/compiledb-generator) for generating compile_commands.json file for large projects (mainly for AOSP projects in my case, for studying purposes) and used it successfully to index and navigate with Rtags for some large modules, such as bionic, didn't test chromium yet and I'm using AOSP 5.0 codebase.

So, could you provide more details on how you tried to use rtags with your chromium repo?

Cheers,
Nick

**Comment by sunlin7** [comment]
Hi @nickdiego 
Actually I follow the instruments from [Checking out and building Chromium on Linux](https://chromium.googlesource.com/chromium/src/+/master/docs/linux_build_instructions.md), after the step [Build Chromium](https://chromium.googlesource.com/chromium/src/+/master/docs/linux_build_instructions.md#Build-Chromium), the chromium is generated and every thing work find.
Then I use command `ninja -C out/Default chrome -t compdb cxx cc > compile_commands.json` to generate the compile_commands.json, and do `rc -J compile_commands.json` for rdm.

The chromium project is so huge, and rdm take about 1 day to index the cc/cxx files (and stuck at about 80%). 
So I suggest the rtags support increasing project manager, that will allow user start from a small project, then add more and more file if user want.

BR,
Lin

**Comment by sunlin7** [comment]
Close this ticket.
I'm try the https://github.com/cquery-project/cquery now.
