### ISSUE TITLE
company-rtags shadows other company backends

### ISSUE THREAD

**Issue by TheJJ** [Andersbakken/rtags#1030]
### Please mark appropriate
 - [ ] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [X] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description
My `company-backends` are: `(company-rtags company-c-headers (company-dabbrev-code company-gtags company-etags company-keywords) company-files company-dabbrev)`

`rtag` completion works, but none of the others. This means for example keywords or some random english words in comments are never completed.

#### Expected behavior
If `rtags` has no completion match, other backends should take over.

#### Actual behavior
`company-rtags` does not allow other backends to provide answers.

#### Example

Cursor is at `|`.

``` cpp
int main() {
	ret|
}
-> M-x company-complete => "No completion found"
-> M-x company-keywords => return is completed
(both completion backends are in the backend list though)
```

### Environment
- Your operating system: Gentoo
- LLVM/Clang version: 4

**Comment by ambihelical** [comment]
Seems to be a duplicate of #838

**Comment by TheJJ** [comment]
Sounds similar, although you are talking about comments specifically, the problem is likely the same.

How does a completion function prevent other backends from running?

**Comment by ambihelical** [comment]
Most likely the response to the prefix command is 'stop.  If it was nil, other company backends would execute.  See http://sixty-north.com/blog/writing-the-simplest-emacs-company-mode-backend

**Comment by TheJJ** [comment]
Hard to tell. Within comments, it should return `nil`. For the completion of keywords like my `return`, it is the right context but doesn't have completion info (i.e. return `stop`). But the only way to make it work is to let it return `nil` as well, so that the `company-keywords` backend can take over.

**Comment by ambihelical** [comment]
Submitted PR to at least handle the comments and strings part.  Please test if possible.

**Comment by TheJJ** [comment]
I think the proper solution is #1033 and adding C/C++ keywords to `company-rtags` (or directly relay by calling `company-keywords` when appropriate).

That way, `company-rtags` is the "only" true source for C++-completion in non-comments/strings.

Before `company-rtags` is that complete, returning `nil` in the prefix function "more often" would be a first step.

**Comment by vibrys** [comment]
I'm experiencing the same problem. company-keywords is not when on the backends list after company-rtags and I'm missing it. @TheJJ, IMO: company-rtags should not prevent later backends to do the job. If one does not want them, then one can remove them from backends list.

**Comment by cslux** [comment]
Hey guys!

I have pushed a fix for this to the [develop](https://github.com/Andersbakken/rtags/commit/956ab09190cc2b9c163cbb86aa03e26c2f3b646f) branch. Please, try it out and report back.

If the call to `rc` returns no candidates, `nil` will now returned, and the next backend gets called.

Thanks
Christian

**Comment by TheJJ** [comment]
Seems to work! Thank you very much. This was the remaining blocking issue for me because words in comments were not completed for me. Now ship it :ship: :shipit:  :)
