### ISSUE TITLE
"No information for symbol" on rtags-display-summary

### ISSUE THREAD

**Issue by chep** [Andersbakken/rtags#1035]
### Please mark appropriate
 - [X] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [X] rtags.el

### Problem description
I always have "No information for symbol" when I try to use rtags-display-summary

#### Expected behavior
A brief summary of my variable/struct/class/function...

### Environment
- Your operating system:
Archlinux

- LLVM/Clang version:
4.0.1-5

- Emacs:
26.0.50

- Rtags:
master branch

### Recipe:

start emacs -Q
Create test.c:

#include <stdio.h>
struct test
{
  int a;
  int b;
};

int main()
{
  struct test testvar;
  testvar.a = 2;
  return 0;  
}

Create Makefile:
all:
	$(CC) -o test test.c

run "make -nk | rc -c -"

load rtags:
M-x load-file and enter the path to rtags.el

In test.c, place point on "testvar" in this line: "testvar.a = 2;"
M-x rtags-find-symbol
Point should move to declaration
M-x rtags-display-summary
=> "No information for symbol"

**Comment by gse4me** [comment]
I also had this problem.
Seems to be related to commit https://github.com/Andersbakken/rtags/commit/097d8ed41009a4f4ce819552a104d2f25442890c
 (rtags-call-rc :path path :noerror t :silent-query silent :silent silent "-U" location "--elisp"

I locally removed the added :silent silent and it works

**Comment by chep** [comment]
You are right.
It works without ":silent silent".
And it also fix the other issue I wrote: #1036

**Comment by Andersbakken** [comment]
Oops. Should work again now.
