### ISSUE TITLE
rtags-current-container-hook never called

### ISSUE THREAD

**Issue by chep** [Andersbakken/rtags#1036]
### Please mark appropriate
 - [X] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [X] rtags.el

### Problem description
Function added to rtags-current-container-hook are not called anymore

#### Actual behavior
rtags-current-container seems to always return nil so run-hook-with-args is never called in function rtags-update-current-container-cache

### Environment
- Your operating system:
Archlinux

- LLVM/Clang version:
4.0.1-5

- Emacs:
26.0.50

**Comment by Andersbakken** [comment]
Should work now.
