### ISSUE TITLE
https://andersbakken.github.io/rtags-releases/rtags-2.13.tar.bz2 not found

### ISSUE THREAD

**Issue by Yevgnen** [Andersbakken/rtags#1037]
While https://andersbakken.github.io/rtags-releases/rtags-2.12.tar.bz2 still works fine.

**Comment by kain88-de** [comment]
I have the same issue.

**Comment by tillt** [comment]
Maybe related to the fact that the 2.13 tag had changed causing other issues (https://github.com/Andersbakken/rtags/issues/1040) as well?

**Comment by tillt** [comment]
Seems I was wrong as the new tag (2.14) has the same issue.

**Comment by novakboskov** [comment]
@tillt Can you please reopen #1040 or somehow signalize that problem is not solved yet? Just to avoid confusion.

**Comment by isolet** [comment]
I have been coded without rtags for 10 days, any idea about how to downgrade it ?

**Comment by novakboskov** [comment]
@isolet Unfortunately, you have to choose another method to install rtags. 
If your OS use some kind of package manager maybe you should search its repository for rtags (and hope that its up to date). I'm on Arch Linux and its third party package repository AUR provides rtags which is up to date and it works fine in conjunction with latest version of Elisp part from MELPA.
Ultimately, you could build it from source.

**Comment by tillt** [comment]
@novakboskov https://github.com/Andersbakken/rtags/issues/1040 was trying to solve the retagging of rtags which caused problems downstream. After the bump I downstream (homebrew) simply bumped their package as well. That way 2.13 will always be broken for homebrew but we got a well functioning 2.14 - good enough.
If this retagging was really related to this issue for the missing tarballs is still unclear to me. Only @Andersbakken will be able to explain that.
I would suggest to open a new issue handling the missing tarball of 2.14.

**Comment by zhangjunphy** [comment]
Seems rtags package versions in this repo and https://github.com/Andersbakken/rtags-releases are out of sync.

For rtags users, change this line in the rtags installation (usually `~/.emacs.d/elpa/rtags-2017*/rtags.el`)
```elisp
(defconst rtags-package-version "2.14")
```
into
```elisp
(defconst rtags-package-version "2.12")
```
should temporarily fix this problem.

**Comment by Andersbakken** [comment]
Sorry guys.

I'm in the middle of a move and my workstation that normally runs a cronjob
to make sure the package is kept up to date is boxed up :-(

I ran it manually now and it should work again

I'll try not to let this happen again.

Anders

**Comment by Andersbakken** [comment]
I've added all the all tarballs to the gh-pages repo so downgrading on homebrew should work again now.

**Comment by kain88-de** [comment]
@Andersbakken can you share the script to publish the tarball? If yes we can move it to a cron-job on travis. That would then be independent from your personal machines. [Travis-Docs](https://docs.travis-ci.com/user/cron-jobs/)
