### ISSUE TITLE
2.13 tag seems to have changed - was this intentional?

### ISSUE THREAD

**Issue by tillt** [Andersbakken/rtags#1040]
### Please mark appropriate
 - [x] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description

The changed 2.13 release tag renders homebrew formula unusable.

The former was 23a3eb2cd2283476f19e630b869acd8545167560, the latest is 93b0063626c54ab976b2c8f2dba8cd9d25e18bd4.

Can you please provide some background on why this was needed or intentional to allow downstream decide on a proper solution.

https://github.com/Homebrew/homebrew-core/issues/17333

**Comment by Andersbakken** [comment]
It actually was. Maybe that was a bad idea but I released with a relatively
bad bug that I didn't want anyone to have :-)

Is it causing problems? I can certainly bump the version again.

Anders

**Comment by tillt** [comment]
homebrew does use both, the tag as well as the head SHA to determine an upstream product. Homebrew's rtags formula originally was referencing the tag 2.13 together with the original SHA. After your retag, the formula broke as the tags HEAD wasn't matching anymore. That appears to be a security feature. I don't think it justifies a new version tag - however it does hint that retagging is a bad idea ;).

**Comment by tillt** [comment]
Ow, thanks for your clarification - much appreciated.

**Comment by tillt** [comment]
Actually, the downstream project maintainer believes other than me - he thinks you should bump the version as it was a bad bug. TBH, I don't care but all I want is stuff to be quickly and easily accessible by me fellow macOS fanboys :).

**Comment by Yevgnen** [comment]
M-x rtags-install <ret> does  not work  any more.

**Comment by novakboskov** [comment]
@Yevgnen Yup, that's because of #1037. Seems that `rtags-install` simply `curl`
https://andersbakken.github.io/rtags-releases/rtags-2.13.tar.bz2 and it's 404.

**Comment by tillt** [comment]
@Yevgnen please don't hijack an entirely unrelated thread.

**Comment by Andersbakken** [comment]
I will bump again. Sorry about all the confusion.

Anders

**Comment by novakboskov** [comment]
@Andersbakken hm... Now https://andersbakken.github.io/rtags-releases/rtags-2.14.tar.bz2 is 404.

**Comment by tillt** [comment]
@Andersbakken thanks a bunch - closing this issue as being outdated now.

**Comment by novakboskov** [comment]
@Andersbakken @tillt but 404 problem is still here.
