### ISSUE TITLE
Warning when compiling company-rtags.el

### ISSUE THREAD

**Issue by JohnC32** [Andersbakken/rtags#1044]
### Please mark appropriate
 - [ ] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [x ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description

This is a minor issue I see in Emacs 24.4.1 when compiling company-rtags.el

   company-rtags.el:284:1:Warning: the following functions are not known to be
        defined: caadr, cadadr

To fix, add the following near top of the file:

    (eval-when-compile
      (require 'cl))

#### Expected behavior

No warnings when byte-compiling company-rtags.el

#### Actual behavior

I see warnings

### Environment
- Your operating system:

Debian 8, Emacs 24.4.1

- LLVM/Clang version:

4.0.1

### Feature request

Describe the feature we should add to **RTags**.

**Comment by Andersbakken** [comment]
Should be fixed now. Thanks.

**Comment by dgutov** [comment]
Why not `(require 'cl-lib)` and use `cl-caadr` and `cl-cadadr` directly?
