### ISSUE TITLE
rc --reindex no longer works

### ISSUE THREAD

**Issue by Nephyrin** [Andersbakken/rtags#1046]
### Please mark appropriate
 - [x] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description
When issuing `rtags-reparse-file` rdm shows the invocation as:
`/usr/bin/rc --current-file=/home/path/to/a/file.cpp -o --silent -b -z --verify-version=124 -V /home/path/to/a/file.cpp`

But no reparse occurs.  Removing --silent and invoking this command yields: `No Matches`

Attempting different variants (relative to project root, no current file, removing other options) I am unable to get it to decide to reparse this file.

However, modifying the file and saving it triggers a reparse.

#### Expected behavior
File is reparsed

#### Actual behavior
`No Match`

### Environment
- Your operating system: Arch Linux x64

- LLVM/Clang version: 4.0.1

**Comment by Andersbakken** [comment]
Oddly this just works for me. Could there be an issue with --sandbox-root
or something like that?

Is the project currently active when you do this? (It's not supposed to be
necessary).

Anders

**Comment by Nephyrin** [comment]
So, after seeing other issues with resolving symbols I ran `rdm -C` and reloaded the project -- now everything seems good again.  I suspect my database was somehow corrupt.

I will re-open this if I find any concrete steps to reproduce - sorry for the noise!
