### ISSUE TITLE
sandbox-root option no longer working

### ISSUE THREAD

**Issue by hhfeng** [Andersbakken/rtags#1047]
### Please mark appropriate
 - [x ] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description
Describe briefly the problem.
rdm --sandbox-root not working because absolute path is saved to db indexed files. 

#### Expected behavior
Describe what you expected to happen.
sandbox-root option should support moving sandbox location without need to re-index source files.
I have filed a pull request #1034, which should fix the sandbox-root regression and also added tests to lock this down. Please review my pull request and incorporate the changes.

#### Actual behavior
Describe what actually happened.
Navigation stops working after moving sandbox location

### Environment
- Your operating system:

- LLVM/Clang version:

### Feature request

Describe the feature we should add to **RTags**.

**Comment by JohnC32** [comment]
The test included with the pull request provides a frame work for extensively testing RTags. Let us know if you'd like to see any changes. I would like to expand what it tests to ensure RTags is well tested once the test is accepted. If you'd like to see changes to the test, can you pull the fixes for now? Thanks
