### ISSUE TITLE
Add customization variable to specify the --config argument to rc

### ISSUE THREAD

**Issue by laynor** [Andersbakken/rtags#1055]
### Please mark appropriate
 - [ ] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [x] rtags.el

### Feature request
RTags tries to parse `$HOME/.rcrc`, which is also used by [RCM](https://github.com/thoughtbot/rcm). It would be great to have a custom variable to specify the path the `rc` config file.

**Comment by Andersbakken** [comment]
Sure thing. You can now set rtags-rc-config-path

**Comment by laynor** [comment]
thanks!
