### ISSUE TITLE
Extreme nit: update README.md to indicate that a rc manpage does exist

### ISSUE THREAD

**Issue by keeyim** [Andersbakken/rtags#1056]
### Please mark appropriate
 - [ ] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description
The Usage section of README.md says the following:

> rc has a vast number of commands and options and we intend to write a man page at some point. 

However there actually is a manpage for rc.

This is really not terribly important, but perhaps the next time someone updates the README they can fix this.

#### Expected behavior
The README should say that a manpage exists.

#### Actual behavior
See above.

### Environment
- Your operating system: Ubuntu 16.04.2 LTS 

- LLVM/Clang version:

### Feature request
n/a

**Comment by Andersbakken** [comment]
:-)

I have now updated it. Thanks
