### ISSUE TITLE
Cmake cannot find rct.cmake or LibClang

### ISSUE THREAD

**Issue by CrosbyD** [Andersbakken/rtags#1057]
### Please mark appropriate
 - [X] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description
I am trying to build rtags on CentOS from the release archive. When I use ./configure --release I get this error:

    CMake Error at src/CMakeLists.txt:107 (include):
    include could not find load file:

       rct/rct.cmake

    -- 
    -- The following OPTIONAL packages have been found:

     * PkgConfig , helper tool , <https://www.freedesktop.org/wiki/Software/pkg-config/>
       We use it to get the bash completion installation path, and replace the prefix with the value of 
    CMAKE_INSTALL_PREFIX.

    -- The following REQUIRED packages have been found:

     * LibClang

     -- Configuring incomplete, errors occurred!
    See also "/home/USER/rtags-2.14/CMakeFiles/CMakeOutput.log".
    See also "/home/USER/rtags-2.14/CMakeFiles/CMakeError.log".

#### Expected behavior
I would have hoped that because I installed clang and llvm-devel that this should just find the necessary libraries on my system.

#### Actual behavior
The cmake should have compiled and made a makefile

### Environment
- Your operating system:
CentOS Linux release 7.3.1611 (Core) 
- LLVM/Clang version:
clang version 3.4.2 (tags/RELEASE_34/dot2-final)
llvm 3.4.2
### Feature request
NA
Describe the feature we should add to **RTags**.

**Comment by Necktwi** [comment]
i'm having same issue, how did you fix it? can you elaborate?

**Comment by Necktwi** [comment]
oh ok i too forgot git --recursive
