### ISSUE TITLE
100% CPU utilization with rtags

### ISSUE THREAD

**Issue by thisEric** [Andersbakken/rtags#1059]
### Please mark appropriate
 - [x] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [x] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description
When I enabled rtags for c++ development, I found the whole emacs is very slow. with "top" command, I found there are 8 rp processes, each one take 100% of the CPU. My computer has 8 cores, all are token by rtags, If I disable rtags, everything will become smooth.

I tried with M-: (setq rtags-diagnostics-suspended t), but it won't help.
Is there any config to limit the CPU usage by rtags?

**Comment by Andersbakken** [comment]
Hi

By default rtags will spawn the same number of indexing jobs that as there
are cores. You can run rdm like this:

rdm -j 4

to run with 4 cores.

Anders

**Comment by thisEric** [comment]
thanks, Anders, will try it.
btw, currently I didn't start rdm manually, but using following config:
(rtags-start-process-unless-running)

**Comment by thisEric** [comment]
it works, thanks Anders
