### ISSUE TITLE
Latest master does not build on Ubuntu 14.04

### ISSUE THREAD

**Issue by fagg** [Andersbakken/rtags#1060]
### Please mark appropriate
 - [X] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description

Does not build on Ubuntu 14.04. I pulled the latest master from here, have tried a number of different suggestions from reading the issue tracker here but no avail. The build error log is attached.
[build_errors.txt](https://github.com/Andersbakken/rtags/files/1306816/build_errors.txt)

Did the usual submodule init and update, no help.

#### Expected behavior

rtags should build

#### Actual behavior

But it doesn't.

### Environment
- Your operating system:

Linux 4.4.0-93-generic #116~14.04.1-Ubuntu SMP Mon Aug 14 16:07:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- LLVM/Clang version:

clang --version
clang version 3.8.0 (tags/RELEASE_380/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/clang+llvm-3.8.0/bin

### Feature request

Describe the feature we should add to **RTags**.

**Comment by Andersbakken** [comment]
Sorry about the long delay. Should be fixed now.
