### ISSUE TITLE
Feature Request: Find all instances of where a function is called

### ISSUE THREAD

**Issue by robert-snakard** [Andersbakken/rtags#1061]
### Please mark appropriate
 - [x] rtags (rdm/rc/rp)

### Feature Request
Currently you can navigate to a function definition from where a function is called. I want to get a list of places a function is called from the function definition.

#### Expected behavior
When the command is executed a new window opens with a list of all instances of that function being called

**Comment by acowley** [comment]
Is what you want different from the existing `rtags-find-references`?

**Comment by Andersbakken** [comment]
That does indeed sound like rtags-find-references (or rtags-find-references-tree). Are you able to try that out and see if it does what you want?

**Comment by robert-snakard** [comment]
It is, I was just being done
