### ISSUE TITLE
Unable to generate build files for rtags

### ISSUE THREAD

**Issue by samaursa** [Andersbakken/rtags#1064]
### Please mark appropriate
 - [X] rtags (rdm/rc/rp)

### Problem description
Spent a couple of days trying to solve the problem on my own but finally thought to open a new issue here.

I am unable to run `CMake` on `rtags` as I get the following error:
![image](https://user-images.githubusercontent.com/817849/30836276-1e0684a0-a22b-11e7-8d23-08d9af1ef9e9.png)

I made sure that I have `libclang-dev` package and `clang` installed. It seems that `check_cxx_source_compiles` fails to compile the basic test set our in the `src/CMakeLists.txt` file.

Any help would be appreciated.

#### Expected behavior
`CMake` to generate project files so that I can build `rtags`.

#### Actual behavior
I get the following error:
```
CMake Error at src/CMakeLists.txt:84 (message):
  We can't seem to compile a small clang test app.  Maybe you need to install
  the libclang dev package?
```

### Environment
- Your operating system: Linux Mint 18.2

- LLVM/Clang version: 3.8.0

**Comment by Andersbakken** [comment]
Do you have llvm-config in your path? Note also that if you first ran cmake, then installed libclang-dev, rerunning cmake is not enough. You need to blow away CMakeCache.txt manually and the rerun cmake.

**Comment by Andersbakken** [comment]
If that still doesn't work, can you post the contents of CMakeFiles/CMakeError.log

**Comment by samaursa** [comment]
You were absolutely right. Deleting `CMakeCache.txt` did the trick. Thank you!

**Comment by Andersbakken** [comment]
My pleasure. It's kind of an annoying thing with cmake.

Anders
