### ISSUE TITLE
Error after commit e5bca1d 

### ISSUE THREAD

**Issue by bradprob** [Andersbakken/rtags#1065]
### Please mark appropriate
 - [x] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [x] company-rtags.el
   - [x] helm-rtags.el
   - [x] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [x] rtags.el

### Problem description
After upgrading the server(rdm) and the emacs package the result-display has been broken and produces the command that is executed in the background. 

For example:
Publisher publisher();
publisher.

#### Expected behavior
A list of publisher's public elements.

#### Actual behavior
The following is produced in the minibuffer and rdm seems to be killed:
clang failed with error 1:
/usr/bin/clang -fsyntax-only -Xclang -code-completion-macros -x c -DDEBUG -I/home/xxx/Documents/include -I/home/xxx/Documents/projects/project/include -I/home/xxx/Documents/projects/project/lib/include -I/home/xxx/Documents/projects/project/src -std=c++14 -w -Wall -lboost_system -lboost_thread -lrt -ldl -lcrypto -lssl -lmsgpackc -lzmq -lpthread -lboost_program_options -o CMakeFiles/project-dir/src/source.cpp.o -Xclang -code-completion-at=-:29:9 -

Executing the the produced command in bash from the source directory, generates this output: 
error: invalid argument '-std=c++14' not allowed with 'C/ObjC'  

### Environment
- Your operating system:
Linux debian 4.12.0-2-amd64 #1 SMP Debian 4.12.13-1 (2017-09-19) x86_64 GNU/Linux

- LLVM/Clang version:
clang version 3.8.1-24 (tags/RELEASE_381/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

**Comment by myrgy** [comment]
is it header file?
if yes - you need to enable c++ mode for .h files.
you can do it with:
``` (add-to-list 'auto-mode-alist '("\\.h\\'" . c++-mode)) ```

**Comment by bradprob** [comment]
It is indeed a header file, thought the suggested solution has not helped.
I am wondering whay I did not have any problems until last update of rdm and emacs' rtags package.

**Comment by myrgy** [comment]
still, seems that in you emacs you are trying to use company-clang.
there is a ```/usr/bin/clang .... -x c ...``` parameter, which force C language, 
so compiler complains  ```that error: invalid argument '-std=c++14' not allowed with 'C/ObjC'```

**Comment by bradprob** [comment]
I have not changed my emacs configurations. If I am not mistaken clang is used by company-rtags self and I am not setting the options passed to it.

**Comment by myrgy** [comment]
as far as I know - rtags use clang on server (daemon), on the other hand client (rc) which is integrated into emacs using different modules are quire stupid and don't print errors like that.
To be able to see rim logs you need to start it manually or using rc in special mode.

It looks like you error message was printed by some other module - on my home machine after modules update I see something similar from company-clang (in header file, event with c++ mode).
to be sure - please try to check if you have ` *clang-error*` or `*clang-output*` buffers. If yes - then I think this issue is not related with rtags.

**Comment by bradprob** [comment]
Forcing emacs to open .h files in c++ mode results in the same error:
clang failed with error 1:
/usr/bin/clang -fsyntax-only -Xclang -code-completion-macros -x c++ -DDEBUG -I/home/user/Documents/include -I/home/user/Documents/projects/project/include -I/home/user/Documents/projects/project/lib/include -I/home/user/Documents/projects/project/src -std=c++14 -w -Wall -lboost_system -lboost_thread -lrt -ldl -lcrypto -lssl -lmsgpackc -lzmq -lpthread -lboost_program_options -o CMakeFiles/project.dir/src/xxx.cpp.o -Xclang -code-completion-at=-:24:43 -

**Comment by myrgy** [comment]
do you use spacemacs? because I have exactly the same issue :(

**Comment by bradprob** [comment]
No, emacs 25.2.2 modified by Debian

**Comment by myrgy** [comment]
what about clang?
``` 
/usr/bin/clang --version
clang version 4.0.1 (tags/RELEASE_401/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by bradprob** [comment]
In my first post you see my system info.

**Comment by cslux** [comment]
@bradprob Is this issue still valid?

**Comment by cslux** [comment]
> /usr/bin/clang -fsyntax-only -Xclang -code-completion-macros -x c -DDEBUG -I/home/xxx/Documents/include -I/home/xxx/Documents/projects/project/include -I/home/xxx/Documents/projects/project/lib/include -I/home/xxx/Documents/projects/project/src -std=c++14 -w -Wall -lboost_system -lboost_thread -lrt -ldl -lcrypto -lssl -lmsgpackc -lzmq -lpthread -lboost_program_options -o CMakeFiles/project-dir/src/source.cpp.o -Xclang -code-completion-at=-:29:9 -

You are using `company-clang` for code completion! Please adjust `company-backends`, and try again.

E.g.
``` emacs-lisp
(add-to-list 'company-backends 'company-rtags)
```

You might add `company-rtags` only to this list when in `c-mode, `c++-mode`, ...

Closing this issue.
