### ISSUE TITLE
Rdm fails to find files included using relative paths to include dir

### ISSUE THREAD

**Issue by clearmisp** [Andersbakken/rtags#1068]
### Please mark appropriate
 - [ x] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ x] company-rtags.el
   - [ x] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ x] rtags.el

### Problem description
We have relative include paths (on the form -I../include_dir) mixed with absolute paths in our Makefiles. I generate a compile_commands.json using bear and feed it to rdm using rc -J. The compile_commands.json will also contain these relative include paths. When rdm start indexing it takes a very long time completing and when I examine the rdm log inside Emacs it shows that rdm outputs an error on all files included from these relative paths.

In the rdm log file I see that the relative include paths have been transformed into absolute paths by appending the current directory so they now have the form -I/path/to/dir/../include_dir.

When I run the corresponding clang command using the input shown in the rdm log it executes without any errors.

If I "clean" all the relative include paths in the compile_commands.json and transform them into absolute paths and them feed them to rdm using rc -J everything works fine.

#### Expected behavior
rdm should not output an error when the include path is relative, the included file should be found.

#### Actual behavior
rdm fails to find files included using relative paths.

### Environment
openSUSE Leap 42.3

- LLVM/Clang version:
3.8.0

**Comment by clearmisp** [comment]
I updated both Emacs and rtags (using git), recompiled rtags and tried again. It seems to work well with the latest version of rtags (both elisp and c++ parts.) I think we can close this.

**Comment by fd3kyt** [comment]
Works for me. Need to do a `rc --clear` after updating.
