### ISSUE TITLE
rtags-find-symbol-at-point finds symbol in installed file instead of source 

### ISSUE THREAD

**Issue by ramestica** [Andersbakken/rtags#1074]
### Please mark appropriate
 - [ x] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ x] rtags.el

### Problem description
in my environment I have a MODROOT directory with C/C++ source code files and Makefiles. And INTROOT where individual Makefiles through MODROOT install binaries and C/C++ header files. rtags-find-symbol-at-point  takes me to right place in the source code. But it is always a header file in INTROOT.

#### Expected behavior
I would expect rtags to index files in MODROOT and never files I install from MODROOT into INTROOT (e.g. header files)

#### Actual behavior
I'm assuming that if files in INTROOT are not indexed, then, rtags-find-symbol-at-point will take me to a source code file in MODROOT.

### Environment
- Linux, gcc toolchain for compiling my project in MODROOT.
- LLVM/Clang version: 3.8

**Comment by Andersbakken** [comment]
I'm assuming the include path for the source file points at introot. clang
will resolve symbols to the header it used during compilation. This is most
likely the reason.

Anders

**Comment by ramestica** [comment]
I see! That makes sense. From that perspective, a valid one, my expectation is just not possible. 

It occurs to me now that I could elisp a function to take me from an INTROOT header file to its original under MODROOT, if it exists at all. I could eventually advice rtags-find-symbol-at-point to do that automatically. Maybe. 

Many thanks for the clarification.
