### ISSUE TITLE
rtags mFileMapScope

### ISSUE THREAD

**Issue by ClintLiddick** [Andersbakken/rtags#1075]
### Please mark appropriate
 - [x] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [x] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [x] rtags.el

### Problem description

`rdm` crashes when completing for an edited file.

Run with 

```gdb --args rdm -v -X "*/third_party/*"```

```
/usr/local/bin/rc --current-file=/home/clint/PROJECT/LIBRARY/backend/REDACTED.hh --silent-query -z --verify-version=124 -T /home/clint/PROJECT/LIBRARY/backend/REDACTED.hh
Query opened 4 files for project /home/clint/.cache/bazel/_bazel_clint/5ba37c15a9f304d4366f43e496507871/
/usr/local/bin/rc --current-file=/home/clint/PROJECT/LIBRARY/backend/REDACTED.hh --unsaved-file=/home/clint/PROJECT/LIBRARY/backend/REDACTED.hh:7051 -z --verify-version=124 --code-complete-at /home/clint/PROJECT/LIBRARY/backend/REDACTED.hh:95:61: --synchronous-completions --elisp --code-complete-prefix=TRAC
Processed /home/clint/PROJECT/LIBRARY/backend/REDACTED.hh:95:61:, parse 1502/82, complete 30, process 32 => 0 completions (unsaved 7049)
rdm: ../src/Project.h:107: std::shared_ptr<FileMap<Location, Symbol> > Project::openSymbols(uint32_t, String*): Assertion `mFileMapScope' failed.

Thread 4 "rdm" received signal SIGABRT, Aborted.
```

#### Expected behavior

Does not crash. May return no completion.

#### Actual behavior

Crashes with signal 11 in release build, crashes with assertion abort in debug build.

### Environment
- Your operating system: Ubuntu 16.04.3 LTS

- LLVM/Clang version: 3.8.0

- Compiler: g++ 5.4.0

- Build tool: bazel

### Feature request

Please help me understand what might cause this crash and:
- provide fix
- provide steps to resolve myself
- suggest steps to work around
- clarify reason my setup cannot work

**Comment by ClintLiddick** [comment]
Switched to 2.14 tag build and haven't seen this issue yet.

**Comment by Andersbakken** [comment]
Sounds good. Not sure why this one would happen. Note that running rtags in
debug is substantially slower than release. Since you hit this assertion
I'm assuming it's a debug build.

Anders

**Comment by collinjackson93** [comment]
This appears to be the same issue as #1071, which I have been able to reproduce with version 2.14.120 (commit b7e7816).

**Comment by collinjackson93** [comment]
@ClintLiddick I believe this was recently fixed. Can you verify that you are no longer able to reproduce with the latest version?
