### ISSUE TITLE
rdm crash

### ISSUE THREAD

**Issue by solotim** [Andersbakken/rtags#1076]
### Please mark appropriate
 - [x] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [x] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description
Have installed rtags on spacemacs roughly based on https://skebanga.github.io/rtags-with-cmake-in-spacemacs/

There are loading issue when start spacemacs:

`(Spacemacs) Warning: package helm-rtags not initialized in layer mineo-rtags, you may consider removing this package from the package list or use the :toggle keyword instead of a 'when' form.`

rdm crashes when I try to call rtags-find-references-at-point for test:

`rdm: /remote/us01home38/thierryl/db/src/llvm/llvm/tools/clang/lib/Frontend/CompilerInstance.cpp:65: virtual clang::CompilerInstance::~CompilerInstance(): Assertion 'OutputFiles.empty() && "Still output files in flight?"' failed.
Caught signal 6
rdm[0x45a0ca]
/lib64/libpthread.so.0(+0xf710)[0x7f1717749710]
/lib64/libc.so.6(gsignal+0x35)[0x7f1716539625]
/lib64/libc.so.6(abort+0x175)[0x7f171653ae05]
/lib64/libc.so.6(+0x2b74e)[0x7f171653274e]
/lib64/libc.so.6(__assert_perror_fail+0x0)[0x7f1716532810]
/depotbld/RHEL6.0/llvm-3.9.1/lib/libclang.so.3.9(+0x8ac144)[0x7f1718584144]
/depotbld/RHEL6.0/llvm-3.9.1/lib/libclang.so.3.9(+0x8ac2ee)[0x7f17185842ee]
/depotbld/RHEL6.0/llvm-3.9.1/lib/libclang.so.3.9(+0x8abc6e)[0x7f1718583c6e]
/depotbld/RHEL6.0/llvm-3.9.1/lib/libclang.so.3.9(+0x2996875)[0x7f171a66e875]
/depotbld/RHEL6.0/llvm-3.9.1/lib/libclang.so.3.9(clang_parseTranslationUnit2FullArgv+0x477)[0x7f17180d0ea2]
/depotbld/RHEL6.0/llvm-3.9.1/lib/libclang.so.3.9(clang_parseTranslationUnit2+0xe0)[0x7f17180d098a]
rdm(_ZN5RTags15TranslationUnit6createERK4PathRK4ListI6StringEP13CXUnsavedFilei5FlagsI23CXTranslationUnit_FlagsEb+0x62a)[0x469d1a]
rdm(_ZN16CompletionThread7processEPNS_7RequestE+0x1cea)[0x56d2ea]
rdm(_ZN16CompletionThread3runEv+0x1229)[0x56fdc9]
rdm(_ZN6Thread10localStartEPv+0x25)[0x51f135]
/lib64/libpthread.so.0(+0x79d1)[0x7f17177419d1]
/lib64/libc.so.6(clone+0x6d)[0x7f17165ef8fd]
`

#### Expected behavior
Describe what you expected to happen.

#### Actual behavior
Describe what actually happened.

### Environment
- Your operating system:
REDHAT linux 6.5
- LLVM/Clang version:
3.9.1
### Feature request

Describe the feature we should add to **RTags**.

**Comment by Andersbakken** [comment]
I'm not sure what the mineo-rtags thing is about. I think this is an issue in the spacemacs integration. As for the crash it's actually a bit of a known bug. clang has tons of assertions that we trigger but that seems to be mostly innocuous. You have to compile clang without assertions enabled to avoid them.

**Comment by Red-Portal** [comment]
@Andersbakken by compiling clang without assertions, do you mean in Release mode? Or is there a specific option for what you mean? Can you specify?

**Comment by Andersbakken** [comment]
Yeah. They can also be enabled/disabled separately doing this I think:

cmake ... -DLLVM_ENABLE_ASSERTIONS=0

Anders

**Comment by Andersbakken** [comment]
Also make sure to blow away your CMakeCache.txt since these kinds of
variables often times are overly sticky in cmake.

Anders

**Comment by solotim** [comment]
Guys, thanks for the responds. I turned to a llvm 5.0 build (perhaps no assertion), and rtags now works like a charm. close this issue.
