### ISSUE TITLE
Lisp error in rtags.el

### ISSUE THREAD

**Issue by leopoldfreeman** [Andersbakken/rtags#1077]
### Please mark appropriate
 - [x] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [x] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [x] rtags.el

### Problem description
Lisp compile error.

#### Expected behavior
No error

#### Actual behavior
In rtags--get-rename-data:
rtags.el:2721:65:Error: ‘add-to-list’ can’t use lexical var ‘result’; use ‘push’ or ‘cl-pushnew’

### Environment
- macOS 10.13
- Emacs 25.3.1
- MELPA rtags-20171023.816
- LLVM/Clang version:
5.0.0

**Comment by Andersbakken** [comment]
Should be fixed now. Sorry about that one.
