### ISSUE TITLE
*Ivy* backend stopped working with emacs-26.0.90 (pretest)

### ISSUE THREAD

**Issue by wrachwal** [Andersbakken/rtags#1079]
### Please mark appropriate
 - [ ] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [X] ivy-rtags.el
   - [X] rtags.el

### Problem description

When I switched from `emacs 25.3` to `emacs 26.0.90 (pretest)` Ivy backend in RTags stopped working completely. The effect is such that the default behavior with *RTags* buffer is always chosen.

I use package system, so .el files are normally byte-compiled. Because `rtags.el` compiled with warnings, so in the first step I removed `rtags.elc` file, and... Ivy appeared!

Next I compiled manually `rtags.el` but using `emacs 25.3` version and with such `.elc` Ivy backend works as well.

Because size of `.elc` has changed, out of curiosity I checked the opposite: `emacs 25.3` with `.elc` generated by `emacs 26` - but such combination ends with runtime error _"Invalid byte opcode: op=183, ptr=110"_ which behavior is however expected (Emacs cannot guarantee old versions to run with newer opcodes).

I don't know where the culprit is... maybe `rtags.el` code is fragile (bear in mind compile-time warnings) when executing newer opcodes something goes wrong? I checked that both versions produce the same set of warnings for `rtags.el`. I tried to reorganize code a bit to eliminate warnings but gave up. No suspicious messages found in *Message* during runtime at times when Ivy backend did't work. Ivy itself, e.g. `M-x ivy-switch-buffer` and friends work without any problems.

### Environment
- Ubuntu 16.04.3
- both emacs versions compiled from sources with the same set of switches
- when running emacs (as editor), for each emacs version I used its own set of elpa/ directory.

For experiments I used extracted `~/.emacs` (as below) from my regular more complex `~/.emacs.d/init.el`. RTags command to trigger Ivy was `M-x rtags-find-references-at-point`.

```emacs-lisp
(require 'package)
(setq package-enable-at-startup nil)
(setq package-archives
      '(("org"   . "http://orgmode.org/elpa/")
        ("gnu"   . "http://elpa.gnu.org/packages/")
        ("melpa" . "https://melpa.org/packages/")))
(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(eval-when-compile
  (require 'use-package))

(require 'cl)
(require 'rtags)
(setq rtags-display-result-backend 'ivy)
(require 'ivy-rtags)

; rtags-find-references-at-point
```

**Comment by cslux** [comment]
Works for me with Emacs 26.1.5. Did you byte-compiled all rtags elisp files again with the new Emacs version? 

But more importantly, did you already resolve it your self?

If it still does not work, do not hesitate to reopen this issue.

Thanks!
Christian
