### ISSUE TITLE
Make rtags-find-symbol-at-point open a buffer in a different window

### ISSUE THREAD

**Issue by clearmisp** [Andersbakken/rtags#1080]
### Please mark appropriate
 - [ x] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ x] company-rtags.el
   - [ x] helm-rtags.el
   - [ x] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ x] rtags.el

### Feature request
Is it possible to get rtags-find-symbol-at-point to open a buffer in a different window (like find-file-other-window does)?

**Comment by Andersbakken** [comment]
It is indeed. 

If you invoke it with a listp prefix it should do that.

E.g. C-u C-x r .

or

 (define-key (kbd ...) (lambda () (rtags-find-symbol-at-point (list 1))))

I think that should do what you want.

Anders
