### ISSUE TITLE
Thank you for rtags

### ISSUE THREAD

**Issue by jlargentaye** [Andersbakken/rtags#1088]
This is not an issue. I just wanted to express my gratefulness for rtags.

I've been using RTags for a bit over a year now, and it's been immensely useful to me. I work on a large C codebase for embedded targets, with many #ifdef'd blocks and multiple definitions depending on the target. Over the years I've tried Gtags, GNU idutils, and cscope, and all have stumbled on the hurdle of multiple definitions with awkward UIs (if any) to jump through possible definitions.

While it's not always perfect (and I mostly blame the C ecosystem for the warts, really), RTags is the best tool yet. It's very reliable in getting the right definition of functions and the right call locations, as appropriate for my current target.

I especially appreciate the first-class support of Emacs, my editor of choice. But RTags' client-server design guarantees that even if Emacs falls by the wayside, there'll still be other options.

So thanks again for the contributors work!

Does @Andersbakken have a Patreon/Paypal? I'd like to put some money where my mouth is :)

**Comment by Andersbakken** [comment]
Hi

I really appreciate that RTags is useful to you. It was borne out of me having had these same long-held frustrations with the tooling, especially when compared the IDEs like eclipse, Visual Studio, Qt Creator and such. 

I'm not really looking for contributions at this point but your comments are much appreciated.

Thanks

Anders
