### ISSUE TITLE
Completion fails, sometimes

### ISSUE THREAD

**Issue by redm123** [Andersbakken/rtags#1103]
### Please mark appropriate
 - [x] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description
I try to complete e.g. variables in Emacs, but often only get `No completion found`.
In general completions are working for me, somewhat, however often somewhat flaky.

When I look at the rdm output it says:

    /usr/local/stow/rtags/bin/rc --current-file=/devel/git/myrepo/MyFile.cpp --silent-query -b -z --verify-version=124 -T /devel/git/myrepo/MyFile.cpp
    Prepared /devel/git/myrepo/MyFile.cpp
    Query opened 4 files for project /devel/git/myrepo/
    /usr/local/stow/rtags/bin/rc --current-file=/devel/git/myrepo/MyFile.cpp -b -z --verify-version=124 --code-complete-at /devel/git/myrepo/MyFile.cpp:72:1: --synchronous-completions --elisp --code-complete-prefix=m_c
    Processed MyFile.cpp:72:1:, parse 0/0, complete 52, process 66 => 0 completions (unsaved 0)

Does `0 completions` mean that there were no completions found?

Strange thing is: at some point, somehow the same completion starts working (maybe if I properly indent first, and save the file). And then pretty reliable. However if I was completing a member variable and I go to another member function in the same class, and try to complete the same member variable again: it doesn't work again. I couldn't really find a pattern until now.

Even if it works I get `0 completions`:

    Processed MyFile.cpp:175:5:, parse 0/0, complete 67, process 94 => 0 completions (unsaved 13504)

What does this mean?

I use the company backend for completion.

#### Expected behavior
Reliably complete.

#### Actual behavior
Sometimes completes, sometimes not.

### Environment
- Your operating system:
Linux Ubuntu 14.04
Emacs 24.3

- LLVM/Clang version: 3.8

### Feature request

Describe the feature we should add to **RTags**.

**Comment by redm123** [comment]
I did some more investigation on that. One thing I found is some weird behavior with regard to indentation:
if I indent 6 or less spaces, completion does not work
if I indent 7 or more spaces, completion works

```
class Foo
{
  void foo(int connection);
};

void Foo::foo(int connection)
{
      connect    // fails to complete (6 spaces)
       connect   // completes fine (7 spaces)
}

```

RDM says:
```

fail:
/usr/local/stow/rtags/bin/rc --current-file=/devel/git/myrepo/MyFile.cpp --silent-query -b -z --verify-version=124 -T /devel/git/myrepo/MyFile.cpp
Query opened 4 files for project /devel/git/myrepo/
/usr/local/stow/rtags/bin/rc --current-file=/devel/git/myrepo/MyFile.cpp -b --unsaved-file=/devel/git/myrepo/MyFile.cpp:13521 -z --verify-version=124 --code-complete-at /devel/git/myrepo/MyFile.cpp:135:7: --synchronous-completions --elisp --code-complete-prefix=connect
Processed MyFile.cpp:135:7:, parse 0/0, complete 58, process 74 => 0 completions (unsaved 13521)
Query opened 0 files for project /devel/git/myrepo/


work: (indented just one more space)
/usr/local/stow/rtags/bin/rc --current-file=/devel/git/myrepo/MyFile.cpp --silent-query -b -z --verify-version=124 -T /devel/git/myrepo/MyFile.cpp
Query opened 4 files for project /devel/git/myrepo/
/usr/local/stow/rtags/bin/rc --current-file=/devel/git/myrepo/MyFile.cpp -b --unsaved-file=/devel/git/myrepo/MyFile.cpp:13522 -z --verify-version=124 --code-complete-at /devel/git/myrepo/MyFile.cpp:135:8: --synchronous-completions --elisp --code-complete-prefix=connect
Processed MyFile.cpp:135:8:, parse 0/0, complete 66, process 91 => 0 completions (unsaved 13522)
Query opened 0 files for project /devel/git/myrepo/
```



I stripped down my .emacs to only rtags and company initialization:

```
(setq load-path (append (list nil
                             "/usr/local/stow/rtags/share/emacs/site-lisp/rtags/")
                              load-path))
(setq rtags-path "/usr/local/stow/rtags/")
(require 'rtags)
(require 'company-rtags)

(rtags-enable-standard-keybindings)
(setq rtags-autostart-diagnostics t)
(rtags-diagnostics)
(setq rtags-completions-enabled t)
(setq company-async-timeout 10)

;; Setup company mode
(autoload 'company-mode "company" nil t)
(company-mode)
(global-company-mode 1)
(add-to-list 'company-backends 'company-rtags)

(add-hook 'c++-mode-hook
         '(lambda nil
      (define-key c++-mode-map "\C-i" 'company-complete-common)))

```

**Comment by myrgy** [comment]
since version 2.17 completion works much better.

**Comment by redm123** [comment]
I just did a git update rtags, rescanned the project... but it seems even worse, I can't get anything to complete :(

**Comment by cslux** [comment]
#1123

**Comment by redm123** [comment]
I cannot confirm this. Just compiled a new rtags from Git and it still often fails to complete.

It seems to work pretty reliable when completing after a "." or "->" (although it seems to list private members now...). But other cases still only work sometimes. 
I just tried to complete a local variable after the first few chars, didn't work. Completing a vector "foo.push_b_" (2nd _ is the cursor), "No completions found" ...
Sometimes completion works if I indent 7, 10, 20 .. characters.

**Comment by redm123** [comment]
You closed this a duplicate... do you think it is? If I look at the referenced issue, it seems to be about timeouts... I don't see timeouts (usually), but it still does not really work.
