### ISSUE TITLE
Another core dump in 2.16

### ISSUE THREAD

**Issue by cohomology** [Andersbakken/rtags#1104]
After the other core dump is gone, 2.16 now shows another one

(_ZNSt10_HashtableIjSt4pairIKjSt10shared_ptrI7FileMapI6String3SetI8LocationEEEESaISA_ENSt8__detail10_Select1stESt8equal_toIjESt4hashIjENSC_18_Mod_range_hashingENSC_20_Default_ranged_hashENSC_20_Prime_rehash_policyENSC_17_Hashtable_traitsILb0ELb0ELb1EEEE4findERS1_+0x4)[0x563c51bc40d4]
rdm(+0x1c83a1)[0x563c51baa3a1]
rdm(_ZN7Project9findByUsrERK6StringjNS_14DependencyModeE+0xf9)[0x563c51badc99]
rdm(_ZN7Project11findTargetsERK6Symbol+0x133)[0x563c51bae573]
rdm(_ZN17FollowLocationJob7executeEv+0x8bd)[0x563c51b6bddd]
rdm(_ZN8QueryJob3runERKSt10shared_ptrI10ConnectionE+0x3a)[0x563c51bcf05a]
rdm(_ZN6Server14followLocationERKSt10shared_ptrI12QueryMessageERKS0_I10ConnectionE+0x13c)[0x563c51a73dec]
rdm(_ZN6Server18handleQueryMessageERKSt10shared_ptrI12QueryMessageERKS0_I10ConnectionE+0x2f6)[0x563c51a7d2a6]
rdm(_ZN6Server12onNewMessageERKSt10shared_ptrI7MessageERKS0_I10ConnectionE+0x216)[0x563c51a7d686]
rdm(_ZN10Connection15onDataAvailableERKSt10shared_ptrI12SocketClientEO6Buffer+0x597)[0x563c51adf367]
rdm(_ZN12SocketClient14socketCallbackEii+0x1b1b)[0x563c51b0139b]
rdm(_ZN9EventLoop10fireSocketEij+0x124)[0x563c51ae8014]
rdm(_ZN9EventLoop19processSocketEventsEP11epoll_eventi+0x85)[0x563c51ae8e45]
rdm(_ZN9EventLoop4execEi+0x7b1)[0x563c51aea8c1]
rdm(main+0x26dd)[0x563c51a40ffd]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1)[0x7fe1beaa12b1]
rdm(_start+0x2a)[0x563c51a4315a]

**Comment by cohomology** [comment]
Really, the last known good version is 2.13 ...

**Comment by collinjackson93** [comment]
I've been running 2.16 for a couple of days without any crashes. Can you try running in debug mode to get a better stack trace or provide steps to reproduce?
