### ISSUE TITLE
llvm-config --system-libs not used

### ISSUE THREAD

**Issue by martincmartin** [Andersbakken/rtags#1105]
### Please mark appropriate
 - [X] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description
cmake fails with:

`We can't seem to compile a small clang test app.`

The problem is a missing `-lpthread` on the link line.  `llvm-config --system-libs` correctly reports needing `-lpthread`, so simply appending the value of that should be fine.

If I comment out this test, everything else works fine: the final install RTags works well.  Not sure why `rdm` and friends compile & run fine, while the test app fails to link.

#### Expected behavior
The test app is linked against `-lpthread`, i.e. against libraries reported by `llvm-config --system-libs`.

#### Actual behavior
cmake fails with:

`We can't seem to compile a small clang test app.`

### Environment
- Your operating system:
    CentOS

- LLVM/Clang version:
    From Github on Dec. 1, 2017.  This has been failing since the test was introduced in 2.11.

**Comment by martincmartin** [comment]
Confirmed that the following patch causes the test program to compile.  Obviously, this isn't the real solution.
```
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index ff4f11f..963342a 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -84,7 +84,7 @@ int main()
     set(CMAKE_OLD_REQUIRED_FLAGS ${CMAKE_REQUIRED_FLAGS})
     set(CMAKE_OLD_REQUIRED_LIBRARIES ${CMAKE_REQUIRED_LIBRARIES})
     set(CMAKE_REQUIRED_FLAGS ${CMAKE_REQUIRED_FLAGS} ${CMAKE_CXX_FLAGS} ${LIBCLANG_CXXFLAGS})
-    set(CMAKE_REQUIRED_LIBRARIES ${CMAKE_REQUIRED_LIBRARIES} ${LIBCLANG_LIBRARIES})
+    set(CMAKE_REQUIRED_LIBRARIES ${CMAKE_REQUIRED_LIBRARIES} ${LIBCLANG_LIBRARIES} "-lpthread")
     check_cxx_source_compiles("${LIBCLANG_COMPILE_TEST}" LIBCLANG_COMPILES)
     if (NOT LIBCLANG_COMPILES)
         message(FATAL_ERROR "We can't seem to compile a small clang test app. Maybe you need to install the libclang dev package?")
```

**Comment by cslux** [comment]
Can't reproduce this on CentOS 7! Does it still happen? If yes, what CentOS version do you have?
