### ISSUE TITLE
rdm locked at 100% cpu not answering

### ISSUE THREAD

**Issue by Percee** [Andersbakken/rtags#1109]
### Please mark appropriate
 - [x] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [x] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description
Rtags never responds to a query and hangs up forever at 100%, until I kill it. The project is big, the tags dir is 2,7G.

#### Expected behavior
I'd expect rc to return eventually, or rdm to stop using 100% cpu.

#### Actual behavior
When running `company-complete` with rtags backend, it will timeout "Company: backend (company-rtags) async timeout with args (candidates ASFSrvcIn)". But after that if I open the `top` command, the rdm process uses 100% cpu and doesn't stop until I kill.

When I start a query from the terminal with `rc`, it will hang forever, using 100% cpu.

rtags-find-reference-at-point and rtags-find-symbol-at-point work perfectly and quite fast tho.

### Environment
- Your operating system: Ubuntu 16.04.1

- LLVM/Clang version: llvm-4.0

**Comment by sg-sp** [comment]
This was the same symptom as I had. PR #1106 resolved it for me.

**Comment by Percee** [comment]
Thanks, I'll try that out tomorrow.

Can I ask how you tracked down this issue?

**Comment by sg-sp** [comment]
I sampled the rdm process while it was stuck, and found that it spent its time somewhere in StringTokenizer::find_and_sort_matches. From there it wasn't too hard figuring out where the issue was.

**Comment by Percee** [comment]
It works perfectly, thanks!
