### ISSUE TITLE
fsevent error

### ISSUE THREAD

**Issue by leopoldfreeman** [Andersbakken/rtags#1111]
### Please mark appropriate
 - [x] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [x] rtags.el

### Problem description
When I run rdm: 'rdm --daemon', it shows:
2017-12-07 13:52 rdm[2722] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)

### Environment
- macOS 10.13.2
- rtags: git commit 324f256acfdac2582c684e757078b1ca73ba28ec

- LLVM/Clang version:
5.0.0

**Comment by cahlbin** [comment]
I'm having the same issue. 

**Environment**

* macOS 10.13.2 (17C205)
* rtags: git commit 53e74892e8bd15baa4d1bd1d640dcabcba9667ee
* LLVM/clang version: 5.0.1 (installed via homebrew)

**Comment by leopoldfreeman** [comment]
I don't have the problem any more. Close the issue.

macOS 10.13.13
