### ISSUE TITLE
Multiple rc processes spawned and never finished

### ISSUE THREAD

**Issue by Satius** [Andersbakken/rtags#1112]
### Please mark appropriate
 - [x] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description
On every completion attempt, rc process is spawned which then locks-up. Completion does not work.

#### Expected behavior
Completion works.

#### Actual behavior
Whenever completion is triggered, a new rc process is created, which never finishes:
```
24806 pts/1    00:00:00 rc
24818 pts/2    00:00:00 rc
24822 pts/3    00:00:00 rc
24826 pts/4    00:00:00 rc
24836 pts/5    00:00:00 rc
24845 pts/6    00:00:00 rc
24849 pts/7    00:00:00 rc
24851 pts/8    00:00:00 rc
24856 pts/9    00:00:00 rc
24866 pts/10   00:00:00 rc
24885 pts/11   00:00:00 rc
24893 pts/12   00:00:00 rc
24927 pts/13   00:00:00 rc
24948 pts/14   00:00:00 rc
24954 pts/15   00:00:00 rc
24956 pts/16   00:00:00 rc
25248 pts/18   00:00:00 rc
25252 pts/19   00:00:00 rc
25254 pts/20   00:00:00 rc
25357 ?        00:00:00 rc
25359 pts/21   00:00:00 rc
```

Every (most?) spawned proccess seems to be waiting in epoll:
```
#0  0x00007f23dff78540 in epoll_pwait () from /usr/lib/libc.so.6
#1  0x00005591b702bbd3 in EventLoop::exec(int) ()
#2  0x00005591b6f7cbdb in RClient::exec() ()
#3  0x00005591b6f76a8d in main ()
```

Meanwhile rdm backtraces look like this:
```
Thread 3 (Thread 0x7f9e2151c700 (LWP 24534)):
#0  0x0000563a454eeac8 in void std::__insertion_sort<__gnu_cxx::__normal_iterator<std::unique_ptr<MatchResult, std::default_delete<MatchResult> >*, std::vector<std::unique_ptr<MatchResult, std::default_delete<MatchResult> >, std::allocator<std::unique_ptr<MatchResult, std::default_delete<MatchResult> > > > >, __gnu_cxx::__ops::_Iter_comp_iter<MatchResultComparator> >(__gnu_cxx::__normal_iterator<std::unique_ptr<MatchResult, std::default_delete<MatchResult> >*, std::vector<std::unique_ptr<MatchResult, std::default_delete<MatchResult> >, std::allocator<std::unique_ptr<MatchResult, std::default_delete<MatchResult> > > > >, __gnu_cxx::__normal_iterator<std::unique_ptr<MatchResult, std::default_delete<MatchResult> >*, std::vector<std::unique_ptr<MatchResult, std::default_delete<MatchResult> >, std::allocator<std::unique_ptr<MatchResult, std::default_delete<MatchResult> > > > >, __gnu_cxx::__ops::_Iter_comp_iter<MatchResultComparator>) ()
#1  0x0000563a454e91b3 in CompletionThread::process(CompletionThread::Request*) ()
#2  0x0000563a454eaf75 in CompletionThread::run() ()
#3  0x0000563a45497525 in Thread::localStart(void*) ()
#4  0x00007f9e26f8708a in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007f9e2633c42f in clone () from /usr/lib/libc.so.6

Thread 2 (Thread 0x7f9e21d1d700 (LWP 24484)):
#0  0x00007f9e26f90958 in read () from /usr/lib/libpthread.so.0
#1  0x0000563a454a93fa in ProcessThread::run() ()
#2  0x0000563a45497525 in Thread::localStart(void*) ()
#3  0x00007f9e26f8708a in start_thread () from /usr/lib/libpthread.so.0
#4  0x00007f9e2633c42f in clone () from /usr/lib/libc.so.6

Thread 1 (Thread 0x7f9e29380740 (LWP 24483)):
#0  0x00007f9e2633c596 in epoll_pwait () from /usr/lib/libc.so.6
#1  0x0000563a4547a8c3 in EventLoop::exec(int) ()
#2  0x0000563a453d60cf in main ()
```

Strace shows that the read called in thread 2 never returns, and the epoll seems to time out and  periodically restarted in thread 1.

This happens on one of my projects. The only specific thing about it, that I can point to, is that it targets QNX. It's a real quest to configure rtags to use QNX headers, so I just use headers from my distribution instead. Since some platform-specific headers are missing, there is a bunch of error messages about missing headers and declarations. These errors do not bother me much (the code is mostly POSIX-compliant), but they might be somehow related to the described behaviour.

Interesting point, is that syntax highlighting works perfectly fine.

### Environment
- Your operating system: 64-bit linux
- LLVM/Clang version: 5.0
- Rtags verstion: 2.16

Please let me know if you need any additional info, since I am not really familiar with rtags internals.

**Comment by Andersbakken** [comment]
Sorry about the delay. Can you try to disable completions and see if you still can reproduce it?

**Comment by Satius** [comment]
Hi! I am extremely sorry, but I've totally forgot about this issue.
Shortly after reporting this, I've switched to git master, and the problem disappeared.

I would not bet on this, but most probably it was related to
https://github.com/Andersbakken/rtags/issues/1109

Probably it's safe to close this now.
Thank you for your great work!
