### ISSUE TITLE
v2.16 tarball missing submodules required to build.

### ISSUE THREAD

**Issue by psipika** [Andersbakken/rtags#1117]
### Please mark appropriate
 - [x] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description
[Latest release tarball](https://github.com/Andersbakken/rtags/archive/v2.16.tar.gz) is missing submodules required to build:

```bash
$ tar -tvzf ~/Downloads/rtags-2.16.tar.gz |grep rct
drwxrwxr-x  0 root   root        0 Nov 29 03:36 rtags-2.16/src/rct/
$ tar -tvzf ~/Downloads/rtags-2.16.tar.gz | grep -c rct
1
```

#### Expected behavior
Latest release tarball should either be self-contained or provide a list of dependencies to be retrieved at build time (e.g. DPKG's `Build-Depends:`)

#### Actual behavior
Extracted tarball failed to build with the following error:

```bash
CMake Error at src/CMakeLists.txt:113 (include):
  include could not find load file:

    rct/rct.cmake
```

### Environment
- Your operating system:
RedHat Enterprise Linux 6.4 x86_64

- LLVM/Clang version:

```bash
-- The C compiler identification is Clang 5.0.0
-- The CXX compiler identification is Clang 5.0.0
```
### Feature request
N/A

**Comment by Andersbakken** [comment]
Should be fixed now. Sorry about that.

**Comment by psipika** [comment]
Many thanks for the quick turnaround!

**Comment by psipika** [comment]
Unfortunately, even though I see that the release has been recreated on the 18th, it is the same size as the one created on the 14th. I don't think github currently supports release tarballs of projects with submodules: https://stackoverflow.com/a/34721233/419639

Thanks!

**Comment by Andersbakken** [comment]
It's in there now. I rolled my own release script due to this. Not sure why it would be the same size but it's definitely in there in https://andersbakken.github.io/rtags-releases/rtags-2.16.tar.gz

**Comment by psipika** [comment]
Many thanks for the extra legwork, I'll use that URL from now on.
Best!

**Comment by Andersbakken** [comment]
It's really unfortunate that github's own tarball thing doesn't handle
submodules. If you want  to see a headache of a script check here:

https://raw.githubusercontent.com/Andersbakken/rtags/master/scripts/rtags-release.sh

:-)

Anders
