### ISSUE TITLE
Emacs lags badly if diagnostics is open while much reparsing is occuring

### ISSUE THREAD

**Issue by Nephyrin** [Andersbakken/rtags#1118]
### Please mark appropriate
 - [ ] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [x] rtags.el

### Problem description
Recently (past few months?) I have noticed that when the entire project is reparsing, emacs begins to grind to a halt if rtags diagnostics is running.

I have a project with several thousand files.  I run rtags with more aggressive warning flags than we normally target for the diagnostics, which can result in a lot of combined warnings when reprocessing a large part of the project.

While this lag is occuring, emacs is usually at 100% CPU, and the built-in profiler shows `rtags-parse-diagnostics` as the culprit (with no further leaf function, oddly)

While emacs remains interactive, there are frequent pauses, and other tools that interact with processes are generally blocked (e.g. calling into fzf hangs for many seconds)

#### Expected behavior
- Emacs should remain lag free while diagnostics are incoming, and ideally should not sit at 100% CPU for the duration.
- Related, an option to only show diagnostics for the current/requested buffer(s) may be helpful.  Often I will open diagnostics for a file, and it will get filled with unrelated files that happen to be being reparsed at that instant.

#### Actual behavior
Heavy CPU usage and lag, diagnostics buffer fills with thousands of diagnostics from unopened/untouched files.

### Environment
- Your operating system: Arch Linux x64, emacs-git 27.0.50.131178-1

- LLVM/Clang version: 5.0

**Comment by Andersbakken** [comment]
I believe this should be improved now. I've put in a patch that makes emacs tell rdm what buffers are visible (as opposed to open) and only send diagnostics for those buffers. Let me know if you notice an improvement at all.

**Comment by Nephyrin** [comment]
Unfortunately I'm still seeing this behavior.  Experimenting with it more, it seems simply re-saving a non-header file in my project causes emacs to chew 100% CPU for upwards of a minute, though only two warnings end up in the diagnostics pane for the file.  Let me know if there's steps I could follow to help debug this further.

**Comment by Nephyrin** [comment]
Debugging this more -- when dirtying a single file (a.cpp) and observing what is piped into `*RTags Raw*` -- checkstyle line with over 1000000 characters is returned from rc, with errors referencing a *ton* of unrelated, un-opened files.  It seems like rdm is returning far more diagnostics information than just the reparsed file.

**Comment by JohnC32** [comment]
I'm seeing a similar problem (https://github.com/Andersbakken/rtags/issues/1131) that seems to be related to the diagnostics handling.
