### ISSUE TITLE
rtags-flycheck doesn't put the cursor on the error column on `next-error`

### ISSUE THREAD

**Issue by amosbird** [Andersbakken/rtags#1120]
### Please mark appropriate
 - [ ] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [X] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description

Hello, how can I make flycheck goto error put the cursor on the correct column instead of on the head of line?

![img-2017-12-16-183421](https://user-images.githubusercontent.com/5085485/34070258-d42d6610-e29d-11e7-8243-fdc09cdc4749.png)

### Environment
- Your operating system:
Centos 6

- LLVM/Clang version:
clang 6

**Comment by cslux** [comment]
This is a flycheck “thing“. `(setq flycheck-display-errors-function 'ignore)` should do the trick for now. 
Only changing this variable when rtags is the current checker would be better...

Chris

**Comment by amosbird** [comment]
@cslux Hmm, it doesn't do the trick here.

**Comment by cslux** [comment]
Hmm, when you change the variable value to 'ignore or to nil and the file is already open you need to revert the buffer or reopen the file. Let me know if it worked.

On January 3, 2018 4:39:24 PM GMT+01:00, Amos Bird <notifications@github.com> wrote:
>@cslux Hmm, it doesn't do the trick here.

-- 
Christian Schwarzgruber
T: +43 699 194 166 34
E: c.schwarzgruber.cs@gmail.com

**Comment by amosbird** [comment]
It still doesn't work after  I restart emacs.

**Comment by cslux** [comment]
@amosbird That's actual I bug in `helm-flycheck.el`, `helm-flycheck-action-goto-error` to be precise. It searches for the Flycheck error overlay but fails to find one, as I suggested to disabling Flycheck overlays as the RTags overlays are more accurate. 

I currently don't know why `helm-flycheck` doesn't use the column provided to go to the error.

**Comment by cslux** [comment]
@amosbird You can remove `(setq-local flycheck-highlighting-mode nil))` or change it to `(setq-local flycheck-highlighting-mode t)` for now.
