### ISSUE TITLE
rtags removes the contents of every buffer

### ISSUE THREAD

**Issue by dmakarov** [Andersbakken/rtags#1121]
### Please mark appropriate
 - [ ] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [x ] rtags.el

### Problem description
Rtgas deletes contents of every buffer in emacs even those that are read-only:

`rtags-call-rc: Buffer is read-only: #<buffer *Messages*>`

#### Expected behavior

Nothing.

#### Actual behavior

Updated to the most recent version of rtags package in emacs. Every buffer content is removed on activating a buffer.

### Environment
- Your operating system:

MacOS 10.13.2

- LLVM/Clang version:

5.0.1

**Comment by clearmisp** [comment]
Here to. Makes it impossible to use Emacs.

**Comment by Andersbakken** [comment]
Whoopsie. That one's pretty bad. Sorry about that. Should be fixed now.
