### ISSUE TITLE
completion fails almost always

### ISSUE THREAD

**Issue by pedro-esteves-pinto** [Andersbakken/rtags#1123]
### Please mark appropriate
 - [x] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [x] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description
Completion does not work

#### Expected behavior
I expected a list of completions.

#### Actual behavior
A request for completion almost always results in the following from elisp:

Company: An error occurred in auto-begin
Company: backend company-rtags async timeout with args (candidates )

I have increased the timeout to 10 secs, which is much longer than what it takes for the translation unit to compile from scratch.

### Environment
- Ubuntu 17.04

- LLVM/Clang version:
clang version 4.0.0-1ubuntu1 (tags/RELEASE_400/rc1)

### Feature request

Describe the feature we should add to **RTags**.

**Comment by mkurop** [comment]
I experience the same problem. Do you solved your issue? I am trying hard to solve but with no success thus far.

**Comment by pedro-esteves-pinto** [comment]
No, to be honest rtags completion has always been very hit or miss for me.

*Pedro Pinto*
*Managing Partner*
*pedro.pinto@bluetradesys.com <pedro.pinto@bluetradesys.com>*
*919-913-0857*

[image: Visit www.bluetradesys.com] <http://www.bluetradesys.com/>
[image: Follow us on LinkedIn]
<https://www.linkedin.com/company/bluetradesystem>  [image: Follow us on
Twitter] <https://twitter.com/bts_software>

**Comment by jwiegley** [comment]
I'm seeing this same behavior. In fact, while finding symbols appears to work fine, diagnostics and completion just seem to hang at the prompt.  For example:

```
14:42 Vulcan:ledger $ rc --list-symbols fn_amount_
fn_amount_expr
fn_amount_expr(ledger::call_scope_t &)
fn_amount_expr(ledger::call_scope_t &)::scope
```

This responds almost instantly.  However:

```
rc --synchronous-completions --code-complete-at ~/Projects/ledger/src/report.cc:1365:38
```

This hangs indefinitely.  As does `rc -m --elisp`.

As a result, `M-.` works just fine, but neither flycheck nor company work at all.

**Comment by drrlvn** [comment]
I can get completion to work when I install using `(rtags-install)` but not when I use the [AUR package](https://aur.archlinux.org/packages/rtags/). The `rc` process hangs indefinitely in that case as previously mentioned.

**Comment by myrgy** [comment]
latest `2.18` rtags - completion fails almost always. During that time emacs hangs up for a while.
In rc -v -g log I can see plenty of same messages about completion request without any responses.

**Comment by cslux** [comment]
Related to #1103, #989, and maybe #818 too

**Comment by redm123** [comment]
Just compiled a new rtags from Git and it still often fails to complete.

It seems to work pretty reliable when completing after a "." or "->" (although it seems to list private members now...). But other cases still only work sometimes.
I just tried to complete a local variable after the first few chars, didn't work. Completing a vector "foo.push_b_" (2nd _ is the cursor), "No completions found" ...
Sometimes completion works if I indent 7, 10, 20 .. characters.

**Comment by cslux** [comment]
Hey guys, Swassie has created a PR yesterday, with fix for completion in RTags. Can you guys try https://github.com/Andersbakken/rtags/commit/b6f578173e53df2d4c4560ae82087e377a4aa080, and check if it works now. Thanks!

**Comment by redm123** [comment]
First impression: That did the trick! Cool. Should this be the first time having truly working smart completion and navigation in Emacs, after all those years fighting with Cedet and what not?! :)

**Comment by cslux** [comment]
Glad to hear that. Yeah, Cedet is a bit of a pain in the ass :-), though quit
useful if you are new to Emacs, and are used to an IDE.

There are some other Clang/LLVM based parsers around, like irony, ycmd,
cquery...
