### ISSUE TITLE
Add to the README that systemctl --user does not work on RHEL derivatives

### ISSUE THREAD

**Issue by onedigit** [Andersbakken/rtags#1125]
### Please mark appropriate
 - [x] rtags (rdm/rc/rp)
 
### Problem description
user level systemd does not work on recent RHEL derivatives (e.g. CentOS 7).  Evidently, support for  this has been withdraw by RedHat as explained here: https://bugs.centos.org/view.php?id=8767

#### Actual behavior
- systemctl --user enable rdm.socket
This will produce the error:
Failed to start rdm.service: Process /bin/false exited with status 1

### Environment
- CentOS Linux release 7.4.1708 (Core)
- Kernel: 4.14.8-1.el7.elrepo.x86_64

- LLVM/Clang version:

### Feature request

Will be worthwhile mentioning this in the README  in case someone runs into very strange output from systemd when trying to set that up on recent RHEL derivatives.

**Comment by Andersbakken** [comment]
Done now. Thanks
