### ISSUE TITLE
rtags-cycle-overlays-on-screen should move point to each issue

### ISSUE THREAD

**Issue by JohnC32** [Andersbakken/rtags#1130]
### Please mark appropriate
 - [ ] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [x] rtags.el

### Problem description

rtags-cycle-overlays-on-screen lets one cycle through the diagnostics. The function does cycle through the diagnostics in the message area, but it doesn't move the point to each diagnostic.

Note, a better name for the function would be rtags-cycle-through-diagnostics (assuming I understand what the function should do).

#### Expected behavior

Cycling through diagnostics should move the point to teach diagnostic.

### Environment
- Your operating system: Debian 8

- LLVM/Clang version: 5.0

**Comment by Andersbakken** [comment]
There definitely were some bugs in all of this. I think it should work better now. Thanks for the report.
