### ISSUE TITLE
flycheck complaints "header file not found"

### ISSUE THREAD

**Issue by qiwei9743** [Andersbakken/rtags#1133]
### Please mark appropriate
 - [ ] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [x] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description
Describe briefly the problem.
I'm using spacemacs. And have my private rtags layer. 
flycheck complaints below error:
Lexical or Preprocessor Issue: 'core/app-template.hh' file not found

#### Expected behavior
Describe what you expected to happen.
flycheck complaints no error.

#### Actual behavior
Describe what actually happened.
A file named ".clang_complete" is created in the root directory of the project. The path points to the location of core/app-template.hh.
```
-I/home/qiw/code/github.com/seastar
```
flycheck complaints below error:
Lexical or Preprocessor Issue: 'core/app-template.hh' file not found
looks like .clang_complete didn't work.

### Environment
- Your operating system:
ubuntu16.04
- LLVM/Clang version:
-> % llvm-config --version
3.8.0
-> % clang --version
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
- my private layer
```elisp
; package.el

(defconst mineo-rtags-packages
  '(cmake-ide
    rtags
    helm-rtags
    flycheck-rtags))

(defun mineo-rtags/init-helm-rtags ())

(defun mineo-rtags/init-cmake-ide ()
  (use-package cmake-ide
    :config
    (cmake-ide-setup)))

(defun mineo-rtags/init-flycheck-rtags ())

(defun mineo-flycheck-rtags-setup ()
  (flycheck-select-checker 'rtags)
  (setq-local flycheck-highlighting-mode nil) ;; RTags creates more accurate overlays.
  (setq-local flycheck-check-syntax-automatically nil))

(defun mineo-rtags/init-rtags ()
  (use-package rtags
    :config
    (setq rtags-autostart-diagnostics t
          rtags-completions-enabled t
          rtags-display-result-backend 'helm)
    (push 'company-rtags
          company-backends-c-mode-common)
    (rtags-enable-standard-keybindings)


    (add-hook 'c-mode-common-hook 'rtags-start-process-unless-running)
    (add-hook 'c-mode-hook #'mineo-flycheck-rtags-setup)
    (add-hook 'c++-mode-hook #'mineo-flycheck-rtags-setup)
    (add-hook 'objc-mode-hook #'mineo-flycheck-rtags-setup))
   (use-package flycheck-rtags
     :ensure rtags))
```

### Feature request

Describe the feature we should add to **RTags**.

**Comment by Andersbakken** [comment]
RTags actually doesn't support .clang_complete files. 

You need to instruct rtags how to build the project with either:

rc -J <compile_commands.json>

or: 

rc -c <compiler> <flags> <source_file>

**Comment by qiwei9743** [comment]
With the help of rtags-find-symbol-at-point, rtags could find the location of the symbol inside 'core/app-template.hh'. But flycheck-rtags could not found this header file and complaint an error.

**Comment by qiwei9743** [comment]
rc -c c++ `pkg-config --cflags --libs $SEASTAR/build/release/seastar.pc` sleep.cc

-> % cat compile_commands.json
[
    {
        "command": "c++ -c -std=gnu++17 -g -Wall -Werror -Wno-error=deprecated-declarations -fvisibility=hidden -pthread -U_FORTIFY_SOURCE -DBOOST_TEST_DYN_LINK -Wno-overloaded-virtual -Wno-maybe-uninitialized -Wno-sign-compare -Wno-error=cpp -DFMT_HEADER_ONLY -DHAVE_HWLOC -DHAVE_NUMA -DHAVE_LZ4_COMPRESS_DEFAULT -O2 -I/home/qiw/code/github.com/seastar -I/home/qiw/code/github.com/seastar/fmt -I/home/qiw/code/github.com/seastar/build/release/gen -I/home/qiw/code/github.com/seastar/build/release/c-ares -Wl,--whole-archive,-lseastar,--no-whole-archive -std=gnu++17 -g -Wall -Werror -Wno-error=deprecated-declarations -fvisibility=hidden -pthread -I/home/qiw/code/github.com/seastar -U_FORTIFY_SOURCE -I/home/qiw/code/github.com/seastar/fmt -DBOOST_TEST_DYN_LINK -Wno-overloaded-virtual -Wno-maybe-uninitialized -Wno-sign-compare -Wno-error=cpp -DFMT_HEADER_ONLY -DHAVE_HWLOC -DHAVE_NUMA -DHAVE_LZ4_COMPRESS_DEFAULT -Wl,--no-as-needed -o sleep /home/qiw/code/cpp/seastar/sleep.cc",
        "directory": "/home/qiw/code/cpp/seastar",
        "file": "/home/qiw/code/cpp/seastar/sleep.cc"
    }

**Comment by cslux** [comment]
@qiwei9743 `flycheck-rtags` shows the errors reported from **rdm** (diagnostics) for the current buffer.  The error very likely stems from a faulty compile command passed to RTags. When [this](https://github.com/scylladb/seastar) is the project you are trying to parse, which uses ninja, you can either pass the compile commands directly to **rc** or generate a compile_commands.json file using ninja. See the manual of ninja.
