### ISSUE TITLE
rtags server compile error with cygwin

### ISSUE THREAD

**Issue by damon-kwok** [Andersbakken/rtags#1137]
### Please mark appropriate
 - [-] rtags (rdm/rc/rp)

### Problem description
rtags server compile error with cygwin

#### Expected behavior
qq563@DESKTOP-GWW ~/rtags-2.17
$ 
make
Scanning dependencies of target rtags
[  1%] Building CXX object src/CMakeFiles/rtags.dir/Source.cpp.o
/home/qq563/rtags-2.17/src/Source.cpp: In function ‘bool isCompiler(const Path&, const List<String>&)’:
/home/qq563/rtags-2.17/src/Source.cpp:283:48: error: ‘strcasestr’ was not declared in this scope
     if (strcasestr(fullPath.fileName(), "emacs"))
                                                ^
make[2]: *** [src/CMakeFiles/rtags.dir/build.make:735: src/CMakeFiles/rtags.dir/Source.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1277: src/CMakeFiles/rtags.dir/all] Error 2
make: *** [Makefile:139: all] Error 2

#### Actual behavior
Describe what actually happened.

### Environment
- Your operating system: windows10 cygwin

- LLVM/Clang version:
clang 5.0.1

### Feature request

Describe the feature we should add to **RTags**.

### Remark
i'm try add"#define _GNU_SOURCE" to Source.h:18, it's resolved！

[ 82%] Linking CXX static library librtags.a
[ 84%] Built target rtags
Scanning dependencies of target rc
[ 85%] Building CXX object src/CMakeFiles/rc.dir/rc.cpp.o
[ 86%] Linking CXX executable ../bin/rc.exe
[ 86%] Built target rc
Scanning dependencies of target rp
[ 88%] Building CXX object src/CMakeFiles/rp.dir/rp.cpp.o
[ 89%] Linking CXX executable ../bin/rp.exe
[ 89%] Built target rp
Scanning dependencies of target rdm
[ 90%] Building CXX object src/CMakeFiles/rdm.dir/rdm.cpp.o
[ 92%] Linking CXX executable ../bin/rdm.exe
[ 92%] Built target rdm
Scanning dependencies of target emacs_byte_compile_helm-rtags.el
[ 93%] Creating byte-compiled Emacs lisp /home/qq563/rtags-2.17/src/helm-rtags.elc
[ 93%] Built target emacs_byte_compile_helm-rtags.el
Scanning dependencies of target emacs_byte_compile_ivy-rtags.el
[ 94%] Creating byte-compiled Emacs lisp /home/qq563/rtags-2.17/src/ivy-rtags.elc
[ 94%] Built target emacs_byte_compile_ivy-rtags.el
Scanning dependencies of target emacs_byte_compile_rtags.el
[ 96%] Creating byte-compiled Emacs lisp /home/qq563/rtags-2.17/src/rtags.elc
[ 96%] Built target emacs_byte_compile_rtags.el
Scanning dependencies of target emacs_byte_compile_ac-rtags.el
[ 97%] Creating byte-compiled Emacs lisp /home/qq563/rtags-2.17/src/ac-rtags.elc
[ 97%] Built target emacs_byte_compile_ac-rtags.el
Scanning dependencies of target emacs_byte_compile_company-rtags.el
[ 98%] Creating byte-compiled Emacs lisp /home/qq563/rtags-2.17/src/company-rtags.elc
[ 98%] Built target emacs_byte_compile_company-rtags.el
Scanning dependencies of target emacs_byte_compile_flycheck-rtags.el
[100%] Creating byte-compiled Emacs lisp /home/qq563/rtags-2.17/src/flycheck-rtags.elc
[100%] Built target emacs_byte_compile_flycheck-rtags.el

**Comment by Andersbakken** [comment]
Should be fixed now. Thanks.
