### ISSUE TITLE
Display rtags-find-file results using the display backends

### ISSUE THREAD

**Issue by kvaneesh** [Andersbakken/rtags#1138]
Even when I have the display backend set to heml, it uses rtags display backend. With rtags.el from melpa as of 9-jan-2018.

**Comment by cslux** [comment]
@kvaneesh Can you share your configuration with us? 
` (setq rtags-display-result-backend 'helm)` works for me.

**Comment by cslux** [comment]
Closing this issue. If the problem remains after setting `rtags-display-result-backend` to `'helm` feel free to reopen this issue.

Christian
