### ISSUE TITLE
You build test by default

### ISSUE THREAD

**Issue by leopoldfreeman** [Andersbakken/rtags#1150]
### Please mark appropriate
 - [x] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description
cmake failed

#### Expected behavior
cmake success

#### Actual behavior
CMake Error at /path/tools/cmake/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find CPPUNIT (missing: CPPUNIT_LIBRARY CPPUNIT_INCLUDE_DIR)

### Environment
- Your operating system:
macOS 10.13.3

- LLVM/Clang version:
5.0.1

**Comment by Andersbakken** [comment]
I've made it opt-in now.

**Comment by leopoldfreeman** [comment]
Thank you
