### ISSUE TITLE
Unable to generate build files for rtags (again)

### ISSUE THREAD

**Issue by gizmo1904** [Andersbakken/rtags#1156]
### Please mark appropriate
 - [x] rtags (rdm/rc/rp)

### Problem description
I am trying to generate build files with cmake for rtags. I installed llvm, libclang-dev, clang, cmake and emacs. Sadly, cmake will stop with this error: 
![cmake_error](https://user-images.githubusercontent.com/17142436/36433603-29d3aff0-165d-11e8-812e-abfc6d082879.PNG)

As you can see llvm-config is found in my path. I've installed everything beforehand, so deleting CMakeCache.txt wouldn't help. 

Any help would be appreciated.

#### Expected behavior
CMake to generate project files so that I can build rtags.

#### Actual behavior
I get the following error:
```
CMake Error at src/CMakeLists.txt:84 (message):
  We can't seem to compile a small clang test app.  Maybe you need to install
  the libclang dev package?
```

### Environment
- Your operating system: Ubuntu 16.04

- LLVM/Clang version: 7.0.0

**Comment by Andersbakken** [comment]
Can you attach your CMakeError.log file from your CMakeFiles folder.

**Comment by binary132** [comment]
I have the same issue.  Ubuntu 17.10 x64 libclang-dev defaults to clang 4.0, but the cmake setup fails with 3.9 and 4.0.  You need 3.8 installed (confirmed by checking the CMakeError.log file.)  That is either a bug or a documentation bug since the build doc says `>= 3.8`.

**Comment by cslux** [comment]
@binary132 You always need to install matching versions of clang, libclang-dev, llvm,...
Some distributions provide multiple versions of clang, though not always a matching devel package, that's unfortunate.

@gizmo1904 Were you able to compile RTags, if not do not hesitate to reopen this issue.
