### ISSUE TITLE
release 2.18 tar.gz is incomplete

### ISSUE THREAD

**Issue by max0x7ba** [Andersbakken/rtags#1158]
### Please mark appropriate
 - [ x] rtags (rdm/rc/rp)

### Problem description
Cannot configure because rct directory is missing in the release archive.

#### Expected behavior
configure succeeds

#### Actual behavior
CMake Error at src/CMakeLists.txt:113 (include):
  include could not find load file:
    rct/rct.cmake

### Environment
CentOS 6.8

- LLVM/Clang version:
3.9

**Comment by Andersbakken** [comment]
Hi

Unfortunately github doesn't seem to have a good solution for submodules
for their tarballs so those can't be used. I have separate tarballs that I
generate here:

https://andersbakken.github.io/rtags-releases/rtags-2.18.tar.gz

and

https://andersbakken.github.io/rtags-releases/rtags-2.18.tar.bz2

These should contain the rct sources as well.

Anders

**Comment by max0x7ba** [comment]
Oh, I see, said a blind man.
