### ISSUE TITLE
Document expected ordering of gcc-rtags-wrapper.sh with ccache

### ISSUE THREAD

**Issue by eklitzke** [Andersbakken/rtags#1162]
I'm using rtags with `gcc-rtags-wrapper.sh` and `ccache`. It's not clear to me if the recommended setup is:
 * `gcc-rtags-wrapper.sh` -> `ccache` -> `/usr/bin/gcc`
 * `ccache` -> `gcc-rtags-wrapper.sh` -> `/usr/bin/gcc`

I'm currently using the first setup (where `gcc-rtags-wrapper.sh` sees the compilation requests before ccache) on the thinking that if I'm working on several different branches at once, ccache might have all (or nearly all) of the files cached for all of the branches, and therefore won't notice when I'm switching branches. But this means that rtags is reindexing the same files over and over again which uses a lot of CPU.

Could you add a brief note in the README file explaining which order is recommended?

**Comment by Andersbakken** [comment]
It doesn't actually matter. RTags will reindex files immediately as soon as they are modified including dependencies. Even though ccache will keep your compilation times almost instant rtags doesn't cache like that. My preference for working on projects with multiple branches is to have a separate checkout for each branch. E.g. git worktree. gcc-rtags-wrapper.sh is only used to inform rtags of how the files are compiled. Once it knows it keeps track of changes using file system watchers by itself.

**Comment by eklitzke** [comment]
Thanks for your response, I went a little deeper down the rabbithole since I first posted this and I'm now using intercept-build to generate a compilation database.

**Comment by Andersbakken** [comment]
I've completely switched to that mode of operating too. I tend to use bear (
https://github.com/rizsotto/Bear) if I'm not using cmake. Glad to hear you
were able to get it to work.

Anders
