### ISSUE TITLE
Code completion in header files

### ISSUE THREAD

**Issue by LKlemens** [Andersbakken/rtags#1163]
### Please mark appropriate
 - [rc] rtags (rdm/rc/rp)
- [deoplete-rtags](https://github.com/rzaluska/deoplete-rtags)

### Problem description
Hi All,
In cpp files code completion works like a charm but in hpp files nope ;/
In rdm server output I get something like this:
rc --absolute-path --synchronous-completions --json -l path/to/file.hpp:88:50 --unsaved-file=/path/to/file.hpp:2789
No completion results available path/to/file.hpp:88:50:
Any suggestions might be helpful.

#### Expected behavior
It would be awesome when code completion will works :P

#### Actual behavior
Code completion doesn't work.

### Environment
- Your operating system: RedHat 6.5

- LLVM/Clang version: 5.0

**Comment by papadokolos** [comment]
Usually, compilation database files (`comple_commands.json`) don't contain information about header files. Hence, this might be the cause for the lack of completion suggestions.

I haven't tried it myself, but [this project](https://github.com/Sarcasm/compdb) is capable of taking an existing compilation database and add information about header files. So it might solve your problem.

In case you give it a shot, please report back :wink:

**Comment by Andersbakken** [comment]
It's meant to work but there has to be a source file that includes this file somewhere in your project. Otherwise we don't have compilation flags to index the file. Is the header included from anywhere?

**Comment by LKlemens** [comment]
@papadokolos Okej, thanks. I will try to run compdb :) 
@Andersbakken Yes headers are include in many cpp files.

**Comment by LKlemens** [comment]
Hi All,
After compdb script, rtags begin working in header files. Sometime peculiar object does not want to cooperate but at the end rtags works much better :)
PS. On the occasion, is there some way to expand macros with rtags? :P

**Comment by LKlemens** [comment]
@mckellyln I've done something like this:
 ```
compdb -p . list > co.json
mv co.json compile_commands.json
rc -W project  //delete project
rc -J .  //create project anew
```
I don't notice some significant difference between time indexing :)

**Comment by mckellyln** [comment]
Thx.  Where/what is list from ?
I used the existing compile_commands.json from a cmake build.
And it worked fine, but the indexing did take a lot longer than with the original compile_commands.json.

**Comment by mckellyln** [comment]
All good, thanks for the info.
And thanks so much for the awesome rtags.

**Comment by Andersbakken** [comment]
My pleasure.
