### ISSUE TITLE
std=c++17 treated as pre-C++11 for diagnostics

### ISSUE THREAD

**Issue by dzhu** [Andersbakken/rtags#1167]
### Please mark appropriate
 - [x] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [x] rtags.el

### Problem description
When a file has `-std=c++17` in its compilation arguments, diagnostics appear in the file as if it is being treated as pre-C++11.

#### Expected behavior/reproduction steps
* Write file `a.cc` in emacs, containing `using x = int;`.
* Run `echo 'g++ -std=c++17 a.cc' | rc -c`.
* No diagnostics should appear in the buffer.

#### Actual behavior
* Diagnostic appears on `int`, with the minibuffer showing `Parse Issue: alias declarations are a C++11 extension: -Wc++11-extensions`.
* Rerunnng `echo | rc` with `c++11` or `c++14` immediately causes the diagnostic to disappear, and rerunning with `c++17`causes it to reappear.
* `rtags-compilation-flags` and `rtags-compile-file` know about the correct version in all cases.

### Environment
- Ubuntu 16.04, emacs 24.5.1 (minimal config, loading only rtags-20180224.1658 from MELPA), rtags git-6f084a31
- LLVM/Clang version: 5.0

**Comment by stellarstriker** [comment]
+1

OS: Fedora 26
rtags: tag v2.18
Clang: 4.0.1

**Comment by Andersbakken** [comment]
This seems to just work for me. I am running clang 6.0 however. Is it possible that your libclang doesn't support c++17?

Can you try to compile the example with the clang executable that goes with the libclang rtags is using?

**Comment by dzhu** [comment]
Oops, rtags was compiled with libclang 3.8. Recompiling with 5.0 fixes it. Thanks!

**Comment by Andersbakken** [comment]
Glad to hear.

Anders
