### ISSUE TITLE
Many Failed to open and Error during validation msgs during index

### ISSUE THREAD

**Issue by mckellyln** [Andersbakken/rtags#1169]
Thank you for rtags.

### Please mark appropriate
 - [x] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description
Perhaps reported before, but I couldn't find these in an issue search -
Hundreds of msgs such as:

1). Failed to open /home/user/.cache/rtags/%2Fhome%2Fuser%2Flnrs%2Fwip%2FHPCC-Platform%2F/1482/symbols /home/user/lnrs/wip/HPCC-Platform/esp/bindings/SOAP/xpp/sxt/XmlTokenizer.h (2) 87
They are always for include files and there is always the (2) 87

2). Error during validation: /home/user/lnrs/wip/HPCC-Platform/thorlcr/thorutil/thmem.hpp (2) 87 /home/user/.cache/rtags/%2Fhome%2Fuser%2Flnrs%2Fwip%2FHPCC-Platform%2F/2755/symnames
They are always for symnames files and there is always the (2) 87

#### Expected behavior
Not sure if this is a problem or not, but curious of the cause and fix if required.

### Environment
Ubuntu 16.04 LTS +hwe 4.13.0-37-generic kernel

- LLVM/Clang version:
3.8

**Comment by mckellyln** [comment]
Interestingly this does not happen when using only 1 job.

**Comment by Andersbakken** [comment]
It is mostly benign actually. The issue happens when an rc request (or during startup of rdm) files that were expected to exist do not exist. 

It should eventually fix itself since these errors will trigger reparses of those files and dependencies of them.

**Comment by mckellyln** [comment]
ok, thanks for that info, I may look into it more one day.
It only happens for me during indexing (rc -J), not from other rc cmds that I can tell.
thx

**Comment by mckellyln** [comment]
Closing for now, since it appears to not really be a problem, just an irritation to see the msgs.
