### ISSUE TITLE
rtags in emacs not working, no communication with rdm

### ISSUE THREAD

**Issue by thetwom** [Andersbakken/rtags#1170]
### Please mark appropriate
 - [ ] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ x] rtags.el

### Problem description
I get no response in emacs when e.g. calling rtags-find-symbol-at-point.

I have a rdm instance running in the terminal and this also works, when e.g. I call rc -F A where A is some class from my test.cpp-sample file. The rdm-terminal gives also some output that his command was called. 

When calling rtags-find-symbol-at-point from emacs the rdm window remains silent.

### Environment
- Your operating system:
Suse Enterprise SLED 12

- LLVM/Clang version: 6.0.0
- emacs version: 25.3.1
- Rtags installed from melpa in emacs (tried both stable and bleeding edge)
- rdm --version: 2.18.123
- M-: rtags-protocol-version -> 124 (#o174, #x7c, ?|)

I installed rtags via rtags-install inside emacs and exported the PATH variable to the resulting binary folder. 
I also tried to set the rtags-binary-path inside emacs via
M-x set-variable RET rtags-path

Is there a way to check if emacs at least calls any rc-command and if there are any failures?

**Comment by Andersbakken** [comment]
I think the issue is that you're getting different builds of rtags.el and rdm. 

You can tell by the 123 in your rdm version being different from the 124 in rtags-protocol-version.

You can see what commands rc runs by doing (setq rtags-rc-log-enabled t) and then checking the *RTags Log* buffer.

You should be able to update your rdm by doing rtags-install again. Please reopen if this doesn't fix it.

**Comment by thetwom** [comment]
Thank you very much for your reply. I reinstalled rtags from melpa such that I have no the same protocol version:
- rdm --version: 2.18.124
- M-: rtags-protocol-version -> 124 (#o174, #x7c, ?|)
I enabled the logging by adding  (setq rtags-rc-log-enabled t)
I start rdm with rdm -v and added my project with rc -J .
As already stated quries with rc -F ... in the terminal work perfectly and also lead to a response in the rdm-log-buffer. 

However, when calling rtags-find-symbol-at-point from emacs the log-buffer remains silent and nothing happens inside emacs. 

Is there a way to see if emacs does any calls at all?

**Comment by vladimir-didenko** [comment]
@thetwom  I don't know if it is relevant but I had similar issue. It was triggered by git checkout that switched my code forward about a year. And it looks like rtags doesn't handle big code changes well. I deleted my ~/.cache/rtags completeley, re-indexed projected from scratch and it fixed the problem.
