### ISSUE TITLE
CentOS 6.8 don't have a systemd!

### ISSUE THREAD

**Issue by Allinaent** [Andersbakken/rtags#1173]
### Please mark appropriate
 - [x] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description
CentOS 6.8 don't have a systemd! I would like to do something like "Integration with systemd" on my system.

#### Expected behavior
rdm can also be socket acivated on CentOS 6.8

#### Actual behavior
I don't configure property.

### Environment
- Your operating system:CentOS 6.8

- LLVM/Clang version:6.0.0

### Feature request

Please Improve the Document to help those who's system don't have systemd.

**Comment by cslux** [comment]
@Allinaent Pretty old Linux system! Unfortunately, I don't think it's worth to spend time to add something for the init.d system for CentOS 6. CentOS 6 end is near :-)

But a PR is more than welcome!

>  * Please note Red Hat's policy on Production Phase 3 for EL6 in the above support policy (Begins on May 10th, 2017, for EL6). Only those security updates deemed crucial are released upstream for EL6 (so also for CentOS Linux 6) during Production Phase 3. Please read this Mailing List post for more details. The CentOS team recommends that you start moving workloads from CentOS Linux 6 to CentOS Linux 7. 

See also https://wiki.centos.org/Download

Closing it!
