### ISSUE TITLE
Rtags protocol mismatch but server and client are both 124

### ISSUE THREAD

**Issue by WiseMaestro** [Andersbakken/rtags#1183]
### Please mark appropriate
 - [x] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [x] rtags.el

### Problem description
Describe briefly the problem.

Emacs commands emit RTags: protocol version mismatch. This is usually caused by getting rtags.el from melpa and installing a new rtags build that modified the protocol. They need to be in sync.

rtags was built within emacs using (rtags-install).

'ps' reports running rtags as
~/.emacs.d/elpa/rtags-20180224.1658//rtags-2.18/bin/rdm

$ ~/.emacs.d/elpa/rtags-20180224.1658//rtags-2.18/bin/rdm --version
2.18.124

Melpa installed ~/.emacs.d/elpa/rtags-20180224.1658/rtags.el

     Status: Installed in ‘rtags-20180224.1658/’ (unsigned).
    Version: 20180224.1658
     Commit: 33aff2c7da8c0925d59c7ae8e052118a9ee5c27d

...
(defconst rtags-protocol-version 124)
(defconst rtags-package-version "2.18")
...

#### Expected behavior
Describe what you expected to happen.

Successful operation.

#### Actual behavior
Describe what actually happened.

Error message as above.

### Environment
- Your operating system:
Debian based linux.
4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux

- LLVM/Clang version:

llvm-4.0

### Feature request

Describe the feature we should add to **RTags**.

Better error messaging or even if you have a general idea of what's wrong or how to troubleshoot.

I tried installing rtags from the git repository master branch as well, but that had the same error. I'm reasonably sure I don't have multiple rtags installations on the path or in elisp.

Thanks! Rtags is pretty awesome when it works.

**Comment by WiseMaestro** [comment]
For whatever reason, rc won't verify it's version the same way it reports it.

$ ~/.emacs.d/elpa/rtags-20180224.1658//rtags-2.18/bin/rc --version
2.18.124
$ ~/.emacs.d/elpa/rtags-20180224.1658//rtags-2.18/bin/rc --verify-version=124
Protocol version mismatch

Try 'rc --help' for more information.

I've edited my rtags.el to just omit the verify-version=124 argument, but this should be fixed.

**Comment by xuning97** [comment]
met the same issue

**Comment by WiseMaestro** [comment]
Submitted a pull request to fix this. Can you have melpa download a stable tag commit or last known green build or something?

**Comment by bugaev** [comment]
@WiseMaestro Thank you for taking care of this issue.

With freshly installed rtags package from melpa, I have the same symptoms as you described (`rc --version` --> 2.18.124") plus the fact that `rc --verify-version 125` passes. At the same time, the elisp package wants rtags to be version 124.

**Comment by cslux** [comment]
> Submitted a pull request to fix this. 

@WiseMaestro Thank you, merged! 

> Can you have melpa download a stable tag commit or last known green build or something?

I don't know if that is possible, but I don't think so. Should be in MELPA in the next 8 hours!
