### ISSUE TITLE
Wrong argument type in process filter

### ISSUE THREAD

**Issue by arpd** [Andersbakken/rtags#1186]
### Please mark appropriate
 - [ ] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [x] rtags.el

### Problem description
rtags does not work via tramp.

#### Expected behavior
rtags functions to not emit errors.

#### Actual behavior
Whenever I switch to an rtags buffer pointing at a file opened via tramp, or attempt to call `rtags-find-symbol-at-point` I get the following error:
```
error in process filter: let: Wrong type argument: arrayp, (tramp-file-name "scp" "<USERNAME>" nil "<IP_ADDR>" nil "<PATH>/firmware_mgmt/" nil)
error in process filter: Wrong type argument: arrayp, (tramp-file-name "scp" "<USERNAME>" nil "<IP_ADDR>" nil "<PATH>/firmware_mgmt/" nil)
```

I've substituted `<SOMETHING>` for their real values.

When I open a file pointing at something in a project cached by rdm, I can see on the remote server some activity for the files in question.

### Environment
- Your operating system:
Ubuntu
- LLVM/Clang version:
5.00
- Emacs version:
GNU Emacs 27.0.50
- rtags version:
master:HEAD as of date of posting.

**Comment by juergenhoetzel** [comment]
> let: Wrong type argument: arrayp, (tramp-file-name "scp" "<USERNAME>" nil "<IP_ADDR>" nil "<PATH>/firmware_mgmt/" nil)

The internal representation of `tramp-file-name` changed. See: [Fix error with newer Tramp versions](https://github.com/Andersbakken/rtags/pull/1188)
