### ISSUE TITLE
rtags-check-includes chooses wrong socket file in emacs

### ISSUE THREAD

**Issue by Abergard** [Andersbakken/rtags#1189]
**Describe the bug**
How I start the rdm: rdm --socket-file /my_location/.rdm --data-dir /my_location/rtags/ --log-file /my_location/rdm.log -S -j 10 &
My alias for rc: rc --socket-file /my_location/.rdm
In emacs: (setq rtags-socket-file "/my_location/.rdm")

All functionality connected with finding references, virtual methods etc. works.
However every time I use the function rtags-check-includes from Emacs I get the information:
Can't seem to connect to server (/home/user/.rdm)

**Expected behavior**
It should use the correct socket file as like as the other functions.

**Environment:**
 - OS/Version: [Red Hat 6.5]
 - RTags(rdm,rc): [2.18]
 - Emacs: [25.2.1]
 - LLVM/Clang: [5.0]

**Comment by cslux** [comment]
Thanks for the report!

Fixed via 4953d46.
