### ISSUE TITLE
rc dies with exception std::regex_error

### ISSUE THREAD

**Issue by redm123** [Andersbakken/rtags#1192]
**Describe the bug**
When I start rc with certain options it simply dies right away with a std::regex_error exception:

    $ rc --socket-file /devel/docker/docker_home/.rdm -U "/devel/foo/Bar.cpp:93:37" --elisp -K terminate called after throwing an instance of 'std::regex_error'
      what():  regex_error
    Aborted

The culprit seems to be the -U option. Other options work fine.

**Screenshots/Backtrace**

    Catchpoint 1 (exception thrown), 0x00007ffff6b508b0 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    (gdb) bt
    #0  0x00007ffff6b508b0 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    #1  0x00007ffff6ba2955 in std::__throw_regex_error(std::regex_constants::error_type) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    #2  0x000000000047df8a in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_atom (this=0x7fffffff7698) at /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/regex_compiler.h:949
    #3  0x000000000047d9ee in _M_term (this=0x7fffffff7698) at /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/regex_compiler.h:795
    #4  std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_alternative (this=0x7fffffff7698) at /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/regex_compiler.h:773
    #5  0x000000000047da3d in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_alternative (this=0x7fffffff7698) at /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/regex_compiler.h:776
    #6  0x000000000047da3d in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_alternative (this=0x7fffffff7698) at /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/regex_compiler.h:776
    #7  0x000000000047da3d in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_alternative (this=0x7fffffff7698) at /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/regex_compiler.h:776
    #8  0x000000000047bb13 in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_disjunction (this=0x7fffffff7698) at /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/regex_compiler.h:758
    #9  0x000000000047b36a in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_Compiler (this=0x7fffffff7698, __b=<optimized out>, __e=<optimized out>, __traits=..., __flags=<optimized out>)
        at /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/regex_compiler.h:729
    #10 0x000000000047afe4 in std::__detail::__compile<char const*, std::regex_traits<char> > (__b=@0x7ffff6ddd8b0: 0x7ffff6dd9af0 <vtable for __cxxabiv1::__si_class_type_info+16> "\340\021\265\366\377\177",
        __e=@0x7ffff6ba34f0: 0x480023bb01058b48 <error: Cannot access memory at address 0x480023bb01058b48>, __t=..., __f=1) at /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/regex_compiler.h:1104
    #11 0x0000000000468249 in basic_regex (__p=<optimized out>, __f=64, this=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/regex.h:387
    #12 RClient::parse(unsigned long, char**)::$_3::operator()(RClient::OptionType, String&&, unsigned long&, List<String> const&) const (this=0x892070, type=RClient::SymbolInfo, value=<unknown type in /usr/local/stow/rtags/bin/rc, CU 0x1d618, DIE 0xc5e65>,
        idx=<optimized out>, arguments=...) at /devel/rtags/src/RClient.cpp:755
    #13 0x00000000004665be in std::_Function_handler<CommandLineParser::ParseStatus (RClient::OptionType, String&&, unsigned long&, List<String> const&), RClient::parse(unsigned long, char**)::$_3>::_M_invoke(std::_Any_data const&, RClient::OptionType, String&&, unsigned long&, List<String> const&) (__functor=..., __args=..., __args=..., __args=..., __args=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/functional:2056
    #14 0x00000000004711a6 in operator() (this=<optimized out>, __args=..., __args=..., __args=..., __args=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/functional:2471
    #15 CommandLineParser::parse<RClient::OptionType>(int, char**, std::initializer_list<CommandLineParser::Option<RClient::OptionType> >, Flags<CommandLineParser::Flag>, std::function<CommandLineParser::ParseStatus (RClient::OptionType, String&&, unsigned long&, List<String> const&)> const&, String const&, std::initializer_list<CommandLineParser::Option<CommandLineParser::ConfigOptionType> >, String*) (argc=<optimized out>, argv=<optimized out>, optsList=..., flags=..., handler=..., app=..., configOpts=..., cmdLine=<optimized out>)
        at /devel/rtags/src/CommandLineParser.h:214
    #16 0x0000000000464629 in RClient::parse (this=0x7fffffffd7c8, argc=<optimized out>, argv=<optimized out>) at /devel/rtags/src/RClient.cpp:1303
    #17 0x0000000000461994 in main (argc=7, argv=0x894e98) at /devel/rtags/src/rc.cpp:21

**Environment (please complete the following information):**
 - OS/Version: Ubuntu 14.04.5 LTS
 - RTags(rdm,rc): git 993f22f9e09a86cb97aa6b8d3211a984eaa63b4a
 - Emacs: 24.3
 - LLVM/Clang: 3.8

**Additional context**
Maybe the libgcc 4.8 is too old? But it's not so easy to upgrade on this system (without upgrading the system itself...)

If that is too old, then maybe the requirements should be updated and check during configure?

**Comment by cslux** [comment]
This is a bug in GCC 4.8. GCC 4.8 has not fully implemented <regex> please use
GCC 4.9.

**Comment by cslux** [comment]
@redm123 see #1187

**Comment by redm123** [comment]
Yea, just found another already closed report here... It was working for me on this machine and now it doesn't anymore, so I though there was some change. Weird. 
I guess we can ignore that than. It might be helpful though, to check that requirement at cmake time...

**Comment by cslux** [comment]
> If that is too old, then maybe the requirements should be updated and check during configure?

The README is already up to date. I already thought about adding a check into cmake.

**Comment by redm123** [comment]
Hmm.. didn't read the README in for a while... :)

**Comment by cslux** [comment]
> But it's not so easy to upgrade on this system (without upgrading the system itself...)

You could try to compile RTags with clang so not sure if that solves the problem!
