### ISSUE TITLE
Is it possible to "Merge" multiple build location into single project? How to do this?

### ISSUE THREAD

**Issue by fiddleyuan** [Andersbakken/rtags#1194]
Hi,
I'm working on a Android project where multiple build locations are expected. For example, for camera in Android, we have:
1. Android camera framework C++ code located at /root/framework/...
2. Vendor's proprietary C++ code located at /root/vendor/proprietary/...
3. Linux kernel driver C code located at /root/kernel/driver/media/...

Each of which can generate its own compile_commands.json file. So when I execute rc -J in each one, they can index well from rdm logging. However, I noticed that only one is "Active" project from the output of rc -w.

Of course I can rc -w to switch projects, but these 3 projects are interrelated. It would be better to look at them as a whole. So is it possible to achieve this, i.e. let single project accept multiple compilation database? Or any other workarounds will be appreciated.

Thanks

**Comment by fiddleyuan** [comment]
I have a working workaround for now. I use Bear to generate compile_commands.json. For every sub-directory, use Bear's -a paramter to append compile commands, and -o parameter to output to a empty compile_commands.json file. Then rc -J from there.

**Comment by Andersbakken** [comment]
Sorry about the long delay. I think your solution currently is the best one available.
