### ISSUE TITLE
Unable to build rtags with Clang 3.9

### ISSUE THREAD

**Issue by rubenmp8** [Andersbakken/rtags#1204]
When trying to build on ubuntu 14.04 LTS with clang-3.9, I get the following error.

-- Performing Test CXX_11_EXTENDED_REGEX_SUPPORT
-- Performing Test CXX_11_EXTENDED_REGEX_SUPPORT - Failed
CMake Error at src/CMakeLists.txt:113 (message):
  Compiler with complete C++11 support required ( >= GCC 4.9 or >= Clang 3.3)

-- Configuring incomplete, errors occurred!

**To Reproduce**
1. Ubuntu 14.04 LTS using clang-3.9
2. cmake --debug-trycompile -DCMAKE_EXPORT_COMPILE_COMMANDS=1 .

**Expected behavior**
Build to succeed

**Logs**
XXX:~/rtags$ cmake --debug-trycompile -DCMAKE_EXPORT_COMPILE_COMMANDS=1 .
debug trycompile on
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- llvm-config executable found: /usr/bin/llvm-config-3.9
-- Using Clang version 3.9.1 from /usr/lib/llvm-3.9/lib with CXXFLAGS -I/usr/lib/llvm-3.9/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-- Found LibClang: /usr/lib/llvm-3.9/lib/libclang.so
-- Performing Test LIBCLANG_COMPILES
-- Performing Test LIBCLANG_COMPILES - Success
-- Performing Test CXX_11_EXTENDED_REGEX_SUPPORT
-- Performing Test CXX_11_EXTENDED_REGEX_SUPPORT - Failed
CMake Error at src/CMakeLists.txt:113 (message):
  Compiler with complete C++11 support required ( >= GCC 4.9 or >= Clang 3.3)

-- Configuring incomplete, errors occurred!
See also "XXX/rtags/CMakeFiles/CMakeOutput.log".
See also "XXX/rtags/CMakeFiles/CMakeError.log".

XXX:~/rtags$ cat XXX/rtags/CMakeFiles/CMakeError.log
Performing C++ SOURCE FILE Test CXX_11_EXTENDED_REGEX_SUPPORT failed with the following output:
Change Dir: XXX/rtags/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_2e594/fast"
/usr/bin/make -f CMakeFiles/cmTC_2e594.dir/build.make CMakeFiles/cmTC_2e594.dir/build
make[1]: Entering directory `XXX/rtags/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_2e594.dir/src.cxx.o
/usr/bin/c++     -I/usr/lib/llvm-3.9/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DCXX_11_EXTENDED_REGEX_SUPPORT -std=c++11   -o CMakeFiles/cmTC_2e594.dir/src.cxx.o -c XXX/rtags/CMakeFiles/CMakeTmp/src.cxx
Linking CXX executable cmTC_2e594
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_2e594.dir/link.txt --verbose=1
/usr/bin/c++    -I/usr/lib/llvm-3.9/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DCXX_11_EXTENDED_REGEX_SUPPORT -std=c++11    CMakeFiles/cmTC_2e594.dir/src.cxx.o  -o cmTC_2e594 -rdynamic
make[1]: Leaving directory `XXX/rtags/CMakeFiles/CMakeTmp'

Return value: 255
Source file was:

#include <regex>

int main()
{
  try {
    std::regex rx("^(.*):([0-9]+):([0-9]+):?-:?([0-9]+):([0-9]+):?(@[A-Za-z,]+)?", std::regex_constants::extended);
  } catch (std::regex_error& e) {
    return -1;
  }

  return 0;
}

**Additional Notes**
If I run the resulting binary from the test in the error logs, it does indeed throw a regex_error. Is clang3.9 no longer supported?

**Comment by cslux** [comment]
Hey @rubenmp8,

it's because of GCC, which is used to build RTags not Clang.
``` bash
Compiler with complete C++11 support required ( >= GCC 4.9 or >= Clang 3.3)
```

Please use GCC 4.9 from the testing repository (ppa:ubuntu-toolchain-r/test).

Christian

**Comment by rubenmp8** [comment]
Oh you're right, it was using GCC. However if I set CMake to use clang as follows

XXX:~/rtags$ CC=/usr/bin/clang CXX=/usr/bin/clang++ cmake .
-- The C compiler identification is Clang 3.9.1
-- The CXX compiler identification is Clang 3.9.1
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- llvm-config executable found: /usr/bin/llvm-config-3.9
-- Using Clang version 3.9.1 from /usr/lib/llvm-3.9/lib with CXXFLAGS -I/usr/lib/llvm-3.9/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-- Found LibClang: /usr/lib/llvm-3.9/lib/libclang.so
-- Performing Test LIBCLANG_COMPILES
-- Performing Test LIBCLANG_COMPILES - Success
-- Performing Test CXX_11_EXTENDED_REGEX_SUPPORT
-- Performing Test CXX_11_EXTENDED_REGEX_SUPPORT - Failed
CMake Error at src/CMakeLists.txt:113 (message):
  Compiler with complete C++11 support required ( >= GCC 4.9 or >= Clang 3.3)


-- Configuring incomplete, errors occurred!
See also "XXX/CMakeFiles/CMakeOutput.log".
See also "XXX/rtags/CMakeFiles/CMakeError.log".

I recognize that using a newer compiler works, but before changing compiler version(unfortunately on many VMs) I wanted to be sure this wasn't a bug of some sort.

**Comment by cslux** [comment]
@rubenmp8 Clang uses the libstdc++ from GCC 4.8.4, and therefore fails with the same error.
