### ISSUE TITLE
Protocol version discrepancy between 2.18 tarball and 2.18 tag.

### ISSUE THREAD

**Issue by kwvanderlinde** [Andersbakken/rtags#1207]
**Describe the bug**
The GIT 2.18 tag has a protocol version of 124, while the 2.18 tarball rtags downloads from https://andersbakken.github.io/rtags-releases/rtags-2.18.tar.bz2 has a protocol version of 125. This results in mismatch errors when using rtags installed from MELPA Stable.

**To Reproduce**

- Install rtags 2.18 from MELPA Stable
- Per the README, run `M-x rtags-install <ret>` to build the binaries.
- Set `rtags-path`
- Try executing `rtags-find-symbol-at-point`
- Should find this in the *Messages* buffer:
```
rtags-call-rc: RTags protocol version mismatch. This is usually caused by getting rtags.el from melpa
and installing a new rtags build that modified the protocol. They need to be in sync.
```

**Expected behavior**
RTags can communicate with the server of the same version as that installed from MELPA.

**Environment (please complete the following information):**
 - Ubuntu 18.04
 - RTags(rdm,rc): 2.18
 - Emacs: 25.2.2
 - LLVM/Clang: 6.0

**Comment by cslux** [comment]
This should be fixed now!

Christian
