### ISSUE TITLE
Files not indexing correctly

### ISSUE THREAD

**Issue by JustAPerson** [Andersbakken/rtags#1208]
**Describe the bug**
After indexing all files using `rc -c gcc $file $flags`, I am unable to actually query any file.

```
$ rc -T $file
managed
$ rc -x $file
Not indexed
```

This is the script I use to process all my files.
```bash
#!/bin/bash
dir=$1
rtag_files=$dir/.rtag_files
rtag_flags=$dir/.rtag_flags
if ! [[ -d $dir ]]; then
    echo "Argument must be a directory"
    exit 1
fi
find $dir -name *.h -o -name *.cc | sort -u | grep -v test > $rtag_files

files=$(<$rtag_files)
flags=$(<$rtag_flags)
for file in $files; do
    echo $file
    rc --project-root $dir -c gcc $flags $file
done
```

**Environment (please complete the following information):**
 - OS/Version: Ubuntu 18.04 atop Windows 10 Pro Windows Subsystem for Linux (WSL)
 - RTags(rdm,rc): 2.18.125
 - LLVM/Clang: 6.0.0

**Comment by JustAPerson** [comment]
Is this even the correct way to use rtags without a compile_commands db?

**Comment by JustAPerson** [comment]
Oh it appears to be indexing C++ files but not header files. I had been trying to jump to the definition of a symbol while at its declaration. How is that supposed to work (as referenced by rtags-find-symbol-at-point help)?

**Comment by cslux** [comment]
@JustAPerson How do you build that project? To get a correct result you need to pass the same commands to RTags as you would pass to GCC itself. You cannot index headers on it's own, you need to include that header in a source file and parse that. 

> Is this even the correct way to use rtags without a compile_commands db?

Well, that depends, if you build the executable by hand too, than yes! But as I said you must pass the correct flags to `rc -c`.

What is the output of `rdm` when you start it with verbose output (one or more `-v`), e.g. `rdm -vv`, and call `rc -c gcc $file $flags`

**Comment by JustAPerson** [comment]
@cslux the project is built using a complex series of scons scripts. I may try something more complicated to read the flags of every individual file rather than just copying one set of flags for all files.

It appears to be working okay now after adjusting my flags. Thanks!
