### ISSUE TITLE
Highlighting of unused preprocessor conditionals (#if / #ifdef) no longer works.

### ISSUE THREAD

**Issue by GerryLG** [Andersbakken/rtags#1209]
**Describe the bug**
Previously, sections of code within #if / #ifdef sections that are not used based on the current compilation flags, are highlighted as such.  This has now stopped working.

**To Reproduce**
Edit code containing unused conditional compilation sections.

**Expected behavior**
Unused preprocessor conditionals are highlighted.

**Screenshots/Backtrace**
Working Version (tag v2.18)

![image](https://user-images.githubusercontent.com/40765148/42230059-f0288104-7edf-11e8-9e8d-e92fc7fc141e.png)

Non-Working Version (commit 015cde3b)

![image](https://user-images.githubusercontent.com/40765148/42229764-27e2ad28-7edf-11e8-96fc-0bff46650994.png)

**Environment (please complete the following information):**
 - OS/Version: Debian 9.4
 - RTags(rdm,rc): 015cde3b, but issues seems to be present since 279c7870
 - Emacs: 25.1.1
 - LLVM/Clang: 6.0.0-1~bpo9+1 (tags/RELEASE_600/final)

**Additional context**
The issue seems to have occurred since commit 279c7870.

**Comment by Andersbakken** [comment]
Should be fixed now. Thanks.
