### ISSUE TITLE
Allow symbolic links in path to socket file

### ISSUE THREAD

**Issue by itollefsen** [Andersbakken/rtags#1214]
Both RDM and RC calls `Path::resolve()` on the socket file, which calls `realpath()` on non-Windows systems.

I'm curious as to why `Path::resolve()` feels the need to do this at all, perhaps especially in light of the interesting `Path::sRealPathEnabled` variable which suggests that at some point it was enough to make the path absolute and canonical. However, the only real problem encountered with the current approach is the socket file.

`struct sockaddr_un::sun_path` is commonly defined as `char sun_path[108]`, which is then the max length of the full path to the socket file.

I went above that limit, and though I could solve it by creating a shortened symbolic link to the directory containing the socket file, jumping a few of the intermediate directories. That didn't work since the symbolic link was resolved.

The easiest fix for this is to stop calling `resolve()` on the socket file in rdm.cpp and RClient.cpp, which is what I did locally.

**Comment by Andersbakken** [comment]
I agree. No reason to resolve the socket path. Should be fixed now.
