### ISSUE TITLE
rtags-company/helm wrong method signature in gmock autocompletion

### ISSUE THREAD

**Issue by Glaeqen** [Andersbakken/rtags#1215]
**Describe the bug**
rtags-company; rtags-helm parses wrongly method signature in case of e.g. gmock and therefore creates not really useful autocompletion template.

**To Reproduce**
1. For instance create test and write EXPECT_CALL macro.
2. Press dot key

**Expected behavior**
Actual usable autocompletion and proper method signature

**Screenshots/Backtrace**
Company:
![Company](https://user-images.githubusercontent.com/20447270/43315517-7ef4eecc-9196-11e8-9b59-8d905a1b468f.png)

Helm:
![Helm](https://user-images.githubusercontent.com/20447270/43315670-fa725904-9196-11e8-97be-43560b92df8d.png)

Incorrect autocompletion after pressing enter in helm/company:
![Incorrect autocompletion after pressing Enter in helm/company](https://user-images.githubusercontent.com/20447270/43315623-cf171bb4-9196-11e8-8bb7-54ec884e29ef.png)

**Environment**
 - OS/Version: [Arch Linux]
 - RTags(rdm,rc): [2.18.125] (from MELPA -> 20180619.823 MELPA versioning)
 - Emacs: [26.1]
 - LLVM/Clang: [6.0.1-1]

**Comment by Andersbakken** [comment]
Sadly this is outside of the domain of RTags. The actual autocompletions originate deep in the guts of libclang and we're a mere middleman for this. I suggest reporting it to the clang people. (This isn't the first such issue I've seen)
