### ISSUE TITLE
latest commit causes never ending indexing ?

### ISSUE THREAD

**Issue by mckellyln** [Andersbakken/rtags#1217]
First of all, thank you so much for rtags, I use it every day and it is awesome :-)

Latest master today (one or all of commits fac76feb, 2397c99c, e5d687b9, 510a61ad) and a complete re-index from scratch (after rc -C) of my project runs seemingly forever, keeps showing msgs such as:

handleInclude failed (nil) inclusion directive include ...

And keeps indexing the same file over and over (among other files):

[ 24%] 227/948 22:20:42 <path-to>/caching.cpp in 1175ms. (3 builds) (2249 syms, 2383 symNames, 9 includes, 3 of 290 files, symbols: 5775 of 49184, 52834 cursors, 2497060 bytes written, 2 queried 0ms) (1045/109/10ms) (dirty). (priority 2)

get repeated over and over with only the timing values slightly different.

I have tried with 8 jobs and also with 1 job and get the same kind of behavior.

This is on ubuntu 16.04 hwe with 4.15.0-30 kernel
/usr/lib/llvm-3.8/lib/libclang-3.8.so.1

Is there some more debug I can enable and rerun and provide to help diagnose ?

**Comment by mckellyln** [comment]
I went back to commit 7003fcab and rebuilt rtags and a reindex of my project from scratch completes quickly.

**Comment by mckellyln** [comment]
A build of rtags from a few months ago (~ May 5) shows:
[100%] 826/828 11:17:46 
so only 828 total files.

**Comment by mckellyln** [comment]
I have found the issue is with rct submodule commit b59102e568de5abaf4f7040ddcc5d0069387a62a
I will debug further to see what exactly from that is the problem.

**Comment by mckellyln** [comment]
Not sure why yet, but this line change is causing the "handleInclude failed (nil) inclusion directive include ..." msgs and never-ending indexing:
```
    if (mode == MakeAbsolute || !sRealPathEnabled) {
        if (isAbsolute()) {
            // problem! canonicalize(changed);
            return true;
        }
```

**Comment by mckellyln** [comment]
ok, I think canonicalize() does not properly handle when '/./' is in the path.

**Comment by mckellyln** [comment]
https://github.com/Andersbakken/rct/pull/76

**Comment by cslux** [comment]
@mckellyln I think we close this now!  If it still doesn't work please reopen this issue.

Christian
