### ISSUE TITLE
Missing rtags v2.19 Git tag in Github

### ISSUE THREAD

**Issue by jetm** [Andersbakken/rtags#1218]
Missing rtags v2.19 Git tag in Github. I maintain rtags package in Arch Linux and by using the tag in GitHub I can make a package release.

This is similar to issue #1013 where it was solved by pushing a Git tag to the repository. In this case v2.19

**Comment by tillt** [comment]
Really confused now - does this possibly mean 2.19 is still in the works, cause why else would this issue be still open after more than a month?

**Comment by jetm** [comment]
I saw now there is a Git tag for 2.20 release. Thank you. I made the AUR release for v2.20.

It's still missing the 2.19 Git tag, but now there is a new release I don't see too much a case for keeping this issue open. Closing it.
