### ISSUE TITLE
Beginner Contributions

### ISSUE THREAD

**Issue by collinjackson93** [Andersbakken/rtags#1219]
I use rtags daily for work and I'd like to contribute, but I'm not too sure where to start. Any recommendations for fairly simple features/bug fixes that don't require an in-depth knowledge of the code? Alternatively, I was thinking of increasing test coverage. Any specific test cases or areas that would benefit from better coverage (maybe completions)?

**Comment by Andersbakken** [comment]
Certainly more autotests in general would be helpful. Completions is I believe 100% devoid of autotests so that would be superuseful.
