### ISSUE TITLE
c++11 range based for-loops issue

### ISSUE THREAD

**Issue by HongxuChen** [Andersbakken/rtags#122]
When dealing with c++ range based for-loops, rtags behaves poorly. Here is an example:

```c++
#include <vector>
#include <string>
#include <iostream>

template <typename T>
class VecWrapper {
  std::vector<T> vect_;

 public:
  /*dest*/VecWrapper(std::vector<T> &vect) : vect_(vect) {}
  std::vector<T> const &getVect() { return vect_; }
};

int main(void) {
  std::vector<int> /*dest wrong*/vect{1, 2, 3, 4};
  for (int &i : /*pos 1*/ vect) {
    i++;
  }
  VecWrapper<int> vectWrapper(vect);
  for (int const &i : /*pos 2*/ vectWrapper./*pos 3*/ getVect()) {
    std::cout << " " << i;
  }
  return 0;
}
```
In the snippet above, when cursor is at `pos 1` or `pos 2`, `rtags-find-symbol-at-point` will lead to the constructor rather than the object itself; for `pos 1` it directs to `bits/stl_vector.h` and for `pos 2` it jumps to `dest` in the snippet. For `pos 3`, rtags finds no definition; it also goes wrong when I rename the VecWrapper::getVect() to VecWrapper::vect(), then rtags mistakenly regards `dest wrong` in the snippet as its defintion.

`rtags-rename-symbol` also suffers from this problem.

BTW, from the results generated by `rtags-taglist`, it seems an internal issues of the way tags generated(however I'm not sure since I still haven't caught a glimpse of the source code, sorry about that).

**Comment by Andersbakken** [comment]
This seems to work now in with clang 3.6.0 from homebrew.
