### ISSUE TITLE
the command of rtags display on emacs buffer

### ISSUE THREAD

**Issue by luluman** [Andersbakken/rtags#1228]
**Describe the bug**
The command of rtags would display on emacs buffer.

**To Reproduce**
1. using mintty terminal ssh to remote access emacs
2. open a  C++ project which rtags has corrected setup
3. find a function and try to call rtags such as "rtags-find-symbol-at-point"
4. the buffer will be polluted and show some commands.

**Expected behavior**
I expected that if there were something rtags could find it will try to jump or doing nothing and show some info in minibuffer if rtags found nothing.

**Screenshots/Backtrace**
The original buffer 
![image](https://user-images.githubusercontent.com/12585858/46127589-b8a25f80-c263-11e8-975b-0c9da2a3b235.png)
But it will be like this
![image](https://user-images.githubusercontent.com/12585858/46127685-00c18200-c264-11e8-9247-aa34c2c42c6d.png)
I need to use Ctrl+l to refresh the display. It's annoying.

**Environment (please complete the following information):**
 - OS/Version: [Ubuntu]
 - RTags(rdm,rc): [2.19.126]
 - Emacs: [26.1]
 - LLVM/Clang: [3.8.0]

**Additional context**
Someone who have any ides about what caused this problem, maybe it's not rtags' problem. I will appreciate any help. Tanks.

**Comment by Abergard** [comment]
Hi @luluman ,

did you try to disable printing to stdout/stderr (e.i. run rdm by `rdm -S`). If you want to have logs you can redirect it to the file by run `rdm --log-file /log/path/rdm.log -S &`

Regards
Lukass
