### ISSUE TITLE
Incomplete Indexing with llvm 7.0.0

### ISSUE THREAD

**Issue by rockypanda** [Andersbakken/rtags#1230]
The indexing of my project is incomplete with llvm 7.0.0. Lots of symbols are missing.
llvm 6.0.1 works just fine.
I'm on MacOs Mojave, and llvm is installed via homebrew.

**Comment by rockypanda** [comment]
Actually llvm 6.0.1 is also missing some symbols.

**Comment by tillt** [comment]
You may want to describe this a bit better, maybe by reducing the problem further into something that can be reproduced.

**Comment by rockypanda** [comment]
Sorry for the late response and also the incomplete description of the issue.

It turns out to be an environment issue. The new command line tool for Xcode 10 somehow does not install the headers to /usr/include. And I have to manually install /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg in order to get those.

Things are working as usual now. Thanks to the developers for this wonderful tool!
