### ISSUE TITLE
Rtags build fails on RedHat7.4

### ISSUE THREAD

**Issue by fperies** [Andersbakken/rtags#1232]
Hello,

I'm trying to compile RTags on a RedHat 7.4 distro but it systematically fails.

Here are the steps to reproduce the issue:
[frperies@localhost:~/rtags/build (master u=)]$ cmake ..
-- The C compiler identification is GNU 6.1.0
-- The CXX compiler identification is GNU 6.1.0
-- Check for working C compiler: /opt/gcc/x86_64/6.1.0/bin/cc
-- Check for working C compiler: /opt/gcc/x86_64/6.1.0/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /opt/gcc/x86_64/6.1.0/bin/c++
-- Check for working CXX compiler: /opt/gcc/x86_64/6.1.0/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- llvm-config executable found: /opt/llvm/x86_64/5.0.0.g610/bin/llvm-config
-- Using Clang version 5.0.0 from /opt/llvm/x86_64/5.0.0.g610-2/lib with CXXFLAGS -I/opt/llvm/x86_64/5.0.0.g610-2/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-- Found LibClang: /opt/llvm/x86_64/5.0.0.g610-2/lib/libclang.so  
-- Performing Test LIBCLANG_COMPILES
-- Performing Test LIBCLANG_COMPILES - Success
-- Performing Test CXX_11_EXTENDED_REGEX_SUPPORT
-- Performing Test CXX_11_EXTENDED_REGEX_SUPPORT - Failed
CMake Error at src/CMakeLists.txt:113 (message):
  **Compiler with complete C++11 support required ( >= GCC 4.9 or >= Clang 3.3)**

-- Configuring incomplete, errors occurred!
See also "/home/frperies/rtags/build/CMakeFiles/CMakeOutput.log".
See also "/home/frperies/rtags/build/CMakeFiles/CMakeError.log".

This error message doesn't seem exact because all prerequisites are installed:
[frperies@localhost:~/rtags/build (master u=)]$ gcc -v
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/gcc/x86_64/6.1.0-2/libexec/gcc/x86_64-redhat-linux/6.1.0/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/opt/gcc/x86_64/6.1.0-2 --exec-prefix=/opt/gcc/x86_64/6.1.0-2 --bindir=/opt/gcc/x86_64/6.1.0-2/bin --sbindir=/opt/gcc/x86_64/6.1.0-2/sbin --sysconfdir=/opt/gcc/x86_64/6.1.0-2/etc --datadir=/opt/gcc/x86_64/6.1.0-2/share --includedir=/opt/gcc/x86_64/6.1.0-2/include --libdir=/opt/gcc/x86_64/6.1.0-2/lib --libexecdir=/opt/gcc/x86_64/6.1.0-2/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/opt/gcc/x86_64/6.1.0-2/man --infodir=/opt/gcc/x86_64/6.1.0-2/info --with-docdir=/opt/gcc/x86_64/6.1.0-2/doc --enable-shared --enable-languages=c,c++ --enable-threads=posix --enable-checking=release --with-system-zlib --disable-libunwind-exceptions --enable-libssp --enable-lto --with-gnu-ld --verbose --disable-gtktest --target=x86_64-redhat-linux --build=x86_64-redhat-linux --host=x86_64-redhat-linux --enable-__cxa_atexit
Thread model: posix
**gcc version 6.1.0 (GCC)**

[frperies@localhost:~/rtags/build (master u=)]$ llvm-config --version
**5.0.0**

[frperies@localhost:~/rtags/build (master u=)]$ clang -v
**clang version 5.0.0 (tags/RELEASE_500/final)**
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/llvm/x86_64/5.0.0.g610/bin
Found candidate GCC installation: /opt/rh/devtoolset-6/root/usr/lib/gcc/x86_64-redhat-linux/6.3.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.5
**Selected GCC installation: /opt/rh/devtoolset-6/root/usr/lib/gcc/x86_64-redhat-linux/6.3.1**
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64

[frperies@localhost:~/rtags/build (master u=)]$ cmake --version
**cmake version 2.8.12.2**

**Environment:**
 - OS/Version: Linux RHEL7.4
 - RTags(rdm,rc): 2.20.126
 - Emacs: 26.1
 - LLVM/Clang: 5.0.0

Please find enclosed files CMakeOutput.log and CMakeError.log (I don't see any obvious errors in there)
[CMakeError.log](https://github.com/Andersbakken/rtags/files/2437945/CMakeError.log)
[CMakeOutput.log](https://github.com/Andersbakken/rtags/files/2437947/CMakeOutput.log)

Thank you for your support.
Regards

**Comment by cslux** [comment]
You have more GCC versions installed, and I think GCC is picking the wrong libstdc++ library. 

Just a guess.

**Comment by fperies** [comment]
@cslux , thank you for your answer.

So, I've removed useless GCC versions and clang now sees only one GCC version:
[frperies@localhost:~]$ clang -v
clang version 5.0.0 (tags/RELEASE_500/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/llvm/x86_64/5.0.0.g610/bin
**Found candidate GCC installation: /opt/rh/devtoolset-6/root/usr/lib/gcc/x86_64-redhat-linux/6.3.1
Selected GCC installation: /opt/rh/devtoolset-6/root/usr/lib/gcc/x86_64-redhat-linux/6.3.1**
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64

but now, the error has changed into:
[frperies@localhost:~/rtags/build (master u=)]$ cmake ..
-- The C compiler identification is GNU 6.3.1
-- The CXX compiler identification is GNU 6.3.1
-- Check for working C compiler: /opt/rh/devtoolset-6/root/usr/bin/cc
-- Check for working C compiler: /opt/rh/devtoolset-6/root/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /opt/rh/devtoolset-6/root/usr/bin/c++
-- Check for working CXX compiler: /opt/rh/devtoolset-6/root/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- llvm-config executable found: /opt/llvm/x86_64/5.0.0.g610/bin/llvm-config
-- Using Clang version 5.0.0 from /opt/llvm/x86_64/5.0.0.g610-2/lib with CXXFLAGS -I/opt/llvm/x86_64/5.0.0.g610-2/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-- Found LibClang: /opt/llvm/x86_64/5.0.0.g610-2/lib/libclang.so  
-- Performing Test LIBCLANG_COMPILES
-- Performing Test LIBCLANG_COMPILES - Failed
CMake Error at src/CMakeLists.txt:88 (message):
  **Failed to compile small clang test app.**

  **It's likely that the include file <clang-c/Index.h> could not be found!**

  **Maybe you need to install the clang development package?**

  See CMakeFiles/CMakeError.log for more info.

-- Configuring incomplete, errors occurred!
See also "/home/frperies/rtags/build/CMakeFiles/CMakeOutput.log".
See also "/home/frperies/rtags/build/CMakeFiles/CMakeError.log".

see CMake*.log in attached.
[CMakeError.log](https://github.com/Andersbakken/rtags/files/2438863/CMakeError.log)
[CMakeOutput.log](https://github.com/Andersbakken/rtags/files/2438864/CMakeOutput.log)

This time some undefined references come in..Any other clues ?

Thanks
Regards

**Comment by cslux** [comment]
@fperies now the clang-devel package is missing.

```
sudo yum whatprovides */clang-c/Index.h

sudo yum install clang5.0-devel
# or
sudo yum install clang-devel
```

regards,
Christian

**Comment by fperies** [comment]
@cslux: I've installed the clang-devel package and I now have headers files but the same error is still there.

[frperies@localhost:\~/rtags/build (master u=)]$ sudo yum install llvm-private-devel-5.0.0-3.el7.x86_64
frperies@localhost:\~/rtags/build (master u=)]$ rpm -ql llvm-private-devel-5.0.0-3.el7.x86_64 | grep Index
**/usr/include/llvm-private/clang-c/Index.h**
/usr/include/llvm-private/clang/Basic/DiagnosticIndexName.inc
/usr/include/llvm-private/clang/Index
...
According to errors reported in file CMakeError.log I think the error message is not relevant here (and maybe need to be improved). 
The errors I get is related to missing symbols from lib libclang.so:
...
/opt/rh/devtoolset-6/root/usr/bin/c++    -I/opt/llvm/x86_64/5.0.0.g610-2/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DLIBCLANG_COMPILES  -I/opt/llvm/x86_64/5.0.0.g610-2/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS    CMakeFiles/cmTryCompileExec115882729.dir/src.cxx.o  -o cmTryCompileExec115882729 -rdynamic /opt/llvm/x86_64/5.0.0.g610-2/lib/libclang.so -Wl,-rpath,/opt/llvm/x86_64/5.0.0.g610-2/lib 
/opt/llvm/x86_64/5.0.0.g610-2/lib/libclang.so: **undefined reference** to \`VTT for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/opt/llvm/x86_64/5.0.0.g610-2/lib/libclang.so: **undefined reference to** \`std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const@GLIBCXX_3.4.21'
/opt/llvm/x86_64/5.0.0.g610-2/lib/libclang.so: **undefined reference** to \`std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)@GLIBCXX_3.4.21'
/opt/llvm/x86_64/5.0.0.g610-2/lib/libclang.so: **undefined reference** to \`std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)@GLIBCXX_3.4.21'
/opt/llvm/x86_64/5.0.0.g610-2/lib/libclang.so: **undefined reference** to \`std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const@GLIBCXX_3.4.21'
/opt/llvm/x86_64/5.0.0.g610-2/lib/libclang.so: **undefined reference** to \`std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::_Ios_Openmode)@GLIBCXX_3.4.21'

Could you please advise ?
Where those symbols are expected to be ? 
Is there any lib missing in the link command ?

Thanks 
Regards

**Comment by cslux** [comment]
@fperies Did you removed the build directory before rebuilding?

**Comment by cslux** [comment]
@fperies the problem could also be that libclang.so was built with a different libstdc++. The symbols are expected to be in libstdc++.

**Comment by fperies** [comment]
@cslux Yes,  I've removed the build directory before trying again. 
By looking to some StackOverflow threads,  I'm wondering if those symbols are expected to be in libstdc++ or in **libc++** (which seems to be the Standard C++ lib for Clang).

**Comment by fperies** [comment]
@cslux You were right, those symbols are expected to be in libstdc++.so
I've finally managed in compiling RTags by copying lib libstdc++.so with the right version into the COMPILER_PATH of /opt/rh/devtoolset-6/root/usr/bin/c++.

This seems a little bit handcrafted but it works !

Thank you very much for your support !!
Regards

**Comment by cslux** [comment]
@fperies Glad to hear you got it running.

Yeah, it indeed seems a little bit handcrafted :-)

regards,
Christian

**Comment by atejeda** [comment]
One can circumvent all that by using the `scl enable` command, e.g.:
    scl enable devtoolset-6 'cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 .'
    make
In my case I had to build cmake first and llvm later, having the binaries of those in my $PATH to build rtags was enough.
