### ISSUE TITLE
Rtags with cross compile environment  (Yocto - Arm)

### ISSUE THREAD

**Issue by Carl2** [Andersbakken/rtags#1236]
Hi,
Im trying to use rtags together with an SDK built with Yocto that is based on ARM.
I have tried several different configuration of RDM using isystem and other, but still fail miserably when it comes to include std-headers.

```
rdm --no-libclang-include-path \
    --enable-compiler-manager \
    -I /opt/ocp/4.3.2/sysroots/cortexa7hf-neon-poky-linux-gnueabi/usr/include \
    --isystem /opt/ocp/4.3.2/sysroots/cortexa7hf-neon-poky-linux-gnueabi/usr/include/c++/7.3.0 \
    --isystem /opt/ocp/4.3.2/sysroots/cortexa7hf-neon-poky-linux-gnueabi/usr/include/c++/7.3.0/arm-poky-linux-gnueabi \
    --exclude-filter "*/CMakeFiles/*;*/.git/*;*/build/*"
```

Unfortunatly this doesn't seem to do it either
The Yocto enviroment set CXX to:

`arm-poky-linux-gnueabi-g++  -march=armv7ve -marm -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a7 --sysroot=/opt/ocp/4.4.0/sysroots/cortexa7hf-neon-poky-linux-gnueabi`

The rdm output is:

```
handleInclude failed (nil) inclusion directive include cstdlib 
<path>/service/main.cpp:1:1
handleInclude failed (nil) inclusion directive include iostream 
<path>/service/main.cpp:2:1
.
.
.
.
```

One issue that i noticed is that clang uses [triple](https://clang.llvm.org/docs/CrossCompilation.html) to x-compile while, gcc uses ` -march=`, the march is not recongisable by clang..I don't know if its an issue.
Can you give me a hint on how to do this, i kind of hit the wall at this point.

Another question which is kind of related is the diagnostics is how to turn it off. I've tried several different ways e.g:
`rtags-toggle-diagnostics-suspended` and `rtags-stop-diagnostics` but both of them seem to be turned on after some event (e.g switching buffer). Is there away to turn it of for good?
The reason is that since rtag doesn't find string include directives it kind of bloats my code with alot of errors. 

Thanks!
Calle

**Comment by cslux** [comment]
Hi @Carl2!

What I always did when I was using RTags for an ARM project, is to convert the compilation database to clang equivalent options (using `sed` e.g.). Like as you already recognized, `-march`, and stuff like that. Some options maybe need to be removed altogether. When you do that, starting rdm with the option `--enable-compiler-manager` should be enough. Try it for one compilation unit, and if it works use sed (or whatever else) to automate it.

 I left all the scripts at my former employer...damn 🤦‍♂️

Regarding diagnostics, maybe you try setting `rtags-autostart-diagnostics` to nil.

Christian

**Comment by Carl2** [comment]
Thanks, 
I'll try that  :)

**Comment by ekoczwara** [comment]
Why this issue is closed? I don't get it.

I have exactly the same problem. I have CMake based project mainly to get compile_commands.json for free and now it looks like it is useless and I need to fix it manually. 

But there are other issues. I need often switch between embedded/desktop targets. Should I clean rdm cache with -C and reparse everything each time? Should I run rdm with different parameters (depending on my target)? Maybe I should run multiple rdm instances with separate cache databases for every project?

**Comment by Carl2** [comment]
I would suggest using [Bear](https://github.com/rizsotto/Bear)
To create _compile_command.json_ that together with _--enable-compiler-manager_ for rdm made my day.
But beware if you are using ccache (turn it off before using bear), and make sure you use make clean before
`bear make` 
e.g
`cd build_dir && cmake .. && bear make`

**Comment by ekoczwara** [comment]
@Carl2 

Indeed I'm using `ccache`, thanks for the tip!

Are you saying that `bear` generates different `compile_commands.json` than `cmake`?
