### ISSUE TITLE
auto-complete-mode support

### ISSUE THREAD

**Issue by Damenly** [Andersbakken/rtags#1237]
Hi,
Thanks first for developing the useful tool. Rtags run quite well on my PC and laptop.
I see the auto-complete-mode feature is on TODO list. Just gentle asking for your plan about
the feature. :)

**Comment by cslux** [comment]
@Damenly  Do you mean ac-rtags.el?

**Comment by cslux** [comment]
RTags does not follow this pattern, there is no rtags minor mode you need to enable. If rtags it's loaded its available in the supported modes. No need to call `rtags-mode`, which by the way is used internally by rtags for specific rtags buffers. 

> Or this function is just not on rtags' plan?

Not really planned, though considered. But yeah, if it ain't broke don't fix it :-D
