### ISSUE TITLE
Failed to build due to C++ 11 support while I have gcc 5.4 installed

### ISSUE THREAD

**Issue by wenzhaoduo** [Andersbakken/rtags#1239]
cmake \
  "$HOME"/local/rtags \
  -DCMAKE_C_COMPILER=/usr/local/bin/gcc \
  -DCMAKE_CXX_COMPILER=/usr/local/bin/g++ \

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/local/bin/gcc
-- Check for working C compiler: /usr/local/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/bin/g++
-- Check for working CXX compiler: /usr/local/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- llvm-config executable found: /usr/local/bin/llvm-config
-- Using Clang version 8.0.0svn from /usr/local/lib with CXXFLAGS -I/usr/local/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-- Found LibClang: /usr/local/lib/libclang.so
-- Performing Test LIBCLANG_COMPILES
-- Performing Test LIBCLANG_COMPILES - Success
-- Performing Test CXX_11_EXTENDED_REGEX_SUPPORT
-- Performing Test CXX_11_EXTENDED_REGEX_SUPPORT - Failed
CMake Error at src/CMakeLists.txt:113 (message):
  Compiler with complete C++11 support required ( >= GCC 4.9 or >= Clang 3.3)

-- Configuring incomplete, errors occurred!
See also "/home/zhaoduo/local/rtags/build/CMakeFiles/CMakeOutput.log".
See also "/home/zhaoduo/local/rtags/build/CMakeFiles/CMakeError.log".

**Comment by cslux** [comment]
@wenzhaoduo This is an issue with your OS. You may have a look at this issue https://github.com/Andersbakken/rtags/issues/1232.

It's picking the wrong libstdc++ library.

Please fill out the issue template form the next time, it would make it a lot easier for us, thank you!

Christian
