### ISSUE TITLE
When listing locations in Emacs 26.1, rtags opens new window, not mini-buffer

### ISSUE THREAD

**Issue by collinjackson93** [Andersbakken/rtags#1249]
**Describe the bug**
When running rtags-find-all-references-at-point or rtags-list-virtuals-at-point, instead of listing all the results in the minibuffer, it opens a new window pointed to one of them. I noticed this after updating rtags, emacs, and all packages.

**To Reproduce**
1. Run rtags-find-all-references-at-point

**Expected behavior**
The minibuffer is populated with the list of all references

**Screenshots/Backtrace**
If applicable, add screenshots or/and a backtrace.

**Environment (please complete the following information):**
 - OS/Version: CentOS 7.3
 - RTags(rdm,rc): 2.20.126
 - Emacs: 26.1
 - LLVM/Clang: 5.0.0

**Additional context**
I'm not too familiar with emacs jargon, so minibuffer may not be the correct term. I am using ivy. I cannot get the issue to go away by installing an older version of rtags, so it could be a problem with the new version of emacs? Unfortunately, I didn't notice the issue until I finished updating everything, so it will be hard for me to track down exactly which update caused the problem.

**Comment by collinjackson93** [comment]
I rolled back to emacs 25.3 and confirmed that the issue no longer occurs

**Comment by cslux** [comment]
I'm afraid, but can't reproduce this on my Fedora 28 machine using Emacs 26.1.90.

Shows the *RTags* Buffer in a new window.

![screenshot from 2018-11-17 19-43-03](https://user-images.githubusercontent.com/1712313/48664580-09367c00-eaa1-11e8-9cbb-e3f1ab93d812.png)

**Comment by cslux** [comment]
Do you have a screenshot?

**Comment by collinjackson93** [comment]
I just re-installed emacs 26.1 to get a screenshot and was unable to reproduce. Not sure what happened last time, but glad it's not a real problem. Thanks for looking into it so quickly!

**Comment by cslux** [comment]
@collinjackson93 Glad to hear!

**Comment by collinjackson93** [comment]
Somehow, it started happening again. See below for a screen grab of it in action. I haven't made any changes/updates to emacs or rtags since it was last working.

![screen recording 2018-11-21 at 3 07 54 pm mov](https://user-images.githubusercontent.com/5580739/48950901-4caa4380-ef02-11e8-81ec-9f010fdf5fdb.gif)

**Comment by cslux** [comment]
Or can you step through the code using `edebug`?

**Comment by collinjackson93** [comment]
I'm not familiar with debugging elisp, but when I started poking around, I renamed the byte-compiled rtags file so I could hopefully set breakpoints in the source code. I found that when the byte-compiled file is renamed (so emacs has to load the source file), the problem does not occur.

I also tried to reproduce using `emacs -Q`, but I couldn't figure out how to force emacs to load the byte-compiled file. It kept defaulting to use the non-compiled one.

**Comment by collinjackson93** [comment]
Thanks so much for the help! Manually doing the bytecompile did not make a difference, but running emacs without the other packages still does not have the issue. 

At this point, I'm fairly certain that another package is somehow conflicting with rtags. Thanks again for all the assistance!
