### ISSUE TITLE
rtags can not find include

### ISSUE THREAD

**Issue by weijietong** [Andersbakken/rtags#1251]
**Describe the bug**

When I try to index https://github.com/yandex/ClickHouse master branch using the command `rc -J .` , I got a repeatedly error message :
 `handleInclude failed (nil) inclusion directive include variant /home/XXX/ClickHouse/build/../dbms/src/Dictionaries/ComplexKeyCacheDictionary.h:6:1
handleInclude failed (nil) inclusion directive include shared_mutex /home/XXX/ClickHouse/build/../dbms/src/Dictionaries/ComplexKeyCacheDictionary.h:8:1`

That is it can not handle `#include <variant>` and `#include <shared_mutex>`.

The index process can't be end.

**Screenshots/Backtrace**

![image](https://user-images.githubusercontent.com/728692/48669002-01281c00-eb35-11e8-84f0-eb2072936f5a.png)

**Environment (please complete the following information):**
 - OS/Version: [e.g. iOS; Fedora 26; Ubuntu]
Red Hat 4.8.5-4
 - RTags(rdm,rc): 
2.20.126
 - Emacs: 
24.4
 - LLVM/Clang:
clang version 7.0.0 (tags/RELEASE_700/final)

**Comment by cslux** [comment]
I cant reproduce this on Fedora 28!

**Comment by cslux** [comment]
Do you have multiple compiler versions installed beside clang 7
