### ISSUE TITLE
RTags 2.21 released on melpa-stable missing on github/git

### ISSUE THREAD

**Issue by DirtYiCE** [Andersbakken/rtags#1257]
**Describe the bug**
The latest release on melpa-stable is 2.21, while the latest tag/release on github is only 2.20. The link at melpa-stable points to https://github.com/Andersbakken/rtags/tree/a978e3330e6727124bb845e2385ca52393311b71 which looks like release 2.21 but if I clone the repo it's missing and it doesn't seem to be reachable from any branches or tags.

**To Reproduce**
1. Update rtags to 2.21 from melpa-stable
2. It bails out with protocol mismatch
3. Try to download rtags 2.21
4. Fail

**Expected behavior**
Tag that commit or remove the release from melpa.

**Environment (please complete the following information):**
 - OS/Version: Gentoo linux
 - RTags(rdm,rc): can't download
 - Emacs: 26.1
 - LLVM/Clang: 7.0.0

**Comment by cslux** [comment]
Whoops! That was me! It points to a commit which "doesn't" exists
anymore. When I set up CI/CD, and tested the release process I created a tag
2.21 which I removed afterwards, this turns now out, that this was the wrong
way to test it. 

I actually don't know right now if it is enough to create a new tag 2.21, or
if a tag 2.22 is required.

Thanks for reporting!

I'll look into that.

**Comment by cslux** [comment]
@DirtYiCE I created a new release 2.21, hopefully MELPA picks this new tag even so its the same version.
