### ISSUE TITLE
"C++ SOURCE FILE Test LIBCLANG_COMPILES" fails, missing -lpthread.

### ISSUE THREAD

**Issue by martincmartin** [Andersbakken/rtags#1262]
**Describe the bug**
Early on, in cmake, it fails to compile:
```
#include <clang-c/Index.h>

int main()
{
    CXIndex index = clang_createIndex(0, true);
    CXTranslationUnit unit = clang_parseTranslationUnit(index, 0, 0, 0, 0, 0, 0);
    clang_disposeTranslationUnit(unit);
    clang_disposeIndex(index);
    return 0;
}
```

libclang.so has undefined reference to various pthread symbols.

llvm-config --system-libs says these are needed:

$ llvm-config --system-libs
-lz -lrt -ldl -lpthread -lm

**To Reproduce**
run "cmake" with various fancy arguments that shouldn't matter.  I'm happy to debug on my end if you tell me what I can run/do to debug.

**Expected behavior**
cmake cam compile a simple program that calls libclang.

**Environment (please complete the following information):**
 - OS/Version: CentOS 7
 - RTags(rdm,rc): Trunk from Nov. 27, 2018
 - Emacs: n/a
 - LLVM/Clang: 7.0.20180201

**Comment by cslux** [comment]
Do you use GCC or CLANG to build RTags?

**Comment by cslux** [comment]
Can you post the output of this simple test program, i.g. the cmake error log,
etc.

You could use the simple program used in the cmake file to debug the problem.

**Comment by martincmartin** [comment]
I use gcc.

I can post the output.  However, the problem is easy to see: when linking the test program, we don't include the output of "llvm-config --system-libs" on the compilation command line.
[CMakeError.log](https://github.com/Andersbakken/rtags/files/2621176/CMakeError.log)

**Comment by cslux** [comment]
@martincmartin Can you try 5870fb6?

**Comment by martincmartin** [comment]
That commit, and the one before it, fail with "Could NOT find clang include path.  You can fix this by setting
  LIBCLANG_CXXFLAGS in your shell or as a cmake variable."  Let me see if setting that fixes things.

**Comment by martincmartin** [comment]
This seems to have fixed the problem.  However, I now have a different problem: the linker can't find -lz.  I think this is a problem on my end, I'll follow up here.  Thanks!

**Comment by martincmartin** [comment]
Actually, this may be a problem with the cmake file:  I'm setting -DZLIB_LIBRARY="$TP2"/zlib/lib/libz.so on the cmake command line.  Maybe that directory needs to be added with -L ?

If I just disable this test, the rest of the configure & build works just fine.  Perhaps this test can be re-tooled to do whatever you do for rdm?

**Comment by cslux** [comment]
> Actually, this may be a problem with the cmake file:  I'm setting -DZLIB_LIBRARY="$TP2"/zlib/lib/libz.so on the cmake command line.  Maybe that directory needs to be added with -L ?
>
> If I just disable this test, the rest of the configure & build works just fine.  Perhaps this test can be re-tooled to do whatever you do for rdm?

Use ccmake to set it! For me the variable is called ZLIB_LIBRARY_RELEASE and
ZLIB_LIBRARY_DEBUG respectively.

You can use cmake to list all variables `cd rtags; cmake -LA PATH .`

What is wrong with CentoOS? :-)
