### ISSUE TITLE
cmake fails with clang v7.0.0

### ISSUE THREAD

**Issue by sophana** [Andersbakken/rtags#1268]
**Describe the bug**
Can't compile on centos7, using clang v7.0.0 installed from conda

**To Reproduce**
install miniconda
conda install clang
cmake .

$ cmake ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- llvm-config executable found: /home/skok/pkgs/miniconda2/bin/llvm-config
-- Using Clang version 7.0.0 from /home/skok/pkgs/miniconda2/lib with CXXFLAGS -I/home/skok/pkgs/miniconda2/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-- Found LibClang: /home/skok/pkgs/miniconda2/lib/libclang.so  
-- Performing Test LIBCLANG_COMPILES
-- Performing Test LIBCLANG_COMPILES - Success
-- Performing Test CXX_11_EXTENDED_REGEX_SUPPORT
-- Performing Test CXX_11_EXTENDED_REGEX_SUPPORT - Failed
CMake Error at src/CMakeLists.txt:113 (message):
  The compiler uses a libstdc++ without c++11 regex support.

**Expected behavior**
should not fail

**Screenshots/Backtrace**

**Environment (please complete the following information):**
 - OS/Version: centos 7.2
 - RTags(rdm,rc): git master 772fdae0a22626f2c2031cd29e1fe2b340e8d208
 - Emacs: [e.g. 24.5]
 - LLVM/Clang: 7.0.0

**Additional context**

What is strange is that I can compile the regex test using the command

```
clang++ -std=c++11 -I/home/skok/pkgs/miniconda2/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS test.cpp
```

**Comment by cslux** [comment]
@sophana Thats a problem with libstdc++, see #1239, #1232

**Comment by cslux** [comment]
@sophana Clang != LLVM

**Comment by sophana** [comment]
How is the cmake test done then?

**Comment by sophana** [comment]
gcc also compiles the test

**Comment by cslux** [comment]
In your case with GCC. You could try using clang instead of GCC.

**Comment by cslux** [comment]
What does the CMakeOutput.log or/and CMakeError.log say?

**Comment by cslux** [comment]
You could also use the `cmake` flag `--debug-trycompile`, it will keep the generated test directories. In one of that directory is the test setup for the `CXX_11_EXTENDED_REGEX_SUPPORT` test, so no src file unless it was the last test to run. 

Directory path to those directories `CMakeFiles/CMakeTmp/CMakeFiles/`

**Comment by sophana** [comment]
It uses system gcc. compilation is ok, but the execution return value is -1
```
/usr/bin/c++    -I/home/skok/pkgs/miniconda2/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DCXX_11_EXTENDED_REGEX_SUPPORT -std=c++11    CMakeFiles/cmTC_7c586.dir/src.cxx.o  -o cmTC_7c586 -rdynamic 
gmake[1]: Leaving directory `/home/skok/pkgs/rtags/b/CMakeFiles/CMakeTmp'

Return value: 255
Source file was:

#include <regex>

int main()
{
  try {
    std::regex rx("^(.*):([0-9]+):([0-9]+):?-:?([0-9]+):([0-9]+):?(@[A-Za-z,]+)?", std::regex_constants::extended);
  } catch (std::regex_error& e) {
    return -1;
  }

  return 0;
}
```
```
$ c++ -v
Using built-in specs.
COLLECT_GCC=c++
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) 
```
using system compiler without conda or clang does the same.

```
$ rpm -q libstdc++
libstdc++-4.8.5-16.el7_4.2.x86_64
libstdc++-4.8.5-16.el7_4.2.i686
```

**Comment by cslux** [comment]
Thats because your libstdc++ version hasn't full regex support. You need at
least GCC 4.9 (libstdc++-4.8.9)
