### ISSUE TITLE
Autocompletion for anonymous structs is buggy

### ISSUE THREAD

**Issue by akuukka** [Andersbakken/rtags#1269]
When using with Emacs and Company, choosing an anonymous member adds an extra "(anonymous)" text which shouldn't be there.

**To Reproduce**
Consider the following case:
```
struct A {
 int member;
 struct {
  int anotherMember;
 } anonMember;
};

A a;
a.
```

Now, when we write a. and get the autocomplete list, you get two choices:

```
member
anonMember(anonymous)
```

Now this is OK. But if you choose the second one, anonMember(anonymous), the "(anonymous)" part is actually also inserted into the code.

I tend to use anonymous structs quite a lot, so this a big nuisance.

Hopefully there is an easy way to fix it. Thank you for rtags - my life wouldn't be the same without it!

**Comment by Andersbakken** [comment]
Better late than never. Thanks for the report.
