### ISSUE TITLE
Diagnostics in XML mode do not show "note". 

### ISSUE THREAD

**Issue by tillt** [Andersbakken/rtags#1274]
**Describe the bug**
diagnostics in JSON mode show more details than XML mode does.

**To Reproduce**

test.cpp:
```
#include <iostream>

int main(int argc, char const *argv[]) {
  std::cout << "Foo" << endl;
  return 0;
}
```

Index the above and trigger diagnostic output:
```
$ rc --diagnose test.cpp
```

Running `RDM` diagnostics in JSON mode;
```
$ rc --json -m |jq
{
  "checkStyle": {
    "test.cpp": [
      {
        "children": [
          {
            "column": 1,
            "file": "/usr/local/Cellar/llvm/7.0.0_1/include/c++/v1/ostream",
            "line": 999,
            "message": "'std::endl' declared here",
            "type": "note"
          }
        ],
        "column": 25,
        "length": 4,
        "line": 4,
        "message": "Semantic Issue: use of undeclared identifier 'endl'; did you mean 'std::endl'?",
        "type": "fixit"
      }
    ]
  }
}
```

Running `RDM` diagnostics in XML mode;
```
$ rc -m
<?xml version="1.0" encoding="utf-8"?>
  <checkstyle>
    <file name="test.cpp">
      <error line="4" column="25" length="4" severity="fixit" message="Semantic Issue: use of undeclared identifier 'endl'; did you mean 'std::endl'?"/>
    </file>
  </checkstyle>
```

As we see, the JSON data get an addition child of type "note" which is not present in the XML variant. 

**Expected behavior**
I would have expected the XML output to contain a child element covering the information as shown for the "child" element within the JSON data. 

**Environment (please complete the following information):**
 - OS/Version: macOS
 - RTags(rdm,rc): 2.21.126

**Comment by Andersbakken** [comment]
Better late than never. Should be fixed now. Thanks for the report.
