### ISSUE TITLE
Support compile_flags.txt

### ISSUE THREAD

**Issue by root42** [Andersbakken/rtags#1280]
In some projects it is not needed or possible to easily create a compile_commands.json due to the project size or build tool in use. Instead of the compile_commands.json Clang also supports a file compile_flags.txt, which simply contains one flag per line to be passed to Clang.

rtags should be able to detect the compile_flags.txt when there is no compile_commands.json, and similar to gtags or the like index all c++ sources below that file in the tree, possible with configurable file suffixes, like gtags allows (e.g. for non-standard file endings, such as .inl, .hh etc).

Currently I am using gtags since my project is so large and using a non standard build tool that I can't create the compile_commands.json easily. The compile_flags.txt would a quick alternative.

**Comment by root42** [comment]
I think it already supports the file... I noticed a change when compile_flags.txt is present, I can't use rdm on that project anymore at all... Maybe the integration is not complete? Not sure...

**Comment by Andersbakken** [comment]
Sorry about the super-late reply. I'm not sure this really fits RTags' model very well. I would recommend using bear (https://github.com/rizsotto/Bear) to generate compile_commands.json
