### ISSUE TITLE
Does rtags works on Windows?

### ISSUE THREAD

**Issue by tomasorti** [Andersbakken/rtags#1285]
**Is your feature request related to a problem? Please describe.**
I am trying to compile *rtags* on Windows 10, but I am not able to do it.
I get an error due to the lack of *llvm-config*, which is not present.

**Describe the solution you'd like**
I am asking it, because I have spent quite time, and I am not sure Windows 10 is really supported.
So I would like a clarification if Windows is supported.

**Additional context**
I have tried to compile *rtags* with Microsoft compiler and also with MinGW.
But I always get:

```
~\.emacs.d\rtags\build
$ cmake ..
CMake Error at cmake/FindLibClang.cmake:84 (message):
  Could NOT find llvm-config executable and LIBCLANG_CXXFLAGS is not set
Call Stack (most recent call first):
  src/CMakeLists.txt:66 (find_package)
```

Before downloading *clang* in order to compile it by myself and get an *llvm-config.exe*, I would like to know if *rtags* is ready for Windows 10.

Thank you!

**Comment by tomasorti** [comment]
Well, it seems he has stopped the efforts to continue:
https://github.com/Andersbakken/rtags/issues/770#issuecomment-457703313

So the answer is tha *rtags* does NOT support Windows.

**Comment by cslux** [comment]
> So the answer is tha rtags does NOT support Windows.

That's correct!

**Comment by mohkale** [comment]
Shame 😢.

**Comment by centuryx476** [comment]
Is Windows still unsupported ?
