### ISSUE TITLE
RDM failing to produce symbol database

### ISSUE THREAD

**Issue by cengizkandemir** [Andersbakken/rtags#1291]
**Describe the bug**
RDM logs

> Running with 12 jobs, using args: -ferror-limit=50 -Wall -fspell-checking -Wno-unknown-warning-option
> Includepaths: "-isystem" /usr/lib/llvm-7/lib/clang/7.0.1/include/

but doesn't populate cache directory. It sometimes produces a database, sometimes it doesn't.

**To Reproduce**
I compiled hash cb9f55fa3524af3c66e81851c3ed641ea4d4091d on a debian 9 machine. Some packages are from stretch backports, but should be highly stable regardless. After successful compilation and install, I have created two files for systemd, as suggested in wiki page. The only modification I made is the following line

ExecStart=/usr/local/bin/rdm --verbose --inactivity-timeout 300 --log-flush --start-suspended --data-dir=%h/.rtags/rtags-cache --log-file=%h/.rtags/rdm.log

I run the following command to invoke rdm

`rc -J ./compile_commands.json -v`

**Expected behavior**
I am not quite sure how to check if a symbol database is properly created. RDM logs pretty much nothing.

**Environment:**
 - OS/Version: Debian 9
 - RTags(rdm,rc): cb9f55fa3524af3c66e81851c3ed641ea4d4091d
 - Emacs: 07f8f9bc5a (26.1)
 - LLVM/Clang: 7

**Additional context**
I do not know how to understand whether a symbol database is created successfully or not, I am judging this, at the moment, based on population of cache directory. Furthermore, rdm doesn't seem to respect --config option, and sometimes ignores .rdmrc as well. I can provide further information if needed.

The log file is created with the log above. Cache directory is also created with "fileids" and ".currentProject" files.

**Comment by cslux** [comment]
So nothing happens when load some compilation commands with =rc=? 



On 10 February 2019 15:37:12 CET, Cengiz Kandemir <notifications@github.com> wrote:
>**Describe the bug**
>RDM logs
>
>> Running with 12 jobs, using args: -ferror-limit=50 -Wall
>-fspell-checking -Wno-unknown-warning-option
>> Includepaths: "-isystem" /usr/lib/llvm-7/lib/clang/7.0.1/include/
>
>but doesn't populate cache directory. It sometimes produces a database,
>sometimes it doesn't.
>
>**To Reproduce**
>I compiled hash cb9f55fa3524af3c66e81851c3ed641ea4d4091d on a debian 9
>machine. Some packages are from stretch backports, but should be highly
>stable regardless. After successful compilation and install, I have
>created two files for systemd, as suggested in wiki page. The only
>modification I made is the following line
>
>ExecStart=/usr/local/bin/rdm --verbose --inactivity-timeout 300
>--log-flush --start-suspended --data-dir=%h/.rtags/rtags-cache
>--log-file=%h/.rtags/rdm.log
>
>**Expected behavior**
>I am not quite sure how to check if a symbol database is properly
>created. RDM logs pretty much nothing.
>
>**Screenshots/Backtrace**
>If applicable, add screenshots or/and a backtrace.
>
>**Environment (please complete the following information):**
> - OS/Version: Debian 9
> - RTags(rdm,rc): cb9f55fa3524af3c66e81851c3ed641ea4d4091d
> - Emacs: 07f8f9bc5a (26.1)
> - LLVM/Clang: 7
>
>**Additional context**
>I do not know how to understand whether a symbol database is created
>successfully or not, I am judging this based on population of cache
>directory. Furthermore, rdm doesn't seem to respect --config option,
>and sometimes ignores .rdmrc as well. I can provide further information
>if needed.

-- 
Christian Schwarzgruber
T: +43 699 194 166 34
E: c.schwarzgruber.cs@gmail.com

**Comment by cengizkandemir** [comment]
This message is printed.

> [Server] Compilation database loading...

I forgot to add this to initial post.

**Comment by cslux** [comment]
Start rdm manually in a terminal like that `rdm -vvv` to get full verbosity.

**Comment by cengizkandemir** [comment]
The problem was --start-suspended. For some reason, when that option is given, the daemon does pretty much nothing. Maybe I am misusing it, but that's an option suggested in the wiki. I am observing a log starting with something like [100%] 176/176 21:43:59, which probably means the symbols db is created. I think I will create another issue if I encounter a problem that I can not solve. Thanks for the help!
