### ISSUE TITLE
rdm very slow to respond during reparse, ~70% CPU time in FileMap::read

### ISSUE THREAD

**Issue by Nephyrin** [Andersbakken/rtags#1299]
**Describe the bug**
Splitting this out as a more actionable issue from #1131

When reparsing a large project (~3000 files) with long index times (~10s per file due to heavy pch usage), rdm is pegged at 100% cpu and very slow to respond to commands, which causes hangs in emacs during trivial operations such as `rc --set-buffers`

Profiling rdm during this time, `Project::isTemplateDiagnostic` -> `FileMap::read` accounts for ~70% of the CPU time, trace provided below.

**To Reproduce**
Not clear what the exact criteria are, but large projects with long per-file compile times seem to reproduce this.

**Expected behavior**
rdm should retain interactive response times to `rc` commands from clients even when heavily loaded.

**Screenshots/Backtrace**
Via `perf record ... && perf report -G --call-graph ...`
```
   - 71.37% Project::updateDiagnostics
      - 70.45% Project::isTemplateDiagnostic
         - 68.74% Project::isTemplateDiagnostic
            - 68.27% FileMap<Location, Symbol>::read<Symbol>
               - 58.19% operator>><Symbol> (inlined)
                  + 16.53% operator>><String> (inlined)
                  + 8.97% operator>><unsigned short> (inlined)
                  + 7.02% operator>><short> (inlined)
                  + 6.12% Sandbox::decode<String, (String*)0>
                  + 3.98% ?? (inlined)
```

**Environment (please complete the following information):**
 - OS/Version: Arch Linux x64
 - RTags(rdm,rc): rtags git 40f5430c (2.21.126)
 - Emacs: 26.1
 - LLVM/Clang: 8.0 (svn build)

**Additional context**
User-visible issue is emacs becoming non-responsive -- if the elisp plugin did not block on background calls to `rc`, or `rdm` responded to rc quickly, the amount of CPU usage is less relevant (it's pegging all cores re-indexing anyway)

**Comment by Andersbakken** [comment]
I believe this should be better after the fix I just put in.

**Comment by Andersbakken** [comment]
Please reopen if you're still seeing the problem.

**Comment by Nephyrin** [comment]
I've tested a bit with the problematic projects and haven't been able to reproduce any lag beyond minor stuttering when rdm is very busy.

Thanks for the fix, and yet again for your work on this project :)
