### ISSUE TITLE
RTags: protocol version mismatch

### ISSUE THREAD

**Issue by laudrup** [Andersbakken/rtags#1307]
**Describe the bug**
The latest version of rtags seems to have a mismatch in protocol versions in the C++ code and elisp code.

In `elisp.py` the protocol version is set to 128, while still being 127 in CMakeLists.txt

**To Reproduce**
Use any rtags command from emacs that interacts with the rdm server and it will fail with a protocol mismatch

**Expected behavior**
The versions should be in sync

**Environment (please complete the following information):**
 - OS/Version: Debian testing
 - RTags(rdm,rc): 2.31.127
 - Emacs: 26.1
 - LLVM/Clang:  7.0.1

**Additional context**
I have tried incrementing the version in CMakeLists.txt to 128, but still get a protocol mismatch although `rc --version` returns `2.31.128`.

**Comment by cslux** [comment]
The protocol version in rtags.el is wrong, should be 127.

**Comment by laudrup** [comment]
@cslux Thanks. I've tried that, but it still fails with the same error. I've verified that it did indeed change by calling `describe-value` with `rtags-protocol-version` which returns `127`.

Seems like something else must be causing this?

**Comment by cslux** [comment]
Strange! Works for me, even without changing the protocol version in rtags.el. Have verified if you have multiple rc/rdm version installed?

**Comment by laudrup** [comment]
@cslux I have tried cleaning my `.emacs.d` directory, reinstalled the package from melpa and installed the rtags binaries with `rtags-install`. The binaries are only installed in the `.emacs.d` directory.

Still the same problem.

It is very likely I'm doing something wrong, but I think I'm pretty much following the "standard procedure".

Thanks very much for you help so far.

**Comment by cslux** [comment]
@laudrup I see! The rtags.el file from rtags-3.31 tag is bogus! If you have installed/compiled rtags via package.el. You would need to change the `rtags-protocol-version` to `126` in rtags.el

**Comment by laudrup** [comment]
@cslux Thanks a lot. That helped!

I assume a new package will be uploaded to elpa at some point which fixes the issue?

**Comment by cslux** [comment]
> I assume a new package will be uploaded to elpa at some point which fixes the issue?

For sure!

**Comment by cslux** [comment]
Already fixed on master branch! Closing it!
