### ISSUE TITLE
Provide a feature to expand 'auto' symbols with their full type when possible

### ISSUE THREAD

**Issue by Nephyrin** [Andersbakken/rtags#1308]
An amazing feature for rtags would be a function to take a declaration using `auto` and replace it with the expanded type.  This would allow typing, e.g. `auto *pFoo = ...` and then pressing a key to expand to `ComplexType<Bar> *pFoo = ...` from the parsed statement.  Sort of like after-the-fact-autocomplete.  Often using the full type is preferred for readability, while the usefulness of auto is in not needing to look it up/type it out as you create the statement.

I took a shot at doing this existing info from rtags.  `rtags-symbol-info` *does* contain the resolved type, but there are two issues that make this difficult:
 - Providing a file location within the literal text `auto` fails to identify the symbol -- the cursor needs to be on the symbol name.  This works as expected for non-auto symbols, where being in the type name will still work.
 - The buffer ranges returned map to the whole statement containing a declaration (e.g. in the case of `auto a = b` the range would include `= b`), so it's not possible to determine which part of that needs to be replaced to update the symbol to the resolved value without parsing C++.

Together this means it's not possible to programmatically determine the bounds of the auto declaration, nor select it from the auto symbol directly (which would be useful for placing the cursor on the auto and then executing said lookup).  These together would make it possible to do neat things like replacing a auto symbol with it's expanded form with a keystroke, or other neat things like showing the type in a popup/message when the point is in the declaration.

**Is your feature request related to a problem? Please describe.**
Attempting to write a helper to expand the `auto` keyword, I could not get enough information out of rtags to do so magically.

**Describe the solution you'd like**
I'd like the output of symbol information to include the specific range encompassing just the symbol (e.g. `auto *pFoo` range of the `auto *pFoo = bar` declaration), and to work when targeting the location of `auto`.

Expanding on that, a simple rtags function to replace the declaration with the full type.

**Describe alternatives you've considered**
Doing simple string tricks (find the symbol, find the word auto) can work for simple declarations, but for types where the symbol name is somewhere insane (e.g. function types) this devolves into parsing C++.

**Additional context**
#819 lacks a bit of information, but may be the same issue as the first bullet above.

**Comment by Andersbakken** [comment]
I added something. Let me know how this works.

M-x rtags-expand-auto

**Comment by Nephyrin** [comment]
I tested this and it seems to work, a few comments:
- The mockup I have actually replaces the whole `auto ... pFoo`  block with the full symbol definition from rtags, which seems to handle things like `auto *pFoo` better without inserting awkward whitespace.  I'm not actually sure what weird constructs C++ allows here, but I think at least function types of the form `auto pFoo` -> `int& (*pFoo)()` would need this approach.
- Placing the cursor inside the word 'auto' still fails - would be nice if anywhere within the declaration statement were a valid target just for QoL.

Otherwise it seems to work great, thanks again for your work on this.  Rtags is definitely invaluable to me on a daily basis.

For the record here's the perhaps needlessly-cautious variant I was using prior to your fixes:

```elisp
      (save-excursion
        (let ((symb (rtags-current-symbol))
              (tok (rtags-current-token))
              (word (current-word)))
          ;; If we have a symbol, and it's not the same as the token, and we see [auto ...] before
          ;; us and [... =] after.  This is because we only support the pretty basic case.
          ;;
          ;; Checking tok!=symb is because sometimes rtags will tell us the current symbol is just
          ;; the token name when it hasn't parsed enough to have all the type information.
          (if (and symb (not (string= symb "")) (not (string= symb tok))
                   (looking-back "auto [^=]*") (looking-at ".*="))
              (progn
                (re-search-backward "[\t\s]auto[\t\s]")
                (forward-char 1)
                (set-mark (point))
                (re-search-forward word)
                (delete-region (mark) (point))
                (insert symb))
            ;; else
            (message "Couldn't find auto symbol at point")))))
```

**Comment by 1wsx10** [comment]
It'd be great to see an rc command for this, for use in editors other than emacs :)
