### ISSUE TITLE
Protocol version mismatch in tag v.2.31 (128 vs 126)

### ISSUE THREAD

**Issue by Abergard** [Andersbakken/rtags#1309]
**Describe the bug**
Tag v2.31 is created with wrong protocol version. Source of RC have v.126, however the rtags.el have v.128

protocol version in rtags.el : 128 (https://github.com/Andersbakken/rtags/blob/v2.31/src/rtags.el#L76)
calculated RClient protocol version based on enum: 161-35 = 126 (https://github.com/Andersbakken/rtags/blob/v2.31/src/RClient.h#L35 - https://github.com/Andersbakken/rtags/blob/v2.31/src/RClient.h#L161)

**Environment:**
    OS/Version: [Red Hat 6.5]
    RTags(rdm,rc): [2.31]
    Emacs: [26.1]
    LLVM/Clang: [6.0]

**Comment by cslux** [comment]
#1307 "Duplicate"

**Comment by sungwonida** [comment]
Yeah. Just follow the comments and you could find https://github.com/Andersbakken/rtags/issues/1307#issuecomment-472847341

I just solved the issue in the same environment to OP.

**Comment by Abergard** [comment]
Thanks @sungwonida, currently I have made changes locally to have protocol version in rtags.el  equal 126 and it works. However doing a rtags update from emacs and getting stuck on protocol mismatch is a inconvenience, esspecialy that this is not the first time I have encountered this problem.

Maybe introducing some validation by CI would resolve this problem in the future.

**Comment by Deanseo** [comment]
I can verify this issue as well, though for my case it's *127 vs 128*.

Not seeing this issue the first time, may we add a functionality to let _force-ignore_ the protocol version when we know that the two versions are equivalent at our own risk?

**Comment by Andersbakken** [comment]
Sorry about that one. I added a defcustom to opt out of protocol versioning. 

rtags-verify-protocol-version can be set to nil to disable it.
