### ISSUE TITLE
Fail to load large compilation_commands.json

### ISSUE THREAD

**Issue by shelper** [Andersbakken/rtags#1312]
**Describe the bug**
i have a compilation_commands.json which are >500MB 
and by running rc -J, it loads for about 1 minute and say:
[Server] Compilation failed to load.
i ran in --verbose mode and i got nothing more

**Environment (please complete the following information):**
 - OS/Version: Ubuntu 18.04
 - RTags(rdm,rc): 2.31.127
 - Emacs: 26.1
 - LLVM/Clang: 5.0.0

**Comment by cslux** [comment]
What does rdm say? rdm - vvv

**Comment by shelper** [comment]
```
listening /run/user/18809/rdm.socket
listening /run/user/18809/rdm.socket
Running with 8 jobs, using args: -ferror-limit=50 -Wall -fspell-checking -Wno-unknown-warning-option
Includepaths: "-isystem" /usr/lib/llvm-6.0/lib/clang/6.0.0/include/
Restoring /home/user/develop/cpp-boilerplate/ ..
FileSystemWatcher::watch() '/home/user/workspace/build/' doesn't seem to be watchable
Restoring /home/user/workspace/ 
Error during validation: /home/user/workspace/main.cpp /home/user/.cache/rtags/%2Fhome%2Fuser%2Fworkspace%2F/306/symbols doesn't exist
.
/home/user/workspace/main.cpp is no longer in /home/user/workspace/build/compile_commands.json removing
```
i restructured my project, now no main in workspace, but in workspace/av
and the compile_commands.json also moved to workspace/av
how do i let rdm to run on new folder???

**Comment by cslux** [comment]
@shelper You need to reparse the source code. You may have a look at the option `--sandbox-root` if you plan to move your project often. You probably have to recreate the compile_commands.json as well.

**Comment by shelper** [comment]
```
listening /run/user/18809/rdm.socket
listening /run/user/18809/rdm.socket
Running with 24 jobs, using args: -ferror-limit=50 -Wall -fspell-checking -Wno-unknown-warning-option
Includepaths: "-isystem" /usr/lib/llvm-6.0/lib/clang/6.0.0/include/
```
and when i run `rc -J` it stops at something like below for me: 
`Source::parse Nothing looks like a compiler /home/username/workspace/project/source/bazel/tools/cpp/wrappers/clang`

i belive this is something related to my project setting, which wrapps and comes with its own clang in the folder but i have clang installed in my path. Not familiar with clang but i am gonna try to setup local clang path for the project and run it again to see what happens
