### ISSUE TITLE
Parsing breaks with "-xSSE2" option (from Intel Compilers)

### ISSUE THREAD

**Issue by rcoacci** [Andersbakken/rtags#1314]
**Describe the bug**
rc -J . returns  `[Server] Compilation failed to load.` when `compile_commands.json` contains an argument consisting of `-xSSE2`. Running `rdm -vvv` shows it stops parsing the arguments when it reaches the `-xSSE2` argument. Removing the argument from compile_commands.json allows `rdm` to parse the remaining arguments.

**To Reproduce**
1. Add `-xSSE2` to the arguments list of a compile_commands.json
2. Run `rdm -vvv`
3. Run `rc -J .`
4. `rc` returns with `[Server] Compilation failed to load.` and `rdm` stops parsing when it reaches `-xSSE2`

**Expected behavior**
`rc`returns successfully.

**Screenshots/Backtrace**

**Environment (please complete the following information):**
 - OS/Version: CentOS 7
 - RTags(rdm,rc): 2.31.127
 - Emacs: N/A
 - LLVM/Clang: 5.0 (from llvm-devtoolset-7)

**Additional context**
It's very weird because other similar arguments like `-axSSE4.2,AVX,CORE-AVX2,MIC-AVX512` works, but `-xSSE2` doesn't

**Comment by Andersbakken** [comment]
Ah. I see. It seems intel differentiates between -x [language] and -xOption

It should work now.

**Comment by rcoacci** [comment]
Thanks! I'll try to test it ASAP.
