### ISSUE TITLE
support macro expander 

### ISSUE THREAD

**Issue by zhihuiFan** [Andersbakken/rtags#1315]
**Is your feature request related to a problem? Please describe.**
I want to expand a macro when reading some source code and c-macro-expand doesn't work well with c++ like it can't find out some c++ header file (<memory>),   rtags knows everything about them (like include path, c++ standard and so on),  so rtags may be the best candidates to support it. 

**Describe the solution you'd like**
like `rtags-macro-expander` which write the source code in another buffer. 

**Describe alternatives you've considered**
https://github.com/chriskmanx/demystifycpp/blob/master/demystifycpp.el#L68  may be ok, but since it let the user to provide the compiler options, so it is not very good to use.

**Comment by cslux** [comment]
I think you are looking for `rtags-preprocess-file`, don't you?

**Comment by Andersbakken** [comment]
A little known feature of rtags-preprocess-file is that it allows you to preprocess only a marked section of the file.

In other words:

Mark the area containing the macro expansion and hit M-x rtags-preprocess-file and you will only get the output for that piece of the code.

**Comment by zhihuiFan** [comment]
Thanks you for the amazing project!!!
