### ISSUE TITLE
How to tune Rtags server for large projects ?

### ISSUE THREAD

**Issue by fperies** [Andersbakken/rtags#1317]
Hello,

First thank you very much for this very good project !
RTags is the best C++ indexer tool I've found so far (really!).

Environment:
 - OS/Version: RedHat7.5
 - RTags(rdm,rc): 2.31.127
 - Emacs: 26.1 (+Spacemacs 0.300@26.1)
 - LLVM/Clang: 6.0.0 

I think I've missed something in RTags server configuration because I experience some freezes.

Indeed, I'm working on a large project ( ~12000 files) with a size of database around  1.1G (ok, this is maybe not so large for some of you :-)).
My folder ~/.cache/rtags is mounted on a local drive and my machine has 12 CPU cores@2.10GHz with 42GB of RAM.

At some point, I get some freezes from my Emacs when I perform some rtags-find-symbol or rtags-find-reference queries. When this happens, from another terminal, if I run command 'strace -p $[PIDof myRDMserver}' I observe during the freeze duration the following bursts of mmap system calls (extract):

"
...
open("/ebs/frperies/.cache/rtags/%2Febs%2Ffrperies%2Frepo%2Fgnb%2F/1299/usrs", O_RDONLY) = 317
fcntl(317, F_SETLKW, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=0, l_len=0}) = 0
fstat(317, {st_mode=S_IFREG|0644, st_size=606, ...}) = 0
mmap(NULL, 606, PROT_READ, MAP_PRIVATE, 317, 0) = 0x7f1c99585000
munmap(0x7f1c9947e000, 466)             = 0
fcntl(318, F_SETLKW, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=0, l_len=0}) = 0
close(318)                              = 0
open("/ebs/frperies/.cache/rtags/%2Febs%2Ffrperies%2Frepo%2Fgnb%2F/1300/usrs", O_RDONLY) = 318
fcntl(318, F_SETLKW, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=0, l_len=0}) = 0
fstat(318, {st_mode=S_IFREG|0644, st_size=546, ...}) = 0
mmap(NULL, 546, PROT_READ, MAP_PRIVATE, 318, 0) = 0x7f1c99584000
munmap(0x7f1c9947d000, 1842)            = 0
fcntl(319, F_SETLKW, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=0, l_len=0}) = 0
close(319)                              = 0
..."

Here is my file .rdmrc:
--completion-cache-size=300
--watch-sources-only
--ignore-printf-fixits
--isystem /ebs/frperies/repo/gnb/uplane/build/prefix-root/asik-x86_64-ps_lfs/toolchain/sysroots/x86_64-oesdk-linux/usr/x86_64-pc-linux-gnu/include/c++/6.4.1
--isystem /ebs/frperies/repo/gnb/uplane/build/prefix-root/asik-x86_64-ps_lfs/toolchain/sysroots/x86_64-oesdk-linux/usr/x86_64-pc-linux-gnu/include/c++/6.4.1/x86_64-pc-linux-gnu
--daemon

What have I missed in my configuration ?

Subsidiary questions:
1) What is the exact meaning of setting complete-cache-size ? Should I increase it ?
2) I've seen in some other issues someone who has symbolic linked his cache folder to /dev/shm.
Does it make sense in my context ? Should I try it ?

Thank you very much for your answers.

**Comment by buherton** [comment]
I have had similar issue.

I use exclude filter of rdm:
`--exclude-filter|-X [arg]                Files to exclude from rdm, default "*/CMakeFiles/*;*/cmake*/Modules/*;*/conftest.c*;/tmp/*;/private/tmp/*;/private/var/*".`

I move the rtags cache to an SSD:
`--data-dir|-d [arg]                      Use this directory to store persistent data (default $XDG_CACHE_HOME/rtags otherwise ~/.cache/rtags).`
You can try to store it on RAM.

**Comment by Andersbakken** [comment]
Sorry about this very late

1)  --completion-cache-size is only meaningful when you use auto-completion. Normally enabled by using ac-rtags or company-rtags.

2) RTags uses its own homegrown mmap'ed database format. We did this after failing to get adequate performance out of leveldb/rocksdb and some other one I can't remember. It is heavy on reading files from disk so SHM might be beneficial though you'd probably want to sync it to a real drive before rebooting or you'd have to reindex the whole project on reboot.

It is a bit of a known problem that certain not crucial rtags operations from emacs might freeze the whole editor when rdm is very busy. I've thought about a couple of approaches to fixing this.

- More threading in rdm itself
- Make most (all) elisp operations from rtags synchronous 
- Shorter timeouts and graceful failures

Neither one is trivial and I sadly haven't had the time/willpower to implement either one of these yet :-(

**Comment by fperies** [comment]
Hello Anders,

Thank you for your answer and for your work on RTags project.

I've done a couple of tries and having the RTags database under /dev/shm/ is a very good option for large projects. Rtags server responsiveness is now very good and I've experienced no more freezes from Emacs.

Thanks
Regards
