### ISSUE TITLE
Protocol version mismatch on v2.31

### ISSUE THREAD

**Issue by szikes-adam** [Andersbakken/rtags#1318]
**Describe the bug**
When I want to use the rtags, it will say:
_RTags: protocol version mismatch. This is usually caused by getting rtags.el from melpa and installing a new rtags build that modified the protocol. They need to be in sync._

I installed the rtags package from MELPA, then I ran the rtags-install command. Here is the releated info:
**.emacs.d/elpa/rtags-20190410.1615/rtags-2.31/CMakeLists.txt**
...
set(RTAGS_VERSION_MAJOR 2)
set(RTAGS_VERSION_MINOR 31)
set(RTAGS_VERSION_DATABASE 127)
...

**.emacs.d/elpa/rtags-20190410.1615/rtags.el**
...
(defconst rtags-protocol-version 128)
(defconst rtags-package-version "2.31")
...

**.emacs.d/elpa/rtags-20190410.1615/rtags-2.31/bin/rc -t128** (from rtags log, without other options)
Protocol version mismatch

**.emacs.d/elpa/rtags-20190410.1615/rtags-2.31/bin/rc --version**
2.31.127

**Environment (please complete the following information):**
 - OS/Version: Ubuntu
 - RTags(rdm,rc): 2.31
 - Emacs: 26.1
 - LLVM/Clang: 6.0

**Comment by laudrup** [comment]
Hi @buherton,

I have the exact same issue and have had that issue before (see #1307).

The workaround from the previous issue still applies. Change the protocol version in `rtags.el` to 126 and the protocol versions seems to be in sync again.

No idea why this issue pops up again though, just thought it might be helpful.

**Comment by buherton** [comment]
Thanks for help! It works as expected.

**Comment by buherton** [comment]
I have checked the source code.

**Problem description**

The protocol version problem of **v2.31** has been introduced with the commit of: [Remove lua. It was never made fully functional and if we ever wanted](https://github.com/Andersbakken/rtags/commit/8944390593804e93c006c2964b667556c9b902a1#diff-9203242a0843ba65acfb9222ad9a9c6b). The `NumOptions` (aka protocol version) has been decreased to 126 by removing the `VisitAST*` enums.

**The current state**

The `NumOptions` is 128 on the **master** because of this commit: [Some changes to --include-path](https://github.com/Andersbakken/rtags/commit/c1a93c2bba41076dbdad5e50d502fb99503520e3#diff-9203242a0843ba65acfb9222ad9a9c6b). The `IncludePath` and `MaxDepth` enums are added.

In addition, there is option to opt out of protocol version verification: [Fix issue 1309. Make it possible to opt out of protocol verification.](https://github.com/Andersbakken/rtags/commit/864924d3c7b4aa35f7b2ec575665d57cf88ec7be)

**How I would fix this situation**

I would add the `VisitAST*` enums as deprecated `OptionType`. Therefore, the `NumOptions` would be 130. This would be a unique protocol version and it would not match with any of the previous rtags packages.

In parallel, I would **not** let the users to opt out of protocol verification because it may cause unexpected behavior (or segfault). They may write mystery issues and no one can reproduce them. I believe the protocol version issues are very boring (and annoying) but I also think the protocol version verification is the first check to avoid users from a bigger trouble.

**Comment by stammw** [comment]
First of all, thank you for this great piece of software !

I've got the exact same problem with 2.31.

**Comment by nayefc** [comment]
Same problem with latest versions. Anyone knows how to fix?

**Comment by stammw** [comment]
I had to add this to my `rtags` configuration : `(setq rtags-verify-protocol-version nil)`.

**Comment by FelixJoehnk** [comment]
Just to make sure everyone changes the right rtags.el file.
If you installed rtags via melpa then there is one rtags.el file in 
~/Path_To_elpa_folder/rtags<MelpaCode>/
and one is in 
~/Path_To_elpa_folder/rtags<MelpaCode>/rtags<Version>/src/

in my case this was
~/.emacs.d/elpa/rtags-20190410.1615/rtags-2.31/src/rtags.el
that needed the version change !

**Comment by Andersbakken** [comment]
I appreciate that this is an issue that keeps hitting people who install from melpa. Most of the time this error is actually benign and the workaround of just changing the protocol version is fine. It can however be a real problem. I might have taken an option away or made something a required argument or done something else that makes the old rtags.el not work. I'll try to think about a better way to solve this.

**Comment by sergeyklay** [comment]
Hello from 2020. This annoying error is still there. I simple can't use rtags w/o modifying `rtags.el` or set `rtags-verify-protocol-version` to `nil`. Both of workarounds looks ugly for me. Is there "The Right Way" to work with rtags, w/o hardcoding path to `rtags.el`, modifying `rtags.el`, set `rtags-verify-protocol-version` to `nil` and similar workaround?

**Comment by cslux** [comment]
@sergeyklay Did you download the v2.31 version from the release page or did you get the version from somewhere else?

**Comment by cslux** [comment]
@sergeyklay I have recreated the release v2.31 with the correct protocol version fix included.

**Comment by sergeyklay** [comment]
Actually I have installed rtags from the git repo:
```bash
$ RTAGS_VERSION=2.37

$ git clone -b "v$RTAGS_VERSION" \
>  --recursive https://github.com/Andersbakken/rtags.git \
>  ~/src/rtags

$ cd ~/src/rtags

$ cmake -S . \
>  -Bbuild \
>  -DCMAKE_BUILD_TYPE=Release

$ cmake --build build -j $(getconf _NPROCESSORS_ONLN)
$ sudo cmake --build build --target install # PREFIX=/usr/local
```

Then I started the daemon (_this was my first mistake_):
```bash
mkdir -p ~/.config/systemd/user
cp systemd/user/rdm.* ~/.config/systemd/user/
systemctl --user enable rdm.socket
systemctl --user start rdm.socket
```

Finally I installed Emacs packages using MELPA (_this was my second mistake_):
```elsip
(use-package rtags
  :ensure t
  ;; ...
)
```

What later I learned:

1. I should use `rtags.el` from the downloaded (installed) source, NOT from the MELPA.
2. rtags does NOT work if I start rdm using systemd (I should use `rtags-start-process-unless-running` instead)

Finally, working Emacs configuration is:

```elisp
(require 'directories) ; user-etc-dir
(require 'utils)       ; fontify-string

(defconst global-executable-path (executable-find "global")
  "The global executable path on this system.")

;;;; Bookmark

(use-package bookmark
  :ensure nil
  :custom
  (bookmark-default-file
   (concat user-etc-dir "bookmarks.el")))

;;;; CMake IDE

(use-package cmake-ide
  :after (projectile rtags)
  :custom
  (cmake-ide-build-dir "build")
  (cmake-ide-header-search-other-file nil)
  (cmake-ide-header-search-first-including nil)
  :config
  (cmake-ide-setup))

;;;; RTags

;; Do not install the following packages using MELPA.
;; These packages should be installed by hand using `make install' from
;; rtags source directory.
;;
;; For more see URL `https://github.com/Andersbakken/rtags/issues/1318'.

(defun rtags-eldoc-function ()
  "Eldoc documentation function to use for `c-mode' as well as `c++-mode'."
  (let ((summary (rtags-get-summary-text)))
    (and summary
         (fontify-string
          (replace-regexp-in-string
           "{[^}]*$" ""
           (mapconcat
            (lambda (str) (if (= 0 (length str)) "//" (string-trim str)))
            (split-string summary "\r?\n")
            " "))
          major-mode))))

(use-package rtags
  :ensure nil
  :if rdm-executable-path
  :defer 3
  :custom
  ;; Whether RTags automatically will restart diagnostics.
  (rtags-autostart-diagnostics t)
  ;; Whether completions are enabled.
  (rtags-completions-enabled t)
  ;; Path to RTags executables.
  (rtags-path (directory-file-name
	       (file-name-directory rdm-executable-path)))
  :config
  (defun my|rtags-common-hook ()
    "Common hook to setup `rtags'."
    (setq-local eldoc-documentation-function #'rtags-eldoc-function)
    (rtags-start-process-unless-running))

  (rtags-enable-standard-keybindings)
  :hook ((c-mode c++-mode) . my|rtags-common-hook))

(use-package company-rtags
  :ensure nil
  :if rdm-executable-path
  :after company rtags
  :config (push 'company-rtags company-backends))

(use-package flycheck-rtags
  :ensure nil
  :if rdm-executable-path
  :after flycheck rtags
  :config
  (defun my|flychack-rtags-common-hook ()
    "Common hook to setup `flycheck-rtags'."
    ;; Do not enable `eldoc' here (it is enabled in separated configuration).
    (flycheck-select-checker 'rtags)
    ;; RTags creates more accurate overlays.
    (setq-local flycheck-highlighting-mode nil
		flycheck-check-syntax-automatically nil))
  :hook ((c-mode c++-mode) . my|flychack-rtags-common-hook))

(use-package ivy-rtags
  :ensure nil
  :if rdm-executable-path
  :after ivy rtags
  :custom
  (rtags-display-result-backend 'ivy))
```

**Comment by sergeyklay** [comment]
IMO, the documentation is a bit unclear what I should not do and what is the recommend way to use inside/outside Emacs (and the explanation of the selected reasons). There is just a vector of proposed actions which are leads (or are not leads) to success.
