### ISSUE TITLE
RTags does not support polymorphism

### ISSUE THREAD

**Issue by zhangbenlong** [Andersbakken/rtags#1319]
**Is your feature request related to a problem? Please describe.**
For example Class LocalSubMatch inherits from Class SubMatch and they both have the function get_postlist(). Then we declare an object as Class SubMath but actually use it to store LocalSubMatch.

SubMatch match = new LocalSubMatch(...);
match->get_postlist();

So we really want to jump to the definition of LocalSubMatch->get_postlist, but apparently rtags now goes to that of SubMatch, which is undefined in this case.

**Describe the solution you'd like**
Jump to the subclass declares and definitions.

**Describe alternatives you've considered**
None

**Additional context**
Maybe consult the real type of an object instead of relying on its declaration?

**Comment by louxiu** [comment]
You can use `rtags-find-virtuals-at-point` with key binding `Ctrl-r v`.
