### ISSUE TITLE
Wrong libclang.so chosen.

### ISSUE THREAD

**Issue by mzr** [Andersbakken/rtags#1320]
**Describe the bug**
`rc` and `rdm` determine wrong version of clang.
```
➜  ~ rc
rc: error while loading shared libraries: libclang.so.7: cannot open shared object file: No such file or directory
```

**To Reproduce**
Invoke `rc` with installed clang 8.0.

**Expected behavior**
I think `rc` should pick libclang.so.8 or just libclang.so.

**Environment (please complete the following information):**
 - OS/Version: x86_64 Linux 5.0.7-1-MANJARO
 - RTags(rdm,rc): v2.31.r11.g626efb46-1
 - Emacs: 26.2
 - LLVM/Clang: 8.0.0

**Comment by mzr** [comment]
Rebuilding solved the problem...

**Comment by gazzatav** [comment]
I also got this strange error today and rebuilding solved it.  Using rtags version 2.31, it was looking for libclang-3.6.so.1 when I have clang version 6.0.0-1ubuntu2 on Ubuntu 18.04.

**Comment by cleeland** [comment]
If you use `ldd` to examine your executable, the executable likely has the name `libclang-3.6.so.1` embedded in it.  That is by design, and enforced by ELF, not by rtags.  There is likely nothing to "fix" here.

**Comment by gazzatav** [comment]
Sorry for delay.  Actually running ldd with rc gets this:

	linux-vdso.so.1 (0x00007ffcf3ed5000)
	libclang-6.0.so.1 => /usr/lib/llvm-6.0/lib/libclang-6.0.so.1 (0x00007fb1c36f9000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb1c3370000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb1c3151000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fb1c2f49000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb1c2bab000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb1c2993000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb1c25a2000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb1c5617000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb1c239e000)
	libLLVM-6.0.so.1 => /usr/lib/llvm-6.0/lib/../lib/libLLVM-6.0.so.1 (0x00007fb1be902000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007fb1be6fa000)
	libedit.so.2 => /usr/lib/x86_64-linux-gnu/libedit.so.2 (0x00007fb1be4c3000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fb1be2a6000)
	libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007fb1be07c000)
and ldd with rdm gets this:
	linux-vdso.so.1 (0x00007ffe16798000)
	libclang-6.0.so.1 => /usr/lib/llvm-6.0/lib/libclang-6.0.so.1 (0x00007fee9bc79000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fee9b8f0000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fee9b6d1000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fee9b4c9000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fee9b12b000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fee9af13000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fee9ab22000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fee9db87000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fee9a91e000)
	libLLVM-6.0.so.1 => /usr/lib/llvm-6.0/lib/../lib/libLLVM-6.0.so.1 (0x00007fee96e82000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007fee96c7a000)
	libedit.so.2 => /usr/lib/x86_64-linux-gnu/libedit.so.2 (0x00007fee96a43000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fee96826000)
	libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007fee965fc000).

However, I do have a version of rtags that I built for Ubuntu 14.04 which uses libclang-3.6.so.1 so I'm willing to concede it may have been human error i.e. emacs had the wrong rtags path or I was running the old server by mistake!
