### ISSUE TITLE
Several 'indexing crashed' happening

### ISSUE THREAD

**Issue by abbaswasim** [Andersbakken/rtags#1327]
**Describe the bug**
I have been trying to figure out no indexing issue for a while now. I have just noticed I am getting lots of indexing crashes.

**To Reproduce**
1. clone rtags, build and install (Release and Debug)
2. `rdm &; rm -rf ~/.cache/rtags ; project/folder/ rc -J .`
3. Lots of error messages starts appearing. Full list is attached

**Expected behavior**
No crashes when indexing files.

**Screenshots/Backtrace**
Here is a backtrace. Also attached full trace.

```
...
handleInclude failed 0x0 inclusion directive include cmath /personal/roar_engine/tests/math/vector3.hpp:32:1
...
Caught signal 11
1/48 sigHandler(int)
2/48 _sigtramp
3/48 0x0
4/48 clang::ASTContext::getTypeInfo(clang::Type const*) const
5/48 clang::ASTContext::getTypeInfoImpl(clang::Type const*) const
6/48 clang::ASTContext::getTypeInfo(clang::Type const*) const
7/48 clang::ASTContext::getTypeInfoInChars(clang::Type const*) const
8/48 ClangIndexer::handleCursor(CXCursor const&, CXCursorKind, Location, Symbol**)
9/48 ClangIndexer::indexVisitor(CXCursor)
10/48 ClangIndexer::visitorHelper(CXCursor, CXCursor, void*)
11/48 clang::cxcursor::CursorVisitor::Visit(CXCursor, bool)
12/48 clang::cxcursor::CursorVisitor::RunVisitorWorkList(llvm::SmallVector<clang::cxcursor::VisitorJob, 10u>&)
13/48 clang::cxcursor::CursorVisitor::Visit(clang::Stmt const*)
14/48 clang::cxcursor::CursorVisitor::VisitChildren(CXCursor)
15/48 clang_visitChildren
16/48 ClangIndexer::visit(CXCursor)
17/48 ClangIndexer::visitorHelper(CXCursor, CXCursor, void*)
18/48 clang::cxcursor::CursorVisitor::RunVisitorWorkList(llvm::SmallVector<clang::cxcursor::VisitorJob, 10u>&)
19/48 clang::cxcursor::CursorVisitor::Visit(clang::Stmt const*)
20/48 clang::cxcursor::CursorVisitor::VisitChildren(CXCursor)
21/48 clang_visitChildren
22/48 ClangIndexer::visit(CXCursor)
23/48 ClangIndexer::handleStatement(CXCursor const&, CXCursorKind, Location)
24/48 ClangIndexer::indexVisitor(CXCursor)
25/48 ClangIndexer::visitorHelper(CXCursor, CXCursor, void*)
26/48 clang::cxcursor::CursorVisitor::Visit(CXCursor, bool)
27/48 clang::cxcursor::CursorVisitor::VisitFunctionDecl(clang::FunctionDecl*)
28/48 clang::cxcursor::CursorVisitor::VisitChildren(CXCursor)
29/48 clang_visitChildren
30/48 ClangIndexer::visit(CXCursor)
31/48 ClangIndexer::visitorHelper(CXCursor, CXCursor, void*)
32/48 clang::cxcursor::CursorVisitor::Visit(CXCursor, bool)
33/48 clang::cxcursor::CursorVisitor::handleDeclForVisitation(clang::Decl const*)
34/48 clang::cxcursor::CursorVisitor::VisitDeclContext(clang::DeclContext*)
35/48 clang::cxcursor::CursorVisitor::VisitChildren(CXCursor)
36/48 clang_visitChildren
37/48 ClangIndexer::visit(CXCursor)
38/48 ClangIndexer::visitorHelper(CXCursor, CXCursor, void*)
39/48 clang::cxcursor::CursorVisitor::Visit(CXCursor, bool)
40/48 clang::cxcursor::CursorVisitor::handleDeclForVisitation(clang::Decl const*)
41/48 clang::cxcursor::CursorVisitor::VisitDeclContext(clang::DeclContext*)
42/48 clang::cxcursor::CursorVisitor::VisitChildren(CXCursor)
43/48 clang_visitChildren
44/48 ClangIndexer::visit(CXCursor)
45/48 ClangIndexer::visit()
46/48 ClangIndexer::exec(String const&)
47/48 main
48/48 start


job crashed 6 9 0x7f9f3c202a68
```

**Environment (please complete the following information):**
 - OS/Version: MacOS 10.14.5
 - RTags(rdm,rc): current master and v2.13 tag
 - Emacs: 26.2, `emacs-mac`
 - LLVM/Clang: 8.0.0

I have removed all `rtags` related packages from emacs and only using `make install`.

**Additional context**
No issues with `rtags` project itself. But it crashes with my project. Link to failing project https://github.com/abbaswasim/roar 

[rtags-crash.txt](https://github.com/Andersbakken/rtags/files/3224815/rtags-crash.txt)

Similar issue from 2015 #527

**Comment by abbaswasim** [comment]
By the way I tried to `bisect` this last nite so I was finding `good` revision and went as far as v2.0 but all of them are broken. I couldn't go beyond that because it won't build clean for me.

**Comment by abbaswasim** [comment]
I think I have worked this one out. I have been using `C++17` features which was crashing `rp`. When I have back ported everything to `C++14` no more crashes. I guess this could now be turned into feature request for `C++17` not really a bug.

**Comment by Andersbakken** [comment]
This appears to be an issue in libclang itself. The crash happens deep in libclang so we can't do anything about it I'm afraid. Have you tried a newer libclang version? RTags should support c++17 just fine as long as your libclang can handle it.
