### ISSUE TITLE
Add 'cppunit' as a build requiriment in the readme/wiki

### ISSUE THREAD

**Issue by f-florian** [Andersbakken/rtags#1328]
It appears that building rtags needs cppunit, which, at least on Gentoo, is a separate package.
I think that it is also a separate package in Debian, though it may be pulled by some other dependency there.

May be related to [#1221](https://github.com/Andersbakken/rtags/issues/1221), which is however marked as fixed, and reported for macOS.

Details:
The call to cmake produces the following error:
`CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find CPPUNIT (missing: CPPUNIT_LIBRARY CPPUNIT_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  src/rct/tests/FindCPPUNIT.cmake:21 (find_package_handle_standard_args)
  src/rct/tests/CMakeLists.txt:6 (find_package)`

**Environment:**
 - OS/Version: Gentoo
 - RTags(rdm,rc): github 'master' branch source
 - Emacs: n.a.
 - LLVM/Clang: 8.0.0

**Comment by cslux** [comment]
This shouldn't be required for a regular user. Only for packagers or devs. I will remove this dependency.
