### ISSUE TITLE
rtags elpa pacakge: is not a bzip2 file.

### ISSUE THREAD

**Issue by Red-Portal** [Andersbakken/rtags#1331]
**Describe the bug**
`rtags-install` results in the message

```sh
Downloading rtags from https://github.com/Andersbakken/rtags/releases/download/v2.33/rtags-2.33.tar.bz2
#=#=#                                                                         
##O#- #                                                                       

bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Failed to untar rtags-2.33.tar.bz2
```

**To Reproduce**
run `rtags-install`

**Environment (please complete the following information):**
 - RTags(rdm,rc): 2.33 (`package-list-packages` upstream version)
 - Emacs: 26.2
 - LLVM/Clang: 8.0.0

**Comment by igroen** [comment]
[https://github.com/Andersbakken/rtags/releases/download/v2.33/rtags-2.33.tar.bz2](https://github.com/Andersbakken/rtags/releases/download/v2.33/rtags-2.33.tar.bz2) does not exist.

**Comment by Red-Portal** [comment]
@igroen apparently that's what `rtags-install` calls right now. I didn't change anything that's the default behavior.

**Comment by igroen** [comment]
@Red-Portal Yes, i know. I have the same problem. v2.33 seems broken. I wonder why this version is released with failing builds.

**Comment by cslux** [comment]
Should work now! Sorry for the inconvenience!

**Comment by tangxinfa** [comment]
The same problem, it's v2.41:
   https://github.com/Andersbakken/rtags/releases/download/v2.41/rtags-2.41.tar.bz2

**Comment by atilaneves** [comment]
> The same problem, it's v2.41: https://github.com/Andersbakken/rtags/releases/download/v2.41/rtags-2.41.tar.bz2

I went there and the latest release seems to be 2.38. I worked around the issue with `(setq rtags-package-version "2.38")` followed by running `rtags-install` again.
