### ISSUE TITLE
rtags installation 

### ISSUE THREAD

**Issue by aviikc** [Andersbakken/rtags#1332]
Hi I have seen this issue on forum before. i cudnt diagnose this myself so far. cmake will not build rtags.

ErrorLog:-

`
Performing C++ SOURCE FILE Test LIBCLANG_COMPILES failed with the following output:
Change Dir: /home/aviik/rtags/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_83d19/fast"
/usr/bin/make -f CMakeFiles/cmTC_83d19.dir/build.make CMakeFiles/cmTC_83d19.dir/build
make[1]: Entering directory '/home/aviik/rtags/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_83d19.dir/src.cxx.o
/usr/bin/c++     -I/usr/lib/llvm-9/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MAC$
Linking CXX executable cmTC_83d19
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_83d19.dir/link.txt --verbose=1
/usr/bin/c++    -I/usr/lib/llvm-9/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACR$
/usr/bin/ld: cannot find -lclang
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_83d19.dir/build.make:97: recipe for target 'cmTC_83d19' failed
make[1]: *** [cmTC_83d19] Error 1
make[1]: Leaving directory '/home/aviik/rtags/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_83d19/fast' failed
make: *** [cmTC_83d19/fast] Error 2

Source file was:

#include <clang-c/Index.h>

int main()
{
    CXIndex index = clang_createIndex(0, true);
    CXTranslationUnit unit = clang_parseTranslationUnit(index, 0, 0, 0, 0, 0, 0);
    clang_disposeTranslationUnit(unit);
    clang_disposeIndex(index);
    return 0;
}
`

[This is the /usr/include/ contents](http://imgur.com/EBTUADCl.png)

**Comment by ashrasmun** [comment]
Do you have clang and libclang-dev installed? This issue is quite common so hopefully you can resolve it soon.

**Comment by Andersbakken** [comment]
Assuming this was solved by installing development package for clang. Please reopen if it's still an issue.
