### ISSUE TITLE
RTags can't index any file that includes fmtlib's format.h

### ISSUE THREAD

**Issue by Oxyd** [Andersbakken/rtags#1335]
**Describe the bug**
Whenever a file contains `#include <fmt/format.h>`, RTags fails to list any symbols defined within that file.

**To Reproduce**
```
mkdir /tmp/foo
cd /tmp/foo
git clone 'https://github.com/fmtlib/fmt.git'
```

Use the following foo.cpp:
```c++
#include <fmt/format.h>

int variable = 0;

int
main() { }
```

and compile_commands.json:
```json
[
  {
    "directory": "/tmp/foo",
    "command": "/usr/bin/g++ -I/tmp/foo/fmt/include -std=c++17 -o foo.o -c foo.cpp",
    "file": "/tmp/foo/foo.cpp"
  }
]
```

Then:
```
/tmp/foo % rc -J                                        
[Server] Compilation database loading...
/tmp/foo % rc -d foo.cpp
#include <fmt/format.h> // 1-24, 0: inclusion directive include fmt/format.h /tmp/foo/foo.cpp:1:1 
/tmp/foo % 
```
If I comment out the `#include` line, RTags works as expected:
```
/tmp/foo % rc -d foo.cpp
int variable = 0; // 5-17, 0: VarDecl cursor variable def c:@variable /tmp/foo/foo.cpp:3:5 int 
int variable = 0; // 16-17, 1: IntegerLiteral literal /tmp/foo/foo.cpp:3:16 
main() { } // 1-11, 0: FunctionDecl cursor main() main def c:@F@main# /tmp/foo/foo.cpp:6:1 int 
main() { } // 8-11, 1: CompoundStmt statement
```

**Expected behavior**
The symbols for `variable` and `main` should be listed even when `<fmt/format.h>` is included.

**Environment (please complete the following information):**
 - OS/Version: ArchLinux
 - RTags(rdm,rc): 2.33.128
 - Emacs: 26.2
 - LLVM/Clang: 8.0.1

**Comment by Andersbakken** [comment]
Sorry about the delay. I'm trying to reproduce this with 2.33.128 albeit with clang 9.0.0 and it seems to work fine. Are you able to try with clang 9?

**Comment by Andersbakken** [comment]
I get the same thing with llvm 8.0.0 actually:

rc -d main.cpp 
#include <fmt/format.h> // 1-24, 0: inclusion directive include fmt/format.h /home/abakken/temp/foobar/main.cpp:1:1 
int variable = 0; // 5-17, 0: VarDecl cursor variable def c:@variable /home/abakken/temp/foobar/main.cpp:3:5 int 
int variable = 0; // 16-17, 1: IntegerLiteral literal /home/abakken/temp/foobar/main.cpp:3:16 
main() { } // 1-11, 0: FunctionDecl cursor main() main def c:@F@main# /home/abakken/temp/foobar/main.cpp:6:1 int 
main() { } // 8-11, 1: CompoundStmt statement 

Can you check what happens with:

rc -d main.cpp --dump-include-headers 

Might be a lot of output

**Comment by Andersbakken** [comment]
Closing for now due to lack of activity.
