### ISSUE TITLE
ivy symbol list is reversed compared with the list in *RTags* buffer

### ISSUE THREAD

**Issue by danlipsa** [Andersbakken/rtags#1336]
** Description**

When doing C-c r . (rtags-find-symbol-at-point) on a symbol that returns a list, the list as it is presented in the *RTags* buffer is in correct order.

If we set
(setq rtags-display-result-backend 'ivy)
the same list is presented in reverse order in the ivy buffer (compared with the order you see in the *RTags* buffer). This creates usability problems as one has to navigate to the last entry and press Enter.

**Environment (please complete the following information):**

 - Ubuntu 18.04
 - RTags(rdm,rc): SHA fd57e4f7304b0da1c24eccda198511424207c5cf
 - Emacs: GNU Emacs 26.2 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30)
 - LLVM/Clang: clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final

**Comment by cslux** [comment]
Thanks for the report @danlipsa. Fixed via f185c4d.

**Comment by danlipsa** [comment]
Great! Thanks for the fix! I checked and it works correctly now.

**Comment by cslux** [comment]
Thanks for the confirmation.
