### ISSUE TITLE
Symbol's function definition is void: rtags-enable-standard-keybinding

### ISSUE THREAD

**Issue by RishabhHardas** [Andersbakken/rtags#1337]
Looking at the Usage section, I added the following line to my config

`(rtags-enable-standard-keybindings c-mode-base-map "\C-xr")`
On starting emacs I get the following error

> Symbol's function definition is void: rtags-enable-standard-keybindings

I searched for configs and all of them seem to use the same.

My configs are as follows

```
(add-to-list 'load-path "/home/user/emacs_packages/neotree")
(require 'neotree)
(global-set-key [f8] 'neotree-toggle)


(add-hook 'after-init-hook 'global-company-mode)
(add-hook 'c++-mode-hook 'company-mode)
(add-hook 'c-mode-hook 'company-mode)
(setq company-idle-delay 0)
(setq company-minimum-prefix-length 2)

(setq rtags-completions-enabled t)
(eval-after-load 'company
  '(add-to-list
    'company-backends 'company-rtags))

(setq rtags-autostart-diagnostics t)
(rtags-enable-standard-keybindings)
(rtags-enable-standard-keybindings c-mode-base-map "\C-xr")
```

**Comment by cslux** [comment]
Hmm, I don't see a `(require 'rtags)`.

**Comment by RishabhHardas** [comment]
After adding that I get the below error

> File error: Cannot open load file, no such file or directory, rtags

But the commands are working

**Comment by RishabhHardas** [comment]
So I added the following lines to the config

`(add-to-list 'load-path ".emacs.d/elpa/rtags-20190820.502/")
(require 'rtags)`

and now it is working fine.

Thank you @cslux !

**Comment by cslux** [comment]
@RishabhHardas What? No, don't do this :-) You used package.el to install rtags right. So add this to your init.el/.emacs.

``` emacs-lisp
(require 'package)
(package-initialize) ;; Isn't required for Emacs >= 27.x.x
(require 'rtags)
```

I recommend using [use-package](https://github.com/jwiegley/use-package) it keeps things clean.

Example setup:
``` emacs-lisp
(require 'package)
(setq package-archives '(("marmalade" . "https://marmalade-repo.org/packages/")
                         ("melpa"     . "https://melpa.org/packages/")
			 ("gnu"       . "http://elpa.gnu.org/packages/")
                         ("orgmode"   . "http://orgmode.org/elpa/")))

;; Setup `load-path'...
(package-initialize) ;; Isn't required for Emacs >= 27.x.x

;; Bootstrap `use-package'
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))


(use-package rtags
    ...)
```

**Comment by RishabhHardas** [comment]
Okay. I'll do that and read about `use-package`
Thanks!
