### ISSUE TITLE
[Q]: Documentation

### ISSUE THREAD

**Issue by Krzmbrzl** [Andersbakken/rtags#1339]
Is there some documentation on how rtags can be used from the command line? Almost everything I try just does nothing.
Via `rc -g` I see that the commands seem to be received by the rdm server but other than that nothing happens.

And the man-pages aren't really helpful either.

Maybe a few examples would suffice that demonstrate the basic usage of the tool might be enough to get going...

**Comment by Andersbakken** [comment]
Sorry about the long delay. There isn't really a lot outside of rc --help which is roughly the same as the man pages. 

The best commands to start with are likely these:

rc -J /path/to/compile_commands.json # This will index a project 
rc -f /path/to/sourcefile.cpp:123:321 # This will print the target location for the location /path/to/sourcefile.cpp at line 123 and column 321
rc -r /path/to/sourcefile.cpp:123:321 # This will print the references to the symbol defined in /path/to/sourcefile.cpp at line 123 and column 321
rc -F foobar # list all symbols with the name foobar
rc -S foobar # list all symbols starting with the string foobar

**Comment by Krzmbrzl** [comment]
Thanks for the reply though `rc -f` and `rc -r` are still not doing anything. `-J` issues the indexing just fine and `-f` and `-S` work as well :man_shrugging:
