### ISSUE TITLE
Increase size of rtags-reference-tree result

### ISSUE THREAD

**Issue by fperies** [Andersbakken/rtags#1342]
Hello,

This is too bad that the string of caller is truncated in the result of the rtags-reference-tree command. It may be confusing when caller is overloaded:
![image](https://user-images.githubusercontent.com/7024137/64641854-4d6a8280-d40d-11e9-9aa6-d0b2eedb852e.png)

Would it be possible to increase the number of characters to display caller function ?

Thanks
Regards

**Comment by Andersbakken** [comment]
Should be doable now by setting rtags-references-tree-truncate to nil

**Comment by fperies** [comment]
Hello,
Unfortunately, the truncate operates on the callee line not on the **caller** line.
I would expect to not have truncature on the string at right-hand side of the <= sign.
Can you please fix this ?

Thank you for your support!
