### ISSUE TITLE
rdm asserts on files referencing strings containing ".."

### ISSUE THREAD

**Issue by xim** [Andersbakken/rtags#1343]
**Describe the bug**

If a compile command references the string ".." in a relevant argument, you hit this assert:

`rdm: ./src/Location.h:100: static uint32_t Location::insertFile(const Path&): Assertion `!path.contains("..")' failed.`

**To Reproduce**

Have a project that autogenerates a lot of stuff, including paths that look like e.g.

`foo_bar_.._.._baz`

**Expected behavior**

Because that path contains "_.._" and not "/../" the path isn't harmful.

**Backtrace**

I can generate a backtrace if so should be desired.

**Environment (please complete the following information):**
 - OS/Version: Debian Stable
 - RTags(rdm,rc): 2.33 (built from git tag)
 - LLVM/Clang: 7.0.1

**Additional context**

The "strange" file paths come from an external build system, and I believe I have seen Qt Quick compiler do the same (but don't use that for this project)

**Comment by Andersbakken** [comment]
That's absolutely right. Should be fixed now.
