### ISSUE TITLE
rtags-compile-file: unknown option: --driver-mode=g++ 

### ISSUE THREAD

**Issue by Dushistov** [Andersbakken/rtags#1347]
**Describe the bug**

After update rtags from 6289e66a69d0d5ff20b12da91e735d3984ad6f88 to f2633f565fc5e7e6958993ef105225f4e68e43ba `rtags-compile-file` doesn't work anymore.
For unknown reason it append `--driver-mode=g++ ` to command line of compiler,
but my default compiler is `g++` and it doesn't support this option,
`compile_commands.json` obviously doesn't contain this option, my build will be failed with option.

**Environment (please complete the following information):**
 - OS/Version: Arch Linux / x86_64
 - Emacs: 26.3
 - LLVM/Clang: 9.0.0

**Comment by Dushistov** [comment]
Seems it is related to clang 9.0.0. Event previously working 6289e66 still add --driver-mode=g++

**Comment by cslux** [comment]
Should be fixed with PR #1366.
