### ISSUE TITLE
Incorrect version set in MELPA

### ISSUE THREAD

**Issue by kwvanderlinde** [Andersbakken/rtags#1351]
**Describe the bug**

The latest rtags version on MELPA Stable is 3.23, but the code makes it apparent that the actual version is 2.33. There is also no tag by the name "3.23". It looks like there was probably a typo while bumping the version.

We can see the discrepancy by opening up the 3.23 package directory in dired:
```
  /home/kenneth/.emacs.d/elpa/rtags-3.23:
  total used in directory 1864 available 134222180
  drwxr-xr-x  3 kenneth kenneth    4096 Nov 11 09:15 .
  drwxr-xr-x 95 kenneth kenneth    4096 Nov 11 04:01 ..
  -rw-r--r--  1 kenneth kenneth     578 Nov 11 09:15 install-rtags.sh
  drwxr-xr-x 12 kenneth kenneth    4096 Nov 11 09:15 rtags-2.33
  -rw-r--r--  1 kenneth kenneth 1430529 Nov 11 09:15 rtags-2.33.tar.bz2
  -rw-r--r--  1 kenneth kenneth   11587 Nov 11 04:01 rtags-autoloads.el
  -rw-r--r--  1 kenneth kenneth  244257 Nov 11 09:14 rtags.el
  -rw-r--r--  1 kenneth kenneth  195297 Nov 11 04:01 rtags.elc
  -rw-r--r--  1 kenneth kenneth     321 Nov 11 04:01 rtags-pkg.el
```
And inside of `rtags.el` we find the same discrepancy
```
;; Package-Version: 3.23
;; Version: 2.33.128
```

**To Reproduce**
Take a look at [MELPA Stable](https://stable.melpa.org/#/?q=rtags) and compare with the tags and version numbers in this repo.

**Expected behavior**
The package version should agree with the tag and the version numbers in the elisp code.

**Environment (please complete the following information):**
 - OS/Version: Ubuntu 19.04
 - RTags(rdm,rc): 2.33 / 3.23
 - Emacs: 25.2.2
 - LLVM/Clang: 6.0.0

**Comment by cslux** [comment]
@kwvanderlinde Thank you for the report. I requested the deletion of that version (https://github.com/melpa/melpa/issues/6583). As soon as the new version (v2.35) lands in Melpa Stable you need to reinstall rtags. Otherwise it want get updated until the release of version v3.24 :-)
