### ISSUE TITLE
protocol version mismatch

### ISSUE THREAD

**Issue by dackon** [Andersbakken/rtags#1357]
**Describe the bug**
I installed rtags-20191206.1733, in rtags-pkg.el:

```lisp
;;; -*- no-byte-compile: t -*-
(define-package "rtags" "20191206.1733" "A front-end for rtags" 'nil :commit "31bff9aafce4e92bd2bf8dd6417dd24dc48b7363" :authors '(("Jan Erik Hanssen" . "jhanssen@gmail.com") ("Anders Bakken" . "agbakken@gmail.com")) :maintainer '("Jan Erik Hanssen" . "jhanssen@gmail.com") :url "http://rtags.net")
```

Then, I did 'git pull':
> git log -1
```shell
commit 31bff9aafce4e92bd2bf8dd6417dd24dc48b7363 (HEAD -> master, origin/master, origin/HEAD)
Author: Anders Bakken <agbakken@gmail.com>
Date:   Fri Dec 6 09:33:53 2019 -0800

    Bump version to 2.34
```

After I compiled and installed the new rtags, I got:
RTags: protocol version mismatch. This is usually caused by getting rtags.el from melpa and installing a new rtags build that modified the protocol. They need to be in sync.

I copied '$RTAGS_INSTALL_DIR/share/emacs/site-lisp/rtags/rtags.el*' to ~/.emacs.d/elpa/rtags-20191206.1733, same problem.

**Comment by cslux** [comment]
Fixed!
