### ISSUE TITLE
emacs-snapshot byte_compile errors

### ISSUE THREAD

**Issue by gillilandrob** [Andersbakken/rtags#1359]
First of all I can't express how much I love this project so please keep up the good work. I've never run into any issues installing rtags before so I just wanted to make note of this one in case it helps anyone. Ultimately I just reverted to a stable release of emacs and everything was fine so this isn't really an issue with rtags but with emacs probably.

Recently I was setting up a new machine and emacs installation on Ubuntu:
add-apt-repository ppa:ubuntu-elisp/ppa
apt-get update
apt-get install emacs-snapshot

And when I tried to compile rtags c/c++ compiled fine but emacs failed to byte compile the .el files properly:

[ 84%] Building CXX object src/CMakeFiles/rdm.dir/rdm.cpp.o
[ 86%] Linking CXX executable ../bin/rdm
[ 86%] Built target rdm
Scanning dependencies of target emacs_byte_compile_company-rtags.el
[ 87%] Creating byte-compiled Emacs lisp /home/rob/frameworks/rtags/src/company-rtags.elc
Package cl is deprecated
Symbol’s value as variable is void: ivy-completing-read-handlers-alist
src/CMakeFiles/emacs_byte_compile_company-rtags.el.dir/build.make:60: recipe for target 'src/company-rtags.elc' failed
make[2]: *** [src/company-rtags.elc] Error 255
CMakeFiles/Makefile2:274: recipe for target 'src/CMakeFiles/emacs_byte_compile_company-rtags.el.dir/all' failed
make[1]: *** [src/CMakeFiles/emacs_byte_compile_company-rtags.el.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

I reverted to emacs 25.2.2 and all the byte compile errors went away:
apt-get install ppa-purge
ppa-purge ppa:ubuntu-elisp/ppa
apt-get install emacs

Thanks,
-Rob

**Comment by cslux** [comment]
Thanks for the report! Should be fixed now (f3ae1172).

Chris
