### ISSUE TITLE
Rdm crashing right at start

### ISSUE THREAD

**Issue by ratnesh1729** [Andersbakken/rtags#1369]
**Describe the bug**
Normal out of the box installation using git clone recursive. 
Upon make - `./bin/rdm &` crashes with reporting - Couldn't parse arguments.

**To Reproduce**
Repeat the compilation of rtags as is in Readme of Rtags.

**Expected behavior**
No crashing of rdm.

**Environment (please complete the following information):**
 - OS/Version: Ubuntu 16.04
 - RTags(rdm,rc): latest and also tried 2.38 from 7 days old
 - Emacs: [e.g. 24.5] Did not reach this but - my emacs is 26+
 - LLVM/Clang: libclang-6.0-dev

**Additional context**
Nothing special.

**Comment by cslux** [comment]
Do have a traceback? 

On January 26, 2020 9:03:50 PM UTC, Ratnesh <notifications@github.com> wrote:
>**Describe the bug**
>Normal out of the box installation using git clone recursive. 
>Upon make - `./bin/rdm &` crashes with reporting - Couldn't parse
>arguments.
>
>**To Reproduce**
>Steps to reproduce the behavior:
>Repeat the compilation of rtags as is in Readme of Rtags.
>
>**Expected behavior**
>No crashing of rdm.
>
>
>
>**Environment (please complete the following information):**
> - OS/Version: Ubuntu 16.04
> - RTags(rdm,rc): latest and also tried 2.38 from 7 days old
> - Emacs: [e.g. 24.5] Did not reach this but - my emacs is 26+
> - LLVM/Clang: libclang-6.0-dev
>
>**Additional context**
>Nothing special. 

-- 
Christian Schwarzgruber
T: +43 699 194 166 34
E: c.schwarzgruber.cs@gmail.com

**Comment by ratnesh1729** [comment]
How can I get a traceback ?

**Comment by cslux** [comment]
There must have been any output from rdm.

You did execute rdm like this `rdm &` and called `rc` how...?

**Comment by cslux** [comment]
I could not reproduce it with Ubuntu 16.04 using llvm/clang 3.8.0. 

I step by step instruction along with the project you tried to parse, which reproduces the crash would be sufficient.

**Comment by ratnesh1729** [comment]
Thanks 
I’m using libclang 6.0
Rdm crashes with just that line. Hence rc fails saying no socket exists

**Comment by cslux** [comment]
Ok I think 🤔 I understand you now.

Rdm is not crashing its just telling you it couldn't parse the compilation command.
 Run rdm with -vvv to see more. 

rdm -vvv



On January 27, 2020 2:58:00 PM UTC, Ratnesh <notifications@github.com> wrote:
>Thanks >
>I’m using libclang 6.0>
>Rdm crashes with just that line. Hence rc fails saying no socket
>exists>
>>
>-- >
>You are receiving this because you commented.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/Andersbakken/rtags/issues/1369#issuecomment-578788079

-- 
Christian Schwarzgruber
T: +43 699 194 166 34
E: c.schwarzgruber.cs@gmail.com

**Comment by ratnesh1729** [comment]
I did directly from the bin/ folder 
`./rdm -vvv` . I get same above result - `Couldn't parse argument `

**Comment by cslux** [comment]
This all does not make sense to me right now. :-

On January 27, 2020 4:09:21 PM UTC, Ratnesh <notifications@github.com> wrote:
>I did directly from the bin/ folder 
>`./rdm -vvv` . I get same above result - `Couldn't parse argument `

-- 
Christian Schwarzgruber
T: +43 699 194 166 34
E: c.schwarzgruber.cs@gmail.com

**Comment by ratnesh1729** [comment]
Not sure what is not clear above. That was a straightforward command. Could be launched from Rtags bin/ folder. Even if I install completely I get the same above info (by running `rdm -vvv`). 

I think I found the reason. I needed to include cpp 17 and clang paths in `.rdmrc` - as explained on the reply on Nov 20 - https://github.com/Andersbakken/rtags/issues/1095

When I have `rdmrc` - I get the error. If I remove this `rdmrc` . I do not get parsing error. But I also do not get cpp17 semantics.

**Comment by cslux** [comment]
You never mentioned anything about rdmrc until now. Nor did you post your rdm setup. I very sorry, but unfortunately I don't have any telepathic skills.

**Comment by ratnesh1729** [comment]
I never mentioned because I'm not a rtags expert or an author. Unfortunately I don't have  magic skills to figure rdmrc was an issue. :-) rdm used to work with the same file. New version it doesn't.

You're welcome to close the issue. (I may not be coming in this repo again to see your comments. I find it weird).

Thanks for being there and I appreciate rtags contribution to my development.
