### ISSUE TITLE
rtags-xref.el requires wrong package version (3.37)

### ISSUE THREAD

**Issue by FreekPaans** [Andersbakken/rtags#1376]
Hi,

It looks like `rtags-xref.el` requires an rtags version that doesn't exist, 3.37, which blocks me from installing it via the package installer. Line is here: https://github.com/Andersbakken/rtags/blob/master/src/rtags-xref.el#L9:

`;; Package-Requires: ((emacs "25.1") (rtags "3.37"))`

Cheers,

-Freek

**Comment by cslux** [comment]
Thats just the minimal required version. `M-x` package-install RET rtags-xref --
works for me.

Whats your emacs version?

`M-x` emacs-version

**Comment by FreekPaans** [comment]
I'm on 26.2, AFAICT, rtags is on "2.x" releases, not "3.x". Quite interesting that it works for you, what is the minimum version for rtags that it lists for you?

**Comment by cslux** [comment]
Uups, I missed the "3". It shouldn't work for me, hmmm. Anyway, I updated the
minimum required rtags version in rtags-xref.el.
