### ISSUE TITLE
How to know more about RDM indexing errors ?

### ISSUE THREAD

**Issue by fperies** [Andersbakken/rtags#1389]
Command 'rc -g' reports the following:
```
[ 81%] 17/21 15:47:32 ~/repo/gnb/uplane/sct/tickler/cpp_testsuites/l2ps/tc/baseline/bl_LoopCellGroupSetupDelete.cpp error in 18ms.  (dirty). (priority 2)
[ 86%] 18/21 15:47:32 ~/repo/gnb/uplane/sct/tickler/cpp_testsuites/l2ps/sctl2ps_support.cpp error in 19ms.  (dirty). (priority 2)
```
How to find out what is behind those errors ?
Is there any trace I can activate to know more about this issue ?

Thanks
Regards

**Comment by cslux** [comment]
You could try `rdm -vvv`.

**Comment by fperies** [comment]
I've already tried without any success:
```
*********************************
info
*********************************
Running a release build
socketFile: /ebs/frperies/.rdm
dataDir: /dev/shm/rtags/
options: 0x40080001c
jobCount: 16
```
I understand I fall into the following condition:
![image](https://user-images.githubusercontent.com/7024137/81709887-82cee080-9472-11ea-96c3-afda7d525687.png)

Is there any more accurate way to find out what is missing in the DB ?

Thanks

**Comment by fperies** [comment]
@cslux : I think I found the issue : this is due to the following include option in compilation command:
```
-include /ebs/frperies/repo/gnb/uplane/build/tickler/cpp_testsuites/l2ps/tc/CMakeFiles/sctl2psTemplatesVars.dir/cmake_pch.hxx
```
If I remove this option the error goes away.

It seems that is is discarded due to the following trace:
Shouldn't index /ebs/frperies/repo/gnb/uplane/build/tickler/cpp_testsuites/l2ps/tc/CMakeFiles/sctl2psTemplatesVars.dir/cmake_pch.hxx.cxx because of exclude filter

That is .cxx files are part of he exclude filter by default.
**The question now is : how do I remove .cxx files from exclude filter ?**

Thanks again for your support !

**Comment by fperies** [comment]
So, I've the --exclude-filter RDM's option as follows:
--exclude-filter="*/cmake*/Modules/*;*/conftest.c*;/tmp/*;/private/tmp/*;/private/var/*"
and the _Shouldn't index_ message goes away but unfortunately errors are still there.

So, for some reasons the include option in compilation command is not supported....

I'm still looking forward your opinion on this topic.

Thanks

**Comment by zhihuiFan** [comment]
Hi @fperies   can you have a steps to reproduce this issue?  If so, I would like to have a try if it is not too complex.

**Comment by fperies** [comment]
Hello @zhihuiFan,

My understanding is that RTags does not support compilation commands where the CMake feature precompiled headers has been used.
I'm not a CMake expert but I think that if the CMake macro **target_precompile_header()** has been used in file CMakeLists.txt then it will add both a warning (-Winvalid_pch) and a preprocessor include directive (-include _<path_to_precompiled_header>/cmake_pch.hxx_) to the compilation command line of the associated CMake target.
Knowing that, if you want to reproduce it, you have to set up a CMake target with a precompiled header (by using the macro target_precompiled_header()) and then try to index it with RTags.  Of course, you will need also to remove string "*/CMakeFiles/*" from RTags --exclude-filter option  as I did above, because CMake put the precompiled headers in some */CMakeFiles/* path within build directory. Then, you should hit the error I've described at the beginning of this issue.

Otherwise, I've found a workaround by using the CMake flag: 
![image](https://user-images.githubusercontent.com/7024137/83522901-9a354280-a4e1-11ea-9475-259e8f49231d.png)
but I can not really say if it is acceptable in all situations.

Let me know if you need additional information.
Thanks !

**Comment by zhihuiFan** [comment]
Hi @fperies :

Actually I was expecting an reproduce  steps like 

```
git clone xxxx/demo.git
cmake --version
cmake ..
rc -J .
balabala...
```
  
Maybe the steps like above is not easy,  and I didn't use CMAKE in my real work,  so it would be hard to provide help.
