### ISSUE TITLE
rct.cmake missing

### ISSUE THREAD

**Issue by gevorgyana** [Andersbakken/rtags#1390]
```
CMake Error at src/CMakeLists.txt:145 (include):
  include could not find load file:

    rct/rct.cmake
```
**To Reproduce**
1. ```git clone https://github.com/Andersbakken/rtags.git```
2. ```mkdir build && cd build && cmake ..```

Where do I get rct/rct.cmake from?

**Environment:**
 - OS/Version: Ubuntu 18.04
 - Emacs: 25.2.2
 - libclang: 6.0

[cmake_output](https://github.com/Andersbakken/rtags/files/4663012/cmake_failure.txt)

**Comment by gevorgyana** [comment]
j

**Comment by gevorgyana** [comment]
It seems like that file comes from another project, which should be loaded as a git submodule, but for some reason it didn't work for me.

**Comment by cslux** [comment]
You need to clone the submodules too. See the install section.

git clone --recursive...



On May 21, 2020 2:38:26 PM UTC, Artyom Gevorgyan <notifications@github.com> wrote:
>**Describe the bug**
>I am on Ubuntu 18.04, libclang is installed, both user and dev
>packages. After cloning the repository and running cmake, configuration
>step failed with the following error:
>```
>-- The following REQUIRED packages have been found:
>
> * __LibClang__
>```
>while also saying that 
>```
>-- __Found LibClang__: /usr/lib/llvm-6.0/lib/libclang.so  
>-- Performing Test LIBCLANG_COMPILES
>-- Performing Test LIBCLANG_COMPILES - Success
>```
>**To Reproduce**
>1. ```git clone https://github.com/Andersbakken/rtags.git```
>2. ```mkdir build && cd build && cmake ..```
>
>**Expected behavior**
>Check against LibClang is not supposed to fail, I guess, because ```apt
>search libclang | grep installed``` gives 
>```
>libclang-6.0-dev/bionic,now 1:6.0-1ubuntu2 amd64 [installed]
>libclang-common-6.0-dev/bionic,now 1:6.0-1ubuntu2 amd64
>[installed,automatic]
>libclang-dev/bionic-updates,now 1:6.0-41~exp5~ubuntu1 amd64 [installed]
>libclang1-6.0/bionic,now 1:6.0-1ubuntu2 amd64 [installed,automatic]
>```
>
>**Environment:**
> - OS/Version: Ubuntu 18.04
> - Emacs: 25.2.2
> - libclang: 6.0
>[cmake_failure.txt](https://github.com/Andersbakken/rtags/files/4663012/cmake_failure.txt)

-- 
Christian Schwarzgruber
T: +43 699 194 166 34
E: c.schwarzgruber.cs@gmail.com

**Comment by gevorgyana** [comment]
Oh, sure...
