### ISSUE TITLE
define-obsolete-function-alias needs a third argument

### ISSUE THREAD

**Issue by seelabs** [Andersbakken/rtags#1408]
**Describe the bug**

In emacs 28, the `when` argument of the function `define-obsolete-function-alias` is no longer optional. When loading rtags, it fails with `wrong-number-of-arguments (3 . 4), 2`

**To Reproduce**
1. Use a development version of emacs (emacs 28)
2. Load the rtags library with "m-x load-library rtags"
3. See the error

**Environment (please complete the following information):**

 - OS/Version: popos 20.04
 - RTags(rdm,rc): 2.41 39339388256df662d0084b4a094d03e52748f9e8
 - Emacs: 28.0.50
 - LLVM/Clang: 11

**Additional context**

If I modify the file `rtags.el` and change line 4694 so it reads:
`(define-obsolete-function-alias 'rtags-start-process-maybe 'rtags-start-process-unless-running "xxx")`
then things work correctly. I don't know what the correct value for "xxx" should be, but any string seems to get past the error.

**Comment by zflat** [comment]
The 'when' argument of make-obsolete and related functions is
mandatory since https://emba.gnu.org/emacs/emacs/-/commit/32c6732d16385f242b1109517f25e9aefd6caa5c

**Comment by Andersbakken** [comment]
Should be fixed now. Thanks.
