### ISSUE TITLE
get mangled name of a symbol

### ISSUE THREAD

**Issue by aa755** [Andersbakken/rtags#1436]
**Is your feature request related to a problem? Please describe.**
file browsing C++ code, I often need to find the mangled name of the function whose definition I am looking at.
(so that I can write the logical specification of that function in another file dealing with logics and correctness proofs. functions are identified using mangled names in the logic files)

**Describe the solution you'd like**
I would like `rtags-print-symbol-info` to also print the mangled name.

**Comment by Andersbakken** [comment]
Should be added now.

https://github.com/Andersbakken/rtags/commit/cf4046a73c9c05a3bf49a150b46559ad5966a503
