### ISSUE TITLE
Memory leak: rp process consumes all host memory, and is killed by oom

### ISSUE THREAD

**Issue by AlexanderKlishin** [Andersbakken/rtags#1437]
1. git clone https://github.com/samba-team/samba.git
2. cd samba && ./configure
3. bear -- make
4. rc -J .
5. rp process consumes all host memory, and is killed by oom

Temporary solution: comment out single line
https://github.com/Andersbakken/rtags/compare/master...AlexanderKlishin:rtags:fix_memleak

**Comment by elheremes** [comment]
I had the same problem working with ORB-SLAM3 repository. This temporary solution worked for me, thank you.

**Comment by Andersbakken** [comment]
Sorry about the long turnaround time. I don't think it's a memory leak strictly speaking. Just that there's tons of doxygen comments in the samba project.

You should be able to disable comment parsing by passing: --no-comments when starting rdm
