### ISSUE TITLE
case insensitive completions (symbolname, path)

### ISSUE THREAD

**Issue by Andersbakken** [Andersbakken/rtags#15]

**Comment by samir-memsql** [comment]
Why was this closed? It doesn't appear to have been implemented -- I only get case-sensitive prefix matches from `rdm`.

**Comment by Andersbakken** [comment]
It actually seems to work fine for me both for files and symbolnames. 

E.g.

(setq rtags-symbolnames-case-insensitive t)
(setq rtags-find-file-case-insensitive t)

M-x rtags-find-symbol <RET> server <RET> gives me matches for Server

On the command line I just do this:

rc -F server -I 

How are you reproducing the problem?
