### ISSUE TITLE
Find symbols with a wildcard expression

### ISSUE THREAD

**Issue by oblique** [Andersbakken/rtags#179]
I think this echancement will be useful. Assume that I don't remember exactly the name of the symbol, but I remember that it has the word `find` in it, I want to be able to use `*find*` and get all the symbols. Also it would be nice to support expressions like `*foo*bar*` and have a way to search with case-insensitive.

For now I use `C-x r T` and I manually search in it, but this shows only the tags of the specific file, so if I don't remember in which file the symbol can be then I have to use grep or gtags.

**Comment by Andersbakken** [comment]
This should be working now. I don't entirely know how to make read-from-minibuffer unbind ? but I guess * is the more important wildcard.
