### ISSUE TITLE
rdm uses a lot of memory

### ISSUE THREAD

**Issue by kcburge** [Andersbakken/rtags#200]
I don't know if this is an issue or not.  Perhaps there are some opportunities for reducing memory usage.

Given a project database of 201M, rdm is consuming 1.3GB of memory (resident).

Jobs took 8.26s, (avg 0.36s), dirtying took 0.00s, syncing took 0.19s, saving took 3.49s. We're using 1441mb of memory. 31575 symbols, 10754 symbolNames

**Comment by Andersbakken** [comment]
As of 2.0 we no longer use very much memory.
