### ISSUE TITLE
rdm locked up consuming a lot of cpu but logging nothing

### ISSUE THREAD

**Issue by kcburge** [Andersbakken/rtags#212]
Note: the line numbers may be different in Project.cpp because of changes in mine that I must have (removing missing headers from dependencies on startup):

<pre>
(gdb) info threads
  Id   Target Id         Frame
  3    Thread 0x7f8b3796c700 (LWP 9045) "rdm" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  2    Thread 0x7f8b3716b700 (LWP 9058) "rdm" 0x0000003eb040e87d in read () at ../sysdeps/unix/syscall-template.S:81
* 1    Thread 0x7f8b3796e780 (LWP 8648) "rdm" 0x0000003eafcec703 in select () at ../sysdeps/unix/syscall-template.S:81
(gdb) bt
#0  0x0000003eafcec703 in select () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007f8b37a9f007 in Process::startInternal (this=0x7fffca4c5f20, command=..., a=..., environ=..., timeout=0, execFlags=0)
    at /home/kevin/Source/System/rtags/src/rct/rct/Process.cpp:422
#2  0x00007f8b37a9f853 in Process::exec (this=0x7fffca4c5f20, command=..., a=..., environ=..., timeout=0, flags=0) at /home/kevin/Source/System/rtags/src/rct/rct/Process.cpp:490
#3  0x00007f8b382062fd in CompilerManager::data (c=..., defines=0x0, includePaths=0x7fffca4c6250) at /home/kevin/Source/System/rtags/src/CompilerManager.cpp:71
#4  0x00007f8b38254fd9 in IndexerJob::encode (this=0xbd4230, serializer=...) at /home/kevin/Source/System/rtags/src/IndexerJob.cpp:113
#5  0x00007f8b38254843 in IndexerJob::launchProcess (this=0xbd4230) at /home/kevin/Source/System/rtags/src/IndexerJob.cpp:50
#6  0x00007f8b382bea37 in Server::startJobs (this=0xbc9c50) at /home/kevin/Source/System/rtags/src/Server.cpp:1553
#7  0x00007f8b382bd878 in Server::addJob (this=0xbc9c50, job=std::shared_ptr (count 2, weak 1) 0xbd4230) at /home/kevin/Source/System/rtags/src/Server.cpp:1449
#8  0x00007f8b38269b4d in Project::index (this=0xbd2960, source=..., flags=2, unsavedFiles=..., dirty=...) at /home/kevin/Source/System/rtags/src/Project.cpp:647
#9  0x00007f8b38267892 in Project::updateContents (this=0xbd2960, thread=0x0) at /home/kevin/Source/System/rtags/src/Project.cpp:375
#10 0x00007f8b3827261d in RestoreThread::run()::{lambda()#1}::operator()() const (__closure=0x7f8b30000978) at /home/kevin/Source/System/rtags/src/Project.cpp:58
#11 0x00007f8b382a6e08 in ApplyMove<0ul>::applyMove<RestoreThread::run()::{lambda()#1}&, std::tuple<>>(std::tuple<>&&, std::tuple<>&&, (RestoreThread::run()::{lambda()#1}&)...) (f=...)
    at /home/kevin/Source/System/rtags/src/rct/rct/Apply.h:67
#12 0x00007f8b382a6d71 in applyMove<RestoreThread::run()::{lambda()#1}&, std::tuple<>&>(ApplyMove<std::tuple_size<std::decay<std::tuple<>&>::type>::value>&&, std::decay&&) (f=...,
    t=empty std::tuple) at /home/kevin/Source/System/rtags/src/rct/rct/Apply.h:79
#13 0x00007f8b382a6cb4 in SignalEvent<RestoreThread::run()::{lambda()#1}>::exec() (this=0x7f8b30000970) at /home/kevin/Source/System/rtags/src/rct/rct/EventLoop.h:55
#14 0x00007f8b37a7aa09 in EventLoop::sendPostedEvents (this=0xbc8ce0) at /home/kevin/Source/System/rtags/src/rct/rct/EventLoop.cpp:265
#15 0x00007f8b37a78e33 in EventLoop::exec (this=0xbc8ce0, timeoutTime=-1) at /home/kevin/Source/System/rtags/src/rct/rct/EventLoop.cpp:816
#16 0x0000000000412c19 in main (argc=1, argv=0x7fffca4c78b8) at /home/kevin/Source/System/rtags/src/rdm.cpp:560
(gdb) thread 2
[Switching to thread 2 (Thread 0x7f8b3716b700 (LWP 9058))]
#0  0x0000003eb040e87d in read () at ../sysdeps/unix/syscall-template.S:81
81      T_PSEUDO (SYSCALL_SYMBOL, SYSCALL_NAME, SYSCALL_NARGS)
(gdb) bt
#0  0x0000003eb040e87d in read () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007f8b37a9d073 in ProcessThread::run (this=0xbd9d20) at /home/kevin/Source/System/rtags/src/rct/rct/Process.cpp:95
#2  0x00007f8b37abf3d2 in Thread::localStart (arg=0xbd9d20) at /home/kevin/Source/System/rtags/src/rct/rct/Thread.cpp:19
#3  0x0000003eb0407f33 in start_thread (arg=0x7f8b3716b700) at pthread_create.c:309
#4  0x0000003eafcf4ded in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) thread 3
[Switching to thread 3 (Thread 0x7f8b3796c700 (LWP 9045))]
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
185     62:     movl    (%rsp), %edi
(gdb) bt
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x0000003b30ab1f5c in __gthread_cond_wait (__mutex=<optimized out>, __cond=<optimized out>)
    at /usr/src/debug/gcc-4.8.3-20140624/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/x86_64-redhat-linux/bits/gthr-default.h:864
#2  std::condition_variable::wait (this=<optimized out>, __lock=...) at ../../../../../libstdc++-v3/src/c++11/condition_variable.cc:52
#3  0x00007f8b382728a6 in RestoreThread::run (this=0xbd21c0) at /home/kevin/Source/System/rtags/src/Project.cpp:66
#4  0x00007f8b37abf3d2 in Thread::localStart (arg=0xbd21c0) at /home/kevin/Source/System/rtags/src/rct/rct/Thread.cpp:19
#5  0x0000003eb0407f33 in start_thread (arg=0x7f8b3796c700) at pthread_create.c:309
#6  0x0000003eafcf4ded in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
</pre>

**Comment by Andersbakken** [comment]
I'm going to assume this is fixed in 2.0 due to the changes in our database layer.
