### ISSUE TITLE
Cygwin64 CMake error on install library

### ISSUE THREAD

**Issue by terranpro** [Andersbakken/rtags#215]
Hi guys,

Experimenting with building rtags on Cygwin64 (now that llvm/clang packages have become available for it) and I ran into this cmake error:

CMake Error at src/CMakeLists.txt:169 (install):
  install Library TARGETS given no DESTINATION!

-- Configuring incomplete, errors occurred!`

I worked around it by adding an `ARCHIVE DESTINATION lib` directive:

`install(TARGETS rtags shared
                LIBRARY DESTINATION lib
                ARCHIVE DESTINATION lib
                COMPONENT rtags)`

I found a relevant help thread on cmake mailing list:  http://www.cmake.org/pipermail/cmake/2008-September/023876.html

It seems to suggest just removing LIBRARY.

**Comment by Andersbakken** [comment]
Hi 

Did you ever get this to work properly? (I realize that it's not functioning quite right for you now but still).

Anders

**Comment by terranpro** [comment]
Hey,

Still having to use a workaround to keep `rc -m` from exiting immediately in Emacs.

I've discovered another way to 'workaround.'  If I start `rc -m` from a regular bash shell, then run `rtags-diagnostics` again in Emacs the process seems to stick and doesn't exit.

Looking more closely at rdm output I saw a socket related error log; here's the log from rdm:

`$ rdm --verbose --isystem /usr/lib/clang/x86_64-pc-cygwin/3.4.2/include/`
`listening /home/Brian/.rdm`
`Running with 4 jobs, using args: -ferror-limit=0 -Wall -fspell-checking -Wno-unknown-warning-option`
`Includepaths: -isystem /usr/lib/clang/x86_64-pc-cygwin/3.4.2/include/ -isystem /usr/lib/`
`Restored project /home/Brian/code/async-task/ in 269 ms`
`/usr/local/bin/rc --current-file=/home/Brian/code/async-task/test/async-test.cpp -V /home/Brian/code/async-task/test/async-test.cpp`
`[100%] 1/1 23:26:16 ~/code/async-task/test/async-test.cpp in 1345ms. (669 syms, 1389 symNames, 297 deps, 1 of 295 files, cursors: 884 of 12675, 0 queried) (1306/11ms) (dirty).`
`Socket error 4 104 Connection reset by peer`
`/home/Brian/code/async-task/test/async-test.cpp /usr/lib/gcc/x86_64-pc-cygwin/4.9.2/include/c++/mutex:707:10: error: thread-local storage is unsupported for the current target`
`/usr/lib/gcc/x86_64-pc-cygwin/4.9.2/include/c++/mutex:708:10: error: thread-local storage is unsupported for the current target`
`/home/Brian/code/async-task/async-task/CoroutineTaskContext.hpp:26:8: error: thread-local storage is unsupported for the current target`
`CI::parse loading unit: clang -std=c++11 -c -ferror-limit=0 -Wall -fspell-checking -Wno-unknown-warning-option -DAS_USE_COROUTINE_TASKS -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/home/Brian/code/async-task/async-task -isystem /usr/lib/clang/x86_64-pc-cygwin/3.4.2/include/ -isystem /usr/lib/ /home/Brian/code/async-task/test/async-test.cpp true`

`Jobs took 1.78s, dirtying took 0.01s, syncing took 0.02s, saving took 0.31s. We're using 0mb of memory. 665 symbols, 341 symbolNames`
