### ISSUE TITLE
Integrate rtags with CEDET

### ISSUE THREAD

**Issue by tuhdo** [Andersbakken/rtags#229]
`rtags` is promising. I suggest that you should make `rtags` generates tags that are compatible with CEDET, since CEDET has many utilities for making use of those parsed tags. If you do this, you can reduce the workload put into writing tools for features such as listing references and completions. 

[CEDET architecture](https://www.gnu.org/software/emacs/manual/html_node/semantic/Introduction.html):

                                                               Applications
                                                                      and
                                                                   Utilities
                                                                     -------
                                                                    /       \
                    +---------------+    +--------+    +--------+
              C --->| C      PARSER |--->|        |    |        |
                    +---------------+    |        |    |        |
                    +---------------+    | COMMON |    | COMMON |<--- SPEEDBAR
           Java --->| JAVA   PARSER |--->| PARSE  |    |        |
                    +---------------+    | TREE   |    | PARSE  |<--- SEMANTICDB
                    +---------------+    | FORMAT |    | API    |
         Scheme --->| SCHEME PARSER |--->|        |    |        |<--- ecb
                    +---------------+    |        |    |        |
                    +---------------+    |        |    |        |
        Texinfo --->| TEXI.  PARSER |--->|        |    |        |
                    +---------------+    |        |    |        |
     
                         ...                ...           ...         ...
     
                    +---------------+    |        |    |        |
        Lang. Y --->| Y      Parser |--->|        |    |        |<--- app. ?
                    +---------------+    |        |    |        |
                    +---------------+    |        |    |        |<--- app. ?
        Lang. Z --->| Z      Parser |--->|        |    |        |
                    +---------------+    +--------+    +--------+

As you see, you only need to generate parse tree that follows CEDET format. Then, many utilities, such as Semantic, ECB and Speedbar that are built into Emacs, can make use of it.

Some examples of the application available in CEDET:

- [Interactive outline tree](http://tuhdo.github.io/static/c-ide/helm-semantic-or-imenu-with-struct.gif)
- [Interactive outline tree 2](http://tuhdo.github.io/static/part3/helm-semantic-or-imenu.gif)
- [Symbol references](http://tuhdo.github.io/static/c-ide/semantic-symref.gif)
- [Code completion demo 1](http://tuhdo.github.io/static/c-ide/semantic-boost-demo.gif)
- [Code completion demo 2](http://tuhdo.github.io/static/auto_complete.gif)
- [semantic-idle-summary-mode](http://tuhdo.github.io/static/func_args.jpg)

There are more to it. All of those utilities make use of SemanticDB, which is the results from the built-in C/C++ parser comes with CEDET. But I don't think it can keep up with C++, and Clang does a good job with C++. You can generate common parse tree format for those utilities to use with `rtags` instead of the built-in parser.

It's just my idea that I hope that it could help you focus on improving the parser without rewriting the small utilities again. I am happy to assist you if you plan to implement this.

**Comment by rileyrg** [comment]
Very late to the show but experiencing yet more issues with CEDET: no CEDET is not "esay to setup". And I don't know ańyone with a good story about it. It's a convoluted mess. How it got into base emacs is beyond me. I'm adding this in case anyone else browses this and thinks they are alone in the hellish config hell of cedet/semantic and all the associated utilites such as company, flycheck et al.
