### ISSUE TITLE
Allow for some caching of previous parse results

### ISSUE THREAD

**Issue by bbannier** [Andersbakken/rtags#234]
First I have to say I like rtags a lot and currently use it a lot with [lyuts/vim-rtags](https://github.com/lyuts/vim-rtags).

I wonder if it would reasonably feasible to not immediately discard old parse results when re-indexing a project. This would be very useful when e.g. switching branches often so that re-indexing could be performed much faster.

**Comment by bbannier** [comment]
@Andersbakken, would you mind opening this again as a future improvement? I would love to see this implemented on way or another?

**Comment by Andersbakken** [comment]
Hi Benjamin

I could take another look but I'm can't think of a good way to reduce the
size of the cache. clang's cached output simply is enormous.

Anders

**Comment by bbannier** [comment]
Hi @Andersbakken,

this issue is still dear to me so I spent some time looking at the code.

It appears that one possibility would be to decouple storage of results (say `StorageId`) from file ids (`FileId` aka `uint32_t`) in the currently active project. It should be possible to calculate quasi-unique `StorageId`s by e.g., forming a hash over file contents, dependencies, and flags. This would require a mapping of `FileId -> StorageId` (maybe also vice versa), and some (LRU?) garbage collection of stale stored content. In the code it seems this would likely require a better centralization of how file ids are created.

Taking this further one could even imagine making file ids directly correspond to the hash (i.e., `FileId == StorageId`). I believe this could help reduce the number of moving pieces. Sadly this seems to require some bigger refactorings as currently file ids do not clearly separate null state on the type level, and valid file ids are sometimes assumed to fully cover a finite range of values (also related: usage of `Server::mLastFileId`).

Do these approaches sound feasible to you? If they did, I would be willing to help with the implementation; it would be helpful though if we could decide on an approach and break this (especially the refactorings) down into smaller pieces.

**Comment by Andersbakken** [comment]
Hi Benjamin

Sorry about the delay. I need to do a little more thinking about this first
I think. In general I feel like the idea probably would work but I'm
worried about the amount of stat'ing and hashing of files to determine the
current StorageId. It could maybe be cached and updated when files are
modified.

Just to make sure I understand the rationale for the feature. Is this
because you check out different branches in the same source tree and want
to be able to switch back and forth without reindexing? How do you deal
with builds? Won't you have to rebuild the equivalent when doing this?

I personally use git-worktree(1) to deal with this. I just want to make
sure I understand what problem we're solving.

Anders

**Comment by bbannier** [comment]
Good point about not making simple lookups too expensive. I haven't looked at the code yet, but a different approach addressing this might be to still use fileIds on the lookup level, but change how indexing is performed: The indexer could write results to some global cache indexed by a hash, but also link the results (e.g., just the folder for that fileid) to the existing project stores (e.g., by hard links, soft links, or copying). When indexing a file one could perform lookups into this cache to potentially speed up the indexing for results in the cache (reducing it to the hash calculation, and linking the existing results). Using a global cache would also simplify management since only a single store would need to be configured (with knobs for e.g., max number of files and total size similar to what `ccache` exposes).

> How do you deal with builds? Won't you have to rebuild the equivalent when doing this?

I use `ccache` extensively with cache sizes exceeding 10x the space required for the projects I am working on. Of course there is a trade-off between speed and storage requirements here; I personally weight speed much higher.

Unfortunately `git-worktree` is an incomplete solution for my use case where I often work on very short-lived branches (e.g., to make quick fixes, or to review patches). Setting up a new tree for me leads to cold `ccache` caches, and also would require complete new `rtags` indexing, even though the results are already known elsewhere. I do use `git-worktree` sometimes when working on long-lived feature branches though.
