### ISSUE TITLE
Does symbol lookup/completion only work on compilable buffers?

### ISSUE THREAD

**Issue by kcburge** [Andersbakken/rtags#239]
I don't know if this is my misunderstanding of how rtags works, or if my usage pattern just does not fit rtags, or what.

While I'm making changes to a file, or even adding a new file, if I put the cursor position on a symbol and go to look it up, I seem to (almost always) get RTags: No Results.  I have not dug in to figure out why yet.  Unfortunately, this is what I'm doing MOST of the time when I want to look up a symbol.  It's very rare that the code I'm working on compiles cleanly.

SHOULD this work?

The same goes for completion (which I really don't even try to use) - seems like a buffer in which I'm asking for code completion, by nature, is not going to compile, because I'm half-way typing a name for which I want suggested completions.

I'm guessing that this SHOULD work and my abnormal usage pattern is what's causing it to not do what I expect.  (I.e. only running rc -x peridocally and not having rdm constantly monitor my file changes).

So, basically, RTags only works for me if I'm just looking into something (i.e. doing research, as opposed to actually writing code) *and* I happen to have all the code up to date in rdm.  Which makes the tool only marginally useful.

If this should work, then I will try to figure out why it doesn't.

Just to better clarify my question:
foo.c contains function foo_is_a_func()
I create bar.c (or bar.h)
I save OR haven't saved the source for bar.c/bar.h yet and I type "foo_is_a_func" and then do a symbol lookup.  

Should this jump me to foo_is_a_func()'s definition/declaration?  

Should I have to save bar.c/bar.h first?  

Does rdm have to have indexed bar.c/bar.h before I can jump to "foo_is_a_func()"?

Completion: if I just started typing "foo_is_" and then invoked completion:

Should it return this as a candidate?

Should I have to save bar.c/bar.h first?  

etc.

Thank you!

**Comment by Andersbakken** [comment]
Hi Kevin

I'll close this. We do kinda have this functionality in rtags-follow-symbol-try-harder now.

**Comment by kcburge** [comment]
Thank you!
