### ISSUE TITLE
header files reparse issue

### ISSUE THREAD

**Issue by HongxuChen** [Andersbakken/rtags#248]
There are some cases when header files are not (re-)parsed correctly. Here is a contrived example:

```c++
// test.h
#ifndef TEST_H
#define TEST_H

#if __cplusplus
#include <iostream>
void dump(int i) { std::cout << i << "\n"; }
#else
#include <stdio.h>
void dump(int i) { printf("%d\n", i); }
#endif

#endif
```

```c++
// t1.cpp
#include "test.h"

int main(void) {
  dump(1);
  return 0;
}
```

```c++
// t2.c
#include "test.h"

int main(void) {
  dump(1);
  return 0;
}
```

In this case, `t1.cpp` is treated as cpp and `t2.c` is treated as c, the difference is that macro `__cpluscplus` is defined in the former while not in the latter. 

When rtags index for `t2.c` and `rtags-find-symbol-at-point` on *dump* it correctly jumps to dump definition(printf case) in `test.h` and we can find `printf` symbol. However when `t1.cpp` is *also* indexed, when we have jumped to *dump* from `t1.cpp`,  `rtags-find-symbol-at-point` will fail for `std::cout`. But when we `rtags-reparse-file`, it seems that rtags will think that `__cpluscplus` is already defined and symbol `std::cout` can be found once again, the problem is that in c version dump(t2.c) *printf* will no longer be found. In the meanwhile, when running `normal-mode` for `test.h`, `printf` will be found while `std::cout` not.

I guess this is a problem intrinsic to preprocessing, is there any good way(maybe interactively) to solve this? 

As to these macros, I also find that sometimes a few of them may be defined by build tools(for example, `make -DXXX`), which seems hard to be captured by rtags(not sure about that, but only with parsed from `compile_commands.json` is not enough). Will rtags provide the way(maybe user defined configurations) to handle macro for *each* c/cpp source files?

**Comment by Andersbakken** [comment]
I can't see a fix  to this problem that isn't worse than the symptom.
