### ISSUE TITLE
readme is a bit confusing

### ISSUE THREAD

**Issue by unhammer** [Andersbakken/rtags#261]
The "Usage" section lists a high-level overview without any commands that you'd actually run. The "daemon setup" section might be useful if you use cmake or ninja, but I don't. I had to read the "Architecture" section to get to to the commands I wanted, ie. symlinking the wrapper. 

I suggest at the very least removing the "* Architecture" heading so that it's all part of the "* Usage" section, because it's very easy to skip what looks like implementation details. Ideally, I think there should be a general quick-start paragraph in the beginning, perhaps something like this:

`* Quickstart`

    rdm & # put this in your ~/.config/autostart or wherever you prefer to start user daemons
    ln -s /path/to/rtags/bin/gcc-rtags-wrapper.sh /somewhere/that/is/in/your/path/before/usr/bin/gcc
    ln -s /path/to/rtags/bin/gcc-rtags-wrapper.sh /somewhere/that/is/in/your/path/before/usr/bin/c++
    ln -s /path/to/rtags/bin/gcc-rtags-wrapper.sh /somewhere/that/is/in/your/path/before/usr/bin/cc
    ln -s /path/to/rtags/bin/gcc-rtags-wrapper.sh /somewhere/that/is/in/your/path/before/usr/bin/g++

Test that it works by recompiling a project, then doing `rc -F some_function_name` (replacing `some_function_name` with something actually used in your project). Now set up rtags for your editor: 
`- [[Emacs]]`
`- [[Vim]]`

**Comment by Andersbakken** [comment]
Sorry about the late reply. I tried to improve it a little bit just now.

**Comment by unhammer** [comment]
Looks good =D

**Comment by Andersbakken** [comment]
Thanks :-)
