### ISSUE TITLE
gcc wrapper script recursion

### ISSUE THREAD

**Issue by hrehfeld** [Andersbakken/rtags#264]
See my comments on the commit:
https://github.com/Andersbakken/rtags/commit/cef323f3c2436cc7a398ed4608f7877b20f7878a

**Comment by Andersbakken** [comment]
Good to hear. Thanks for the report.

**Comment by hrehfeld** [comment]
Ah, we both already replied here :+1: https://github.com/Andersbakken/rtags/commit/cef323f3c2436cc7a398ed4608f7877b20f7878a

**Comment by Andersbakken** [comment]
:-)
