### ISSUE TITLE
Exclude directories to index

### ISSUE THREAD

**Issue by saileshkrish** [Andersbakken/rtags#271]
Is it possible to instruct rtags to exclude certain files/directories to be indexed ?

Our build system deposits a bunch of include files in a build directory and I would like to exclude them from what is indexed. 

Sailesh

**Comment by Andersbakken** [comment]
Awesome.

Anders

**Comment by shelper** [comment]
so is there a way to setup workspace based excluding?
setting `.rdmrc` seems to be global..

**Comment by cslux** [comment]
Not at the moment!
