### ISSUE TITLE
libclang: crash detected during parsing

### ISSUE THREAD

**Issue by YorkZ** [Andersbakken/rtags#274]
This problem has driven me crazy during the last few days. I've tried a bunch of configuration to compile Clang, and then compile rtags with the different configuration of Clang builds. But I always ended up with this issue. It's extremely frustrating. 

Here's the error:

    [ 57%] 306/533 16:15:48 ~/swarm/swarm-dev/code/thirdparty/rtbkit/common/bid_request.cc error in 14395ms. (1 deps).
    /home/york/swarm/swarm-dev/code/thirdparty/rtbkit/common/bid_request.cc rp: /home/york/src/llvm-3.5.0/tools/clang/lib/Sema/SemaTemplateInstantiate.cpp:2703: llvm::PointerUnion<clang::Decl*, llvm::SmallVector<clang::Decl*, 4u>*>* clang::LocalInstantiationScope::findInstantiationOf(const clang::Decl*): Assertion `isa<LabelDecl>(D) && "declaration not instantiated in this scope"' failed.
    libclang: crash detected during parsing: {
      'source_filename' : '/home/york/swarm/swarm-dev/code/thirdparty/rtbkit/common/bid_request.cc'
      'command_line_args' : ['-pipe', '-Wall', '-Werror', '-Wno-sign-compare', '-Woverloaded-virtual', '-Wno-mismatched-tags', '-Wno-unused-local-typedef', '-Wno-constexpr-not-const', '-fPIC', '-m64', '-ggdb', '-fno-omit-frame-pointer', '-std=c++0x', '-Wno-deprecated-declarations', '-Wno-deprecated', '-Winit-self', '-fno-omit-frame-pointer', '-std=c++0x', '-msse3', '-Wno-unused-but-set-variable', '-Wno-psabi', '-fno-builtin-malloc', '-fno-builtin-calloc', '-fno-builtin-realloc', '-fno-builtin-free', '-c', '-O3', '-ferror-limit=0', '-fspell-checking', '-Wno-unknown-warning-option', '-DBOOST_DISABLE_ASSERTS', '-D__GXX_EXPERIMENTAL_CXX0X__=1', '-I/home/york/swarm/swarm-dev/code/thirdparty/rtbkit/.', '-I/home/york/local/include', '-I/home/york/local/include/node', '-I/home/york/swarm/swarm-dev/code/thirdparty/rtbkit/leveldb/include', '-I/home/york/local/include', '-I/home/york/swarm/swarm-dev/code/thirdparty/rtbkit/build/x86_64/gen', '-I/home/york/local/include/cairomm-1.0', '-I/home/york/local/lib/cairomm-1.0/include', '-I/usr/include/sigc++-2.0', '-I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include', '-I/usr/include/cairo', '-I/usr/include/glib-2.0', '-I/usr/lib/x86_64-linux-gnu/glib-2.0/include', '-I/usr/include/pixman-1', '-I/usr/include/freetype2', '-I/usr/include/libpng12', '-isystem', '/usr/local/lib/clang/3.5.0/include/'],
      'unsaved_files' : [],
      'options' : 1,
    }
    rp: /home/york/src/llvm-3.5.0/tools/clang/lib/Sema/SemaTemplateInstantiate.cpp:2703: llvm::PointerUnion<clang::Decl*, llvm::SmallVector<clang::Decl*, 4u>*>* clang::LocalInstantiationScope::findInstantiationOf(const clang::Decl*): Assertion `isa<LabelDecl>(D) && "declaration not instantiated in this scope"' failed.
    libclang: crash detected during parsing: {
      'source_filename' : '/home/york/swarm/swarm-dev/code/thirdparty/rtbkit/common/bid_request.cc'
      'command_line_args' : ['-pipe', '-Wall', '-Werror', '-Wno-sign-compare', '-Woverloaded-virtual', '-Wno-mismatched-tags', '-Wno-unused-local-typedef', '-Wno-constexpr-not-const', '-fPIC', '-m64', '-ggdb', '-fno-omit-frame-pointer', '-std=c++0x', '-Wno-deprecated-declarations', '-Wno-deprecated', '-Winit-self', '-fno-omit-frame-pointer', '-std=c++0x', '-msse3', '-Wno-unused-but-set-variable', '-Wno-psabi', '-fno-builtin-malloc', '-fno-builtin-calloc', '-fno-builtin-realloc', '-fno-builtin-free', '-c', '-O3', '-ferror-limit=0', '-fspell-checking', '-Wno-unknown-warning-option', '-DBOOST_DISABLE_ASSERTS', '-D__GXX_EXPERIMENTAL_CXX0X__=1', '-I/home/york/swarm/swarm-dev/code/thirdparty/rtbkit/.', '-I/home/york/local/include', '-I/home/york/local/include/node', '-I/home/york/swarm/swarm-dev/code/thirdparty/rtbkit/leveldb/include', '-I/home/york/local/include', '-I/home/york/swarm/swarm-dev/code/thirdparty/rtbkit/build/x86_64/gen', '-I/home/york/local/include/cairomm-1.0', '-I/home/york/local/lib/cairomm-1.0/include', '-I/usr/include/sigc++-2.0', '-I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include', '-I/usr/include/cairo', '-I/usr/include/glib-2.0', '-I/usr/lib/x86_64-linux-gnu/glib-2.0/include', '-I/usr/include/pixman-1', '-I/usr/include/freetype2', '-I/usr/include/libpng12', '-isystem', '/usr/local/lib/clang/3.5.0/include/'],
      'unsaved_files' : [],
      'options' : 1,
    }
    rp: /home/york/src/llvm-3.5.0/tools/clang/lib/Sema/SemaTemplateInstantiate.cpp:2703: llvm::PointerUnion<clang::Decl*, llvm::SmallVector<clang::Decl*, 4u>*>* clang::LocalInstantiationScope::findInstantiationOf(const clang::Decl*): Assertion `isa<LabelDecl>(D) && "declaration not instantiated in this scope"' failed.
    libclang: crash detected during parsing: {
      'source_filename' : '/home/york/swarm/swarm-dev/code/thirdparty/rtbkit/common/bid_request.cc'
      'command_line_args' : ['-pipe', '-Wall', '-Werror', '-Wno-sign-compare', '-Woverloaded-virtual', '-Wno-mismatched-tags', '-Wno-unused-local-typedef', '-Wno-constexpr-not-const', '-fPIC', '-m64', '-ggdb', '-fno-omit-frame-pointer', '-std=c++0x', '-Wno-deprecated-declarations', '-Wno-deprecated', '-Winit-self', '-fno-omit-frame-pointer', '-std=c++0x', '-msse3', '-Wno-unused-but-set-variable', '-Wno-psabi', '-fno-builtin-malloc', '-fno-builtin-calloc', '-fno-builtin-realloc', '-fno-builtin-free', '-c', '-O3', '-ferror-limit=0', '-fspell-checking', '-Wno-unknown-warning-option', '-DBOOST_DISABLE_ASSERTS', '-D__GXX_EXPERIMENTAL_CXX0X__=1', '-I/home/york/swarm/swarm-dev/code/thirdparty/rtbkit/.', '-I/home/york/local/include', '-I/home/york/local/include/node', '-I/home/york/swarm/swarm-dev/code/thirdparty/rtbkit/leveldb/include', '-I/home/york/local/include', '-I/home/york/swarm/swarm-dev/code/thirdparty/rtbkit/build/x86_64/gen', '-I/home/york/local/include/cairomm-1.0', '-I/home/york/local/lib/cairomm-1.0/include', '-I/usr/include/sigc++-2.0', '-I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include', '-I/usr/include/cairo', '-I/usr/include/glib-2.0', '-I/usr/lib/x86_64-linux-gnu/glib-2.0/include', '-I/usr/include/pixman-1', '-I/usr/include/freetype2', '-I/usr/include/libpng12', '-isystem', '/usr/local/lib/clang/3.5.0/include/'],
      'unsaved_files' : [],
      'options' : 1,
    }

And here's the corresponding JSON compilation database entry:

    [
    ...
    {
      "directory": "/home/york/swarm/swarm-dev/code/thirdparty/rtbkit",
      "command": "g++ -I. -pipe -Wall -Werror -Wno-sign-compare -Woverloaded-virtual -Wno-mismatched-tags -Wno-unused-local-typedef -Wno-constexpr-not-const -fPIC -m64 -ggdb -fno-omit-frame-pointer -I/home/york/local/include -std=c++0x -Wno-deprecated-declarations -Wno-deprecated -Winit-self -fno-omit-frame-pointer -std=c++0x -I/home/york/local/include/node -msse3 -Ileveldb/include -Wno-unused-but-set-variable -I/home/york/local/include -Ibuild/x86_64/gen -I/home/york/local/include/cairomm-1.0 -I/home/york/local/lib/cairomm-1.0/include -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -Wno-psabi -D__GXX_EXPERIMENTAL_CXX0X__=1 -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -o build/x86_64/obj/rtbkit/common/bid_request.a94a12b1aae84f323c5a1c3f9504c0d4.lo -c ./rtbkit/common/bid_request.cc -MP -MMD -MF build/x86_64/obj/rtbkit/common/bid_request.d -MQ build/x86_64/obj/rtbkit/common/bid_request.a94a12b1aae84f323c5a1c3f9504c0d4.lo -O3 -DBOOST_DISABLE_ASSERTS -DNDEBUG",
      "file": "/home/york/swarm/swarm-dev/code/thirdparty/rtbkit/common/bid_request.cc"
    }
    ...
    ]

I'm using Clang 3.5.0. I tried Clang 3.2, but then running "rc -J" produces the "invalid argument `-J`" error. So what is the lowest version of Clang that supports "rc -J"?

Is this a problem of rtags, or Clang?

Please help!

Thanks in advance,
York

**Comment by YorkZ** [comment]
I created a new compile_commands.json which parses only one source file:

    [
    {
      "directory": "/home/york/swarm/swarm-dev/code/thirdparty/rtbkit",
      "command": "g++ -I. -pipe -Wall -Werror -Wno-sign-compare -Woverloaded-virtual -Wno-mismatched-tags -Wno-unused-local-typedef -Wno-constexpr-not-const -fPIC -m64 -ggdb -fno-omit-frame-pointer -I/home/york/local/include -std=c++0x -Wno-deprecated-declarations -Wno-deprecated -Winit-self -fno-omit-frame-pointer -std=c++0x -I/home/york/local/include/node -msse3 -Ileveldb/include -Wno-unused-but-set-variable -I/home/york/local/include -Ibuild/x86_64/gen -I/home/york/local/include/cairomm-1.0 -I/home/york/local/lib/cairomm-1.0/include -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -Wno-psabi -D__GXX_EXPERIMENTAL_CXX0X__=1 -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -o build/x86_64/obj/rtbkit/common/bid_request.a94a12b1aae84f323c5a1c3f9504c0d4.lo -c ./rtbkit/common/bid_request.cc -MP -MMD -MF build/x86_64/obj/rtbkit/common/bid_request.d -MQ build/x86_64/obj/rtbkit/common/bid_request.a94a12b1aae84f323c5a1c3f9504c0d4.lo -O3 -DBOOST_DISABLE_ASSERTS -DNDEBUG",
      "file": "/home/york/swarm/swarm-dev/code/thirdparty/rtbkit/common/bid_request.cc"
    }
    ]

Then I ran "rc -C", and "rc -J". Here's the full output:

    $ [100%] 1/1 16:58:45 ~/swarm/swarm-dev/code/thirdparty/rtbkit/common/bid_request.cc error in 6677ms. (1 deps).
    /home/york/swarm/swarm-dev/code/thirdparty/rtbkit/common/bid_request.cc rp: /home/york/src/llvm-3.5.0/tools/clang/lib/Sema/SemaTemplateInstantiate.cpp:2703: llvm::PointerUnion<clang::Decl*, llvm::SmallVector<clang::Decl*, 4u>*>* clang::LocalInstantiationScope::findInstantiationOf(const clang::Decl*): Assertion `isa<LabelDecl>(D) && "declaration not instantiated in this scope"' failed.
    libclang: crash detected during parsing: {
      'source_filename' : '/home/york/swarm/swarm-dev/code/thirdparty/rtbkit/common/bid_request.cc'
      'command_line_args' : ['-pipe', '-Wall', '-Werror', '-Wno-sign-compare', '-Woverloaded-virtual', '-Wno-mismatched-tags', '-Wno-unused-local-typedef', '-Wno-constexpr-not-const', '-fPIC', '-m64', '-ggdb', '-fno-omit-frame-pointer', '-std=c++0x', '-Wno-deprecated-declarations', '-Wno-deprecated', '-Winit-self', '-fno-omit-frame-pointer', '-std=c++0x', '-msse3', '-Wno-unused-but-set-variable', '-Wno-psabi', '-fno-builtin-malloc', '-fno-builtin-calloc', '-fno-builtin-realloc', '-fno-builtin-free', '-c', '-O3', '-ferror-limit=0', '-fspell-checking', '-Wno-unknown-warning-option', '-DBOOST_DISABLE_ASSERTS', '-D__GXX_EXPERIMENTAL_CXX0X__=1', '-I/home/york/swarm/swarm-dev/code/thirdparty/rtbkit/.', '-I/home/york/local/include', '-I/home/york/local/include/node', '-I/home/york/swarm/swarm-dev/code/thirdparty/rtbkit/leveldb/include', '-I/home/york/local/include', '-I/home/york/swarm/swarm-dev/code/thirdparty/rtbkit/build/x86_64/gen', '-I/home/york/local/include/cairomm-1.0', '-I/home/york/local/lib/cairomm-1.0/include', '-I/usr/include/sigc++-2.0', '-I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include', '-I/usr/include/cairo', '-I/usr/include/glib-2.0', '-I/usr/lib/x86_64-linux-gnu/glib-2.0/include', '-I/usr/include/pixman-1', '-I/usr/include/freetype2', '-I/usr/include/libpng12', '-isystem', '/usr/local/lib/clang/3.5.0/include/'],
      'unsaved_files' : [],
      'options' : 1,
    }
    rp: /home/york/src/llvm-3.5.0/tools/clang/lib/Sema/SemaTemplateInstantiate.cpp:2703: llvm::PointerUnion<clang::Decl*, llvm::SmallVector<clang::Decl*, 4u>*>* clang::LocalInstantiationScope::findInstantiationOf(const clang::Decl*): Assertion `isa<LabelDecl>(D) && "declaration not instantiated in this scope"' failed.
    libclang: crash detected during parsing: {
      'source_filename' : '/home/york/swarm/swarm-dev/code/thirdparty/rtbkit/common/bid_request.cc'
      'command_line_args' : ['-pipe', '-Wall', '-Werror', '-Wno-sign-compare', '-Woverloaded-virtual', '-Wno-mismatched-tags', '-Wno-unused-local-typedef', '-Wno-constexpr-not-const', '-fPIC', '-m64', '-ggdb', '-fno-omit-frame-pointer', '-std=c++0x', '-Wno-deprecated-declarations', '-Wno-deprecated', '-Winit-self', '-fno-omit-frame-pointer', '-std=c++0x', '-msse3', '-Wno-unused-but-set-variable', '-Wno-psabi', '-fno-builtin-malloc', '-fno-builtin-calloc', '-fno-builtin-realloc', '-fno-builtin-free', '-c', '-O3', '-ferror-limit=0', '-fspell-checking', '-Wno-unknown-warning-option', '-DBOOST_DISABLE_ASSERTS', '-D__GXX_EXPERIMENTAL_CXX0X__=1', '-I/home/york/swarm/swarm-dev/code/thirdparty/rtbkit/.', '-I/home/york/local/include', '-I/home/york/local/include/node', '-I/home/york/swarm/swarm-dev/code/thirdparty/rtbkit/leveldb/include', '-I/home/york/local/include', '-I/home/york/swarm/swarm-dev/code/thirdparty/rtbkit/build/x86_64/gen', '-I/home/york/local/include/cairomm-1.0', '-I/home/york/local/lib/cairomm-1.0/include', '-I/usr/include/sigc++-2.0', '-I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include', '-I/usr/include/cairo', '-I/usr/include/glib-2.0', '-I/usr/lib/x86_64-linux-gnu/glib-2.0/include', '-I/usr/include/pixman-1', '-I/usr/include/freetype2', '-I/usr/include/libpng12', '-isystem', '/usr/local/lib/clang/3.5.0/include/'],
      'unsaved_files' : [],
      'options' : 1,
    }
    rp: /home/york/src/llvm-3.5.0/tools/clang/lib/Sema/SemaTemplateInstantiate.cpp:2703: llvm::PointerUnion<clang::Decl*, llvm::SmallVector<clang::Decl*, 4u>*>* clang::LocalInstantiationScope::findInstantiationOf(const clang::Decl*): Assertion `isa<LabelDecl>(D) && "declaration not instantiated in this scope"' failed.
    libclang: crash detected during parsing: {
      'source_filename' : '/home/york/swarm/swarm-dev/code/thirdparty/rtbkit/common/bid_request.cc'
      'command_line_args' : ['-pipe', '-Wall', '-Werror', '-Wno-sign-compare', '-Woverloaded-virtual', '-Wno-mismatched-tags', '-Wno-unused-local-typedef', '-Wno-constexpr-not-const', '-fPIC', '-m64', '-ggdb', '-fno-omit-frame-pointer', '-std=c++0x', '-Wno-deprecated-declarations', '-Wno-deprecated', '-Winit-self', '-fno-omit-frame-pointer', '-std=c++0x', '-msse3', '-Wno-unused-but-set-variable', '-Wno-psabi', '-fno-builtin-malloc', '-fno-builtin-calloc', '-fno-builtin-realloc', '-fno-builtin-free', '-c', '-O3', '-ferror-limit=0', '-fspell-checking', '-Wno-unknown-warning-option', '-DBOOST_DISABLE_ASSERTS', '-D__GXX_EXPERIMENTAL_CXX0X__=1', '-I/home/york/swarm/swarm-dev/code/thirdparty/rtbkit/.', '-I/home/york/local/include', '-I/home/york/local/include/node', '-I/home/york/swarm/swarm-dev/code/thirdparty/rtbkit/leveldb/include', '-I/home/york/local/include', '-I/home/york/swarm/swarm-dev/code/thirdparty/rtbkit/build/x86_64/gen', '-I/home/york/local/include/cairomm-1.0', '-I/home/york/local/lib/cairomm-1.0/include', '-I/usr/include/sigc++-2.0', '-I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include', '-I/usr/include/cairo', '-I/usr/include/glib-2.0', '-I/usr/lib/x86_64-linux-gnu/glib-2.0/include', '-I/usr/include/pixman-1', '-I/usr/include/freetype2', '-I/usr/include/libpng12', '-isystem', '/usr/local/lib/clang/3.5.0/include/'],
      'unsaved_files' : [],
      'options' : 1,
    }
    Failed to parse clang -pipe -Wall -Werror -Wno-sign-compare -Woverloaded-virtual -Wno-mismatched-tags -Wno-unused-local-typedef -Wno-constexpr-not-const -fPIC -m64 -ggdb -fno-omit-frame-pointer -std=c++0x -Wno-deprecated-declarations -Wno-deprecated -Winit-self -fno-omit-frame-pointer -std=c++0x -msse3 -Wno-unused-but-set-variable -Wno-psabi -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -c -O3 -ferror-limit=0 -fspell-checking -Wno-unknown-warning-option -DBOOST_DISABLE_ASSERTS -D__GXX_EXPERIMENTAL_CXX0X__=1 -I/home/york/swarm/swarm-dev/code/thirdparty/rtbkit/. -I/home/york/local/include -I/home/york/local/include/node -I/home/york/swarm/swarm-dev/code/thirdparty/rtbkit/leveldb/include -I/home/york/local/include -I/home/york/swarm/swarm-dev/code/thirdparty/rtbkit/build/x86_64/gen -I/home/york/local/include/cairomm-1.0 -I/home/york/local/lib/cairomm-1.0/include -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -isystem /usr/local/lib/clang/3.5.0/include/ /home/york/swarm/swarm-dev/code/thirdparty/rtbkit/common/bid_request.cc

    Jobs took 7.22s, dirtying took 0.00s, syncing took 0.00s, saving took 0.00s. We're using 1142mb of memory. 0 symbols, 2 symbolNames

Please help!

York

**Comment by Andersbakken** [comment]
Hi

Sorry about the delay. Have you tried to disable assertions when building
clang? I am pretty convinced this is a clang bug and I think it might make
sense to put together a small example that reproduces this without rtags.

Can you try to run this command in your terminal:
clang -pipe -Wall -Werror -Wno-sign-compare -Woverloaded-virtual
-Wno-mismatched-tags -Wno-unused-local-typedef -Wno-constexpr-not-const
-fPIC -m64 -ggdb -fno-omit-frame-pointer -std=c++0x
-Wno-deprecated-declarations -Wno-deprecated -Winit-self
-fno-omit-frame-pointer -std=c++0x -msse3 -Wno-unused-but-set-variable
-Wno-psabi -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc
-fno-builtin-free -c -O3 -ferror-limit=0 -fspell-checking
-Wno-unknown-warning-option -DBOOST_DISABLE_ASSERTS
-D__GXX_EXPERIMENTAL_CXX0X__=1
-I/home/york/swarm/swarm-dev/code/thirdparty/rtbkit/.
-I/home/york/local/include -I/home/york/local/include/node
-I/home/york/swarm/swarm-dev/code/thirdparty/rtbkit/leveldb/include
-I/home/york/local/include -I/home/york/swarm/swarm-dev/
code/thirdparty/rtbkit/build/x86_64/gen -I/home/york/local/include/cairomm-1.0
-I/home/york/local/lib/cairomm-1.0/include -I/usr/include/sigc++-2.0
-I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/cairo
-I/usr/include/glib-2.0
-I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1
-I/usr/include/freetype2 -I/usr/include/libpng12 -isystem
/usr/local/lib/clang/3.5.0/include/ /home/york/swarm/swarm-dev/
code/thirdparty/rtbkit/common/bid_request.cc

Make sure it's running the same clang version as the one you're using with
rtags?

Also. Do you think you could run this command and send me the output (it
will be a lot):

clang -pipe -Wall -Werror -Wno-sign-compare -Woverloaded-virtual
-Wno-mismatched-tags -Wno-unused-local-typedef -Wno-constexpr-not-const
-fPIC -m64 -ggdb -fno-omit-frame-pointer -std=c++0x
-Wno-deprecated-declarations -Wno-deprecated -Winit-self
-fno-omit-frame-pointer -std=c++0x -msse3 -Wno-unused-but-set-variable
-Wno-psabi -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc
-fno-builtin-free -c -O3 -ferror-limit=0 -fspell-checking
-Wno-unknown-warning-option -DBOOST_DISABLE_ASSERTS
-D__GXX_EXPERIMENTAL_CXX0X__=1
-I/home/york/swarm/swarm-dev/code/thirdparty/rtbkit/.
-I/home/york/local/include -I/home/york/local/include/node
-I/home/york/swarm/swarm-dev/code/thirdparty/rtbkit/leveldb/include
-I/home/york/local/include -I/home/york/swarm/swarm-dev/
code/thirdparty/rtbkit/build/x86_64/gen -I/home/york/local/include/cairomm-1.0
-I/home/york/local/lib/cairomm-1.0/include -I/usr/include/sigc++-2.0
-I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/cairo
-I/usr/include/glib-2.0
-I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1
-I/usr/include/freetype2 -I/usr/include/libpng12 -isystem
/usr/local/lib/clang/3.5.0/include/ /home/york/swarm/swarm-dev/
code/thirdparty/rtbkit/common/bid_request.cc -E

I was hoping to use it to reproduce the crash.

Anders

**Comment by YorkZ** [comment]
Hi Andersbakken,

Thank you so much for your help. I've finally figured out the exact line in the project that causes libclang to crash, it's in the file "json_parsing.h":

    struct JsonParsingContext {
        ...
        virtual void forEachMember(const std::function<void ()> & fn) = 0;
    }

    struct StreamingJsonParsingContext
        : public JsonParsingContext  {
        ...

        template<typename Fn>
        void forEachMember(const Fn & fn)
        {
            ...
        }

        virtual void forEachMember(const std::function<void ()> & fn)
        {
            /// This line causes libclang parser to crash.
            return forEachMember<std::function<void ()> >(fn); 
        }
    }

As soon as I commented out that line, libclang no longer crashes. I apologize for reporting the issue here.

I really appreciate your help to try to reproduce this libclang issue. I will definitely try your suggestions later.

Thank a lot,
York

**Comment by Andersbakken** [comment]
Glad to hear that. Would like to see it fixed in libclang.

Anders

**Comment by YorkZ** [comment]
Yes, I will report this bug to Clang. But I guess they will ask me to reproduce it in a minimal environment which will take some time.

**Comment by Andersbakken** [comment]
Yeah. If you need help with that I could probably be of assistance.

Anders

**Comment by YorkZ** [comment]
> Yeah. If you need help with that I could probably be of assistance.

Thanks in advance.

York
