### ISSUE TITLE
List all defined and/or declared symbols in a given file

### ISSUE THREAD

**Issue by xuhdev** [Andersbakken/rtags#277]
This can be useful to integrate with speedbar or ecb to display all useful symbols in a buffer. Probably also related to #229.

**Comment by Andersbakken** [comment]
Hi Hong

Sorry about the delay. There's actually something similar to this already
in rtags-imenu. I'm sure the elisp could be tweaked to integrate with
speedbar or ecb relatively easily.

Anders
