### ISSUE TITLE
Tramp buffers parsing?

### ISSUE THREAD

**Issue by chep** [Andersbakken/rtags#278]
I often have tramp buffers, but not for code. My org agenda for example.
When I use rtags (daily) sometimes completion is very slow and I can see tramp messages:
Tramp: Waiting for prompts from remote shell...done

This is very annoying particularly because tramp buffers do not contain source code.

I tried to enable debug on quit but I got no backtrace. I don't know how to reproduce this problem, I think it only occurs when tramp connections are out of date.

Is it possible to tell rtags to ignore some buffers or something like that?

**Comment by Andersbakken** [comment]
Hi Cedric

Sorry about the delay. I have to admit I'm not entirely sure what the issue
is here but I added something to explicitly disregard tramp buffers as far
as rtags is concerned.

Incidentally. Do you know of a better way to detect that something is a
tramp buffer than (string-match "^ssh:" (buffer-file-name)) ?

Anders

**Comment by chep** [comment]
Hi Anders,

I'm gonna try with your last commit and tell you if I still see the problem.

Someone on IRC gave me this code: (file-remote-p (buffer-file-name)). It seems
to work for both ssh and sudo files but there is an error if (buffer-file-name)
returns nil so you must check it before.

Regards.

**Comment by chep** [comment]
file-remote-p function may try to connect to the remote and could be long. (tramp-tramp-file-p (buffer-file-name)) seems to work better even if (buffer-file-name) returns nil.
