### ISSUE TITLE
I use emacs in putty, when use rtags find symbol, this will make buffer messy. Is rtags support emacs in terminal?

### ISSUE THREAD

**Issue by suteng** [Andersbakken/rtags#279]

**Comment by Andersbakken** [comment]
Hi

Well. It should work but I don't ever test it. Messy how? We use these two standard faces for decorating the results buffer:

    font-lock-string-face
    font-lock-function-name-face

Maybe you need to remove any custom formatting from them?

Can you send a screen shot?

Anders

**Comment by suteng** [comment]
I have find the reason, because I start rdm and emacs in the same terminal, when use rtags-find-symbol, rdm will print some message in the termianl, this will affect the emacs, but I don't know why.

**Comment by Andersbakken** [comment]
Ah. That makes sense. Rdm is not quiet by default. You could do this:

rdm --silent &

I would rather recommend running it in screen though if you want to only
have one putty session open.

E.g.

screen
rdm
[C-A] d (default key binding I think)

Anders
