### ISSUE TITLE
Changing a global header reparses entire project each time.

### ISSUE THREAD

**Issue by Nephyrin** [Andersbakken/rtags#280]
We have a few headers that end up in scope of the majority of the codebase. Editing one, especially with `rtags-enable-unsaved-reparsing` set, causes rdm to begin recompiling thousands of files. Worse, rtags seems to immediately throw out the old parse data when this happens, effectively disabling rtags for minutes while it catches up.

**Comment by Nephyrin** [comment]
Correction: rdm is slow to respond during this reparsing, but it does continue to return existing data while the reparse happens. A lower -y value to rdm made this less of an issue, though the 20m+ of CPU use every time I touch the file is still undesirable.

**Comment by Andersbakken** [comment]
Hi John

Sorry about the delay. I agree that this definitely is a problem but it's
hard to decide else to actually do. We automatically reparse all files that
depend on the modified file when it changes (its mtime). There is a feature
that already exists where you can suspend certain files.

E.g. if you know you're going to modify a file that has a lot of dependents
you can do

M-x rtags-toggle-file-suspended

first and no reparsing will happen.

Anders

**Comment by Nephyrin** [comment]
I agree that it seems hard to solve this without some much more in-depth AST-diffing to determine how changes affect the context of another file. I think a few factors made this more annoying to me than it needed to be:
- I had a manual -y value that made RDM slow to respond, so the recompilation-in-progress hampered using rtags
- I had `(rtags-diagnostics)` in a hook for opening new files. This was unconditionally dirtying the visited file (bug?) and was thus causing every header I visited to be dirtied. Combine with `rtags-find-references-at-point` to invalidate 4k files quickly!

With these fixed this has been much less of an issue, though rdm does spend a considerable part of the day recompiling things repeatedly :-/

**Comment by Andersbakken** [comment]
Hi John

Ah. I can see how that could make matters even worse. We have some changes
that we're working on in a separate branch that I hope will alleviate this
somewhat. We're planning to store our database in a way that allows us to
more or less completely skip the sync step. Also, we've put in a mechanism
by which emacs can tell rtags which files are currently open which allows
us to schedule reparsing of those files first. We could disregard
diagnostics for files that arent't open. You can check it out in the "file"
branch. It's not quite ready but we're getting close.

Anders

**Comment by Andersbakken** [comment]
I fixed the bug that would unconditionally reparse the buffer on rtags-diagnostics btw.

**Comment by Andersbakken** [comment]
I don't know if you've had a chance to update lately but we've made some changes that hopefully would improve the situation. We're still reparsing all dependencies but we're trying harder to have rtags be usable while things are being reparsed.
