### ISSUE TITLE
rtags-rename-symbol and macro fail

### ISSUE THREAD

**Issue by Gravemind** [Andersbakken/rtags#281]
If I try to `rtags-rename-symbol` a symbol used inside a macro, the marco gets weirdly replaced too.

eg: If I rename `CToRename` to `CRenamed`:
```C++

template <typename _T>
class TPtr
{
};

#define FORWARD_DECLARE(__class)				\
	class C ## __class;							\
	typedef TPtr<C ## __class > P ## __class

class CToRename
{
public:
	CToRename() {}
	~CToRename() {}
private:
};

FORWARD_DECLARE(ToRename);

int main(int argc, char const * const * argv)
{
	CToRename		c;
	return 0;
}
```
It's fine except the `FORWARD_DECLARE(ToRename);` line gets renamed to:
```C++
CRenamedECLARE(ToRename);
```

I much rather see the macro not renamed at all.

**Comment by Andersbakken** [comment]
Hi

Sorry about the delay. I see that it's causing some problems. Will try to
see if I can fix it.

Anders

**Comment by Andersbakken** [comment]
It should be fixed. I have to admit I'm a bit puzzled as to how you discovered this. It almost seems like a construct designed to do nothing but break our rename algorithm :) As part of the fix I also tried to make it a little safer. E.g. Check that the word we're replacing actually is what it should be and bail if it isn't.

Thanks for the report.
