### ISSUE TITLE
rc location syntax is un/mis-documented

### ISSUE THREAD

**Issue by DeadParrot** [Andersbakken/rtags#282]
The README implies the syntax for "location" is `filename,position` where position is not defined. The actual syntax for rc locations (based on experimentation) is:
```
rc --follow-location filename:line:col
```
where `col` is the character column position (counting any tab indents as 1 character).

The `rc --help` and `man rc` don't define location at all. For scripting applications documentation for `rc` is essential. And this looks like a great system that can be very useful for C++ analysis and transformation tasks.

**Comment by Andersbakken** [comment]
Hi Stuart

I've updated that section to reflect the current format. I absolutely agree
that the documenation is a bit lacking all over rtags. I'll try to add
something when I get around to it. Feel free to shoot me any question about
anything that's underdocumented.

Anders

**Comment by DeadParrot** [comment]
@Andersbakken Great! I'm using it from a code migration script over the few weeks so I may have more input as I go. After hitting a wall with clang-tags and clang-ctags and all the others it is great to have a system that works!
