### ISSUE TITLE
Tramp error when completing

### ISSUE THREAD

**Issue by moonlite** [Andersbakken/rtags#285]
I get this when I try to complete using `company-rtags`:
```Symbol's function definition is void: tramp-tramp-file-p```

I looked in rtags.el and found this:

```el
(defun rtags-is-indexed (&optional buffer)
  (let ((path (buffer-file-name buffer)))
    (cond ((not path) nil)
          ((tramp-tramp-file-p path) nil)
          ((equal (rtags-buffer-status buffer) 'rtags-indexed)))))
```

If I remove the call to `tramp-tramp-file-p` completion works fine.

**Comment by Andersbakken** [comment]
It should work now. Let me know if you have problems. Thanks for the report.

**Comment by moonlite** [comment]
Thanks for the quick fix!

**Comment by Andersbakken** [comment]
My pleasure :-)

On Mon, Feb 9, 2015 at 10:00 PM, Mattias Bengtsson <notifications@github.com
