### ISSUE TITLE
rtags-find-symbol doesn't use ido

### ISSUE THREAD

**Issue by moonlite** [Andersbakken/rtags#286]
I'm using Ido for mostly everything and enjoy it a lot and would love for rtags-find-symbol to use it as well when available. Would this be possible?

**Comment by Andersbakken** [comment]
It's kinda tricky actually. The dataset is way too large for ido to handle
I'm afraid. We have to do the filtering in c++ in the daemon to be able to
make it performant enough to use. I would love to be able to use ido but
for it myself but I just don't think it's feasible.

Admittedly I haven't really tested it but there's some 279833 unique
symbols in rtags alone which I highly doubt ido can handle.

Anders

**Comment by moonlite** [comment]
Oh, I see. That's sad. 

Thanks for the quick reply though!
