### ISSUE TITLE
Error message when finding symbol: bookmark-alist-from-buffer: Not bookmark format

### ISSUE THREAD

**Issue by mraway** [Andersbakken/rtags#287]
This is the error message I got when using rtags to find a symbol, is there any direction on what could be possibly wrong?

Upgrading bookmark format from 0 to 1...
bookmark-alist-from-buffer: Not bookmark format

Thanks

**Comment by mraway** [comment]
Update:
Here is how to trigger the problem: after I use the rtags find references, a *rtags* buffer is displayed in plain text mode (fundamental), this is weird because it should be a different mode. After that, finding symbol stopped working as well, the above messages show up, it seems like a emacs bookmark compatibility issue.

**Comment by mraway** [comment]
Update 2:
I deleted the ~/.emacs.d/bookmark file and problem was fixed.

**Comment by Andersbakken** [comment]
Hi

Odd. I'm inclined to suspect that it's unrelated to rtags though. If you
find a way to reliably reproduce it that would be great.

Anders

**Comment by ramblehead** [comment]
Hello,

I run in to the same issue today. It seems that I can reproduce this problem by creating an empty `bookmarks` file in my `.emacs.d`. The file is the most likely created by the [bookmark](https://www.gnu.org/software/emacs/manual/html_node/emacs/Bookmarks.html) package, which I do not normally use. When this file does not exist or it is not empty (e.g. created by pressing `‘C-x r m’`), then everything works fine. When `.emacs.d/bookmarks` file exits and empty then rtags if failing to find symbol with the following messages:

```
Upgrading bookmark format from 0 to 1...
bookmark-alist-from-buffer: Not bookmark format
```

rh

**Comment by Andersbakken** [comment]
I can reproduce the problem but I have to say this is not really for rtags
to fix.

I have committed a workaround that keeps rtags functioning but really the
user for whom this happens has to go and remove the broken bookmark file.
The workaround also disables normal rtags functionality that relies on
bookmarks.

Anders

**Comment by sergeyklay** [comment]
Than you @mraway 
Deleting ~/.emacs.d/bookmark fixes my issue too
