### ISSUE TITLE
Linker error when building under cygwin

### ISSUE THREAD

**Issue by sigma914** [Andersbakken/rtags#288]
Hi,

I get the following linker errors, all related the SHA256 functions when building under cygwin.

    FAILED: : && /usr/bin/c++.exe  -Wextra -Wall -fno-rtti -Wall -fstack-protector-all -Wstack-protector -std=gnu++0x -O3 -DNDEBUG  -Wl,--enable-auto-import src/CMakeFiles/rp.dir/rp.cpp.o 
    src/CMakeFiles/rp.dir/ClangIndexer.cpp.o  -o bin/rp.exe -Wl,--out-implib,src/librp.dll.a -Wl,--major-image-version,0,--minor-image-version,0  src/librtags.a src/libshared.a src/rct/librct.a -lz -Wl,--start-group -L/usr/lib -lclang -Wl,-rpath,/usr/lib -Wl,--end-group -lstdc++ && :
    src/rct/librct.a(SHA256.cpp.o):SHA256.cpp:(.text+0x25e): undefined reference to `SHA256_Final'
    src/rct/librct.a(SHA256.cpp.o):SHA256.cpp:(.text+0x25e): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `SHA256_Final'
    src/rct/librct.a(SHA256.cpp.o):SHA256.cpp:(.text+0x267): undefined reference to `SHA256_Init'
    src/rct/librct.a(SHA256.cpp.o):SHA256.cpp:(.text+0x267): relocation truncated to fit: 
    src/rct/librct.a(SHA256.cpp.o):SHA256.cpp:(.text+0x3ec): undefined reference to `SHA256_Update'
    src/rct/librct.a(SHA256.cpp.o):SHA256.cpp:(.text+0x3ec): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `SHA256_Update'

    ...

    ninja: build stopped: subcommand failed.

I definitely have the openssl-devel package installed, but cmake doesn't seem to be specifying it in the linker arguments.

Thanks!

**Comment by Andersbakken** [comment]
Hi

Ah. It seems some of the cmakery is off. Can you try now? We don't actually
have a Windows machine to test.

Anders

**Comment by sigma914** [comment]
That seems to have fixed it, linking succeeded all around.

Thanks for the quick response and sorry for the delay, had to wait
til I was back in work until _I_ had a windows machine to test on.

Thanks!

**Comment by Andersbakken** [comment]
Glad to hear. Let me know if you have other issues.

Anders

**Comment by kingram6865** [comment]
Could someone explain what was changed in the cmake link lines?

**Comment by cslux** [comment]
@kingram6865 What does the git history say?

**Comment by kingram6865** [comment]
@cslux it says make changes to CMakeLists.txt which I did not see was a link.
But the changes seem to be irrelevant, as I cannot find those lines anywhere in the source.

**Comment by cslux** [comment]
```bash
git log -p -G'MATCHES "Linux"'
```

Is this what you are looking after?

**Comment by kingram6865** [comment]
No. I am attempting to fix this problem:

$ make
[ 90%] Built target chromaprint_objs
[ 95%] Linking CXX shared library cygchromaprint-1.dll
/usr/local/lib/libavutil.a(random_seed.o): In function `av_get_random_seed':
/home/kingram/src/ffmpeg/libavutil/random_seed.c:126: undefined reference to `BCryptOpenAlgorithmProvider'
/home/kingram/src/ffmpeg/libavutil/random_seed.c:126:(.text+0x28): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `BCryptOpenAlgorithmProvider'
/home/kingram/src/ffmpeg/libavutil/random_seed.c:129: undefined reference to `BCryptGenRandom'
/home/kingram/src/ffmpeg/libavutil/random_seed.c:129:(.text+0x44): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `BCryptGenRandom'
/home/kingram/src/ffmpeg/libavutil/random_seed.c:130: undefined reference to `BCryptCloseAlgorithmProvider'
/home/kingram/src/ffmpeg/libavutil/random_seed.c:130:(.text+0x52): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `BCryptCloseAlgorithmProvider'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/chromaprint.dir/build.make:122: src/cygchromaprint-1.dll] Error 1
make[1]: *** [CMakeFiles/Makefile2:194: src/CMakeFiles/chromaprint.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by cslux** [comment]
What has this to do with RTags?

**Comment by kingram6865** [comment]
Apparently google thought it was relevant to the question I asked.
So maybe just let this exchange die now?

**Comment by cslux** [comment]
I'm afraid, but I don't know out of my head what is going on here.

Try searching for "ffmpeg cygwin" in DuckDuckGo:

https://ffmpeg.org/platform.html
https://www.lesliesikos.com/install-ffmpeg-under-windows/

regards,
Christian
