### ISSUE TITLE
commit ab59ff04b05508494332fa88476efdb4b3534671 broke diagnostics?

### ISSUE THREAD

**Issue by chep** [Andersbakken/rtags#292]
My rtags-diagnostics-process variable is always nil:

(if (cond ((not rtags-diagnostics-process) t)
              ((eq (process-status rtags-diagnostics-process) 'exit) t)
              ((eq (process-status rtags-diagnostics-process) 'signal) t)
              (t nil))
        (unless nodirty
          (rtags-reparse-file))
        (let ((process-connection-type (not rtags-diagnostics-use-pipe))) ;; use a pipe if rtags-diagnostics-use-pipe is t
          (setq rtags-diagnostics-process (start-process "RTags Diagnostics" buf (rtags-executable-find "rc") "-m"))
          (set-process-filter rtags-diagnostics-process (function rtags-diagnostics-process-filter))
          (rtags-clear-diagnostics))))

The 'unless' block is executed (or not) but the 'let' block is only executed when the 'if' condition is nil.
I fixed it by using a 'when' instead of the 'if'.

**Comment by Andersbakken** [comment]
Should work now. Sorry about that.
