### ISSUE TITLE
Configure stage doesn't detect missing curses libs

### ISSUE THREAD

**Issue by martinal** [Andersbakken/rtags#293]
No big deal, but I've installed rtags on a fairly fresh ubuntu 14.10 system and didn't have curses installed, and it wasn't not found until linking stage:

Linking CXX executable ../bin/rc
/usr/bin/ld: cannot find -lcurses

I'm now using rtags -> colorgcc -> ccache for https://bitbucket.org/fenics-project/dolfin/ and this works great! I'll definitely be telling the rest of the team about rtags.

**Comment by Andersbakken** [comment]
Takk for bugrapport. Skal være fiksa nå.

**Comment by Andersbakken** [comment]
Hei Martin

Jobber du tilfeldigvis med Benjamin Kehlet? Vi er veldig gode venner.

Anders

**Comment by martinal** [comment]
Stemmer. Og jeg har jobbet med Henrik i Tandberg.

Martin
6. mar. 2015 06.40 skrev "Anders Bakken" <notifications@github.com>:

> Hei Martin
>
> Jobber du tilfeldigvis med Benjamin Kehlet? Vi er veldig gode venner.
>
> Anders
>
> On Tue, Mar 3, 2015 at 2:54 AM, Martin Sandve Alnæs <

**Comment by Andersbakken** [comment]
Hah. Var du termvakt på blindern også kanskje?

**Comment by martinal** [comment]
Niks :) var på Blindern 2001-2006.

Martin
6. mar. 2015 07.09 skrev "Anders Bakken" <notifications@github.com>:

> Hah. Var du termvakt på blindern også kanskje?
>
> On Thu, Mar 5, 2015 at 10:05 PM, Martin Sandve Alnæs <
