### ISSUE TITLE
"Only reparse if we actually need to recreate the diagnostics buffer." Regresses diagnostics

### ISSUE THREAD

**Issue by Nephyrin** [Andersbakken/rtags#294]
Ironically as I was the one to complain about this, commit ab59ff0 regresses diagnostics for me. The diagnostics buffer never contains any entries, and no overlays are created. Reverting ab59ff0 fixes diagnostics on both `master` and `file`.

**Comment by Andersbakken** [comment]
Should work now. Sorry about that.
