### ISSUE TITLE
Overlays are misaligned with tabs

### ISSUE THREAD

**Issue by Nephyrin** [Andersbakken/rtags#296]
When working in a file with tabs (possibly against one's will), rtags overlays are mis-aligned.

This seems to be due to using clang's line:character output as line:column in emacs, which doesn't take multi-column characters into account.

Replacing `move-to-column` with `forward-char` in `rtags-goto-line-col` fixes this for me, but I'm not sure if other places are passing actual-column-positions to said function.

**Comment by Andersbakken** [comment]
Hm. It was actually a contribution from someone that changed it from forward-char to move-to-column. I never entirely understood what it supposedly fixed. Will look into it.

**Comment by Andersbakken** [comment]
Does this fix it?

**Comment by Nephyrin** [comment]
It does, thanks!
