### ISSUE TITLE
Debugger entered--Lisp error: (void-variable repeat-on-final-keystroke)

### ISSUE THREAD

**Issue by xwl** [Andersbakken/rtags#297]
Should explicitly load it: (require 'repeat)

Debugger entered--Lisp error: (void-variable repeat-on-final-keystroke)
  (eq repeat-on-final-keystroke t)
  (if (eq repeat-on-final-keystroke t) last-command-event (car (memq last-command-event (listify-key-sequence repeat-on-final-keystroke))))
  (let ((repeat-char (if (eq repeat-on-final-keystroke t) last-command-event (car (memq last-command-event (listify-key-sequence repeat-on-final-keystroke))))) (instack (nth rtags-location-stack-index rtags-location-stack)) (cur (rtags-current-location))) (if (not (string= instack cur)) (rtags-goto-location instack t) (let ((target (+ rtags-location-stack-index by))) (if (and (>= target 0) (< target (length rtags-location-stack))) (progn (setq rtags-location-stack-index target) (rtags-goto-location (nth rtags-location-stack-index rtags-location-stack) t))))) (if repeat-char (progn (set-transient-map (let ((map (make-sparse-keymap))) (define-key map (vector repeat-char) (list (quote lambda) nil (quote ...) (list ... by))) map)))))
  rtags-location-stack-jump(1)
  rtags-location-stack-back()
  call-interactively(rtags-location-stack-back nil nil)
  command-execute(rtags-location-stack-back)

**Comment by LefterisJP** [comment]
+1 also experiencing this with latest master checkout

**Comment by Andersbakken** [comment]
Oops. Sorry about that.
