### ISSUE TITLE
.rtags data files won't work across machines?

### ISSUE THREAD

**Issue by henry-y** [Andersbakken/rtags#300]
So, there are two machines, A and B.

on A: rtags and compilers are installed, so I've successfully created the .rtags files and I can rtags-find-symbol, etc.
on B: rtags is installed but compilers are not, so I've copied the .rtags files from A to B, both at the same location, plus, I doubt that the rtags recorded the full path of source files, so I've created the same source tree at B. But when I rtags-find-symbol, output from *Rtags* says that it's not indexed.

**Comment by Andersbakken** [comment]
We do actually store absolute paths so if your directory structure is
exactly the same (including system headers etc) it should work fine I
think. (Never tried though).

Anders

**Comment by henry-y** [comment]
Anyway, I can't get it work, but I think it's not an important scenario
