### ISSUE TITLE
Build failure with gcc 4.7

### ISSUE THREAD

**Issue by artagnon** [Andersbakken/rtags#302]
I tried building rTags against my llvm and clang trees (see #301). Apart from tons of warnings, there seems to be atleast one fatal error in rct:
```
/home/rramacha/src/rtags/src/FileManager.cpp:123:35: error: call of overloaded ‘remove(const char*)’ is 
ambiguous
/home/rramacha/src/rtags/src/FileManager.cpp:123:35: note: candidates are:
In file included from /home/rramacha/src/rtags/src/rct/rct/Path.h:9:0,
                 from /home/rramacha/src/rtags/src/FileManager.h:19,
                 from /home/rramacha/src/rtags/src/FileManager.cpp:16:
/home/rramacha/src/rtags/src/rct/rct/Set.h:25:10: note: bool Set<T>::remove(const T&) [with T = String]
/home/rramacha/src/rtags/src/rct/rct/Set.h:34:9: note: int Set<T>::remove(std::function<bool(const T&)>)
 [with T = String]
```

Apparently, a const T& can be wrapped into a std::function<bool(const T&)> implicitly. Some guidance?

**Comment by Andersbakken** [comment]
I kinda can't reproduce this on current master clang/llvm/libcxx/libcxxabi. 

llvm
commit 4bf95b38b27f7e85dab452e4304919ae2543fd6b
libcxx
commit 6fb33ea8fb10be941c1b66d7054a67a9356a893d
libcxxabi
commit fdd39fd838828bba84c4f7ad620207ae0d734ad5
clang
commit 1443d728a3a59925af36d23d58f2a95f7386c1dc

**Comment by artagnon** [comment]
Sorry, gcc is picked up.

```
-- Using compiler /usr/bin/c++
$ /usr/bin/c++ --version
c++ (Debian 4.7.2-5) 4.7.2
```

In any case, we should not advertise that compiling with gcc 4.7 works. Any idea how to use clang as first preference, with gcc as fallback?

**Comment by Andersbakken** [comment]
Ah. I can see the issue now. I think it's just a bug in 4.7 but I was able
to work around it.
