### ISSUE TITLE
why am I getting this error?

### ISSUE THREAD

**Issue by henry-y** [Andersbakken/rtags#304]
FileSystemWatcher::watch() watch failed for '/home/henry/projects/mc_pkg/' (28) No space left on device

I have space at my home directory, is there any other places I should notice?
btw, I'm not root on this machine.

**Comment by Andersbakken** [comment]
Hi Henry

This is because inotify_add_watch set errno to ENOSPC

E.g.
The user limit on the total number of inotify watches was reached or the kernel failed to allocate a needed resource.

I'm not quite sure what the limit is. I do know that we are a little bit wasteful with these. I'll look into being more efficient about how many directories to watch.

**Comment by henry-y** [comment]
OK, thanks for clarification

2015-03-12 15:09 GMT+08:00 Anders Bakken <notifications@github.com>:

**Comment by henry-y** [comment]
@Andersbakken One more thing, does this affect the initial collection of tags? If this error pops up, does it mean that some tags are not collected?

**Comment by Andersbakken** [comment]
No. It only matters for our ability to track changes to files to reindex at the right time. Btw. When it happens, can you do a:

rc -s watchedpaths 

and send me the output? (probably quite a bit)

**Comment by henry-y** [comment]
Sorry, I can't provide you with the exact output. But it can be seen that
the output file is 929K, and there are 8232 lines, it seems every directory
which has .h or .c files in it is listed there.

2015-03-12 16:11 GMT+08:00 Anders Bakken <notifications@github.com>:

**Comment by henry-y** [comment]
@Andersbakken Can I specify the only paths which needs be watched, please?

**Comment by Andersbakken** [comment]
Not currently. I could probably add something.

Could you try to run rdm with -M

This might help. It should vastly cut down on the number of directories we
watch.

Anders

**Comment by henry-y** [comment]
Yes, this helps. sorry I didn't check manual carefully, so it says

--no-filemanager-watch|-M
             Don't use a file system watcher for filemanager.

does it mean those paths are not watched, or not just watched by file
system watcher, but by some other mechanism?

2015-03-13 15:44 GMT+08:00 Anders Bakken <notifications@github.com>:

> Not currently. I could probably add something.
>
> Could you try to run rdm with -M
>
> This might help. It should vastly cut down on the number of directories we
> watch.
>
> Anders
>

**Comment by Andersbakken** [comment]
Hi Henry

No worries. There's not much in the way of documentation that could have
led you to find this out on your own. We normally watch directories for two
reasons.

1) To update the file cache (Used by rtags-find-file rc -P)
2) To monitor files for changes and reindex appropriately.

-M  only matters for the former. If you pass -M we will walk the directory
structure to build the file cache in the background each time rc is called
if the cache is older than 1 minute. This still works reasonably well and
is actually default behavior on Mac.

Anders

**Comment by henry-y** [comment]
Thanks a lot, so -W solves it.

**Comment by Andersbakken** [comment]
Glad to hear that.

Anders

**Comment by ydm** [comment]
Actually you can increase the maximum number of watched files. Check this thread: http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc
