### ISSUE TITLE
why's that rc refers a nonexistent file?

### ISSUE THREAD

**Issue by henry-y** [Andersbakken/rtags#307]
Error log from rdm:

/home/henry/tools/rtags/rc --current-file=/home/henry/mc_tool/trunk/src/lib/libconv/libconv.c -f /home/henry/mc_tool/trunk/src/lib/libconv/libconv.c:29:28
Failed to open /home/henry/.rtags-file/_home_henry_mc<underscore>tool_trunk_/2/symbols /home/henry/mc_tool/trunk/src/lib/libconv/libconv.c x.sh
0 hits, 1 misses ( 0%) 0 removals

I don't know where does the "x.sh" come from. And ...
After list files at /home/henry/.rtags-file/.rtags-file/_home_henry_mc<underscore>tool_trunk_/ , I've found no directory named "2", but there're many directories there:

20/   2036/ 2073/ 2109/ 2146/ 2183/ 2220/ 2257/ 2294/ 2331/ 2368/ 2405/ 2442/ 2479/ 2512/ 2546/ 2580/ 2614/ 2648/ 2683/ 2717/ 2750/ 2785/ 2819/ 2852/ 2886/ 292/  2953/ 2987/
2000/ 2037/ 2074/ 2110/ 2147/ 2184/ 2221/ 2258/ 2295/ 2332/ 2369/ 2406/ 2443/ 248/  2513/ 2547/ 2581/ 2615/ 2649/ 2684/ 2718/ 2751/ 2786/ 282/  2853/ 2887/ 2920/ 2954/ 2988/
2001/ 2038/ 2075/ 2111/ 2148/ 2185/ 2222/ 2259/ 2296/ 2333/ 2370/ 2407/ 2444/ 2480/ 2514/ 2548/ 2582/ 2616/ 265/  2685/ 2719/ 2752/ 2787/ 2820/ 2854/ 2888/ 2921/ 2955/ 2989/
2002/ 2039/ 2076/ 2112/ 2149/ 2186/ 2223/ 2260/ 2297/ 2334/ 2371/ 2408/ 2445/ 2481/ 2515/ 2549/ 2583/ 2617/ 2650/ 2686/ 272/  2753/ 2788/ 2821/ 2855/ 2889/ 2922/ 2956/ 299/
2003/ 2040/ 2077/ 2113/ 2150/ 2187/ 2224/ 2261/ 2298/ 2335/ 2372/ 2409/ 2446/ 2482/ 2516/ 255/  2584/ 2618/ 2653/ 2687/ 2720/ 2754/ 2789/ 2822/ 2856/ 289/  2923/ 2957/ 2990/
2004/ 2041/ 2078/ 2114/ 2151/ 2188/ 2225/ 2262/ 2299/ 2336/ 2373/ 2410/ 2447/ 2483/ 2517/ 2550/ 2585/ 2619/ 2654/ 2688/ 2721/ 2755/ 279/  2823/ 2857/ 2890/ 2924/ 2958/ 2991/
2005/ 2042/ 2079/ 2115/ 2152/ 2189/ 2226/ 2263/ 2300/ 2337/ 2374/ 2411/ 2448/ 2484/ 2518/ 2551/ 2586/ 262/  2655/ 2689/ 2722/ 2756/ 2790/ 2824/ 2858/ 2891/ 2925/ 2959/ 2992/
2006/ 2043/ 2080/ 2116/ 2153/ 2190/ 2227/ 2264/ 2301/ 2338/ 2375/ 2412/ 2449/ 2485/ 2519/ 2552/ 2587/ 2620/ 2656/ 269/  2723/ 2757/ 2791/ 2825/ 2859/ 2892/ 2926/ 296/  2993/
2007/ 2044/ 2081/ 2117/ 2154/ 2191/ 2228/ 2265/ 2302/ 2339/ 2376/ 2413/ 2450/ 2486/ 252/  2553/ 2588/ 2621/ 2657/ 2690/ 2724/ 2758/ 2792/ 2826/ 286/  2893/ 2927/ 2960/ 2994/
2008/ 2045/ 2082/ 2118/ 2155/ 2192/ 2229/ 2266/ 2303/ 2340/ 2377/ 2414/ 2451/ 2487/ 2520/ 2554/ 2589/ 2622/ 2658/ 2691/ 2725/ 2759/ 2793/ 2827/ 2860/ 2894/ 2928/ 2961/ 2995/
2009/ 2046/ 2083/ 2119/ 2156/ 2193/ 2230/ 2267/ 2304/ 2341/ 2378/ 2415/ 2452/ 2488/ 2521/ 2555/ 259/  2623/ 2659/ 2692/ 2726/ 276/  2794/ 2828/ 2861/ 2895/ 2929/ 2962/ 2996/
2010/ 2047/ 2084/ 2120/ 2157/ 2194/ 2231/ 2268/ 2305/ 2342/ 2379/ 2416/ 2453/ 2489/ 2522/ 2556/ 2590/ 2624/ 266/  2693/ 2727/ 2760/ 2795/ 2829/ 2862/ 2896/ 293/  2963/ 2997/
2011/ 2048/ 2085/ 2121/ 2158/ 2195/ 2232/ 2269/ 2306/ 2343/ 2380/ 2417/ 2454/ 249/  2523/ 2557/ 2591/ 2625/ 2660/ 2694/ 2728/ 2761/ 2796/ 283/  2863/ 2897/ 2930/ 2964/ 2998/
2012/ 2049/ 2086/ 2122/ 2159/ 2196/ 2233/ 2270/ 2307/ 2344/ 2381/ 2418/ 2455/ 2490/ 2524/ 2558/ 2592/ 2626/ 2661/ 2695/ 2729/ 2762/ 2797/ 2830/ 2864/ 2898/ 2931/ 2965/ 2999/
2013/ 2050/ 2087/ 2123/ 2160/ 2197/ 2234/ 2271/ 2308/ 2345/ 2382/ 2419/ 2456/ 2491/ 2525/ 2559/ 2593/ 2627/ 2662/ 2696/ 273/  2763/ 2798/ 2831/ 2865/ 2899/ 2932/ 2966/ 
2014/ 2051/ 2088/ 2124/ 2161/ 2198/ 2235/ 2272/ 2309/ 2346/ 2383/ 2420/ 2457/ 2492/ 2526/ 256/  2594/ 2628/ 2663/ 2697/ 2730/ 2764/ 2799/ 2832/ 2866/ 290/  2933/ 2967/ 
2015/ 2052/ 2089/ 2125/ 2162/ 2199/ 2236/ 2273/ 2310/ 2347/ 2384/ 2421/ 2458/ 2493/ 2527/ 2560/ 2595/ 2629/ 2664/ 2698/ 2731/ 2765/ 280/  2833/ 2867/ 2900/ 2934/ 2968/ 
2016/ 2053/ 2090/ 2126/ 2163/ 2200/ 2237/ 2274/ 2311/ 2348/ 2385/ 2422/ 2459/ 2494/ 2528/ 2561/ 2596/ 263/  2665/ 2699/ 2732/ 2766/ 2800/ 2834/ 2868/ 2901/ 2935/ 2969/ 
2017/ 2054/ 2091/ 2127/ 2164/ 2201/ 2238/ 2275/ 2312/ 2349/ 2386/ 2423/ 2460/ 2495/ 2529/ 2562/ 2597/ 2630/ 2666/ 270/  2733/ 2767/ 2801/ 2835/ 2869/ 2902/ 2936/ 297/  
2018/ 2055/ 2092/ 2128/ 2165/ 2202/ 2239/ 2276/ 2313/ 2350/ 2387/ 2424/ 2461/ 2496/ 253/  2563/ 2598/ 2631/ 2667/ 2700/ 2734/ 2768/ 2802/ 2836/ 287/  2903/ 2937/ 2970/ 
2019/ 2056/ 2093/ 2129/ 2166/ 2203/ 2240/ 2277/ 2314/ 2351/ 2388/ 2425/ 2462/ 2497/ 2530/ 2564/ 2599/ 2632/ 2668/ 2701/ 2735/ 2769/ 2803/ 2837/ 2870/ 2904/ 2938/ 2971/ 
2020/ 2057/ 2094/ 2130/ 2167/ 2204/ 2241/ 2278/ 2315/ 2352/ 2389/ 2426/ 2463/ 2498/ 2531/ 2565/ 260/  2633/ 2669/ 2702/ 2736/ 277/  2804/ 2838/ 2871/ 2905/ 2939/ 2972/ 
2021/ 2058/ 2095/ 2131/ 2168/ 2205/ 2242/ 2279/ 2316/ 2353/ 2390/ 2427/ 2464/ 2499/ 2532/ 2566/ 2600/ 2634/ 267/  2703/ 2737/ 2770/ 2805/ 2839/ 2872/ 2906/ 294/  2973/ 
2022/ 2059/ 2096/ 2132/ 2169/ 2206/ 2243/ 2280/ 2317/ 2354/ 2391/ 2428/ 2465/ 250/  2533/ 2567/ 2601/ 2635/ 2670/ 2704/ 2738/ 2771/ 2806/ 284/  2873/ 2907/ 2940/ 2974/ 
2023/ 2060/ 2097/ 2133/ 2170/ 2207/ 2244/ 2281/ 2318/ 2355/ 2392/ 2429/ 2466/ 2500/ 2534/ 2568/ 2602/ 2636/ 2671/ 2705/ 2739/ 2772/ 2807/ 2840/ 2874/ 2908/ 2941/ 2975/ 
2024/ 2061/ 2098/ 2134/ 2171/ 2208/ 2245/ 2282/ 2319/ 2356/ 2393/ 2430/ 2467/ 2501/ 2535/ 2569/ 2603/ 2637/ 2672/ 2706/ 274/  2773/ 2808/ 2841/ 2875/ 2909/ 2942/ 2976/ 
2025/ 2062/ 2099/ 2135/ 2172/ 2209/ 2246/ 2283/ 2320/ 2357/ 2394/ 2431/ 2468/ 2502/ 2536/ 257/  2604/ 2638/ 2673/ 2707/ 2740/ 2775/ 2809/ 2842/ 2876/ 291/  2943/ 2977/ 
2026/ 2063/ 21/   2136/ 2173/ 2210/ 2247/ 2284/ 2321/ 2358/ 2395/ 2432/ 2469/ 2503/ 2537/ 2571/ 2605/ 2639/ 2674/ 2708/ 2741/ 2776/ 281/  2843/ 2877/ 2910/ 2944/ 2978/ 
2027/ 2064/ 2100/ 2137/ 2174/ 2211/ 2248/ 2285/ 2322/ 2359/ 2396/ 2433/ 2470/ 2504/ 2538/ 2572/ 2606/ 264/  2675/ 2709/ 2742/ 2777/ 2810/ 2844/ 2878/ 2911/ 2945/ 2979/ 
2028/ 2065/ 2101/ 2138/ 2175/ 2212/ 2249/ 2286/ 2323/ 2360/ 2397/ 2434/ 2471/ 2505/ 2539/ 2573/ 2607/ 2640/ 2676/ 271/  2743/ 2778/ 2811/ 2845/ 2879/ 2912/ 2946/ 298/  
2029/ 2066/ 2102/ 2139/ 2176/ 2213/ 2250/ 2287/ 2324/ 2361/ 2398/ 2435/ 2472/ 2506/ 254/  2574/ 2608/ 2641/ 2677/ 2710/ 2744/ 2779/ 2812/ 2846/ 288/  2913/ 2947/ 2980/ 
2030/ 2067/ 2103/ 2140/ 2177/ 2214/ 2251/ 2288/ 2325/ 2362/ 2399/ 2436/ 2473/ 2507/ 2540/ 2575/ 2609/ 2642/ 2678/ 2711/ 2745/ 278/  2813/ 2847/ 2880/ 2914/ 2948/ 2981/ 
2031/ 2068/ 2104/ 2141/ 2178/ 2215/ 2252/ 2289/ 2326/ 2363/ 2400/ 2437/ 2474/ 2508/ 2541/ 2576/ 261/  2643/ 2679/ 2712/ 2746/ 2780/ 2814/ 2848/ 2881/ 2915/ 2949/ 2982/ 
2032/ 2069/ 2105/ 2142/ 2179/ 2216/ 2253/ 2290/ 2327/ 2364/ 2401/ 2438/ 2475/ 2509/ 2542/ 2577/ 2610/ 2644/ 268/  2713/ 2747/ 2781/ 2815/ 2849/ 2882/ 2916/ 295/  2983/ 
2033/ 2070/ 2106/ 2143/ 2180/ 2217/ 2254/ 2291/ 2328/ 2365/ 2402/ 2439/ 2476/ 251/  2543/ 2578/ 2611/ 2645/ 2680/ 2714/ 2748/ 2782/ 2816/ 285/  2883/ 2917/ 2950/ 2984/ 
2034/ 2071/ 2107/ 2144/ 2181/ 2218/ 2255/ 2292/ 2329/ 2366/ 2403/ 2440/ 2477/ 2510/ 2544/ 2579/ 2612/ 2646/ 2681/ 2715/ 2749/ 2783/ 2817/ 2850/ 2884/ 2918/ 2951/ 2985/ 
2035/ 2072/ 2108/ 2145/ 2182/ 2219/ 2256/ 2293/ 2330/ 2367/ 2404/ 2441/ 2478/ 2511/ 2545/ 258/  2613/ 2647/ 2682/ 2716/ 275/  2784/ 2818/ 2851/ 2885/ 2919/ 2952/ 2986/ 

Maybe I have too large codebase, the space consumed by these tag files is over 400MB:

$ du -sh ~/.rtags-file/_home_henry_mc\<underscore\>tool_trunk_/
426M    /home/henry/.rtags-file/_home_henry_mc<underscore>tool_trunk_/

**Comment by henry-y** [comment]
**Update**

now I've seen another log that it failed to open the /4210/symbols file, but it actually exists, and I can open the symbols file by Emacs,and it looks like a binary file.

**Comment by Andersbakken** [comment]
It's conceivable that this file was just being generated at the time rdm was trying to open it. Are you able to reliably reproduce this?

As for the first case. I don't entirely understand what would cause the x.sh text to be written but I added some additional logging just now.

**Comment by henry-y** [comment]
Hi, I've updated rtags to test. Please check this error log:

/home/henry/tools/rtags/rc --current-file=/dev/henry/mc/trunk/src/bin/lib_cs/src/main.c --wildcard-symbol-names -f /dev/henry/mc/trunk/src/bin/lib_cs/src/main.c:76:15
Failed to open /home/henry/.rtags/_dev_henry_mc_trunk_/3837/symbols /dev/henry/mc/trunk/src/bin/lib_cs/src/main.c 82
Letting /dev/henry/mc/trunk/src/bin/lib_cs/src/main.c go even with a headerheader error from /opt/mips/sysroot/usr/include/bits/types.h
0 hits, 1 misses ( 0%) 0 removals
[100%] 1/1 16:09:46 /dev/henry/mc/trunk/src/bin/lib_cs/src/main.c in 572ms. (291 syms, 148 symNames, 38 includes, 1 of 210 files, symbols: 1006 of 21298, 209 queried) (290/48/234ms) (dirty). (header-error)
Jobs took 0.85s. We're using 85mb of memory. 
/dev/henry/mc/trunk/src/bin/lib_cs/src/main.c
/opt/mips/sysroot/usr/include/stdlib.h:33:10: fatal error: 'stddef.h' file not found

**Comment by Andersbakken** [comment]
Odd. I don't really think it should be possible for it to fail there. I've
added some extra logging for this. Can you reproduce it again?

Also, can you test that flock works at all on your system?

Try this example:

#include <string.h>
#include <fcntl.h>
#include <stdio.h>
#include <errno.h>
#include <unistd.h>

int main(int argc, char **argv)
{
    int fd = open(argv[0], O_RDONLY);
    if (!fd) {
        printf("Failed to open %s for reading\n", argv[0]);
        return 1;
    }
    int ret = flock(fd, LOCK_EX);
    if (ret) {
        printf("Failed to flock %d %s\n", errno, strerror(errno));
        return 1;
    }
    flock(fd, LOCK_UN);
    close(fd);
    return 0;
}

regards

Anders

**Comment by henry-y** [comment]
Hi, thanks for the analysis.
Firstly, I've run the test for flock, and it fails with error "9 Bad file descriptor".
I've run the test on two machines.
On machine A, I run as root, and flock works, besides, there's no such issue in this case.
On machine B, I run as unprivileged user, and flock fails with error 9, and this issue exists.

I'll update rtags to reproduce the issue later because it takes time.

**Comment by henry-y** [comment]
Well, it seems flock does not lock files over NFS. and On machine A, I'm on a NFS share folder, On machine B, I'm on local disk, so I thinks it has nothing to do with root account. After looking into manual of flock, for NFS, you can use fcntl, so could you please modify it to use fcntl?

**Comment by Andersbakken** [comment]
I did. Can you check if it works now?

Anders

**Comment by henry-y** [comment]
Thanks a lot, it works now.

**Comment by henry-y** [comment]
I haven't updated rtags for quite a while.
It happens after updating, could you please check whether some commits broke this?

**Comment by Andersbakken** [comment]
Do you have any steps on how to reproduce this? Note that after an update I
might have changed the database version and that would lead to rdm tossing
out its database.

**Comment by Andersbakken** [comment]
I believe this issue might be fixed now? If this is incorrect please reopen.
