### ISSUE TITLE
Integrating with ido-ubiquitous

### ISSUE THREAD

**Issue by dccmmccd1** [Andersbakken/rtags#308]
First of all I have to say that rtags is fantastic!
I've got almost everything I needed to work, the only thing I'm missing is for IDO to work with rtags-find-file. It already seems to works perfectly with rtags-imenu.
Do you think this is something that can be added to rtags?

**Comment by Andersbakken** [comment]
Hi

The problem is performance. rtags-find-file potentially works on very large
datasets and I am not sure it would be useful. Maybe we could set some
threshold for number of files where it would fall back to using ido (or
calling standard completing-read). How big is your project?

E.g. What is the output of:

find /path/to/project/root | wc -l

**Comment by dccmmccd1** [comment]
Instead of using find (gives too many results including stuff rtags doesn't care abount) I used rtags-find and just pressed TAB so it gives me all the completion results. I got close to 35K results. One way of handling this is first running the completion in the background so that it doesn't slow the user's typing. Also start a new async process every time the user enters a new character that narrows down the possibilities (also this should kill any older async process as well). This way, as far as the user is concerned it's seamless. He'll get the results as fast as his machine is able to produce them and it won't slow him down if he just wants to type the whole file name explicitly.
I really don't have a clue how hard this is to implement in lisp though.

**Comment by Andersbakken** [comment]
Hi

I would absolutely love to have ido completion for find-files as well but I
simply don't think this is possible to achieve with ido. Emacs' general
completion framework is flexible enough that we can do all the heavy
lifting in c++ but I don't think ido lets us do this.

I would love to be proven wrong though.

Anders

**Comment by pradhanpk** [comment]
@Andersbakken FWIW I use `helm-find-file` on a codebase around the size being discussed by OP. The completion isn't as fast as you would like it, but, usually, stays out of my way. Also, [projectile](https://github.com/bbatsov/projectile) defaults to `ido` and have heard it works well with 50K-file projects. (Actually, I have heard that about `helm-projectile`, but perhaps it's safe to extrapolate :))

I would like to report a slightly tangential issue related to the use of `completing-read` - `rtags-imenu` uses `completing-read` without specifying a non-`nil` for the require match feature. I don't know how `ido-completing-read` deals with it, but with `helm`, this gives `rtags-imenu` the behaviour very similar to the one reported [here](https://github.com/emacs-helm/helm/issues/376) about an unrelated package. Changing that would be helpful. Please let me know if you would rather have me open a new issue report, or if you need more information. Thanks!

**Comment by Andersbakken** [comment]
I'll take a look at making use ido. Maybe it works fine.

I fixed the require-match thing. Thanks for the reports.

Anders

**Comment by Andersbakken** [comment]
Hi

I added support for this. To enable do this:

(setq rtags-use-filename-completion nil)

If rtags-use-filename-completion is nil we'll generate all results up front and use completing-read which allows helm/ido to take over.
