### ISSUE TITLE
Assertion in FindFileJob::execute()

### ISSUE THREAD

**Issue by azuk** [Andersbakken/rtags#309]
With rtags built from tag v2.0 and bleeding edge clang as of this writing, command `rc --path rtags` crashes rdm with the following message:
> rdm: /home/hannuko/projects/3rdparty/rtags/src/FindFileJob.cpp:42: virtual int FindFileJob::execute(): Assertion `srcRoot.endsWith('/')' failed.
> [1]  + 31115 abort (core dumped)  /usr/local/rtags/bin/rdm -v --silent --log-file ~/.rtags/.log

**Comment by Andersbakken** [comment]
I can't seem to reproduce this but I added some code to try to make sure that all project roots end with / (which is what the assert is all about). Are you able to reliably reproduce this?

**Comment by azuk** [comment]
I can reproduce the problem with v2.0. I can no longer reproduce it with the latest master branch tip. I guess this can be closed (github seems to give me the possibility to do that, so I'll try -- I hope I'm not breaking any protocol here...)

The way to reproduce it was to start from scratch (empty ~/.rtags) directory, index the following file named rtagstest.cpp (and only that) and then run `rc --path rtags`.

```
#include <stdio.h>

/** kala */
struct foo {
    double kala;
};

int main(int argc, char** argv)
{
    printf("%u\n", alignof(foo));
    printf("%u\n", alignof(foo));
    return 0;
}

/* Local Variables: */
/* compile-command: "RTAGS_PROJECT=/home/hannuko/projects/hacks g++ -march=i686 -m32 -std=c++11 -Wall -o rtagstest rtagstest.cpp" */
/* End: */
```
