### ISSUE TITLE
Report problems in communication with rdm to Emacs users

### ISSUE THREAD

**Issue by azuk** [Andersbakken/rtags#311]
With rtags built from tag v2.0, if I try to use `rtags-find-symbol-at-point` when `rdm` is not running, the result is *RTags: No results*, which is the same I get if `rdm` *is* running but there simply are no results.

In such a case `rc` program reports *Can't seem to connect to server* and it looks like `rtags-call-rc` should be able to detect that, but it doesn't, because `:output` keyword argument is `(list t nil)` (=discard stderr) by default and most callers don't override that default.

**Comment by Andersbakken** [comment]
I moved that message to stdout so it should work better now. Thanks for the report.
