### ISSUE TITLE
rdm not starting when autodiagnostics is true?

### ISSUE THREAD

**Issue by LefterisJP** [Andersbakken/rtags#312]
With the latest rtags I get:
```
error in process filter: rtags-parse-diagnostics: Symbol's value as variable is void: Can
error in process filter: Symbol's value as variable is void: Can
```
when being inside any C/C++ buffer. I suspect that this is due to rdm not having started even though I have a diagnostics autostart in my init.el

This is the initialization file I use for rtags:
```emacs-lisp
(require 'rtags)


(rtags-enable-standard-keybindings c-mode-base-map)
(setq rtags-autostart-diagnostics t)

;; enable completions with company-mode
(require 'company-rtags)
(setq rtags-completions-enabled t)
(eval-after-load 'company
  '(add-to-list 'company-backends 'company-rtags))

(provide 'init-rtags)
```

This is the backtrace I get when I toggle `debugg-on-error`

```
Debugger entered--Lisp error: (void-variable Can)
  eval(Can)
  rtags-parse-diagnostics()
  rtags-diagnostics-process-filter(#<process RTags Diagnostics> "Can't seem to connect to server\n")
```

This leads me to believe that for some reason `rtags-autostart-diagnostics` no longer starts `rdm` and as such we don't communicate with the process at all.

As an added bonus here would be awesome to also have something to catch the "Can't connect to server message" and display it to the user instead of having a lisp exception.

**Comment by LefterisJP** [comment]
Thanks for the quick response. Now the error message when I start emacs is more concise:
```
RTags: rdm doesn't seem to be running
error in process filter: rtags-diagnostics-process-filter: Wrong type argument: listp, "RTags: rdm doesn't seem to be running"
error in process filter: Wrong type argument: listp, "RTags: rdm doesn't seem to be running"
```

Still though, shouldn't rdm start automatically when I visit a C/C++ file and I have `rtags-autostart-diagnostics` set to true?

**Comment by Andersbakken** [comment]
I think this should work. It should maybe start rdm automatically but it currently doesn't. What you could do is put this in your init.el:

(rtags-start-process-maybe)
