### ISSUE TITLE
Document Emacs version requirement (and possibly lower it)

### ISSUE THREAD

**Issue by azuk** [Andersbakken/rtags#313]
Currently rtags.el requires Emacs version that is not available in, for example, the latest stable Ubuntu distribution (14.04), so it would be good to mention the requirement in README's Prerequisites.

I'm not sure if `set-transient-map` is the only used function not available in 24.3 but if it is, one could consider supporting also the old name `set-temporary-overlay-map`.

**Comment by Andersbakken** [comment]
This should actually be fixed in bf966f67a71188df9ca3f9956c4acc6c8b06b5bf.
Can you check that it works. I agree that we should document minimum
version but I frankly have no idea which one it is. I suppose I should go
installing a couple of older ones and bisect my way.

Anders

**Comment by azuk** [comment]
bf966f6 indeed solves the `set-transient-map` problem.

I think it would be sufficient to document the oldest version that you intentionally support, instead of possible even older version that happens to work with the current rtags.el. I was mainly concerned that if the Emacs version requirement practically means that you either need to have an unstable version of a popular Linux distribution or build Emacs yourself, then it would be good to mention that.

**Comment by Andersbakken** [comment]
That seems sensible. I'll add something. Thanks.
