### ISSUE TITLE
Undefined symbols while linking under cygwin

### ISSUE THREAD

**Issue by c-nixon** [Andersbakken/rtags#315]
Hi,

I get the following output while linking rdm.exe under cygwin64:

    rct/librct.a(cJSON.c.o):cJSON.c:(.text+0x13b): undefined reference to `__stack_chk_fail'
    rct/librct.a(cJSON.c.o):cJSON.c:(.text+0x13b): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__stack_chk_fail'
    ....
    rct/librct.a(cJSON.c.o):cJSON.c:(.text+0x1e38): additional relocation overflows omitted from the output
    rct/librct.a(cJSON.c.o):cJSON.c:(.rdata$.refptr.__stack_chk_guard[.refptr.__stack_chk_guard]+0x0): undefined reference to `__stack_chk_guard'
    collect2: error: ld returned 1 exit status

It seems to be to do with -fstack-protector-all, adding -lssp to the RTAGS_CLANG_LIBRARIES variable allows linking to go ahead and everything seems to work, but presumably there's a nicer way to fix this.

**Comment by Andersbakken** [comment]
I just removed the flag on Cygwin. It's never really found us a bug anyway.

**Comment by Andersbakken** [comment]
Thanks for the report.
