### ISSUE TITLE
problem with temporary source file

### ISSUE THREAD

**Issue by henry-y** [Andersbakken/rtags#316]
Hi,

The scenario is like this:
While building a library, make will firstly generate a random .c file, then gcc will compile with this .c file, after compiling, make will remove this .c file.

So, now log output from rdm read this:
```
Error during validation: /dev/henry/mc/trunk/src/bin/lib_encrypt/target/gen/random.c (2) 73 /home/henry/.rtags/_dev_henry_mc_trunk_/3555/symnames
error: error reading '/dev/henry/mc/trunk/src/bin/lib_encrypt/target/gen/random.c'                                                                      
Failed to parse clang ................
```

And what bothers me is that rdm will not stop logging this and the log file will get increasingly huge.

Besides, I don't know if it will impact anything.

Please have a look, thanks.

**Comment by Andersbakken** [comment]
Hi Henry

I think I've fixed it now. Can you check?

Anders

**Comment by henry-y** [comment]
Hi

I've checked twice with your fix. Unfortunately, it doesn't work and the error log is the same.

**Comment by Andersbakken** [comment]
Hi Henry

It seems this exposed a bug in our filesystemwatcher on linux. Can you see
if it works better for you now?

Also, if it still doesn't work, are you able to provide some simple exact
steps to reproduce this? I was unable to reproduce the exact same thing
that you see even before my mix.

Anders

**Comment by henry-y** [comment]
Hi Anders

I've tried to pinpoint the problem, but it seems it's not so easy to extract the exact steps to reproduce it.

So the background information I can give you is that I have a big project containing many sub projects, and there's four sub projects' makefiles will generate this random.c file and remove it. And the steps I've tried are like the following:

1. Start rdm with command line:  rdm -L ~/rdm.log -M
2. Build the whole project using the rtags-wrapper provided
   * After compiling finished, I see a lot of 'Error during validation' logs continuously produced at rdm.log, and I can see it fails for one specific sub project.
3. Restart rdm and build only that sub project
   * But, no error logs are produced now.

Therefore, I can only reproduce the error logs when building the whole project, and there are so many makefiles that I don't know where to start. And you can see that after building, restarting rdm can be a workaround.

I think it takes time to know what's wrong exactly from my side but I'll keep you updated if I find anything.
Anyway, I've found a workaround for now. So it's up to you to close the issue.

**Comment by Andersbakken** [comment]
Hi Henry

I figured it out. It should work now. In short I didn't treat a clang parse
failure correctly and ended up in an endless loop.

Thanks for the report.

Anders

**Comment by henry-y** [comment]
Superb, thanks!
