### ISSUE TITLE
[Question/Feature?] Get function name at point

### ISSUE THREAD

**Issue by chep** [Andersbakken/rtags#317]
Hi,

Currently I initialize semantic for only one think: stickyfunc.

Semantic Sticky Function minor mode displays a header line that shows the
declaration line of the function or tag on the topmost line in the text area. I
modified it to use point instead of the topmost line.

This is very useful when you are in a big function (which should be smaller) you
don't need to remember where you are because it is written in the header line.

Initialize semantic is "long" and it parses a lot of buffers/files. It creates a
database and does a lot of things I don't know/use.

Is there a way to get the prototype of the function at point (or any location)
with rtags?

**Comment by Andersbakken** [comment]
Hi Cedric

I just added something that I hope will help.

    Fix issue #317
    Expose an elisp custom rtags-track-container that, when t means rtags
    will track the current "container" (function/class/struct/namespace) and
    store it in the variable rtags-cached-current-container. The interval
    can be controlled with rtags-container-timer-interval and changes can be
    tracked with the hook rtags-current-container-hook. This could be used
    to put it in the modeline or an overlay or something like that.

Does this work for you?

Anders

**Comment by chep** [comment]
Hi,

It looks awesome, I'll apply syntax coloration on the result and it will be perfect.
Thank you very much.

**Comment by Andersbakken** [comment]
Cool. Let me know if what you add might be worth rolling into rtags.el.

Anders

**Comment by LefterisJP** [comment]
+1 very nice idea :)

**Comment by chep** [comment]
Hi,

I wrote this, I don't think it can be integrated in rtags because this is only
how I use an rtags features. I post it here because it can give ideas to
someone. I couldn't find a better way to apply syntax highlighting than creating
a buffer with the same major mode as current edited file... it works... not as
efficient as I wanted. I'll try to find a better way.


(defun my-stickyfunc(arg)
  (let ((mode major-mode)
        header-line)
    (with-current-buffer (get-buffer-create "*my-stickyfunc*")
      (erase-buffer)
      (funcall mode)
      (insert rtags-cached-current-container)
      (font-lock-fontify-region (point-min) (point-max))
      (setq header-line (buffer-substring (point-min) (point-max))))
    (setq header-line-format header-line)))

(add-hook 'rtags-current-container-hook 'my-stickyfunc)

Now I can definitely ban semantic in my configuration.

**Comment by Andersbakken** [comment]
Oops. It passed the wrong value. It's passing the container name.
