### ISSUE TITLE
Some files continue to 

### ISSUE THREAD

**Issue by gvol** [Andersbakken/rtags#318]
Certain files continually fail to index.  I run rdm as

    nice -11 ./bin/rdm -j 1

and continue to get errors like the below.  I'm using 5ed252b8e89ebd624e8b9951da1d1901c30bdee2 (though it had the same problem a few revisions before that)

    /Users/iandrus/DiscoverStuff/axle/rezzer/rez_merge_stager.cpp
    Caught signal 11

    1/27 sigHandler(int)
    2/27 _sigtramp
    3/27 std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__init(char const*, unsigned long)
    4/27 clang::comments::CommentVisitorBase<clang::comments::make_const_ptr, (anonymous namespace)::CommentASTToXMLConverter, void>::visit(clang::comments::Comment const*)
    5/27 (anonymous namespace)::CommentASTToXMLConverter::visitFullComment(clang::comments::FullComment const*)
    6/27 clang::index::CommentToXMLConverter::convertCommentToXML(clang::comments::FullComment const*, llvm::SmallVectorImpl<char>&, clang::ASTContext const&)
    7/27 clang_FullComment_getAsXML
    8/27 ClangIndexer::handleCursor(CXCursor const&, CXCursorKind, Location const&, Symbol**)
    9/27 ClangIndexer::indexVisitor(CXCursor, CXCursor, void*)
    10/27 clang::cxcursor::CursorVisitor::Visit(CXCursor, bool)
    11/27 clang::cxcursor::CursorVisitor::VisitDeclContext(clang::DeclContext*)
    12/27 clang::cxcursor::CursorVisitor::VisitCXXRecordDecl(clang::CXXRecordDecl*)
    13/27 clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::cxcursor::CursorVisitor, bool>::Visit(clang::Decl*)
    14/27 clang::cxcursor::CursorVisitor::VisitChildren(CXCursor)
    15/27 clang::cxcursor::CursorVisitor::Visit(CXCursor, bool)
    16/27 clang::cxcursor::CursorVisitor::VisitDeclContext(clang::DeclContext*)
    17/27 clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::cxcursor::CursorVisitor, bool>::Visit(clang::Decl*)
    18/27 clang::cxcursor::CursorVisitor::VisitChildren(CXCursor)
    19/27 clang::cxcursor::CursorVisitor::Visit(CXCursor, bool)
    20/27 clang::cxcursor::CursorVisitor::VisitDeclContext(clang::DeclContext*)
    21/27 clang::cxcursor::CursorVisitor::VisitChildren(CXCursor)
    22/27 clang_visitChildren
    23/27 ClangIndexer::visit()
    24/27 ClangIndexer::exec(String const&)
    25/27 main
    26/27 start
    27/27 0x0

Sometimes, I also get an error like the one below directly above the corresponding large error

    Error during validation: /Users/iandrus/DiscoverStuff/axle/vlib/recurrence.cpp No such file or directory (2) 73 /Users/iandrus/.rtags/_Users_iandrus_DiscoverStuff_axle_/2008/symnames

**Comment by gvol** [comment]
Let me know what I can do to help.

**Comment by Andersbakken** [comment]
Hi Ivan

I've fixed the fact that we even try to validate when the file fails to parse (the data files will obviously not be there then and there are other mechanisms in place for attempting a reparse).
I think the crash very likely is a clang bug but I added an rdm option to disable comments.

E.g.

echo "--no-comments" >> ~/.rdmrc

Should fix it.

Let me know if this helps.

**Comment by gvol** [comment]
Thanks!  This has fixed things for me.

**Comment by Andersbakken** [comment]
Glad to hear. Thanks for the report.

Anders
