### ISSUE TITLE
Class Hierarchy 

### ISSUE THREAD

**Issue by dccmmccd1** [Andersbakken/rtags#319]
I realize this might be a more advanced feature, but could be useful. They have this feature in eclipse (though I don't know much about it since, obviously, I use emacs). From what I understand you click on a class and it gives you all the parent classes and/or inheriting classes. I'm not even sure if clang supports it, but a possible way to display this would be something like this:
```
GetSubclasses output:
---->   YourClass
          -InheritingClass0    
          -InheritingClass1
            - InheritingClass1.1
            - InheritingClass1.2
          -InheritingClass2
            - InheritingClass2.1
          -InheritingClass3

GetSuperclasses output (your class inherits from 4 super classes):
---->   YourClass
          -SuperClass0
            - SuperClass1.1
          -SuperClass1
          -SuperClass2
            - SuperClass2.1
            - SuperClass2.2
              - SuperClass2.2.1
          -SuperClass3
```
Then maybe you would be able to press on a class and it would jump to it's declaration.
Do you know how difficult this would be?

**Comment by Andersbakken** [comment]
We don't currently track this information but I think we definitely can.
I'll look into adding something.

Anders

**Comment by Andersbakken** [comment]
I added something so rtags knows about base classes. There's no elisp to
visualize it yet but I'll look into adding something.

**Comment by Andersbakken** [comment]
It should all be working now. Try it with M-x rtags-print-class-hierarchy
