### ISSUE TITLE
rdm man page not up to date

### ISSUE THREAD

**Issue by cslux** [Andersbakken/rtags#320]
rdm option `--no-current-project` has changed to `--no-startup-project`.

I don't know if there are other options wrong too, but I came just a long this one while writing `.rdmrc`.

**Comment by Andersbakken** [comment]
Hi Christian

It seems they're both out of date. I will take a look.

Anders

**Comment by Andersbakken** [comment]
I've ran some emacs macros over them so they should reflect reality a
little better now. Thanks for the report.

**Comment by cslux** [comment]
Thank you for providing such a great software.

**Comment by Andersbakken** [comment]
Our pleasure.

Anders

**Comment by cslux** [comment]
On Wednesday, March 25, 2015 10:19:35 AM Anders Bakken wrote:


Our pleasure.

Anders

On Wed, Mar 25, 2015 at 4:43 AM, Christian Schwarzgruber <notifications@github.com> wrote:

> Thank you for providing such a great software.> On Mar 25, 2015 9:22 AM, "Anders Bakken" 
<notifications@github.com> wrote:>> > I've ran some emacs macros over them so they 
should reflect reality a> > little better now. Thanks for the report.> >> > On Mon, Mar 23, 
2015 at 10:58 AM, Anders Bakken <agbakken@gmail.com>> > wrote:> >> > > Hi Christian> 
> >> > > It seems they're both out of date. I will take a look.> > >> > > Anders> > >> > > 
On Sat, Mar 21, 2015 at 5:46 PM, Christian <notifications@github.com>> > > wrote:> > >> > 
>> rdm option --no-current-project has changed to --no-startup-project.> > >>> > >> I don't 
know if there are other options wrong too, but I came just a> > long> > >> this one while 
configuring .rdmrc> > >>> > >> —> > >> Reply to this email directly or view it on GitHub> > 
>> <https://github.com/Andersbakken/rtags/issues/320>.> > >>> > >> > >> >> > —> > 
Reply to this email directly or view it on GitHub> > 
<https://github.com/Andersbakken/rtags/issues/320#issuecomment-85915109> >.>> >>> —
> Reply to this email directly or view it on GitHub> 
<https://github.com/Andersbakken/rtags/issues/320#issuecomment-85993498>.>


—Reply to this email directly or view it on GitHub[1].[2]




while I was considering to write a small program, which auto generates a man page out of the 
`--help` option. I came across this tool from GNU /[help2man]
(https://www.gnu.org/software/help2man/)/[3] which does a really good job. 
I tried it with `rdm` and the result is almost the same. 

I just wanted to let you know about this tool in case you did not know it. ;-)

Regards,
	Christian 




--------
[1] https://github.com/Andersbakken/rtags/issues/320#issuecomment-86129556
[2] https://github.com/notifications/beacon/ABoguUQN-xt2GbyrRSMfrdfJl_z0SNORks5n4uWngaJpZM4Dykqq.gif
[3] https://www.gnu.org/software/help2man/

**Comment by Andersbakken** [comment]
Hi Christian

I was not aware of this but it seems like exactly what we need. I
regenerated the pages with it. I manually added the description section but
I could probably use -i for that. Thanks for the tip.

Anders
