### ISSUE TITLE
Integrate rtags with flycheck instead of flymake

### ISSUE THREAD

**Issue by ddovod** [Andersbakken/rtags#324]
http://www.flycheck.org/

Flycheck is more fresh and maintained tool than flymake. It will be great to have rtags as a flycheck backend

**Comment by Andersbakken** [comment]
We're actually doing our own overlays currently (e.g. no flymake
integration) but flycheck integration sounds like a good idea. Do you have
any experience with writing backends for flycheck?

Anders

**Comment by ddovod** [comment]
@Andersbakken 
Unfortunately I'm not experienced in elisp, so i do not have any experience in it

**Comment by Hylen** [comment]
I'm willing to do this, when I get time for it. A flycheck integration with RTags could be really neat. I have no experience with flycheck other than using it, so it might take me a while though.

**Comment by Andersbakken** [comment]
Sure, give it a go. I haven't looked into it but it's probably not that
hard.

Anders

**Comment by cocreature** [comment]
FTR, I have a very crappy implementation. I probably won’t clean it up and finish it anytime soon but if anybody else wants to do so go for it!
```
(use-package flycheck
    :config
    (eval '(defun flycheck-rtags-start (checker callback)
             (let ((buffer (current-buffer))
                   (mychecker checker)
                   (diagnostics-buffer (get-buffer-create "*rtags-diagnostics*")))
               (setq lexical-binding t)
               (message (format "%s" checker))
               (setq rtags-diagnostics-process (start-file-process "RTags Diagnostics flycheck" diagnostics-buffer "rc" "-m" "--elisp"))
               (set-process-filter
                rtags-diagnostics-process
                (lambda (process output)
                  (message (format "%s" (type-of output)))
                  (let ((parsed-output (cdadr (eval (read output)))))
                    (message (format "%s" parsed-output))
                    (let ((errors (-map (lambda (e) (flycheck-rtags-parse-error checker buffer e)) parsed-output)))
                      (funcall callback 'finished (delq nil errors))))))
               (set-process-query-on-exit-flag rtags-diagnostics-process nil))) t)

    (defun flycheck-rtags-parse-error (checker buffer input)
      (let ((line (cadr input))
            (column (caddr input))
            (level (car (cddddr input)))
            (message (cadr (cddddr input))))
        (when level
          (flycheck-error-new-at line column level message
                                 :checker checker
                                 :buffer buffer
                                 :filename (buffer-file-name buffer)))))
    (flycheck-define-generic-checker 'flycheck-rtags
      "flycheck rtags"
      :start 'flycheck-rtags-start
      :modes '(c++-mode c-mode)))
```
Ignore the `eval` and `use-package` stuff, I needed lexical bindings for this and that was the easiest way to get this. I just copied it from my config.

**Comment by cslux** [comment]
Initial implementation has been added, however, it is far from perfect yet. https://github.com/Andersbakken/rtags/commit/62e0391bc8d91820503de3575f9811f33e1848b1

Closing this issue now 

regards,
Christian
