### ISSUE TITLE
failed to find definitions of smart pointers in some cases

### ISSUE THREAD

**Issue by HongxuChen** [Andersbakken/rtags#326]
When comma is present for the smart pointer variables' declaration, rtags seems only to successfully locate the definition of the 1st one. For example,

```c++
#include <memory>
int add(int v1, int v2) { return v1 + v2; }
int main(void) {
  std::unique_ptr<int> v1, v2;
  add(*v1, *v2); // A: correct for v1, failed to find the definition/declaration of v2
  int *v3, *v4;
  add(*v3, *v4); // B: both correct
}
```

In the above example, at Line A, rtags when cursor is at `v2` of Line A, `rtags-find-symbol-at-point` will jump to the declaration of `std::unique_ptr` rather than `v2`'s. 

- raw pointers are fine, such as `v3`, `v4` at Line B
- standard smart pointers, e.g., `std::shared_ptr`, also have this issue; other smart pointers, such as `llvm/src/include/llvm/ADT/IntrusiveRefCntPtr.h`, also have the problem

**Comment by Andersbakken** [comment]
Should be fixed now. Thanks for the report.

**Comment by HongxuChen** [comment]
Thanks, it works!
