### ISSUE TITLE
Build failure: no reference to clang_parseTranslationUnit2.

### ISSUE THREAD

**Issue by Fizzixnerd** [Andersbakken/rtags#333]
trying to build rtags from source for the past 7 days now.  Get this error.

make
->[.... lots of stuff being made ....]
CMakeFiles/rdm.dir/RTagsClang.cpp.o: In function `RTags::parseTranslationUnit(Path const&, List<String> const&, CXTranslationUnitImpl*&, void*, CXUnsavedFile*, int, unsigned int, String*)':
/home/matt/src/rtags/src/RTagsClang.cpp:145: undefined reference to `clang_parseTranslationUnit2'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/rdm] Error 1
make[1]: *** [src/CMakeFiles/rdm.dir/all] Error 2
make: *** [all] Error 2

llvm-config --version
-> 3.5.2

I also had to manually symlink the necessary includes to my include directory.  Don't know if that's related.

Used to get a similar error in a different file, but that was resolved in one of the commits 5 days ago.

**Comment by Andersbakken** [comment]
Hi

Is it possible that you're picking up different headers than libraries? We
do have an #ifdef to determine whether this function exists. Which version
of clang are you using?

Anders

**Comment by Fizzixnerd** [comment]
Yes, this is very possible.  I have found that multiple version of clang were installed.  I have tried removing them, but some of their libraries remain.  I will report back when I have a chance to do a clean reinstall.  For now, I suggest the issue be closed.

Thanks for your time.

Matt

**Comment by Andersbakken** [comment]
Ok. Let me know if you can't figure it out.

Anders
