### ISSUE TITLE
company-rtags--candidates does not recognize the case with no completions

### ISSUE THREAD

**Issue by pradhanpk** [Andersbakken/rtags#337]
`rtags-last-completions` seems to not maintain the information that `rdm` found 0 completions. It ends up being `nil` both in the 0 completions case and in the waiting for completions case, making `company-rtags--candidates` timeout instead of returning as soon as `rdm` finds no matches. Could you fix this?

**Comment by Andersbakken** [comment]
I think this fixes it. Can you check?

Anders

**Comment by pradhanpk** [comment]
@Andersbakken Yes, this fixed it. Thanks!

**Comment by Andersbakken** [comment]
Cool. Thanks for the report.
