### ISSUE TITLE
Can't kill buffer visiting a deleted file in a deleted directory

### ISSUE THREAD

**Issue by chep** [Andersbakken/rtags#339]
Hi Anders,

I can't kill buffers visiting files in a deleted directory even if it isn't part of a project.
It's is easy to reproduce:

In terminal:
mkdir /tmp/plop

In Emacs:
open /tmp/plop/test.txt
write something save and do not kill buffer

In terminal:
rm -r /tmp/plop

In Emacs:
try to kill the buffer.

Here is my backtrace ("Aucun fichier ou dossier de ce type" = "no such file or directory"):
Debugger entered--Lisp error: (file-error "Setting current directory" "Aucun fichier ou dossier de ce type" "/tmp/plop/")
  call-process-region(1 1 "/home/chep/bin/rc" nil #<buffer  *temp*> nil "--silent-query" "--set-buffers" "-")
  apply(call-process-region 1 1 "/home/chep/bin/rc" nil #<buffer  *temp*> nil ("--silent-query" "--set-buffers" "-"))
  rtags-call-rc(:noerror t :silent-query t :path t :unsaved #<buffer  *temp*> "--set-buffers" "-")
  rtags-set-buffers((...))
  rtags-kill-buffer-hook()
  kill-buffer("test.txt")
  ido-visit-buffer("test.txt" kill t)
  ido-buffer-internal(kill kill-buffer "Kill buffer: " "test.txt" nil ignore)
  ido-kill-buffer()
  funcall-interactively(ido-kill-buffer)
  call-interactively(ido-kill-buffer nil nil)
  command-execute(ido-kill-buffer)

**Comment by Andersbakken** [comment]
I think it should be fixed now. Can you verify?

**Comment by chep** [comment]
Fixed :-) 

thanks.

**Comment by Andersbakken** [comment]
Thanks for the report.

Anders
