### ISSUE TITLE
rc --follow-location fails, but --symbol-info  -> --find-symbols does not

### ISSUE THREAD

**Issue by Nephyrin** [Andersbakken/rtags#340]
Occasionally, `rtags-find-symbol-at-point` returns no results while `rtags-find-symbol <RET>` works. The latter auto-fills the symbol under the cursor. Looking at rdm, this corresponds to the following:

`rtags-find-symbol-at-point`:

    $ /usr/bin/rc --current-file=somefile.cpp -f somefile.cpp:320:27:

No results. `rtags-find-symbol` looks up info for the same location:

    $ /usr/bin/rc --current-file=somefile.cpp -U somefile.cpp:320:27:
    somefile.cpp:320:26:            if ( !SomeClass::SomeFunc( arg ) )
    SymbolName: bool SomeClass::SomeFunc(SomeArg *)
    Kind: MemberRefExpr
    Type: Unexposed
    SymbolLength: 17
    Range: 320:8-320:43

Which does recognize the symbol. Pressing enter:

    $ /usr/bin/rc --current-file=somefile.cpp -F "bool SomeClass::SomeFunc(SomeArg *)" --wildcard-symbol-names
    anotherfile.cpp:1114:24:    bool SomeClass::SomeFunc(SomeArg *)

Works. Unless I'm missing something, this is what -f should have returned (and usually does). I haven't figured out the pattern on what functions/files this occurs on, though it seems to work sometimes and other times not -- even in the same context.

**Comment by Nephyrin** [comment]
I should add, dropping `--wildcard-symbol-names` doesn't affect the -F invocation -- it finds the result either way.

**Comment by Andersbakken** [comment]
It's sort of a known limitation.

There are a couple of reasons that might cause this:

somefile.cpp is currently being indexed so there's no data for it.
somefile.cpp is not being indexed but has compile errors which cause clang
not to be able to fully index it.
the call that isn't found is made from a member template function. In these
cases clang often doesn't have the information for us.

It's a hard problem to solve. If you can find a reproducible case that
demonstrates it happening under other circumstances I'd like to hear about
it.

Anders

**Comment by Nephyrin** [comment]
Not sure I understand -- in the cases you mention why should `--symbol-info` and `--find-symbols` have the information and line number but not `--follow-location`?

If I can find a case that reproduces consistently I will try to narrow down a test case

**Comment by Nephyrin** [comment]
I have not seen this in some time, I believe it is fixed

**Comment by Andersbakken** [comment]
Sounds good. Let me know if it comes back.

Anders
