### ISSUE TITLE
rc -F --path-filter does not seem to work anymore

### ISSUE THREAD

**Issue by philippe-grenet** [Andersbakken/rtags#344]
This command used to return the symbols of the current file only, but now it returns all symbols for any included file which can be a lot: `/usr/local/bin/rc -F --current-file /path/to/file.cpp --path-filter /path/to/file.cpp --cursor-kind --display-name --no-context`. You can verify that with <kbd>M-x rtags-taglist</kbd> which takes a really long time on any non-trivial file.

It's too bad because I am using this command to display the symbols of the current file into a Helm buffer, like so:

![Rtags Helm](https://raw.github.com/philippe-grenet/exordium/master/doc/rtags_helm.png)

Is there anything I should change in the command to make it work again? Thanks in advance.

**Comment by Andersbakken** [comment]
Thanks for the report. It should be fixed now.

**Comment by philippe-grenet** [comment]
Yes it works. Thanks!

Let me know if you are interested by this Helm thing (screenshot above). If yes I can send you a PR once I have cleaned up the code a bit.

**Comment by Andersbakken** [comment]
Hi Philippe

Sure. Please do.

Anders
