### ISSUE TITLE
`rtags-find-symbol-at-point' stops working after saving a source file

### ISSUE THREAD

**Issue by YorkZ** [Andersbakken/rtags#346]
I just compiled the latest rtags d1a4728. I noticed that
`rtags-find-symbol-at-point` works fine as long as the source files never get
saved. However, once I change something in a file and save it, the command
`rtags-find-symbol-at-point` no longer works. Here's my steps to reproduce:

1. Open a terminal window, and run `rdm &`, the terminal prints the following:

        Running with 8 jobs, using args: -ferror-limit=0 -Wall -fspell-checking -Wno-unknown-warning-option Includepaths: -isystem /usr/local/lib/clang/3.6.0/include/
2. Find a C++ source file in Emacs.
3. Move point to a function call, and run `M-x rtags-find-symbol-at-point`, it
   works, and the point moves to the function definition!
4. Now insert a space any where in the buffer, then deleted the newly inserted
   space just to make the buffer dirty but introduces no changes.
5. Save the buffer.
6. Check the terminal window but no messages were printed.
7. Move point to the same function call, and run `M-x
   rtags-find-symbol-at-point`, it no longer works, but shows the `RTags: No
   results" message`.
8. Switch to terminal window, and run `rc -C` followed by `rc -J`, the terminal
   window the prints the following message:

        [Server] Compilation database loaded

        [100%] 1/1 15:43:48 ~/temp/myexp.cpp in 502ms. (83 syms, 45 symNames, 8 includes, 1 of 191 files, symbols: 94 of 9237, 0 queried) (487/15/0ms) (dirty). (priority 1)
        Jobs took 0.51s. We're using 2mb of memory.

   As expected, `M-x rtags-find-symbol-at-point` works again. Now, if we run
   `touch myexp.cpp` to change the time stamp, the terminal window would print
   the messages:

        [100%] 1/1 15:43:48 ~/temp/myexp.cpp in 502ms. (83 syms, 45 symNames, 8 includes, 1 of 191 files, symbols: 94 of 9237, 0 queried) (487/15/0ms) (dirty). (priority 1)
        Jobs took 0.51s. We're using 2mb of memory.

   and as expected, `M-x rtags-find-symbol-at-point` works.

**Comment by YorkZ** [comment]
Update: looks like that this problem was introduced recently because after
rolling back to commit 852cd59, the issue went away!

**Comment by Andersbakken** [comment]
Hi

How long do you wait after you save the file until you try to navigate?

Also, does rdm print anything after you save?

We have to discard all our old data about the source file when you've
modified it and let clang finish reindexing it for us.

Can you reproduce this with a small file?

regards

Anders

**Comment by YorkZ** [comment]
> How long do you wait after you save the file until you try to navigate?

I've waited for long enough, tested numerous times and had never got it work
after I saved the file.

> Also, does rdm print anything after you save?

No.

> We have to discard all our old data about the source file when you've modified
> it and let clang finish reindexing it for us.

Sure! Actually, issuing "rc -C" have delete the directory "~/.rtags".

> Can you reproduce this with a small file?

Yes, the file I used was a hello world program.

Thanks,
York

**Comment by Andersbakken** [comment]
Interesting. What platform are you on?

Can you try the following:

shell 1
$ rdm

shell 2
$ rc -J . # this should lead to output in shell 1
$ rc -s watchedpaths # can you send me the output
$ touch main.cpp # or one of the source files. This should also lead to
some output in shell 1

Anders

**Comment by YorkZ** [comment]
> What platform are you on?

Linux Mint 17.1

> shell 1
> $ rdm

    $ rdm &
    [1] 9897
    Running with 8 jobs, using args: -ferror-limit=0 -Wall -fspell-checking -Wno-unknown-warning-option
    Includepaths: -isystem /usr/local/lib/clang/3.6.0/include/

> shell 2
> $ rc -J . # this should lead to output in shell 1

Yes, here's the output from shell 1:

    $ [100%] 1/1 11:21:06 ~/test-rtags/hello-world.cpp in 580ms. (33246 syms, 45037 symNames, 308 includes, 134 of 134 files, symbols: 41413 of 41413, 133 queried) (225/291/62ms). (priority 0)
    Jobs took 0.59s. We're using 2mb of memory.

> $ rc -s watchedpaths # can you send me the output

    $ rc -s /home/york/test-rtags
    rc -s fileids|watchedpaths|dependencies|cursors|symbols|targets|symbolnames|sources|jobs|info|compilers|declarations|headererrors

Looks like rc -s WATCHEDPATHS didn't work, maybe I didn't have the correct syntax?

> $ touch main.cpp # or one of the source files. This should also lead to some
> output in shell 1

Yes. Here's the output in shell 1:

    $ [100%] 1/1 11:31:12 ~/test-rtags/hello-world.cpp in 229ms. (5 syms, 6 symNames, 1 includes, 1 of 134 files, symbols: 7 of 5191, 0 queried) (222/6/1ms) (dirty). (priority 1)
    Jobs took 0.23s. We're using 3mb of memory.

Thanks,

York

**Comment by Andersbakken** [comment]
Hi York

Sorry about the delay. It seems like your file system watcher is functioning then. Can you try to save the file from your editor and make sure it reindexes then too?

**Comment by YorkZ** [comment]
Hi Andersbakken,

> Can you try to save the file from your editor and make sure it reindexes then
> too

Sorry I'm not sure if I know exactly what you mean. Did you want te save the file to let Rtags re-indexing the project? This is the exact issue: when I save the file, I got no rdm terminal output, and rtags will no longer work. Could you please read my original bug report again, and let me know if there is anything unclear?

Thanks a lot,

York

**Comment by YorkZ** [comment]
Hi Andersbakken,

I just noticed that this issue has been closed, could you please re-open it?

Thanks,
York

**Comment by Andersbakken** [comment]
My bad. I think I tried to close another issue.

**Comment by Andersbakken** [comment]
Hi York

Can you apply this patch to FileSystemWatcher_inotify.cpp and recompile.

diff --git a/rct/FileSystemWatcher_inotify.cpp b/rct/FileSystemWatcher_inotify.cpp
index 22ff83d..e4a51ca 100644
--- a/rct/FileSystemWatcher_inotify.cpp
+++ b/rct/FileSystemWatcher_inotify.cpp
@@ -142,11 +142,11 @@ void FileSystemWatcher::notifyReadyRead()
             inotify_event *event = reinterpret_cast<inotify_event*>(buf + idx);
             idx += sizeof(inotify_event) + event->len;
             Path path = mWatchedById.value(event->wd);
-            // if (event->mask) {
-            //     printf("%s [%s]", path.constData(), event->name);
-            //     dump(event->mask);
-            //     printf("\n");
-            // }
+            if (event->mask) {
+                printf("%s [%s]", path.constData(), event->name);
+                dump(event->mask);
+                printf("\n");
+            }
 
             const bool isDir = path.isDir();
 
After that, can you run rdm and see if you get any output when you save the file in emacs?

**Comment by YorkZ** [comment]
Hi Andersbakken,

Thanks for responding. Where is the end of this patch? Anyway, since I've
noticed there are a few new commits, I pulled the latest (c3e18b2), compiled,
installed it and tested against my hello-world cpp file. Things gets changed
now. When I run "rc -J", I got the following output:

    $ [100%] 1/1 08:11:57 ~/Test/rtags/hello-world.cpp in 588ms. (33246 syms, 45037 symNames, 308 includes, 134 of 134 files, symbols: 41413 of 41413, 133 queried) (225/293/68ms). (priority 0)
    Jobs took 0.60s. We're using 2mb of memory

I then opened my hello-world.cpp, moved the point to the symbol cout, and ran
M-x rtags-find-symbol-at-point. I got the following output on the rdm terminal:

    $ Invalid message version. Got 89, expected 96 id: 33
     >59000000 21004900 00002F75 73722F6C< Y...!.I.../usr/l 00000000 >6F63616C 2F62696E 2F726320 2D54202F< ocal/bin/rc -T / 00000010 >686F6D65 2F796F72 6B2F5465 73742F72< home/york/Test/r 00000020 >74616773 2F68656C 6C6F2D77 6F726C64< tags/hello-world 00000030 >2E637070 202D2D73 696C656E 742D7175< .cpp --silent-qu 00000040 >65727925 0000002F 686F6D65 2F796F72< ery%.../home/yor 00000050 >6B2F5465 73742F72 74616773 2F68656C< k/Test/rtags/hel 00000060 >6C6F2D77 6F726C64 2E637070 10000000< lo-world.cpp.... 00000070 >00000002 FFFFFFFF FFFFFFFF FFFFFFFF< ................ 00000080 >00000000 00000000 00000000<          ............     00000090

By the way, here's my hello-world.cpp:

    #include <iostream>     // std::cout

    using namespace std;

    int main ()
    {
      cout << "Hello world\n";
    }

And here's my compile_commands.json:

    [
    {
      "directory": "/home/york/Test/rtags",
      "command": "g++ -Wall -g -pthread -std=c++11 -c hello-world.cpp",
      "file": "/home/york/Test/rtags/hello-world.cpp"
    }
    ]

Please let me know if you want me to do more experiments.

Thanks,

York

**Comment by Andersbakken** [comment]
Hi York

Sorry about the delay. I believe you're running two different versions of rdm and rc. Can you make sure there isn't an old version of rc sitting in your path?

E.g. 

M-: (executable-find "rc") <enter>

and make sure it's the right one?

Anders

**Comment by YorkZ** [comment]
Hi Andersbakken,

Yes I have both the old "working" version, and the version c3e18b2 in my system. The old version was installed in `/usr/local/bin`, and the new version in `~/Test/rtags/bin`. When I did my test, I ran `PATH=~/Test/rtags/bin:$PATH`, followed by `rdm &`. However, I probably forgot to restart my Emacs from the terminal where I changed the PATH. Therefore, my Emacs was still using the old `rc` located at `/usr/local/bin`. I apologize for this.

So, this time I started my Emacs from the terminal where I changed the PATH, and of course the "new" problem was gone. However, what's really exciting is that my old problem was also gone. Apparently the problem has been addressed somewhere between d1a4728 and c3e18b2 (there are a lot of commits in between). Anyway, this issue has been addressed, and thank you very much for your help.

I noticed there are sixteen more commits after c3e18b2, so I'm going to pull the latest, and report back if anything is wrong.

Thanks,
York

**Comment by YorkZ** [comment]
Hi Andersbakken,

Unfortunately, the original issue was still present! I did a lot of experiments but there's something I can't understand. It's all about the file name, when the file name is `myexp.cpp` it wouldn't work. However, when I changed the file name to `myexp1.cpp`, `hello.cpp` or `hello-world.cpp`, they all worked.

Could you please re-open this issue?

Thanks,
York

**Comment by Andersbakken** [comment]
Hi York

Can we try with the patch again?

<pre><code>
diff --git a/rct/FileSystemWatcher_inotify.cpp b/rct/FileSystemWatcher_inotify.cpp
index 00882fb..ad3bd54 100644
--- a/rct/FileSystemWatcher_inotify.cpp
+++ b/rct/FileSystemWatcher_inotify.cpp
@@ -142,11 +142,11 @@ void FileSystemWatcher::notifyReadyRead()
             inotify_event *event = reinterpret_cast<inotify_event*>(buf + idx);
             idx += sizeof(inotify_event) + event->len;
             Path path = mWatchedById.value(event->wd);
-            // if (event->mask) {
-            //     printf("%s [%s]", path.constData(), event->name);
-            //     dump(event->mask);
-            //     printf("\n");
-            // }
+            if (event->mask) {
+                printf("%s [%s]", path.constData(), event->name);
+                dump(event->mask);
+                printf("\n");
+            }
 
             const bool isDir = path.isDir();
 
</code></pre>

After applying this patch I would like to see the output from rdm after modifying the file from emacs.

**Comment by YorkZ** [comment]
Hi Andersbakken,

I just test it again with your patch. The problem is still there. Below is the rdm output after saving the changes to the file:

    $ /home/york/experiments/gcc/ [.#myexp.cpp]IN_CREATE
    /home/york/experiments/gcc/ [.#myexp.cpp]IN_CREATE
    /home/york/experiments/gcc/ [myexp.cpp]IN_MOVED_FROM
    /home/york/experiments/gcc/ [myexp.cpp]IN_MOVED_FROM
    /home/york/experiments/gcc/.~/ [myexp.cpp.~3049~]IN_MOVED_TO
    /home/york/experiments/gcc/ [myexp.cpp]IN_CREATE
    /home/york/experiments/gcc/.~/ [myexp.cpp.~3039~]IN_DELETE
    /home/york/experiments/gcc/ [myexp.cpp]IN_CREATE
    /home/york/experiments/gcc/ [myexp.cpp]IN_CLOSE_WRITE IN_CLOSE
    /home/york/experiments/gcc/ [.#myexp.cpp]IN_DELETE
    /home/york/experiments/gcc/ [myexp.cpp]IN_ATTRIB
    /home/york/experiments/gcc/ [myexp.cpp]IN_CLOSE_WRITE IN_CLOSE
    /home/york/experiments/gcc/ [.#myexp.cpp]IN_DELETE
    /home/york/experiments/gcc/ [myexp.cpp]IN_ATTRIB
    []
    []
    []
    []
   
Thanks

**Comment by YorkZ** [comment]
@Andersbakken: please don't close this issue because I don't think it has been addressed. The last commit I've tested against was 052c700, and I had exactly the same problem.

I also noticed that my comment I posted on Jun 4 seemed to have been shortened dramatically. If I remember correctly I had provide a very detailed rdm output, but they've just disappeared.

Please let me know what I could do to help getting to the bottom of this issue.


Thanks,
York

**Comment by Andersbakken** [comment]
Hi York

Sorry about that. Can you try the following.

cd rtags
git pull
git submodule update
# apply patch I sent earlier to FileSystemWatcher_inotify.cpp

rdm -v -v -v  2>&1 | tee logfile

echo "" >> main.cpp # make sure rdm reindexes
# modify main.cpp from emacs and then save

Then send me the whole log

Anders

**Comment by Andersbakken** [comment]
Hi York

Any chance you could update to the latest rtags and check if it might have gone away? I fixed something that might be causing this kind of problem in this commit: https://github.com/Andersbakken/rct/commit/5d6cda1d5bf2400021a7d730eebed69af8afe8e6

**Comment by YorkZ** [comment]
Hi Andersbakken,

I'm really sorry for not having the time recently, and thank you very much for trying to fix this issue. I will pull the latest and test it tomorrow. Is the commit you suggested included in the master branch?

Thanks,
York

**Comment by Andersbakken** [comment]
No worries.

Yeah it's in master as long as you make sure to update the rct submodule.

Let me know. I'd like to get to the bottom of it.

Anders

**Comment by YorkZ** [comment]
Great work Anders! I've tested commit 51cee86, with rct 0be8422, and it works now!

Thanks,
York

**Comment by Andersbakken** [comment]
Awesome. Glad to hear. I've just made some more changes in the same general
area btw. Can you check that it didn't break?

Anders

**Comment by YorkZ** [comment]
Yes, I will definitely test it. But since I will be extremely busy until Aug 8, I may test it after Aug 8, is that OK? Sorry about it.

Thanks,
York

**Comment by Andersbakken** [comment]
Sure. No problem at all. Just let me know if it breaks.

Anders

**Comment by YorkZ** [comment]
Hi Andersbakken,

Sorry for the delay, I've just tested this issue with the latest version, commit 17bdbd4 with rct b70e7a0. It still works. Thank you very much!

York

**Comment by Andersbakken** [comment]
Hi York

Glad to hear.

Anders
