### ISSUE TITLE
Symbol finding functions with semantic information?

### ISSUE THREAD

**Issue by pradhanpk** [Andersbakken/rtags#347]
Is there a way of finding symbols by specifying what we are looking for? For example, running `rc -F SomeClass` shows a lot of matches which aren't `class SomeClass`. If `SomeClass` was defined in a nested namespace `A::B::C`, then `using A::B::C::SomeClass` declarations end up matching, in addition to member function definitions of `SomeClass`. Would it be possible to support the type info that clang's AST exposes?

@Andersbakken Would you mind giving me a very short overview of the classes I should look at for where this is implemented? I looked through this chain before deciding to ask you first : `FindSymbolsJob::execute` -> `Project::findSymbols` -> `Project::openSymbolNames`.

**Comment by Andersbakken** [comment]
Hi Pradhan

I've been meaning to write up something about the datastructure of the database but it's relatively complicated so it's rather a lengthy task. Do I understand you correctly that you want to filter on the kind? 

E.g.

You want to restrict your matches to only class definitions (no constructors/no forward declarations/using declarations).

I could probably add some custom filter for this kind of thing.

**Comment by pradhanpk** [comment]
@Andersbakken Yeah, that's right. I want to filter by the kind, like your example illustrated.

**Comment by Andersbakken** [comment]
Can you see if this works for you?

In your example you'd want to do this:

rc -F SomeClass --definition-only --kind-filter class

**Comment by Andersbakken** [comment]
https://github.com/Andersbakken/rtags/commit/430481365a5ce407b4e9d2eb4c322856272110ad

**Comment by Andersbakken** [comment]
My commit message claimed it was --filter-kind but the switch is actually --kind-filter :-)

Please reopen if it doesn't work or if needs tweaking.
