### ISSUE TITLE
rct submodule issue

### ISSUE THREAD

**Issue by mrbiggfoot** [Andersbakken/rtags#350]
$ git submodule init
Submodule 'src/rct' (https://github.com/Andersbakken/rct) registered for path 'src/rct'

$ git submodule update
Initialized empty Git repository in /home/xxx/tmp/rtags_Andersbakken/src/rct/.git/
remote: Counting objects: 4127, done.
remote: Total 4127 (delta 0), reused 0 (delta 0), pack-reused 4127
Receiving objects: 100% (4127/4127), 1.12 MiB | 961 KiB/s, done.
Resolving deltas: 100% (2855/2855), done.
fatal: reference is not a tree: 635b2978b600523e87ce0084d1eeebf6f42696e5
Unable to checkout '635b2978b600523e87ce0084d1eeebf6f42696e5' in submodule path 'src/rct'

Please push up the appropriate commit into src/rct.

**Comment by Andersbakken** [comment]
Just fixed it.
