### ISSUE TITLE
--no-comments doesn't seem to work

### ISSUE THREAD

**Issue by gvol** [Andersbakken/rtags#351]
I'm running with 

    ./bin/rdm -j4 -a11 --no-comments

and getting the errors below

    Caught signal 11
    
    1/27 sigHandler(int)
    2/27 _sigtramp
    3/27 std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__init(char const*, unsigned long)
    4/27 clang::comments::CommentVisitorBase<clang::comments::make_const_ptr, (anonymous namespace)::CommentASTToXMLConverter, void>::visit(clang::comments::Comment const*)
    5/27 (anonymous namespace)::CommentASTToXMLConverter::visitFullComment(clang::comments::FullComment const*)
    6/27 clang::index::CommentToXMLConverter::convertCommentToXML(clang::comments::FullComment const*, llvm::SmallVectorImpl<char>&, clang::ASTContext const&)
    7/27 clang_FullComment_getAsXML
    8/27 ClangIndexer::handleCursor(CXCursor const&, CXCursorKind, Location const&, Symbol**)
    9/27 ClangIndexer::indexVisitor(CXCursor, CXCursor, void*)
    10/27 clang::cxcursor::CursorVisitor::Visit(CXCursor, bool)
    11/27 clang::cxcursor::CursorVisitor::VisitDeclContext(clang::DeclContext*)
    12/27 clang::cxcursor::CursorVisitor::VisitCXXRecordDecl(clang::CXXRecordDecl*)
    13/27 clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::cxcursor::CursorVisitor, bool>::Visit(clang::Decl*)
    14/27 clang::cxcursor::CursorVisitor::VisitChildren(CXCursor)
    15/27 clang::cxcursor::CursorVisitor::Visit(CXCursor, bool)
    16/27 clang::cxcursor::CursorVisitor::VisitDeclContext(clang::DeclContext*)
    17/27 clang::declvisitor::Base<clang::declvisitor::make_ptr, clang::cxcursor::CursorVisitor, bool>::Visit(clang::Decl*)
    18/27 clang::cxcursor::CursorVisitor::VisitChildren(CXCursor)
    19/27 clang::cxcursor::CursorVisitor::Visit(CXCursor, bool)
    20/27 clang::cxcursor::CursorVisitor::VisitDeclContext(clang::DeclContext*)
    21/27 clang::cxcursor::CursorVisitor::VisitChildren(CXCursor)
    22/27 clang_visitChildren
    23/27 ClangIndexer::visit()
    24/27 ClangIndexer::exec(String const&)
    25/27 main
    26/27 start
    27/27 0x0

I also have an .rdmrc with some include paths in it.  

I'm not sure when this regression started since I hadn't updated for a while.  I can bisect if that would be helpful.

**Comment by Andersbakken** [comment]
Thanks for the report. Should work again now.

**Comment by gvol** [comment]
Thanks, that was fast!

**Comment by Andersbakken** [comment]
My pleasure :-)

Anders
