### ISSUE TITLE
Error in elisp diagnostics completions parsing

### ISSUE THREAD

**Issue by terranpro** [Andersbakken/rtags#352]
Hi Anders,

Recently I've seen run into some errors in the diagnostics process:

    Debugger entered--Lisp error: (void-variable header)
      (list "include" "include " header "" "NotImplemented")
      (list (list "define" "define macro" "NotImplemented") (list "define" "define macro(args)" "NotImplemented") (list "elif" "elif condition" "NotImplemented") (list "else" "else" "NotImplemented") (list "endif" "endif" "NotImplemented") (list "error" "error message" "NotImplemented") (list "if" "if condition" "NotImplemented") (list "ifdef" "ifdef macro" "NotImplemented") (list "ifndef" "ifndef macro" "NotImplemented") (list "include" "include " header "" "NotImplemented") (list "include" "include <header>" "NotImplemented") (list "include_next" "include_next " header "" "NotImplemented") (list "include_next" "include_next <header>" "NotImplemented") (list "line" "line number" "NotImplemented") (list "line" "line number " filename "" "NotImplemented") (list "pragma" "pragma arguments" "NotImplemented") (list "undef" "undef macro" "NotImplemented") (list "warning" "warning message" "NotImplemented"))

     ...

All those `NotImplemented`s look pretty intimidating - am I missing some clang features or maybe need some extra flags?
Looks like not only `header` but also `filename` below it will both trigger this `void-variable` error.

This is on a linux machine with clang 3.5.1 and gcc 4.9.1

Brian

**Comment by terranpro** [comment]
D'oh I think you just fixed this - looks like a dup of https://github.com/Andersbakken/rtags/issues/322

Will verify and close

**Comment by Andersbakken** [comment]
Yeah I think it should work now. I had an escape function that I used it
spell checking but not for completions which also needed it. Hopefully this
is the last of these.

Anders

**Comment by terranpro** [comment]
Indeed it did fix it - thanks!
