### ISSUE TITLE
Can't find some includes after Clang packages changed search path.

### ISSUE THREAD

**Issue by toojays** [Andersbakken/rtags#358]
The Debian packaging for Clang recently fixed an issue where Clang was being configured to look in GCC's internal include directory. https://llvm.org/bugs/show_bug.cgi?id=23556

Since then, rtags is failing to find certain standard headers which are supposed to be provided by the compiler rather than the C library. E.g. stddef.h, stdbool.h, stdarg.h.

For example:
```
jscott@citra:~/src/rtags-test$ cat foo.cpp 
#include <stdio.h>

void f ()
{
  printf("Hello!\n");
}
jscott@citra:~/src/rtags-test$ clang++ -c foo.cpp
```

Then rtags says:
```
/home/jscott/src/rtags-test/foo.cpp
/usr/include/stdio.h:33:11: fatal error: 'stddef.h' file not found
CI::parse loading unit: clang -c -ferror-limit=0 -Wall -fspell-checking -Wno-unknown-warning-option -isystem /usr/lib/llvm-3.6/lib/clang/3.6.1/include/  /home/jscott/src/rtags-test/foo.cpp true
couldn't create included file inclusion directive i stddef.h /usr/include/stdio.h:33:1
couldn't create included file inclusion directive i stddef.h /usr/include/_G_config.h:15:1
couldn't create included file inclusion directive i stdarg.h /usr/include/libio.h:49:1
```

**Comment by toojays** [comment]
Silly me. The answer was right in front of my face, in the output which I omitted to paste:

```
Includepaths: -isystem /usr/lib/llvm-3.6/lib/clang/3.6.1/include/
```

But these new packages are versioned 3.6.2.

After doing a clean build, it looks fine.

```
Includepaths: -isystem /usr/lib/llvm-3.6/lib/clang/3.6.2/include/
```

Sorry for the noise.

**Comment by Andersbakken** [comment]
Ah. Glad to hear. Let me know if you run into other problems.

regards

Anders
