### ISSUE TITLE
rdm has a memory leak on certain systems.

### ISSUE THREAD

**Issue by adireini** [Andersbakken/rtags#359]
I'm using the exact same configuration on two systems (MacBook Pro and an iMac). On the iMac, every indexing round reports a bigger memory consumption. On the MacBook, memory consumption is relatively constant, and drops after spiking.

any Idea?

**Comment by adireini** [comment]
I found the problem. It seems that the ScanThread is working very hard. The project root is calculated to be at a parent directory of the compilation tree, which causes the ScanThread to scan a *huge* tree of non related source code (Gigabytes).
As a result, rdm takes up 100% cpu and occupies more than 1.5 gigabytes of memory.
How is the project root calculated? Is it the nearest common ancestor of all the files in the compilation commands?

**Comment by Andersbakken** [comment]
Sorry about the delay. It uses various heuristics. Did you figure out a way
to properly identify the root of the project? We might have to add
something for your build system.

regards

Anders
