### ISSUE TITLE
rtags does not find enum class and its member definition

### ISSUE THREAD

**Issue by Mafeuser** [Andersbakken/rtags#362]
Hallo rtags team.

First of all, thank You for rtags module.
It brings new quality to C++/C++11 programming in emacs.

Yesterday I found the following problem (comment in the code):
```
enum class RadioButton
{
  BUTTON1 = 1,
  BUTTON2,
  BUTTON3
};

class Radio
{
  public:
    Radio() = default;
    virtual ~Radio() = default;
    RadioButton button() const { return rb; }

  private:
    RadioButton rb {RadioButton::BUTTON2};
};                 //   ^          ^     problem:
                   //   +----------+---- rtags-find-symbol-at-point
                   //                    ends with following message:
                   //                    RTags: No results

int main(int argc, char *argv[])
{
  Radio rr;
  return 0;
}
```
Is it an rtags issue, or clang one? Or maybe I'm doing something wrong?

compilation command:
`~/g++  -MD -MP -Wpedantic -Wall -O0 -g -std=c++11 11/enumClass.cpp -o 11/enumClass`

```
$ ll ~/g++
lrwxrwxrwx 1 user user 50 may 12 20:07 /home/user/g++ -> /usr/local/rtags/gcc-rtags-wrapper.sh*
```

I'm using rtags:52bc7d4, clang:3.6.1, emacs:24.5, cc-mode: 5.33.

regards,
Paul

**Comment by Andersbakken** [comment]
Hi Paul

Thanks for the report. I believe it's a clang issue I'm afraid. We don't get any cursor for this location at sadly. I believe it's an issue of the public C-api lagging behind the internal C++ API since clang-check -dump-ast seems to expose at least a little bit of info about it.

**Comment by Mafeuser** [comment]
Anders,
thanks for clarification

regards,
Paul
