### ISSUE TITLE
Cannot be compiled with the newly updated rct/rct/Log.h

### ISSUE THREAD

**Issue by ooScott** [Andersbakken/rtags#363]
In the newly updated Log.h, implicit conversion from int to enum type LogLevel is no longer available. Therefore, it caused compiling failure of rtags.

**Comment by jhanssen** [comment]
Did you update rct manually? The commit referenced from the rtags tree should work just fine. We are aware that HEAD of rct doesn't work with rtags right now.

**Comment by Andersbakken** [comment]
I believe this should be fixed now. If not, please reopen.
