### ISSUE TITLE
Fail with depth path 

### ISSUE THREAD

**Issue by sunlin7** [Andersbakken/rtags#368]
Hi Anders,

The rtags will fail on some deep folder, especial the path with underscore "_", 
and it's seems the function ```encodePath()``` in https://github.com/Andersbakken/rtags/blob/5af18c06059b0c31bc6905ce529110bc1ab5680f/src/RTags.h#L139-#L163 would generate an very long filename.

For example, the maximum filename length for ext4 file system is 255 bytes(```Maximum filename length``` from http://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits)
A a.c under follow folder:
```
/tmp/test_folder_1/test_folder_2/test_folder_3/test_folder_4/test_folder_5/test_folder_6/test_folder_7/a.c
```
then ```encodePath()``` with generate a path like this,
```
_tmp_test<underscore>folder<underscore>1_test<underscore>folder<underscore>2_test<underscore>folder<underscore>3_test<underscore>folder<underscore>4_test<underscore>folder<underscore>5_test<underscore>folder<underscore>6_test<underscore>folder<underscore>7
```
This is too long as file name for ext4 system.

So, could you change ```encodePath()``` to a better method to generate the filename please?
Thank you.

PS:I simply replace the "/" with "!" in the path, and it works for me.

Best Regards
Lin Sun

**Comment by Andersbakken** [comment]
You're absolutely right. I've made it a little less silly. I could put in something that base64-encodes it if it gets too long. Does this patch fix it for you or is it still adding too many extra characters?

**Comment by sunlin7** [comment]
Hi Anders,

https://github.com/Andersbakken/rtags/blob/3cac8b73732fa8c477331723d42619b03ed01e28/src/RTags.h#L150
```
path.replace(i, 1, "_");
```
did you miss one underscore? 
```
path.replace(i, 1, "__");
```

**Comment by Andersbakken** [comment]
Oops.

**Comment by sunlin7** [comment]
Hi Anders,

Thank you for your help, every thing seems OK now.
And I'm compiling rtags now, then the test result will update later.

Best Regards
Lin Sun

**Comment by Andersbakken** [comment]
Cool. Let me know if there are more issues.

Anders

**Comment by sunlin7** [comment]
Hi Anders, 

After update to github.com/Andersbakken/rtags/commit/74db4d1660d965eaf2a2dcaabbf2e2ac5a185643,
the path issue fixed. Than you.

But there is an new critical issue, the rdm will crash with arguments.
please try ```rdm -v```, then it crashed.
Should I report another issue?

**Comment by Andersbakken** [comment]
Try now. I think it should be gone. Thanks for the report.

**Comment by sunlin7** [comment]
It works awesome.
Please close this ticket.
Thank you~
