### ISSUE TITLE
Allow customizing the layout of the *RTags* buffer

### ISSUE THREAD

**Issue by miabrahams** [Andersbakken/rtags#373]
It would be nice if the layout could be altered to give a offer a better vertical split.  The way I would try first would be to add a newline between the file path and the code snippet and to add a horizontal line between each entry.  

I went to try to do it but it depends on a refactor extracting the regex used to parse the buffer and potentially other things.

**Comment by Andersbakken** [comment]
It would require some refactoring of the elisp code around that. I could take a look at making it possible to customize. If you feel like contributing some code we would happily consider merging it too.

**Comment by Andersbakken** [comment]
I added something. Let me know how this works for you. I'm perfectly willing to change the appearance btw :-)

**Comment by miabrahams** [comment]
Thank you so much for the change!  I split my dev time between windows and linux and I've been on Windows for a few days, but I expect to share a patch after I get a chance to experiment.

**Comment by Andersbakken** [comment]
Sounds good. It would be nice with a system where one could pass a function
to format a line or something.

Anders

On Sat, Jul 18, 2015 at 10:55 PM, Michael Abrahams <notifications@github.com

**Comment by miabrahams** [comment]
I was playing around with the source, if I'm going to try to write a function to generate arbitrary output format, writing a Helm extension might be only a hair's breadth away.  I may try to do that first since I am a great fan of Helm.

**Comment by Andersbakken** [comment]
Sounds good. Let me know when you have something.


Anders
