### ISSUE TITLE
Installation does not install Emacs Lisp files

### ISSUE THREAD

**Issue by egarrulo** [Andersbakken/rtags#375]
`make install` should install Emacs Lisp libraries in a subdirectory of `<prefix>/share` (for example: `<prefix>/share/rtags-2.0/editors/emacs/`).  Currently, the `<prefix>/share` only contains the `man` directory. 

Thanks for your attention.

**Comment by Nephyrin** [comment]
Not to nitpick this too much, but the common place for emacs lisp is `<prefix>/share/emacs/site-list/<package>/`

I have numerous files there on my current system, but nothing in `/usr/share/elisp/`

The rtags arch package currently installs these to the former

**Comment by egarrulo** [comment]
I didn't know about that location.  Thanks for this information. Indeed I have some Emacs libraries there.  Yet, `load-path` does not contain that folder.  Maybe the reason is that I didn't install Emacs in `/usr/local/", but used a prefix instead.

**Comment by egarrulo** [comment]
I have tried with the Emacs that comes with my Linux distro, started with `emacs -Q`, and it doesn't look in that directory either.  But it should, according to the Emacs Lisp reference. Sorry, but I don't know what to say now.  Anyway, I see that there is already a commit for this.  Thanks for your assistance.

**Comment by Andersbakken** [comment]
Good point John. Should be fixed now.

Anders

**Comment by autosquid** [comment]
how can install from melpa. what should I add to my config. after install-package?

**Comment by Andersbakken** [comment]
I don't really use 'package so I couldn't tell you much about that part but you shouldn't need much more than

(require 'rtags)

to get started with using it. You need to start the daemon and make sure that it knows about your compilation flags etc though.

There's some info here: https://github.com/Andersbakken/rtags

(under SETUP).
