### ISSUE TITLE
Cygwin windows build fails

### ISSUE THREAD

**Issue by deuscovrigus** [Andersbakken/rtags#377]
Hello!

First or all I want to say that rtags is amazing and I was waiting forever for a such an off the charts replacement for cedet. Everything works well on my Mac and Unix boxes but I decided to give the windows build a shot using Cygwin. It seems that cmake finds all of the clang/llvm/ssl/ncurses deps, but I get this error during the build process:

/home/octi/rtags/src/rct/rct/FileSystemWatcher_win32.cpp: In member function ‘void WatcherData::updatePaths()’:
/home/octi/rtags/src/rct/rct/FileSystemWatcher_win32.cpp:188:38: error: no matching function for call to ‘Path::visit(Path::VisitResult (&)(const Path&, void*), WatcherData::PathData*) const’
             path.visit(initDir, &data);
                                      ^
/home/octi/rtags/src/rct/rct/FileSystemWatcher_win32.cpp:188:38: note: candidate is:
In file included from /home/octi/rtags/src/rct/rct/FileSystemWatcher.h:5:0,
                 from /home/octi/rtags/src/rct/rct/FileSystemWatcher_win32.cpp:1:
/home/octi/rtags/src/rct/rct/Path.h:149:10: note: void Path::visit(const std::function<Path::VisitResult(const Path&)>&) const
     void visit(const std::function<VisitResult(const Path &path)> &callback) const;
          ^
/home/octi/rtags/src/rct/rct/Path.h:149:10: note:   candidate expects 1 argument, 2 provided
/home/octi/rtags/src/rct/rct/FileSystemWatcher_win32.cpp: In member function ‘void WatcherData::run()’:

Did I just get unlucky and pull a revision where the windows Cygwin build does not work?

Thanks,

-Octi

**Comment by Andersbakken** [comment]
Thanks for the report. I think it should be fixed now. Can you check?

**Comment by deuscovrigus** [comment]
Thanks for being so prompt. I will be active now. 
I pulled the latest but it seems I get the same trace:

/home/octi/rtags/src/rct/rct/FileSystemWatcher_win32.cpp: In member function ‘void WatcherData::updatePaths()’:
/home/octi/rtags/src/rct/rct/FileSystemWatcher_win32.cpp:188:38: error: no matching function for call to ‘Path::visit(Path::VisitResult (&)(const Path&, void*), WatcherData::PathData*) const’
             path.visit(initDir, &data);
                                      ^
/home/octi/rtags/src/rct/rct/FileSystemWatcher_win32.cpp:188:38: note: candidate is:
In file included from /home/octi/rtags/src/rct/rct/FileSystemWatcher.h:5:0,
                 from /home/octi/rtags/src/rct/rct/FileSystemWatcher_win32.cpp:1:
/home/octi/rtags/src/rct/rct/Path.h:149:10: note: void Path::visit(const std::function<Path::VisitResult(const Path&)>&) const
     void visit(const std::function<VisitResult(const Path &path)> &callback) const;
          ^
/home/octi/rtags/src/rct/rct/Path.h:149:10: note:   candidate expects 1 argument, 2 provided
/home/octi/rtags/src/rct/rct/FileSystemWatcher_win32.cpp: In member function ‘void WatcherData::run()’:
/home/octi/rtags/src/rct/rct/FileSystemWatcher_win32.cpp:258:41: error: no matching function for call to ‘Path::visit(Path::VisitResult (&)(const Path&, void*), WatcherData::PathData*) const’
                 p.visit(updateDir, &data);
                                         ^
/home/octi/rtags/src/rct/rct/FileSystemWatcher_win32.cpp:258:41: note: candidate is:
In file included from /home/octi/rtags/src/rct/rct/FileSystemWatcher.h:5:0,
                 from /home/octi/rtags/src/rct/rct/FileSystemWatcher_win32.cpp:1:
/home/octi/rtags/src/rct/rct/Path.h:149:10: note: void Path::visit(const std::function<Path::VisitResult(const Path&)>&) const
     void visit(const std::function<VisitResult(const Path &path)> &callback) const;
          ^
/home/octi/rtags/src/rct/rct/Path.h:149:10: note:   candidate expects 1 argument, 2 provided
src/rct/CMakeFiles/rct.dir/build.make:675: recipe for target 'src/rct/CMakeFiles/rct.dir/rct/FileSystemWatcher_win32.cpp.o' failed
make[2]: *** [src/rct/CMakeFiles/rct.dir/rct/FileSystemWatcher_win32.cpp.o] Error 1
CMakeFiles/Makefile2:303: recipe for target 'src/rct/CMakeFiles/rct.dir/all' failed
make[1]: *** [src/rct/CMakeFiles/rct.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Andersbakken** [comment]
Hm. That's odd. Did you make sure to do a:

git submodule update

after

git pull

Anders

**Comment by deuscovrigus** [comment]
that's exactly what it was! I didn't notice the error was in rct which didn't get pulled without the submodule update.
Now everything build and linked successfully! Can't wait to test it after work! 
Thanks Anders!

**Comment by Andersbakken** [comment]
My pleasure. Let me know if you run into any more issues.

Anders
