### ISSUE TITLE
company-mode completion fails - "clang failed with error 1:"

### ISSUE THREAD

**Issue by deuscovrigus** [Andersbakken/rtags#379]
I am trying to use company instead of ac for rtags completion and every time I try to complete something I get:
clang failed with error 1:
/usr/bin/clang -fsyntax-only -Xclang -code-completion-macros -x c++ -Xclang -code-completion-at=-:43:11 -
I am using the latest build of rtags and latest version of the .el packages.

Auto complete works, but I would like the popup to appear as soon as I press a "." or the "->"
It usually appears after I press the ".", delete it and then press "." again. It sounds like an auto-complete issue but I'm not sure.

Any help is appreciated

-octi

**Comment by deuscovrigus** [comment]
I got company to work on my mac, where rtags was build with llvm 3.6 instead. It didn't work right off the bat until I added this to my init file
	    (require 'company-rtags)
	    (setq company-backends '(company-rtags))
	    (company-mode)
	    (rtags-diagnostics)
Apparently company-rtags needs rtags-diagnostics on?
However, the reported issue is on my ubuntu box with llvm 3.4. I don't know right now whether enabling rtags-diagnostics will fix it.

**Comment by Andersbakken** [comment]
Diagnostics have to be on so hopefully that should take care of it.

**Comment by deuscovrigus** [comment]
Yep! Enabling rtags-diagnostics makes it work.
Strangely enough, ac-mode doesn't need it or it might get turned on somewhere else?

**Comment by Andersbakken** [comment]
It seems the rtags-ac backend autostarts it. Probably would be a good idea for company too. I just added something that would autostart it.
