### ISSUE TITLE
core dumped

### ISSUE THREAD

**Issue by henry-y** [Andersbakken/rtags#382]
```
Running with 32 jobs, using args: -ferror-limit=0 -Wall -fspell-checking -Wno-unknown-warning-option
Includepaths: -isystem /usr/local/lib/clang/3.4.2/include/
terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
Aborted (core dumped)
```

used committed version: cb91d9bbac6c7e965e8691c28393c0157a74a152

**Comment by Andersbakken** [comment]
I believe this should take care of it. We really don't have a lot of threads and there was definitely some unsafe code in FileManager. Thanks for the report. Let me know if you can reproduce this again with the patch.

**Comment by henry-y** [comment]
It still fails:

terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
Aborted (core dumped)

**Comment by Andersbakken** [comment]
Hm. Can you catch it in gdb and send me the stack trace?

regards

Anders

**Comment by henry-y** [comment]
Hi, it seems this only happens while using on NFS. I've tried to reproduce the issue locally on my computer, and it works without any problem. When I ssh to a remote server, my home directory is a nfs directory, and I can't see any dump file created, maybe because of the configuration of the server? I'm not root.

Could you please check whether it's related to lock nfs files? I remembered you solved one issue about this before. Please refer to issue number 307.
