### ISSUE TITLE
Symbols file deleted on fast file writes

### ISSUE THREAD

**Issue by sphaerophoria** [Andersbakken/rtags#385]
When saving a file multiple times (only tested from vim) the symbols file for the file get deleted and cannot be restored. 

Noticed and tested on both Ubuntu 15.04 and 14.04 with vim from the repos and neovim from the official neovim ppa.

To reproduce create a simple test file

    testuser@cavetroll:~/test$ cat test.cpp
    #include <iostream>
    int main(void)
    {
            int x = 5;
            std::cout << x << std::endl;
    }

    testuser@cavetroll:~/test$ rc --project-root . -c "clang++ -o test test.cpp"
    testuser@cavetroll:~/test$ rc --project-root . -f test.cpp:6:15
    /home/testuser/test/test.cpp:5:6:               int x = 5;
    testuser@cavetroll:~/test$ vim -c ":w" -c ":w" -c ":wq" test.cpp
    testuser@cavetroll:~/test$ rc --project-root . -f test.cpp:6:15

with rdm showing the following

    [100%] 1/1 18:22:09 ~/test/test.cpp in 123ms. (10 syms, 10 symNames, 1 includes, 1 of 96 files, symbols: 12 of 3319, 0 queried) (121/2/0ms). (priority 0)
    Jobs took 0.14s. We're using 4mb of memory.
    rc --project-root . -f test.cpp:6:15
    => /home/testuser/test/test.cpp:5:6:            int x = 5;
    rc --project-root . -f test.cpp:6:15
    Failed to open /home/testuser/.rtags/_home_testuser_test_._/4/symbols /home/testuser/test/test.cpp (2) 71

The file is never restored, rc -V does nothing, I have to re-pass the compilation command to get it back. The folder /home/testuser/.rtags/_home_testuser_test_._/4 does not exist at all.

**Comment by Andersbakken** [comment]
Thanks for the report. I think it should work now.

**Comment by sphaerophoria** [comment]
Awesome, looks good. My day at work tomorrow will be much more pleasant :).

**Comment by Andersbakken** [comment]
Glad to hear. Let me know if you run into other issues.

Anders
