### ISSUE TITLE
rtags crashes on some source files that use boost/circular_buffer.hpp

### ISSUE THREAD

**Issue by mraway** [Andersbakken/rtags#390]
I have been using rtags in a relative large C++ project for a while, the overall experience is wonderful. The only problem I could find so far is that rtags crashes every time it parse source files that contains boost/circular_buffer.hpp. The trace is shown below:

Caught signal 11

1/24 /home/wei/.emacs.d/elisp/rtags/bin/rp() [0x41bba6]
2/24 /lib/x86_64-linux-gnu/libpthread.so.0(+0x10340) [0x7f688efa0340]
3/24 /usr/lib/llvm-3.4/lib/libclang.so.1(+0x86fd79) [0x7f688fd21d79]
4/24 /usr/lib/llvm-3.4/lib/libclang.so.1(+0x1fcd13) [0x7f688f6aed13]
5/24 /usr/lib/llvm-3.4/lib/libclang.so.1(+0x1faca8) [0x7f688f6acca8]
6/24 /usr/lib/llvm-3.4/lib/libclang.so.1(+0x1fd5ad) [0x7f688f6af5ad]
7/24 /usr/lib/llvm-3.4/lib/libclang.so.1(clang_FullComment_getAsXML+0x68) [0x7f688f676878]
8/24 ClangIndexer::handleCursor(CXCursor const&, CXCursorKind, Location const&, Symbol*_)
9/24 ClangIndexer::indexVisitor(CXCursor, CXCursor, void_)
10/24 /usr/lib/llvm-3.4/lib/libclang.so.1(+0x1aa99b) [0x7f688f65c99b]
11/24 /usr/lib/llvm-3.4/lib/libclang.so.1(+0x1ad913) [0x7f688f65f913]
12/24 /usr/lib/llvm-3.4/lib/libclang.so.1(+0x1aa354) [0x7f688f65c354]
13/24 /usr/lib/llvm-3.4/lib/libclang.so.1(+0x1aa9ef) [0x7f688f65c9ef]
14/24 /usr/lib/llvm-3.4/lib/libclang.so.1(+0x1ad913) [0x7f688f65f913]
15/24 /usr/lib/llvm-3.4/lib/libclang.so.1(+0x1aa568) [0x7f688f65c568]
16/24 /usr/lib/llvm-3.4/lib/libclang.so.1(+0x1aa9ef) [0x7f688f65c9ef]
17/24 /usr/lib/llvm-3.4/lib/libclang.so.1(+0x1ad913) [0x7f688f65f913]
18/24 /usr/lib/llvm-3.4/lib/libclang.so.1(+0x1aa72e) [0x7f688f65c72e]
19/24 /usr/lib/llvm-3.4/lib/libclang.so.1(clang_visitChildren+0x185) [0x7f688f664c35]
20/24 ClangIndexer::visit()
21/24 ClangIndexer::exec(String const&)
22/24 /home/wei/.emacs.d/elisp/rtags/bin/rp(main+0x2d4) [0x41b304]
23/24 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7f688e7caec5]
24/24 /home/wei/.emacs.d/elisp/rtags/bin/rp() [0x41ba75]

I'm not sure what caused this SEG FAULT though. I have tried ratgs on a standalone circular buffer example program and saw no problem. It only crashes when parsing files in my large project.

**Comment by Andersbakken** [comment]
Odd. If you could compile clang with debug symbols and run rdm with -q1 rp
should sit in the sighandler and allow you to attach to it with gdb -p.

I realize it's a bit of an effort. Which clang version are you on? It's
quite likely a crash inside of clang so upgrading or downgrading might be a
solution as well.

Anders

**Comment by mraway** [comment]
I'm on 3.4 which is a little outdated. I will report what happens on newer clang versions when I get some time. Thank you!

**Comment by mraway** [comment]
Since I'm on a shared server it took me a while to get the library updates, yes I'm still seeing the same seg fault with libclang 3.5.

**Comment by mraway** [comment]
This is fixed by applying the "--no-comments" option, thank you!

**Comment by Andersbakken** [comment]
My pleasure. We should probably make a stand-alone example that reproduces
this and report it to the libclang people.

Anders

**Comment by cslux** [comment]
@mraway does rtags still crash?
