### ISSUE TITLE
Code completion approach and related functionality.

### ISSUE THREAD

**Issue by lyuts** [Andersbakken/rtags#392]
Hi,

I've got a question regarding code completion. Trying to get it integrated into vim bindings plugin. So far it seems like this will be a rather challenging thing task. Here are my findings, could have missed/misunderstood something, so apologies in advance.

AFAIU, the only way right now to get code completion is to invoke

```rc -l file:row:col```

however, the problem with this approach is that the file changes should be saved before invoking ```rc```. In my opinion, this saves are redundant and should not be made unless this is the only existing options to get code completion working.

With this in mind, couple of questions:
1. Is it possible to expose completion options given a type? With this approach the code completion functionality would be just to determine the type for which the completion is requests (already exists in rtags) and then to query rtags for this type. For example, having
```
Set<int> s;
s.*
```
*- is cursor position at code completion invocation
we know that s is of type Set, get completions from rtags for type Set and then prepare/display completion options.
2. I remember seeing some scripts for emacs. Do you have completion for emacs? If so, how did you get it working?

Thank you.

**Comment by jhanssen** [comment]
If I'm understanding you correctly then you should be able to make this work by passing the unsaved buffer from vim to rtags using ```--unsaved-file```. Clang will use this data instead of the actual file, this is what we do for emacs. I don't think Clang gives us the option to complete with just the type information, at least not using just the C API.

**Comment by lyuts** [comment]
When invoking with this flag, e.g.
```rc -U src/Server.cpp:116:10 --unsaved-file=src/Server.cpp:3034```
does the unsaved-file filename have to match the actual file name?

**Comment by lyuts** [comment]
Ignore me, read unit tests that use this flag and show how this flag is supposed to be used.
