### ISSUE TITLE
Provide type for symbol

### ISSUE THREAD

**Issue by hotpxl** [Andersbakken/rtags#394]
Is it possible (or if it is already implemented) to get type for C++ symbols? It would be really useful when using `auto`.

**Comment by Andersbakken** [comment]
I just added something for this. To use do: (rtags-symbol-type)

**Comment by hotpxl** [comment]
That's infuriatingly fast! Thanks.

**Comment by Andersbakken** [comment]
My pleasure. ;)

**Comment by Andersbakken** [comment]
Btw. I've refactored this a little in the last couple of days so it should be better now.

**Comment by hotpxl** [comment]
`(rtags-symbol-type)` always shows `progn: Symbol's value as variable is void: match-string`. But other functions are correct.

**Comment by hotpxl** [comment]
Wait. I can solve this.

**Comment by Andersbakken** [comment]
Oops. I guess I never tested the elisp. I'll get it fixed (unless you want
to send a pull request in the meantime).

**Comment by hotpxl** [comment]
PR sent #397

**Comment by Andersbakken** [comment]
Thanks. Merged now.
