### ISSUE TITLE
Function Definitions Hidden by Macros are not Detected Properly

### ISSUE THREAD

**Issue by sphaerophoria** [Andersbakken/rtags#395]
If I create a sample file containing

```
#include <iostream>

#define TEST_DEFS \
    TEST_MACRO(one); \
    TEST_MACRO(two);

#define TEST_MACRO(__NAME__) \
    void testFunc_##__NAME__()\
    { \
        std::cout << #__NAME__ << std::endl; \
    }
    TEST_DEFS
#undef TEST_MACRO

void testFunc_three()
{
    std::cout << "three" << std::endl;
}

int main(int argc, const char *argv[])
{
    testFunc_one();
    testFunc_two();
    testFunc_three();

    return 0;
}
```

and tag it, I get the following results.
    $ rc -S test
    testFunc_three
    testFunc_three()

I believe I should also get one and two. Maybe this isn't a bug but this is how tagging systems in IDE's have resolved the same file.

**Comment by Andersbakken** [comment]
There's definitely still some issues here. It's not trivial to fix because of the data model we decided to use. I'll try to come up with something.

**Comment by sphaerophoria** [comment]
Thanks :). It is better, but as you said there is room for improvement.

**Comment by ville-h** [comment]
```
#define FUN(x) auto x() -> void {}


FUN(function_with_long_name)


auto main() -> int {
    function_with_long_name(); // rtags-find-symbol-at-point works
    func  // company completion fails
    return 0;
}
```
company completion fails for the "func" line. On the line above rtags-find-symbol-at-point nicely jumps to where the FUN macro is used so perhaps just an oversight?

**Comment by Andersbakken** [comment]
This one probably is libclang's bug actually. We don't really have much influence over how the completion results are generated.
