### ISSUE TITLE
Bash completion documentation

### ISSUE THREAD

**Issue by deepankarsharma** [Andersbakken/rtags#396]
This isnt a bug per se, but could you explain how to setup rtags-bash-completion.sh to be used by bash? I am using rtags on a ubuntu based machine.

**Comment by Andersbakken** [comment]
Just add this to your .bashrc

source /path/to/rtags/src/rtags-bash-completion.sh

After this rc and rdm should have completions.

Let me know if it works.

Anders

On Tue, Aug 11, 2015 at 10:05 AM, Deepankar Sharma <notifications@github.com
