### ISSUE TITLE
GenerateTest appears to be crash code

### ISSUE THREAD

**Issue by Mortal42** [Andersbakken/rtags#398]
Attempted to use via:
rc --generate-test ../rtags/src/IndexMessage.cpp

Causes segv due to use of NULL pointer from call to project->openSymbols(...)
This API depends on mFileMapScope which has not been set as there is no QueryJob in generateTests.

Found because the API sounded interesting, but I realize now that it's an internal test generator API.

**Comment by Andersbakken** [comment]
Thanks. Should be fixed now.
