### ISSUE TITLE
Dependency not working

### ISSUE THREAD

**Issue by hotpxl** [Andersbakken/rtags#399]
Hi.

I sent a PR #397 yesterday. I specified dependency to `popup` for MELPA. But I found out it's still not working. I still need to change the first line of every `.el` file from

    ;; blabla.el --- blabla

to

    ;;; blabla.el --- blabla

(Three semi-colons)

It's a small fix and not worth another PR. So I'm sending this fix as an issue instead.

Thanks

**Comment by hotpxl** [comment]
To be exact it still needs `company` and `auto-complete` as dependencies. But since I'm a `company` user, I don't like the idea of installing both. So I'll just let the errors fly. Probably it would be a better idea to separate them into other repositories.

**Comment by Andersbakken** [comment]
Thanks

Can you verify that this is correct?

e0c519a

Anders

**Comment by hotpxl** [comment]
I tested with a local MELPA and it works. But I'll still have to wait for the online version to update its cache. I'll open another issue if it's not solved.

**Comment by hotpxl** [comment]
Cool. It's working as expected.

**Comment by Andersbakken** [comment]
Glad to hear. Thanks.


Anders
