### ISSUE TITLE
failing to install

### ISSUE THREAD

**Issue by bardov** [Andersbakken/rtags#401]
Trying to install using the instructions, except instead of cloning with git, downloading the zip.
rct sub directory is empty.

**Comment by cslux** [comment]
Well, in that case you also need to download rc separately. After
extracting, put the content of the rc folder into the rct directory of
rtags.

See issue #371 which is about the same problem.

You can extract the content of rc directly into the rct folder read 'man
tar' for more information, on how to do that.

Regards,  Christian

**Comment by Andersbakken** [comment]
I added a link to a tarball now.
