### ISSUE TITLE
Cannot find system headers

### ISSUE THREAD

**Issue by hotpxl** [Andersbakken/rtags#404]
The problem looks like this.

I started with `rdm -vv` to show some debugging information. Before that I cleaned `.rtags` directory. I had a simple C++ file like:

    #include <cstdio>
    int main() {}

I had my `g++` symlinked. So I invoke `g++ main.cpp`. This will instruct `rdm` to index this file. Instead I got this back:

> listening /home/lyt/.rdm
> Running with 32 jobs, using args: -ferror-limit=0 -Wall -fspell-checking -Wno-unknown-warning-option
> Includepaths: -isystem /home/lyt/nix/store/mwx6w59gp3l0959a8c6bbbk3zk6ay3hb-llvm-3.6.2/lib/clang/3.6.2/include/
> Source::parse ( /usr/bin/g++-4.9 main.cpp ) => List<String>(/usr/bin/g++-4.9, main.cpp) /home/lyt/tmp/haha/
> Parsed Source(s) successfully: List<Source>(Source(/usr/bin/g++-4.9 -ferror-limit=0 -Wall -fspell-checking -Wno-unknown-> warning-option -isystem /home/lyt/nix/store/mwx6w59gp3l0959a8c6bbbk3zk6ay3hb-llvm-3.6.2/lib/clang/3.6.2/include/ /home/lyt/> tmp/haha/main.cpp Build: /home/lyt/tmp/haha/))
> Starting process for 1 4294967299 0x246f7f0
> job got index data message 1 4294967299 0x246f7f0
> [100%] 1/1 00:29:35 ~/tmp/haha/main.cpp in 5ms. (2 syms, 4 symNames, 0 includes, 1 of 1 files, symbols: 2 of 2, 0 queried) > (4/0/1ms). (priority 0)
> Jobs took 0.01s. We're using 2mb of memory.
> Output from /home/lyt/tmp/haha/main.cpp:
> CI::parse: List<String>(-ferror-limit=0, -Wall, -fspell-checking, -Wno-unknown-warning-option, -isystem, /home/lyt/nix/> store/mwx6w59gp3l0959a8c6bbbk3zk6ay3hb-llvm-3.6.2/lib/clang/3.6.2/include/, )
> 
> /home/lyt/tmp/haha/main.cpp:1:10: fatal error: 'cstdio' file not found
> CI::parse loading unit: clang -ferror-limit=0 -Wall -fspell-checking -Wno-unknown-warning-option -isystem /home/lyt/nix/> store/mwx6w59gp3l0959a8c6bbbk3zk6ay3hb-llvm-3.6.2/lib/clang/3.6.2/include/  /home/lyt/tmp/haha/main.cpp true
> couldn't create included file inclusion directive i cstdio /home/lyt/tmp/haha/main.cpp:1:1

Anyways it says it couldn't find `cstdio`, which is part of standard headers.

I built `rdm` using a `nix-shell`. The built was correct. I don't know if you have used Nix before. But the main difference it had every shared library's `RPATH` hard-coded so it will link to a specific version. Besides, it's no different than a normal build.

Wonder why it can't find system headers. Could you provide me more instructions on debugging this?

**Comment by hotpxl** [comment]
I tried looking into this directory and found nothing but vain air. I guess this might be the problem.

> Includepaths: -isystem /home/lyt/nix/store/mwx6w59gp3l0959a8c6bbbk3zk6ay3hb-llvm-3.6.2/lib/clang/3.6.2/include/

**Comment by Andersbakken** [comment]
Hi Yutian

We try to detect where the system headers for clang are based on some
heuristics in rtags/cmake/FindLibClang.cmake

You can pass another --isystem path to rdm to fix it if we detected the
wrong path. E.g.

rdm --isystem /path/to/clang/system/headers

Can you see if that works for you?

Anders

**Comment by hotpxl** [comment]
I tried `rdm` on my Mac (where it works perfectly). Now I could find the header `cstdio`, but the `cstdio` file isn't in the `Includepaths` either. So I guess this is not related to `Includepaths`?

**Comment by Andersbakken** [comment]
Well. There are some built-in includepaths in libclang so it might be that
your libclang installation has some problems. Did you build it yourself?
You should make sure to pass a prefix when you build it in and do make
install

Anders

**Comment by hotpxl** [comment]
I wonder how system header search paths are included. My guess is that indexer somehow gets all the search paths and recursively indexes the headers itself. If I'm going to do it, I'm going to runtime call `clang++ -v -E - < /dev/null` or something alike. I wonder if I could print all the search paths so I could start from there. Or is it compile time thing?

**Comment by hotpxl** [comment]
I tried building with another libclang but still failed. I built `rdm` myself but not clang.

**Comment by hotpxl** [comment]
OK. I kinda found the problem. Under complicated circumstances (like mine), I think it's necessary to enable compiler manager for real include paths. And it works (*ONLY* under Clang). G++ does not take flag `-nobuiltinc`. If you could check whether it's G++ and don't test for that flag. It would work under all circumstances.

Thanks.

**Comment by hotpxl** [comment]
Also, [this case](https://github.com/Andersbakken/rtags/blob/master/src/CompilerManager.cpp#L81) is not reachable. I think it should set `i = 1` after line 103.
