### ISSUE TITLE
Tradeoff memory consumption for faster symbol lookup

### ISSUE THREAD

**Issue by pradhanpk** [Andersbakken/rtags#408]
The symbol lookup times vary widely between consecutive runs. I don't have a more formal statement of this except the variability in the delays I notice on hitting `C-x r .`. Would it be possible to, at the cost of increased memory usage, speedup symbol lookup? Perhaps by keeping more of the symbol-lookup related datastructures in memory?

**Comment by Andersbakken** [comment]
Hi

I added a thing that hopefully speeds it up. We could maybe do something more but it will be a little trickier so if this help enough I'd like to just keep it this way. Can you check if there's a difference?

**Comment by pradhanpk** [comment]
Great! This seems to have sped up lookup considerably.

**Comment by Andersbakken** [comment]
Ah. Glad to hear. I'll close it then.

**Comment by Andersbakken** [comment]
Ah. You did :-)

Thanks

Anders

**Comment by cslux** [comment]
Also the initial start-up is now considerable faster. Previously it took quite a while to load the database of the chromium (content_shell) project which is alone 4 GB big. 

Thanks

Anders

**Comment by Andersbakken** [comment]
Glad to hear. The performance is largely dependent on the performance of
your disk.

Anders

**Comment by cslux** [comment]
> The performance is largely dependent on the performance of your disk.

Right! I'll have a SSD, disk I/O should therefore not be of any big concern.
