### ISSUE TITLE
No source found errors after recent changes

### ISSUE THREAD

**Issue by Nephyrin** [Andersbakken/rtags#409]
Sometime in the past ~24h I started getting these errors querying some files.

I tried to query this file while rdm was indexing and got a file error:
```
[ 92%] 2362/2558 18:14:17 ...
/usr/bin/rc --current-file=somefile.cpp -f somefile.cpp:595:9:
Failed to open /home/.../.rtags/_some_path_/5826/symbols somefile.cpp (2) 71
[ 92%] 2363/2558 18:14:18 ...
```

Afterwards, rdm refused to provide information about this file:
```
/usr/bin/rc --current-file=somefile.cpp -Y -l somefile.cpp:594:13:
No source found for somefile.cpp
```

Something to do with b6b86373e5f0 and querying queued files?

**Comment by pradhanpk** [comment]
I see this too. Sample output from `rdm`'s log:

    rc --current-file=/some/file/source.cpp -f /some/file/source.cpp:462:10:
    rc --current-file=/some/file/source.cpp -U /some/file/source.cpp:462:10: --symbol-info-exclude-targets --symbol-info-exclude-references
    rc --current-file=/some/file/source.cpp -F SomeSymbol --wildcard-symbol-names
    Prepared /some/file/source.cpp

where the symbol at source.cpp:462:10 is `SourceSymbol`.

**Comment by pradhanpk** [comment]
Looking through my `.emacs`'s git history, I found the change which seems to be affecting this behaviour - when `rtags-completions-timer-interval` is set to the default value of `nil`, I don't see the above issues. I had it set to `60`, which resulted in the above.

**Comment by Andersbakken** [comment]
Hi Pradhan

Ah. I think I see what's going on. Try with the latest patch.

Anders

**Comment by sphaerophoria** [comment]
Not sure if this is the same issue, but somewhere between 12e903b215e9d5edcbcc79732fbc366f6634332d and current HEAD paths started being stored as relative instead of absolute. This prevents lookups from files in vim-rtags for me.

**Comment by Andersbakken** [comment]
Hm. We did have some problems with a recent patch we put in. How does this
manifest itself? Could you explain how to reproduce easily?

Anders

**Comment by Andersbakken** [comment]
There's been some more changes in this general area. Are you still seeing this problem?

**Comment by pradhanpk** [comment]
@Andersbakken I haven't seen the issue I described. However, I did not face the original issue opened by @Nephyrin.

**Comment by Nephyrin** [comment]
I'm no longer seeing the original issue here either. Thanks!

**Comment by Andersbakken** [comment]
Glad to hear. Thanks
