### ISSUE TITLE
symbol rename error

### ISSUE THREAD

**Issue by autosquid** [Andersbakken/rtags#417]
try to rename `dataset` in the following line gives error:

```  auto datasets = bamdataset::v2::loaddatasetconfig(_config_file_batch);```

The error from rdm is:
```
Failed to make location from xxx line
```
**xxx line** is the same line where is `dataset`

**Comment by Andersbakken** [comment]
This error actually indicates that the source file in question isn't indexed. Can you make sure that you've told rdm how to build it?

**Comment by autosquid** [comment]
Thanks for your quick reply.
I use cmake in my project. 
So I first export the ```compile_commands.json``` with cmake, the load it with `rc -J`.

**Comment by Andersbakken** [comment]
Hi

Weird. Can you do this in emacs?

M-: (rtags-is-indexed) <enter>

and see what it prints? It should say t if the file is indexed.

Anders

**Comment by autosquid** [comment]
The problem disappears after I restarted rdm. So I will close this issue temporarily .

**Comment by Andersbakken** [comment]
Glad to hear. Btw, if you find a way to reproduce this kind of issue I'd
love to hear about it. I believe we have some long-standing bugs that cause
such behavior that we never seem to be able to nail down.

Anders
