### ISSUE TITLE
Why logging output is put into syslog file? 

### ISSUE THREAD

**Issue by cslux** [Andersbakken/rtags#418]
Hey Anders, 

is there a good reason why the logs are written into the /var/log/syslog file and not in a own log file, for instance in the users home directory?

Why you may ask.

The Admin wrote me a email yesterday that the syslog contains log output from `rp` (compile commands). He wasn't really amused as it was 40 MB big! :-/ He further stated that thos logs doesn't belong there, I agree with him. 

Is there already a flag available to change the destination the logs go into? 

Thanks in advance,

Christian

**Comment by Andersbakken** [comment]
Your admin is correct :-) 

I made it an opt-in feature. Thanks for the report.

**Comment by cslux** [comment]
Thanks Anders!
