### ISSUE TITLE
Selecting items in rtags symbols list splits the window repeatedly

### ISSUE THREAD

**Issue by Nephyrin** [Andersbakken/rtags#420]
If I pull up a list of symbols with e.g. `rtags-find-references` and cycle through them with `rtags-next-match` the symbols in a not-currently-open file will split the window to display the file, resulting in cycling through matches quickly filling my frame with 90 tiny windows. If the buffers are already visited, rtags simply cycles my current window between them, the more desirable behavior.

I may be overlooking a setting I can fiddle with, but a way to request rtags just navigate the current window rather than attempt to split would be awesome.

**Comment by Nephyrin** [comment]
Annd I just discovered it is in fact just using `find-file-other-window` which has crappy default behavior for me.

Sorry, carry on!

**Comment by Andersbakken** [comment]
Ah. We could probably make that a defcustom or something if desired.

Anders

**Comment by Nephyrin** [comment]
I played with my settings a bit, I think the issue is find-file-other-window's behavior is useful for e.g. helm buffers and other pop-up style tools, but for cycling through results in a list I don't want each result to use a new other-window. It seems like having the first result from a given taglist buffer use find-file-other-window, followed by re-using said window for next/prev result, would best suite my use case (which is easy enough with a defadvice)

**Comment by Andersbakken** [comment]
I think you're right. I'd welcome a patch that achieved this inside of
rtags though.

Anders
