### ISSUE TITLE
rdm to parse nmake makefiles

### ISSUE THREAD

**Issue by deuscovrigus** [Andersbakken/rtags#421]
I am wondering if there's any functionality to parse the nmake files generated by visual studio. I configured my cmake generator to be "Nmake Makefiles", however, the CMAKE_EXPORT_COMPILE_COMMANDS option is not present in the cmake gui, so i'm guessing it's unsupported.

Any suggestions?

**Comment by deuscovrigus** [comment]
Actually I just had to add the option -DCMAKE_EXPORT_COMPILE_COMMANDS=ON in the command line and it did generate a json file. However, when I start rdm and tell rc to parse the json, nothing really happens. Are nmake build files not supported?

**Comment by Andersbakken** [comment]
Hi

rdm is mostly written as a unix tool so whatever windows support we've had
has been for cygwin. That being said we would love for it work.

If you run like this:

rdm -v -v

You should see a lot of debug info about why it couldn't parse the command
lines from your compliation_database.json file. (Possibly related to paths
and slashes etc).

Be aware, if it's a big project it will flood your terminal.

Let me know what you get.

Anders

**Comment by deuscovrigus** [comment]
Hey Anders!
So I tested it with -v -v ( I actually tried just -v last night without too much success). and as you might have suspected, it's the paths in the json of the compiler:

Source::parse Nothing looks like a compiler
Source::parse ( D:develminGWbing++.exe -DINSTANTIATE_TEMPLATES -DVXL_LEGACY_ERROR_REPORTING -DVXL_WARN_DEPRECATED -DVXL_WARN_DEPRECATED_ONCE @CMakeFiles/vepl.dir/includes_CXX.rsp -O0 -o CMakeFilesvepl.dirvepl_gaussian_convolution.obj -c E:develvxlcontribtblveplvepl_gaussian_convolution.cxx ) => List<String>(D:develminGWbing++.exe, -DINSTANTIATE_TEMPLATES, -DVXL_LEGACY_ERROR_REPORTING, -DVXL_WARN_DEPRECATED, -DVXL_WARN_DEPRECATED_ONCE, @CMakeFiles/vepl.dir/includes_CXX.rsp, -O0, -o, CMakeFilesvepl.dirvepl_gaussian_convolution.obj, -c, E:develvxlcontribtblveplvepl_gaussian_convolution.cxx) E:/devel/vxl_build_unix/contrib/tbl/vepl/
Source::parse Nothing looks like a compiler

The original json entry for a minGW make file looks like this:

{
  "directory": "E:/devel/vxl_build_unix/contrib/tbl/vepl1",
  "command": "D:\\devel\\minGW\\bin\\g++.exe   -DINSTANTIATE_TEMPLATES -DVXL_LEGACY_ERROR_REPORTING -DVXL_WARN_DEPRECATED -DVXL_WARN_DEPRECATED_ONCE   @CMakeFiles/vepl1.dir/includes_CXX.rsp   -o CMakeFiles\\vepl1.dir\\vepl1_gaussian_convolution.obj -c E:\\devel\\vxl\\contrib\\tbl\\vepl1\\vepl1_gaussian_convolution.cxx",
  "file": "E:/devel/vxl/contrib/tbl/vepl1/vepl1_gaussian_convolution.cxx"
},

So then I tried replacing the \\ with / and it seems rdm doesn't like the g++.exe as a compiler

Source::parse Nothing looks like a compiler
Source::parse ( D:/devel/minGW/bin/g++.exe -DVXL_LEGACY_ERROR_REPORTING -DVXL_WARN_DEPRECATED -DVXL_WARN_DEPRECATED_ONCE @CMakeFiles/boxm.dir/includes_CXX.rsp -o CMakeFiles/boxm.dir/Templates/boxm_block+boct_tree+short.int--.obj -c E:/devel/vxl/contrib/brl/bseg/boxm/Templates/boxm_block+boct_tree+short.int--.cxx ) => List<String>(D:/devel/minGW/bin/g++.exe, -DVXL_LEGACY_ERROR_REPORTING, -DVXL_WARN_DEPRECATED, -DVXL_WARN_DEPRECATED_ONCE, @CMakeFiles/boxm.dir/includes_CXX.rsp, -o, CMakeFiles/boxm.dir/Templates/boxm_block+boct_tree+short.int--.obj, -c, E:/devel/vxl/contrib/brl/bseg/boxm/Templates/boxm_block+boct_tree+short.int--.cxx) E:/devel/vxl_build_unix/contrib/brl/bseg/boxm/
Source::parse Nothing looks like a compiler

The nmake files might be even trickier because the compiler flags are passed with forward slashes like this json entry from a visual studion nmake:

{
  "directory": "E:/devel/vxl_build/vcl",
  "command": "D:\\PROGRA~1\\MICROS~2.0\\VC\\bin\\amd64\\cl.exe  @<<
 /nologo /TP  /DWIN32 /D_WINDOWS /W3 /GR /EHsc  /D_DEBUG /MDd /Zi /Ob0 /Od /RTC1 -IE:\\devel\\vxl_build\\vcl -IE:\\devel\\vxl\\vcl -IE:\\devel\\vxl_build\\core -IE:\\devel\\vxl\\core    -DVXL_LEGACY_ERROR_REPORTING -DVXL_WARN_DEPRECATED -DVXL_WARN_DEPRECATED_ONCE /FoCMakeFiles\\vcl.dir\\vcl_cmath.obj /FdCMakeFiles\\vcl.dir\\ /FS -c E:\\devel\\vxl\\vcl\\vcl_cmath.cxx
<<",
  "file": "E:/devel/vxl/vcl/vcl_cmath.cxx"
},

I think rdm needs to be acquainted with these .exe compilers? I know I tried scanning Cygwin builds of my project and it worked, presumably because the compiler was simply g++ not g++.exe. Am I guessing right?

Thanks again ! You guys are the best, I still can't get over how well rtags works on my unix/ OS X box. Now I never have to leave emacs again haha.

**Comment by Andersbakken** [comment]
Hi

Sorry about the delay. RTags definitely would need some clever handling for
this to work. I think it would take quite a bit more than just tolerating
.exe files as compilers. We kinda require stat(2) to say that it's a file
and that it's executable and all of our path handling assumes that absolute
paths start with a /

I think cygwin is the way to go for RTags on Windows. We certainly wouldn't
mind contributions to make it all work but I since I don't really have
access to a windows machine I doubt I will be adding support myself for all
of this.

Anders

**Comment by deuscovrigus** [comment]
Sounds good thanks for looking into this! My main beef is specific to my needs, i.e. the project that I'm working on has poor cygwin support, although it does build on OS X and linux. I think I got rtags to parse the json's in cygwin so I'll start there.

Thanks again!

**Comment by fourier** [comment]
Another question, has anybody able to compile and run rtags on Windows with MinGW ? Just to understand if it is worth it.

**Comment by jhanssen** [comment]
We assume Posix so that's unlikely to work. There are people who have used it with Cygwin though.

**Comment by cslux** [comment]
@fourier @jhanssen 
Well I didn't tried it with MinGW yet, but I made some tests on cygwin, and it turned out, it doesn't work. You can compile rtags with gcc on cygwin but rtags will than fail to parse, if you, e.g., want to parse rtags, as rtags uses TLS. If you compile rtags right a way with clang on cygwin you will encounter the same error (See my post https://github.com/Andersbakken/rtags/issues/389#issuecomment-146814213).

**Comment by fourier** [comment]
Thanks @jhanssen @cslux
