### ISSUE TITLE
emacs freezes when using rtags-start-process-maybe

### ISSUE THREAD

**Issue by duud** [Andersbakken/rtags#424]
I hacked quick eldoc support for rtags in my init.el

```
(defun my-rtags-eldoc ()
  (when (and (not (nth 4 (syntax-ppss))) (thing-at-point 'symbol t))
    (let ((doc (rtags-get-summary-text)))
      (and doc (replace-regexp-in-string "{.*" ""
                                         (replace-regexp-in-string "[ \t\n]+" " "
                                                                   (replace-regexp-in-string "\n" "" doc)))))))

 (setq-local eldoc-documentation-function #'my-rtags-eldoc)
```
This works ok, but if I modify the buffer and place the cursor on any symbol, rtags starts reparsing the buffer and emacs freezes.
However it doesn't freeze if I use pipes for process-communication.

```
     (let ((process-connection-type nil))  ;; use pipes
        (setq rtags-process (start-process-shell-command
                             "RTags"	     ;process name
                             "*rdm*"	     ;buffer
                             (rtags-command)))) ;command
```
This prevents also freezes in other situations when starting rdm with rtags-start-process-maybe.

**Comment by Andersbakken** [comment]
Hm. I'm not entirely sure why this would be the case but I added a
defcustom you can set:

rtags-rdm-process-use-pipe

Anders

**Comment by Andersbakken** [comment]
The eldoc thing sounds cool. I might try to put something in for that.

Anders

**Comment by velkyel** [comment]
eldoc support would be nice anyway
