### ISSUE TITLE
rtags.el rename-symbol locates wrong files

### ISSUE THREAD

**Issue by jmalmari** [Andersbakken/rtags#430]
Hello!

Function *rtags-rename-symbol* fails to rename symbols. I have a project directory like so:

`src/file.cpp`

When trying to rename symbol in `file.cpp`, *rdm* refers to the file as `src/file.cpp`. My current directory is `src`, and eventually *rtags.el* tries to rename a file named `src/src/file.cpp` which doesn't exist.

Related code line: https://github.com/Andersbakken/rtags/blob/master/src/rtags.el#L1374

On first run, it creates a new buffer in the background (instead of using the correct one) with *find-file-noselect*. On subsequent runs, the invalid buffer already exists so *find-buffer-visiting* returns it but since there's no existing file behind the buffer the operation fails with message:

    Rename gone awry. Refusing to rename nil (src/src/file.cpp:1:1:) to newname

**Comment by Andersbakken** [comment]
Ah. I think I just broke this last night. I believe the b69e664 should take
care of it. Can you check?

Anders

**Comment by jmalmari** [comment]
Fix confirmed. Thanks!

**Comment by Andersbakken** [comment]
Glad to hear. Thanks for the report.

Anders
