### ISSUE TITLE
Problem with private class members

### ISSUE THREAD

**Issue by happycorsair** [Andersbakken/rtags#431]
Hello, rtags-developers!
Thank you for your great job, I believe that rtags is on of the best goodies for C++ programming in Emacs. It works like a charm together with Company-mode.

Unfortunately, I've found a little problem with autocompletion of private class members.

Let me show the way to reproduce it:
test.h:
```c++
namespace nm_1 {
    class Foo {
    private:
        void method_private();
    public:
        void method_public();
    };
}
```
test:cpp:
```c++
#include "test.h"

namespace nm_1 {
    // rtags failes to complete this function after ::
    void Foo::method_private() {
        2 + 3;
    }
    // rtags completes this function after ::
    void Foo::method_public() {
        3 + 2;
    }
}
```
Is this issue simple to fix?
Thanks in advance!

My environment:
Arch Linux, Emacs 24.5.1, Clang 3.6.2

**Comment by Andersbakken** [comment]
Hi

Glad to hear you like it. Well. It seems we can solve this but it will come
at the cost of private functions being available to completed in different
contexts too.

I guess that probably isn't really a problem though so I'll make the change.

Thanks for the report.

Anders

**Comment by happycorsair** [comment]
Hi, @Andersbakken 
Thank you for such a quick response!

This approach seems not to be a good one, it's gonna bring just more problems, if it's straightforward implemented. As far as I understand the problem, we'll have (for example) all private stuff from std classes just as unuseful garbage.

By the way, is it possible to explicitly write access modifier in rtags output?

**Comment by Andersbakken** [comment]
I made it an opt-in option instead. Clang doesn't seem to give a different
priority or anything else to determine what context the completion happens
in. E.g.

int foo()
{
   A a;
   a.privFun<complete>
}

vs

int A::privFunc<complete>

So I don't think there's much I can do about it.

If you want the behavior you can run rdm with --completions-no-filter

otherwise it's back to the old behavior.

Anders
