### ISSUE TITLE
emacs+rtags freezes when trying to visit some remote location with tramp

### ISSUE THREAD

**Issue by Mafeuser** [Andersbakken/rtags#432]
I'm using

emacs 24.5
rtags:17bdbd40a25722709efe921bf1b2f9fa5046a3d4

rtags is working fine, BUT when I try to visit some remote location through tramp (for example /scp:remote.host.domain:/), emacs freezes at password prompt.

Of course, in case rtags is not initialized, freeze does not occur.

Following is part of backtrace around rtags invocation:
  ....
  ....
  tramp-file-name-handler(file-directory-p #("/scp:remote.host.domain:/" 1 4 (tramp-default t)))
  file-directory-p(#("/scp:remote.host.domain:/" 1 4 (tramp-default t)))
  (and (not (eq (current-buffer) rtags-last-update-current-project-buffer)) (file-directory-p default-directory))
  (if (and (not (eq (current-buffer) rtags-last-update-current-project-buffer)) (file-directory-p default-directory)) (progn (setq rtags-last-update-current-project-buffer (current-buffer)) (let* ((rc (rtags-executable-find "rc")) (path (or (buffer-file-name) default-directory)) (arguments (list "-T" path "--diagnose" path "--silent-query"))) (if rc (progn (apply (function start-process) "rtags-update-current-project" nil rc arguments))))))
  rtags-update-current-project()
  apply(rtags-update-current-project nil)
  byte-code("r\301\302H\303H\"\210)\301\207" [timer apply 5 6] 4)
  timer-event-handler([t 0 0 500000 nil rtags-update-current-project nil idle 0])
  read-string(#("Password for /scp:remote.host.domain: " 14 17 (tramp-default t)) nil t nil)
  read-passwd(#("Password for /scp:remote.host.domain: " 14 17 (tramp-default t)))
  password-read(#("Password for /scp:remote.host.domain: " 14 17 (tramp-default t)) #("/scp:remote.host.domain:" 1 4 (tramp-default t)))
  tramp-read-passwd(#<process *tramp/scp remote.host.domain*>)
  tramp-action-password(#<process *tramp/scp remote.host.domain*> [#("scp" 0 3 (tramp-default t)) nil "remote.host.domain" "" nil])
  tramp-process-one-action(#<process *tramp/scp remote.host.domain*> [#("scp" 0 3 (tramp-default t)) nil "remote.host.domain" "" nil] ((tramp-login-prompt-regexp tramp-action-login) (tramp-password-prompt-regexp tramp-action-password) (tramp-wrong-passwd-regexp tramp-action-permission-denied) (shell-prompt-pattern tramp-action-succeed) (tramp-shell-prompt-pattern tramp-action-succeed) (tramp-yesno-prompt-regexp tramp-action-yesno) (tramp-yn-prompt-regexp tramp-action-yn) (tramp-terminal-prompt-regexp tramp-action-terminal) (tramp-process-alive-regexp tramp-action-process-alive)))
  ....
  ....

**Comment by Andersbakken** [comment]
I hope this will fix it. Can you check? We're trying to check that files aren't tramp-tramp-file-p before processing but there's a timer involved which I think could make this happen regardless. Now that should be fixed. Let me know what happens.

**Comment by Mafeuser** [comment]
Hi Anders

Fix works!

best regards

**Comment by Andersbakken** [comment]
Thanks. Glad to hear.

Anders
