### ISSUE TITLE
Could NOT find OpenSSL

### ISSUE THREAD

**Issue by cyboflash** [Andersbakken/rtags#433]
I've followed these directions:
```
$ mkdir build
$ cd build
$ cmake ..
$ make
$ make install
```

and gotten the following error during ```cmake ..```

```
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindOpenSSL.cmake:313 (find_package_handle_standard_args)
  src/rct/rct.cmake:77 (find_package)
  src/rct/CMakeLists.txt:2 (include)
```

Here is the output of 
```
$ which openssl
$ /usr/bin/openssl
```

What could be the issue?

**Comment by aaptel** [comment]
You probably need the openssl development librairies for your distribution. It's probably called libssl-dev or libopenssl-devel or something similar. Once you've done that `pkg-config --list-all | grep -i ssl` should print some stuff cmake should pass that step (and fail somewhere else, maybe :)

**Comment by cyboflash** [comment]
You are correct. Running ```apt-get install libssl-dev``` solved the issue.
