### ISSUE TITLE
rtags to serve independant projects in two emacs processes.

### ISSUE THREAD

**Issue by Mafeuser** [Andersbakken/rtags#434]
Hallo rtags team.

First of all, thank You for rtags.
It gives outstanding quality to C++ emacs IDE. I'm running it since ~4 months and find it very responsive and accurate.

Client/Server model is very good idea.

There is my use-case I've just started having trouble with though:

- I'm running emacs process (emacs1) that handles project1.
- I'm starting another emacs process (emacs2) in parallel to start handling project2, which is independent to project1.
- both emacs processes query their rtags projects' databases independently.

problem:
rtags does not track emacs1 wants to query project1 database and emacs2 wants to query project2, I mean queries are intermixed in the way emacs1 sometimes gets response from project2 and emacs2 sometimes gets resonse from project1.

I have impression, that earlier versions of rtags did the job.

once more thank You for rtags.

**Comment by Andersbakken** [comment]
Sorry about the delay. Can you easily reproduce this? Generally rtags
command tries to update the project to be the right one in the process but
there is still a concept of current project. Could you give me some easy
steps to reproduce?

Anders

**Comment by Mafeuser** [comment]
Hallo Anders.

Yes, I have one more important detail.
My impression comes from the fact that current project is not updated when search starts from dired buffer.

To ease the description, let's assume that SomeFunc symbol exists both in project1 and in project2.

reproduction:

I'm working with emacs1/project1.
Now I want to search SomeFunc from project2, so I'm going to emacs2, then revisiting project2 base directory dired buffer. Then invoking (rtags-find-symbol ..) to find SomeFunc. I end up in project1's SomeFunc. It is because: when in dired buffer, (rtags-find-symbol..) does not update current project.

Problem does not occur if I invoked (rtags-find-symbol ..) from some *.cpp/*.h file of project2.

I realize that adding extra code to handle dired buffers might complicate rtags unnecessarily, so maybe I just should change my habit and always start the search from rtags indexed file, not from dired buffer.

regards

**Comment by Andersbakken** [comment]
Ah. I think I understand what's going on then. It should be fixed now.

Anders

**Comment by Mafeuser** [comment]
Fix does the job!

thank You and regards

**Comment by Andersbakken** [comment]
Glad to hear. Thanks for the report.

Anders
