### ISSUE TITLE
feature request: current function name in modeline.

### ISSUE THREAD

**Issue by Mafeuser** [Andersbakken/rtags#435]
Hallo rtags team.

I'm using which-function-mode to display in modeline, the C++ function name the cursor is currently within.
Those that use it, know that this method is not accurate though.

Thus the question if rtags could to the job much better and easier?

regards

**Comment by Andersbakken** [comment]
We do actually kinda have something like that.

I do this:

(setq rtags-track-container t)

and then

(add-hook 'find-file-hook (lambda ()
                            (setq header-line-format (and (rtags-is-indexed)
                                                          '(:eval
rtags-cached-current-container)))))

By default we will update the current container every .5 seconds (after
cursor has moved) since it's not free to do. You can tune the interval by
setting rtags-container-timer-interval

Anders

**Comment by Mafeuser** [comment]
This works indeed :)

thank You very much!

**Comment by Andersbakken** [comment]
My pleasure.

Anders

**Comment by ramblehead** [comment]
I have been using Anders' solution for "which-function-mode" (see above) for a while now. I found it quite useful. However, there were a few issues with using that code as it is, such as incorrect display in multiple windows, adjacent windows headers might look like one long line, and inconsistent face.

Here is my attempt to address those issues:

```lisp
(cl-defun vr-c++-header-line (&optional
                              (header-line-trim-indicator "\x203a")
                              (header-line-beginning-indicator " "))
  (propertize
   (let* ((header-string (concat header-line-beginning-indicator
                                 rtags-cached-current-container))
          (header-string-width (string-width header-string))
          (header-filler-width (- (window-total-width) header-string-width)))
     (if (< header-filler-width 0)
         (concat (substring header-string
                            0 (- (window-total-width)
                                 (string-width header-line-trim-indicator)))
                 header-line-trim-indicator)
       (concat header-string (make-string header-filler-width ?\ ))))
   'face 'mode-line-inactive))

(make-local-variable 'rtags-cached-current-container)
(setq rtags-track-container t)
(add-hook 'find-file-hook
          (lambda ()
            (when (rtags-is-indexed)
              (set (make-local-variable 'header-line-format)
                   '(:eval (vr-c++-header-line)))))
          nil t)
```

I hope, it might be useful useful to someone.

Victor.
