### ISSUE TITLE
`Unknown damned auto` error on `reinterpret_cast()` expressions

### ISSUE THREAD

**Issue by sergei-dyshel** [Andersbakken/rtags#438]
I'm getting this error on statements like this
```c++
auto a = reinterpret_cast<const struct some_struct *>(some_ptr);
```

The type is pretty easy deductable, isn't it?

**Comment by Andersbakken** [comment]
It is, I just needed to handle it. Should work now. For a look at the worst code in all of Rtags just check out RTags::resolveAuto in RTagsClang.cpp

**Comment by sergei-dyshel** [comment]
Thanks! Works great now!
