### ISSUE TITLE
A few minor issues

### ISSUE THREAD

**Issue by ramblehead** [Andersbakken/rtags#439]
I have recently installed ```rtags``` for C++11 source code navigation in Emacs, which works quite well. Digging a bit dipper into ```rtags``` capabilities revealed a few minor issues.

Could someone guide me through the troubleshooting, or point me to the right settings if I am missing something:

1. ```rtags-imenu``` does not use ```ido``` - just conventional Emacs tab-completion (e.g. like ```M-x``` without ```smex```)
2. ```rtags-rename-symbol``` does not rename symbol, producing the following message: ```Opened 0 new files and made 0 modifications```
3. ```*RTags Raw*``` buffer is always empty. What should it display?
4. At the moment I am running ```rdm``` in ```*shell*``` buffer without ```&``` to see its output. What is "the right" way to start ```rdm``` and observe its output (in Linux).
5. ```Unknown damned auto!!! VarDecl c buf...``` at ```auto buf = reinterpret_cast<const char*>(base::header)```, where ```base::header``` is ```uint8_t header[6]```.

I tried running ```rtags``` with the default Emacs settings (except ```popup.el```, which seems to be required by ```rtags```) to eliminate possibility of interfering with other packages. The issues were still the same.

**Comment by cslux** [comment]
Hey,

I can only give some input to your question 2/4/5.

2)
> rtags-rename-symbol does not rename symbol, producing the following message: Opened 0 new files and made 0 modifications

Seems like it stopped working, I opened an issue for this #440.

4)
> At the moment I am running rdm in *shell* buffer without & to see its output. What is "the right" way to start rdm and observe its output (in Linux).

Add something like that to your init file.

``` emacs-lisp
(defun my-c++-mode-hook ()
    (rtags-start-process-unless-running))
(add-hook 'c++-mode-hook 'my-c++-mode-hook)
```

I'll live my hole rtags config here in case it can help someone.
``` emacs-lisp
(setq rtags-completions-enabled t
      rtags-display-current-error-as-tooltip t
      rtags-autostart-diagnostics t
      rtags-show-containing-function t
      rtags-track-container t)

(defun my-rtags-setup ()
  (define-key c-mode-base-map (kbd "M-.") 'rtags-find-symbol-at-point)
  (define-key c-mode-base-map (kbd "M-,") 'rtags-find-references-at-point)
  (define-key c-mode-base-map (kbd "M-;") 'rtags-find-file)
  (define-key c-mode-base-map (kbd "C-.") 'rtags-find-symbol)
  (define-key c-mode-base-map (kbd "C-,") 'rtags-find-references)
  (define-key c-mode-base-map (kbd "C-<") 'rtags-find-virtuals-at-point)
  (define-key c-mode-base-map (kbd "M-s") 'rtags-imenu)
  (define-key c-mode-base-map (kbd "C-c r i") 'rtags-print-symbol-info)
  (define-key c-mode-base-map (kbd "M-[") 'rtags-location-stack-back)
  (define-key c-mode-base-map (kbd "M-]") 'rtags-location-stack-forward)
  (define-key c-mode-base-map (kbd "M-n") 'rtags-next-match)
  (define-key c-mode-base-map (kbd "M-p") 'rtags-previous-match)

  (define-key c++-mode-map (kbd "M-.") 'rtags-find-symbol-at-point)
  (define-key c++-mode-map (kbd "M-,") 'rtags-find-references-at-point)
  (define-key c++-mode-map (kbd "M-;") 'rtags-find-file)
  (define-key c++-mode-map (kbd "C-.") 'rtags-find-symbol)
  (define-key c++-mode-map (kbd "C-,") 'rtags-find-references)
  (define-key c++-mode-map (kbd "C-<") 'rtags-find-virtuals-at-point)
  (define-key c++-mode-map (kbd "M-s") 'rtags-imenu)
  (define-key c++-mode-map (kbd "C-c r i") 'rtags-print-symbol-info)
  (define-key c++-mode-map (kbd "M-[") 'rtags-location-stack-back)
  (define-key c++-mode-map (kbd "M-]") 'rtags-location-stack-forward)
  (define-key c++-mode-map (kbd "M-n") 'rtags-next-match)
  (define-key c++-mode-map (kbd "M-p") 'rtags-previous-match)

  (define-key rtags-mode-map (kbd "n") 'rtags-next-match)
  (define-key rtags-mode-map (kbd "p") 'rtags-next-prev-match)
  (rtags-start-process-unless-running)
  (which-function-mode t)
  (add-hook 'find-file-hook
	  (lambda ()
	    (setq header-line-format
		  (and (rtags-is-indexed)
		       '(:eval rtags-cached-current-container))))))
```

5)
> Unknown damned auto!!! VarDecl c buf... at auto buf = reinterpret_cast<const char*>(base::header), where base::header is uint8_t header[6].

This issue has been reported too, lets see what @Andersbakken says. But either its a missing clang feature to get the type or it has yet not been added to https://github.com/Andersbakken/rtags/blob/master/src/RTagsClang.cpp#L178

I'm curios to way

**Comment by Andersbakken** [comment]
Hi

1)

It used to call ido-completing-read directly but I think someone wanted to
be able to use helm instead of ido so at this point it's just calling
completing-read. The way to get it to use ido (this is how I run it) is to
use something like https://github.com/DarwinAwardWinner/ido-ubiquitous
which is excellent for all sorts of other things as well.

2)
This should be fixed now. Thanks for the report.

3)
It's really there only for the rare occasions when we get diagnostics that
are too large to fit in one read and even then only temporarily. The buffer
can safely be ignored.

4)
I personally run rdm in a terminal but I think Christian's suggestion is
the most seamless for most people.

5)
I will try to fix that one. Sadly there's no real API in libclang to
determine the underlying type for autos so I've had to write some nasty
code to try to determine it (see RTags::resolveAuto for details).

regards

Anders

**Comment by ramblehead** [comment]
Anders and Chris,

Thank you for your help and very quick response!

All mentioned issues are now resolved. With ido-ubiquitous, there are more "ido" than even ever hoped for :)

Here are my settings additionally to Chris's for further reference (default key bindings and error colours):

```elisp
(rtags-enable-standard-keybindings)
(custom-set-faces
 '(rtags-errline ((((class color)) (:background "#ef8990"))))
 '(rtags-fixitline ((((class color)) (:background "#ecc5a8"))))
 '(rtags-warnline ((((class color)) (:background "#efdd6f"))))
 '(rtags-skippedline ((((class color)) (:background "#34ef85")))))
```
Kind regards,
Victor.

**Comment by Andersbakken** [comment]
Sounds good. Let me know if you find other issues.

Anders
