### ISSUE TITLE
rtags-rename-symbol does not work "Opened 0 new files and made 0 modifications"

### ISSUE THREAD

**Issue by cslux** [Andersbakken/rtags#440]
Hey Anders,

`rtags-rename-symbol` does not work anymore, this issue is also mentioned in #439.

**Comment by Andersbakken** [comment]
This should work again now. Thanks for the report.

**Comment by cslux** [comment]
Works again, thanks!

**Comment by Andersbakken** [comment]
My pleasure.

Anders
