### ISSUE TITLE
emacs completions are truncated based on window width

### ISSUE THREAD

**Issue by tom-seddon** [Andersbakken/rtags#442]
The expansion inserted into the buffer is limited by the window width. This truncation is fine for the scrolling list, but the full expansion should always be inserted into the buffer.

For example, if I try to expand a call to `task_get_exception_ports` (an OS X function with a particularly lengthy prototype - it just happened to be the call that was bothering me just now when I decided to finally figure out what the problem might be), I get this, because my window is 100-odd chars wide.

    task_get_exception_ports(task_t task, exception_mask_t exception_m<...>)

But it should be inserting a full expansion, more like this:

    task_get_exception_ports(task_t task, exception_mask_t exception_mask, exception_mask_array_t masks, mach_msg_type_number_t *masksCnt, exception_handler_array_t old_handlers, exception_behavior_array_t old_behaviors, exception_flavor_array_t old_flavors);

This is even currently annoying to work around! - because once the truncated expansion has been inserted, you can't use C-x r . to visit the prototype to copy and paste it! The expansion isn't valid C++, so you have to delete the parameters list before you can do this.

Thanks,

--Tom

**Comment by Andersbakken** [comment]
Hi Tom

I see. I'm assuming this is with company-mode. I think my last commit
should fix it. Can you check?

Anders

**Comment by Andersbakken** [comment]
Please reopen if you can still reproduce. Thanks for the report.

Anders

**Comment by tom-seddon** [comment]
Yes, that's fixed it. Thanks :)

--Tom

**Comment by Andersbakken** [comment]
Glad to hear. My pleasure.

Anders
