### ISSUE TITLE
Feature request: Automatic reloading of compilation database

### ISSUE THREAD

**Issue by Hylen** [Andersbakken/rtags#445]
I find that I go to a terminal and reload the database with a rc -J several times a day. It would be convenient to have RTags reload the compilation database automatically. It seems pretty straightforward to implement such a feature given FileSystemWatcher, and it could be a configurable feature.

**Comment by Andersbakken** [comment]
I think that's a good idea. I will look into adding something.

**Comment by Andersbakken** [comment]
I think it should work now. Can you check? It also removes files that no longer are present in the compile_commands.json file after the file being modified (as well as adding new ones).

**Comment by Hylen** [comment]
Sorry for the late answer. I've only been using it at home so far, because I haven't had time to configure my environment at work yet. Tomorrow I will update rtags at work and start testing it out for real.

That was fast and nice work by the way. Thanks a lot for this patch, and for the rest of rtags, it really makes C++ development in emacs much nicer.

**Comment by Andersbakken** [comment]
Thanks. My pleasure.

Anders
