### ISSUE TITLE
rtags requires popup twice

### ISSUE THREAD

**Issue by tom-seddon** [Andersbakken/rtags#446]
rtags.el requires popup in two places:

    (require 'popup)

    (defconst rtags-popup-available (require 'popup nil t))

I got rid of the first one (since I don't have popup) and... it seems to work! But which one is supposed to be there?

(If popup is a mandatory dependency, I think this should be mentioned in the readme.)

Thanks,

--Tom

**Comment by Andersbakken** [comment]
Hi Tom

It's not really required. I've fixed it now. Thanks for the report.

Anders
