### ISSUE TITLE
rtags-taglist freezes

### ISSUE THREAD

**Issue by Mafeuser** [Andersbakken/rtags#448]
Hallo rtags team.

C-r-T in some rtags indexed *.cpp file freezes emacs endlessly.

rdm console displays following message (does it matter?):
/usr/local/bin/rc --current-file=/home/user/myProj/ -F --cursor-kind --display-name --no-context
Failed to open /home/user/.rtags/_home_user_myProj_/0/symnames (2) 71

I'm using emacs.24.5.1 + rtags:402b43d, but I experienced the same problem when rtags:0caca3b was used, so the problem is not caused by some recent changes.

quit relinquishes the freeze and leads to the following:

Debugger entered--Lisp error: (quit)
  call-process("/usr/local/bin/rc" nil (t nil) nil "--current-file=/home/user/myProj/" "-F" "--cursor-kind" "--display-name" "--no-context")
  apply(call-process "/usr/local/bin/rc" nil (t nil) nil ("--current-file=/home/user/myProj/" "-F" "--cursor-kind" "--display-name" "--no-context"))
  (cond ((and unsaved async) (let ((proc (apply (function start-process) "rc" (current-buffer) rc arguments))) (save-current-buffer (set-buffer unsaved) (save-restriction (widen) (process-send-region proc (point-min) (point-max)))) proc)) (async (apply (function start-process) "rc" (current-buffer) rc arguments)) ((and unsaved (or (buffer-modified-p unsaved) (not (buffer-file-name unsaved)))) (let ((output-buffer (current-buffer))) (save-current-buffer (set-buffer unsaved) (save-restriction (widen) (apply (function call-process-region) (point-min) (point-max) rc nil output-buffer nil arguments) nil)))) (unsaved (apply (function call-process) rc (buffer-file-name unsaved) output nil arguments) nil) (t (apply (function call-process) rc nil output nil arguments) nil))
  (let ((proc (cond ((and unsaved async) (let ((proc ...)) (save-current-buffer (set-buffer unsaved) (save-restriction ... ...)) proc)) (async (apply (function start-process) "rc" (current-buffer) rc arguments)) ((and unsaved (or (buffer-modified-p unsaved) (not ...))) (let ((output-buffer ...)) (save-current-buffer (set-buffer unsaved) (save-restriction ... ... nil)))) (unsaved (apply (function call-process) rc (buffer-file-name unsaved) output nil arguments) nil) (t (apply (function call-process) rc nil output nil arguments) nil)))) (if proc (progn (set-process-query-on-exit-flag proc nil) (set-process-filter proc (car async)) (set-process-sentinel proc (cdr async))) (goto-char (point-min)) (and (cond ((looking-at "Can't seem to connect to server") (erase-buffer) (if noerror nil (message "Can't seem to connect to server. Is rdm running?")) nil) ((looking-at "Project loading") (erase-buffer) (message "Project loading...") t) (t)) rtags-autostart-diagnostics (rtags-diagnostics))))
  (if (not rc) (if noerror nil (error "Can't find rc")) (if (and async (not (consp async))) (progn (error "Invalid argument. async must be a cons or nil"))) (setq arguments (rtags-remove-keyword-params arguments)) (setq arguments (cl-remove-if (quote (lambda (arg) (not arg))) arguments)) (if path-filter (progn (setq arguments (cons (concat "--path-filter=" path-filter) arguments)) (if path-filter-regex (progn (setq arguments (cons "-Z" arguments)))))) (if (and unsaved (buffer-file-name unsaved)) (progn (setq arguments (cons (format "--unsaved-file=%s:%d" (buffer-file-name unsaved) (save-current-buffer (set-buffer unsaved) (rtags-buffer-size))) arguments)))) (if silent-query (progn (setq arguments (cons "--silent-query" arguments)))) (if range-filter (progn (setq arguments (cons (format "--range-filter=%d-%d" (or range-min (rtags-offset ...)) (or range-max (rtags-offset ...))) arguments)))) (if (or timeout rtags-timeout) (progn (setq arguments (cons (format "--timeout=%d" (or timeout rtags-timeout)) arguments)))) (if (and rtags-show-containing-function (not (member "-N" arguments))) (progn (setq arguments (cons "-o" arguments)))) (cond ((stringp path) (setq arguments (cons (concat "--current-file=" path) arguments))) (path nil) (default-directory (setq arguments (cons (concat "--current-file=" default-directory) arguments))) (t nil)) (if rtags-rc-log-enabled (progn (rtags-log (concat rc " " (rtags-combine-strings arguments))))) (let ((proc (cond ((and unsaved async) (let (...) (save-current-buffer ... ...) proc)) (async (apply (function start-process) "rc" (current-buffer) rc arguments)) ((and unsaved (or ... ...)) (let (...) (save-current-buffer ... ...))) (unsaved (apply (function call-process) rc (buffer-file-name unsaved) output nil arguments) nil) (t (apply (function call-process) rc nil output nil arguments) nil)))) (if proc (progn (set-process-query-on-exit-flag proc nil) (set-process-filter proc (car async)) (set-process-sentinel proc (cdr async))) (goto-char (point-min)) (and (cond ((looking-at "Can't seem to connect to server") (erase-buffer) (if noerror nil (message "Can't seem to connect to server. Is rdm running?")) nil) ((looking-at "Project loading") (erase-buffer) (message "Project loading...") t) (t)) rtags-autostart-diagnostics (rtags-diagnostics)))) (or async (> (point-max) (point-min))))
  (let ((rc (rtags-executable-find "rc")) proc) (if (not rc) (if noerror nil (error "Can't find rc")) (if (and async (not (consp async))) (progn (error "Invalid argument. async must be a cons or nil"))) (setq arguments (rtags-remove-keyword-params arguments)) (setq arguments (cl-remove-if (quote (lambda (arg) (not arg))) arguments)) (if path-filter (progn (setq arguments (cons (concat "--path-filter=" path-filter) arguments)) (if path-filter-regex (progn (setq arguments (cons "-Z" arguments)))))) (if (and unsaved (buffer-file-name unsaved)) (progn (setq arguments (cons (format "--unsaved-file=%s:%d" (buffer-file-name unsaved) (save-current-buffer ... ...)) arguments)))) (if silent-query (progn (setq arguments (cons "--silent-query" arguments)))) (if range-filter (progn (setq arguments (cons (format "--range-filter=%d-%d" (or range-min ...) (or range-max ...)) arguments)))) (if (or timeout rtags-timeout) (progn (setq arguments (cons (format "--timeout=%d" (or timeout rtags-timeout)) arguments)))) (if (and rtags-show-containing-function (not (member "-N" arguments))) (progn (setq arguments (cons "-o" arguments)))) (cond ((stringp path) (setq arguments (cons (concat "--current-file=" path) arguments))) (path nil) (default-directory (setq arguments (cons (concat "--current-file=" default-directory) arguments))) (t nil)) (if rtags-rc-log-enabled (progn (rtags-log (concat rc " " (rtags-combine-strings arguments))))) (let ((proc (cond ((and unsaved async) (let ... ... proc)) (async (apply ... "rc" ... rc arguments)) ((and unsaved ...) (let ... ...)) (unsaved (apply ... rc ... output nil arguments) nil) (t (apply ... rc nil output nil arguments) nil)))) (if proc (progn (set-process-query-on-exit-flag proc nil) (set-process-filter proc (car async)) (set-process-sentinel proc (cdr async))) (goto-char (point-min)) (and (cond ((looking-at "Can't seem to connect to server") (erase-buffer) (if noerror nil ...) nil) ((looking-at "Project loading") (erase-buffer) (message "Project loading...") t) (t)) rtags-autostart-diagnostics (rtags-diagnostics)))) (or async (> (point-max) (point-min)))))
  (save-excursion (let ((rc (rtags-executable-find "rc")) proc) (if (not rc) (if noerror nil (error "Can't find rc")) (if (and async (not (consp async))) (progn (error "Invalid argument. async must be a cons or nil"))) (setq arguments (rtags-remove-keyword-params arguments)) (setq arguments (cl-remove-if (quote (lambda (arg) (not arg))) arguments)) (if path-filter (progn (setq arguments (cons (concat "--path-filter=" path-filter) arguments)) (if path-filter-regex (progn (setq arguments ...))))) (if (and unsaved (buffer-file-name unsaved)) (progn (setq arguments (cons (format "--unsaved-file=%s:%d" ... ...) arguments)))) (if silent-query (progn (setq arguments (cons "--silent-query" arguments)))) (if range-filter (progn (setq arguments (cons (format "--range-filter=%d-%d" ... ...) arguments)))) (if (or timeout rtags-timeout) (progn (setq arguments (cons (format "--timeout=%d" ...) arguments)))) (if (and rtags-show-containing-function (not (member "-N" arguments))) (progn (setq arguments (cons "-o" arguments)))) (cond ((stringp path) (setq arguments (cons (concat "--current-file=" path) arguments))) (path nil) (default-directory (setq arguments (cons (concat "--current-file=" default-directory) arguments))) (t nil)) (if rtags-rc-log-enabled (progn (rtags-log (concat rc " " (rtags-combine-strings arguments))))) (let ((proc (cond (... ...) (async ...) (... ...) (unsaved ... nil) (t ... nil)))) (if proc (progn (set-process-query-on-exit-flag proc nil) (set-process-filter proc (car async)) (set-process-sentinel proc (cdr async))) (goto-char (point-min)) (and (cond (... ... ... nil) (... ... ... t) (t)) rtags-autostart-diagnostics (rtags-diagnostics)))) (or async (> (point-max) (point-min))))))
  (let* ((path (car (cdr (or (plist-member arguments (quote :path)) (list nil (buffer-file-name)))))) (unsaved (car (cdr (plist-member arguments (quote :unsaved))))) (async (car (cdr (plist-member arguments (quote :async))))) (path-filter (car (cdr (plist-member arguments (quote :path-filter))))) (path-filter-regex (car (cdr (plist-member arguments (quote :path-filter-regex))))) (range-filter (car (cdr (plist-member arguments (quote :range-filter))))) (output (car (cdr (or (plist-member arguments (quote :output)) (list nil (list t nil)))))) (range-min (car (cdr (plist-member arguments (quote :range-min))))) (range-max (car (cdr (plist-member arguments (quote :range-max))))) (noerror (car (cdr (plist-member arguments (quote :noerror))))) (timeout (car (cdr (plist-member arguments (quote :timeout))))) (silent-query (car (cdr (plist-member arguments (quote :silent-query)))))) (save-excursion (let ((rc (rtags-executable-find "rc")) proc) (if (not rc) (if noerror nil (error "Can't find rc")) (if (and async (not (consp async))) (progn (error "Invalid argument. async must be a cons or nil"))) (setq arguments (rtags-remove-keyword-params arguments)) (setq arguments (cl-remove-if (quote (lambda ... ...)) arguments)) (if path-filter (progn (setq arguments (cons ... arguments)) (if path-filter-regex (progn ...)))) (if (and unsaved (buffer-file-name unsaved)) (progn (setq arguments (cons ... arguments)))) (if silent-query (progn (setq arguments (cons "--silent-query" arguments)))) (if range-filter (progn (setq arguments (cons ... arguments)))) (if (or timeout rtags-timeout) (progn (setq arguments (cons ... arguments)))) (if (and rtags-show-containing-function (not (member "-N" arguments))) (progn (setq arguments (cons "-o" arguments)))) (cond ((stringp path) (setq arguments (cons ... arguments))) (path nil) (default-directory (setq arguments (cons ... arguments))) (t nil)) (if rtags-rc-log-enabled (progn (rtags-log (concat rc " " ...)))) (let ((proc (cond ... ... ... ... ...))) (if proc (progn (set-process-query-on-exit-flag proc nil) (set-process-filter proc ...) (set-process-sentinel proc ...)) (goto-char (point-min)) (and (cond ... ... ...) rtags-autostart-diagnostics (rtags-diagnostics)))) (or async (> (point-max) (point-min)))))))
  rtags-call-rc(:path nil :path-filter nil "-F" "--cursor-kind" "--display-name" "--no-context")
  (progn (rtags-call-rc :path fn :path-filter fn "-F" "--cursor-kind" "--display-name" "--no-context") (if (= (point-min) (point-max)) nil (while (not (eobp)) (let ((line (buffer-substring-no-properties (point-at-bol) (point-at-eol)))) (if (string-match "^\\(.*:\\)\\([0-9]+\\)\\(:[0-9]+:\\)	\\(.*\\)	\\(.*\\)$" line) (progn (let (... ... ... ... ...) (add-to-list ... ...))))) (forward-line))))
  (unwind-protect (progn (rtags-call-rc :path fn :path-filter fn "-F" "--cursor-kind" "--display-name" "--no-context") (if (= (point-min) (point-max)) nil (while (not (eobp)) (let ((line (buffer-substring-no-properties ... ...))) (if (string-match "^\\(.*:\\)\\([0-9]+\\)\\(:[0-9]+:\\)	\\(.*\\)	\\(.*\\)$" line) (progn (let ... ...)))) (forward-line)))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))
  (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (rtags-call-rc :path fn :path-filter fn "-F" "--cursor-kind" "--display-name" "--no-context") (if (= (point-min) (point-max)) nil (while (not (eobp)) (let ((line ...)) (if (string-match "^\\(.*:\\)\\([0-9]+\\)\\(:[0-9]+:\\)	\\(.*\\)	\\(.*\\)$" line) (progn ...))) (forward-line)))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer))))
  (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (rtags-call-rc :path fn :path-filter fn "-F" "--cursor-kind" "--display-name" "--no-context") (if (= (point-min) (point-max)) nil (while (not (eobp)) (let (...) (if ... ...)) (forward-line)))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))))
  (let* ((fn (buffer-file-name)) functions classes variables enums macros other) (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (rtags-call-rc :path fn :path-filter fn "-F" "--cursor-kind" "--display-name" "--no-context") (if (= (point-min) (point-max)) nil (while (not ...) (let ... ...) (forward-line)))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer))))) (if (or functions classes variables enums macros other) (progn (if (not dest-window) (progn (delete-other-windows))) (let ((buf (rtags-get-buffer)) (max 0)) (save-current-buffer (set-buffer buf) (erase-buffer) (setq max (max max (rtags-taglist-insert-category functions "Functions"))) (setq max (max max (rtags-taglist-insert-category classes "Classes/Structs"))) (setq max (max max (rtags-taglist-insert-category variables "Vars/Fields/Params"))) (setq max (max max (rtags-taglist-insert-category enums "Enums"))) (setq max (max max (rtags-taglist-insert-category macros "Macros"))) (setq max (max max (rtags-taglist-insert-category other "Other"))) (setq buffer-read-only t) (goto-char (point-min)) (forward-line)) (if (not dest-window) (progn (split-window-horizontally (min ... ...)))) (switch-to-buffer buf) (rtags-taglist-mode) (deactivate-mark)))))
  rtags-taglist()
  call-interactively(rtags-taglist nil nil)
  command-execute(rtags-taglist)

regards,
Paul

**Comment by cslux** [comment]
It does work it just takes endless time, first rdm needs to collect all the tags after that it will insert it into the `*RTags*` buffer which takes even more time. Try it on a very very very small project and watch the rdm process and the emacs process. First the rdm process will spin the CPU, in my case one core, that is 25%, after that emacs will spin the CPU, again one core.

I tried it on the rtags project, it took approximately 8-10 minutes until the job was done, and the `*RTags*` buffer was **6.1M** big and **68806** lines long :-). I better try it not on the chromium project :-D

regards,
Chris

**Comment by cslux** [comment]
Hey @Mafeuser,

if I request the  taglist from the shell, it takes just a few seconds.

```
rdm --deamon
rc -F --cursor-kind --display-name --no-context
```

My second try was to comment out the regex stuff in `rtags-taglist` as regexp's are very computation intensive. Result...it takes just a few more seconds than from the shell. We know now where the bottleneck lies. But I'm not a lisp expert on how we could improve it, lets see what @Andersbakken says.

regards,
Chris

**Comment by Andersbakken** [comment]
I think I might have fixed it now. Can you give it a shot?

**Comment by Mafeuser** [comment]
works like a charm!

Using other face for "functions:", "Classes:" etc. improves readibility alot.

by the way. Yesterday I had to do some debugging on preprocessor result.
C-crE turned to be very handy.

thank You for this particular case and rtags in general.

regards

**Comment by Andersbakken** [comment]
Hi

My pleasure. Let me know if you run into other issues or have ideas for
ways to improve rtags.

Anders
