### ISSUE TITLE
Old database gets not deleted when database needs to be rebuild

### ISSUE THREAD

**Issue by cslux** [Andersbakken/rtags#449]
Hey Anders,

it seems like the old database gets not deleted when the database version gets rebuild due to a newer version.

e.g. rtags databse is now ~70MB big where it is only ~40MB big when I delete it and let rtags recreate it,
same for chromium ~1.6GB now ~2.6GB big etc..

BTW, it turns out that Fedora seems to be the only distro which ships bash-completion with the bash-completion-config.cmake file. At least the following distro's do not contain it.

- Debian and all it's derivatives like Ubuntu, CentoOS ...
- OpenSuSe
- Nor is it available in Homebrew

Pretty sad, as this file(s) is in the bash-completion project since 2013. Fedora seems to be the only distro which uses the git master branch to install bash-completion. Anyway, I'll hack something together the next couple days.

Chris

**Comment by Andersbakken** [comment]
Hi Chris

That is kinda unfortunate about the cmake thing.

I can't quite reproduce this issue about the ~/.rtags directory. We do
recursively rmdir the whole directory so it really shouldn't be happening.

Can you reproduce it easily? (I would just do something like this to make
it happen):

$ git diff HEAD -- /Users/abakken/dev/rtags/src/Server.cpp
diff --git a/src/Server.cpp b/src/Server.cpp
index db09ebf..702407e 100644
--- a/src/Server.cpp
+++ b/src/Server.cpp
@@ -1632,7 +1632,7 @@ void Server::load()
 {
     const Path p = mOptions.dataDir + "fileids";
     DataFile fileIdsFile(mOptions.dataDir + "fileids",
RTags::DatabaseVersion);
-    if (fileIdsFile.open(DataFile::Read)) {
+    if (false && fileIdsFile.open(DataFile::Read)) {
         Hash<Path, uint32_t> pathsToIds;
         fileIdsFile >> pathsToIds;
         Location::init(pathsToIds);

Then compare before and after?

There's going to be some differences in which files get which fileids so
you can't compare the directory contents but the total size should be
roughly the same for before and after.

I see roughly the same size (some difference is expected I think).

Anders

**Comment by cslux** [comment]
hmmm, could swore the chromium database was just 1.6GB before.

**Comment by Andersbakken** [comment]
If you find a way to repro just reopen.

Anders

**Comment by Andersbakken** [comment]
Maybe we should bundle with a version of bash-completion-config.cmake and
use it only if there's no system version. The cmake warning is a little
annoying. I'm assuming we could query some thing else to figure out where
bash completions are supposed to be installed.

Anders

**Comment by cslux** [comment]
> I'm assuming we could query some thing else to figure out where bash completions are supposed to be installed.

That would probably be better anyway, since the bash-completion cmake module is hard-coded it always points to `/usr/share/bash-completion/completions`, at least on Fedora. This is a bit of a problem when `RTags` gets installed without `sudo`, and the cmake module was found :-/. I will write something, before someone files an issue, that the installation fails.

Christian
