### ISSUE TITLE
Assertion triggered in EmbeddedLinkedList

### ISSUE THREAD

**Issue by HongxuChen** [Andersbakken/rtags#450]
Found a possible assert violation in `EmbeddedLinkedList`. Sorry I'm not sure how to reproduce this issue right now, but will update when possible.

```
rdm: /home/user1/.builds/rtags/src/rct/rct/EmbeddedLinkedList.h:60: void EmbeddedLinkedList<T>::remove(const T&) [with T = CompletionThread::SourceFile*]: Assertion `mCount == 1' failed.
```

**Comment by Andersbakken** [comment]
That is indeed scary. Seems like a bad bug somewhere (maybe unprotected
concurrent access). Would love it if you could figure out how to repro or
catch it in the debugger.

Anders

**Comment by HongxuChen** [comment]
Yes, I also guess it might result from concurrency. Sure, I'll present the details when coming across this issue again.
