### ISSUE TITLE
Call FileSystemWatcher::watch on fewer directories

### ISSUE THREAD

**Issue by pradhanpk** [Andersbakken/rtags#463]
Hi @Andersbakken,

I am seeing a lot of 'FileSystemWatcher::watch() watch failed' error messages. This is almost surely because of the limit on the number of inotify processes on my work machine. However, I did notice that rtags tries to add many directories, even when one of them is contained in the other. For example, it seems to try to watch every directory in my boost/include folder. Would it be possible to change this behaviour somehow? Perhaps allow the user to choose a coarse file-watching mechanism for some directories? Include directories, especially when containing system headers, for example.

Thanks,
Pradhan

**Comment by Andersbakken** [comment]
Hi Pradhan

To the best of my knowledge inotify does not recursively watch directories so I don't think it's really viable to just watch the root. 

We do have this option:

--watch-sources-only

Which will lead to only directories with source files (c, cpp etc) in them being watched. 

There's also this option:

--no-filemanager-watch

It makes rtags not track changes in other directories that do not contain sources or headers. (For (rtags-find-file etc).

Does this help any?

**Comment by pradhanpk** [comment]
@Andersbakken Ah ok. The overhead of an `inotify` watch is very low - just around 1kb of memory on 64-bit machines, making the increased resource usage very manageable. Thanks!

**Comment by Andersbakken** [comment]
No problem. Let me know if the --watch-sources-only thing works out for you
(it was broken until recently but should be working now).

Anders
