### ISSUE TITLE
CMake install doesn't seem to install install rtags wrapper

### ISSUE THREAD

**Issue by brcm-ruperts** [Andersbakken/rtags#464]
I built everything with the following commands (wrapped up in some env stuff to sort out paths, but I don't think that's relevant to this bug report)

    cmake -DCMAKE_INSTALL_PREFIX:PATH=/home/ruperts/work/tools/rtags ..
    make -j4
    make install

The result:

    ~/work/tools/src/rtags/build> find /home/ruperts/work/tools/rtags/
    /home/ruperts/work/tools/rtags/
    /home/ruperts/work/tools/rtags/bin
    /home/ruperts/work/tools/rtags/bin/rdm
    /home/ruperts/work/tools/rtags/bin/rc
    /home/ruperts/work/tools/rtags/bin/rp
    /home/ruperts/work/tools/rtags/share
    /home/ruperts/work/tools/rtags/share/man
    /home/ruperts/work/tools/rtags/share/man/man7
    /home/ruperts/work/tools/rtags/share/man/man7/rc.7
    /home/ruperts/work/tools/rtags/share/man/man7/rdm.7
    /home/ruperts/work/tools/rtags/share/emacs
    /home/ruperts/work/tools/rtags/share/emacs/site-lisp
    /home/ruperts/work/tools/rtags/share/emacs/site-lisp/rtags
    /home/ruperts/work/tools/rtags/share/emacs/site-lisp/rtags/company-rtags.el
    /home/ruperts/work/tools/rtags/share/emacs/site-lisp/rtags/rtags-ac.el
    /home/ruperts/work/tools/rtags/share/emacs/site-lisp/rtags/rtags.el

which seems to be missing `gcc-rtags-wrapper.sh`. Should this be installed too?

**Comment by Andersbakken** [comment]
It should. Thanks for the bug report.

Anders
