### ISSUE TITLE
Issue building rtags

### ISSUE THREAD

**Issue by LefterisJP** [Andersbakken/rtags#465]
I can't seem to build the latest rtags master. It is managed by [el-get](https://github.com/dimitri/el-get) and for the first time in over a year I got a failure in rtags compilation. The el-get recipe is  [here](https://github.com/dimitri/el-get/blob/master/recipes/rtags.rcp)

Error is at cmake configure phase
```
-- Performing Test HAVE_CXX11
-- Performing Test HAVE_CXX11 - Failed
CMake Error at src/rct/rct.cmake:213 (message):
  C++11 support not detected.  rct requires a modern compiler, GCC >= 4.8 or
  Clang >= 3.2 should suffice
Call Stack (most recent call first):
  src/rct/CMakeLists.txt:2 (include)
```

I checked the cmake file and the test should compile. I can manually build the test source code here:

```cmake
check_cxx_source_compiles("
  #include <memory>
  #include <mutex>
  #include <tuple>
  #include <string>
  #include <${CMAKE_CURRENT_LIST_DIR}/rct/Apply.h>

  void callTest(int, std::string) { }

  int main(int, char**) {
      std::shared_ptr<int> ptr;
      std::mutex mtx;
      std::unique_lock<std::mutex> lock(mtx);
      std::tuple<int, std::string> tpl(5, std::string(\"foo\"));
      applyMove(std::bind(callTest, std::placeholders::_1, std::placeholders::_2), tpl);
      return 0;
  }" HAVE_CXX11)
```

My gcc is version 5.2
My OS is ArchLinux. I can try to research this further when I go back home.

**Comment by cslux** [comment]
Hey @LefterisJP ,

I also use gcc 5.2 on my machine (fedora 22) and do not get this error. I made recently some changes in the cmake files but since the build wasn't failing on my laptop nor at work nor on travis, it seems a bit strange too me. 

I will try to compile rtags with el-get tomorrow, something must be wrong there.

Will report back.

**Comment by cslux** [comment]
Where does el-get run 
```
git submodule init
git submodule update
```
Am I missing something?

**Comment by cslux** [comment]
Do have tried it to compile it by manually already?

**Comment by cslux** [comment]
I see, el-get takes care of the submodules.

I'll just tried it, and it works.

Maybe a `RET el-get-remove RET rtags` followed by `RET el-get-install RET rtags` helps!?

**Comment by LefterisJP** [comment]
@cslux Yes as you can see el-get runs the submodule update and init. I have always been using it in order to build/manage my emacs packages.

In my home computer I got a different error when I tried updating to the latest master.

```
Scanning dependencies of target rtags
Scanning dependencies of target rct
[  1%] Building CXX object src/CMakeFiles/rtags.dir/IndexMessage.cpp.o
[  2%] Building CXX object src/CMakeFiles/rtags.dir/Symbol.cpp.o
[  4%] Building CXX object src/CMakeFiles/rtags.dir/Location.cpp.o
[  5%] Building CXX object src/CMakeFiles/rtags.dir/QueryMessage.cpp.o
[  7%] Building CXX object src/rct/CMakeFiles/rct.dir/rct/AES256CBC.cpp.o
/home/lefteris/.emacs.d/el-get/rtags/src/rct/rct/AES256CBC.cpp:1:0: error: bad value (generic-pipe--param=ssp-buffer-size=4) for -mtune= switch
 #include "AES256CBC.h"
 ^
/home/lefteris/.emacs.d/el-get/rtags/src/Location.cpp:1:0: error: bad value (generic-pipe--param=ssp-buffer-size=4) for -mtune= switch
 /* This file is part of RTags (http://rtags.net).
 ^
/home/lefteris/.emacs.d/el-get/rtags/src/QueryMessage.cpp:1:0: error: bad value (generic-pipe--param=ssp-buffer-size=4) for -mtune= switch
 /* This file is part of RTags (http://rtags.net).
 ^
/home/lefteris/.emacs.d/el-get/rtags/src/Symbol.cpp:1:0: error: bad value (generic-pipe--param=ssp-buffer-size=4) for -mtune= switch
 
 ^
/home/lefteris/.emacs.d/el-get/rtags/src/IndexMessage.cpp:1:0: error: bad value (generic-pipe--param=ssp-buffer-size=4) for -mtune= switch
 /* This file is part of RTags (http://rtags.net).
 ^
src/CMakeFiles/rtags.dir/build.make:86: recipe for target 'src/CMakeFiles/rtags.dir/Location.cpp.o' failed
make[2]: *** [src/CMakeFiles/rtags.dir/Location.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
src/CMakeFiles/rtags.dir/build.make:134: recipe for target 'src/CMakeFiles/rtags.dir/QueryMessage.cpp.o' failed
make[2]: *** [src/CMakeFiles/rtags.dir/QueryMessage.cpp.o] Error 1
src/CMakeFiles/rtags.dir/build.make:62: recipe for target 'src/CMakeFiles/rtags.dir/IndexMessage.cpp.o' failed
make[2]: *** [src/CMakeFiles/rtags.dir/IndexMessage.cpp.o] Error 1
src/CMakeFiles/rtags.dir/build.make:110: recipe for target 'src/CMakeFiles/rtags.dir/Symbol.cpp.o' failed
make[2]: *** [src/CMakeFiles/rtags.dir/Symbol.cpp.o] Error 1
src/rct/CMakeFiles/rct.dir/build.make:62: recipe for target 'src/rct/CMakeFiles/rct.dir/rct/AES256CBC.cpp.o' failed
make[2]: *** [src/rct/CMakeFiles/rct.dir/rct/AES256CBC.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:303: recipe for target 'src/CMakeFiles/rtags.dir/all' failed
make[1]: *** [src/CMakeFiles/rtags.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  8%] Building CXX object src/rct/CMakeFiles/rct.dir/rct/SHA256.cpp.o
/home/lefteris/.emacs.d/el-get/rtags/src/rct/rct/SHA256.cpp:1:0: error: bad value (generic-pipe--param=ssp-buffer-size=4) for -mtune= switch
 #include "SHA256.h"
 ^
src/rct/CMakeFiles/rct.dir/build.make:86: recipe for target 'src/rct/CMakeFiles/rct.dir/rct/SHA256.cpp.o' failed
make[2]: *** [src/rct/CMakeFiles/rct.dir/rct/SHA256.cpp.o] Error 1
CMakeFiles/Makefile2:358: recipe for target 'src/rct/CMakeFiles/rct.dir/all' failed
make[1]: *** [src/rct/CMakeFiles/rct.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

And then when I tried to  `el-get-remove` and then `el-get-install`  I got the CXX11 error again. 

I  also just tried the same with a clean `--recursive` clone of the rtags repo and building by hand and if fails at the cmake configure phase with the CXX11 error.

I will have to try and debug it further. Need to somehow see what is the error that `check_cxx_source_compiles()` throws.

**Comment by cslux** [comment]
Could you configure cmake to make verbose makefiles and post the output here please, thanks. 
``` bash
cmake -DCMAKE_VERBOSE_MAKEFILES
```
Do you use the flag `-mtune`?

**Comment by LefterisJP** [comment]
@cslux I found out what the problem was. Made a PR and linked it to this issue.

**Comment by cslux** [comment]
Cool thanks!

**Comment by LefterisJP** [comment]
@cslux Merge it whenever you can if it's not breaking anything else. Would help me in being able to use the upstream version of rtags from el-get again :)

**Comment by cslux** [comment]
I would, but I don't have push access to upstream/master :-)

We have to wait for @Andersbakken,

I have to get this off my chest..it really sucks that clang is compiled on every
GNU/Linux distribution with different options, because we actually only need the
`-D....` stuff from the output of `llvm-config --cxxflags`, with the exception
of `-DNDEBUG`. Anyway, thanks ones more for fixing my buggy regex. :-)

I will probably install all common Linux distribution, on my other laptop, to
get such bugs in the first place.


regards,
Christian

**Comment by Andersbakken** [comment]
Sorry about the delay guys. I merged it just now.

Anders
