### ISSUE TITLE
question: where is the rdm binary?

### ISSUE THREAD

**Issue by finjulhich** [Andersbakken/rtags#466]
on fedora linux, emacs 24.5.1, through "Manage Emacs packages" and ELPA, i installed rtags 20151013.1352.

I have a
(required 'rtags) 
in my .emacs but I see this error in the messages at some point (on Ctrl X Ctrl F a file):

File  mode specification error: (file-error "Searching for program" "no such file or directory" "rdm")

**Comment by cslux** [comment]
If you have install rtags from the melpa repository the binaries are not getting
compiled and installed.

You have two options:

1) Use `el-get` to install RTags, `el-get` will also compile rtags for you

2) Fetch the repository from github and compile it manually.

``` bash
cd ~/Downloads
git clone https://github.com/Andersbakken/rtags.git
cd rtags
git submodule init
git submodule update
mkdir build
cd build
cmake ../ -DCMAKE_INSTALL_PREFIX=/usr
make -j4
sudo make install
```

You can adjust the install prefix to your needs. `ccmake` is pretty convenient
to configure to project.

regards,
Christian

**Comment by cslux** [comment]
If choose the manual version you don't need the melpa package as the lisp code gets also installed. However, you need to make sure that the path is in the `load-path` of emacs, if you choose to install rtags into `/usr`, nothing has to be done.

**Comment by finjulhich** [comment]
After rebuild rtag, rc, rm, the correct llvm include dir is used.
Thanks a lot for your time and help
Issue can be closed
