### ISSUE TITLE
Installation assumes that elisp shoudl be installed under CMAKE_INSTALL_PREFIX

### ISSUE THREAD

**Issue by cleeland** [Andersbakken/rtags#469]
Emacs is not always installed under CMAKE_INSTALL_PREFIX, especially when a distribution's packaged emacs is too old.

rtags should permit easy specification of an alternate emacs site-lisp location independent of CMAKE_INSTALL_PREFIX.

**Comment by Andersbakken** [comment]
Should be possible now. Thanks for the report.

**Comment by cleeland** [comment]
Great! Will try it out tomorrow morning.

**Comment by Andersbakken** [comment]
Cool. Let me know if it works out or if we need to make changes.
