### ISSUE TITLE
make install: file INSTALL cannot find   "/home/hrehfeld/projects_local/rtags/src/rtags.elc".

### ISSUE THREAD

**Issue by hrehfeld** [Andersbakken/rtags#472]
~/.local/tmp/build/rtags 
$ make install
[  1%] Built target emacs_byte_compile_company-rtags.el
[  2%] Built target emacs_byte_compile_rtags-ac.el
[  3%] Built target emacs_byte_compile_rtags.el
[ 43%] Built target rct
[ 51%] Built target rtags
[ 56%] Built target rc
[ 92%] Built target rdm
[100%] Built target rp
Install the project...
-- Install configuration: "Release"
Installing rtags...
-- Installing: /usr/local/etc/bash_completion.d/rtags
-- Installing: /usr/local/etc/bash_completion.d/rc
-- Installing: /usr/local/etc/bash_completion.d/rdm
-- Installing: /usr/local/bin/rdm
-- Installing: /usr/local/bin/rc
-- Installing: /usr/local/bin/rp
-- Installing: /usr/local/bin/gcc-rtags-wrapper.sh
-- Installing: /usr/local/share/man/man7/rc.7
-- Installing: /usr/local/share/man/man7/rdm.7
-- Installing: /usr/local/share/emacs/site-lisp/rtags/rtags.el
CMake Error at src/cmake_install.cmake:98 (file):
  file INSTALL cannot find
  "/home/hrehfeld/projects_local/rtags/src/rtags.elc".
Call Stack (most recent call first):
  cmake_install.cmake:37 (include)

Makefile:61: recipe for target 'install' failed
make: *** [install] Error 1
fail  ~/.local/tmp/build/rtags

$ ls ~/.local/tmp/build/rtags/src 
CMakeFiles/  rct/        cmake_install.cmake  rtags-ac.el  company-rtags.elc  rtags.elc
Makefile     librtags.a  company-rtags.el     rtags.el     rtags-ac.elc

**Comment by Andersbakken** [comment]
Hm. The .elc files should have gotten built during the make phase. Any chance you could do a git clean -xfd and then run cmake again? I think something might get cached by cmake that stops it from generating the .elc files.

**Comment by cleeland** [comment]
This is the same problem I had and for which I submitted a pull request.

On Tuesday, October 20, 2015, Anders Bakken <notifications@github.com>
wrote:

> Hm. The .elc files should have gotten built during the make phase. Any
> chance you could do a git clean -xfd and then run cmake again? I think
> something might get cached by cmake that stops it from generating the .elc
> files.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Andersbakken/rtags/issues/472#issuecomment-149596091>.
>


-- 
Chris Cleeland

**Comment by Andersbakken** [comment]
I'll assume this is fixed by cleeland then. Please reopen if you still can repro. Thanks Chris.
