### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by sizur** [Andersbakken/rtags#475]
cd .emacs.d/src/rtags && rm -rf bld && mkdir bld && cd bld && cmake -DCMAKE_BUILD_TYPE=Release .. && make
-- The C compiler identification is GNU 5.2.0
-- The CXX compiler identification is GNU 5.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- llvm-config executable found: /usr/bin/llvm-config
-- Using Clang version 3.7.0 from /usr/lib with CXXFLAGS -I/usr/include -march=x86-64 -mtune=generic -pipe --param=ssp-buffer-size=4  -pedantic   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-- Found LibClang: /usr/lib64/libclang.so  
-- Found Curses: /usr/lib64/libcurses.so  
-- Looking for backtrace
-- Looking for backtrace - found
-- Looking for CLOCK_MONOTONIC_RAW
-- Looking for CLOCK_MONOTONIC_RAW - found
-- Looking for CLOCK_MONOTONIC
-- Looking for CLOCK_MONOTONIC - found
-- Looking for mach_absolute_time
-- Looking for mach_absolute_time - not found
-- Looking for inotify_init
-- Looking for inotify_init - found
-- Looking for kqueue
-- Looking for kqueue - not found
-- Looking for epoll_wait
-- Looking for epoll_wait - found
-- Looking for select
-- Looking for select - found
-- Looking for FD_CLOEXEC
-- Looking for FD_CLOEXEC - found
-- Looking for SO_NOSIGPIPE
-- Looking for SO_NOSIGPIPE - not found
-- Looking for MSG_NOSIGNAL
-- Looking for MSG_NOSIGNAL - found
-- Looking for GetLogicalProcessorInformation
-- Looking for GetLogicalProcessorInformation - not found
-- Looking for SCHED_IDLE
-- Looking for SCHED_IDLE - found
-- Looking for SHM_DEST
-- Looking for SHM_DEST - found
-- Performing Test HAVE_STATMTIM
-- Performing Test HAVE_STATMTIM - Success
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.8") 
-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.2d") 
-- Performing Test HAVE_CXX11
-- Performing Test HAVE_CXX11 - Success
-- Performing Test HAVE_UNORDERDED_MAP_WORKING_MOVE_CONSTRUCTOR
-- Performing Test HAVE_UNORDERDED_MAP_WORKING_MOVE_CONSTRUCTOR - Success
Copying files from /home/sizur/git/dotfiles/.emacs.d/src/rtags/bin to /home/sizur/git/dotfiles/.emacs.d/src/rtags/bld/bin
-- 
-- The following OPTIONAL packages have been found:

 * ZLIB
 * OpenSSL

-- The following REQUIRED packages have been found:

 * LibClang
 * Curses

-- The following OPTIONAL packages have not been found:

 * bash-completion

-- Configuring done
-- Generating done
-- Build files have been written to: /home/sizur/git/dotfiles/.emacs.d/src/rtags/bld
make[1]: Entering directory '/home/sizur/git/dotfiles/.emacs.d/src/rtags/bld'
make[2]: Entering directory '/home/sizur/git/dotfiles/.emacs.d/src/rtags/bld'
make[3]: Entering directory '/home/sizur/git/dotfiles/.emacs.d/src/rtags/bld'
Scanning dependencies of target emacs_byte_compile_company-rtags.el
make[3]: Leaving directory '/home/sizur/git/dotfiles/.emacs.d/src/rtags/bld'
make[3]: Entering directory '/home/sizur/git/dotfiles/.emacs.d/src/rtags/bld'
make[3]: *** No rule to make target 'src/company-rtags.el', needed by 'src/company-rtags.elc'.  Stop.
make[3]: Leaving directory '/home/sizur/git/dotfiles/.emacs.d/src/rtags/bld'
CMakeFiles/Makefile2:195: recipe for target 'src/CMakeFiles/emacs_byte_compile_company-rtags.el.dir/all' failed
make[2]: *** [src/CMakeFiles/emacs_byte_compile_company-rtags.el.dir/all] Error 2
make[2]: Leaving directory '/home/sizur/git/dotfiles/.emacs.d/src/rtags/bld'
Makefile:127: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/sizur/git/dotfiles/.emacs.d/src/rtags/bld'
Makefile:79: recipe for target 'rtags' failed
make: *** [rtags] Error 2
make rtags  2.07s user 0.45s system 80% cpu 3.133 total

**Comment by cslux** [comment]
Same here, working on it!
regards,
Christian

**Comment by cleeland** [comment]
If this worked before, it may be related to issue #473 solution.  However, what you're doing looks very similar to what I do to build, except that I specify more stuff to cmake via "-D" options.

**Comment by cslux** [comment]
Should be fixed with PR #476
