### ISSUE TITLE
feature request: let rtags handle the project that sits on remote site.

### ISSUE THREAD

**Issue by Mafeuser** [Andersbakken/rtags#477]
Use-case 1: Application I'm working on is spanned across multiple linux boxes. Each linux box runs different version of development tool chain. What is more I'd prefer to have my emacs configuration installed and managed on single machine, which is my desktop.

Use-case 2: I'm working with driver development. Machine freezes are quite common in such a case and happen in least expected moment. In this moment I loose all my development context. Of course emacs could save session state, but it would be much more convenient not to have to do anything at all, but just wait on the machine to be woken up from reboot.

Both the cases are already handled by emacs tramp, ie. emacs runs on my desktop and both the gcc and gdb run on remote machine. Emacs also can browse source code that is physically put on remote machine. You can of course use cscope for that but what is really lacking here is rtags. Rtags is the best with source code "browsing", but it lacks the awareness of project being on remote location.

I imagine that rdm would run on remote machine and would be queried by rc also invoked on behalf of remote machine. All the communication between local emacs and remote rdm/rc would be done by emacs tramp module. IMHO: neither rc nor rdm would probably require any changes. Rtags.el would have to be modified.

Emacs is the only editor I know that is able to do such an advanced remote work. rtags being the part of this family would be very valuable closure.

regards

**Comment by Andersbakken** [comment]
Hi

I think it definitely is possible. We could also with relative ease make
rdm listen on a tcp connection (it currently uses a unix domain socket) and
run rc on the same machine that emacs runs on.

It's a little bit of work however. I'll see if I can find some time to take
a crack at it.

Anders

**Comment by Andersbakken** [comment]
I added the tcp connection support (rdm --tcp-port xxxx, rc
--socket-address host:1234

I think we need some elisp work to figure out that you're in a tramp file
(we already have some code that check that) and then some magic that
realizes that paths coming back are from tramp and need to be opened as
such etc. Contributions are very welcome.

Anders

**Comment by Mafeuser** [comment]
Hi Anders.

Yes, having rc run on local site to communicate rdm running on remote site is more intuitive. On the other hand my concern is the case when the only port open on remote host is ssh.

regards

**Comment by Andersbakken** [comment]
I guess that makes some sense. You can start remote processes over tramp?

Anders

**Comment by Mafeuser** [comment]
Yes. there is tramp-call-process function for that.
(tramp-call-process VEC PROGRAM &optional INFILE DESTINATION DISPLAY &rest ARGS)
                   (call-process PROGRAM &optional INFILE DESTINATION DISPLAY &rest ARGS)

VEC differs both the signatures.

According to manual: it explicitly tells what user/host to use for calling the PROGRAM.
But VEC can be nil, then current tramp connection user/host is taken.

So when you have some remote site visited with tramp, the following will call date from remote location:

(tramp-call-process nil "date")

You can check this by visiting *debug tramp/scp remote-site-name*

prior to command, above, please set (setq tramp-verbose 10) to see more.

I don't need the following in my config, but that might be needed also.
(setq tramp-debug-buffer nil)

Maybe I should mention about very usefull feature of tramp.

Let's assume the current buffer is:
/scp:remote-host:/home/user

now in order to visit /user/include on remote host You don't have to type /scp:remote-host:/usr/include.

It is enough to press C-x C-f (You will see /scp:remote-host:/home/user), then just add '//usr/include' to our current path. Completion will work of course.

Why I think this is important?

Assume rc has been called from some remote project /scp:remote-host:/home/user/proj. tramp-call-process was used of course. But rc returns some location which has local format:
for example /usr/include/errno.h

What emacs does? It glues both the paths: current buffer and the rc result with one extra `/` character:
/scp:remote-host:/home/user/proj//usr/include/errno.h
tramp resolves it to: 
/scp:remote-host:/usr/include/errno.h

Is this the magic that could be used.

There one more magic to be aware of. `///` makes tramp start from local host. So
/scp:remote-host:/home/user////usr/include will end up in /usr/include of local host.

2 functions that seem to be usefull:
(tramp-dissect-file-name default-directory): return tramp path dissected to vector.
[#("scp" 0 3 (tramp-default t)) nil "remote-host" "/home/user/" nil]

(tramp-tramp-file-p default-directory) - tells if path is tramp like

regards

**Comment by Andersbakken** [comment]
It does seem like this would be possible to do and quite useful in certain
scenarios. I'll see if I can find some time to look into it but if you feel
like writing up some elisp to achieve this yourself it would be much
appreciated. :-)

Anders

**Comment by Mafeuser** [comment]
I'll try at least :)

anyway, thank You for Your attention.

best regards!

**Comment by Andersbakken** [comment]
Let me know if you need help with anything. I'd love to have this feature.

Anders

**Comment by dholm** [comment]
Unless you need to force tramp you should simply use `process-file` etc to launch your processes.  Tramp installs a file handler so if `default-directory` points to a Tramp managed path all functions that are compatible with file handlers will "just work".  The good thing is that this will also work for potentially other special cases, not just Tramp.

**Comment by vibrys** [comment]
I am going to start working with this feature.
IMHO: first results should be visible in about 2 weeks time.

Anders, do You plan some major changes in rtags.el with this time horizon?
Could You please assign this feature to me so that other people knew the work is in progress

best regards

**Comment by Andersbakken** [comment]
Nothing major planned for that time period. Thanks for taking this on.

Anders

**Comment by ramestica** [comment]
Question. My understanding is that in the remote machine (where files live and compilation happens) I should start rdm associated to some xxxx tcp port. And in my local machine, where emacs run and remote files are accessed through tramp, rc should be executed passing remote:xxxx as socket-address. 

However, how could I tell rtags.el to use xxxx? I cannot find a variable/option to set that value.

Thanks,
 Rodrigo

**Comment by vibrys** [comment]
@ramestica, You don't have to configure tcp port on remote rdm.

Please see comments on https://github.com/Andersbakken/rtags/pull/546, especially 1.4.

regards

**Comment by samwise-gh** [comment]
> I added the tcp connection support (rdm --tcp-port xxxx, rc
> --socket-address host:1234
> 
> I think we need some elisp work to figure out that you're in a tramp file
> (we already have some code that check that) and then some magic that
> realizes that paths coming back are from tramp and need to be opened as
> such etc. Contributions are very welcome.
> 
> Anders

I would like to run rtags(rdm) on a remote server which hosts all of my project files.  I have done the following which seems to work.

REMOTE:
  $ rdm --tcp-port x.x.x.x:1234

CLIENT:
  $ rc --socket-address x.x.x.x:1234 -w

The problem that I am having is trying to get Emacs to run the rc command, which I assume that it does, with the --socket-address added.  I have looked at the rtags.el file, but was not able to figure how how to specify this.

DESIRED USE CASE:

Emacs running on Client machine(Laptop)
Project file system NFS mounted on Client
Server running rdm 
Server hosting all project files and build environment

Regards,
SAmb.

**Comment by hubgitname** [comment]
I've created a pull-request for samwise-gh's request. Can someone/anders approve the pull ?
https://github.com/Andersbakken/rtags/pull/1303
