### ISSUE TITLE
Failing to build with link errors on OSX 10.10.5

### ISSUE THREAD

**Issue by sbroberg** [Andersbakken/rtags#481]
I'm following the instructions on the main page, but running into a link error.  My steps:

    brew install homebrew/versions/llvm36 --with-libcxx --with-clang --without-assertions --rtti --with-asan --with-lldb --with-lld --with-all-targets    

    git clone https://github.com/Andersbakken/rtags.git --recursive
    cd rtags
    mkdir build
    cd build
    LIBCLANG_LLVM_CONFIG_EXECUTABLE=/usr/local/bin/llvm-config-3.6 /Volumes/CarboniteToolChain/bin/cmake ..
    -- The C compiler identification is Clang 6.1.0
    -- The CXX compiler identification is Clang 6.1.0
    -- Check for working C compiler: /usr/bin/clang
    -- Check for working C compiler: /usr/bin/clang -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/clang++
    -- Check for working CXX compiler: /usr/bin/clang++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- llvm-config executable found: /usr/local/bin/llvm-config-3.6
    -- Using Clang version 3.6.2 from /usr/local/Cellar/llvm36/3.6.2/lib/llvm-3.6/lib with CXXFLAGS -I/usr/local/Cellar/llvm36/3.6.2/lib/llvm-3.6/include  -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS  
    -- Found LibClang: /usr/local/Cellar/llvm36/3.6.2/lib/llvm-3.6/lib/libclang.dylib  
    -- Found Curses: /usr/lib/libcurses.dylib  
    -- Looking for backtrace
    -- Looking for backtrace - found
    -- Looking for CLOCK_MONOTONIC_RAW
    -- Looking for CLOCK_MONOTONIC_RAW - not found
    -- Looking for CLOCK_MONOTONIC
    -- Looking for CLOCK_MONOTONIC - not found
    -- Looking for mach_absolute_time
    -- Looking for mach_absolute_time - found
    -- Looking for inotify_init
    -- Looking for inotify_init - not found
    -- Looking for kqueue
    -- Looking for kqueue - found
    -- Looking for epoll_wait
    -- Looking for epoll_wait - not found
    -- Looking for select
    -- Looking for select - found
    -- Looking for FD_CLOEXEC
    -- Looking for FD_CLOEXEC - found
    -- Looking for SO_NOSIGPIPE
    -- Looking for SO_NOSIGPIPE - found
    -- Looking for MSG_NOSIGNAL
    -- Looking for MSG_NOSIGNAL - not found
    -- Looking for GetLogicalProcessorInformation
    -- Looking for GetLogicalProcessorInformation - not found
    -- Looking for SCHED_IDLE
    -- Looking for SCHED_IDLE - not found
    -- Looking for SHM_DEST
    -- Looking for SHM_DEST - not found
    OS X version 10.10.5
    -- Using FSEvents
    -- Performing Test HAVE_STATMTIM
    -- Performing Test HAVE_STATMTIM - Failed
    -- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.5") 
    -- Found OpenSSL: /usr/lib/libssl.dylib;/usr/lib/libcrypto.dylib (found version "0.9.8zg") 
    -- Performing Test HAVE_CXX11
    -- Performing Test HAVE_CXX11 - Success
    -- Performing Test HAVE_UNORDERDED_MAP_WORKING_MOVE_CONSTRUCTOR
    -- Performing Test HAVE_UNORDERDED_MAP_WORKING_MOVE_CONSTRUCTOR - Success
    Copying files from /Users/stebro/.emacs.d-new/rtags/bin to /Users/stebro/.emacs.d-new/rtags/build/bin
    -- 
    -- The following OPTIONAL packages have been found:
    
     * ZLIB
     * OpenSSL
    
    -- The following REQUIRED packages have been found:
    
     * LibClang
     * Curses
    
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /Users/stebro/.emacs.d-new/rtags/build
    
    make

   ...

    Linking CXX executable ../bin/rdm
    Undefined symbols for architecture x86_64:
      "_launch_activate_socket", referenced from:
          Server::initUnixServer() in Server.cpp.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[2]: *** [bin/rdm] Error 1
    make[1]: *** [src/CMakeFiles/rdm.dir/all] Error 2

I run into a different compilation error when trying to use emacs's el-get to install malinka, which will build and install rtags (I'm not sure how to get it to produce more informative output regarding the configuration it's using):

    [ 94%] Building CXX object src/CMakeFiles/rdm.dir/StatusJob.cpp.o
    [ 95%] Building CXX object src/CMakeFiles/rdm.dir/Symbol.cpp.o
    /Users/stebro/.emacs.d/el-get/rtags/src/Project.cpp:495:29: error: 'severities' cannot be captured because it does not have automatic storage duration
            formatDiagnostic = [severities](const Location &loc, const Diagnostic &diagnostic) {
                                ^
    /Users/stebro/.emacs.d/el-get/rtags/src/Project.cpp:471:24: note: 'severities' declared here
        static const char *severities[] = { "none", "warning", "error", "fixit", "skipped" };
                           ^
    /Users/stebro/.emacs.d/el-get/rtags/src/Project.cpp:503:29: error: 'severities' cannot be captured because it does not have automatic storage duration
            formatDiagnostic = [severities](const Location &loc, const Diagnostic &diagnostic) {
                                ^
    /Users/stebro/.emacs.d/el-get/rtags/src/Project.cpp:471:24: note: 'severities' declared here
        static const char *severities[] = { "none", "warning", "error", "fixit", "skipped" };
                           ^
    [ 97%] Building CXX object src/CMakeFiles/rdm.dir/RTagsClang.cpp.o
    2 errors generated.
    make[2]: *** [src/CMakeFiles/rdm.dir/Project.cpp.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    make[1]: *** [src/CMakeFiles/rdm.dir/all] Error 2
    make: *** [all] Error 2

**Comment by cslux** [comment]
Hey @sbroberg,

could you run cmake with the flag `-DCMAKE_VERBOSE_MAKEFILES=ON`  please, and post the output error where it fails, thanks.

**Comment by Andersbakken** [comment]
I've just fixed the severities thing btw. Can you check if it works now?

**Comment by cslux** [comment]
Seems like he has different compiler settings, than I e.g. Because I just got warnings instead of errors. Please post the output of make (just some of it), after you have called cmake  with the flag mentioned in 
https://github.com/Andersbakken/rtags/issues/481#issuecomment-150669411, thanks!

@Andersbakken warnings are gone so hist built should succeed too now.

**Comment by cslux** [comment]
@Andersbakken I don't know but I think it would be better to just extract the `-D` stuff from `llvm-config --cxxflags` as there are "endless" possibilities how clang can be built?

**Comment by cslux** [comment]
This was also discussed already on the llvm mailing list. http://lists.llvm.org/pipermail/llvm-dev/2015-August/088929.html. Which stated that actually only the `-D` stuff is needed and of course `-std=c++11`, if llvm was compiled with `c++11` support.

**Comment by sbroberg** [comment]
@cslux, I ran cmake with that flag, but it didn't change the output of cmake or the make itself.  However, running make with VERBOSE=y produces what I think you need:

    mbp15-04539:build stebro$ make VERBOSE=Y
    "/Volumes/CarboniteToolChain/Applications/CMake 2.8-12.app/Contents/bin/cmake" -H/Users/stebro/.emacs.d-new/rtags -B/Users/stebro/.emacs.d-new/rtags/build --check-build-system CMakeFiles/Makefile.cmake 0
    "/Volumes/CarboniteToolChain/Applications/CMake 2.8-12.app/Contents/bin/cmake" -E cmake_progress_start /Users/stebro/.emacs.d-new/rtags/build/CMakeFiles /Users/stebro/.emacs.d-new/rtags/build/CMakeFiles/progress.marks
    /Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/Makefile2 all
    /Applications/Xcode.app/Contents/Developer/usr/bin/make -f src/CMakeFiles/emacs_byte_compile_company-rtags.el.dir/build.make src/CMakeFiles/emacs_byte_compile_company-rtags.el.dir/depend
    cd /Users/stebro/.emacs.d-new/rtags/build && "/Volumes/CarboniteToolChain/Applications/CMake 2.8-12.app/Contents/bin/cmake" -E cmake_depends "Unix Makefiles" /Users/stebro/.emacs.d-new/rtags /Users/stebro/.emacs.d-new/rtags/src /Users/stebro/.emacs.d-new/rtags/build /Users/stebro/.emacs.d-new/rtags/build/src /Users/stebro/.emacs.d-new/rtags/build/src/CMakeFiles/emacs_byte_compile_company-rtags.el.dir/DependInfo.cmake --color=
    /Applications/Xcode.app/Contents/Developer/usr/bin/make -f src/CMakeFiles/emacs_byte_compile_company-rtags.el.dir/build.make src/CMakeFiles/emacs_byte_compile_company-rtags.el.dir/build
    make[2]: Nothing to be done for `src/CMakeFiles/emacs_byte_compile_company-rtags.el.dir/build'.
    "/Volumes/CarboniteToolChain/Applications/CMake 2.8-12.app/Contents/bin/cmake" -E cmake_progress_report /Users/stebro/.emacs.d-new/rtags/build/CMakeFiles  1
    [  1%] Built target emacs_byte_compile_company-rtags.el
    /Applications/Xcode.app/Contents/Developer/usr/bin/make -f src/CMakeFiles/emacs_byte_compile_rtags-ac.el.dir/build.make src/CMakeFiles/emacs_byte_compile_rtags-ac.el.dir/depend
    cd /Users/stebro/.emacs.d-new/rtags/build && "/Volumes/CarboniteToolChain/Applications/CMake 2.8-12.app/Contents/bin/cmake" -E cmake_depends "Unix Makefiles" /Users/stebro/.emacs.d-new/rtags /Users/stebro/.emacs.d-new/rtags/src /Users/stebro/.emacs.d-new/rtags/build /Users/stebro/.emacs.d-new/rtags/build/src /Users/stebro/.emacs.d-new/rtags/build/src/CMakeFiles/emacs_byte_compile_rtags-ac.el.dir/DependInfo.cmake --color=
    /Applications/Xcode.app/Contents/Developer/usr/bin/make -f src/CMakeFiles/emacs_byte_compile_rtags-ac.el.dir/build.make src/CMakeFiles/emacs_byte_compile_rtags-ac.el.dir/build
    make[2]: Nothing to be done for `src/CMakeFiles/emacs_byte_compile_rtags-ac.el.dir/build'.
    "/Volumes/CarboniteToolChain/Applications/CMake 2.8-12.app/Contents/bin/cmake" -E cmake_progress_report /Users/stebro/.emacs.d-new/rtags/build/CMakeFiles  2
    [  2%] Built target emacs_byte_compile_rtags-ac.el
    /Applications/Xcode.app/Contents/Developer/usr/bin/make -f src/CMakeFiles/emacs_byte_compile_rtags.el.dir/build.make src/CMakeFiles/emacs_byte_compile_rtags.el.dir/depend
    cd /Users/stebro/.emacs.d-new/rtags/build && "/Volumes/CarboniteToolChain/Applications/CMake 2.8-12.app/Contents/bin/cmake" -E cmake_depends "Unix Makefiles" /Users/stebro/.emacs.d-new/rtags /Users/stebro/.emacs.d-new/rtags/src /Users/stebro/.emacs.d-new/rtags/build /Users/stebro/.emacs.d-new/rtags/build/src /Users/stebro/.emacs.d-new/rtags/build/src/CMakeFiles/emacs_byte_compile_rtags.el.dir/DependInfo.cmake --color=
    /Applications/Xcode.app/Contents/Developer/usr/bin/make -f src/CMakeFiles/emacs_byte_compile_rtags.el.dir/build.make src/CMakeFiles/emacs_byte_compile_rtags.el.dir/build
    make[2]: Nothing to be done for `src/CMakeFiles/emacs_byte_compile_rtags.el.dir/build'.
    "/Volumes/CarboniteToolChain/Applications/CMake 2.8-12.app/Contents/bin/cmake" -E cmake_progress_report /Users/stebro/.emacs.d-new/rtags/build/CMakeFiles  3
    [  4%] Built target emacs_byte_compile_rtags.el
    /Applications/Xcode.app/Contents/Developer/usr/bin/make -f src/CMakeFiles/rtags.dir/build.make src/CMakeFiles/rtags.dir/depend
    cd /Users/stebro/.emacs.d-new/rtags/build && "/Volumes/CarboniteToolChain/Applications/CMake 2.8-12.app/Contents/bin/cmake" -E cmake_depends "Unix Makefiles" /Users/stebro/.emacs.d-new/rtags /Users/stebro/.emacs.d-new/rtags/src /Users/stebro/.emacs.d-new/rtags/build /Users/stebro/.emacs.d-new/rtags/build/src /Users/stebro/.emacs.d-new/rtags/build/src/CMakeFiles/rtags.dir/DependInfo.cmake --color=
    /Applications/Xcode.app/Contents/Developer/usr/bin/make -f src/CMakeFiles/rtags.dir/build.make src/CMakeFiles/rtags.dir/build
    make[2]: Nothing to be done for `src/CMakeFiles/rtags.dir/build'.
    "/Volumes/CarboniteToolChain/Applications/CMake 2.8-12.app/Contents/bin/cmake" -E cmake_progress_report /Users/stebro/.emacs.d-new/rtags/build/CMakeFiles  64 65 66 67 68
    [ 11%] Built target rtags
    /Applications/Xcode.app/Contents/Developer/usr/bin/make -f src/rct/CMakeFiles/rct.dir/build.make src/rct/CMakeFiles/rct.dir/depend
    cd /Users/stebro/.emacs.d-new/rtags/build && "/Volumes/CarboniteToolChain/Applications/CMake 2.8-12.app/Contents/bin/cmake" -E cmake_depends "Unix Makefiles" /Users/stebro/.emacs.d-new/rtags /Users/stebro/.emacs.d-new/rtags/src/rct /Users/stebro/.emacs.d-new/rtags/build /Users/stebro/.emacs.d-new/rtags/build/src/rct /Users/stebro/.emacs.d-new/rtags/build/src/rct/CMakeFiles/rct.dir/DependInfo.cmake --color=
    /Applications/Xcode.app/Contents/Developer/usr/bin/make -f src/rct/CMakeFiles/rct.dir/build.make src/rct/CMakeFiles/rct.dir/build
    make[2]: Nothing to be done for `src/rct/CMakeFiles/rct.dir/build'.
    "/Volumes/CarboniteToolChain/Applications/CMake 2.8-12.app/Contents/bin/cmake" -E cmake_progress_report /Users/stebro/.emacs.d-new/rtags/build/CMakeFiles  6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
    [ 54%] Built target rct
    /Applications/Xcode.app/Contents/Developer/usr/bin/make -f src/CMakeFiles/rc.dir/build.make src/CMakeFiles/rc.dir/depend
    cd /Users/stebro/.emacs.d-new/rtags/build && "/Volumes/CarboniteToolChain/Applications/CMake 2.8-12.app/Contents/bin/cmake" -E cmake_depends "Unix Makefiles" /Users/stebro/.emacs.d-new/rtags /Users/stebro/.emacs.d-new/rtags/src /Users/stebro/.emacs.d-new/rtags/build /Users/stebro/.emacs.d-new/rtags/build/src /Users/stebro/.emacs.d-new/rtags/build/src/CMakeFiles/rc.dir/DependInfo.cmake --color=
    /Applications/Xcode.app/Contents/Developer/usr/bin/make -f src/CMakeFiles/rc.dir/build.make src/CMakeFiles/rc.dir/build
    make[2]: Nothing to be done for `src/CMakeFiles/rc.dir/build'.
    "/Volumes/CarboniteToolChain/Applications/CMake 2.8-12.app/Contents/bin/cmake" -E cmake_progress_report /Users/stebro/.emacs.d-new/rtags/build/CMakeFiles  4 5
    [ 57%] Built target rc
    /Applications/Xcode.app/Contents/Developer/usr/bin/make -f src/CMakeFiles/rdm.dir/build.make src/CMakeFiles/rdm.dir/depend
    cd /Users/stebro/.emacs.d-new/rtags/build && "/Volumes/CarboniteToolChain/Applications/CMake 2.8-12.app/Contents/bin/cmake" -E cmake_depends "Unix Makefiles" /Users/stebro/.emacs.d-new/rtags /Users/stebro/.emacs.d-new/rtags/src /Users/stebro/.emacs.d-new/rtags/build /Users/stebro/.emacs.d-new/rtags/build/src /Users/stebro/.emacs.d-new/rtags/build/src/CMakeFiles/rdm.dir/DependInfo.cmake --color=
    /Applications/Xcode.app/Contents/Developer/usr/bin/make -f src/CMakeFiles/rdm.dir/build.make src/CMakeFiles/rdm.dir/build
    Linking CXX executable ../bin/rdm
    cd /Users/stebro/.emacs.d-new/rtags/build/src && "/Volumes/CarboniteToolChain/Applications/CMake 2.8-12.app/Contents/bin/cmake" -E cmake_link_script CMakeFiles/rdm.dir/link.txt --verbose=Y
    /usr/bin/clang++   -I/usr/local/Cellar/llvm36/3.6.2/lib/llvm-3.6/include  -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS   -Wall -Wextra -Wpointer-arith -Wnon-virtual-dtor -fno-rtti -std=c++11 -stdlib=libc++ -Wstrict-aliasing=2 -fno-exceptions -Wcast-qual -fPIC -fstack-protector-all -Wstack-protector -O3 -DNDEBUG -Wl,-search_paths_first -Wl,-headerpad_max_install_names  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk -mmacosx-version-min=10.7 CMakeFiles/rdm.dir/rdm.cpp.o CMakeFiles/rdm.dir/ClassHierarchyJob.cpp.o CMakeFiles/rdm.dir/CompilerManager.cpp.o CMakeFiles/rdm.dir/CompletionThread.cpp.o CMakeFiles/rdm.dir/SymbolInfoJob.cpp.o CMakeFiles/rdm.dir/DependenciesJob.cpp.o CMakeFiles/rdm.dir/DumpThread.cpp.o CMakeFiles/rdm.dir/FileManager.cpp.o CMakeFiles/rdm.dir/FindFileJob.cpp.o CMakeFiles/rdm.dir/FindSymbolsJob.cpp.o CMakeFiles/rdm.dir/FollowLocationJob.cpp.o CMakeFiles/rdm.dir/IncludeFileJob.cpp.o CMakeFiles/rdm.dir/IndexerJob.cpp.o CMakeFiles/rdm.dir/JobScheduler.cpp.o CMakeFiles/rdm.dir/ListSymbolsJob.cpp.o CMakeFiles/rdm.dir/Preprocessor.cpp.o CMakeFiles/rdm.dir/Project.cpp.o CMakeFiles/rdm.dir/QueryJob.cpp.o CMakeFiles/rdm.dir/ReferencesJob.cpp.o CMakeFiles/rdm.dir/ScanThread.cpp.o CMakeFiles/rdm.dir/Server.cpp.o CMakeFiles/rdm.dir/StatusJob.cpp.o CMakeFiles/rdm.dir/Symbol.cpp.o CMakeFiles/rdm.dir/RTagsClang.cpp.o CMakeFiles/rdm.dir/Source.cpp.o  -o ../bin/rdm  librtags.a rct/librct.a /usr/local/Cellar/llvm36/3.6.2/lib/llvm-3.6/lib/libclang.dylib -lstdc++ /usr/lib/libcurses.dylib /usr/lib/libform.dylib -lpthread /usr/lib/libz.dylib /usr/lib/libcrypto.dylib -framework CoreServices -framework CoreFoundation 
    Undefined symbols for architecture x86_64:
      "_launch_activate_socket", referenced from:
          Server::initUnixServer() in Server.cpp.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[2]: *** [bin/rdm] Error 1
    make[1]: *** [src/CMakeFiles/rdm.dir/all] Error 2
    make: *** [all] Error 2

**Comment by sbroberg** [comment]
@Andersbakken, 

I deleted my .emacs.d and re-ran el-get-install of malinka (after waiting for el-get to finish self-configuring), and it got past the severity error, but now it appears to be hitting the same link error as when I build from the command shell:

    [ 97%] Building CXX object src/CMakeFiles/rdm.dir/RTagsClang.cpp.o
    [ 98%] Building CXX object src/CMakeFiles/rdm.dir/Source.cpp.o
    [100%] Linking CXX executable ../bin/rdm
    Undefined symbols for architecture x86_64:
      "_launch_activate_socket", referenced from:
          Server::initUnixServer() in Server.cpp.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[2]: *** [bin/rdm] Error 1
    make[1]: *** [src/CMakeFiles/rdm.dir/all] Error 2
    make: *** [all] Error 2

**Comment by sbroberg** [comment]
Any updates on this issue?

**Comment by Andersbakken** [comment]
Hi

Sorry about the delay. I kinda don't know what would be causing this. Which
version of xcode/os x are you running?

Anders

**Comment by sbroberg** [comment]
I'm using llvm-36 installed via homebrew, OSX 10.10.5:

    stebro$ /usr/local/bin/clang++-3.6 --version
    clang version 3.6.2 (tags/RELEASE_362/final)
    Target: x86_64-apple-darwin14.5.0
    Thread model: posix

I also get the same error when building with the default clang installed by XCode:

    stebro$ /usr/bin/clang --version
    Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
    Target: x86_64-apple-darwin14.5.0
    Thread model: posix

What library is _launch_activate_socket supposed to be in?  I see that it's defined by /usr/include/launch.h, but I don't know what library or framework that header corresponds to.

**Comment by Andersbakken** [comment]
Seems like it's in /usr/lib/system/libxpc.dylib for me. Do you have that?

Anders

**Comment by Andersbakken** [comment]
Maybe we need to explicitly link to it.

Anders

**Comment by sbroberg** [comment]
I tried linking directly to the library, but I received this rather informative error:

    stebro$ /usr/bin/clang++   -I/usr/local/Cellar/llvm36/3.6.2/lib/llvm-3.6/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Wall -Wextra -Wpointer-arith -Wnon-virtual-dtor -fno-rtti -std=c++11 -stdlib=libc++ -Wstrict-aliasing=2 -fno-exceptions -Wcast-qual -fPIC -fstack-protector-all -Wstack-protector -O3 -DNDEBUG -Wl,-search_paths_first -Wl,-headerpad_max_install_names  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk -mmacosx-version-min=10.7 CMakeFiles/rdm.dir/rdm.cpp.o CMakeFiles/rdm.dir/ClassHierarchyJob.cpp.o CMakeFiles/rdm.dir/CompilerManager.cpp.o CMakeFiles/rdm.dir/CompletionThread.cpp.o CMakeFiles/rdm.dir/SymbolInfoJob.cpp.o CMakeFiles/rdm.dir/DependenciesJob.cpp.o CMakeFiles/rdm.dir/DumpThread.cpp.o CMakeFiles/rdm.dir/FileManager.cpp.o CMakeFiles/rdm.dir/FindFileJob.cpp.o CMakeFiles/rdm.dir/FindSymbolsJob.cpp.o CMakeFiles/rdm.dir/FollowLocationJob.cpp.o CMakeFiles/rdm.dir/IncludeFileJob.cpp.o CMakeFiles/rdm.dir/IndexerJob.cpp.o CMakeFiles/rdm.dir/JobScheduler.cpp.o CMakeFiles/rdm.dir/ListSymbolsJob.cpp.o CMakeFiles/rdm.dir/Preprocessor.cpp.o CMakeFiles/rdm.dir/Project.cpp.o CMakeFiles/rdm.dir/QueryJob.cpp.o CMakeFiles/rdm.dir/ReferencesJob.cpp.o CMakeFiles/rdm.dir/ScanThread.cpp.o CMakeFiles/rdm.dir/Server.cpp.o CMakeFiles/rdm.dir/StatusJob.cpp.o CMakeFiles/rdm.dir/Symbol.cpp.o CMakeFiles/rdm.dir/RTagsClang.cpp.o CMakeFiles/rdm.dir/Source.cpp.o  -o ../bin/rdm  librtags.a rct/librct.a /usr/local/Cellar/llvm36/3.6.2/lib/llvm-3.6/lib/libclang.dylib -lstdc++ /usr/lib/libcurses.dylib /usr/lib/libform.dylib -lpthread /usr/lib/libz.dylib /usr/lib/libcrypto.dylib /usr/lib/system/libxpc.dylib -framework CoreServices -framework CoreFoundation
    ld: cannot link directly with /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk/usr/lib/system/libxpc.dylib.  Link against the umbrella framework 'System.framework' instead. for architecture x86_64

But when I tried to link against -framework System (-framework System.framework didn't work), I got the original error:

    mbp15-04539:src stebro$ /usr/bin/clang++   -I/usr/local/Cellar/llvm36/3.6.2/lib/llvm-3.6/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Wall -Wextra -Wpointer-arith -Wnon-virtual-dtor -fno-rtti -std=c++11 -stdlib=libc++ -Wstrict-aliasing=2 -fno-exceptions -Wcast-qual -fPIC -fstack-protector-all -Wstack-protector -O3 -DNDEBUG -Wl,-search_paths_first -Wl,-headerpad_max_install_names  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk -mmacosx-version-min=10.7 CMakeFiles/rdm.dir/rdm.cpp.o CMakeFiles/rdm.dir/ClassHierarchyJob.cpp.o CMakeFiles/rdm.dir/CompilerManager.cpp.o CMakeFiles/rdm.dir/CompletionThread.cpp.o CMakeFiles/rdm.dir/SymbolInfoJob.cpp.o CMakeFiles/rdm.dir/DependenciesJob.cpp.o CMakeFiles/rdm.dir/DumpThread.cpp.o CMakeFiles/rdm.dir/FileManager.cpp.o CMakeFiles/rdm.dir/FindFileJob.cpp.o CMakeFiles/rdm.dir/FindSymbolsJob.cpp.o CMakeFiles/rdm.dir/FollowLocationJob.cpp.o CMakeFiles/rdm.dir/IncludeFileJob.cpp.o CMakeFiles/rdm.dir/IndexerJob.cpp.o CMakeFiles/rdm.dir/JobScheduler.cpp.o CMakeFiles/rdm.dir/ListSymbolsJob.cpp.o CMakeFiles/rdm.dir/Preprocessor.cpp.o CMakeFiles/rdm.dir/Project.cpp.o CMakeFiles/rdm.dir/QueryJob.cpp.o CMakeFiles/rdm.dir/ReferencesJob.cpp.o CMakeFiles/rdm.dir/ScanThread.cpp.o CMakeFiles/rdm.dir/Server.cpp.o CMakeFiles/rdm.dir/StatusJob.cpp.o CMakeFiles/rdm.dir/Symbol.cpp.o CMakeFiles/rdm.dir/RTagsClang.cpp.o CMakeFiles/rdm.dir/Source.cpp.o  -o ../bin/rdm  librtags.a rct/librct.a /usr/local/Cellar/llvm36/3.6.2/lib/llvm-3.6/lib/libclang.dylib -lstdc++ /usr/lib/libcurses.dylib /usr/lib/libform.dylib -lpthread /usr/lib/libz.dylib /usr/lib/libcrypto.dylib -framework System -framework CoreServices -framework CoreFoundation
    Undefined symbols for architecture x86_64:
      "_launch_activate_socket", referenced from:
          Server::initServers() in Server.cpp.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by sbroberg** [comment]
@Andersbakken : You can close this issue; it turns out (unsurprisingly) that it's an environment issue.  If you look at the compile & link lines above, you'll see that they're specifying -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk , which are set in our development environment for building our apps that must be backwards-compatible to 10.7.  However, it appears that the 10.7 version of that framework does not have that symbol.  When I removed the toolkit constraint, rtags built correctly.

Now I just have to figure out how to use it :).  I'm struggling to figure out how to translate the step-by-step instructions on your main page into a set of configuration files (init.el plus maybe others to launch the rdm daemon?) to make it work.  Right now just putting "(require 'rtags)" in my init.el results in my getting 

    File mode specification error: (file-error "Searching for program" "no such file or directory" "rdm")

 in *Messages* at startup.

**Comment by Andersbakken** [comment]
Ah. That makes sense.

You need to make sure rdm is in your path. Otherwise you can set rtags-path
to the directory where it can be found.
Anders
