### ISSUE TITLE
README.org issues

### ISSUE THREAD

**Issue by panaseleus** [Andersbakken/rtags#483]
In [TLDR Quickstart](https://github.com/Andersbakken/rtags/blob/master/README.org#tldr-quickstart) line number `rdm.cpp:30` is out of sync.

Also it says `rtags-follow-symbol-at-point`, but I don't see this symbol now, perhaps should be `rtags-find-references-at-point`

**Comment by cslux** [comment]
@panaseleus, it should be `rtags-find-symbol-at-point` the `...follow...` has been renamed to `...find...`

**Comment by panaseleus** [comment]
Yes, `rtags-find-symbol-at-point`. I just copied wrong command (which I have tried too).
