### ISSUE TITLE
Invalid message version

### ISSUE THREAD

**Issue by dongz9** [Andersbakken/rtags#485]
Hi,

I followed the instructions on the project hompage to compile rtags. When I tried to call any rtags command within Emacs, rdm displayed the following messages:

Invalid message version. Got 97, expected 104 id: 33

I'm using libclang3.7. Any idea what's going on here?

**Comment by cslux** [comment]
Hey,

do you have a previous version installed?

**Comment by Andersbakken** [comment]
That's almost certainly what's going on. An old version of rc is talking to
a newer version of rdm.

Anders

**Comment by dongz9** [comment]
Problem solved. Thanks!

**Comment by KarateSnowMachine** [comment]
For people finding this issue via google, I wanted to add that this will happen also if you happen to build/run a newer version of `rdm` while an older version is still running. I used to `strace` to figure out that when the new `rdm` tried to open the socket, it would error out and segfault with a crazy stack trace.

**Comment by Andersbakken** [comment]
Yeah. That's kind of a known issue. I could maybe handle it more gracefully
I suppose.

Anders
