### ISSUE TITLE
rtags build failure

### ISSUE THREAD

**Issue by hhnr** [Andersbakken/rtags#486]
Rtags build fails, doesn't detect installed clang compiler

Steps followed.
$ git clone https://github.com/Andersbakken/rtags.git
$ cd rtags
$ cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=1
-- The C compiler identification is GNU
-- The CXX compiler identification is GNU
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- llvm-config executable found: /usr/bin/llvm-config
-- Using Clang version 2.9 from /usr/lib/llvm-2.9/lib with CXXFLAGS -I/usr/lib/llvm-2.9/include -D_GNU_SOURCE -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS
-- Found LibClang: -L/usr/lib/llvm-2.9/lib;-lclang;-Wl,-rpath,/usr/lib/llvm-2.9/lib
-- Found Curses: /usr/lib/x86_64-linux-gnu/libcurses.so
-- Looking for backtrace
-- Looking for backtrace - not found.
-- Looking for CLOCK_MONOTONIC_RAW
-- Looking for CLOCK_MONOTONIC_RAW - not found.
-- Looking for CLOCK_MONOTONIC
-- Looking for CLOCK_MONOTONIC - not found.
-- Looking for mach_absolute_time
-- Looking for mach_absolute_time - not found.
-- Looking for inotify_init
-- Looking for inotify_init - not found.
-- Looking for kqueue
-- Looking for kqueue - not found.
-- Looking for epoll_wait
-- Looking for epoll_wait - not found.
-- Looking for select
-- Looking for select - not found.
-- Looking for FD_CLOEXEC
-- Looking for FD_CLOEXEC - not found.
-- Looking for SO_NOSIGPIPE
-- Looking for SO_NOSIGPIPE - not found.
-- Looking for MSG_NOSIGNAL
-- Looking for MSG_NOSIGNAL - not found.
-- Looking for GetLogicalProcessorInformation
-- Looking for GetLogicalProcessorInformation - not found.
-- Looking for SCHED_IDLE
-- Looking for SCHED_IDLE - not found.
-- Looking for SHM_DEST
-- Looking for SHM_DEST - not found.
-- Performing Test HAVE_STATMTIM
-- Performing Test HAVE_STATMTIM - Failed
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.3.4")
-- checking for module 'openssl'
--   found openssl, version 1.0.1
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1..1")
-- Performing Test HAVE_CXX11
-- Performing Test HAVE_CXX11 - Failed
CMake Error at src/rct/rct.cmake:218 (message):
  C++11 support not detected.  rct requires a modern compiler, GCC >= 4.8 or
  Clang >= 3.2 should suffice
Call Stack (most recent call first):
  src/rct/CMakeLists.txt:2 (include)

-- Configuring incomplete, errors occurred!

Installed clang compiler details.
$ clang --version
Ubuntu clang version 3.4-1ubuntu3~precise2 (tags/RELEASE_34/final) (based on LLVM 3.4)
Target: x86_64-pc-linux-gnu
Thread model: posix

Ubuntu system
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:        12.04
Codename:       precise

**Comment by jhanssen** [comment]
The build is using GCC though. What does ```c++ -v``` say?

**Comment by hhnr** [comment]
The output of C++ -v
Using built-in specs.
COLLECT_GCC=c++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.6.3-1ubuntu5' --with-bugurl=file:///usr/share/doc/gcc-4.6/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.6 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.6 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --disable-werror --with-arch-32=i686 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5)

**Comment by jhanssen** [comment]
Right, you need GCC >= 4.8, though you could use clang to compile assuming you have it set up correctly. Try setting ```CC=clang CXX=clang++``` as environment variables when running cmake. You might have to blow away your cmake cache or start with a fresh build directory. If this doesn't work then there's probably a PPA you could add to get GCC 4.8 on your system.

**Comment by jhanssen** [comment]
Additionally, you might have to pass ```-DRCT_USE_LIBCXX=1``` as an argument to cmake, otherwise the build will use stdlibc++ and that could be too old as well.

**Comment by hhnr** [comment]
ok. Will try installing GCC 4.8.

**Comment by jhanssen** [comment]
Ok, feel free to reopen if you still have problems after that.
