### ISSUE TITLE
rdm error messages on Mac OS X

### ISSUE THREAD

**Issue by dongz9** [Andersbakken/rtags#488]
Hi,

I saw the following error messages today:

Trying to send message to unconnected client (2)
Trying to send message to unconnected client (2)
2015-10-27 16:07 rdm[1808](FSEvents.framework) FSEventStreamCreate: _FSEventStreamCreate: ERROR: CFStringGetCString() failed

I feel like rdm didn't start compiling util I opened one of the c++ files using Emacs (which took a really long time). Any idea what's going on here?

Thanks!

**Comment by Andersbakken** [comment]
The trying to send message to unconnected is really not an error so I just
turned that into a warning (not printed by default).

The FSEventStreamCreate is real and I've been meaning to look into it. Do
you know of a simple way to reproduce that?

I don't really understand the last one. Emacs will call use rc to talk to
rdm when it opens a new file and if rdm is busy this might cause delays but
rdm shouldn't generally be that busy. The vast majority of the work is done
by rp.

Anders
