### ISSUE TITLE
Rtags buffer leaves its window around sometimes

### ISSUE THREAD

**Issue by Nephyrin** [Andersbakken/rtags#489]
- Ask rtags for something with multiple results
- Without dismissing the rtags window, ask for something with one result.

The rtags buffer will vanish (rtags just jumps to the only match), but the small window it made will not, leaving me with a often five-line-tall superfluous window I need to select and close.

**Comment by Andersbakken** [comment]
Can you see if the new behavior seems better to you? I now kill the window as well.

**Comment by cslux** [comment]
Oooh was just about to create a PR, my solution was a bit different :-/ and very short. I'll leave it here and test yours now.

``` diff
1 file changed, 2 insertions(+)
src/rtags.el | 2 ++

modified   src/rtags.el
@@ -368,6 +368,8 @@ return t if rtags is allowed to modify this file."
 (defun rtags-get-buffer (&optional name)
   (unless name (setq name rtags-buffer-name))
   (when (get-buffer name)
+    (when (get-buffer-window name)
+      (delete-window (get-buffer-window name)))
     (kill-buffer name))
   (generate-new-buffer name))
```

**Comment by cslux** [comment]
Both work :-)! But your solution is clearly more robust.

**Comment by Nephyrin** [comment]
This seems to work perfectly now.

Thanks again for your work on this project, it has definitely increased my productivity.

**Comment by Andersbakken** [comment]
Glad to hear.

It's kinda been bugging me for a long time too but I've just somehow never
looked into fixing it.

Anders
