### ISSUE TITLE
Make rtags install easier

### ISSUE THREAD

**Issue by zhongweiy** [Andersbakken/rtags#493]
Hi, there, is it possible package rtags into a deb (or alike) package and make install process easier?

Because this is already my second trial of rtags after an unsuccessful trial several months ago. It takes me more than 5 hours to get rtags work (still with issues).

**Comment by cslux** [comment]
> Hi, there, is it possible package rtags into a deb (or alike) package and make install process easier?
> 
> Because this is already my second trial of rtags after an unsuccessful trial several months ago. It takes me more than 5 hours to get rtags work (still with issues).

What OS are you on? What commands did you enter (exactly) to install etc, that would be very helpful so we can improve the README etc. 

regards,
Christian

**Comment by zhongweiy** [comment]
Hi, Christian, here is  my detail:

OS is Ubuntu 14.04 LTS.

```
$wget https://github.com/Andersbakken/rtags-releases/raw/gh-pages/rtags.tar.bz2
$tar -xvf rtags.tar.bz2
$cd rtags && make build && cd build
$cmake ..
#cmake have no problem. GCC is 4.8.2
$make
[ 46%] Building CXX object src/CMakeFiles/rtags.dir/IndexMessage.cpp.o
In file included from /home/zhongwei/projects/read_learn/rtags_tar/rtags/src/RTags.h:21:0,
                 from /home/zhongwei/projects/read_learn/rtags_tar/rtags/src/IndexMessage.h:22,
                 from /home/zhongwei/projects/read_learn/rtags_tar/rtags/src/IndexMessage.cpp:16:
/home/zhongwei/projects/read_learn/rtags_tar/rtags/src/Location.h:24:27: fatal error: clang-c/Index.h: No such file or directory
 #include <clang-c/Index.h>
                           ^
compilation terminated.
make[2]: *** [src/CMakeFiles/rtags.dir/IndexMessage.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/rtags.dir/all] Error 2
make: *** [all] Error 2
```
I check `make VERBOSE=1` output, and find it is caused by:
```
cd /home/zhongwei/projects/read_learn/rtags_tar/rtags/build/src && /usr/bin/c++   -DCLANG_LIBDIR=/usr/lib/llvm-3.3/lib -DOS_Linux -DRTAGS_BIN=\"/home/zhongwei/projects/read_learn/rtags_tar/rtags/build/bin/\" -I/usr/lib/llvm-3.3/include  -DNDEBUG -D_GNU_SOURCE -D__S\
TDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS   -fomit-frame-pointer -fvisibility-inlines-hidden -fno-exceptions -fPIC -Woverloaded-virtual -Wcast-qual -std=c++0x -fpic -O3 -DNDEBUG -I/home/zhongwei/projects/read_learn/rtags_tar/rtags/src -I/home\
/zhongwei/projects/read_learn/rtags_tar/rtags/src/rct/include -I/home/zhongwei/projects/read_learn/rtags_tar/rtags/src/rct -I/home/zhongwei/projects/read_learn/rtags_tar/rtags/build/src/rct/include/rct    -Wall -o CMakeFiles/rtags.dir/IndexMessage.cpp.o -c /home/zh\
ongwei/projects/read_learn/rtags_tar/rtags/src/IndexMessage.cpp
```
And after some search, it turns out that llvm-config does not return correct value:
```
$llvm-config --cxxflags
-I/usr/lib/llvm-3.3/include  -DNDEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -g -O2 -fomit-frame-pointer -fvisibility-inlines-hidden -fno-exceptions -fPIC -Woverloaded-virtual -Wcast-qual
$ls /usr/lib/llvm-3.3/include
llvm  llvm-c
$ls /usr/lib/llvm-3.4/include
clang  clang-c  llvm  llvm-c
```
I don't know what happened to llvm-config on my system. So I try to manually setup following flags:
```
$cmake -DLIBCLANG_LIBDIR=/usr/lib/llvm-3.4/lib -DLIBCLANG_CXXFLAGS="-I/usr/lib/llvm-3.4/include  -DNDEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -g -O2 -fomit-frame-pointer -fvis\
ibility-inlines-hidden -fno-exceptions -fPIC -Woverloaded-virtual -Wcast-qual" ..
-- llvm-config found at: /usr/bin/llvm-config
CMake Error at cmake/FindLibClang.cmake:41 (message):
  Could NOT find clang libdir.  You can fix this by setting CLANG_LIBDIR in
  your shell or as a cmake variable.
Call Stack (most recent call first):
  src/CMakeLists.txt:41 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/zhongwei/projects/read_learn/rtags_tar/rtags/build/CMakeFiles/CMakeOutput.log".
See also "/home/zhongwei/projects/read_learn/rtags_tar/rtags/build/CMakeFiles/CMakeError.log".
```
Cmake seems need `CLANG_LIBDIR` not `LIBCLANG_LIBDIR` (same to `LIBCLANG_CXXFLAGS`) and I does not find what `LIBCLANG_LIBRARIES` should be on my system, just omit it.
```
$cmake -DCLANG_LIBDIR=/usr/lib/llvm-3.4/lib -DCLANG_CXXFLAGS="-I/usr/lib/llvm-3.4/include  -DNDEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -g -O2 -fomit-frame-pointer -fvisibi\
lity-inlines-hidden -fno-exceptions -fPIC -Woverloaded-virtual -Wcast-qual" ..
```
Finally, it build without problem.
If it could be installed by package system like: apt-get install rtags, it will be much easier for users.

**Comment by cslux** [comment]
Hey @zhongweiy!

I see now whats going on here. 

Interesting, you seem to have two version of llvm installed!, there is definitely something wrong with your system, not with rtags.

Maybe you could try this to see if there are multiply version installed.
``` bash
dpkg --get-selections | grep -i llvm
```

Unfortunately, I do not have Ubuntu installed on one have my computers, but from a bit googeling (not sure if this word exists :-). It is probably, as I already said, a problem that you have installed multiply version of llvm, but you can reconfigure the hole thing, see http://kwangyulseo.com/2014/02/05/using-multiple-llvm-versions-on-ubuntu/. On fedora you can do similar stuff with the tool `alternatives`. 

> Cmake seems need CLANG_LIBDIR not LIBCLANG_LIBDIR (same to LIBCLANG_CXXFLAGS) and I does not find what LIBCLANG_LIBRARIES should be on my system, just omit it.

We changed the name from `CLANG_....` to `LIBCLANG_....`, to follow the cmake, "FindLib....` convention. The release tarball you have downloaded is already a view month old, so I recommend you whenever you download a tarball from the web, to consult the included README file ;-), not the latest one.

> If it could be installed by package system like: apt-get install rtags, it will be much easier for users.

True, I already thought about it, but as always, somebody has the write and maintain the hole stuff etc., so I don't think that will happen anytime soon. 

If you have git installed, you can use the latest version of rtags if you like, since many changes and bug fixes have been added.

QUICK GUIDE:
``` bash
git clone https://github.com/Andersbakken/rtags.git
cd rtags
git submodule init
git submodule update
mkdir build 
cd build 
cmake ..
make 
sudo make install
```

Christian

**Comment by zhongweiy** [comment]
> so I recommend you whenever you download a tarball from the web, to consult the included README file ;-), not the latest one.

Thanks, nice tip!

I finally remove all llvm versions and install only one, and it can build the master version of rtags successfully now. And installing rtags as the dependency of [Malinka](https://github.com/LefterisJP/malinka) by el-get also works like a charm!

**Comment by cslux** [comment]
Cool! Glad I could help!

**Comment by jclosure** [comment]
In Ubuntu 14.04, I use g++.  In order to compile rtags, I had to install llvm-3.9.  Use whichever version of llvm you prefer.

```bash
sudo apt-get install clang-3.9 llvm-3.9 libclang-3.9-dev
```

Then change add it to to alternatives.

```bash
sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang 100
sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 100
```

Now temporarily switch to clang++

```bash
sudo update-alternatives --config c++
```

Ensure that clang++ is set to auto

Then build rtags

```bash
cmake -DLIBCLANG_LIBDIR=/usr/lib/llvm-3.9/lib  -DLIBCLANG_CXXFLAGS="-I/usr/lib/llvm-3.9/include -I/usr/lib/llvm-3.9/include/clang-c  -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS" -DCMAKE_EXPORT_COMPILE_COMMANDS=1 .
make
```

Now switch the default back to g++

```bash
sudo update-alternatives --config c++
```

Ensure that g++ is set to auto

**Comment by Andersbakken** [comment]
I think it should build with gcc 4.8 again now. We use a third party json
library that requires gcc >= 4.9 and I think 4.8 is the system compiler on
ubuntu 14.04. I've made that component optional for now (with a compile
time test).

Anders
