### ISSUE TITLE
"Could NOT find llvm-config executable"

### ISSUE THREAD

**Issue by ville-h** [Andersbakken/rtags#494]
On arch linux if i don't have extra/llvm installed i get the following error `cmake ..`:
CMake Error at cmake/FindLibClang.cmake:57 (message):
  Could NOT find llvm-config executable.
Call Stack (most recent call first):
  src/CMakeLists.txt:30 (find_package)

Not sure if this means llvm should be listed as a dependency as well.

**Comment by cslux** [comment]
Actually in the readme stands  that llvm-config will be used to retrieve certain information about clang.
https://github.com/Andersbakken/rtags#finding-clang

But maybe we should add a note also in the prerequisites section.

**Comment by cslux** [comment]
llvm-config will only be used if the user does not provide the information explained under [finding-clang](https://github.com/Andersbakken/rtags#finding-clang), i.e. llvm-config is not a dependency in a broader sense, it is just a convenient tool to get the needed information without user interaction.

**Comment by Andersbakken** [comment]
Does arch provide any other means to query the paths and flags for libclang? 

Maybe we could fall back to pkg-config if it's available. 

Anders

**Comment by cslux** [comment]
@ville-h Is this issue solved for you?

**Comment by engsbk** [comment]
same issue
please assist

**Comment by Andersbakken** [comment]
Do you not have an llvm-config on your system? We generally use this to
find includepaths/libs etc for clang/llvm.

If you have llvm-config but it isn't in your path you can either specify
the location of it using:

cmake -DLIBCLANG_LLVM_CONFIG_EXECUTABLE=/path/to/llvm-config ...

or PATH=/path/to/llvm-config:$PATH cmake ...

Anders

**Comment by engsbk** [comment]
I did not have it so I installed it and it was solved.

Thanks for taking the time to read this,
Shaikhah B. Alkhadhr

On Mar 26, 2017, at 2:57 AM, Anders Bakken <notifications@github.com<mailto:notifications@github.com>> wrote:

Do you not have an llvm-config on your system? We generally use this to
find includepaths/libs etc for clang/llvm.

If you have llvm-config but it isn't in your path you can either specify
the location of it using:

cmake -DLIBCLANG_LLVM_CONFIG_EXECUTABLE=/path/to/llvm-config ...

or PATH=/path/to/llvm-config:$PATH cmake ...

Anders

**Comment by Andersbakken** [comment]
My pleasure. Glad to hear you got it work.

Anders

On Sat, Mar 25, 2017 at 11:12 PM, Shaikha Alkhuder <notifications@github.com
> wrote:

> I did not have it so I installed it and it was solved.
>
> Thanks for taking the time to read this,
> Shaikhah B. Alkhadhr
>
> On Mar 26, 2017, at 2:57 AM, Anders Bakken <notifications@github.com<
