### ISSUE TITLE
cl-lib error when building on OS X 10.11

### ISSUE THREAD

**Issue by joeroback** [Andersbakken/rtags#498]
I don't use emacs, I use vim. I've been compiling and updating rtags for months. Recently something in the build changed related to cl-lib. Not sure what that is exactly. Not sure how to tell the build system to not build the emacs bytecode either..

```
git clone --recurse-submodules https://github.com/Andersbakken/rtags.git
cd rtags
mkdir build
cd build

export CXXFLAGS='-march=native -O2 -g'
export LLVM_CONFIG=llvm-config-mp-3.6
export CC=/opt/local/bin/clang-mp-3.6
export CXX=/opt/local/bin/clang++-mp-3.6
export CXXFLAGS='-march=native -O2 -g'
export LLVM_CONFIG=/opt/local/bin/llvm-config-mp-3.6

cmake -G Ninja ..
ninja
```

Results in

```
...
-- 
-- The following OPTIONAL packages have been found:

 * ZLIB
 * OpenSSL

-- The following REQUIRED packages have been found:

 * LibClang
 * Curses

-- Configuring done
-- Generating done
CMake Warning (dev):
  Policy CMP0058 is not set: Ninja requires custom command byproducts to be
  explicit.  Run "cmake --help-policy CMP0058" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  This project specifies custom command DEPENDS on files in the build tree
  that are not specified as the OUTPUT or BYPRODUCTS of any
  add_custom_command or add_custom_target:

   src/company-rtags.el
   src/rtags-ac.el
   src/rtags.el

  For compatibility with versions of CMake that did not have the BYPRODUCTS
  option, CMake is generating phony rules for such files to convince 'ninja'
  to build.

  Project authors should add the missing BYPRODUCTS or OUTPUT options to the
  custom commands that produce these files.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Build files have been written to: /Users/jroback/Downloads/src/rtags/build
[63/9/1] Creating byte-compiled Emacs lisp /Users/jroback/Downloads/src/rtags/build/src/rtags.elc
FAILED: cd /Users/jroback/Downloads/src/rtags/build/src && /usr/bin/emacs -batch -l /Users/jroback/Downloads/src/rtags/src/compile-shim.el -l /Users/jroback/Downloads/src/rtags/src/rtags.el -f batch-byte-compile /Users/jroback/Downloads/src/rtags/build/src/rtags.el
Cannot open load file: cl-lib
[63/8/2] Creating byte-compiled Emacs lisp /Users/jroback/Downloads/src/rtags/build/src/company-rtags.elc
FAILED: cd /Users/jroback/Downloads/src/rtags/build/src && /usr/bin/emacs -batch -l /Users/jroback/Downloads/src/rtags/src/compile-shim.el -l /Users/jroback/Downloads/src/rtags/src/rtags.el -f batch-byte-compile /Users/jroback/Downloads/src/rtags/build/src/company-rtags.el
Cannot open load file: cl-lib
[63/7/3] Creating byte-compiled Emacs lisp /Users/jroback/Downloads/src/rtags/build/src/rtags-ac.elc
FAILED: cd /Users/jroback/Downloads/src/rtags/build/src && /usr/bin/emacs -batch -l /Users/jroback/Downloads/src/rtags/src/compile-shim.el -l /Users/jroback/Downloads/src/rtags/src/rtags.el -f batch-byte-compile /Users/jroback/Downloads/src/rtags/build/src/rtags-ac.el
Cannot open load file: cl-lib
[63/0/10] Building CXX object src/CMakeFiles/rtags.dir/RTags.cpp.o
ninja: build stopped: subcommand failed.
```

**Comment by cslux** [comment]
@joeroback,

You can set the variable `RTAGS_NO_ELISP_BYTECOMPILE` to `TRUE`. We have lately added the functionality to byte-compile the elisp code. We add something to the README on how to disable it. 

Thanks for the report!

Christian

**Comment by Andersbakken** [comment]
Ah. I can see that being a pain. 

I just added a cmake switch to not build the elisp.

If you run cmake like so:

cmake -DRTAGS_NO_ELISP=1

It shouldn't do that anymore. 

Does this work for you?

We should probably detect the version of emacs in cmake and if it's too old (this is the case for you I think) not build it. I'll look into fixing that.

Anders

**Comment by cslux** [comment]
@joeroback One more note, the variable `LLVM_CONFIG` has been renamed to `LIBCLANG_LLVM_CONFIG_EXECUTABLE`.

**Comment by joeroback** [comment]
With -DRTAGS_NO_ELISP=1 everything is back to compiling! Thanks! That was fast!
BTW, I am using cmake 3.3.2, but i am sure my emacs (OSX default) is ancient.

Only issue now is that it appears the default install path was changed from /usr/local/bin to /usr/bin, which by default on OS X 10.11 is sandboxed even when run with sudo.

Once I added -DCMAKE_INSTALL_PREFIX:PATH=/usr/local to the cmake call everything installed.

**Comment by cslux** [comment]
True that changed too, I'll add a conditional to install the binaries on OS
X into /usr/local by default and on GNU/Linux systems into /usr.

**Comment by cslux** [comment]
@joeroback 
Could you please tell me where the bash completion files are getting installed on OS X by default.  Is `/usr/local` the prefix of homebrew? 

Thanks,
Christian

**Comment by joeroback** [comment]
hrmm. I don't use the bash completion feature, nor do I use HomeBrew. I use MacPorts, because I like that everything is sandboxed off into "/opt/local" by default, and you can setup your PATH to either prefer MacPorts binaries or system binaries.

I could still experiment or look for something specific if you need. Just let me know.

**Comment by joeroback** [comment]
for MacPorts, if you install bash-completions, it will go to /opt/local prefix..

**Comment by cslux** [comment]
So the completions are located under /opt/local/share/bash-completion/completions, right?

**Comment by Andersbakken** [comment]
I just reverted my fix since Christian's solution already was in there (and doing exactly the same).

In other words, to disable byte compiling of elisp use cmake -DRTAGS_NO_ELISP_BYTECOMPILE=1  

not cmake -DRTAGS_NO_ELISP=1

**Comment by joeroback** [comment]
@cslux 
```
$ pwd
/opt/local/share/bash-completion/completions

$ ls -lsa
total 152
  0 drwxr-xr-x  8 root  admin    272 Oct 31 09:05 .
  0 drwxr-xr-x  3 root  admin    102 Oct  2 17:56 ..
  8 -rw-r--r--  1 root  admin   1389 Oct 19 09:17 gapplication
  8 -rw-r--r--  1 root  admin    935 Oct 19 09:17 gdbus
112 -rw-r--r--  1 root  admin  56618 Oct 31 09:05 git
  8 -rw-r--r--  1 root  admin   1356 Oct 19 09:17 gresource
  8 -rw-r--r--  1 root  admin   2609 Oct 19 09:17 gsettings
  8 -rw-r--r--  1 root  admin   1940 Oct  3 11:36 pdfgrep
```

**Comment by cslux** [comment]
@joeroback 

Cool thanks! I changed the install path back to the original, i.e. the prefix is again /usr/local.
And the bash completion files will now be installed into PREFIX/share/bash-completion/completions. 

A substitute the prefix, which pkg-config returns for the bash-completion package, with CMAKE_INSTALL_PREFIX. But the install path can be changed to what ever you like, via the BASH_COMPLETION_COMPLETIONSDIR cmake variable.

Thanks again,
Christian

**Comment by Andersbakken** [comment]
Hi Christian

I guess we should make the elisp install thing dependent on having emacs >=
23 (I think that's the minimum requirement). Feel like taking a crack at
that?

Anders

**Comment by cslux** [comment]
Date: Sun, 01 Nov 2015 18:42:35 +0100
Message-ID: <8737wp39bo.fsf@gmail.com>
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 8bit
--text follows this line--

**Comment by cslux** [comment]
> Feel like taking a crack at that?

Sure, I can do that.

**Comment by Andersbakken** [comment]
Thanks.

**Comment by joeroback** [comment]
Tried today without RTAGS_NO_ELISP_BYTECOMPILE (as the emacs that ships with 10.11 is 22.1.1) and everything worked.

**Comment by cslux** [comment]
Thank you for the feedback!

Christian
