### ISSUE TITLE
"Failed to find node" error messages

### ISSUE THREAD

**Issue by pradhanpk** [Andersbakken/rtags#509]
After creating a new source file and adding it to the compile_commands.json, I see a repeated errors of this sort when `rdm` is processing an `rc` query:

```
Failed to open cache/path/symnames new/file/added.cpp
Looking for new/file/added.cpp
Failed to find node for new/file/added.cpp
```

While I am not sure if this is a real issue, I wanted to report this to you guys since multiple such messages in the *same* `rc` query sounds wrong.

I am using a recent rtags(HEAD 57d58f749da976d9a61116b6c5395feeceb74366) and have the change which tracks changes in compile_commands.json.

**Comment by Andersbakken** [comment]
Sorry about the late reply. It's not really a real issue. I've changed the message a little to make it clearer that it's not really a problem.
