### ISSUE TITLE
"No project" error from rc. How to help rtags find the project?

### ISSUE THREAD

**Issue by mwbuksas** [Andersbakken/rtags#510]
I have rtags built and working, and my project is indexed. When I attempt rtags commands from emacs however, rc responds with a "Failed to make location from" error message and "No Project". e.g.:

```/usr/local/bin/rc --current-file=/somepath/foo.cpp -f /somepath/foo.cpp:265:6: -K --symbol-info-exclude-targets --symbol-info-exclude-references
Failed to make location from [/somepath/foo.cpp:265:6]```

This worked like a charm when I was using ```cmake-ide```, but I had to abandon it because the size of my project is overloading it.  Perhaps my project structure is atypical enough to throw off rtags' built-in project search?

How do I manually configure rtags to find the project?

Thanks!

**Comment by Andersbakken** [comment]
Hi Michael

Normally this means the file hasn't been indexed at all. Are there by any
chance symlinks involved?

What does rc -w say?

Anders

**Comment by autosquid** [comment]
Hi, I met the same problem today. 

what info. do you need for debugging -- glad to provide.

I run `rc -J` in a build dir in a cmake project (compile_commands.json is generated correctly) which is versioned with git. (.git dir is in the project dir)

but `rc -w` outputs no project.

Do I need manually "create a project"?

**Comment by autosquid** [comment]
ok, I found my problem with `rdm -v`:

```
Source::parse Nothing looks like a compiler /usr/local/bin/clang-omp++
```

what can I do then?

**Comment by autosquid** [comment]
I checked related code on deciding if something is a compiler, would it be a  better way to decide by  the result of "compiling" a snippet with it?

**Comment by mwbuksas** [comment]
I shouldn't have left this issue open. The project _hadn't_ been indexed yet, so my original problem was self-caused. Apologies for not following up on it.

autosquid, you should open your own ticket with the issue you're experiencing, because mine should be closed at this point.

**Comment by autosquid** [comment]
@mwbuksas  y, feel free to close it. I'll open a new issue. :)
