### ISSUE TITLE
Problems storing rdm database on NFS?

### ISSUE THREAD

**Issue by cleeland** [Andersbakken/rtags#512]
Ever since moving forward to a build that is the latest from master, my rtags is not working.  Specifically, from within emacs, searching, for example, for references to a function where the references are mostly in the same file, I get a message that says "RTags: No results".

I'm not really sure how to interpret the output in the rdm log file.  I see a lot of messages like 

/full/path/to/my/sourcefile.cpp is already running

Additionally, when I look at the output of "rc -s", I see at the end that there are several files in the "Active" list with status "0x11, Dirty, Running"...and that list never changes.  It also doesn't look like any of the "rp" subprocesses of rdm ever make any progress.

What I have found is that if I change my rdm data directory from being stored on an NFS mounted volume to one stored locally (e.g., in /tmp), that everything seems to work just fine.

When the 'rp' processes are using NFS and are "stuck", the output of lsof(1m) shows each of them having a substantial number (50-60?) of PIPE file descriptors open.  Also, process state of each of them is either "signal" or "rpc_wait":

0 D 10680 23955 23867  0  80   0 - 35756 rpc_wa pts/1    00:00:00 rp
0 D 10680 23965 23867  0  80   0 - 36600 rpc_wa pts/1    00:00:01 rp
0 D 10680 23967 23867  0  80   0 - 52495 rpc_wa pts/1    00:00:02 rp
0 D 10680 23969 23867  0  80   0 - 37919 rpc_wa pts/1    00:00:00 rp
0 D 10680 23973 23867  0  80   0 - 34789 rpc_wa pts/1    00:00:00 rp
0 D 10680 23975 23867  0  80   0 - 34210 rpc_wa pts/1    00:00:00 rp
0 D 10680 23979 23867  0  80   0 - 63937 rpc_wa pts/1    00:00:04 rp
0 D 10680 23981 23867  0  80   0 - 58865 rpc_wa pts/1    00:00:02 rp
0 D 10680 23983 23867  0  80   0 - 35781 rpc_wa pts/1    00:00:01 rp
0 D 10680 23991 23867  0  80   0 - 58286 rpc_wa pts/1    00:00:02 rp
0 D 10680 23993 23867  0  80   0 - 66763 rpc_wa pts/1    00:00:04 rp
0 D 10680 23995 23867  0  80   0 - 67838 rpc_wa pts/1    00:00:04 rp
0 D 10680 23997 23867  0  80   0 - 35894 rpc_wa pts/1    00:00:00 rp
0 D 10680 23999 23867  0  80   0 - 35332 rpc_wa pts/1    00:00:01 rp
0 T 10680 24001 23867  0  80   0 - 38566 signal pts/1    00:00:00 rp
0 D 10680 24003 23867  0  80   0 - 55215 rpc_wa pts/1    00:00:02 rp
0 D 10680 24009 23867  0  80   0 - 38620 rpc_wa pts/1    00:00:01 rp
0 D 10680 24010 23867  0  80   0 - 37014 rpc_wa pts/1    00:00:00 rp
0 D 10680 24013 23867  0  80   0 - 41112 rpc_wa pts/1    00:00:01 rp
0 D 10680 24015 23867  0  80   0 - 34692 rpc_wa pts/1    00:00:00 rp
0 D 10680 24211 23867  0  80   0 - 34559 rpc_wa pts/1    00:00:00 rp
0 D 10680 25036 23867  0  80   0 - 55230 rpc_wa pts/1    00:00:02 rp
0 D 10680 25189 23867  0  80   0 - 42512 rpc_wa pts/1    00:00:01 rp
0 D 10680 25286 23867  0  80   0 - 36062 rpc_wa pts/1    00:00:00 rp
0 D 10680 25626 23867  0  80   0 - 36945 rpc_wa pts/1    00:00:00 rp
0 D 10680 26019 23867  0  80   0 - 35575 rpc_wa pts/1    00:00:01 rp
0 D 10680 26516 23867  0  80   0 - 35069 rpc_wa pts/1    00:00:00 rp
0 D 10680 26584 23867  1  80   0 - 62192 rpc_wa pts/1    00:00:02 rp
0 D 10680 26669 23867  0  80   0 - 38201 rpc_wa pts/1    00:00:00 rp
0 D 10680 27250 23867  0  80   0 - 37581 rpc_wa pts/1    00:00:01 rp
0 D 10680 27713 23867  2  80   0 - 61328 rpc_wa pts/1    00:00:02 rp
0 D 10680 30370 23867  2  80   0 - 35404 rpc_wa pts/1    00:00:00 rp

Any suggestions on how to start debugging?

**Comment by Andersbakken** [comment]
Hi

I think the best thing to do would be to just attach to one of the rp
processes that are stuck with gdb -p and see what they are up to.

We don't call pipe(2) ourselves in rp more than once so likely some of
these pipes are created by clang.

Let me know what you find. In general rtags is very very file system heavy
(lots of mmap'ing of files) so NFS is likely to have performance problems
even if we can fix the problem that it gets stuck.

Anders

**Comment by cleeland** [comment]
When the processes are in this state, they are stuck in "D" state, and neither gdb nor strace can attach to them since they are not interruptible.

You indicate that rtags is FS-heavy (due to mmap'ing); does that apply to rp?

mmap of an nfs file can be fine as long as there is enough memory on the box to support filesystem caching.

**Comment by Andersbakken** [comment]
rp doesn't mmap, but it does open and write to a lot of files. There's also
file locking going on. Note that we fixed a rather serious bug in the file
locking today. It's conceivable that it could impact this. Can you try to
sync?

Anders

**Comment by cleeland** [comment]
I'll try a pull and see if it addresses the issue.

Locking on nfs volumes is pretty heinous performance-wise.

On Thu, Nov 12, 2015 at 11:57 PM, Anders Bakken <notifications@github.com>
wrote:

> rp doesn't mmap, but it does open and write to a lot of files. There's also
> file locking going on. Note that we fixed a rather serious bug in the file
> locking today. It's conceivable that it could impact this. Can you try to
> sync?
>
> Anders
>
> On Thu, Nov 12, 2015 at 9:06 AM, Chris Cleeland <notifications@github.com>
> wrote:
>
> > When the processes are in this state, they are stuck in "D" state, and
> > neither gdb nor strace can attach to them since they are not
> interruptible.
> >
> > You indicate that rtags is FS-heavy (due to mmap'ing); does that apply to
> > rp?
> >
> > mmap of an nfs file can be fine as long as there is enough memory on the
> > box to support filesystem caching.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Andersbakken/rtags/issues/512#issuecomment-156167992
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Andersbakken/rtags/issues/512#issuecomment-156331047>.
>



-- 
Chris Cleeland

**Comment by Andersbakken** [comment]
We could make it an option to just not lock (and hope for the best, rdm
would possibly crash). I don't suppose storing the database on a
non-network drive is an option?

Anders

**Comment by cleeland** [comment]
On Sat, Nov 14, 2015 at 11:20 AM, Anders Bakken <notifications@github.com>
wrote:

> We could make it an option to just not lock (and hope for the best, rdm
> would possibly crash). I don't suppose storing the database on a
> non-network drive is an option?
>

On some machines local filesystem is only the boot device and /tmp.  Not my
design.

-- 
Chris Cleeland

**Comment by Andersbakken** [comment]
Yeah. I can see how that might be problematic.

I just added an option to rdm to not do file locking.  --no-file-lock

Can you see if helps?

Anders

**Comment by cleeland** [comment]
I'll give it a try. What does the locking prevent?

On Sunday, November 15, 2015, Anders Bakken <notifications@github.com>
wrote:

> Yeah. I can see how that might be problematic.
>
> I just added an option to rdm to not do file locking. --no-file-lock
>
> Can you see if helps?
>
> Anders
>
> On Sat, Nov 14, 2015 at 12:03 PM, Chris Cleeland <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > On Sat, Nov 14, 2015 at 11:20 AM, Anders Bakken <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> > > We could make it an option to just not lock (and hope for the best, rdm
> > > would possibly crash). I don't suppose storing the database on a
> > > non-network drive is an option?
> > >
> >
> > On some machines local filesystem is only the boot device and /tmp. Not
> my
> > design.
> >
> > --
> > Chris Cleeland
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Andersbakken/rtags/issues/512#issuecomment-156742921
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Andersbakken/rtags/issues/512#issuecomment-156861578>.
>


-- 
Chris Cleeland

**Comment by Andersbakken** [comment]
We're basically writing files from rp potentially at the same that we're
reading them (mmap'ing) them in rdm. It's not that likely but can
definitely lead to crashes without the locking.

Given that the locking until recently was broken I don't think these
problems are altogether likely though.

Anders

**Comment by cleeland** [comment]
Maybe have a different strategy for this so that they're never contending
for the same file? Rdm can unlink the file after its mmap'd so that it
can't be overwritten. Rp can communicate completion back to rdm after which
time rdm unmaps, closes, then goes thru mmap/unlink.

On Sunday, November 15, 2015, Anders Bakken <notifications@github.com>
wrote:

> We're basically writing files from rp potentially at the same that we're
> reading them (mmap'ing) them in rdm. It's not that likely but can
> definitely lead to crashes without the locking.
>
> Given that the locking until recently was broken I don't think these
> problems are altogether likely though.
>
> Anders
>
> On Sun, Nov 15, 2015 at 4:28 PM, Chris Cleeland <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > I'll give it a try. What does the locking prevent?
> >
> > On Sunday, November 15, 2015, Anders Bakken <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> > > Yeah. I can see how that might be problematic.
> > >
> > > I just added an option to rdm to not do file locking. --no-file-lock
> > >
> > > Can you see if helps?
> > >
> > > Anders
> > >
> > > On Sat, Nov 14, 2015 at 12:03 PM, Chris Cleeland <
> > notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>>
> > > wrote:
> > >
> > > > On Sat, Nov 14, 2015 at 11:20 AM, Anders Bakken <
> > > notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>>
> > > > wrote:
> > > >
> > > > > We could make it an option to just not lock (and hope for the best,
> > rdm
> > > > > would possibly crash). I don't suppose storing the database on a
> > > > > non-network drive is an option?
> > > > >
> > > >
> > > > On some machines local filesystem is only the boot device and /tmp.
> Not
> > > my
> > > > design.
> > > >
> > > > --
> > > > Chris Cleeland
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > https://github.com/Andersbakken/rtags/issues/512#issuecomment-156742921
> > > >.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/Andersbakken/rtags/issues/512#issuecomment-156861578
> > >.
> > >
> >
> >
> > --
> > Chris Cleeland
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Andersbakken/rtags/issues/512#issuecomment-156878827
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Andersbakken/rtags/issues/512#issuecomment-156889046>.
>


-- 
Chris Cleeland

**Comment by Andersbakken** [comment]
Hi Chris

The problem is that we don't really know if rp is in the process of writing
this file or not. 99% of the time the file will not be modified by rp at
that exact time.

We could implement file locking over ipc so that rp would more or less
request a write lock from rdm and only open the file after it gets a
response.

(Note also that we just fixed another race in the locking code).

Have you been able to try with --no-file-lock to see if this makes a big
impact on the performance?


Anders

**Comment by cleeland** [comment]
I just got a chance to try the latest (ffeda6829a5f49ff9d2aed52e351ffdf4fe11fa8) over NFS again.  The rp processes were not in rpc_wait, but neither was any progress made whatsoever.  I switched back to /tmp (non-NFS) and things ripped along.

I tried using strace on a few of the rp processes to see what they were doing, and strace hung attaching. That typically means some sort of iowait issue.

**Comment by Andersbakken** [comment]
Hi Chris

Yeah. I'm assuming the slowness is due to file system contention of some
sort. Were you able to try the --no-file-lock argument?

Also. Whenever a job finishes rdm prints some information about it. E.g.

[ 95%] 58/61 09:08:03 ~/dev/rtags/src/DependenciesJob.cpp in 3510ms. (51
syms, 44 symNames, 5 includes, 1 of 605 files, symbols: 68 of 32014, 0
queried) (3464/41/2ms). (priority 0)

This indicates that clang_parseTranslationUnit took 3464ms,
clang_visitChildren (so basically our logic to index the files) took 41 ms
and that the writing of files to ~/.rtags/... took 2 ms.

What do these numbers typically look like on your system?

Anders

**Comment by flv0** [comment]
Since I got hit by the same problem, here some numbers:

NFS with file-lock:
[100%] 1/1 15:34:23 /data/anasynth/schmitz/development/ircam/ILF/Tests/ilfTestApplication/JuceLibraryCode/juce_gui_basics.cpp in 4104ms. (6 syms, 8 symNames, 2 includes, 2 of 692 files, symbols: 4 of 22740, 23083 cursors, 1 queried 0ms) (2461/221/1420ms) (dirty). (priority 1)

NFS --no-file-lock:
[100%] 1/1 15:36:10 /data/anasynth/schmitz/development/ircam/ILF/Tests/ilfTestApplication/JuceLibraryCode/juce_gui_basics.cpp in 5339ms. (6 syms, 8 symNames, 2 includes, 2 of 692 files, symbols: 4 of 22740, 23083 cursors, 1 queried 0ms) (1792/222/3322ms) (dirty). (priority 1)

Local with lock:
[100%] 1/1 15:37:43 /data/anasynth/schmitz/development/ircam/ILF/Tests/ilfTestApplication/JuceLibraryCode/juce_gui_basics.cpp in 1964ms. (6 syms, 8 symNames, 2 includes, 2 of 692 files, symbols: 4 of 22740, 23083 cursors, 1 queried 0ms) (1733/227/1ms) (dirty). (priority 1)

Local --no-file-lock:
[100%] 1/1 15:38:30 /data/anasynth/schmitz/development/ircam/ILF/Tests/ilfTestApplication/JuceLibraryCode/juce_gui_basics.cpp in 1939ms. (6 syms, 8 symNames, 2 includes, 2 of 692 files, symbols: 4 of 22740, 23083 cursors, 1 queried 0ms) (1732/203/2ms) (dirty). (priority 1)

HTH

**Comment by Andersbakken** [comment]
Interesting numbers. It seems like the file lock, while slow, actually
improved write performance over NFS.

Anders
