### ISSUE TITLE
too many open files

### ISSUE THREAD

**Issue by dmakarov** [Andersbakken/rtags#514]
When ```rdm``` is set up to run on demand by ```launchd``` on OS X, ```rc``` quickly opens too many files for a file in a sufficiently large project (e.g. LLVM source tree).
```
Failed to open .../llvm/include/llvm/InitializePasses.h Too many open files
```
It's not very straightforward to change the limit of open files for processes started by ```launchd``` in OS X versions newer 10.9, since ```/etc/launchd.conf``` is no longer read by ```launchd```.  For example, adding
```
    <key>HardResourceLimits</key>
    <dict>
      <key>NumberOfFiles</key>
      <integer>65536</integer>
    </dict>
```
to ```~/Library/LaunchAgents/com.andersbakken.rtags.agent.plist``` doesn't help because the child processes of ```launchd``` can't seem to have more than 256 open files which is a limit of open files for ```launchd``` itself.  The latter can be changed with ```sudo launchctl limit maxfiles 65536 65536``` for example, but that is not very convenient and requires ```rdm``` restart.

So, it would be nice to close files in ```FileMap``` objects  (or destroy the objects?) as soon as they don't need to be open, thus reducing the number of simultaneously open files.

**Comment by Andersbakken** [comment]
There's actually a setting for this. 

Can you try to put this into your ~/.rdmrc

--max-file-map-cache-size=200

Or something to that effect.

**Comment by dmakarov** [comment]
Yes, ```--max-file-map-cache-size=200``` helps.  This issue can be closed. Thank you.

**Comment by Andersbakken** [comment]
Glad to hear. Let me know if you run into other issues.
