### ISSUE TITLE
Would be amazing if rtags-find-references-at-point had rtags-references-tree functionality

### ISSUE THREAD

**Issue by Nephyrin** [Andersbakken/rtags#515]
I briefly changed my "find references" bind to `rtags-references-tree` since the tree-mode stuff is super helpful, but it loses the other-window magic of e.g. rtags-find-references-at-point, where it is opened as a minimal other window with hotkeys to jump between matches. If I could keep the latter behavior, but optionally focus the references window and commence tab completions, my life would be complete.

**Comment by Andersbakken** [comment]
Ah right. I kinda never finished the work on references-tree. My intention indeed was to unify all of that behavior into rtags-find-references-at-point. I'll try to get back to that.

**Comment by Andersbakken** [comment]
I've put some work into this. It should behave more like
rtags-references-at-point now. Can you try it out again?

Anders

**Comment by Nephyrin** [comment]
Used this a bit yesterday and it seems much better. My only gripe is the "Called from:" text is not aligned, so it can be hard to quickly parse multiple results. Overall though, it's basically a straight upgrade from references-at-point.

Thanks for your work on this!

**Comment by Andersbakken** [comment]
Ah. Good idea. I added something. Can you check if it works for you?

Anders

**Comment by Nephyrin** [comment]
Better than before, with a few issues:
- The buffer often ends up at 2x of your codebase's line width limit, and if said limit is not strictly enforced, errant extra-long lines can make the aligned column 240+ chars out
- One codebase I'm using, rather unfortunately, uses tabs, which break the alignment

An option to to make these use multiple lines, or perhaps ignore the 95th percentile of line lengths (so the random 150 char line would just have a mis-aligned label) might make this better. It is definitely a lot of text to fit in to a readable display so there might not be a perfect solution.

I am using this as my bind in lieu of find-references-at-point, so I will let you know if I run into any other issues. Overall, it is much more useful.

**Comment by Andersbakken** [comment]
I tried to limit it a little more by basically cutting off the context/containing function when they exceed (/ (window-width) 3)

Do you think this works better?

**Comment by Andersbakken** [comment]
Hi John

Just wanted to mention that I introduced some aligning. I added something
for the tabs too (I'm removing the indentation altogether now).

Let me know how this works for you.

Anders

**Comment by Andersbakken** [comment]
I'll close this for now. Please reopen if you have other suggestions for improvements or if something's not working.

**Comment by Nephyrin** [comment]
Sorry for the delayed response --
Just gave this a shot and it's fantastic now. With the indentation removal it's actually nicer to read than normal `rtags-find-references-at-point`, and the tree functionality is very useful.

The only gripe I can muster is that it still often ends up too wide for side-by-side windows, but given the amount of information being displayed, I'm not sure that's easily fixable.

Thanks again for your work on this, I'm finding rtags overall much more useful than the usual ctags/cedet workflow in emacs.

**Comment by Andersbakken** [comment]
Yeah. It's kinda hard to fit it all on screen :-)

Sorry about the delayed response. Thanks for your input on references-tree.
I don't think it would have happened otherwise. I had kinda shelved it
before your request(s). I now use it instead of
rtags-find-references-at-point. Let me know if you have any other
suggestions or gripes.

Anders
