### ISSUE TITLE
`rtags-parse-check-style` constant error messages

### ISSUE THREAD

**Issue by atilaneves** [Andersbakken/rtags#516]
I'd provide the project this is caused in but it's proprietary. In the last few days I've gotten bombarded by this message at frequent intervals:

    error in process filter: Wrong type argument: number-or-marker-p, skipped

Looking at the messages buffer, this is being caused by 

    error in process filter: rtags-parse-check-style: Wrong type argument: number-or-marker-p, skipped

**Comment by Andersbakken** [comment]
Hi Atila

Hm. Are you fully up-to-date?

Right after it happens, Can you do C-x h v rtags-last-check-style <RET> and
send me the output?

Anders

**Comment by atilaneves** [comment]
I updated my packages just in case before I filed the bug. The only way I managed to edit anything was by redefining the function within emacs.

I have `C-x h` set to `mark-whole-buffer`

**Comment by Andersbakken** [comment]
Oops. I meant C-h v rtags-last-check-style <RET>


Whenever we get some diagnostics we can't parse we store them in this
variable.

Anders

**Comment by atilaneves** [comment]
I got this:

    rtags-last-check-style is a variable defined in `rtags.el'.
    Its value is shown below.

    Documentation:
    Not documented as a variable.

    Value: (("/home/aalvesne/sla/sla/xos/sender/application/src/sla_xos_http_oper.c"
             (18 2 58 skipped "")
             (39 2 106 skipped "")
             (209 2 118 skipped "")
             (219 2 116 skipped "")
             (252 2 118 skipped "")
             (262 2 116 skipped "")
             (302 2 114 skipped "")
             (367 2 116 skipped "")
             (453 2 63 skipped "")))

**Comment by Andersbakken** [comment]
Hi Atila 

Have you seen any more of this? I finally took the change to take a look at what the problem is and it seems to be a mismatched rtags.el and rdm.

It seems like rtags.el is from a newer version and rdm is from an older build. Is this possible?

**Comment by atilaneves** [comment]
Possible, yes. But I've not seen this recently so I'll close it.
