### ISSUE TITLE
too ttooo tooo much much much loggggginnnggggg

### ISSUE THREAD

**Issue by Kannen** [Andersbakken/rtags#517]
I use to launch rdm and then work in the same terminal. 

It is not possible to work in the same terminal than rdm since it is logging all the time. Options do not fix it.

I think it is a good idea to keep in the background tasks which shall run in the background. rdm shall log everything to a file, and that behavior shall be the default one.

**Comment by cslux** [comment]
You could pass the flag `--silent` to it, if you don't want any output...
``` bash
rdm --silent --daemon
```
...or instruct rdm, to log everything into a file.
``` bash
rdm --log-file=/path/to/log/file --daemon
```

Christian

**Comment by cslux** [comment]
@Kannen 

Or, If you want this behavior by default, put the flags you want into `~/.rdmrc`.
```
--silent
--daemon
...
```

Christian

**Comment by cslux** [comment]
@Kannen just updated my comment https://github.com/Andersbakken/rtags/issues/517#issuecomment-156490593!  Wasn't entirely correct.

**Comment by cslux** [comment]
@Kannen you can now log everything to a file without the need to pass the flag `--silent` to rdm.

``` bash
rdm --log-file=/path/to/log/file &
rdm --log-file=/path/to/log/file  --daemon
```

regards,
Christian

**Comment by Kannen** [comment]
I have installed the new version,  it works very well. I like the daemon option.
Many thanks!
