### ISSUE TITLE
Byte-compile errors when installing rtags package from MELPA

### ISSUE THREAD

**Issue by ackalker** [Andersbakken/rtags#518]
When I install rtags package from MELPA, I get the following:

```
Leaving directory `/home/<username>/.emacs.d/elpa/rtags-20151112.1339'

Compiling file /home/<username>/.emacs.d/elpa/rtags-20151112.1339/company-rtags.el at Sat Nov 14 10:00:14 2015
Entering directory `/home/<username>/.emacs.d/elpa/rtags-20151112.1339/'

Compiling file /home/<username>/.emacs.d/elpa/rtags-20151112.1339/compile-shim.el at Sat Nov 14 10:00:14 2015
compile-shim.el:13:1:Warning: global/dynamic var `rtags' lacks a prefix
compile-shim.el:2:27:Error: End of file during parsing

Compiling file /home/<username>/.emacs.d/elpa/rtags-20151112.1339/rtags-ac.el at Sat Nov 14 10:00:14 2015
rtags-ac.el:27:1:Error: Cannot open load file: no such file or directory, auto-complete

Compiling file /home/<username>/.emacs.d/elpa/rtags-20151112.1339/rtags.el at Sat Nov 14 10:00:15 2015
```

I'm using company for completion, so I don't have auto-complete package installed.
I think the `Error: End of file during parsing` is some Emacs or config issue, but the `Cannot open load file` error is definitely related to rtags.
Looking into this, I think the file `compile-shim.el` is meant to mitigate these errors, but it only deals with `company` (which I do have installed) and not with `auto-complete`. Also, it isn't actually `require`d in any elisp file.

I'm by no means an Elisp whiz, but perhaps a fix could be (not tested!):

In `rtags-ac.el`:
```elisp
(eval-when-compile
  (when (not (require 'auto-complete t))
    (require 'compile-shim-ac))
  (require 'rtags))
```

and similarly for `company-rtags.el`, using `compile-shim-company`, splitting the appropriate function stubs between `compile-shim-ac.el` and `compile-shim-company.el`.
But perhaps there is a cleaner way :-)

**Comment by cslux** [comment]
Hey @ackalker,

oh, I don't think that the file `compile-shim.el` should be included in the MELPA package, we created it to byte-compile the elisp files via `cmake/make`. I took already a lock at the MELPA rtags package, they include everything in the `src` directory ending with `.el`, which is not correct anymore. 

About the auto-complete error. It is definitely not nice to see such errors, but happen frequently if a package has no hard dependencies to the required package, as we do, since you can use rtags without any completion system at all.  Anyway, I need to study the MELPA package manual first, to see if it is possibly to only byte-compile a file if its requirements are satisfied.

Thanks for the report,
Christian

**Comment by ackalker** [comment]
Thanks for your quick reply and the explanation :)

**Comment by cslux** [comment]
My pleasure :)

**Comment by cslux** [comment]
@ackalker 
I created a PR on MELPA https://github.com/milkypostman/melpa/pull/3299. The compile-shim.el file should be excluded once the MELPA maintainers have accepted the PR.

Actually, I don't know if we should suppress the error about the missing auto-complete package, and print a warning instead, all whats happen, is that the rtags-ac.el file gets not byte-compiled. But lets ask @Andersbakken what his thoughts are about this. 

Further, without the rtags-backend the MELPA rtags package is pretty useless, so to speak. But I think it is also possible to compile the rtags-backened with package.el (MELPA...). But that's probably not a good idea, as RTags is only working on UNIX like systems. However, it might be even possible to tell MELPA on which operating systems this package shell be available or not. Lot's of open questions... :-) 

Last but certainly not least, if you build the rtags-backend, you don't need to install rtags from MELPA, as all elisp files are getting installed along with the rtags-backend.

Christian

**Comment by Andersbakken** [comment]
It's probably possible to make rtags-autocomplete be a noop if autocomplete
is not available. I'll see if I can cook something up. Otherwise I don't
think I mind a warning either. A lot of the packages I've installed have
warnings during compilation.

Anders
