### ISSUE TITLE
Finding Clang, another approach

### ISSUE THREAD

**Issue by kastiglione** [Andersbakken/rtags#521]
I wanted to report an alternative approach that might be worth mentioning in the [Finding Clang](https://github.com/Andersbakken/rtags#finding-clang) section of the README. I used CMake's [`CMAKE_PREFIX_PATH`](https://cmake.org/cmake/help/latest/variable/CMAKE_PREFIX_PATH.html) and pointed it to where my LLVM install directory was. My `cmake` command was:

```
cmake -DCMAKE_PREFIX_PATH=/opt/llvm/stable \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
```

**Comment by cslux** [comment]
Good point, so in your case the binaries/libraries are in `/opt/llvm/stable/bin` /opt/llvm/stable/lib` etc. respectively.

I will add something to the README, thanks that you let us know.

Christian
