### ISSUE TITLE
(rtags-rename-symbol) with range-based-for and in-class-init

### ISSUE THREAD

**Issue by ramblehead** [Andersbakken/rtags#522]
Small example:

``` C++
// test.cpp
// and then rc -c gcc -std=c++11 test.cpp

class InClassInit {
 public:
  void func() {
    int nPtrs[] {1, 2, 3, 4, 5, 6, 7};
    for(auto&& n : nPtrs) {
      if(n > 3)  n = 0;
    }
    nPtrs[0] = 0;
  }
  int a() {
    return m_a;
  }
 private:
  int m_a = 1;
  int m_b = m_a;
};

int main(int argc, char *argv[])
{
  return 0;
}
```

Using `(rtags-rename-symbol)` in the above example on `m_a` would rename all instances of `m_a` except in "`int m_b = m_a;`"

Using `(rtags-rename-symbol)`  on `nPtrs` would rename all instances of `nPtrs` except in "`for(auto&& n : nPtrs)`"

rtags is built from 0a38673 commit.

**Comment by Andersbakken** [comment]
Hi

This does indeed seem like a bug. It is however a bug in libclang. We don't
seem to get a symbol for this reference at all. I'm using clang 3.6 so it's
possible that it's been fixed already. clang-check shows it correctly with
the same version of clang so it seems to just not have been exposed to the
c-api.

I haven't checked if clang 3.7.0 might have fixed it.

Anders

**Comment by cslux** [comment]
I have upgraded to Fedora 23 recently, which comes with clang 3.7.0, I can test this. Give me some minutes or more :-)

**Comment by ramblehead** [comment]
Anders, thank you for the quick reply.
cslux, great! Waiting - would save me plenty of time building clang from source on my old ubuntu box :)

**Comment by cslux** [comment]
@ramblehead Unfortunately, with clang 3.7.0 `int m_b = m_a;` isn't renamed either, but `nPtrs` in the for loop is.

**Comment by ramblehead** [comment]
Ok. Thank you. Half fix,. Loops are important enough to switch to clang 3.7.0
