### ISSUE TITLE
rtags can not index itself anymore because of cotire

### ISSUE THREAD

**Issue by Dushistov** [Andersbakken/rtags#526]
I tried to check how recent rtags index itself,
so as README.org suggest I run:
ninja -t commands | rc -c -

but after indexing show 100%, the rtags-find-symbol and friends
not work at all, plus rdm during indexing giving error:

error: empty filename
job crashed

I bisect the problem and the faulty commit is:

commit 3b2b70e94333bca8b993de8304fc1d77e703e558
Author: Anders Bakken <agbakken@gmail.com>
Date:   Mon Nov 16 17:12:45 2015 -0800

    Use cotire, also, don't barf on it.

**Comment by Andersbakken** [comment]
Hm. Interesting. I did put cotire in to start work on supporting pch files.
I think this actually uncovered a bug in how I was handling rc -c from
stdin.

I've simplified the code and it should work again now.

Can you verify?

Anders

On Wed, Nov 18, 2015 at 6:47 PM, Evgeniy Dushistov <notifications@github.com

**Comment by Dushistov** [comment]
>Can you verify?

indexing partly works (jump from emacs at least), but

It much much slower then before `cotire` commit.
Looks like it index the same files several times,
there are still several `indexing crashed`
the strange for me thing in rdm output is:
Output from /home/evgeniy/projects/rtags/src/rct/rct/ReadWriteLock.cpp:
CI::parse loading unit: clang -Wall -Wextra -Wpointer-arith -Wnon-virtual-dtor -fno-rtti -std=c++11 -Wall -Wextra -Wpointer-arith -Wnon-virtual-dtor -fno-rtti -std=c++11 -Wstrict-aliasing=2 -fno-exceptions -Wcast-qual -fPIC -fstack-protector-all -Wstack-protector -O3 -Qunused-arguments -c -ferror-limit=0 -Wall -fspell-checking -Wno-unknown-warning-option -DCLANG_LIBDIR=/usr/lib64 -DOS_Linux -DRCT_HAVE_OPENSSL -DRCT_HAVE_ZLIB -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -D__builtin_ia32_addcarryx_u32(...) -D__builtin_ia32_bsrsi(...) -D__builtin_ia32_pause(...) -D__builtin_ia32_rdpmc(...) -D__builtin_ia32_rdtsc(...) -D__builtin_ia32_rdtscp(...) -D__builtin_ia32_rolhi(...) -D__builtin_ia32_rolqi(...) -D__builtin_ia32_rorhi(...) -D__builtin_ia32_rorqi(...) -I/usr/include -I/home/evgeniy/projects/rtags/build/../src -I/home/evgeniy/projects/rtags/build/../src/rct -I/home/evgeniy/projects/rtags/build/src/include/rct -isystem /usr/local/include/ -isystem /usr/include/ -isystem /usr/lib64/gcc/x86_64-pc-linux-gnu/5.2.0/include/g++-v5/ -isystem /usr/lib64/gcc/x86_64-pc-linux-gnu/5.2.0/include/g++-v5/x86_64-pc-linux-gnu/ -isystem /usr/lib64/gcc/x86_64-pc-linux-gnu/5.2.0/include/g++-v5/backward/ -isystem /usr/lib64/clang/3.7.0/include/  /home/evgeniy/projects/rtags/src/rct/rct/ReadWriteLock.cpp true

see `true` at the end? for some reason it appears in every `CI::parse loading unit: `, but
`ninja -t commands | grep true` is empty, so I have no idea from where it take this `true`,

any option to disable  `cotire`? And can you reopen bug report please

**Comment by Andersbakken** [comment]
True here just meant that the indexing succeeded (returned a non-null translation unit).

Can you make sure your project is erased before doing: ninja -t commands | rc -c 

E.g.

rc -W rtags
ninja -t commands | rc -c

**Comment by Andersbakken** [comment]
I added an option:

cmake -DRTAGS_NO_COTIRE=1 ...

I timed the time to index a clean build before and after the cotire fix and
saw no real difference. (Ever so slightly faster after than before but
that's likely unrelated to cotire)

Anders

On Wed, Nov 18, 2015 at 6:47 PM, Evgeniy Dushistov <notifications@github.com

**Comment by Dushistov** [comment]
>Can you make sure your project is erased before doing: `ninja -t commands | rc -c`
>rc -W rtags
>ninja -t commands | rc -c 

I update to 15b67c68e3e4b80af4b824e2702833b3ceaebffd , and all looks ok now.

By the way there is list of functions that safe to execute from `signal handler`, and `printf` and friends not in the list.

**Comment by Andersbakken** [comment]
I know. But in a sigsegv handler there's really nothing sensible we could
do. I backtrace_symbols isn't safe either I think but it really couldn't
cause much more mayhem than still being crashed.

Anders

**Comment by Dushistov** [comment]
>I know. But in a sigsegv handler there's really nothing sensible we could do. I backtrace_symbols isn't safe either 

you can call write on stdout/stderr, and format string by your self, this how some low level
exceptional code works.

>I think but it really couldn't cause much more mayhem than still being crashed. 

for example if SIGSEGV happens in malloc/new or in printf or in both, the call of printf
may give you some strange output.

**Comment by Dushistov** [comment]
>cmake -DRTAGS_NO_COTIRE=1 ... I timed the time to index a clean build before and after the cotire fix and saw >no real difference. (Ever so slightly faster after than before but that's likely unrelated to cotire)

I got `-10%` with gcc and manual programming script for `cmake`, but my project was much larger then `rtags`

**Comment by Andersbakken** [comment]
Yeah. I also think I could do something like this:

     backtrace_symbols_fd(..., ..., FILENO_STDERR);

I'll see if I can fix it.

Thanks for the report.

Anders

Anders
