### ISSUE TITLE
clang protocol version 82

### ISSUE THREAD

**Issue by Lompik** [Andersbakken/rtags#530]
where do you I get clang with protocol version 82 ?

indexing keep crashing with this message : 

    Wrong protocol 81 vs 82
    ClangIndexer error

I have clang 3.7.0 installed but rtags' readme says clang > 3.2 !

**Comment by Lompik** [comment]
plz ignore this bug report. Issue was related to mismatch of rc / rdm version.

**Comment by Andersbakken** [comment]
No worries. It tends to be that when you get that error.

Anders
