### ISSUE TITLE
Possible to highlight "current" line in *Rtags* buffer?

### ISSUE THREAD

**Issue by cleeland** [Andersbakken/rtags#531]
When I use rtags-find-reference[-at-point], the *RTags* buffer gets populated with references to lines in various source files (ala *grep*).  Unlike the *grep*, there is no visual indication of the currently active line.

I have no idea how hard it would be to add such a feature, but if it's relatively easy it would be a really nice feature.  Even just moving 'point' so that when I switched to the buffer 'point' would be sitting on the currently active line would be better.

**Comment by cleeland** [comment]
Actually, I just saw that 'point' does move within the buffer if I switch to it.  So I guess the feature request is for some sort of indicator to be visible even when focus is not in that buffer.

**Comment by cslux** [comment]
Agree, that would be nice. This was feature was requested already a while ago.

Duplicate of #147

**Comment by cleeland** [comment]
Ah, I would not have correlated this with #147, but I see that they definitely can be.

**Comment by cslux** [comment]
A mix of xcscope and ggtags  would be nice.

**Comment by Andersbakken** [comment]
Hm. I don't actually have any decoration in my grep buffer (outside of
seeing the cursor). Is this something you've turned on in grep-mode? Maybe
we could do the same thing for consistency,

I just added an option for this though. It's on by default (not sure about
the color choice but it can be customized).

Anders
