### ISSUE TITLE
Getting file/line information with --list-symbols

### ISSUE THREAD

**Issue by mdk2029** [Andersbakken/rtags#534]
I have a usage question, am sorry if this is not the right place to ask it (where is the right place?)

When using rc --list-symbols, is there a way to get  the file/line information. By default, it just prints a list of all matching symbols without any context information for them.

Thanks a lot in advance!

**Comment by Andersbakken** [comment]
This is fine.

I think you want rc --find-symbols

It behaves similarly but also prints line numbers/columns.  --list-symbols
is mostly there to provide completions for interactive use.

Anders

**Comment by mdk2029** [comment]
Yes, --find-symbols indeed works. Thanks!

**Comment by Andersbakken** [comment]
My pleasure

Anders
