### ISSUE TITLE
where to specify include dirs?

### ISSUE THREAD

**Issue by finjulhich** [Andersbakken/rtags#535]
In the *rdm* buffer I see:
Running with 2 jobs, using args: -ferror-limit=0 -Wall -fspell-checking -Wno-unknown-warning-option
Includepaths: -isystem /usr/lib64/llvm/clang/3.5.0/include/    (what is this?)
Restoring /home/hich/dir1/ .................................................
Restoring /home/hich/dir2/..................................................

I get these errors:

fatal error: 'stddef.h' file not found

that header for me resides here:   /usr/lib/gcc/x86_64-redhat-linux/5.1.1/include/

Where do I need to add that directory for rdm to find it successfully?

Thanks

**Comment by cslux** [comment]
You can pass the flag `--isystem` to `rdm`.

In your case:
``` bash
rdm --isystem /usr/lib/gcc/x86_64-redhat-linux/5.1.1/include/
```
See `man rdm` or `rdm --help` for more option.

Christian

**Comment by finjulhich** [comment]
I am actually using cmake-ide. I never run rdm directly myself. As soon as I open a c++ file in a buffer, emacs launches it for me. Here is a snippet of what I have in my .emacs.

;; cmake-ide
(setq cmake-ide-flags-c++ "-I/usr/local/include -I/usr/include -I/home/hich/Trading/blitzq")
(setq cmake-ide-dir "/home/hich/Trading/blitzq-build-release")
(require 'rtags) ;; optional, must have rtags installed
(cmake-ide-setup)

Can I set something in my .emacs to pass that --isystem arg to rdm ?

**Comment by cslux** [comment]
> Includepaths: -isystem /usr/lib64/llvm/clang/3.5.0/include/ (what is this?)

That's the include path, the clang headers are located in, the are needed for parsing the source files.

**Comment by cslux** [comment]
> Can I set something in my .emacs to pass that --isystem arg to rdm ?

Well, there are more possibilities. 
1.) You could use the variable `rtags-rdm-includes`
2.) You could create your own function to for getting the required flags and assign the function symbol to `rtags-includes-func`.


e.g. for 1
``` emacs-lisp
(setq rtags-rdm-includes "/usr/lib/gcc/x86_64-redhat-linux/5.1.1/include/")
```

**Comment by finjulhich** [comment]
I'm gonna try this

(setq rtags-rdm-includes "/usr/lib/gcc/x86_64-redhat-linux/5.1.1/include/")
(require 'rtags) ;; optional, must have rtags installed
(cmake-ide-setup)

thanks

**Comment by finjulhich** [comment]
Setting

(setq rtags-rdm-includes "/usr/lib/gcc/x86_64-redhat-linux/5.1.1/include/")

either before 

(require 'rtags) ;; optional, must have rtags installed

or after it, or both, doesn't seem to have an effect.

The same isystem /usr/lib64/llvm/clang/3.5.0/include/  appears in the rdm buffer, and the same error about stddef.h appears.

I can see with M-x describe-variable that that variable has indeed taken the value specified.

**Comment by cslux** [comment]
Sorry to here that, I'll look more closely to it tomorrow. However, I'll took a quick look in the cmake-ide.el file and it seems that what happens here, is that, he calls `rc` with `-J` flags. Which means, you should have a **compile_commands.json** file in your build directory, you could start `rdm` yourself until someone finds a solution, after that call `rc` with the `-J` flag and point to the directory the **compile_commands.json** is located in.

``` bash
rdm --isystem /usr/lib/gcc/x86_64-redhat-linux/5.1.1/include/
rc -J path/to/your/cmake/build/directory
```

Christian

**Comment by cslux** [comment]
BTW, is this a open-source/free project you get the error for? If that's the way it is, could you provide a link to it, so I can try to reproduce, it more easily (hopefully).

**Comment by Andersbakken** [comment]
It's actually supposed to find stddef.h in the clang headers. The stddef.h
header from your gcc install is not compatible with clang.

Where did you get your libclang from?

My assumption is that you're missing something a dev package for libclang.

Anders

**Comment by finjulhich** [comment]
I have the following versions: (Fedora 23)
clang-3.7.0-1.fc23.x86_64
clang-analyzer-3.7.0-1.fc23.noarch
clang-devel-3.7.0-1.fc23.x86_64
clang-libs-3.7.0-1.fc23.x86_64
llvm-libs-3.7.0-1.fc23.x86_64
llvm-devel-3.7.0-1.fc23.x86_64
llvm-3.7.0-1.fc23.x86_64

and indeed i see stddef.h here:

/usr/lib/clang/3.7.0/include/stddef.h

so I need rdm to consider the include path /usr/lib/clang/3.7.0/include

and indeef the /usr/lib64/llvm/clang/3.5.0/include/ that rdm gets is wrong.

so the 3.5.0 is wrong 

The cmake-ide is here

https://github.com/atilaneves/cmake-ide

I don't have a definite need to use it, but my project uses cmake so I thought why not.
From that page:

"cmake-ide can make usage of rtags for finding definitions, also using clang. If (require 'rtags) is called before cmake-ide-setup, it will automatically start the rtags server (rdm) and call rc -J to index the project files for 0-config "jump to definition" and everything else rtags offers. This only works if both rdm and rc and in the system path or if cmake-ide-rdm-executable and cmake-ide-rc-executable are customized correctly."

**Comment by finjulhich** [comment]
added a question here: 
https://github.com/atilaneves/cmake-ide/issues/27

**Comment by cslux** [comment]
Hey, I use Fedora 23 too!

That's weird, seems like you have same clang stuff left from Fedora 22 (did
you upgrade from 22->23 or is this a fresh installation?) Or you didn't
reinstall rtags since than.

Could you post the output of...

rpm -qa | egrep "clang|llvm"

please.

Christian

**Comment by finjulhich** [comment]
from f22 to f23. The rpm output is exaclty what's already in my previous post. 
Yes, I didn't reinstall rtags. I just have a vague memory of building rtags locally myself.

AH yes I just found my rtags git clone :-) I will git pull, re cmake, and install and see what happens

**Comment by toojays** [comment]
Fedora's Clang packages are broken in the way the include paths are configured. I filed https://bugzilla.redhat.com/show_bug.cgi?id=1222786 as a symptom of this some time ago. [I'm not a Fedora user myself so have let that bug lapse.] I suspect that if Fedora's Clang packages get fixed to *not* use ``--with-c-include-dirs``, that might resolve this issue as well.

**Comment by cslux** [comment]
@toojays I can't reproduce this on Fedora 22/23 with the steps described in the link you have provided.

**Comment by cslux** [comment]
@toojays I personally use Fedora since Fedora 18 and use rtags since Fedora 22. And never come across this issue, so must be something other.

**Comment by toojays** [comment]
@cslux I stand corrected. Good to hear.

**Comment by finjulhich** [comment]
i forgot to confirm that after rebuilding rdm, the new correct clang include path is used.
thanks
close issue?
