### ISSUE TITLE
Find all implemtnations of [pure] virtual method

### ISSUE THREAD

**Issue by Phyllostachys** [Andersbakken/rtags#541]
It seems that when I'm using interface classes and try to find implementations for pure virtual methods that nothing is returned from ```rc --current-file=... -f ...``` or ```rc --current-file=... -S ...```. Am I missing something or is that a possible enhancement?

**Comment by cslux** [comment]
Actually this feature is already implemented.  The flag is called `--find-virtuals` or `-k` for short.

**Comment by Andersbakken** [comment]
Hi Jacob

I think you're calling rc with the wrong switch.

This should work:

rc --current-file=... -r ... -k

Anders

**Comment by Phyllostachys** [comment]
Ah, awesome! I'm using rtags with Atom and the plugin that handles that only uses -f which works for most cases but not this one. Good to know that rtags does handle it.

**Comment by Andersbakken** [comment]
Ah. Cool. I'm kinda stoked that there's a atom/sublime/vim plugins out
there. Let me know if you have questions about other things RTags can or
should do.

Anders
