### ISSUE TITLE
company-rtags fails to autocomplete

### ISSUE THREAD

**Issue by atilaneves** [Andersbakken/rtags#542]
In [this project](https://bitbucket.org/atilaneves/gravastar) in file `CDelta.cpp:35`, if I delete the line and type `mWeap` and try to autocomplete with company and `company-backends` set to `'(company-rtags)`, it doesn't work. If I set `company-backends` to `'(company-clang)` instead (and provided `company-clang-arguments` is correctly set), the autocompletion works.

The worst is that there is no error from `company-rtags`, so company won't try the next backend.

**Comment by Andersbakken** [comment]
This seems to be a bug in libclang. It marks the entry as:

  /**
   * \brief The entity is available, but not accessible; any use of it will
be
   * an error.
   */
  CXAvailability_NotAccessible


I've committed a work-around (that basically lets these entries through
even if the API says not to).

Thanks for the report.

Anders
