### ISSUE TITLE
Automate installation

### ISSUE THREAD

**Issue by aragnon** [Andersbakken/rtags#543]
Please automate installation for the various platforms such that you don't scare people away with laborious installation and setup.

**Comment by cslux** [comment]
@aragnon What exactly do you mean by **automate**?

**Comment by cslux** [comment]
@aragnon There is el-get for emacs which simplifies the process. Also some guys have created a RPM package for it, see http://software.opensuse.org/package/rtags?search_term=rtags for instance.
Anyway, which part does look complicated for you in the README, maybe we can simplify it, to look less complicated :-)? 

Christian

**Comment by aragnon** [comment]
@cslux I don't think it is complicated, but I am just lazy. I would make it such that the Emacs mode can start the daemon if it not already running, for example. 

And for emacs M-x package-install RET rtags-mode (or whatever) should just work.

**Comment by aragnon** [comment]
Otherwise, good development that this exists :+1:

**Comment by aragnon** [comment]
Via Nix one can also install rtags, except it is currently broken: https://github.com/NixOS/nixpkgs/issues/11789 . Perhaps interesting to mention that once it is all working, of course.

**Comment by cslux** [comment]
> but I am just lazy

:-D are we not all to some extend lazy... 

> And for emacs M-x package-install RET rtags-mode (or whatever) should just work.

We are aware of this issue, some guy long time ago created a MELPA rtags package, but this installs only the elisp files, and, unfortunately, it is not possible via MELPA to compile source code. So we need a different solution here. @Andersbakken created already a issue, which when done, should take care of this problem. https://github.com/Andersbakken/rtags/issues/538

> I would make it such that the Emacs mode can start the daemon if it not already running, for example.

rdm gets started automatically if not running already.

> Via Nix one can also install rtags, except it is currently broken: NixOS/nixpkgs#11789 . Perhaps interesting to mention that once it is all working, of course.

Good to know, thanks.

**Comment by Andersbakken** [comment]
I've been meaning to add something to rtags.el that would download and
build rdm/rp/rc if it's not already built. Irony-mode has something
similar.

https://github.com/Andersbakken/rtags/issues/538

Anders

**Comment by magthe** [comment]
I'd point to `irony` for inspiration. It offers an elisp function for building its server, and start the server on its own.

**Comment by Andersbakken** [comment]
Yeah. I think that's the way to go. I've been meaning to get around to it
but haven't had the time.

Anders

**Comment by lucasduffey** [comment]
Plus If you look at the commits many of them fail to build properly. They shouldn't be commited if they don't compile successfully.

It does scare people away, if doesn't work when you follow the directions..
