### ISSUE TITLE
cmake doesn't compile under debian.

### ISSUE THREAD

**Issue by introom** [Andersbakken/rtags#544]
Output here:
<pre>
-- cotire 1.7.5 loaded.
--
-- The following OPTIONAL packages have been found:

 * ZLIB
 * OpenSSL

-- The following REQUIRED packages have been found:

 * Curses

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBCLANG_LIBRARIES
    linked by target "rp" in directory /home/introom/temp/rtags/src
    linked by target "rdm" in directory /home/introom/temp/rtags/src
    linked by target "rc" in directory /home/introom/temp/rtags/src

-- Configuring incomplete, errors occurred!
See also "/home/introom/temp/rtags/CMakeFiles/CMakeOutput.log".
See also "/home/introom/temp/rtags/CMakeFiles/CMakeError.log"

</pre>

**Comment by Andersbakken** [comment]
It seems like you need to install a libclang-dev package. Not entirely sure
what it's called on debian but probably something like that. Note that you
should blow away your build dir after installing before retrying the build.

Anders

**Comment by introom** [comment]
Yes. Clearing the cmakecache is really a must.
