### ISSUE TITLE
Add an option to integrate rtags with helm.

### ISSUE THREAD

**Issue by amosbird** [Andersbakken/rtags#545]
It would be very useful in finding references.

**Comment by Andersbakken** [comment]
I don't use helm but I believe it's similar to ido right? E.g. smart
completion with fuzzy matching etc? I'm not entirely sure I understand how
this would integrate with rtags-find-references. Would you like to complete
on the locations and select which one in the minibuffer?

Anders

**Comment by amosbird** [comment]
Yes. Just like https://github.com/syohex/emacs-helm-gtags does.  

![](http://i.imgur.com/Run7xxU.png) 

This feature is more efficient than `Rtags Mode` IMO.

**Comment by Andersbakken** [comment]
I have very little experience with helm but I tried to mock up a simple integration. To use:
(setq rtags-use-helm t)

It should be used for rtags-find-references and rtags-find-symbol and a couple of other functions.

Let me know how it works.

**Comment by Andersbakken** [comment]
I thunk this works pretty well actually and I think I like it. I'll close this for now. Reopen if necessary.
