### ISSUE TITLE
company-rtags.el is presumably for completion through company?

### ISSUE THREAD

**Issue by ville-h** [Andersbakken/rtags#547]
company-rtags.el is presumably for completion through company? don't see it mentioned anywhere in the readme. how do i use it?

**Comment by Andersbakken** [comment]
Ah. Let me see if I can add something.

**Comment by ville-h** [comment]
According to the instructions in readme and placing following in init.el:
(setq rtags-autostart-diagnostics t)
(setq rtags-completion-enabled t)
(push 'company-rtags company-backends)
(global-company-mode)

Errors out during emacs startup with:
Symbol's value as variable is void: company-backends

It would appear (require 'company) needs to be issued before (push 'company...) line.

**Comment by Andersbakken** [comment]
Yeah. I'll add that. Does it work after that? I kinda did this from memory,
I don't normally use autocompletion.

Anders

**Comment by ville-h** [comment]
I don't appear to be able to get completion to work through company. I've tried various combinations but my lack of emacs and lisp knowledge apparently prevents me from finding the right one. I did manage to get things like rtags-find-symbol-at-point to work. Is there a minimal complete copy-pastable snippet of init.el that gets completion to work somewhere?

**Comment by Andersbakken** [comment]
I think I broke completion recently but it should work again now. If you
pull and recompile.

I also added a minimal init.el example to the README

Let me know if this works for you.

Anders

**Comment by ville-h** [comment]
Okay now completion works with just pulled rtags and copypasted init.el snippet from the readme. Thanks for the help.

For some reason the company-rtags appears twice in the company backends after (push 'company-rtags company-backends) is that expected? I inspected the backends through emacs' customize interface.

**Comment by Andersbakken** [comment]
Glad to hear.

Hm. Maybe we actually add it explicitly in rtags-company.el. If so the push
thing can be dropped.

Anders
