### ISSUE TITLE
rtags sets keybindings under C-c r NOT C-x r

### ISSUE THREAD

**Issue by floli** [Andersbakken/rtags#558]
Hello,

the README.org claims

```
(rtags-enable-standard-keybindings)
Sets up a ton of standard keybindings under C-x r (we try to avoid crashing with the register shortcuts).
```

but ```rtags.el``` actually does

```
(defun rtags-enable-standard-keybindings (&optional map prefix)
  (interactive)
  (unless map
    (setq map c-mode-base-map))
  (unless prefix
    (setq prefix "\C-cr"))
  (ignore-errors
    (define-key map (concat prefix ".") (function rtags-find-symbol-at-point))
[...]
```

which sets up the keybindings under C-c r.

I don't know if this is a rtags.el or documentation bug, but it should be consistent.

**Comment by Andersbakken** [comment]
How's that for a quick turn-around :-)

Thanks for the report. Should be fixed now.

Anders

**Comment by floli** [comment]
Quick bugfix! Just a minor addition, since the register shortcuts are actually at C-x r, I would also remove ```(we try to avoid crashing with the register shortcuts).```
