### ISSUE TITLE
Add an option to integrate rtags with evil-jumper or evil.

### ISSUE THREAD

**Issue by amosbird** [Andersbakken/rtags#559]
If I understand correctly, `rtags` has its own jumplist. It would be nice to intergrate with `evil-jumper's` `C-o` and `C-i`.

**Comment by Andersbakken** [comment]
Seems like a good idea. Do you know if it simply is a matter of calling:
(evil-jumper--push) before (or after) we've moved the point?

Anders

**Comment by amosbird** [comment]
@Andersbakken Here is what I've found in the cscope layer.
```
 (defun cscope/post-init-evil-jump ()
  (defadvice helm-cscope-find-this-symbol (before cscope/goto activate)
    (evil-jumper--push)))
```
I think `(evil-jumper--push)` may be enough. There is also a `evil-jump-hook`,
```
(defun evil-jump-hook (&optional command)
  "Set jump point if COMMAND has a non-nil :jump property."
  (setq command (or command this-command))
  (when (evil-get-command-property command :jump)
    (evil-set-jump)))
```

**Comment by Andersbakken** [comment]
I just added a hook that's called every time we jump somewhere that I think you could easily use for this.

E.g.

(add-hook 'rtags-jump-hook 'evil-jumper--push)

Let me know if this works and reopen if not.

**Comment by amosbird** [comment]
After adding `(add-hook 'rtags-jump-hook 'evil-jumper--push)` I can use `ctrl-o` to jump backward. However, `ctrl-i` cannot jump forward.

**Comment by amosbird** [comment]
After I make emacs distinguish `ctrl-i` and `Tab`, it works correctly. :-)
