### ISSUE TITLE
compile-shim.el blows up running emacs when installing via melpa

### ISSUE THREAD

**Issue by abutilize** [Andersbakken/rtags#562]
byte compiling compile-shim.el during installation via melpa causes the mini-buffer to go haywire. 

this is where the culprit lies:
(defun completing-read-default (&rest args))

Wondering if this should be
(unless (fboundp 'completing-read-default)
   (defun completing-read-default (&rest args)))

But then again I'm not understanding what that point of the shim is.

**Comment by Andersbakken** [comment]
I think this should be fixed with the next melpa package. The compile-shim should never have been installed to begin with. It's an awful hack to prevent getting a ton of warnings at make time and there's probably something smarter I could do. Thanks for the report.

**Comment by abutilize** [comment]
Thanks, Anders! Your response time is Outstanding.

**Comment by Andersbakken** [comment]
My pleasure.

Anders
