### ISSUE TITLE
rtags-find-references-at-point forced open new frame

### ISSUE THREAD

**Issue by tomhk215** [Andersbakken/rtags#563]
Upon doing this command, a new frame is created with weird resolution. The new frame is separated into two windows. The LHS consists all reference and the RHS consist the corresponding code. And they both in wrong resolution.

Can it be separated in the same frame?
![frame1](https://cloud.githubusercontent.com/assets/16475673/12202534/5785d3b0-b665-11e5-9f35-f35c0382432b.jpg)
![frame2](https://cloud.githubusercontent.com/assets/16475673/12202536/6087efd4-b665-11e5-8cb5-d167c6888cd2.jpg)

**Comment by Andersbakken** [comment]
Sorry about the delay. 

We had a bug around the time you submitted this regarding opening up new windows with references (though I don't entirely understand how it cause a whole new frame to be opened). Can you check with latest trunk?

Do you think this is related to some other package that rtags doesn't play nicely with perhaps? I really don't see how anything we do could open up a new frame.

**Comment by Andersbakken** [comment]
Didn't mean to close the task.

**Comment by tomhk215** [comment]
I think this is related to emacs code browser. After the disabling the ecb, the reference window can spawn in the same frame. However, the way to split the frame seems to be random, sometimes vertical and sometimes horizontal.

**Comment by cslux** [comment]
@tomhk215 
> I think this is related to emacs code browser. After the disabling the ecb, the reference window can spawn in the same frame. However, the way to split the frame seems to be random, sometimes vertical and sometimes horizontal.

Yeah, there is not much you can do about it, without implementing some special dedicated buffer like helm, ecb etc did. 
However, you could set `split-height-threshold` to 160, with that value new windows which pop up are almost always (99 % of the time) opened right or left of the current window.

Put this in your init.el or .emacs file.
```
(setq-default split-height-threshold 160)
```
Also, I suggest reading the info of the function `split-window-sensibly` (`C-h f split-window-sensibly RET`), maybe you find some better settings which suit your needs. 

regards,
Christian
