### ISSUE TITLE
No preamble.*-pch files in /tmp

### ISSUE THREAD

**Issue by pradhanpk** [Andersbakken/rtags#568]
Hi @Andersbakken,
This [post](http://lists.llvm.org/pipermail/cfe-dev/2016-January/046751.html) from a cfe-dev thread discussing clang's code completion speed mentions that when generating precompiled preambles with clang_parseTranslationUnit, you should see `preamble*.pch` files in `/tmp`. I don't see any such files. Is this an issue?

The thread also mentions that these files, when using clang3.7 and earlier, are only generated on a reparse. IIUC, `CompletionThread::process`(HEAD) does indeed call `RTags::reparseTranslationUnit` immediately after the first `RTags::parseTranslationUnit`, to solve this problem. Is that right?

**Comment by Andersbakken** [comment]
This is a little surprising. I can indeed not find these files anywhere. I think I've seen them before (haven't tried on linux yet).

We do use the reparse step. I suppose we can drop that in clang >= 3.7.

I'll try to investigate a little.

**Comment by Andersbakken** [comment]
I figured out where they go on mac:

find  /var/folders/df/ | grep pream

Should show some (after some completions)
