### ISSUE TITLE
Face rtags-skippedline is way too dark for light themes

### ISSUE THREAD

**Issue by hrehfeld** [Andersbakken/rtags#571]
Face rtags-skippedline is way too dark for light themes. Using the standard-theme, it basically hides all text that's not angry-fruit-salad-colored.

in rtags.el:371

    (defface rtags-skippedline
      '((((class color) (background dark)) (:background "gray12"))
        (((class color) (background light)) (:background "gray12")))
      "Face used for marking skipped lines."
      :group 'rtags)

has the same definition for light and dark. I suggest to use "light gray" for the light variant.
![preview](https://i.imgur.com/J3xpKxl.png)

**Comment by Andersbakken** [comment]
Should be fixed now. Thanks.

**Comment by hrehfeld** [comment]
Thanks!

**Comment by Andersbakken** [comment]
My pleasure.

Anders
