### ISSUE TITLE
Server.cpp:235:19: error: use of undeclared identifier 'launch_activate_socket'

### ISSUE THREAD

**Issue by jwatt** [Andersbakken/rtags#572]
On my OS X 10.9 machine I get the following build error:

```
rtags/src/Server.cpp:235:19: error: use of undeclared identifier 'launch_activate_socket'
        int ret = launch_activate_socket("Listener", &fds, &numFDs);
                  ^
1 error generated.
make[2]: *** [src/CMakeFiles/rtags.dir/Server.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/rtags.dir/all] Error 2
make: *** [all] Error 2
```

I suspect that's just because this is an older version of OS X. It would be good if there was a way to disable compilation of the launchd integration though (I don't see anything in ccmake).

**Comment by jwatt** [comment]
I updated the machine to 10.11, and indeed the issue is gone. I'll leave this issue open in case any rtags devs want to either document this in the README or else warn during the build, or something.

**Comment by Andersbakken** [comment]
We could add a version check ifdef. Thanks for the report.
