### ISSUE TITLE
Update the README now that homebrew-versions is no longer needed

### ISSUE THREAD

**Issue by jwatt** [Andersbakken/rtags#574]
The README says:

```
you’ll need a custom libclang, the default one built through homebrew does not support using LLVM’s libc++. You’ll need to install one from homebrew-versions instead and explicitly tell it to enable libc++. For LLVM 3.6 the following works:

$ brew tap homebrew/versions
$ brew install llvm36 --with-libcxx --with-clang --without-assertions --rtti
```

Simply using:

```brew install llvm --with-libcxx --with-clang --without-assertions --rtti```

worked fine for me though.

**Comment by jhanssen** [comment]
And that works for C++11 enabled projects as well? It always worked for C++98 projects but maybe the homebrew people finally fixed the problem?

**Comment by Andersbakken** [comment]
I think the point is that you don't need to tap homebrew/versions anymore. The options passed to install are seemingly the same.

**Comment by jwatt** [comment]
jhanssen: Methods marked with the 'override' special identifier are handled correctly, so yes, this works in C++11 projects.

Andersbakken: yes, sorry that wasn't clear; there's no need to tap homebrew/versions, and I was able to specify 'llvm' for install rather than 'llvm36' (the default llvm that brew installed for me is 3.6.2).

**Comment by jhanssen** [comment]
Fixed, thanks.
