### ISSUE TITLE
No way to index files in /tmp

### ISSUE THREAD

**Issue by jeffkowalski** [Andersbakken/rtags#575]
rdm has an exclude filter which includes [/tmp/ by default](https://github.com/Andersbakken/rtags/blob/71102cd23d9912d50075a8e73da922f1c7fb93cb/src/rdm.cpp#L50)
There is a commandline switch ```-X``` that can be used to specify other directories, but they are [_added_ to the default list](https://github.com/Andersbakken/rtags/blob/71102cd23d9912d50075a8e73da922f1c7fb93cb/src/rdm.cpp#L395).  Because this list only accumulates, it's impossible to tell rdm to index files in /tmp.

Why index files in /tmp?  Because it's convenient for temporary work.  In fact, the Homebrew/Linuxbrew rtags.rb formula creates temporary source for indexing, and on Linux it's stored in /tmp.  Because the indexing doesn't proceed, the tests will fail.

I propose a one-character semantic change to rtags/rdm.cpp:
from:
```
            serverOpts.excludeFilters += String(optarg).split(';');
```
to 
```
            serverOpts.excludeFilters = String(optarg).split(';');
```
A user should be able to aggregate the excludeFilter externally if the original behaviour is required.

**Comment by Andersbakken** [comment]
I made it so that the defaults only are used if no excludefilters have been set.

**Comment by Andersbakken** [comment]
Thanks for the report.

**Comment by jeffkowalski** [comment]
Thanks for the quick fix, @Andersbakken.  It's an even more elegant solution than I proposed.

**Comment by Andersbakken** [comment]
No problem. Thanks for the report. Let me know if you find anything else
that should be fixed or could be improved.

Anders
