### ISSUE TITLE
Out of source builds result in two unrelated projects

### ISSUE THREAD

**Issue by jwatt** [Andersbakken/rtags#577]
I'm trying to index the Mozilla source using rtags but am having some problems.

As background, Mozilla's C++ source is built using unified compilation. Specifically, this means that instead of compiling the individual C++ source files, the build system generates a bunch of C++ files in the build/object directory and compiles them instead. The C++ files in the object directory each #include a number of the real source files. (Doing this speeds up build times significantly.)

Mozilla's build system can generate a compile_commands.json for the unified (generated .cpp) files only, and rc processes that json without error. Unfortunately the results leave a lot to be desired. I think this is probably because Mozilla builds are typically out of source builds. Instead of one project, rtags lists two projects after processing the compile_commands.json file - one for the source directory, another for the object directory.

If I write a script to generate additional content in compile_commands.json that pretends that the real source files are compiled with the same flags as their corresponding unified file then rtags creates a much bigger database and does a much better job of understanding the codebase. Unfortunately because Mozilla's code only compiles using unified compilation nowadays many of the source files have missing include and other things that prevent rtags from getting information for those files, so this isn't a good solution at all.

To work well with the Mozilla source, rtags would have to better support out of source builds, I think. Is there a way I can get rtags to create a single project that can track both the source and object directory?

**Comment by Andersbakken** [comment]
Hi Jonathan

There's actually a feature in there that's meant to cover this (though I
have to admit I don't really use it myself for any of my project so it
might not be that well tested).

If you pass an explicit project-root to rc when you load your
compilation_database.json file it should work.

E.g.

rc --project-root=/path/to/desired/project/root -J
/path/to/compile_commands.json

Can you see this works for you?

regards

Anders

**Comment by jwatt** [comment]
Hi Anders. I had noticed that option but assumed it was for fixing incorrect detection, and that it wouldn't be a solution for my case. My mozilla trees look something like this:

```
~/
  mozilla/
    trees/
      obj/
        i-debug/
        i-opt/
        i2-debug/
        i2-opt/
      i/
      i2/
```

To get both 'i' and 'i-debug' into the same project using `--project-root` would require `--project-root=~/mozilla/trees`. Since that directory also contains all of my other mozilla source trees and object directories I imagine this could cause problems or at least some inefficiencies, but maybe I'm wrong? For that reason I had been thinking that a new argument along the lines of `--out-of-source-objdir=<path>` would be required.

**Comment by Andersbakken** [comment]
I believe you should be able to just set the project-root to
~/mozilla/trees/i for both of them. If this doesn't work we could add
something like what you mentioned but I think it will.

Anders

**Comment by Andersbakken** [comment]
Did the trick work?

**Comment by jwatt** [comment]
Sorry, I missed your previous reply. I'm away from the computer I set this up on but I'll test it in a few days.
