### ISSUE TITLE
List all symbols in a certain file?

### ISSUE THREAD

**Issue by xuhdev** [Andersbakken/rtags#579]
It would be a useful feature if rtags is capable to list all symbols in a certain file.

**Comment by asenac** [comment]
+1

**Comment by cslux** [comment]
This feature is already available. Call `rtags-taglist' in the file you
want all symbols from.

Christian

**Comment by xuhdev** [comment]
@cslux  Thanks for the info. Is it possible to add some documentation to it? Also, after calling `rtags-taglist`, moving the cursor back to the main window causes the taglist window disappear is a bit confusing for me....

**Comment by cslux** [comment]
Or call `rc` from the CL like so:
``` bash
rc -o --path-filter=/same/path -F --display-name --no-context
# Or
rc  --path-filter=/path/to/file -F --display-name --no-context
```

**Comment by cslux** [comment]
> Is it possible to add some documentation to it?

Sure, we will add something.

> Also, after calling rtags-taglist, moving the cursor back to the main window causes the taglist window disappear is a bit confusing for me....

I see... hmm, I personally find the behavior of the `*RTags* buffer also a bit confusing, It certainly needs some cosmetic adjustments :-)
We will improve that for sure, but may take some time. It needs some shortcuts, and also the taglist should be sorted by line number... Do you have also some suggestions? 

Christian

**Comment by xuhdev** [comment]
@cslux There is a current big issue on using taglist : After `rtags-taglist`, switching back to the source code view leads to the closing of the taglist window---I'm not really able to use much of it. Do you have this issue? I tried to debug it but I've got no clue.

**Comment by cslux** [comment]
@xuhdev Same here.

**Comment by Andersbakken** [comment]
Yeah. This behavior is a little strange. I added two defcustoms to control
the behavior:

rtags-close-taglist-on-selection

and

rtags-close-taglist-on-focus-lost

Which can help you tune the behavior (Should maybe have been a single
defcustom actually).

Does this help?

Anders

**Comment by xuhdev** [comment]
Thanks, `(setq rtags-close-taglist-on-focuslost nil)` works! Strange enough even I commented out the close command it still closed before...

Some further improvements in my opinion may be:

- taglist window can refresh after a reparsing.
- If a variable is a local variable inside a function, it probably should be marked differently in the taglist (e.g., list local variables in the function list with a foldable view, which may also apply to the class and member function case...).
- I prefer alphabetical order (of course, local variables in functions should be grouped togather).
- Allow customization of the size of taglist window when it is opened (or remember the size from the last time).

**Comment by xuhdev** [comment]
It seems that `rtags-taglist` does not work any more...

**Comment by Andersbakken** [comment]
Thanks for the report. Should work again now I think.

**Comment by xuhdev** [comment]
It seems that this issue comes up again....

**Comment by Andersbakken** [comment]
Sorry about the late reply. Are you still seeing issues with this? It seems
to work for me.

Anders
