### ISSUE TITLE
rtags-find-symbol-at-point fails on auto

### ISSUE THREAD

**Issue by ville-h** [Andersbakken/rtags#580]
On line "auto x = f();" and rtags-find-symbol-at-point on "auto" doesn't find the type. rtags-symbol-type is still able to display what the type is if point is on "x".

````
auto f() -> int {
}

auto main() -> int {
    auto x = f();
}
````

I guess the point should jump to "int" in "auto f() -> int {"?

Does rtags offer mechanism to automatically do rtags-symbol-type after point is left for N units of time on a symbol?

**Comment by Andersbakken** [comment]
Hi

We don't normally jump built-in types.

E.g. If you change the example to this:

     1 struct Foo
     2 {};
     3
     4 auto f() -> Foo {
     5    return Foo();
     6 }
     7
     8 auto main() -> int {
     9    auto x = f();
    10    return 0;
    11 }
    12

Doing rtags-find-symbol-at-point on the auto on line 9 will jump to the
struct declaration on line 1, not the lambda return value on line 4.

We do have a function that you can call to achieve this:

rtags-display-summary will display a tooltip with info about the symbol
under cursor. We don't currently offer integration with the tooltip system
but it shouldn't be too hard to implement. Maybe we could add something.

Anders

**Comment by ville-h** [comment]
Fair enough point about that it's a builtin. Perhaps extend the error/status reported in the minibuffer from "RTags: No results" to explain why there were no results. To me it just looked like rtags failed mysteriously and made me think my setup was broken. It  failed on some and worked on others.

rtags-display-summary returns "No information for symbol" in minibuffer for the original auto/int case. So had i tried that previously it would also looked like another mysterious breakage.

Guess what i am getting at that having these functions "fail" on auto depending on the type what the auto is masquerading as is bit disorienting when I was trying to find out what the auto was in the first place. Now i know not to try to find what the type of auto is having the point on auto because it will only work some of the time. slightly unintuitive.

**Comment by Andersbakken** [comment]
I agree. We could probably improve that a little. Maybe even print some
information about which built-in type it is. I'll see if I can add
something for this.

regards

Anders
