### ISSUE TITLE
Completion times out

### ISSUE THREAD

**Issue by petercheng00** [Andersbakken/rtags#581]
After updating rtags a while back, completion always hangs, regardless of how long I set the company async timeout. Rtags otherwise works perfectly fine for me. `rc --code-complete-at` and `rc --dump-completions` from a terminal both produce large amounts of output, so I imagine it's something going wrong when passing to company.

**Comment by Andersbakken** [comment]
Can you try to set rtags-completions-timer-interval to something positive
(like .5).

What this means is that every time you move your cursor we restart a timer
for .5 seconds and if/when the timer fires we will tell rdm to prepare
completions for that position. This should mean that completions will be
ready sooner when you actually need them but does mean that there's some
more cpu spent preparing completions that never will be used).

Anders

**Comment by petercheng00** [comment]
It was already set to 1, and setting it to 0.5 doesn't appear to have changed much. If it's useful, this is what I'm getting in the messages buffer:
`Company: An error occurred in auto-begin`
`Company: backend company-rtags async timeout with args (candidates )`

**Comment by Andersbakken** [comment]
Can you try the following:

Disable company-mode altogether.

Move around in the file and occasionally check the value of (car
rtags-last-completions)

It should have a location in it and the cdr should be a list of results. If
this doesn't work then clearly the problem is with rtags itself, not
company.

Anders

**Comment by petercheng00** [comment]
rtags-last-completions stays nil.
However, if I do rc --code-complete-at from a terminal, rtags-last-completions does update properly.

**Comment by Andersbakken** [comment]
Do you have a live diagnostics buffer? This is required for completions to
work. Also, rtags-completions-enabled must be t

**Comment by petercheng00** [comment]
Well, I feel silly - I had a typo, and had set rtags-completion-enabled instead.
Thanks so much for all the prompt help and rtags in general!

**Comment by Andersbakken** [comment]
No problem at all. Let me know if you run into other issues.

Anders
