### ISSUE TITLE
Helm support

### ISSUE THREAD

**Issue by apmanol** [Andersbakken/rtags#583]
Hello all and gratz for this great software.

I couldn't find something in the instructions so my question is how do you enable the helm support? I noticed in the rtags.el that there is the `rtags-use-helm`.

It would be very nice also, if the rtags-imenu was using the helm too.

**Comment by apmanol** [comment]
It seems that there is a related issue #545 .

**Comment by cslux** [comment]
@apmanol 

> It seems that there is a related issue #545 .

Just set `rtags-use-helm` to `t`, as stated in https://github.com/Andersbakken/rtags/issues/545#issuecomment-168099582. rtags-imenu will than be displayed in the helm interface too. It least for me, if not, try the helm-imenu.
This is what I have in my init.el
```
(use-package imenu
  :ensure t
  :defer t
  :bind ("C-c h i" . helm-imenu)
  :init
  (autoload 'helm-imenu "imenu" nil t))
```
Christian

**Comment by Andersbakken** [comment]
With rtags-use-helm it should also display
rtags-find-references/rtags-find-symbols etc with helm.

regards

Anders

**Comment by amosbird** [comment]
@Andersbakken  Could `rtags-find-symbol` use helm in the first place instead of filtering specific symbol result? Just like IDE's fuzzy find symbol.

**Comment by vibrys** [comment]
@amosbird do You mean #587 ?

**Comment by Andersbakken** [comment]
I merged the PR. Let me know if it works out. I'm a little worried that the
sheer amount of alternatives sometimes can make it problematic to use.

Anders

**Comment by amosbird** [comment]
@vibrys Yes. And I've tried this new feature. It takes about 10 seconds to get the helm output when typing in new characters. It works however not quite useful. ![](http://i.imgur.com/af1X0GB.jpg)

**Comment by Andersbakken** [comment]
Maybe we could have a system whereby it arrives asynchronously over the
diagnostics channel. Then we could fall back to previous behavior if we
don't have a full cache in elisp but use this if we've received everything
we need.

Anders

**Comment by vibrys** [comment]
@amosbird - here are details about the delay.
https://github.com/emacs-helm/helm/issues/1366

 It was working without delay for a while just before the revert of the above.

This is also the reason why I reverted the change from rtags as well.

regards
