### ISSUE TITLE
Working with ccache or supersede it.

### ISSUE THREAD

**Issue by amosbird** [Andersbakken/rtags#585]
README says rtags has a `man-in-the-middle` approach which looks quite like ccache. I wonder if rtags can help boost compilation progress just like ccache does. If not, will rtags benefit from using ccache locally?

**Comment by Andersbakken** [comment]
As it is libclang can't open a .o file and get the AST from it so I don't
know if there's any chance of alleviating ccache for faster indexing.. You
have to add an additional parameter to export the AST from a compilation
command and the output is huge compared to the object files so I'm not sure
how viable it is.

Anders

**Comment by cslux** [comment]
I honestly don't think that rtags it self will benefit from ccache, if the cache can be reused for the actual build of the project you will benefit from it dramatically, but for small to medium size projects (< 10^6 LOC), I don't think it is worth the work. Also the disk usage would be huge, I mean really huge, especially if debug symbols are included. For chromium you would need 20-50 GB of disk storage if not more.

@Andersbakken Do you know if it is easily possible to integrate rtags with [icecream](https://github.com/icecc/icecream) or [distcc](https://github.com/distcc/distcc), to speed up the parsing for big projects (> 10^6 LOC), like Firefox, Chromium etc..

**Comment by Andersbakken** [comment]
I don't really think there's much we can gain from the distributed build
systems. We actually had our own distributed solution back in the day but
the benefits weren't enough and I hated the code so I killed it.

Anders

**Comment by cslux** [comment]
> I don't really think there's much we can gain from the distributed build systems. We actually had our own distributed solution back in the day but the benefits weren't enough and I hated the code so I killed it.

Ok, good to know, so I can forget about it... for now :-D

**Comment by Andersbakken** [comment]
:-)
