### ISSUE TITLE
crash detected in code completion

### ISSUE THREAD

**Issue by velkyel** [Andersbakken/rtags#586]
another rdm assert:

```
Assertion failed: (FromClassification.isLValue()), function TryObjectArgumentInitialization, file /private/tmp/llvm3720151203-62789-1xdiv3g/llvm-3.7.0.src/tools/clang/lib/Sema/SemaOverload.cpp, line 4746.
libclang: crash detected in code completion
Assertion failed: (TemplateIds.empty() && "Still alive TemplateIdAnnotations around?"), function ~Parser, file /private/tmp/llvm3720151203-62789-1xdiv3g/llvm-3.7.0.src/tools/clang/lib/Parse/Parser.cpp, line 446.
Caught signal 6
1/15 sigSegvHandler(int)
2/15 _sigtramp
3/15 0x0
4/15 abort
5/15 abort
6/15 clang::Parser::~Parser()
7/15 clang::Parser::~Parser()
8/15 llvm::CrashRecoveryContext::~CrashRecoveryContext()
9/15 clang_codeCompleteAt
10/15 CompletionThread::process(CompletionThread::Request*)
11/15 CompletionThread::run()
12/15 Thread::localStart(void*)
13/15 _pthread_body
14/15 _pthread_body
15/15 thread_start

```

**Comment by Andersbakken** [comment]
I've frankly seen a lot of assertions in libclang that seems not to be
fatal if you compile without asserts. Maybe I should run the completions in
a separate process to be able to respawn.

I think you might be better off compiling clang without assertions enabled.
It's sort of a known issue that clang crashes some times and longjmp's back
to the calling thread. I believe this might be what's going on here (though
I can't say for sure, did you see a message like this printed just before
it?

libclang: crash detected in code completion

Anders

**Comment by velkyel** [comment]
you are right.  I've reinstall llvm37 (brew) with --without-assertions switch and rdm works fine.  Maybe it's a solution for #578 too.
thanks
