### ISSUE TITLE
Adding new file to an project

### ISSUE THREAD

**Issue by rajukv** [Andersbakken/rtags#589]
What is the procedure to add a new file to an existing project? Should I provide the new file and its compile command in a seperate compile_commands.json or should I provide a new compile_commands.json with all the old files and the new files?

**Comment by cslux** [comment]
@rajukv It is sufficient to update the compile_comamnds.json! rtags will automatically detect the changes.

Christian

**Comment by rajukv** [comment]
Thanks for your response Christian. I assume that removing and entry from compile_commands.json would also remove the file's entry from rtags?

**Comment by cslux** [comment]
@rajukv It should ;-). If not, something is wrong!

**Comment by cslux** [comment]
@rajukv I close this issue! If you encounter any issue feel free to reopen it, or create a new issue.

regards,
Christian
