### ISSUE TITLE
Indexing crashing after update

### ISSUE THREAD

**Issue by deuscovrigus** [Andersbakken/rtags#590]
So I haven't git pulled in a while, so I decided to do so, after building, installing, clearing my projects with rc -C and then reparsing the build json with rc -J .
I get the following trace whenever I attempt a completion or I type something in a c++ source file :

Wrong Protocol 76 vs 83
Clang Indexer Error
I double checked rdm --version and rc --version and both seem to return 2.0.83
Jumping to definition seems to work fine.
It might be something on the emacs side as the rtags-ac module stopped working.
(require 'rtags-ac) yields this error trace:

Debugger entered--Lisp error: (void-variable rtags)
  byte-code("\301\302\303\"\210\304\305\"\210\306\307!\207" [rtags add-hook rtags-completions-hook rtags-ac-completions-hook ac-define-source ((init . rtags-ac-init) (prefix . rtags-ac-prefix) (candidates . rtags-ac-candidates) (action . rtags-ac-action) (document . rtags-ac-document) (requires . 0) (symbol . "r")) provide rtags-ac] 3)
  require(rtags-ac)
  eval((require (quote rtags-ac)) nil)
  eval-expression((require (quote rtags-ac)) nil)
  call-interactively(eval-expression nil nil)

I am currently at  revision 88ec0aeec9cbc9a5c12211295a16d02896b90821
Any ideas?

**Comment by Andersbakken** [comment]
This basically means that you're mixing versions of executables. Almost
certainly your rc is older. The versions are kinda not really bumped very
often so sadly that doesn't help that much. I should do something about
that.

Can you double check the paths?

Anders

**Comment by deuscovrigus** [comment]
I double checked today (but also made sure yesterday) that both rc --version and rdm --version return 2.0.83
Both of them are located in/usr/local/bin and there are no other copies.
I also tried scanning the rtags source tree, and although the indexer isn't crashing and I don't get that error, completion doesn't work or error underlining. if I type anything then save the buffer, the rdm output just looks like this:

Got completion request for src/ClangIndexer.cpp:66:1:
/usr/local/bin/rc --current-file=/home/octi/rtags/src/ClangIndexer.cpp --no-color --prepare-code-complete-at /home/octi/rtags/src/ClangIndexer.cpp:65:5:
Got completion request for src/ClangIndexer.cpp:65:5:

without any feedback to emacs

**Comment by cslux** [comment]
> Got completion request for src/ClangIndexer.cpp:66:1:
> /usr/local/bin/rc --current-file=/home/octi/rtags/src/ClangIndexer.cpp --no-color --prepare-code-complete-at /home/octi/rtags/src/ClangIndexer.cpp:65:5:
> Got completion request for src/ClangIndexer.cpp:65:5:

Strange, I have the same problem regarding completion (company), but only at work. At home, everything works. Same project but different GNU/Linux OS. Error underlining however works. 

Can you check, if there is a buffer called *RTags Diagnostics*.

**Comment by deuscovrigus** [comment]
Update: I got completion to work by byte-compiling the file myself. The one compiled by make in the rtags source tree yields the following backtrace when running (require 'rtags-ac)
Debugger entered--Lisp error: (void-variable rtags)
  byte-code("\301\302\303\"\210\304\305\"\210\306\307!\207" [rtags add-hook rtags-completions-hook rtags-ac-completions-hook ac-define-source ((init . rtags-ac-init) (prefix . rtags-ac-prefix) (candidates . rtags-ac-candidates) (action . rtags-ac-action) (document . rtags-ac-document) (requires . 0) (symbol . "r")) provide rtags-ac] 3)
  require(rtags-ac)
  eval((require (quote rtags-ac)) nil)
  eval-expression((require (quote rtags-ac)) nil)
  call-interactively(eval-expression nil nil)

**Comment by deuscovrigus** [comment]
Ok so now *sometimes* I get error underlining, but as soon as I corrected, the underline still exists, and the error message in the minibuffer is not going away. Similarly to typing something incorrect, the error message/underline does not appear.
I have work to do now, but I hope I can find the previous commit where everything worked because I just updated rtags and ended up into a hot mess.

**Comment by deuscovrigus** [comment]
This might help and looks suspicious when running  rp --version :
About to die 0 2 0
1/5 Deserializer::read(void*, int)
2/5 ClangIndexer::exec(String const&)
3/5 rp(main+0x2fc) [0x4388fc]
4/5 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7ffb1eb2bec5]
5/5 rp() [0x439b8b]

**Comment by deuscovrigus** [comment]
Ok so once I made sure rtags works on my mac with the lastest version, I installed llvm-3.6 and pulled did a git pull and now it works as expected. At this point i'm not sure whether the git pull help or whether llvm-3.6 fixed my issue.

**Comment by Andersbakken** [comment]
Hi

rp is not really meant to be run like that. It's only exec'ed from rdm so
it doesn't really have a version argument.

Either way I guess it works now. Let me know if you have other problems.

Anders
