### ISSUE TITLE
 Emacs freezes for a short period of time when moving cursor

### ISSUE THREAD

**Issue by cslux** [Andersbakken/rtags#591]
Hey Anders,

at work emacs freezes for a short period of time (~5 sec.)  when rc calles rdm. This doesn't happen at home on the same project.

Notes:
 - Project is chromium
 - At home I use Fedora, at work Debian Wheezy. 
 - Emacs 24.5
 - At work chromium gets cross-compiled for arm, at home for the host (I don't think this has any influence)
 - On both machines the project is located on a SSD as well as the rtags cache.
 

After the following output of rdm I can move the cursor again in emacs.
``` bash
Query opened 71083 files for project /path/to/chromium
```

For me it seems my laptop has a better I/O than the server :-D. 

rdm flags
 - --job-count 4
 - --completion-cache-size 200
 - --no-comments
 - --rp-nice-value 19
 - --no-filemanager # only 8192 watches are available at work, but roughly 80.000 are needed
 - --no-filemanager-watch
 - --enable-compiler-manager # wasn't able to get the include path, so I added them manually
 - --no-filesystem-watcher
 - --data-dir /path/to/ssd/.rtags
 - --block-argument -march=armv7-a
 - --block-argument -mtune=generic-armv7-a
 - --block-argument -mfpu=vfpv4-d16
 - --block-argument -mfloat-abi=softfp
 - --block-argument -mthumb
 - --block-argument -Wno-literal-suffix
 - --block-argument -Winconsistent-missing-override
 - --isystem /cross/toolchain/includes ...
 
I tried it with the same flags at home, but without the compiler-manager, block-argument and isystem flags. But no freezes (lags) there.

Do you have an idea would could causing this, or how to avoid it, maybe with some other flags? Or maybe you have an idea how to further triage this problem?

Thanks,
Christian

**Comment by floli** [comment]
I have the same behavior, the echo area indicates "Reparsing FileIAmWorkingOn"

**Comment by cslux** [comment]
Some more nodes, rdm has done parsing the project, nor did I modified the file, just moving and jumping around in the project. 

@floli Is this also valid for you? According to the message you have posted, you have modified the file, and rtags is reparsing it to be up to date. The reparsing causes some delays until it is done. However, you can turn of the automatic reparsing, and trigger it manually via `C-c r e`, if you have enabled the rtags standard key bindings. 

The following `rdm` flag prevent the reindexing `--no-filesystem-watcher`
If you want disable indexing on startup too, pass `--start-suspended` to rdm.
See `rdm --help` or `man rdm` for more information about this flags and other possibly flags.

Christian

**Comment by floli** [comment]
Here, I think it's connected to changing the file but there is no need to actually save the file for triggering the reparsing message.
Anyway, I thought that rdm parses the file, so why does reparsing causes lag in Emacs?

**Comment by cslux** [comment]
@floli Correct, you don't need to save it. Well, when rtags is currently parsing a project, than it doesn't always respond immediately to the `rc`, when you call any of the `rtags-*` functions in emacs.

**Comment by cslux** [comment]
However, you could limit the amount of concurrent parsing jobs and/or adjust the nice value, for `rp`. So rdm can respond more quickly and b) the system load wont be always at 100% due to the rtags parser. I personally recommend adjusting those values anyway, especially if you use rtags for large scale projects. Otherwise your hole system will be pretty unresponsive.

**Comment by cslux** [comment]
I think I might have found out what was causing those small freezes.
After restoring the original values (nil) of `rtags-show-containing-function` and `rtags-track-container`, those small freezes/lags did go away.

**Comment by Andersbakken** [comment]
Ah. Sounds good.

Hm. That seems to indicate a bug in one these features. Can you figure out
which of the two is causing the problem? (Assuming it isn't a combination).

Anders

**Comment by cslux** [comment]
Sure that! ☺

**Comment by cslux** [comment]
The freezes are coming from `rtags-track-container`, as conceived. 
The profiler doesn't show any significant cpu usage. What I have noticed, it happens pretty much every time on either variable declarations or definitions.

**Comment by cslux** [comment]
This is the output when I do, `M-x toggle-debug-on-quite RET` move the cursor with the mouse to one of the location where it always happen, and hit `C-g C-g`.
``` emacs-lisp
Debugger entered--Lisp error: (quit)
  call-process("/home/cschwarzgruber/.local/bin/rc" nil (t nil) nil "--current-file=/path/to/chromium/src/ui/aura/test/test_focus_client.h" "-o" "--silent-query" "--no-color" "-U" "/path/to/chromium/src/ui/aura/test/test_focus_client.h:35:49:" "--elisp")
  apply(call-process "/home/cschwarzgruber/.local/bin/rc" nil (t nil) nil ("--current-file=/path/to/chromium/src/ui/aura/test/test_focus_client.h" "-o" "--silent-query" "--no-color" "-U" "/path/to/chromium/src/ui/aura/test/test_focus_client.h:35:49:" "--elisp"))
  process-file("/home/cschwarzgruber/.local/bin/rc" nil (t nil) nil "--current-file=/path/to/chromium/src/ui/aura/test/test_focus_client.h" "-o" "--silent-query" "--no-color" "-U" "/path/to/chromium/src/ui/aura/test/test_focus_client.h:35:49:" "--elisp")
  apply(process-file "/home/cschwarzgruber/.local/bin/rc" nil (t nil) nil ("--current-file=/path/to/chromium/src/ui/aura/test/test_focus_client.h" "-o" "--silent-query" "--no-color" "-U" "/path/to/chromium/src/ui/aura/test/test_focus_client.h:35:49:" "--elisp"))
  rtags-call-rc(:path "/path/to/chromium/src/ui/aura/test/test_focus_client.h" :noerror t :silent-query t "-U" "/path/to/chromium/src/ui/aura/test/test_focus_client.h:35:49:" "--elisp")
  rtags-symbol-info-internal(nil nil t)
  rtags-current-container-name()
  rtags-update-current-container-cache()
  apply(rtags-update-current-container-cache nil)
  byte-code("r\301\302H\303H\"\210)\301\207" [timer apply 5 6] 4)
  timer-event-handler([t 0 0 500000 nil rtags-update-current-container-cache nil idle 0])
```

**Comment by floli** [comment]
I have both ```rtags-show-containing-function``` and ```rtags-track-container``` untouched i.e. set to nil. Still I experience the freeze while reparsing. I'm now also experiencing it also when only moving/scrolling around without changing anything.

**Comment by cslux** [comment]
~~Do you experience the same freezes when rtags is not reparsing?~~ Did you try setting `--job-count=CPU_COUNT/2` as well as `--rc-nice-value=19`? Do you see any significant cpu usage in your system taskmanger? What also could be a problem is the disk I/O performance on your machine.  And you could also start `rdm` with `-vvv`, or fewer `v`, to see what is doing.

Last but not least, could you profile Emacs when moving the cursor and post the result here.
1. Enable profiler for cpu only `M-x profiler-start RET`
2. Move cursor around
3. Print profiler report `M-x profiler-report RET`
4. Disable profiler `M-x profiler-stop RET`
See https://www.gnu.org/software/emacs/manual/html_node/elisp/Profiling.html for more information about profiling Emacs.

regards,
Christian

**Comment by Andersbakken** [comment]
It might be useful to check what rtags seemed to be doing at the time it
froze.

Can you try this:

(setq rtags-rc-log-enabled t)

Then, after reproducing it take a look at the *RTags Log* buffer to see
what we were calling.

Anders

**Comment by floli** [comment]
Hey,

this is RTags Log when a reparsing is done
```
**********************************
/usr/bin/rc --current-file=/home/florian/precice/src/cplscheme/tests/PostProcessingMasterSlaveTest.cpp --silent-query --no-color -T /home/florian/precice/src/cplscheme/tests/PostProcessingMasterSlaveTest.cpp
**********************************
/usr/bin/rc --current-file=/home/florian/precice/src/cplscheme/tests/PostProcessingMasterSlaveTest.cpp --unsaved-file=/home/florian/precice/src/cplscheme/tests/PostProcessingMasterSlaveTest.cpp:36123 --no-color --silent -V /home/florian/precice/src/cplscheme/tests/PostProcessingMasterSlaveTest.cpp --wait
**********************************
/usr/bin/rc --current-file=/home/florian/precice/src/cplscheme/tests/PostProcessingMasterSlaveTest.cpp --no-color --declaration-only -N -f /home/florian/precice/src/cplscheme/tests/PostProcessingMasterSlaveTest.cpp:605:28: -K
**********************************
/usr/bin/rc --current-file=/home/florian/precice/src/cplscheme/tests/PostProcessingMasterSlaveTest.cpp --unsaved-file=/home/florian/precice/src/cplscheme/tests/PostProcessingMasterSlaveTest.cpp:36123 --no-color -N -f /home/florian/precice/src/cplscheme/tests/PostProcessingMasterSlaveTest.cpp:605:28: -K
```
The file was changed, but not saved. But there was definitely no change between the previous reparsing and this one.

This is the CPU profiler report. Same file, changed, but not saved and no changes since the last reparse. I was just moving around a lot.

```
+ command-execute                                                1362  54%
+ beacon--post-command                                            370  14%
+ redisplay_internal (C function)                                 285  11%
+ ...                                                             271  10%
+ timer-event-handler                                             201   7%
- rtags-post-command-hook                                           8   0%
 - rtags-restart-update-current-project-timer                       4   0%
  - run-with-idle-timer                                             4   0%
   - timer-activate-when-idle                                       3   0%
    - timer--activate                                               3   0%
       timer--time-less-p                                           3   0%
  beacon--record-vars                                               3   0%
+ flycheck-error-list-update-source                                 3   0%
+ flycheck-display-error-at-point-soon                              3   0%
+ semanticdb-save-all-db-idle                                       3   0%
  xselect-convert-to-string                                         2   0%
+ company-post-command                                              1   0%
+ beacon--vanish                                                    1   0%
```
rdm is running without special arguments, but it's niceness is set to 5 by systemd --user. I don't think the lag is caused by the daemon, the rest of the system runs smoothly. I also doubt that it's IO problem. The entire system and code are on a SSD on a modern machine with no load otherwise.

**Comment by Andersbakken** [comment]
Sorry about the long delay. 

Could you try to set rtags-enable-unsaved-reparsing to nil?

I suspect it might be part of the problem.

**Comment by floli** [comment]
Yes, this did the trick. Thanks!

**Comment by Andersbakken** [comment]
I don't think that one is from rtags. Can't seem to find anything that outputs something like that in our code and I can't remember seeing it. Glad to hear it helped. I've been considering turning rtags-enable-unsaved-reparsing off by default.
