### ISSUE TITLE
rtags-calculate-completion-point fails

### ISSUE THREAD

**Issue by azuk** [Andersbakken/rtags#593]
Consider the following case:
```
int main(int argc, char** argv)
{
    if (mai<cursor here>)
    {
    }
}
```
I can't get completions using `company-complete`. The reason seems to be that `rtags-calculate-completion-point`, called by `rtags-update-completions`, returns `nil` because point is not at the end of the line and we are not `looking-at` certain characters.

Related to this, it seems that instead of asking clang for completions at the current point (at the end of the "prefix"), the idea is to ask for completions at the beginning of the prefix and then find the right one out of those based on the prefix, using Emacs Lisp. Does the clang API require it to be done like this or is there another reason?

I'm using e384cd0976ea6ff8cf94a1c62a2d820972a4b8d1 of rtags and fairly recent master branch version of clang.

**Comment by Andersbakken** [comment]
Hi Hannu

That's indeed a bug. I checked in something that I believe will take care
of it.

The libclang model for completion does indeed expect you to pass the
location of the beginning of the prefix and do your own filtering. See here
for more info:

http://clang.llvm.org/doxygen/group__CINDEX__CODE__COMPLET.html#ga50fedfa85d8d1517363952f2e10aa3bf

Anders

**Comment by azuk** [comment]
I verify that the fix solves the problem.

If I were nitpicking, I'd point out that `(skip-chars-backward rtags-symbol-chars)` doesn't cover all source code representations of (beginnings of) all identifiers, at least those split across lines or those containing universal characters, but perhaps those two cases are not that important :)

**Comment by Andersbakken** [comment]
We'd love a pull request that would take care of that :-)

Anders
