### ISSUE TITLE
is there a way to let rtags works with cross compiler  like arm-linux-gcc

### ISSUE THREAD

**Issue by pangchol** [Andersbakken/rtags#594]
cause I a embedded SDE, I am very like rtags's work style with gcc. but, is there any way to let rtags works with arm-linux-gcc? as I know rtags is base on clang, so I can't think out how to do it. maybe it's impossible. but I just want to know whether or not have no way.

**Comment by pangchol** [comment]
oh, it amazing !!! I see the " rtags and cross compiler #100 " report and try to creat a softlink from arm-linux-gcc to gcc-rtags-wrapper.sh and rebuild my project by using make. rtags find it and working. I have been unable to suppress my love for the rtags.  Thanks again for your hard work on this beautiful software.

**Comment by Andersbakken** [comment]
Glad to hear you like it. Let us know if you have problems getting stuff to
work or suggestions for improvements.

Anders
