### ISSUE TITLE
rtags-last-completions not updated on one project but gets on another, broken database?

### ISSUE THREAD

**Issue by cslux** [Andersbakken/rtags#595]
Hey Anders,

I mentioned in one of my comments that completion does not work for chromium at work but does work at home. Only difference is that at work the project is cross-compiled using arm-linux. Strange thing, completion does work for the Linux kernel, also cross compiled for arm-linux. Could this have something to do with a broken database, I'm not quite sure as jumping around works. `rdm` doesn't return anything when requesting completion, but it does for the Linux kernel. :-/

Thanks,
Christian

**Comment by Andersbakken** [comment]
Hi Christian

It's kinda involved how all of that works. One thing that might be worth
checking out is to start an rc command in a shell:

$ rc -m --elisp

This should print all diagnostics as they come in which should include
completions.

I would do that. Then go to a spot where you think completions should work
and do:

M-: (rtags-update-completions t)

Ideally now some output related to completions (possibly quite a lot)
should come into the rc command.

Anders

**Comment by cslux** [comment]
Unfortunate nothing to see. `rtags-update-completions` always returns 1, means completions got updated, but nothing actually happens. BTW, I have reparsed the project.  

I instrumented the function `rtags-update-completions` with edebug and called it once more for the chromium project as well as the linux-kernel. The requested location for code completion seems to be wrong for the chromium project, the column location is always minus two what emacs shows while on the linux-kernel it is minus one, which is correct. This is probably why it doesn't work, but I have know idea why this happens. Any idea?

Christian

**Comment by Andersbakken** [comment]
Hm. That's definitely interesting. Can you run file on the sourcefile?

Maybe it's encoded differently or has windows newlines or something like
that.

Anders

**Comment by cslux** [comment]
> Maybe it's encoded differently or has windows newlines or something like that.

`buffer-file-coding-system` variable value is "undecided-unix" for the linux-kernel as well as chromium.

> Can you run file on the sourcefile?

Sorry, I don't know what you mean by "run file on the sourcefile".

Christian

**Comment by cslux** [comment]
> I instrumented the function rtags-update-completions with edebug and called it once more for the chromium project as well as the linux-kernel. The requested location for code completion seems to be wrong for the chromium project, the column location is always minus two what emacs shows while on the linux-kernel it is minus one, which is correct. This is probably why it doesn't work, but I have know idea why this happens. Any idea?

You can ignore this, it's the same with one of the file from the Linux kernel, must be some other problem.

**Comment by Andersbakken** [comment]
Hi Christian

I guess we're not thinking this is the issue anymore but I was thinking in
a terminal.

E.g.

$ file /path/to/file.c

Anders

**Comment by cslux** [comment]
Hmmm, it works now. I'm not entirely sure if my compile command transformation is the reason why it is working now or due some changes in rtags.

All I did was to transform the -mtune=...arm, -march=arm... etc., and some other flags to clang equal flags. This also made the parsing much more accurate. Most off the `rp` (clang) warnings/errors I got before, are gone now (Chromium project).

It seems to be important to transform the GCC architecture flags to clang equal ones to get correct results.
I noticed clang doesn't support the `-specs` flag, so I had to transform those compile commands, and extract the content of the `*.specs` file (different project, but also for ARM). But after doing this, I got zero warnings from the parser (clang) and everything else (completion, ...) works too.

I'll close this issue!

Christian

**Comment by Andersbakken** [comment]
Strange. As long as it works I guess.

:-)

Anders

**Comment by cslux** [comment]
It is! My words where not as accurate as they have should been. Completion works partly, in other words I do get compiletion for chromium now, however, the completion result doesn't contain all possible completion. For instance, I do not get completion for a `std::string` variable, and there are likely more cases where I do not get completion. 

Maybe I do need to transform the compile commands even more to get full completion support :-/. 

As soon as I find something new out I will post it here, or create a new issue.

Christian

**Comment by Andersbakken** [comment]
Sounds good.

Anders
