### ISSUE TITLE
Reindexing occurs even though nothing has changed

### ISSUE THREAD

**Issue by Helsingfors** [Andersbakken/rtags#596]
Firstly, thanks for producing rtags.  Without it I would be lost when using Vim on large code bases. 

I am using version 2.0.83 of rtags on Fedora 20.

I start rdm with "rdm  --isystem /usr/lib/clang/3.4.2/include"  and then index the code with "rc -c clang++ -o ....".  Everything works fine apart from one problem.  This occurs when:

- there are no code changes

- I do a rebuild of my source code using scons

This then triggers all the source files to be reindexed by rtags.  The only thing that has changed is that every time scons rebuilds it updates one file  (.sconsign.dblite) in the top level directory. 

Is there anyway that I can avoid rtags reindexing even though there are no code changes?  Ideally I would like to avoid turning off the filesystem watching (-B option).

Mark

**Comment by Andersbakken** [comment]
I guess everything includes sconsigndblite somehow then.

There is one option you can use:

rc --suspend /path/to/sconsigndblite

Will tell rdm to ignore changes that happens to this file.

Let me know if it works.

Anders

**Comment by Andersbakken** [comment]
Is this by the way how scons always works? If so we might want to just put
something into rdm to always ignore this file. What does it contain?

Anders

**Comment by Helsingfors** [comment]
I have tried the "rc --suspend /path/to/sconsigndblite" and it did not work.

The .sconsign.dblite is used as a temporary database to speed up builds.  I think this is the way SCons usually works.

Reading the SCons documentation, there might be a way to move the .sconsign.dblite to an alternative location so I will try that.

Thanks,

Mark

**Comment by Helsingfors** [comment]
I have moved the location of .sconsign.dblite from the build directory to my home directory. This did not solve the problem and rtags is still re-indexing even when there are no changes.

Mark

**Comment by Helsingfors** [comment]
I have used the -vv option on rdm and this tells me that certain .h/.cc files have changed (the timestamp has changed on these files but the contents are the same).  These files are auto generated from google protobuf specifications.  This is occurring even though there are no changes.  This means that the problem might lie with our build system rather than rtags.  I will investigate further.

Mark

**Comment by Andersbakken** [comment]
Ah. That makes sense. I actually had to make some changes to the build
system we use at work to avoid the same problem.

Anders

**Comment by Helsingfors** [comment]
I have identified all the auto generated source files and used the "--suspend" option.  This has solved my problem.

Many thanks,

Mark
