### ISSUE TITLE
Inclusion directive fails with quotes

### ISSUE THREAD

**Issue by minijackson** [Andersbakken/rtags#597]
Hello, I'm using [meson](https://github.com/mesonbuild/meson) as a build system, which generates rules for Ninja, and quotes MANY arguments in the rules, which can leads to commands like this:
```
ccache c++  '-pipe' '-Wall' '-std=c++14' '-g' '-I../src/an-include-path' '-I./src/myLib/.' -o 'src/myExec.bin@exe/mySource.cpp.o' -c ../src/mySource.cpp
```

and I get something like that when looking at the output of rdm:

```
rdm[20063]: Output from /path/src/mySource.cpp:
rdm[20063]: /path/src/mySource:1:10: fatal error: 'file-in-include-path.hpp' file not found
rdm[20063]: couldn't create included file inclusion directive i file-in-include-path.hpp /path/src/mySource.cpp:1:1
```

So my humble hunch is that rtags does not support parsing quoted include directives, or is it me who failed to read the instructions?

**Comment by Andersbakken** [comment]
Sorry about the long delay. Quotes are definitely supported (this is actually done by clang itself so there's no room for us to mess that up) but since these includepaths are relative my hunch is that the working directory somehow is wrong. 

Can you try to do this:

rc --sources  mSource.cpp 

This should print out the compilation flags rtags will use to index this file and it should include resolved paths for all includepaths. Can you verify that these paths are correct?

regards

Anders

**Comment by minijackson** [comment]
Here's the output (less cleaned up than in my first post):

```
/usr/bin/ccache /usr/bin/c++ -pipe -Wall -std=c++14 -g -MMD -MQ 'src/myExec.bin@exe/mySource.cpp.o' -MF './src/myExec.bin@exe/mySource.cpp.o.d' -c -ferror-limit=0 -fspell-checking -II/usr/include' -II./src/myExec.bin@exe' -II../src' -II./src' -II./src/myLib/.' -II.././src/myLib/.' -isystem /usr/lib/clang/3.7.1/include/ /home/.../topLevel/src/mySource.cpp Build: /home/.../toplevel/ Parsed: 2016-02-22 17:51:31 Active
```

And indeed, the includepaths are not correct considering the working directory:
Runing `rc -w` gives me:
```
/home/.../topLevel/ <=
```

whereas the correct for these includepaths directory would be:
```
/home/.../topLevel/build/ <=
```

But I find it a bit weird that the includepaths are specified with `-II` and ended with an unmatched single quote.

Thanks

**Comment by minijackson** [comment]
After doing a manual unquoting (I do not have files with spaces):
```
ninja -t commands | sed "s/'//g" | rc -c
```

I find that everything works fine and every includepaths is now an absolute path, with a single `-I` and no single quote and the end of each include directive.

**Comment by Andersbakken** [comment]
I suppose we could assume that an argument that starts and ends with. I
added something. Can you check if it works?

Anders

**Comment by minijackson** [comment]
Yep, everything seems to work: no more compilation failures due to inclusion directives, `rc --sources mySource.cpp`  have coherent includes and absolute paths, and the editor plugin works!

Thank you very much!

**Comment by Andersbakken** [comment]
Glad to hear.

Anders
