### ISSUE TITLE
Use of own location stack

### ISSUE THREAD

**Issue by magthe** [Andersbakken/rtags#600]
What's the reason for using `rtags-location-stack-X` instead of the mark-ring (via `push-mark` and `pop-mark`)?

**Comment by Andersbakken** [comment]
Most likely because I'm relatively ignorant of these functions :-)

I thought they didn't move the point which kinda is what we want to do
here. I'm quite likely to be mistaken about some of this though.

Anders

**Comment by floli** [comment]
Would be great, if you used the standard stack. That would simplify configuration if using emacs on systems with and without rtags.
``` (bind-key "M-*" 'rtags-location-stack-back c-mode-base-map)``` would be unecessary und would not interfer with other modes using the stack.

**Comment by Andersbakken** [comment]
Unless I read the docs wrong the standard stack is buffer-local though.
This seems like it wouldn't really work well for our goals. There's of
course no reason why I can't use both stacks. Is the short version that I
should do (push-mark) whenever I've made a jump?

Anders

**Comment by floli** [comment]
I guess so, it looks like it's used like that by etags.el.
Since mark-ring is buffer local, I think (push-mark) etc. are also working buffer local. I never had a problem, when I was still working with gtags. What is the problem here? (just curious) :-)

**Comment by magthe** [comment]
This is taken from *haskell-mode*:

```elisp
;; Cross-referencing commands have been replaced since Emacs 25.1.
;; These aliases are required to provide backward compatibility.
(unless (fboundp 'xref-push-marker-stack)
  (defalias 'xref-pop-marker-stack 'pop-tag-mark)

  (defun xref-push-marker-stack (&optional m)
    "Add point to the marker stack."
    (ring-insert find-tag-marker-ring (or m (point-marker)))))
```

would that not be enough?

Well, the reason why I bumped into this was that I tried out a patch to add *rtags* to *spacemacs* and noticed that from the defaults I could only jump in one direction. When looking into why the keyboard shortcut to `pop-tag-mark` didn't work I found that *rtags* uses its own way of keeping track of past locations.

**Comment by magthe** [comment]
Oh, I realise I should have written `pop-tag-mark` in the question...

**Comment by Andersbakken** [comment]
Ah. This seems to be a part of etags. Hm. I didn't even realize etags was
bundled with emacs. I suppose we could/should try to integrate with it. I
don't suppose you'd want to make a pull request? There's no reason why we
don't outside of ignorance.

Anders
