### ISSUE TITLE
"ninja -t commands" may include commands rc can't parse

### ISSUE THREAD

**Issue by tomjakubowski** [Andersbakken/rtags#601]
My project that uses node-gyp produces `ninja -t commands` output which looks like this:

```
c++ ... -c ../../src/foo.cc -o obj/src/project.foo.o
...
if [ ! -e project.node -o ! -e project.node.TOC ] || otool -l project.node ...
```

It seems that if I pipe this to `rc -c -`, rc exits with an error code of 1.  Presumably this is because rc fails to parse the last command as a c++ compiler invocation. If I use grep to filter out lines that start with `if`, rc exits with an error code of 0. I have some scripts that I'd like to run with `set -e`, so the error code matters (I know how to work around this; unfortunately, without the "grep hack", it's hard to distinguish genuine rc failures from cases where it just can't parse the last line)

Is it worth adding a heuristic to rtags to ignore commands that don't look like C or C++ compiler invocations? Seems kind of gross. Maybe there's a better way to deal with this (maybe just skip lines that can't be parsed, but consider the operation as a whole a success?). Maybe it's not an rtags issue at all and this ticket should be closed. But I thought I'd let you know about this situation.

**Comment by Andersbakken** [comment]
Hi

I think it should be fixed now. It seems arbitrary to let the last command decided the return value of the whole rc invocation so I decided to say that one command that exits with 0 is good enough to return 0.

**Comment by tomjakubowski** [comment]
Awesome! Thanks so much.
