### ISSUE TITLE
rtags-find-references-at-point and rtags-find-virtuals-at-point do not re-size

### ISSUE THREAD

**Issue by ramblehead** [Andersbakken/rtags#602]
Dear rtags team,

I recently updated my rtags to commit 3b8b9d5 (05/02/2016). Everything is still working ;)
There is an issue I noticed in compare with the previous version I used: before automatic windows with code refs for subj. used to shrink themselves to the minimum height. They do not do that any more. rtags-references-tree core refs window height shrinks correctly.

Victor.

**Comment by Andersbakken** [comment]
Ah. I hadn't noticed since I tend to split horizontally. Should be fixed now. Thanks for the report.
