### ISSUE TITLE
rdm fails to reload existing project on restart

### ISSUE THREAD

**Issue by jaytiar** [Andersbakken/rtags#603]
When restarting rdm I get a "Can't restore project xxx" error, even though the contents of ~/.rtags looks fine and there is no corruption.

Tracked down a problem loading the project file. 

In Server.cpp in Server::load(), you open the existing project by adding "project" to the file variable, but that value is a directory name with no trailing slash, so the file fails to open.
if (FILE *f = fopen((file + "project").constData(), "r")) {

Needs to change to
if (FILE *f = fopen((file + "/project").constData(), "r")) {

To add the missing slash and find the file so the database can be loaded. 

Making this change makes the reload processing work fine.
Please could you fix up? Thanks! RTags is excellent!

**Comment by Andersbakken** [comment]
Should be fixed now. It's a little odd. The dirs should strictly speaking
have had trailing slashes on them but this fix won't hurt.

Thanks for the report.

Anders
