### ISSUE TITLE
rtags-last-request-not-indexed is not set as expected by tags-find-symbol-at-point

### ISSUE THREAD

**Issue by azuk** [Andersbakken/rtags#604]
Near the end of README.org  you have some example code for falling back to other taggers. It includes the following:
```
(defun tags-find-symbol-at-point (&optional prefix)
  (interactive "P")
  (if (and (not (rtags-find-symbol-at-point prefix)) rtags-last-request-not-indexed)
      (gtags-find-tag)))
```
Unfortunately, if I switch from an indexed buffer to another that isn't indexed and evaluate `(rtags-find-symbol-at-point prefix)`, I see "RTags: No results" in messages, it returns `nil` and `rtags-last-request-not-indexed` is `nil` after that. So the function above wouldn't fall back to `gtags-find-tag`.

I also don't quite understand why some example tagger-multiplexer functions use `use-rtags` and some don't.

**Comment by Andersbakken** [comment]
Ah. That stuff. I kinda wish I'd instead returned different values instead of using this ugly errno-like solution but I guess I might break some people's elisp if I changed it.

It should work now. Thanks for the report.

**Comment by Andersbakken** [comment]
Oh. And the reason some of them don't use (use-rtags) is because it saves a round-trip. For those functions, like rtags-find-symbol-at-point) and rtags-find-references-at-point, we can just try to call it and fall back to gtags based on them returning nil and setting rtags-last-not-indexed to t.
