### ISSUE TITLE
Emacs is unresponsive before reindexing starts

### ISSUE THREAD

**Issue by azuk** [Andersbakken/rtags#605]
When indexed files change, for example when I switch current version control branch in an indexed project, I see that for a while rdm consumes all CPU it can before logging indicates that it starts reindexing the changed files. In a certain project I measured that it took 2 minutes before reindexing started.

The worst part is that during that time Emacs is completely unresponsive even if I don't try to use rtags(.el) functionality. I assume some idle-timer or hook triggered functionality tries to talk to rdm but it's busy. I have set both `rtags-autostart-diagnostics` and `rtags-completions-enabled` to `t`.

**Comment by Andersbakken** [comment]
Hi Hannu

Can you reproduce this? I would recommend trying to run rdm like this:

$ rdm -v -v

To see if one can get a handle of what's going on.

If rdm's main loop somehow is blocked (which it kinda seems like) emacs
would probably lock up. We do send some messages back and forth at times.

Anders

**Comment by azuk** [comment]
I can reproduce it easily.

I added --log-file-log-level debug to my usual command (I checked that it _seemed_ to produce similar output as rdm -v -v): `rdm --silent --log-file-log-level debug --log-file "$LOGDIR/log"`.

That didn't seem to cover debug() << ... lines. I'll check if I need verbose-debug for that or if they are outside of the log mechanism.

Anyway, since logging isn't time stamped and there is a lot of output, it's rather difficult to get a big picture. I'm thinking of adding timestamps. Alternatively, or in addition, I could try running rdm under valgrind's callgrind.

I also tried attaching a debugger twice during different "stuck"-periods and execution was within Project::onDirtyTimeout() in both cases. In my test case I switched a branch in version control and due to that rtags needed to reindex a bit over 6000 files.

Sorry, I don't have useful information yet, I need to dig more.

**Comment by Andersbakken** [comment]
There's actually a thing for timestamps but it seems like it's pretty
crappy. I just added something.

You can now run like this:

rdm --log-timestamp

And get relative times to start of the application on each line.

Anders

**Comment by Andersbakken** [comment]
Hm. The onDirtyTimeout is a telling thing. Maybe I should move that
checking to a thread. Let me see how much work that would be.

Anders

**Comment by Andersbakken** [comment]
I did some profiling to optimize onDirtyTimeout and I think I was able to shave off some allocations and recursions that hopefully will help a little. Making it threaded is going to be a little tough so I'd rather not. Can you see if it made a difference?

**Comment by azuk** [comment]
Sorry for the long delay. Unfortunately if anything the problem seems worse. I no longer have the 100% same test case I measured 2min delay with but approximately the same case (with around 200 more files needing reindexing) now takes ~5min.

I have a log (another case and a slower machine) that I'm including as an attachment. Perhaps it helps. For some reason in this particular case where I switched from branch A to B there seemed to be two separate ~4min delays with some logging in between but when I switched back from B to A, there was just a single 4min delay. I had to censor all file names and I removed similar repeating lines, replacing them with "... <possible comment>".

I'll try to dig more/better information, this has been a bit slow since I've had to test only "in production".

PS. Extra "(" in ClangIndexer.cpp:1280 needs to be removed for build to succeed.
[rtags-log-to-master-trimmed.txt](https://github.com/Andersbakken/rtags/files/143112/rtags-log-to-master-trimmed.txt)

**Comment by azuk** [comment]
I ran rdm (debug build) under valgrind's callgrind. In the attachment you can see an exported callgraph from kcachegrind (original profile data file is available on request). Profiling was done during the "stuck" period, for about 10min or so. Numbers in parenthesis "(1234x)" are call counts and other numbers are instruction costs.

Since I normally use debug builds, I also measured difference between release and debug builds in a certain case: rdm was "stuck" ~100s when using a release build and ~270s when using a debug build.

[callgraph.pdf](https://github.com/Andersbakken/rtags/files/144707/callgraph.pdf)
