### ISSUE TITLE
rc -c should concat "compile commands", containing '\\\n' at the end

### ISSUE THREAD

**Issue by cslux** [Andersbakken/rtags#607]
Make allows you to use a \ to split long commands like shell does (escaping new line).

Consider this simple valid makefile
``` make
# Makefile ---
CC=$(shell which gcc)

all:
        $(CC) \
        main.c -o main
clean:
        rm -rf main
```
When executing e.g. `make -n | rc -c` rtags fails to parse the source file, a) because the first line doesn't contain the source file, and b) the second line of the compile command doesn't contain a valid compiler.
``` bash
Source::parse ( /usr/bin/gcc \
) => List<>(/usr/bin/gcc, \) /home/cschwarzgruber/Developing/Testing/c/
Source::parse No file for /usr/bin/gcc \

Source::parse (	test.c -o test
) => List<>(test.c, -o, test) /home/cschwarzgruber/Developing/Testing/c/
Source::parse Nothing looks like a compiler
```

I think rc should concat lines ending in \, and than pass the compile command to the parser. 

Christian

**Comment by Andersbakken** [comment]
Should be fixed now. Can you verify?

**Comment by cslux** [comment]
That works, thanks!

**Comment by Andersbakken** [comment]
Note that it had a bug. Should work again now for more than one compile :-)

**Comment by cslux** [comment]
I see,  did test it only for one compile command! Let's see if it works at work too. That's where I actually come across it. Report back in an hour!

**Comment by cslux** [comment]
I had no time to test it at work, but I have modified a make based project. I tried it with `rc -J`, and `rc -c` both time 15 units where parsed by rtags.

**Comment by Andersbakken** [comment]
Sounds good. Thanks
