### ISSUE TITLE
emacs freezes or tramp reconnects when visiting remote files

### ISSUE THREAD

**Issue by abred** [Andersbakken/rtags#608]
Hi,

I'm using
Emacs 24.5.1
rtags 3499b27ae24c

Steps to reproduce:
- clean emacs
- install rtags, add to load path, require 'rtags
- start emacs and open several remote files

What is supposed to happen (and does happen without rtags):
- tramp connects once and reuses this connection to open new files

What does happen:
- tramp reconnects for each file, so every time there is the initial connection overhead
- often (but not always) emacs freezes after opening the file
modeline says: Wrote /tmp/tramp....
It "Unfreezes" after pressing C-g three times or waiting for a minute or so

Message buffer output:
Tramp: Opening connection for erwin using ssh...
Tramp: Sending command `exec ssh   -o ControlMaster=auto -o ControlPath='tramp.%C' -o ControlPersist=no -e none erwin'
Tramp: Waiting for prompts from remote shell...done
Tramp: Found remote shell prompt on `erwin'
Tramp: Opening connection for erwin using ssh...done
Tramp: Inserting `/ssh:erwin:/home/user/.bashrc'...
Tramp: Encoding remote file `/ssh:erwin:/home/user/.bashrc' with `base64 <%s'...done
Tramp: Decoding local file `/tmp/tramp.32686eUF' with `base64-decode-region'...done
Tramp: Inserting `/ssh:erwin:/home/user/.bashrc'...done
Setting up indent for shell type zsh
Indentation variables are now local.
Indentation setup for shell type zsh

Tramp: Checking `vc-registered' for /ssh:erwin:/home/user/.bashrc...done
Indentation setup for shell type zsh
Tramp: Opening connection for erwin using ssh...
Tramp: Sending command `exec ssh -q   -o ControlMaster=auto -o ControlPath='tramp.%C' -o ControlPersist=no -e none erwin'
Tramp: Waiting for prompts from remote shell...done
Tramp: Found remote shell prompt on `erwin'
Wrote /tmp/tramp.32686reL
Error running timer `rtags-update-buffer-list': (file-error "Couldn't find exit status of `test -e /tmp/tramp.326864oR'")
Tramp: Opening connection for erwin using ssh...done

(Not sure if it's relevant (or supposed to be different), the "Wrote /tmp/tramp..." and the "running timer ... /tmp/tramp..." file have different names)

**Comment by juergenhoetzel** [comment]
I had the same issue:  `rtags` tries to invoke `rc` even though `rtags-tramp-enabled` is  `nil`

**Comment by abred** [comment]
that seems to fix it, thanks! :)
