### ISSUE TITLE
company-complete times out

### ISSUE THREAD

**Issue by ville-h** [Andersbakken/rtags#609]
I was trying to investigate why completions stopped working after recent pull I noticed that if I issue "company-complete" manually in: 
```
void funcion_with_long_name() {
}


int main() {
    func
    return 0;
}
```

with the point after "func" I get:
```
Making completion list...
Company: An error occurred in auto-begin
Company: backend company-rtags async timeout with args (candidates func)
```

in the \*Messages\* buffer and it fails to show any completions. Trying to let company trigger it automatially fails completely silently. I am currently at commit: 3499b27ae24cb23039840758676496a8e4e9d27c

**Comment by deuscovrigus** [comment]
I'm having the same issue on part of my project.

**Comment by ville-h** [comment]
I recall there was a company update in melpa recently, this could be the culprit as well. What company version do you have deuscovrigus? I've:
  company            20160211.520  installed             Modular text completion framework
I am also not sure how to downgrade a package with emacs package managing to test it out.

**Comment by deuscovrigus** [comment]
I actually use the git company bleeding edge. I'm at commit e251568e99de9e684b21cc74306fa1c3678444b5

**Comment by ville-h** [comment]
Apparently "rtags-completion-enabled" has recently changed to "rtags-completions-enabled". https://github.com/juergenhoetzel/rtags/commit/a0ebdc69c77cb4b28f52bb900d33b60d7e734986
```
(setq rtags-completions-enabled t)
```
fixes this issue.

**Comment by Andersbakken** [comment]
Ah. For the record it didn't really change. It was always rtags-completions-enabled but the documentation recently was updated to reflect this :-)
