### ISSUE TITLE
[help request] Completion api unerstanding

### ISSUE THREAD

**Issue by mkwork** [Andersbakken/rtags#615]
Hello.

What's wrong with [attached script](https://github.com/Andersbakken/rtags/files/140419/rtags-test-project.zip)? It shows too much results for point. Looks like, it shows results for empty context.

Is it wrong api usage or a bug?

**Comment by mkwork** [comment]
Wrong location was used

**Comment by Andersbakken** [comment]
Glad to hear. Let us know if you have more problems.

Anders
