### ISSUE TITLE
placement new completion failure

### ISSUE THREAD

**Issue by ville-h** [Andersbakken/rtags#616]
```
#include "cstddef"
#include "new"
#include "type_traits"


namespace nn {
    template<typename T, typename E>
    struct aa {
        aa(T const& x) {
            // new (&storage) T{x};
            new (&sto
        }


        static constexpr auto  alignment() -> std::size_t {
            return alignof(T) > alignof(E) ? alignof(T) : alignof(E);
        }


        static constexpr auto  size() -> std::size_t {
            return sizeof(T) > sizeof(E) ? sizeof(T) : sizeof(E);
        }


        std::aligned_storage_t<size(), alignment()> storage;
     };
}


auto main() -> int {
    nn::aa<int, int> x{0};
    return 0;
}
```

With point at "new (&sto" and executing `company-complete` it fills in "rage(), alignment()" where as i just expected it to fill in "rage" as the comment line above.

**Comment by Andersbakken** [comment]
I could have sworn I responded to this. Sorry about the delay. 

It definitely seems like a bug but the bug is in libclang itself. It might be good if we could cook up a standalone example using the clang executable to reproduce this and report it to the clang team.
