### ISSUE TITLE
Build failure on OS X 10.11 with 10.9 SDK

### ISSUE THREAD

**Issue by projedi** [Andersbakken/rtags#619]
This is similar to #572.

In https://github.com/Andersbakken/rtags/commit/5687de1d1c6d95a502988ad441fd82fb5e0f37ec#diff-daff29799219cc51ddbf311717e4250bR28 logic was introduced to use `launchd` on OS X 10.11 and up. But if you use 10.11 with 10.9 SDK then we will pass `#ifdef __MAC_10_11` test and still won't have `launch_activate_socket`. This is exactly the case when using Nix on OS X.

Probably it would be better to check the SDK version (if at all possible) and/or to add the `cmake` configuration flag to disable `launchd` integration altogether.

**Comment by Andersbakken** [comment]
We should probably do build test in cmake to check if the feature is
available. I'll look into adding something.

Anders

**Comment by Andersbakken** [comment]
I think it should be correct now. Can you verify?
