### ISSUE TITLE
emacs completions broken?

### ISSUE THREAD

**Issue by ville-h** [Andersbakken/rtags#620]
I am at c1a41507d9b25dcb1ad5d6f993f76421bc662381 and completions seem broken? Using following init.el:
```
    (require 'package)
    (package-initialize)
    (require 'rtags)
    (require 'company)

    (setq rtags-autostart-diagnostics t)
    (rtags-diagnostics)
    (setq rtags-completions-enabled t)
    (setq company-backends nil)
    (push 'company-rtags company-backends)
    (global-company-mode)
    (define-key c-mode-base-map (kbd "<C-tab>") (function company-complete))
```
The only difference to the minimal example in readme is the addition of `(setq company-backends nil)` to make sure other completion backend like dabbrev isn't offering the result.

**Comment by ville-h** [comment]
It appeats ae549603c6b3f4e4b7bc7161b476674243b5501e works fine.

**Comment by ville-h** [comment]
It would seem the problem is with how the melpa package is byte compiled perhaps. If I delete the *.elc files completions work. Any idea who packages rtags for melpa? During install of the melpa package there's lots of output in the byte compilation output.

**Comment by ville-h** [comment]
I can't reproduce this from a clean checkout and clean ~/.emacs so there are no .elc files. Classify as user error.

**Comment by Andersbakken** [comment]
Ok. Let me know if it shows up again.

Anders
