### ISSUE TITLE
rtags-find-symbol-at-point fails on macro used in macro definition

### ISSUE THREAD

**Issue by ville-h** [Andersbakken/rtags#621]
```
#define XXX 1
#define YYY XXX // rtags-find-symbol-at-point fails


auto main() -> int {
    YYY + 1;
    return 0;
}
```

point on "XXX" in "#define YYY XXX" rtags-find-symbol-at-point" fails to jump to the definition of XXX.

**Comment by cslux** [comment]
Right, I already came across that too, `rtags-find-symbol` works however.
