### ISSUE TITLE
Restore window configuration when closing *Rtags*

### ISSUE THREAD

**Issue by jockej** [Andersbakken/rtags#623]
Hi

When I quit the _Rtags_ buffer, the window configuration I had before doing C-c r . is not restored, instead  the window of _Rtags_ is deleted. I always use two side by side windows.

I would be nice if rtags could restore my window configuration when hiding _Rtags_.

**Comment by Andersbakken** [comment]
Sounds like a good idea.

**Comment by ZedThree** [comment]
I would really like to see this fixed. It's very painful having my window configuration broken. I think how magit does it, with a customisable variable, [`magit-bury-buffer-function`][1], that lets you choose how windows are buried/deleted would be the best way to do it.

I see @cslux has had a crack at it, but the commits don't appear to be on a branch, so I've not been able to have a play. 

[1]: https://github.com/magit/magit/blob/6e23f2de27a5de23ba36305c7f5e823db44541ec/lisp/magit-mode.el#L177

**Comment by Andersbakken** [comment]
I've added a defcustom for this. I suppose we really should take care of it
and make it the default behavior inside of RTags though. E.g. saving the
configuration to a file and restoring it etc.

I'll try to fix that too.

Anders
