### ISSUE TITLE
Disable bookmarking while using rtags helm and evil jump.

### ISSUE THREAD

**Issue by amosbird** [Andersbakken/rtags#624]
Is it possible to disable `Saving bookmarks to file xxx` while doing `rtags-find-references-at-point`? I use `rtags` together with `helm` and `evil`. It seems no need to have additional bookmarkings. When dealing with a large list of references, it is slow, even producing warnings. 

```
Warning (undo): Buffer `*Bookmark List*' undo info was 12207241 bytes long.
The undo info was discarded because it exceeded `undo-outer-limit'.

This is normal if you executed a command that made a huge change
to the buffer.  In that case, to prevent similar problems in the
future, set `undo-outer-limit' to a value that is large enough to
cover the maximum size of normal changes you expect a single
command to make, but not so large that it might exceed the
maximum memory allotted to Emacs.

If you did not execute any such command, the situation is
probably due to a bug and you should report it.

You can disable the popping up of this buffer by adding the entry
(undo discard-info) to the user option `warning-suppress-types',
which is defined in the `warnings' library.
```

I may be superficial though :-)

**Comment by amosbird** [comment]
After tons of bookmark savings, I get `File mode specification error: (error "Lisp nesting exceeds `max-lisp-eval-depth'") [2 times]`. Are they relevant?

**Comment by Andersbakken** [comment]
Hi Amos

The reason we use bookmarks for this is that they will store some
additional info and as such they will work even if the file gets modified
after they were made.

E.g.

int main()
{
     int a;


     ++a;
     ++a;
}

Imagine that you do rtags-find-references-at-point on the a

Then, you add a line after: int a;

E.g.

int main()
{
     int a;
     char foobar;


     ++a;
     ++a;
}

At this point the line/column combinations of the references are wrong but
the bookmarks will make sure that jumping to them still jumps to the right
place.

That being said I can provide an option to turn it off.

I'm not 100% sure those bookmarks are the issue though. We don't actually
save bookmarks to a file from emacs. Maybe something else in your setup
does that.

Anyway. You can now disable it by setting rtags-use-bookmarks to nil

Anders

**Comment by cslux** [comment]
Rtags only creates 100 bookmarks by default and can be adjusted with
rtags-max-bookmark-count you may set this to 0 for now..

I personally have not got the other error so far, even with 10000>
references and cycling through it.

Could you post the stack trace when this happens? Maybe some interferences
with helm your evil!

Christian

**Comment by amosbird** [comment]
Here is the stack strace :-)

```
  bookmark-write-file("/home/amos/.emacs.d/.cache/bookmarks")
  bookmark-save()
  bookmark-delete("RTags_236")
  #[(bookmark) "\301\302\"\205\n\303!\207" [bookmark string-match "^RTags_" bookmark-delete] 3]("RTags_236")
  mapcar(#[(bookmark) "\301\302\"\205\n\303!\207" [bookmark string-match "^RTags_" bookmark-delete] 3] ("RTags_325" "RTags_324" "RTags_323" "RTags_322" "RTags_321" "RTags_320" "RTags_319" "RTags_318" "RTags_317" "RTags_316" "RTags_315" "RTags_314" "RTags_313" "RTags_312" "RTags_311" "RTags_310" "RTags_309" "RTags_308" "RTags_307" "RTags_306" "RTags_305" "RTags_304" "RTags_303" "RTags_302" "RTags_301" "RTags_300" "RTags_299" "RTags_298" "RTags_297" "RTags_296" "RTags_295" "RTags_294" "RTags_293" "RTags_292" "RTags_291" "RTags_290" "RTags_289" "RTags_288" "RTags_287" "RTags_286" "RTags_285" "RTags_284" "RTags_283" "RTags_282" "RTags_281" "RTags_280" "RTags_279" "RTags_278" "RTags_277" "RTags_276" ...))
  rtags-reset-bookmarks()
  rtags-handle-results-buffer(nil nil "/home/amos/dsql/backend/chstor.h" nil)
  rtags-find-references-at-point(nil)
  call-interactively(rtags-find-references-at-point nil nil)
  command-execute(rtags-find-references-at-point)
```

**Comment by Andersbakken** [comment]
Ah. I think I see what might be going on. My guess is that your
bookmark-save-flag is set to something else than t.

Can you see if the commit I just pushed fixes this for you?

Anders
