### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by vardanian** [Andersbakken/rtags#628]
Scanning dependencies of target emacs_byte_compile_flycheck-rtags.el
[  4%] Copying /home/vram.vardanian/rtags/src/flycheck-rtags.el -> /home/vram.vardanian/rtags/build/src/flycheck-rtags.el
[  5%] Creating byte-compiled Emacs lisp /home/vram.vardanian/rtags/build/src/flycheck-rtags.elc
Loading /usr/share/emacs/site-lisp/site-start.d/focus-init.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/php-mode-init.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/po-mode-init.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/puppet-mode-init.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/rpm-spec-mode-init.el (source)...
Loading tramp...

In toplevel form:
flycheck-rtags.el:40:30:Error: Cannot open load file: pcase
make[2]: *** [src/flycheck-rtags.elc] Error 1
make[1]: *** [src/CMakeFiles/emacs_byte_compile_flycheck-rtags.el.dir/all] Error 2

**Comment by cslux** [comment]
I think I know whats wrong here... I'll assume your Emacs version is < 24. I need to add a conditional or so around this byte-compilation to exclude flycheck-rtags.el when the Emacs version is < 24.

**Comment by vardanian** [comment]
@cslux, you are right!
it is  23.1.1.

**Comment by cslux** [comment]
I'll fix it when I'm back home from work, 3 hours from now  :-)

**Comment by vardanian** [comment]
nice! :)

**Comment by cslux** [comment]
Hmm, turned out there is more stuff which isn't emacs 23 compatible. `flycheck-rtags.el` as well as `company-rtags.el` of course, but also some lisp code in `rtags.el`, like `setq-local` and `(kbd (concat prefix "."))` in `rtags-enable-standard-keybindings`, and probably more. Actually I don't know what emacs 23 had for local variable assignment, but for the `kbd` issue I might have a solution.
```
(if (< emacs-major-version 24)
    (defalias 'kbd 'read-kbd-macro))
```

@Andersbakken How should we proceed.

**Comment by cslux** [comment]
Aaahh, I may have found a solution. Report back after testing.

**Comment by cslux** [comment]
@vardanian I have tested it in Emacs 23 very superficial, jumping around works, but I haven't tested rtags-ac.el.

Let us know if something else doesn't work, thanks for the report!

regards,
Christian

**Comment by Andersbakken** [comment]
Is it completely right for rtags to map M-n and M-p though?

I personally have them mapped to something already and I kinda believe a
lot of people would have.

Otherwise it looks real good.

Anders

**Comment by cslux** [comment]
Well, I'm not 100 % sure... Ahrrg... I will change it back!

Christian
