### ISSUE TITLE
flycheck-rtags error: (invalid-function (or (\` "fixit") (\` "warning")))

### ISSUE THREAD

**Issue by ackalker** [Andersbakken/rtags#632]
Emacs 24.5.1, RTags built from Git, using `flycheck-rtags` with `flycheck`, checking a C file doesn't work for me, no errors are reported by the `rtags` checker.
When I toggle debug on error and do `M-x revert-buffer`, I get the following backtrace:

```elisp
Debugger entered--Lisp error: (invalid-function (or (\` "fixit") (\` "warning")))
  signal(invalid-function ((or (\` "fixit") (\` "warning"))))
  #[257 "\300 \210\301@A\"\207" [flycheck-report-failed-syntax-check signal] 4 "\n\n(fn ERR)"]((invalid-function (or (\` "fixit") (\` "warning"))))
  funcall(#[257 "\300 \210\301@A\"\207" [flycheck-report-failed-syntax-check signal] 4 "\n\n(fn ERR)"] (invalid-function (or (\` "fixit") (\` "warning"))))
  flycheck-buffer()
  #[0 "\300 \207" [flycheck-buffer] 1 "\n\n(fn)"]()
  funcall(#[0 "\300 \207" [flycheck-buffer] 1 "\n\n(fn)"])
  flycheck-buffer-automatically()
  flycheck-perform-deferred-syntax-check()
```

Looking into this, I found that Flycheck checking did work when I installed the elisp part of RTags from MELPA.
I think that I've found the cause: when RTags is built from Git, `compile-shim.elisp` defines `pcase` to be a function, when it actually is a macro. When I removed the lines referring to `pcase` from this file and rebuilt RTags, the error no longer occurs.

**Comment by Andersbakken** [comment]
That compile shim is pretty awful. Maybe we should have submodules for our
dependent elisp to keep make for elisp working.

Anders

**Comment by cslux** [comment]
I have mainly  added the pcase definition to the compile-shim.elisp to support Emacs 23. With Emacs 25.1.5 I do not get any errors, even though pcase is a macro, interesting. 

@Andersbakken Do you mean git submodules?

**Comment by Andersbakken** [comment]
Yeah. I think that might be better tbh. We already require rct as a
submodule so even if we don't keep our elisp dependencies entirely
up-to-date at least we won't have these kinds of problems anymore.

I think I'll try to add it.

Anders

**Comment by Andersbakken** [comment]
Hm. I really am not a huge fan of the idea after all. I took a quick look
at magit.el's build system and basically can't understand how it works. It
does very much rely on thirdparty elisp however so maybe we should
investigate what other packages like it does this.

Anders

**Comment by ackalker** [comment]
Maybe have a look at [irony-mode](https://github.com/Sarcasm/irony-mode). It's server part builds using CMake, the elisp part provides a command for the user to build and install the server. The server is placed in `~/.emacs.d/irony/bin/irony-server`.

**Comment by Andersbakken** [comment]
Yeah. I like their approach and have been meaning to get something like
that in for a while.

Anders
