### ISSUE TITLE
Improve man pages

### ISSUE THREAD

**Issue by cslux** [Andersbakken/rtags#635]
#634

**Comment by cslux** [comment]
Figure out a good way to automate the generation of the man pages.

**Comment by marxin** [comment]
+1

I've just noticed that man pages are out of date. Can you please add:
help2man --no-info -s 7 ./bin/rc -o man/man7/rc.7
help2man --no-info -s 7 ./bin/rdm -o man/man7/rdm.7

to 'make man' for instance? I'm not familiar with CMake to do so.
I've also noticed that using the help2man, we loose SYNOPSIS section for rdm.

**Comment by cslux** [comment]
#921

**Comment by cslux** [comment]
486316ddc111472f24ec621038bd7d589dca61f4 fixes partly this issue. The script still needs to be executed manually, as I don't want to force a dependency. Although, we could add a developer cmake flag, when set to true it will also update the man pages when rc and rdm executable get updated. Nevertheless, I will close this issue now.
