### ISSUE TITLE
Something wrong with multibyte buffers

### ISSUE THREAD

**Issue by mdraven** [Andersbakken/rtags#639]
When a buffer contains multibyte characters, rtags incorrect highlights text's sections.

`rtags-skippedline` is displaced:
![bug](https://cloud.githubusercontent.com/assets/916211/13929841/5ff21f6e-efc6-11e5-831e-8f49a4aac47d.png)

Without multibyte characters is all right:
![no-bug](https://cloud.githubusercontent.com/assets/916211/13929843/63f30a7e-efc6-11e5-8904-1bc5e5998f62.png)

Bug doesn't affect code completion. `company-mode` works with unibyte or multibyte encoding.

Now I am using primitive hack: ```(defun rtags-buffer-is-multibyte () nil)```.

Maybe the problem in `startoffset` in [rtags.el#L2452](https://github.com/Andersbakken/rtags/blob/master/src/rtags.el#L2452)? I think `make-overlay` expects `(point)` and not byte-offset.

**Comment by Andersbakken** [comment]
I think it should be fixed now. Can you check?

**Comment by mdraven** [comment]
It works great! Thank you.
