### ISSUE TITLE
find-references-at-point in helm mode removes windows

### ISSUE THREAD

**Issue by petercheng00** [Andersbakken/rtags#646]
Say I have 2 windows side by side. If I call find-references-at-point, I get references in the helm buffer.
As soon as a I select an entry, not only does the helm buffer disappear, but one of my original 2 windows goes away as well. Same is true for 3 windows to 2, etc.

Also, in addition to not removing my windows, it would be nice if behavior could match the non-helm version, and have the results window could stay open so I can jump to each returned result in turn.

**Comment by mikeandmore** [comment]
I have similar issue. I created a pull request #684 .

**Comment by cslux** [comment]
Hey @petercheng00 should be fixed now, if a call `rtags-next-match`, which I have bind to `M-n'  rtags jumps to the next match even when the helm buffer closes after the first selection. Tip, you can press tab when the helm buffer is open to jump to the location, the helm buffer stays than open.


@mikeandmore Thanks for the fix.
