### ISSUE TITLE
C++ code in .c file results in wrong tags

### ISSUE THREAD

**Issue by ienkovich** [Andersbakken/rtags#652]
When I have C++ code in .c file and compile it using g++ I get incorrect tags for it and many false syntax 'errors' are highlighted by flycheck.  Is there any way to treat c file as cpp?

**Comment by Andersbakken** [comment]
Ah. I see.

If you're able to modify the compile arguments you could add:

 -x c++

e.g.

g++ -x c++ foo.c

It should treat it as c++. Does that work for you?

Anders

**Comment by ienkovich** [comment]
Unfortunately in my build system CXXFLAGS are also passed when link and '-x c++' breaks linkage.  I use gcc-rtags-wrapper and this change seems to help me.

+                g++)
+                   cc=g++
+                    flags="-x c++"
+                    ;;


Thanks for help!
