### ISSUE TITLE
Autocomplete with expand arguments in snippet

### ISSUE THREAD

**Issue by kvaneesh** [Andersbakken/rtags#654]
I am writing this to check whether we support argument expansion while autocomplete ?. Something similar to http://emacs.stackexchange.com/questions/9526/extending-autocomplete-for-go-to-insert-function-arguments

**Comment by mkwork** [comment]
Imho, such feature requires to sent full set of completion model, just like [tokens](http://clang.llvm.org/doxygen/group__CINDEX__CODE__COMPLET.html#ga82570056548565efdd6fc74e57e75bbd) to client side.

So, if I can ask for some additional requirements for such interfaces changes:
Please implement such kind of output interfaces changes in [json](http://www.json.org/) format, while it's needed to implement good enough plugin implementation in [vim-rtags](https://github.com/lyuts/vim-rtags) to compete with [ycm's](https://github.com/Valloric/YouCompleteMe) c++ semantic completion implementation. 

As reference implementation of completion string mapping in format like json model, you can use such python [bindings](https://github.com/llvm-mirror/clang/tree/master/bindings/python). Their completion string mappings have rest of detail which are enough for the most full completion implementation on the client side.

**Comment by kvaneesh** [comment]
https://code.visualstudio.com/blogs/2016/06/27/common-language-protocol
This looks interesting. If we get an emacs implementation then we could possible make the language server available to other editors too.

**Comment by Andersbakken** [comment]
Incidentally. This is now implemented. There might be bugs but you can now
do something like this:

rc --code-complete-at /Users/abakken/dev/rtags/src/rdm.cpp:50:1:
--synchronous-completions --json

Note that I suspect there's too much info there for it to be performant. I
think the ideal solution maybe filters out something on the server side.

Anders

**Comment by kvaneesh** [comment]
Is the emacs part of this done ? I guess company mode integration will also need an update to show the details ?

**Comment by Andersbakken** [comment]
Not really. I don't entirely know what one would need to do to implement it
at this point.

Anders

On Fri, Aug 26, 2016 at 10:24 AM, Aneesh Kumar K.V <notifications@github.com

**Comment by kvaneesh** [comment]
https://github.com/company-mode/company-mode/blob/master/company-gtags.el that indicate that we can insert argument template if the company backend support it when building completions. I am not expert in elisp to code that. But i noticed that even rc --code-complete-at --elisp returns the argument details. So we may be able to skip the all the json part and just get the arguments in completion with simple hack ?

**Comment by Andersbakken** [comment]
Hm. You know what. We already do this apparently. I think Philippe Vaucher
added this in his initial company contribution. My bad.

Anders

**Comment by cslux** [comment]
I think we can close this.
