### ISSUE TITLE
It would be cool to expose the AST to a scripting language to be able to write little tools for analysis and refactoring

### ISSUE THREAD

**Issue by Andersbakken** [Andersbakken/rtags#657]
For example Javascript

**Comment by kvaneesh** [comment]
An example of what can be achieved will be nice.

**Comment by Andersbakken** [comment]
I'll see if I could write up something. I kinda implemented it (mostly
finished) so I suppose I should write an example showing something that can
be done with it.

Anders

On Fri, Aug 26, 2016 at 10:23 AM, Aneesh Kumar K.V <notifications@github.com
