### ISSUE TITLE
With Clang 3.8 on Ubuntu 14.04 rtags returns no completions on e.g. QVector<QString>

### ISSUE THREAD

**Issue by cpbotha** [Andersbakken/rtags#659]
I am really loving rtags, thank you for making this! (I also wrote this blog post to help others on their way: https://vxlabs.com/2016/04/11/step-by-step-guide-to-c-navigation-and-completion-with-emacs-and-the-clang-based-rtags/ )

As mentioned in that blog post, I'm working on a Qt project of just under 200K lines. With Clang 3.6, everything works really well. With Clang 3.8 (installed from the LLVM repos) however, completion on Qt class instances such as a QVector<QString> or a QHash<QString, QPair ...> returns "no completions". Everything else works: Even rtags-find-symbol on such a QHash or QVector will jump to the right place in the Qt headers.

I'm mentioning this issue in case this rings any bells for anyone. I hope to make some more time at some point to make a minimal C++ reproducer that I can share here.

**Comment by cslux** [comment]
I just tried it with a self compiled 3.8 LLVM/Clang on Fedora and indeed you get no completion for QT types like QString, QVector, etc.. However,  `rc -m --elisp` shows that the completion list contains QString, QVector, etc. and inside emacs you get a async timeout from company. Not entirely sure how to triage this problem, any thoughts @Andersbakken.

@cpbotha First, sorry for the late reply, I'm sure we will soon fix this! Secondly, I read your blog post and saw the following line in your rtags setup `(add-hook 'c-mode-common-hook #'setup-flycheck-rtags))`, which is not correct anymore. We removed this function, only `(require 'flycheck-rtags` is required, though we suggest customizing Flycheck a bit, see https://github.com/Andersbakken/rtags#optional-1

regards,
Christian

**Comment by Andersbakken** [comment]
I think the main problem is that it just takes too long to generate. Let me
look into it some more.

Anders

**Comment by Andersbakken** [comment]
Btw. Can you try to call rc --dump-completions and paste the output after
having the timeout happen?

Anders

**Comment by cslux** [comment]
Sure!

**Comment by cslux** [comment]
Hmm, I don't know but somehow it does work now :-/, strange.  ![rtags-complete-qt-types](https://cloud.githubusercontent.com/assets/1712313/15683230/9195c8ea-2761-11e6-9d2a-c30e5f9106b0.png). 

![rtags-complete-qt-types1](https://cloud.githubusercontent.com/assets/1712313/15683388/5ff7a1a4-2762-11e6-8035-3c77de1e2594.png)

All I did was:
- Rebuild RTags with LLVM/Clang 3.8
- Deleted indexed QT based project
- Indexed QT based project

Anyway, here is the output of `rc --socket-file ~/.rdm_tmp --dump-completions | grep -E "Q(Vec|Str)"`:
```
        "append" +void append(const QVector<QString> &l)" 34 -1 CXXMethod
        "append" +void append(QString &&t)" 34 -1 CXXMethod
        "append" +void append(const QString &t)" 34 -1 CXXMethod
        "copyConstruct" +void copyConstruct(const QString *srcFrom, const QString *srcTo, QString *dstFrom)" 34 -1 CXXMethod
        "data" +QString * data()" 34 -1 CXXMethod
        "defaultConstruct" +void defaultConstruct(QString *from, QString *to)" 34 -1 CXXMethod
        "destruct" +void destruct(QString *from, QString *to)" 34 -1 CXXMethod
        "fill" +QVector<QString> & fill(const QString &t)" 34 -1 CXXMethod
        "first" +QString & first()" 34 -1 CXXMethod
        "front" +QString & front()" 34 -1 CXXMethod
        "insert" +iterator insert(iterator before, const QString &x)" 34 -1 CXXMethod
        "insert" +void insert(int i, const QString &t)" 34 -1 CXXMethod
        "insert" +void insert(int i, int n, const QString &t)" 34 -1 CXXMethod
        "insert" +iterator insert(iterator before, int n, const QString &x)" 34 -1 CXXMethod
        "last" +QString & last()" 34 -1 CXXMethod
        "prepend" +void prepend(const QString &t)" 34 -1 CXXMethod
        "push_back" +void push_back(const QString &t)" 34 -1 CXXMethod
        "push_back" +void push_back(QString &&t)" 34 -1 CXXMethod
        "push_front" +void push_front(const QString &t)" 34 -1 CXXMethod
        "removeAll" +int removeAll(const QString &t)" 34 -1 CXXMethod
        "removeOne" +bool removeOne(const QString &t)" 34 -1 CXXMethod
        "replace" +void replace(int i, const QString &t)" 34 -1 CXXMethod
        "swap" +void swap(QVector<QString> &other)" 34 -1 CXXMethod
        "takeAt" +QString takeAt(int i)" 34 -1 CXXMethod
        "takeFirst" +QString takeFirst()" 34 -1 CXXMethod
        "takeLast" +QString takeLast()" 34 -1 CXXMethod
        "at" +const QString & at(int i) const" 35 -1 CXXMethod
        "constData" +const QString * constData() const" 35 -1 CXXMethod
        "constFirst" +const QString & constFirst() const" 35 -1 CXXMethod
        "constLast" +const QString & constLast() const" 35 -1 CXXMethod
        "contains" +bool contains(const QString &t) const" 35 -1 CXXMethod
        "count" +int count(const QString &t) const" 35 -1 CXXMethod
        "data" +const QString * data() const" 35 -1 CXXMethod
        "endsWith" +bool endsWith(const QString &t) const" 35 -1 CXXMethod
        "first" +const QString & first() const" 35 -1 CXXMethod
        "fromList" +QVector<QString> fromList(const QList<QString> &list)" 35 -1 CXXMethod
        "fromStdVector" +QVector<QString> fromStdVector(const std::vector<QString> &vector)" 35 -1 CXXMethod
        "indexOf" +int indexOf(const QString &t) const" 35 -1 CXXMethod
        "isSharedWith" +bool isSharedWith(const QVector<QString> &other) const" 35 -1 CXXMethod
        "last" +const QString & last() const" 35 -1 CXXMethod
        "lastIndexOf" +int lastIndexOf(const QString &t) const" 35 -1 CXXMethod
        "mid" +QVector<QString> mid(int pos) const" 35 -1 CXXMethod
        "startsWith" +bool startsWith(const QString &t) const" 35 -1 CXXMethod
        "toList" +QList<QString> toList() const" 35 -1 CXXMethod
        "toStdVector" +std::vector<QString> toStdVector() const" 35 -1 CXXMethod
        "value" +QString value(int i, const QString &defaultValue) const" 35 -1 CXXMethod
        "value" +QString value(int i) const" 35 -1 CXXMethod
        "QVector" +QVector::" 75 -1 ClassDecl 
```

**Comment by Andersbakken** [comment]
Hm. Maybe the async timeout thing can be modified. I suspect that it
succeeds with enough time.

Anders

**Comment by cpbotha** [comment]
@Andersbakken I double-checked your linked  documentation https://github.com/Andersbakken/rtags#optional-1 -- this is exactly what I have in my blog post.

(I even copy-pasted your code into my org-mode blog source to double-check. Am I missing something?)

I'm going to try and reproduce the bug described in this issue with latest rtags and clang 3.8 again.

**Comment by cslux** [comment]
> @Andersbakken I double-checked your linked documentation https://github.com/Andersbakken/rtags#optional-1 -- this is exactly what I have in my blog post.
> 
> (I even copy-pasted your code into my org-mode blog source to double-check. Am I missing something?)

Ooops, you have this function at the top, I just saw the hook at the bottom calling `setup-flycheck-rtags`, I initially added a function in `flycheck-rtags` with the same name (almost the same, `flycheck-rtags-setup`) but removed it. Sorry, for the noise.

regards,
Christian

**Comment by Andersbakken** [comment]
I did add something that might make this issue less likely. In short, I
will try to warm up the completion cache as soon as you make the buffer
active and that might make it more likely to finish in a reasonable time
frame.

Anders
