### ISSUE TITLE
Hovering in compile buffer opens file

### ISSUE THREAD

**Issue by floli** [Andersbakken/rtags#660]
Hello,

when I hover about a line like

```In file included from src/mapping/config/MappingConfiguration.cpp:5:``` in the compile buffer, Emacs opens an unrelated file and buries the buffer when moving away from the line.

rc --verbose prints that line:
```
/usr/sbin/rc --current-file=/home/florian/precice/src/mapping/PetRadialBasisFctMapping.hpp --no-color --declaration-only -N -f /home/florian/precice/src/mapping/PetRadialBasisFctMapping.hpp:160:42: -K
=> /home/florian/precice/src/mapping/PetRadialBasisFctMapping.hpp:156:18:
Query opened 5354 files for project /home/florian/precice/
/usr/sbin/rc --current-file=/home/florian/precice/src/mapping/PetRadialBasisFctMapping.hpp --no-color -U /home/florian/precice/src/mapping/PetRadialBasisFctMapping.hpp:156:18: -K --symbol-info-exclude-targets --symbol-info-exclude-references
=> /home/florian/precice/src/mapping/PetRadialBasisFctMapping.hpp:156:18:         PetscErrorCode ierr = 0;
=> SymbolName: PetscErrorCode ierr
Kind: VarDecl
Type: PetscErrorCode
SymbolLength: 4
Range: 156:3-156:26
Linkage: No Linkage
Definition
Usr: c:PetRadialBasisFctMapping.hpp@4569@N@precice@N@mapping@ST>1#T@PetRadialBasisFctMapping@F@~PetRadialBasisFctMapping<RADIAL_BASIS_FUNCTION_T>#@ierr
sizeof: 4
alignment (bytes): 4

Query opened 1 files for project /home/florian/precice/
```
It seems to happen only when the compilation buffer is not active, otherwise rtags is not triggered.
I don't really know whats happening, but as a result I have quite a few unwanted buffers created.

Can I disable rtags inside a compilation buffer?

Thanks!

**Comment by Andersbakken** [comment]
Sorry about the delay. I'll try to take a look at this shortly.

Anders

**Comment by Andersbakken** [comment]
I don't entirely understand how to reproduce this. Any chance you could
record a video of it or possibly writing some more detailed steps?

Anders

**Comment by floli** [comment]
Actually right now I'm not able to reproduce that. Sorry, I'll close it.

**Comment by Andersbakken** [comment]
Ah. Please reopen if you find a way to make it happen again.

Anders
