### ISSUE TITLE
Cygwin compilation fails

### ISSUE THREAD

**Issue by graywolf** [Andersbakken/rtags#663]
Cannot compile under cygwin, execinfo.h isn't available on Cygwin. Could this possible be somehow `ifdef`ed around it?

Responsible commit is 2b3d4211966b26c39dc38c5ee7e13086034050c1, so maybe just disable crashdump creation on cygwin?

**Comment by Andersbakken** [comment]
Thanks for the report. It should be fixed now. Can you re-open if this doesn't fix it?
