### ISSUE TITLE
rc -J invalid option

### ISSUE THREAD

**Issue by snandan** [Andersbakken/rtags#665]
According to the README, I tried to compile the project by using the following command:

`$ bin/rc -J .`

However I got error saying:
```
bin/rc: invalid option -- J
bin/rc option...
```

And rest of the help is displayed. Is there anything I am doing wrong? I am using v2.2

Thanks,
Suman.

**Comment by Andersbakken** [comment]
Hi

My guess is that your clang is rather old. We use a clang API to load these
files and that API showed up in clang 3.4.

Anders
