### ISSUE TITLE
Everything is reindexed when compile_commands.json is touched

### ISSUE THREAD

**Issue by petersohn** [Andersbakken/rtags#670]
When `compile_commands.json` is touched, everything is reindexed even if the content of the file does not change at all. The whole index is also cleared, so if I try a lookup on a file that is not yet reindexed, then `rc` says that it is not indexed.

If my build system automatically generates `compile_commands.json`, that means that I have a significant downtime after every build, especially for large projects.

**Comment by cslux** [comment]
Is rtags up to date? 

If  I do `touch compile_commands.json` on the rtags `compile_commands.json` file nothing gets re-indexed, even when I re-run cmake to generate the compile_commands.json again.

What build system do you use to generate the `compile_commands.json` file?

regards,
Christian

**Comment by petersohn** [comment]
I use b46fcda98ee0fd7da894445eeadc336bb4697fbe. I have compilation problems since Lua was introduced, so I didn't try to upgrade since then.

**Comment by petersohn** [comment]
I updated to the latest master, and the problem seems to be solved.

**Comment by Andersbakken** [comment]
Hi Peter

It's not really supposed to.

You may get some usable output to determine why it happened if you run rdm
with -v -v -v

You should pipe the output somewhere. There's tons of it.

Anders
