### ISSUE TITLE
cmake fails to find Lua when it is installed in /usr/local

### ISSUE THREAD

**Issue by petersohn** [Andersbakken/rtags#671]
I have Ubuntu 14.04 which only has Lua 5.1. So I installed Lua from source into `/usr/local`. If I run `cmake` it says that Lua is not found.

**Comment by cslux** [comment]
You could set the LUA variables by hand, if the cmake find module was not able to find lua.
``` bash
LUA_INCLUDE_DIR
LUA_LIBRARY
# Example
cmake -DLUA_INCLUDE_DIR=/usr/local/include -DLUA_LIBRARY=/usr/local/lib/liblua-5.3.0.so ....
```

I will test this at home as well, and update the README.

Thanks for the report!

regards,
Christian

**Comment by petersohn** [comment]
Umm. It seems that I don't have `liblua.so`, only `liblua.a`. Maybe it's the problem? Is it possible to tell cmake that it should link Lua statically?

**Comment by cslux** [comment]
Ahh right I remember! By default lua's build system do not generate a shared library, needs to be patched. 

> Maybe it's the problem?

That could definitely be the case, by default FindLua.cmake searches in `/usr/local` anyway but only searches for `.so`

> Is it possible to tell cmake that it should link Lua statically?

Not quite sure, so you could try to set `CMAKE_FIND_LIBRARY_SUFFIXES` to `".a;.so"` before `find_package(Lua ...)`

``` cmake
set(CMAKE_FIND_LIBRARY_SUFFIXES ".a;.so")
set(LUA_VERSION_STRING "5.3.0")
find_package(Lua 5.3)
set(CMAKE_FIND_LIBRARY_SUFFIXES ".so")
```

But that would just be a sloppy hack anyway, so no solution we can use. I think it's best to provide I guide on how to patch a and build lua from scratch, or something like that.

**Comment by cslux** [comment]
@petersohn I took a look at the RPM Lua package on Fedora, it got patched quite a bit, and other distributions likely did the same. Anyway, you may follow this [instruction](http://www.linuxfromscratch.org/blfs/view/svn/general/lua.html) from the [Linux From Scratch](http://www.linuxfromscratch.org) homepage, it looks quite promising. A link to a patch is provided to create, and install shared lua libraries, as well as a comprehensive instruction to build Lua.

regards,
Christian

**Comment by Andersbakken** [comment]
I don't entirely see why we can't link against a static lua TBH.

Anders

**Comment by cslux** [comment]
> I don't entirely see why we can't link against a static lua TBH.

Right, tested it my self and it works of course :-)

@petersohn Here is a short list of commands to compile rtags with a lua static library installed to a different place.

If you are a mac user you need to replace `make linux` with `make macosx`.

``` bash
mkdir -p ~/Developing/third_party
cd Developing
wget https://www.lua.org/ftp/lua-5.3.2.tar.gz
tar xf lua-5.3.2.tar.gz
cd lua-5.3.2.tar.gz
make linux 
sudo make install INSTALL_TOP=/usr/local
cd ~/Developing/third_party/rtags/build
cmake -DLUA_INCLUDE_DIR=/usr/local/include/ -DLUA_LIBRARY=/usr/local/lib/liblua.a ../
```

regards,
Christian

**Comment by cslux** [comment]
Will add a some nodes to the readme, closing this now.
