### ISSUE TITLE
how default include paths are treated?

### ISSUE THREAD

**Issue by autosquid** [Andersbakken/rtags#672]
Hi, 

I found I have to point out default include paths explicitly for rdm to run correctly, or it will not find headers such as `<string>` or `<vector>`.

I checked the `compile_commands.jsoncompile_commands.json` where these default headers are not included.

For me, with `clang`, after adding the following stuff,  things begin to work:

> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1
>  /usr/local/include
>  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0/include
>  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
>  /usr/include
>  /System/Library/Frameworks (framework directory)
>  /Library/Frameworks (framework directory)

I am writing to query if this is the default/designed behavior?  or am I messing anything up?

**Comment by Andersbakken** [comment]
Which libclang are you linking against?

I'm usually installing it from homebrew. Strictly speaking the expectation
is that libclang itself will know where to go for default paths. I suspect
that you're using the one from XCode and I kinda believe we've had some
issues with it in the past (not supporting c++11 or something like that).

Anders

**Comment by dgel** [comment]
I have the same issue as autosquid, but I'm pretty sure I'm linking against libclang installed from brew. It's installed in lib under /usr/local/opt/llvm/, which is where my other custom llvm programs reside.. Is there any way I can add global include directives for rdm?

**Comment by autosquid** [comment]
@Andersbakken 
Thanks for your reply!

I re-checked my installation of llvm, finding that I missed the `--libcxx` option. After a reinstallation of llvm, things seem to work! (Is this why things begin to work?

As to libclang, I am not sure which one I linked to. the output of  `otool -L mylib.dylib`, tells no word about "libclang".

**Comment by Andersbakken** [comment]
That is likely the reason it started working I think. Did you try otool -L
rdm?

It might be linked statically (in which case you'd have to inspect the link
line to figure out where it found the .a).

Anders

**Comment by autosquid** [comment]
I tried ` try otool -L rdm`, and it links to libclang I installed from homebrew.

**Comment by autosquid** [comment]
P.S. why adding the headers would solve my previous problems? does it mean it would work the same with clang from xcode?

**Comment by Andersbakken** [comment]
Sorry about the delay. There are some weird heuristics at play regarding how to find the required system headers for clang. By default it should know where they are but I think the one that comes with xcode has them installed in a different location or something to that effect.
