### ISSUE TITLE
company-c-headers integration

### ISSUE THREAD

**Issue by baol** [Andersbakken/rtags#675]
Hi,
I'm using rdm on a daily basis and would enjoy a feature that is (AFAIK) missing, header autocompletion. I know that one could use rtags-get-include-for-symbol, but this would be a nice addition to that functionality.

What I mean is that if the https://github.com/randomphrase/company-c-headers package is installed, rdm could populate the company-c-headers-path-system and company-c-headers-path-user automatically, based on the file compilation options. 

Thanks!

**Comment by baol** [comment]
(closed by mistake)

**Comment by cslux** [comment]
@baol It doesn't sound like a bad idea, I personally would add a second back-end to the existing `company-rtags.el` file or create a new `el` file company-rtags-headers.el. We could dabble in [company-irony-c-headers.el](https://github.com/hotpxl/company-irony-c-headers/blob/master/company-irony-c-headers.el), and see how he did it. Or we add just something to `company-rtags.el`, to include the headers in the result when we are inside `"|"` or `<|>` (| is the cursor), and the line starts with `#include`.  


> What I mean is that if the https://github.com/randomphrase/company-c-headers package is installed, rdm could populate the company-c-headers-path-system and company-c-headers-path-user automatically, based on the file compilation options.

I don't think we have to depend on `company-c-headers.el` to accomplish this, `RTags` can figure the system include paths out as well, secondly `company-c-headers.el` is very small, it's not worth the hassle :-).

Let's see what @Andersbakken says.

regards,
Christian

**Comment by Andersbakken** [comment]
Sounds like a good idea to me. I suppose we'd identify the context
(completing on headers or not) in elisp and call different APIs. I think we
could achieve that relatively easily.

I added something for it. Can you see if it works for you? It's tied to the
company-rtags backend should ideally just start working if you pull and
rebuild.

Anders

**Comment by cslux** [comment]
First of all, very well done, you are so fast :-O. However, not all includes are shown, for instance, consider this includes in a header file.
``` c
#include "sandbox/linux/system_headers/linux_futex.h"
#include "sandbox/linux/system_headers/linux_syscalls.h"
#include "sandbox/linux/system_headers/linux_time.h"
#include "base/allocator/allocator_check.h"
```
Now I would expect to get candidates for `sandbox/linux/....` but instead I only get candidates for `sandbox/mac/...`.

The other thing has been fixed by me https://github.com/Andersbakken/rtags/commit/f08bec7ef74742233aeb7e135f55ff2facc25c0d

Christian

**Comment by baol** [comment]
Wow,
super fast :)

I found another small issue, after the dot in the filename, the completion fails.

mirko

**Comment by Andersbakken** [comment]
Ah right. Thanks. Fixed the dot issue. Thanks.

Anders

**Comment by Andersbakken** [comment]
@Christian

I'm slightly confused about the files in your example. where is sandbox/max
in the file structure?

I had a max recurse depth of only 2 which might be too little. I increased
it to 3 and made it configurable

  --max-include-completion-depth [arg]       Max recursion depth for header
completion (default 3).

Does that help?

Anders

**Comment by cslux** [comment]
@Andersbakken You mean the general file structure, it can go far more than 3 (13 or so is max depth) in depth, but as it is now customizable I can adjust it to my needs.

Coming back to your question, you can have a look at the file structure online [https://code.google.com/p/chromium/codesearch#chromium/src/sandbox/&q=sandbox&sq=package:chromium](https://code.google.com/p/chromium/codesearch#chromium/src/sandbox/&q=sandbox&sq=package:chromium)

I also have noticed that in c++ `<vector>, <string>` and the like are not candidates for header includes.

**Comment by Andersbakken** [comment]
Interesting. Let me take a look.

Anders
