### ISSUE TITLE
File not properly indexed (Kind: InvalidFile SymbolLength: 0)

### ISSUE THREAD

**Issue by flv0** [Andersbakken/rtags#678]
I'm having a problem with rtags indexing files from a library I'm working with. I don't know if that might be a reason for it, but the one I'm just now having problems with is actually a .cpp file included in another .cpp file, for reasons how that library is built.

Rtags is missing the symbols from within juce_TabbedButtonBar.cpp. --dump-file-maps gives me the following for that file:
```
ceephax:~/development/ircam/ILF/Tests/ilfTestApplication/Builds/LinuxMakefile% rc --dump-file-maps /data/anasynth/schmitz/development/ircam/juce-glbinding/modules/juce_gui_basics/layout/juce_TabbedButtonBar.cpp
Symbols:
--------
| /data/anasynth/schmitz/development/ircam/juce-glbinding/modules/juce_gui_basics/layout/juce_TabbedButtonBar.cpp:1:1:   | Symbol(SymbolName:  Kind: InvalidFile SymbolLength: 0 )                                                   |
| /data/anasynth/schmitz/development/ircam/juce-glbinding/modules/juce_gui_basics/layout/juce_TabbedButtonBar.cpp:141:5: | Symbol(SymbolName: jassert Kind: macro expansion SymbolLength: 7 Range: 141:5-141:82 )                    |
| /data/anasynth/schmitz/development/ircam/juce-glbinding/modules/juce_gui_basics/layout/juce_TabbedButtonBar.cpp:196:5: | Symbol(SymbolName: JUCE_DECLARE_NON_COPYABLE Kind: macro expansion SymbolLength: 25 Range: 196:5-196:51 ) |
| /data/anasynth/schmitz/development/ircam/juce-glbinding/modules/juce_gui_basics/layout/juce_TabbedButtonBar.cpp:251:5: | Symbol(SymbolName: jassert Kind: macro expansion SymbolLength: 7 Range: 251:5-251:35 )                    |
| /data/anasynth/schmitz/development/ircam/juce-glbinding/modules/juce_gui_basics/layout/juce_TabbedButtonBar.cpp:264:9: | Symbol(SymbolName: jassert Kind: macro expansion SymbolLength: 7 Range: 264:9-264:44 )                    |
Symbol names:
-------------
| /data/anasynth/schmitz/development/ircam/juce-glbinding/modules/juce_gui_basics/layout/juce_TabbedButtonBar.cpp | /data/anasynth/schmitz/development/ircam/juce-glbinding/modules/juce_gui_basics/layout/juce_TabbedButtonBar.cpp:1:1: |
| juce_TabbedButtonBar.cpp                                                                                        | /data/anasynth/schmitz/development/ircam/juce-glbinding/modules/juce_gui_basics/layout/juce_TabbedButtonBar.cpp:1:1: |
Targets:
--------
| c:juce_PlatformDefs.h@5693@macro@jassert                   | /data/anasynth/schmitz/development/ircam/juce-glbinding/modules/juce_gui_basics/layout/juce_TabbedButtonBar.cpp:141:5:,                                                        |
*                                                            *  /data/anasynth/schmitz/development/ircam/juce-glbinding/modules/juce_gui_basics/layout/juce_TabbedButtonBar.cpp:251:5:,                                                       *
*                                                            *  /data/anasynth/schmitz/development/ircam/juce-glbinding/modules/juce_gui_basics/layout/juce_TabbedButtonBar.cpp:264:9:                                                        *
| c:juce_PlatformDefs.h@8533@macro@JUCE_DECLARE_NON_COPYABLE | /data/anasynth/schmitz/development/ircam/juce-glbinding/modules/juce_gui_basics/layout/juce_TabbedButtonBar.cpp:196:5:                                                         |
Usrs:
-----
```

Where the first line (Kind: InvalidFile SymbolLength: 0) seems to be problematic.

In case it helps spotting a problem, here is the actual file:
https://github.com/flv0/juce-glbinding/blob/4.2-glbinding/modules/juce_gui_basics/layout/juce_TabbedButtonBar.cpp

However I can't spot anything special about it. How would I go about further troubleshooting this?

Thanks!

**Comment by Andersbakken** [comment]
Hi

The invalidfile one is actually not a problem. We synthesize cursor at
location 1:1: of every included file to be able to jump to it.

What does rdm say when it indexes the file?

E.g. if you touch it, what's the output from rdm?

regards

Anders

**Comment by flv0** [comment]
[100%] 1/1 11:55:31 /data/anasynth/schmitz/development/ircam/ILF/Tests/ilfTestApplication/JuceLibraryCode/juce_gui_basics.cpp in 1949ms. (8 syms, 8 symNames, 2 includes, 2 of 692 files, symbols: 6 of 22740, 23083 cursors, 1 queried 0ms) (1767/178/2ms) (dirty). (priority 1)

**Comment by Andersbakken** [comment]
Hm. That looks strictly speaking right. Is this file being included from
different files by any chance?

E.g.

a.cpp

#include <juce_TabbedButtonBar.cpp>

b.cpp:

#include <juce_TabbedButtonBar.cpp>

I don't suppose this is opensource so I could build it myself and take a
look?

Anders

**Comment by flv0** [comment]
Yes it is opensource, although it's a built/deployed in a (for me) very unorthodox way. You don't build the library independently, but rather include the whole library's sourcetree in your actual application project. You need to use the "Projucer" project tool under extras/Projucer to build an application (which you need to bootstrap by going into extras/Projucer/Builds/LinuxMakefile and typing make). Maybe you could build one of the applications under examples, such as the ComponentTutorialExample. I'm just seeing that to do that you'll first have to create a LinuxMakefile config (in the Projucer UI tool), since it does not exist in the repository. If that's too much hassle for you I can totally understand, if I can provide debugging info instead I'll happily do that.

It seems the cpp file is included only in one place (modules/juce_gui_basics/juce_gui_basics.cpp). I also just noticed that I actually get completions in emacs for the inner enum types ColourIds and Orientation:
```
TabbedButtonBar::<TABTAB>

Possible completions are:
TabbedButtonBar::ColourIds LookAndFeel_V3::drawTabButton(juce::TabBarButton &, juce::Graphics &, bool, bool)::colID
TabbedButtonBar::ColourIds UIScheme::drawTabButton(juce::TabBarButton &, juce::Graphics &, bool, bool)::colID
TabbedButtonBar::ColourIds _ilf_1_3_::UIScheme::drawTabButton(juce::TabBarButton &, juce::Graphics &, bool, bool)::colID
TabbedButtonBar::ColourIds colID
TabbedButtonBar::ColourIds drawTabButton(juce::TabBarButton &, juce::Graphics &, bool, bool)::colID
TabbedButtonBar::ColourIds juce::LookAndFeel_V3::drawTabButton(juce::TabBarButton &, juce::Graphics &, bool, bool)::colID
TabbedButtonBar::Orientation TabbedComponent::getOrientation
TabbedButtonBar::Orientation TabbedComponent::getOrientation()
TabbedButtonBar::Orientation getOrientation
TabbedButtonBar::Orientation getOrientation()
TabbedButtonBar::Orientation juce::TabbedComponent::getOrientation
TabbedButtonBar::Orientation juce::TabbedComponent::getOrientation()
```

However if I hit return on just the TabbedButtonBar typename, resulting in this query:
```
/u/anasynth/schmitz/bin/rc --current-file=/data/anasynth/schmitz/development/ircam/juce-glbinding/modules/juce_gui_basics/layout/ --no-color -Y -S TabbedButtonBar --wildcard-symbol-names
```

I get no results. So the file *is* parsed in some way, maybe fully correct, but I don't receive results for that type/symbol.

Thanks for your help!

**Comment by Andersbakken** [comment]
Hm. That does sound very involved. Do you know if it builds on Mac? I do most of my development on Mac these days (though I could try on my linux desktop if it doesn't).

**Comment by flv0** [comment]
I tried it again with the current version of rtags and well, it works now :smile: Closing, thanks!

**Comment by Andersbakken** [comment]
Awesome.
