### ISSUE TITLE
How to compile rtags with mingw (or clang) on windows?

### ISSUE THREAD

**Issue by mzbab88** [Andersbakken/rtags#681]
I have troubles installing rtags. I'm on windows 7, I have emacs, cmake, mingw, clang and visual studio 2008 installed here. I followed installation instructions, but it gave me this error after command `cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 .`

`Could NOT find llvm-config executable and LIBCLANG_CXXFLAGS is not set`

And indeed I don't have it in my LLVM\bin. Maybe I installed wrong version of clang?

**Comment by cslux** [comment]
Hey @mzbab88, did you try this as stated in the instruction? 

``` bash
LIBCLANG_LLVM_CONFIG_EXECUTABLE=/path/to/llvm-config
```

Also I don't think it will work reliable, (but that may have changed), in mingw, cygwin and the like. See issue https://github.com/Andersbakken/rtags/issues/421, https://github.com/Andersbakken/rtags/issues/560 and https://github.com/Andersbakken/rtags/issues/389.

regards,
Christian

**Comment by cslux** [comment]
@mzbab88 It has been tested with LLVM/Clang 3.4 and above, but probably will also work with 3.3

**Comment by mzbab88** [comment]
@cslux for some reason I don't have llvm-config here. I don't know where to get it from. Probably have to compile it from source, but that's scary.

Maybe I can compile rtags without llvm-config and without cmake, somehow? I only need to figure out correct commands and correct flags for the compiler, somehow.

**Comment by mzbab88** [comment]
This is a bit unrelated, but how rtags works? Which libraries it uses, which functions it calls?

**Comment by cslux** [comment]
> for some reason I don't have llvm-config here. I don't know where to get it from. Probably have to compile it from source, but that's scary.

I'm not quit sure if it was mingw or cygwin, which provides llvm-config through the repository.
Compiling clang from scratch isn't that hard, there are plenty of tutorials out there, even for mingw, here for instance http://here-be-braces.com/blog/building-clang-natively-on-windows-mingw

> Maybe I can compile rtags without llvm-config and without cmake, somehow?

RTags uses the cmake meta-built system, so unless you port it to something else, no, it is not possible!
However, you can compile RTags without `llvm-config`, please have a look in the readme. If it does not work, post the exact command you entered, and we will try to help.

**Comment by mzbab88** [comment]
Can you upload compiled binaries for windows?

>However, you can compile RTags without llvm-config, please have a look in the readme.

Which one?

**Comment by cslux** [comment]
> Which one?

https://github.com/Andersbakken/rtags#finding-clang

**Comment by mzbab88** [comment]
So, to compile rtags, I need to set LIBCLANG_CXXFLAGS, LIBCLANG_LIBDIR and LIBCLANG_LIBRARIES to something?

By the way, in that readme you have "You need 3 things: 
1. LIBCLANG_CXXFLAGS, 
1. LIBCLANG_LIBDIR, 
1. LIBCLANG_LIBRARIES"
Wrong numeration.

**Comment by cslux** [comment]
Correct! Oh, thanks will fix it!

**Comment by mzbab88** [comment]
What should I do to compile it?

**Comment by cslux** [comment]
@mzbab88 You need to be more specific and tell us what exactly (step by step) you have tried, it's otherwise impossible to give some useful input. 

regards,
Christian

**Comment by cslux** [comment]
On Fedora for instance, the llvm-config executable comes with the llvm-devel package not sure if mingw has a similar name for the llvm development package. But if you post the commands you entered in mingw I probably can figure out way you don't have a llvm-config executable.

regards,
Christian

**Comment by mzbab88** [comment]
Ok. Step by step.

1. I installed windows 7.
2. I downloaded http://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/5.2.0/threads-win32/sjlj/i686-5.2.0-release-win32-sjlj-rt_v4-rev1.7z , and placed it into C:\mingw32-5.2.0 folder.
3. I added C:\mingw32-5.2.0\bin into %PATH%.
4. I downloaded Clang for Windows (32-bit) (or 64-bit, don't remember) from http://llvm.org/releases/download.html
5. I downloaded emacs.
6. I installed cmake.
7. I installed git gui.
8. I downloaded sources of rtags using command git clone --recursive https://github.com/Andersbakken/rtags.git
9. cd rtags
10. cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 .
11. It said something about Visual Studio 2008 being found (which is also installed here), and thrown error `Could NOT find llvm-config executable and LIBCLANG_CXXFLAGS is not set`
12. I don't know what LIBCLANG_CXXFLAGS is and what it should be.

**Comment by cslux** [comment]
Ah ok, not sure about step 4, when I tried to compile RTags in mingw I used LLVM/Clang compiled for mingw, so I can't really help you in that case. That said, it also explains why cmake was not able to find the llvm-config executable.  LIBCLANG_CXXFLAGS should at least contain the include path to the clang header files. 

Probably something like that on Windows.
``` 
cmake -DLIBCLANG_CXXFLAGS="C:\Program Files\LLVM\include"
```
But honestly I don't think RTags will reliable work as does on GNU/Linux or OS X.

**Comment by mzbab88** [comment]
Ok, now it prints this:

CMake Error at cmake/FindLibClang.cmake:84 (message):
  Could NOT find llvm-config executable and LIBCLANG_LIBDIR is not set
Call Stack (most recent call first):
  src/CMakeLists.txt:32 (find_package)

Hm, last version with "Experimental Clang Binaries for Mingw32/x86" is LLVM 3.2, looks like experiment has ended by now.

**Comment by cslux** [comment]
Question where do you run cmake?

**Comment by cslux** [comment]
Under windows cmd or mingw shell

**Comment by cslux** [comment]
Also you only can use rtags under mingw, cygwin or msys environment, if at all. It seems to me you are trying to compile rtags under mingw and want to use it with the Windows emacs binary. I'm 100 % sure that will not work. Please read trough the links I have provided under my comment [above](https://github.com/Andersbakken/rtags/issues/681#issuecomment-219634659).

**Comment by cslux** [comment]
@mzbab88 I installed the Windows LLVM/Clang binary and checked the installation directory and there are a lot includes missing, needed to compile RTags, my guess the pre-compiled Windows binary does not contain the development files to interact with LLVM/Clang. In short, it will definitely not work. However, patches are welcome to make RTags work on Windows natively Will close this issue now.

regards,
Christian

**Comment by mzbab88** [comment]
Can you please point out where in the code does rtags interact with clang? If I can't compile it, I'd like to see how it works at least.

**Comment by cslux** [comment]
Hey, [ClangIndexer.cpp](https://github.com/Andersbakken/rtags/blob/master/src/ClangIndexer.cpp) is could starting point!

regards,
Christian
