### ISSUE TITLE
rtags-fix-fixit-at-point gets confused with subsequent applications

### ISSUE THREAD

**Issue by sbroberg** [Andersbakken/rtags#682]
If I have a file that has several fixit errors in it, after using rtags-fix-fixit-at-point on the first occurrence, applying rtags-fix-fixit-at-point on subsequent errors results in the wrong text being replace (presumably due to the offsets generated by the original fixit messages no longer being correct.  Example:

    int
    main(int, char **)
    {
    cout << "Hello";
    cout << "world";
    
    return 0;
    }

C-x ` to the first error, C-c r X to fix, C-x ` to the next line's error error, C-c r X to fix, results in:

    int
    main(int, char **)
    {
    std::cout << "Helstd::cout
    cout << "world";
    
    return 0;
    }

**Comment by Andersbakken** [comment]
Yeah. It's a bit of a hard problem. I suppose we could offset the current
fixits when we apply a fixit but there's also a problem if you just insert
some lines of code further down. In a sense the safe thing to do is to save
after every modification and wait for the new results to come around.

I put in something that solves the problem in your example but it's hard to
be perfect for this.

Thanks for the report.

Anders

Anders
