### ISSUE TITLE
skipped-whitespace misses first character

### ISSUE THREAD

**Issue by blaenk** [Andersbakken/rtags#685]
Skipped whitespace seems to be working well except that it's not highlighting the initial `#` of the preprocessor directive.

![screenshot](http://i.imgur.com/aWiPpzO.png)

**Comment by Andersbakken** [comment]
I have noticed that. Oddly it's actually what clang reports. They claim
this skipped range starts at column 2. I've worked around it in elisp now.

Thanks for the report.

Anders
