### ISSUE TITLE
rtags-display-summary-as-message is missing

### ISSUE THREAD

**Issue by JohnC32** [Andersbakken/rtags#686]
In rtags.el, we have the menu item,

    (define-key map (kbd (concat prefix "U")) 'rtags-display-summary-as-message)

However, the definition of the rtags-display-summary-as-message is missing, it should be:

     (defun rtags-display-summary-as-message ()
      "Display a short text in message area describing the item at point.
    See `rtags-get-summary-text' for details."
      (interactive)
      (let ((summary (rtags-get-summary-text)))
        (when (null summary)
          (setq summary "No information for symbol"))
        (message "%s" summary)))

I find the ability to see the summary as a message convenient, though if you don't think it is useful, you could remove the key map to avoid the undefined function.

**Comment by Andersbakken** [comment]
Done. Thanks.
