### ISSUE TITLE
kbd support in emacs 23

### ISSUE THREAD

**Issue by JohnC32** [Andersbakken/rtags#687]
rtags.el currently has:

    (if (< emacs-major-version 24)
        (defalias 'kbd 'read-kbd-macro))

this only runs at load time. If you compile rtags.el with emacs 23 you get an error. The fix is to eval this at load and compile time:

    (eval-and-compile
      (when (< emacs-major-version 24)
        (defalias 'kbd 'read-kbd-macro)))

**Comment by cslux** [comment]
Hmm, I could swear it works without `eval-and-compile`, at least when a tested it in emacs 23, anyway, will test it again and report back.

**Comment by cslux** [comment]
I tested it again with emacs 23 and I got zero warnings at compile/load time, and the shortcuts are of course working. However, I'm no elisp expert, so I'm not sure if we need to put inside `eval-and-compile`.

**Comment by JohnC32** [comment]
I think the issue I'm seeing is due to coupling with other libraries when we compile rtags. When I test emacs 23 with just rtags it works. We are in the process of switching to emacs 24, so this isn't a significant issue for us and you could drop the request and wait to see if others report the issue. I had just found using eval-and-compile to work, but I admit I don't fully understand what is going on and to do so will take more time than I'd like to devote to this because it isn't an issue with emacs 24.

**Comment by cslux** [comment]
Ah ok, if so I will further investigate it. Can you post the error message please, thanks!

**Comment by JohnC32** [comment]
With the version of rtags.el from a while back, 
    
    % emacs23 -batch -Q -f batch-byte-compile rtags.el
    Loading tramp...
    
    In toplevel form:
    rtags.el:1972:4:Error: Wrong type argument: integer-or-marker-p, (concat prefix ".")
    
                (defun rtags-enable-standard-keybindings (&optional map prefix)
                  "Setup standard keybindings for the RTags commands.
    
                If optional MAP is non-nil, add the keys to MAP instead of `c-mode-base-map'.
                If optional PREFIX is non-nil, use PREFIX as prefix key for the commands,
                default is \"C-c r \". It doesn't matter whether you add a space at the end
                of PREFIX or not, if doesn't contain one, one will be added."
     line 1972>    (interactive)
    
    
Changing 
    
    (if (< emacs-major-version 24)
        (defalias 'kbd 'read-kbd-macro))
    
to
    
    (eval-and-compile
      (if (< emacs-major-version 24)
          (defalias 'kbd 'read-kbd-macro)))
    
then compiling, I see things compile correctly:
    
    % emacs23 -batch -Q -f batch-byte-compile rtags.el
    Loading tramp...
    
    In rtags-eldoc:
    rtags.el:4348:15:Warning: thing-at-point called with 2 arguments, but accepts
        only 1
    
    In end of data:
    rtags.el:4422:1:Warning: the following functions are not known to be defined:
        popup-tip, helm, yas-expand-snippet, rtags-helm-get-candidate-line,
        helm-highlight-current-line
    Wrote /local-ssd/ciolfi/sbtools/apps/emacs-add-ons/src/rtags/rtags.elc
    
Note, emacs23 may just be a bad idea to support because the current version of
company mode doesn't work. I see in the *Messages* buffer of emacs23
    
    Error in post-command-hook: (void-function condition-case-unless-debug)
    
which I believe is coming from company.el usage of (condition-case-unless-debug)
    
Thanks
John

**Comment by cslux** [comment]
Thanks a lot! That's interesting I saw this error as well in emacs 23 ` Wrong type argument: integer-or-marker-p`, that's why I added the `defalias` for `kbd`. 

Ahhh, I tried the same command than you right now and I'm getting the same error. I understand now what's going on. We use this slightly different command to byte-compile rtags.el in our cmake file.
``` bash
emacs23 -batch -Q -l share/emacs/site-lisp/rtags.el -f batch-byte-compile 
# we also add a compile-shim file as well `-l compile-shim.elisp` to suppress some other warnings. 
```

Since we load `rtags.el` before compiling we never saw this error. Now `eval-and-compile` makes absolutely sense. I will wrap this two lines than, since the user should also be able to compile it without the need to load it before.

Thanks for reporting this issue.

regards,
Christian
