### ISSUE TITLE
rc command to stop watching for file updates

### ISSUE THREAD

**Issue by kvaneesh** [Andersbakken/rtags#688]
This is going to be useful, when we are making multiple header changes and want to avoid reindexing in between, but then want other diagnostics to work in emacs. So rtags-quit-rdm may not really help here. What we want is a variant that will make rdm, stop listening for changes to file, but still be around to answer queries.

**Comment by cslux** [comment]
Not quite sure if this is what you want, but try this:
``` bash
rdm --no-filesystem-watcher
```
``` emacs-lisp
(setq rtags-enable-unsaved-reparsing nil) ;; nil is default value
(setq rtags-reindex-on-save nil)
```

regards,
Christian

**Comment by Andersbakken** [comment]
I think what you want it rtags-toggle-file-suspended

Basically you can use the -X option to temporarily ignore changes to files.

You can do it for all files:

rc -X all

or single files:

rc -X /path/to/header.h

to clear:

rc -X clear

There's also some elisp functions to toggle from within emacs. (include one
that I just added).

rtags-.*suspended

Basically changes to suspended files get ignored.

Anders

**Comment by kvaneesh** [comment]
I tried 

# rc -X all
# rc -X 
All files are suspended.
No files suspended for project <myproject>

and I still find rp process running.

-aneesh

**Comment by Andersbakken** [comment]
It won't stop or cancel the currently running (or scheduled) rp processes
but no more should get scheduled. Note that there could be 100s waiting in
the pipeline.

I'm also confused about why it says: "No files are suspended for project".

Just to make sure, try this:

rc -X all

(touch some header file, notice that no files gets reindexed)

rx -X clear

(touch the same header file, notice that files all dependencies will get
reindexed. You can check this with rc -s jobs)

Does it not behave that way for you?

Anders

**Comment by kvaneesh** [comment]
:[/tmp]$ rc --is-indexing
0
:[/tmp]$ rc -X clear
No files suspended.
:[/tmp]$ rc -X 
No files suspended for project /myproject
:[/tmp]$ rc -X  all
All files are suspended.
:[/tmp]$ rc -X 
All files are suspended.
No files suspended for project /myproject
kvaneesh@skywalker:[/tmp]$ rc -s jobs
*********************************
jobs
*********************************
kvaneesh@skywalker:[/tmp]$

**Comment by kvaneesh** [comment]
Ignoring the minor confusion w.r.t to the above output, rdm did stop indexing files with rc -X all. But then after some time it was taking 100% cpu utilization. rc -s jobs didn't list any jobs. Ended up killing using rc --quit-rdm. Will try to collect more data if I hit it again.

**Comment by Andersbakken** [comment]
If you can get that to happen I would be very interested in seeing a stack
trace of what it's doing at the time.

Anders

**Comment by Andersbakken** [comment]
I also, made a change that will stop all scheduled jobs when you do -X all. Please reopen if you're able to reproduce the 100% cpu usage from rdm without any live jobs again.
