### ISSUE TITLE
Add mechanism to customize some of the common RTags error messages

### ISSUE THREAD

**Issue by JohnC32** [Andersbakken/rtags#690]
There are a couple of errors that would be nice if we could customize without having to maintain local modifications to rtags.el. The errors are:

```
"Can't seem to connect to server. Is rdm running?"
"RTags: No results"
```

In rtags.el, we have errors being reported like:

```
(error "Can't seem to connect to server. Is rdm running?")
```

I'd like to customize this message for our environment. We have a wrapper that launches rdm, runs rc to index, etc. Currently, this wrapper  needs to be run outside of emacs to support monitoring (at least the way we set it up). One approach to customizing this error is to add to rtags.el

```
;; Clients can programmatically set the 'not running message' to explain how to
;; start the server in their local environment.
(defvar rtags-rdm-not-running-message
  "Can't seem to connect to server. Is rdm running?")
```

then rtags.el would invoke the error via:

```
(error rtags-rdm-not-running-message)
```

In our environment I can then customize the message telling them how to run rdm. A similar customization would be for the "RTags: No results".

Another approach would be to create something like

```
(rtags-report-error (error-id) 
      (cond ((eq error-id ‘no-rdm)
                (error  “Can’t seem to connect to server. Is rdm running?”))
      …
```

and invoke via:

```
(rtags-report-error ‘no-rdm)
```

which can be overridden via defadvice, though the customization variables seems like an easier approach.

RTags is very useful and the navigation is amazing especially for people used to other tag systems. With this we can make it very easy for non-emacs gru's to recover from some of the common errors.

Thanks

**Comment by Andersbakken** [comment]
I think I prefer the defcustom approach as well. Wanna cook up a
pull-request?

Anders

**Comment by JohnC32** [comment]
I will do this in the next few days. Thanks.

**Comment by Andersbakken** [comment]
Awesome. Thanks.

Anders
