### ISSUE TITLE
Locate static function

### ISSUE THREAD

**Issue by quicknir** [Andersbakken/rtags#692]
I followed the quick start instructions and indexed the rtags codebase. I try to call rtags-find-symbol with argument Server::instance. Rtags tells me no results. I then try with just instance, and Rtags responds with, found 5 locations. The second like looks like this:

src/Server.h:52:20:	    static Server *instance() { return sInstance; }

When I look at Server.h, it's quite clear that instance is a static method of Server. So the previous search should have worked according to the documentation examples. Any thoughts?

**Comment by Andersbakken** [comment]
Oops. I apparently just broke this yesterday. Should be fixed now. If you
sync and re-eval rtags.el that should work as expected. Thanks for the
report.

Anders

**Comment by quicknir** [comment]
Thanks!

**Comment by Andersbakken** [comment]
My pleasure.

Anders
