### ISSUE TITLE
Setting both rtags-periodic-reparse-timeout and completions-timer-interval deathspirals rdm

### ISSUE THREAD

**Issue by Nephyrin** [Andersbakken/rtags#693]
In a file where a reparse + re-evaluate-completions takes about 1.5 seconds, setting this:

``` elisp
  (setq rtags-periodic-reparse-timeout 0.5)
  (setq rtags-completions-timer-interval 0.5)
```

And then typing quickly, such as a lengthy comment, will cause rdm and then emacs to start stuttering.  rdm was using ~24G of ram by time I killed it.  Watching rdm output, it seems as though the events continually back up, rather than only triggering once the previous reparse/completion was flushed.

**Comment by cslux** [comment]
Likely related too #683.

**Comment by Andersbakken** [comment]
Yeah. I guess that's true. The issue is that we currently don't know when
the reparse is finished. I'll look into adding something.

Anders

**Comment by Nephyrin** [comment]
Recently, `rtags-periodic-reparse-timeout` has stopped applying entirely -- with it set, with or without `rtags-enable-unsaved-reparsing`, the buffer only seems to reparse when I request a completion or save.

**Comment by cslux** [comment]
@Nephyrin `C-h v rtags-periodic-reparse-timeout` ;-)

**Comment by Nephyrin** [comment]
Well that's just cruel.

Okay, disregard!  PEBKAC.  Original issue still stands from setting these values too low, however!
