### ISSUE TITLE
Long --socket-file=NAME paths result in chopped file names

### ISSUE THREAD

**Issue by JohnC32** [Andersbakken/rtags#694]
If you place --socket-file=NAME in a deep path (directory + file name > 120 or so characters), the path is chopped off. We ran into this because we run one rdm server per 'sandbox' where a sandbox is a large collection of modules. The --socket-file switch lets us bind rdm's to a given sandbox. Our use of directory structures to organize the sandboxes results in long paths to the sandbox root. Would it be possible to increase the path length?  Thanks

**Comment by Andersbakken** [comment]
Hi John

I don't entirely see how it would get chopped off. I did add something to
resolve it in case it's not canonical. There might be a maximum path length
for unix domain socket.

Are you seeing it chopped off in the "Unable to listen on ..." message?

Any chance you could add some printfs along the way to see when it happens?

We are kinda just assigning optarg to a string in rdm.cpp so I don't see
much room for an issue there.

Anders

**Comment by cslux** [comment]
Duplicate of #1042
