### ISSUE TITLE
when is rdm ready to accept requests?

### ISSUE THREAD

**Issue by ville-h** [Andersbakken/rtags#695]
When starting rdm as a subprocess of an editor how to reliably determine that rdm is now ready to accept requests? Is rdm ready to start to process requests sent with rc soon as the "Running with # jobs..." message is printed or some time later? Wondering if there is a timing issue where launching the rdm process asynchronously and immediately sending a request afterwards would fail because rdm had some large cache files to process?

**Comment by cslux** [comment]
actually, after you have started rdm, though it may not respond immediately when loading the projects.

**Comment by Andersbakken** [comment]
Christian is right in that it pretty much happens immediately. You could sort of poll it by doing something like this (kinda untested).

while true; do
if rc --connect-timeout 1 -w &>/dev/null; then 
     break; 
fi
done
