### ISSUE TITLE
rdm output stderr or stdout?

### ISSUE THREAD

**Issue by ville-h** [Andersbakken/rtags#696]
Should output from regular operation like startup go to stdout? For example:
"Running with 4 jobs, using args: -ferror-limit=0 -Wall -fspell-checking -Wno-unknown-warning-opion"
Makes it slightly annoying to deal with spawning rdm and discerning whether the output from it is part of normal operations or some sort of error has occured if everything goes to stderr.

**Comment by Andersbakken** [comment]
That's a good point. Mostly it all goes to stderr because we don't have a
log level that goes anywhere else but I think I'll add that since it's a
good idea. (Or use printf for those things).

Anders

**Comment by Andersbakken** [comment]
I think this should be a bit better.

**Comment by ville-h** [comment]
yep works out ok. thanks.
