### ISSUE TITLE
Problems with auto completion

### ISSUE THREAD

**Issue by quicknir** [Andersbakken/rtags#704]
I've had a lot of difficulties with auto completion. When I hit the auto-complete button in emacs, I tend to see stuff like this coming out of the server (verbose mode):

Got completion request for <filename>:36:7

And that's all. On occasion, it will say "No completion results available". I've tried deleting and reindexing already and did not solve the issue. Navigation and fly-check work fine.

**Comment by quicknir** [comment]
This was some kind of issue on my end, my apologies.

**Comment by Andersbakken** [comment]
No worries.
