### ISSUE TITLE
auto completion should warm up the current buffer from emacs

### ISSUE THREAD

**Issue by Andersbakken** [Andersbakken/rtags#705]

**Comment by quicknir** [comment]
I've been able to get auto completion working on a larger project but it is incredibly slow, company by default is timing out on me. Generally I have to hit auto complete once, wait for it to time out, then hit it again in order to get completion.

**Comment by Andersbakken** [comment]
I hope the patch I just put in will somewhat help this matter by preemptively parsing the file and getting it ready for completions.
