### ISSUE TITLE
rtags-helm-select open the selection in new window

### ISSUE THREAD

**Issue by kvaneesh** [Andersbakken/rtags#706]
I am finding this after an update from melpa.

**Comment by kvaneesh** [comment]
I reverted back to the older version of the patch and i also behave the same way. May be i got confused with helm gtags select. I was able to get the desired behaviour by changing rtags-helm-select to do a rtags-select nil nil. 

I guess it will be nice to provide two helm actions, rtags-slect and rtags-select-other-window. ?

-aneesh

**Comment by kvaneesh** [comment]
`diff --git a/src/rtags.el b/src/rtags.el
index fc701da0a530..a47e8c1082df 100644
--- a/src/rtags.el
+++ b/src/rtags.el
@@ -4549,9 +4549,14 @@ the user enter missing field manually."
   (defun rtags-helm-select (candidate)
     (with-current-buffer (get-buffer rtags-buffer-name)
       (goto-char candidate)
-      (rtags-select t nil)))
+      (rtags-select nil nil)))
   ;; (message "CAND: %d" (get-text-property 0 'rtags-buffer-position candidate)))
 
+  (defun rtags-helm-select-other-window (candidate)
+    (with-current-buffer (get-buffer rtags-buffer-name)
+      (goto-char candidate)
+      (rtags-select t nil)))
+
   (defun rtags-helm-get-candidate-line (candidate)
     (with-current-buffer (get-buffer rtags-buffer-name)
       (goto-char candidate)
@@ -4588,7 +4593,8 @@ the user enter missing field manually."
   (defvar rtags-helm-source '((name . "RTags Helm")
                               (candidates . rtags-helm-candidates)
                               (real-to-display . rtags-helm-transform)
-                              (action . rtags-helm-select)
+                              (action . (("Select in current window" . rtags-helm-select)
+                                        ("Select in other window" . rtags-helm-select-other-window)))
                               (persistent-action . rtags-helm-select-persistent))))
`

**Comment by Andersbakken** [comment]
I put in a defcustom that allows you to override. By default it now has two actions. Hope this works for you?

**Comment by kvaneesh** [comment]
There is an error with the change you committed. One extra '('
