### ISSUE TITLE
with-eval-after-load on helm

### ISSUE THREAD

**Issue by blaenk** [Andersbakken/rtags#709]
Instead of outright requiring helm with `(require 'helm ...)` I think you should put your helm stuff in `(with-eval-after-load 'helm ...)`. Otherwise I think you're forcing helm to load even if the user is deferring it to some future time.

**Comment by blaenk** [comment]
Can you please do this? I've taken great care to defer all of the packages I use to reduce my startup time, but it seems like rtags ends up requiring helm anyways on startup, despite the fact that I defer its loading until I actually need it.

Could you instead wrap all of [helm integration](https://github.com/Andersbakken/rtags/blob/master/src/rtags.el#L4550) section in `(with-eval-after-load 'helm ...)` ? I would really appreciate it!

**Comment by Andersbakken** [comment]
Sure thing. I missed this one completely. Sorry about the delay.

Anders

**Comment by blaenk** [comment]
No worries, thank you very much!
