### ISSUE TITLE
Entire source directory deleted

### ISSUE THREAD

**Issue by quicknir** [Andersbakken/rtags#710]
I've now experienced numerous times that when the server goes down, it simply deletes the entire source tree (!!!). I am building in source so perhaps that is related, either way it is incredibly annoying.

Edit: to clarify, it deletes the entire source tree of rtags, not of my code.

**Comment by Andersbakken** [comment]
I'm not sure I understand. Are you saying it deletes the actual source
files or the "database". E.g. the files in ~/.rtags/...

What do you mean by goes down? Does it crash? Do you have a way to
reproduce this? I don't think I've experienced this myself.

Anders

**Comment by quicknir** [comment]
It deletes the source of rtags itself. I have a directory called "rtags" in which I have git cloned rtags. I do a build without specifying any out of source options, so it puts the compiled binaries in rtags/bin. The index etc are in a completely different place. When I killed the server, it deleted all of the contents of rtags/.

**Comment by cslux** [comment]
I tried to reproduce it with the following but as expected nothing gets deleted.

``` bash
git clone --recursive https://github.com/Andersbakken/rtags.git
cd rtags
cmake . -DCMAKE_EXPORT_COMPILE_COMMANDS=on
make -j24
./bin/rdm
./bin/rc -J
pkill rdm
git status --porcelain # says that there are no changes, i.e. the src code wasn't deleted
ls
automated_tests  bin  build  clang.sup  cmake  CMakeCache.txt  CMakeFiles  cmake_install.cmake  CMakeLists.txt  completions  LICENSE.txt  Makefile  man  README.org  scripts  src  tests  Uninstall.cmake  web
```

Even when I killed `rdm` with `-9`, nothing got deleted. There must be something otherwise wrong.
At least I couldn't reproduce it.

Christian

**Comment by quicknir** [comment]
I'm not sure how to go about helping you reproduce it, obviously I didn't imagine it, but on the other hand that doesn't help you guys either. I'll close this for now, I'll reopen if I have some way to reproduce. I may try building out of source and see if that helps.

**Comment by Andersbakken** [comment]
The only reason where rtags should delete a whole directory would be
directories under its datadir. The default is ~/.rtags but if you pass -d
~/some/path to rdm you could run into something like this. Please reopen if
you figure out what causes it to happen.

Anders
