### ISSUE TITLE
Enhancement: include path auto-completion

### ISSUE THREAD

**Issue by quicknir** [Andersbakken/rtags#711]
There's a company backend called company c headers, that provides auto completion for #including header files. I was going to sit down with it and tell it where to look for all of my include paths, when I realized that rtags has this information already in a very precise way. So it would be relatively straightforward to write a company backend that is only enabled when doing #include {",<} that auto completes all of the possibilities.

Thoughts?

**Comment by cslux** [comment]
Hey @quicknir, this has been implemented recently, see #675.  

If you are at `#include <|` or `#include "|` where `|` is the cursor, and you call `company-complete` you should get the possible includes. 
![rtags-company-header-complete](https://cloud.githubusercontent.com/assets/1712313/15867635/74402550-2ce4-11e6-9d5a-0489c1bb0cb3.png)

Actually you should also get the includes when you're at `#include <|>` or `#include "|"` where `|` is the cursor. But `company-rtags` currently doesn't like it when `"` or `>` follows cursor. I will fix that one.

regards,
Christian

**Comment by quicknir** [comment]
Hi cslus, you are right, my bad. However, from testing it seems like currently the auto completion does not work when going into directories. In other words, if I have <some_path>/foo1/header.h, and <some_path> is one of my -I's for compiling that translation unit, when I use the auto completion it offers me foo1 as an option, but after that I cannot go on. If I try to auto complete from #include "foo1/|, it says completion is unavailable.

**Comment by cslux** [comment]
> However, from testing it seems like currently the auto completion does not work when going into directories. In other words, if I have <some_path>/foo1/header.h, and <some_path> is one of my -I's for compiling that translation unit, when I use the auto completion it offers me foo1 as an option, but after that I cannot go on. If I try to auto complete from #include "foo1/|, it says completion is unavailable.

Right, this however did work too must have been recently broken, I will look into it.

**Comment by baol** [comment]
Hi,
is it worth adding an automated test?

**Comment by Andersbakken** [comment]
Should be fixed now btw. Sorry about the long delay.

An automated test would be good probably. I'll see if I can do something.
