### ISSUE TITLE
clang-omp++ issue.

### ISSUE THREAD

**Issue by autosquid** [Andersbakken/rtags#712]
I use rtags in a cmake file, with compiler set to `clang-omp++`.

Then `rdm -v` complains:

```Source::parse Nothing looks like a compiler /usr/local/bin/clang-omp++```

Then I try to added -U to resolve this, but got the following error:

```
libc++abi.dylib: terminating with uncaught exception of type std::__1::regex_error
[1]    12604 abort      rdm -v -U "/usr/local/bin/clang-omp++"
```

What is more, I checked related code on deciding if something is a compiler, and I wonder if it would be a better way by checking the result of "compiling" a snippet with what is provided, instead of checking by a string matching.

**Comment by Andersbakken** [comment]
Hi

I've pushed a fix that will make the test pass for this anything that
starts with "clang". It would probably be better to invoke the compiler and
check the return code. I'll look into doing something when I have time.

As for the -U thing I suspect that you're using a rather old gcc to compile
rtags. gcc < ${some_version} didn't have proper regexp support. I have
added some code to catch the exception but it won't work then.

Hope this helps.

Anders

**Comment by autosquid** [comment]
hi,

Thanks for your fix, @Andersbakken .

I compiled rtags from source with clang 3.7.

Is it possible the exception is caused by the two consecutive `+` ? (I don't know much about ECMAScript regex, but   `++` looks suspectable).

**Comment by autosquid** [comment]
Nevermind, I am closing the issue since the original problem is already solved.

**Comment by Andersbakken** [comment]
Hm. The regex thing is interesting. Yeah. It's probably the consecutive
+'es. Honestly, I am not sure it should be a regex. Maybe wildcard is
better.

Anders

**Comment by autosquid** [comment]
yeah, that is part of the reason why I prefer to "invoke the compiler and
check the return code" -- you just don't have to consider these corner cases. (Extensibility is another reason).
