### ISSUE TITLE
Source::parse Nothing looks like a compiler

### ISSUE THREAD

**Issue by gokulnair** [Andersbakken/rtags#713]
Pulling in the latest version of rtags now breaks indexing entirely. When I try to index any file, rdm fails with the following message (file paths have been modified below, since its a proprietary project). All this was working just fine as of yesterday.

$~/rtags/bin/rc -c g++ client.cpp

$~/rtags/bin/rdm -v -v -v
listening ~/.rdm
Running with 8 jobs, using args: -ferror-limit=0 -Wall -fspell-checking -Wno-unknown-warning-option
Includepaths: -isystem /usr/local/Cellar/llvm/3.6.2/lib/clang/3.6.2/include/

Source::parse ( g++ client.cpp ) => List<>(g++, client_side.cpp) ~/src/
Source::parse Nothing looks like a compiler

**Comment by gokulnair** [comment]
FYI, I switched back to this commit to get things working for now: https://github.com/Andersbakken/rtags/commit/51b889b4a32ccf04e654d2e15330f2522f35bd48

**Comment by Andersbakken** [comment]
I think it should work better now.

Anders

**Comment by samwise** [comment]
Hi there, as far as I can tell as of now this same issue is still happening. No compiler is found on my system either. I looked around a bit and I think that instead of this:

```
-            if (strcmp(p.fileName(), "gcc-rtags-wrapper.sh") && !access(p.nullTerminated(), R_OK | X_OK)) {
 +            if (isWrapper(p.fileName()) && !access(p.constData(), R_OK | X_OK)) {

```
you meant:
```
-            if (strcmp(p.fileName(), "gcc-rtags-wrapper.sh") && !access(p.nullTerminated(), R_OK | X_OK)) {
 +            if (!isWrapper(p.fileName()) && !access(p.constData(), R_OK | X_OK)) {
```

**Comment by bagnose** [comment]
I've got the same problem. I bisected it to:

17ba45d17c536179654babf555f6551437d6648e is the first bad commit
commit 17ba45d17c536179654babf555f6551437d6648e
Author: Anders Bakken <agbakken@gmail.com>
Date:   Wed Jun 8 09:28:16 2016 -0700

    Fix issue #712 properly. Actually invoke the compiler with a dummy
    c-file and check the return value. Hopefully this is as portable as I think.

Can reproduce with compile_commands.json:

    [
        { "directory": "/home/bagnose/tmp",
          "command":   "clang++ -c test.cc -o test.o",
          "file":      "test.cc"  }
    ]

Works with 170e8eee7a4957606cf429b03fdfd8b5ce71557a but not 17ba45d17c536179654babf555f6551437d6648e

    $ rdm --verbose
    $ rc -J
    Source::parse Nothing looks like a compiler

**Comment by samwise** [comment]
If you are looking for a work around, probably using the explicit path to clang will avoid the buggy code path I mentioned above.

**Comment by Andersbakken** [comment]
You're absolutely right. Thanks. Can you verify that it's fixed for you now?

**Comment by bagnose** [comment]
I just tried the change proposed by @samwise against 7b2bf372e35471dd995e4d8a9c1f8f9d7937d26c and it solved my problem.

**Comment by samwise** [comment]
@Andersbakken, yep your commit worked.

**Comment by azuk** [comment]
I updated rtags from c75d987 to ce229f4. When I run `rc -J` in a project directory as before, it says "[Server] Compilation database loading..." but nothing else happens. Indexing doesn't start and nothing is logged to rdm's log. `~/.rtags` contains only `fileids` file.

I bisected the problem to commit f1b7d0f3c4a5f835ef07e05113a0a115a8e7505d, mentioned above: "Issue #713 again. We want to skip the wrappers"

I didn't try to decipher what that does but I can see it involves ccache which I'm using. The way I'm using ccache is that `/usr/bin/g++`, pointed to by `/usr/bin/c++` symlink which again is used in `compile_commands.json`, is actually a script that either execs `/usr/bin/g++.orig` or `ccache /usr/bin/g++.orig`

**Comment by Andersbakken** [comment]
Sorry about the delay.

I added some additional warnings when this happens. Can you pull and rerun
with -v?

There should be some output like this:

Failed to compile <compile command> and some more lines of stderr etc.

Can you send the output so we can determine what's going on?

Anders

**Comment by azuk** [comment]
Thanks, warnings helped to solve the problem. My compiler wrapper script depended on HOME environment variable, which isn't set when rdm runs the compiler in isCompiler(). Before the mentioned commit it didn't (try to) run the compiler, because of the filename matching.

**Comment by Andersbakken** [comment]
Hm. That's actually a bug in rtags I think. We should maintain the whole
environment that rc was invoked with. I'll try to fix it.

Anders

**Comment by ambihelical** [comment]
I was having this problem as well, but I resolved it by making the following change, which works because on my system the compiler /usr/lib/ccache/c++ resolves to /usr/bin/ccache

```
diff --git i/src/Source.cpp w/src/Source.cpp
index 6aa4c38..b2b1860 100644
--- i/src/Source.cpp
+++ w/src/Source.cpp
@@ -331,7 +331,7 @@ static Path resolveCompiler(const Path &unresolved, const Path &cwd, const List<
 
 static inline bool isCompiler(const Path &fullPath, const List<Path> &pathEnvironment)
 {
-    const char *fileName = fullPath.fileName();
+    const char *fileName = fullPath.followLink().fileName();
     if (!strcmp(fileName, "ccache"))
         return true;
     assert(EventLoop::isMainThread());

```

**Comment by shixiao** [comment]
Would it be possible to relax the constraint to allow custom wrappers?

**Comment by Andersbakken** [comment]
Yeah. I'll try to add something. It seems to be causing quite a bit of
problems right now.

Anders

**Comment by yhager** [comment]
I had the same issue, @ambihelical patch solved my issue.

**Comment by Andersbakken** [comment]
You can now do something like this:

rdm --compiler-wrappers "ccache;myownwrapper;foobar"
