### ISSUE TITLE
Instant completions at the cost of context-awareness?

### ISSUE THREAD

**Issue by Nephyrin** [Andersbakken/rtags#714]
Issue 705 seems to have increased the cases where completions are cached a little, but context-sensitive completions still seem to block on a roundtrip through rdm that takes a few seconds on large projects.

The common case for autocomplete for me is usually as a cheap "tab complete" for chained members or calls in structures such as `gFooSystem->GetBar().m_bFoo` where I may not remember the exact names or where typing e.g. `m_bF[tab]` is quicker than `m_bFullFooSystemActivated`. Though rtags provides extremely accurate suggestions at each step, it takes a few seconds to do so, negating much of the speed benefit of using autocomplete as a tab-complete style typing helper.

Sometimes, though, rtags does have the symbol available: On new lines, for instance, `gFoo->` will (sometimes) autocomplete instantly, whereas `Foo( gFoo->` will block for seconds, presumably because of magic such as ADL that could change what is now available in that scope.  Would it be feasible to have a "less contextually accurate" completions mode that might offer less contextually filtered completions in exchange for having them always available? Or am I overestimating how general the caching of completions is on the emacs side?

**Comment by Andersbakken** [comment]
Hi John

After some diagnostics I came to the conclusion that the main problem with
completion performance was the emacs process filter. Somehow having an
async process running and monitoring it for output using set-process-filter
is ridiculously expensive compared to just firing up an async process and
waiting for it to finish and then parsing the results. This new approach is
a lot simpler to deal with in a number of ways and from what I can gather a
fair bit more performant. Can you give it a check?

Anders

**Comment by Nephyrin** [comment]
Hey Anders,

I used this for much of the day yesterday, and it seems much improved -- when rdm is idle, using company with synchronous completions, it seems to only take about a second in the worst case, and many more completion cases seem to be instant.  Sometimes completions while rdm is reparsing many files block for longer, but overall it is an order of magnitude faster.

In particular, doing something like `this->m_[tab]` sometimes blocks for about a second, but then chaining completion calls to sub-members and functions seem to be fully cached.  I'll keep using it and report back if I can nail down more specific slow usage scenarios, but I think these changes alleviate the need for the original feature request in this bug.

Thanks as usual for your work on this!
