### ISSUE TITLE
compile error in `RTagsLogOutput.h`

### ISSUE THREAD

**Issue by danshapero** [Andersbakken/rtags#716]
When compiling from the master branch, I get the following error in the source file `CompletionThread.cpp`:

    [ 11%] Building CXX object src/CMakeFiles/rtags.dir/CompletionThread.cpp.o
    In file included from /home/daniel/programs/rtags/src/CompletionThread.cpp:21:0:
    /home/daniel/programs/rtags/src/RTagsLogOutput.h: In constructor ‘RTagsLogOutput::RTagsLogOutput(LogLevel, unsigned int, const std::shared_ptr<Connection>&)’:
    /home/daniel/programs/rtags/src/RTagsLogOutput.h:38:29: error: ‘class SocketClient’ has no member named ‘setLogsEnabled’
                 conn->client()->setLogsEnabled(false);
                                 ^~~~~~~~~~~~~~
    src/CMakeFiles/rtags.dir/build.make:158: recipe for target 'src/CMakeFiles/rtags.dir/CompletionThread.cpp.o' failed

Looking at the header file for `SocketClient.h`, there doesn't appear to be any member named `setLogsEnabled`. Is this maybe a submodule versioning issue?

I've tried this with gcc-6.1 and clang-3.8.

**Comment by Andersbakken** [comment]
My bad. I forgot to push the rct update. If you pull and do a git submodule
update it should work now.

Anders

**Comment by danshapero** [comment]
That fixed it, thanks!

**Comment by Andersbakken** [comment]
My pleasure.

Anders
