### ISSUE TITLE
colon in path causes problems?

### ISSUE THREAD

**Issue by ville-h** [Andersbakken/rtags#717]
I am not sure how to escape a colon in path for something like:
```
rc --follow-location /home/ville/projects/test:filename/src/main.cxx:1:1
```
Single quotes, \\:, \\\\: doesn't seem to do any difference. It invariably results in:
```
Can't resolve argument /home/ville/projects/test:filename/src/main.cxx:1:1
```

**Comment by Andersbakken** [comment]
I think it should be fixed now. Thanks for the report.

**Comment by ville-h** [comment]
Possibly solved not or i just don't know the exact syntax to use. Can you give me a an example command that i can copypaste to verify and get an idea what format is the correct format?

**Comment by Andersbakken** [comment]
This should work:

[abakken@lgml-abakken1:~/temp/test:colon] cat -n main.cpp
     1  int main()
     2  {
     3      return 0;
     4  }
[abakken@lgml-abakken1:~/temp/test:colon] rc  -f
/Users/abakken/temp/test:colon/main.cpp:3:5:
main.cpp:1:1:   int main()

Anders

**Comment by ville-h** [comment]
Aha! I was missing the trailing :.

**Comment by Andersbakken** [comment]
It wasn't actually meant to be required so thanks for reporting it.

Anders
