### ISSUE TITLE
Segmentation fault on Kubuntu 14.04

### ISSUE THREAD

**Issue by sdeber** [Andersbakken/rtags#720]
Hi, Ander. I got a segmentation fault on Kunbutu 14.04 64bit. It fails immediately when I run 'rdm' command from terminal. Here is the backtrace:

 Core was generated by `rdm'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f7e1656045b in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007f7e1656045b in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00000000004d8064 in Rct::executablePath() ()
#2  0x000000000044a21e in defaultRP() ()
#3  0x0000000000447e6a in _GLOBAL__sub_I_rdm.cpp ()
#4  0x00000000005b5d5d in __libc_csu_init ()
#5  0x00007f7e155a6ed5 in __libc_start_main (main=0x4456f0 <main>, argc=1, argv=0x7ffc50b485c8, init=0x5b5d10 <__libc_csu_init>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7ffc50b485b8) at libc-start.c:246
#6  0x0000000000449af4 in _start ()

**Comment by Andersbakken** [comment]
Hi 

I think this should be fixed now. Can you check?

**Comment by sdeber** [comment]
Just tested. It is fixed. Thank you so much for the quick response!
