### ISSUE TITLE
Auto completion crashes

### ISSUE THREAD

**Issue by quicknir** [Andersbakken/rtags#721]
I'm seeing a lot of this lately while trying to autocomplete:

```
lang::ASTUnit::ConcurrencyState::start(): Assertion `acquired && "Concurrent access to ASTUnit!"' failed.
libclang: crash detected in code completion
```

Any ideas?

**Comment by Andersbakken** [comment]
I've seen this one before and I really don't understand how it could
happen. We very definitely only touch the completion APIs from that one
thread. In general I suggest building clang without assertions. A lot of
them are seemingly erroneous.

Anders
