### ISSUE TITLE
recent update broken the command line parser

### ISSUE THREAD

**Issue by lianghu** [Andersbakken/rtags#722]
rdm complains "invalid option" for almost all options used to work.

such as  "rdm -M -v --job-count 4 -G -mabi=aapcs-linux --daemon"  will emit:
rdm: invalid option -- 'M'
rdm: invalid option -- ‘v'
.....
rdm: invalid option '--daemon'

**Comment by Andersbakken** [comment]
Hm. I busted that pretty bad it turns out. Should work better now.

**Comment by lianghu** [comment]
can't pass compile with error:

Rtags.h:776:14: error: 'optreset' was not declared in this scope.
