### ISSUE TITLE
[Request] Add functions-called-by-this-function and functions-calling-this-function

### ISSUE THREAD

**Issue by dubnde** [Andersbakken/rtags#728]
Is it completely bonkers to ask for two features?
1. Functions called by a function
2. Find all functions calling a function

Similar to what [cscope](http://cscope.sourceforge.net/) does.

**Comment by wandns** [comment]
I second this request. One thing I miss from Eclipse is its call hierarchy feature.

**Comment by gokulnair** [comment]
Any chance of getting "2. Find all functions calling a function" ?

**Comment by Andersbakken** [comment]
We do kinda have that feature. If you use rtags-references-tree instead of
rtags-find-references-at-point.

You can expand the tree with tab and see the calling function on the right.

Does this work? I'm open to suggestions of better ways of presenting this
info.

Anders
