### ISSUE TITLE
rc --symbol-info return field SymbolName missing trailing-return-type

### ISSUE THREAD

**Issue by ville-h** [Andersbakken/rtags#731]
```
void function0() -> void {}
auto function1() -> void {}
```
Running `rc --symbol-info` on function1 will leave out the trailing-return-type "-> void" from the SymbolName field of the command output.

**Comment by ville-h** [comment]
correction to above it seems it occurs on non-static member functions only.
```
struct aa {
    auto function() -> void {
    }
```

**Comment by Andersbakken** [comment]
I can't actually reproduce this. Which version of clang/rtags are you
using? It seems to work for me as of current HEAD of RTags and clang 3.8.1.

I tried to repro like this:

$ rc -F "auto aa::function() -> void"
main.cpp:4:10:      auto function() -> void {

$ rc -U main.cpp:4:10:
main.cpp:4:10:      auto function() -> void {
SymbolName: auto aa::function() -> void
Kind: CXXMethod
Type: auto () -> void
SymbolLength: 8
Range: 4:5-5:6
Stack cost: 0
Linkage: External
Definition Container
Usr: c:@S@aa@F@function#

$ cat -n main.cpp
     1  auto function1() -> void {}
     2
     3  struct aa {
     4      auto function() -> void {
     5      }
     6      auto function3() -> int {
     7          return 1;
     8      }
     9
    10      static auto function2() -> void {
    11      };
    12  };
    13
    14
    15  int main(int argc, char **argv)
    16  {
    17
    18  }


Anders

**Comment by ville-h** [comment]
Very poor reporting on my part. It's member functions and function templates(?) with any cv- or ref-qualifiers and late-return-type.
```
struct aa {
    auto cv_qualifier() const -> void {
    }

    auto cv_qualifier() volatile -> void {
    }

    auto ref_qualifier() & -> void {
    }

    auto ref_qualifier() && -> void {
    }
};


int main() {
}
```
```
rc --symbol-info main.cxx:2:10:
rc --symbol-info main.cxx:5:10:
rc --symbol-info main.cxx:8:10:
rc --symbol-info main.cxx:11:10:
```

**Comment by Andersbakken** [comment]
Should be fixed now. Sorry about the long delay.

**Comment by ville-h** [comment]
Works as expected. Thansk for the fix.
