### ISSUE TITLE
rdm 100% usa ge

### ISSUE THREAD

**Issue by kvaneesh** [Andersbakken/rtags#734]
I hit this again. I have suspended all the file watch and rdm start hitting 100%

The stack trace
#20 0x00007eff6778cdbc in ?? () from /usr/lib/llvm-3.8/lib/libclang-3.8.so.1
#21 0x00007eff6778210b in ?? () from /usr/lib/llvm-3.8/lib/libclang-3.8.so.1
#22 0x00007eff6720c59e in ?? () from /usr/lib/llvm-3.8/lib/libclang-3.8.so.1
#23 0x00007eff671d2fe4 in ?? () from /usr/lib/llvm-3.8/lib/libclang-3.8.so.1
#24 0x00007eff66fdcff5 in ?? () from /usr/lib/llvm-3.8/lib/libclang-3.8.so.1
#25 0x00007eff66fddb9c in ?? () from /usr/lib/llvm-3.8/lib/libclang-3.8.so.1

---Type <return> to continue, or q <return> to quit---
#26 0x00007eff634f5299 in llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) () from /usr/lib/x86_64-linux-gnu/libLLVM-3.8.so.1
#27 0x00007eff634f5324 in ?? () from /usr/lib/x86_64-linux-gnu/libLLVM-3.8.so.1
#28 0x00007eff6355b05d in ?? () from /usr/lib/x86_64-linux-gnu/libLLVM-3.8.so.1
#29 0x00007eff668a96fa in start_thread (arg=0x7eff616a0700) at pthread_create.c:333
#30 0x00007eff65c9eb5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Sorry i don't have libclang debug version installed

**Comment by Andersbakken** [comment]
Hm. It seems like it's related to completions then since that would be the
only thing using a clang thread inside rdm (outside of --visit-ast and
--dump-file which I doubt you most likely weren't using).

Are you using completions?

Anders

On Tue, Jun 21, 2016 at 10:39 PM, Aneesh Kumar K.V <notifications@github.com

**Comment by kvaneesh** [comment]
Yes, i have autocomplete enabled via company-mode.

**Comment by Andersbakken** [comment]
Hm. I don't entirely know how to diagnose this further. Is it stuck in a
loop at this point do you think? E.g. if you go to the RunSafely frame (26)
and hit continue does it ever wake up?

Anders

**Comment by kvaneesh** [comment]
I now have installed clang debug package and will try to get a better stack, when we hit this next time.
