### ISSUE TITLE
Appropriate for embedded development? 

### ISSUE THREAD

**Issue by gkontsevich** [Andersbakken/rtags#735]
I was wondering if rtags would be appropriate for embedded development. I finally got a build system set up for ARM (specifically the stm32f4 discovery board) but unfortunately it's quit involved. There is a custom linking script, specially assembly headers, gcc directives to strip symbols - all uses the GNU toolchain.

I understand rtags uses the clang/LLVM tool chain, however how much of it do i need to get rtags working? I can maybe get the compilation to work just fine, but I don't imagine i can get the linking to ever work (or at least that's beyond my skillset). Would that be sufficient? Or do i need to be able to build end to end?

Thanks for the awesome tool,

George

**Comment by gkontsevich** [comment]
sorry, i was too quick to open the issue!
I found closed issues that seem to indicate it's not a problem

https://github.com/Andersbakken/rtags/issues/594
https://github.com/Andersbakken/rtags/issues/100

just need to wrap around my head around the bin scripts and how that works

**Comment by rajukv** [comment]
Only thing you need to use rtags is the compile_commands.json file. If you
have a build system that uses regular make, then you can use bear(
https://github.com/rizsotto/Bear) to generate the compile_commands.json
file.

On Wed, Jun 22, 2016 at 5:24 PM, George Kontsevich <notifications@github.com

**Comment by Andersbakken** [comment]
Generally it shouldn't be a problem. If your compile commands use esoteric
switches that clang doesn't support we may have to make sure they get
stripped out before being passed to clang. Let me know if you have any
problems. I use rtags for embedded linux development on a daily basis.

Anders
