### ISSUE TITLE
Can't kill tramp buffer, when rtags is enabled

### ISSUE THREAD

**Issue by martin5233** [Andersbakken/rtags#740]
I'm experiencing a strange phenomenon, which includes rtags, cmake-ide and tramp. When rtags and cmake-ide are enabled and I visit a remote buffer via tramp, and the buffer is visited via the SMB protocol of tramp, then this buffer cannot be killed. The attempt results in an error message
tramp-file-name-handler: Directory /smb:remoteuser@remotemachine:/C$/Temp not accessible.

If either cmake-ide or rtags are not initialized, or the remote buffer is via ssh, everything works as expected. Emacs version is 25.0.95.
This is the stack backtrace I get, when I stop in rtags-untrampify, which I believe has something to do with the problem:

  (edebug-after (edebug-before 0) 10 (if (edebug-after (edebug-before 1) 3 (tramp-tramp-file-p (edebug-after 0 2 location))) (edebug-after (edebug-before 4) 8 (tramp-file-name-localname (edebug-after (edebug-before 5) 7 (tramp-dissect-file-name (edebug-after 0 6 location))))) (edebug-after 0 9 location)))
  (lambda nil (edebug-after (edebug-before 0) 10 (if (edebug-after (edebug-before 1) 3 (tramp-tramp-file-p (edebug-after 0 2 location))) (edebug-after (edebug-before 4) 8 (tramp-file-name-localname (edebug-after (edebug-before 5) 7 (tramp-dissect-file-name (edebug-after 0 6 location))))) (edebug-after 0 9 location))))()
  edebug-enter(rtags-untrampify ("--set-buffers") (lambda nil (edebug-after (edebug-before 0) 10 (if (edebug-after (edebug-before 1) 3 (tramp-tramp-file-p (edebug-after 0 2 location))) (edebug-after (edebug-before 4) 8 (tramp-file-name-localname (edebug-after (edebug-before 5) 7 (tramp-dissect-file-name (edebug-after 0 6 location))))) (edebug-after 0 9 location)))))
  edebug-enter(rtags-untrampify ("--set-buffers") (lambda nil (edebug-after (edebug-before 0) 10 (if (edebug-after (edebug-before 1) 3 (tramp-tramp-file-p (edebug-after 0 2 location))) (edebug-after (edebug-before 4) 8 (tramp-file-name-localname (edebug-after (edebug-before 5) 7 (tramp-dissect-file-name (edebug-after 0 6 location))))) (edebug-after 0 9 location)))))
  rtags-untrampify("--set-buffers")
  mapcar(rtags-untrampify ("--set-buffers" "-"))
  rtags-call-rc(:noerror t :silent-query t :path t :unsaved #<buffer  *temp*> "--set-buffers" "-")
  rtags-set-buffers((#<buffer  *Minibuf-1*> #<buffer ooa> #<buffer *Bookmark List*> #<buffer  *guide-key*> #<buffer 16MY> #<buffer *rdm*> #<buffer &bitlbee> #<buffer localhost:6667> #<buffer *scratch*> #<buffer  *Minibuf-0*> #<buffer *Messages*> #<buffer  *code-conversion-work*> #<buffer  *Echo Area 0*> #<buffer  *Echo Area 1*> #<buffer  *mu4e-mails*-252827> #<buffer  *mu4e-mails*-470178> #<buffer init.el> #<buffer cmake-ide> #<buffer private.org> #<buffer WizardSubVarTreeWidget.cpp> #<buffer SubVarAddInfoProxyModel.cpp> #<buffer 010_EGB_B_engine_gearbox_2em_2gm.par.spck> #<buffer simpack-2017.ini> #<buffer 010_EGB> #<buffer 112_BRK_D_brakes_sliding_caliper.par.spck> #<buffer SubVarAddInfoProxyModel.h> #<buffer MessageLogEventHandler.cpp> #<buffer ModelTreeFilterModel.h> #<buffer CommentSupport.cpp> #<buffer 112_BRK> #<buffer 00_wizardsubvars> #<buffer v_00> #<buffer d01> #<buffer 12-FSR> #<buffer *Alerts*> #<buffer *helm buffers*> #<buffer  *tip*> #<buffer geburtstage.org> #<buffer na.org> #<buffer *tramp/smb mal1%dsone@lw5-mal1-cem*> #<buffer  bogus edebug buffer> #<buffer *helm-mode-kill-buffer*>))
  rtags-kill-buffer-hook()
  kill-buffer("CMakeLists.txt")
  funcall-interactively(kill-buffer "CMakeLists.txt")
  call-interactively(kill-buffer nil nil)
  command-execute(kill-buffer)

**Comment by Andersbakken** [comment]
Odd. Are you running rdm on the remote server? What does it take to
reproduce it.

Anders

**Comment by martin5233** [comment]
Thanks for your answer. I am running rdm on the same Linux machine as Emacs.
I have created the following small elisp snippet, which you can store in a file:

(add-to-list 'load-path "~/.emacs.d/el-get/rtags/src")
(require 'rtags)
(find-file "/smb:user%domain@machine:/E$/users/ma/CMakeLists.txt")


Start emacs with 'emacs -Q -l filename.el' and then try to kill the buffer of the CMakeLists.txt file
interactively. It doesn't matter, which major mode the opened file has, I used a CMake file for convenience. In this case I also get the message 
_Error running timer `rtags-update-buffer-list': (file-error "Directory /smb:mal1%dsone@lw5-mal1-cem:/C$/Temp not accessible")_
even before trying to kill the buffer.
I tried this with Emacs 25.0.95 and also with 24.4, both with the same result. A small correction with respect to my initial bug report: It doesn't have anything to do with cmake-ide, rtags alone seems to be enough, at least in this minimal environment of 'emacs -Q'.

Hope this helps,

Martin

**Comment by ramestica** [comment]
Any updates on this issue?

I wonder about the question 'Are you running rdm on the remote server?'

Compiling rdm in my remote system would be quite some work, therefore, I was wondering whether that's really needed or not. Perhaps I just do not understand the mechanism, but I thought that perhaps rc running in my local system would be able to extract the needed information from the remote project into my local rdm process. Is that possible?

Thanks,
 Rodrigo

**Comment by Andersbakken** [comment]
Hi Martin

I think my last commit might fix it. Can you check?

regards

Anders

**Comment by martin5233** [comment]
Hi Anders,

I checked it and it seems to work now. Thanks a lot, rtags is really a great project!

Regards,

Martin

**Comment by Andersbakken** [comment]
Thanks. Glad to hear that.

Anders
