### ISSUE TITLE
Should -march be blocked automatically?

### ISSUE THREAD

**Issue by ambihelical** [Andersbakken/rtags#741]
Working in a cross-compile embeded environment, the embedded gcc compiler often has an -march argument that clang doesn't understand, leading to parse errors in rdm.  I'm currently using --block-argument -march=  in rtags-process-flags to get around this.  Does it make sense for rtags to block this by default?

**Comment by Andersbakken** [comment]
I think that's a good idea. I blacklisted some more similar gcc-specific as well. Thanks

**Comment by phord** [comment]
This causes my PC compiles to generate lots of errors because it filters out -march=corei7 which is needed for SSE4 instructions.  Can the blacklist be more selective?  Or can we add a whitelist?
