### ISSUE TITLE
rtags sets up invalid enviroment during compiler detection.

### ISSUE THREAD

**Issue by Artem-B** [Andersbakken/rtags#742]
pathEnvironment passed to isCompiler() is a list of paths which gets passed to proc.exec() as if it were process' environment. The end result is that compiler process ends up running with no PATH set.

One case where it shows up is when compilation is done with ccache.
`# /usr/lib/ccache/clang -c foo.c`
where `/usr/lib/ccache/clang` is a symlink -> `ccache`
ccache relies on being able to find clang somewhere else in PATH
In this particular case, rdm runs ccache with environment that has no PATH set, ccache can't find real compiler and returns an error which results in rdm ignoring all compile commands that use ccache.

**Comment by Andersbakken** [comment]
Sorry about the delay. I'll take a look soon.

**Comment by Artem-B** [comment]
rtags works fine with ccache in 016b7a87edd1bf695.
I think 22789e8a182043fc fixed it.

**Comment by Artem-B** [comment]
Argh. The issue is still there. I've accidentally 'tested' on build that used clang without ccache. Rtags still does not detect compiler with ccache that relies on valid PATH.

**Comment by Andersbakken** [comment]
Sorry about the long delay. How can I reproduce this?

**Comment by Artem-B** [comment]
One way to reproduce it would be to just print pathEnvironment inside isCompiler() for any build you have when you're loading compilation database for a new project with `rc -J`. pathEnvironment will be wrong (i.e. there's no `PATH=/usr/bin:....` whether or not you're using ccache. The difference is that real gcc or clang do not depend on PATH, will run fine and keep rtags happy.

The hard way (which is probably an overkill):
`# make sure real clang++ and clang are  found somewhere in $PATH`
`# ln -s /path/to/ccache /some/path/clang++`
`# ln -s /path/to/ccache /some/path/clang`

Now configure something to build with CXX=/some/path/clang++ and CC=/some/path/clang.
I typically use `cmake -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ...` and then do `rc -J $BUILD_DIR`

Normally `/some/path/clang++` would invoke ccache. Ccache would check what name it was ran as (`clang` or `clang++`) and would attempt to find an executable in $PATH which is not the symlink that started this ccache. Typically that would be real clang++ which would then do the compilation if needed.

In this case, during load of compilation database rtags attempts to run compiler, but it messes up environment. Ccache is run w/o PATH set, fails to find real compiler, compilation fails, and rtags figures that it's not a compiler and ignores all entries in the compilation database that use `/some/path/clang++` to compile files.

**Comment by Andersbakken** [comment]
Ah. I see what's wrong now. I was passing $PATH to the process invocation
which expected the whole environment.

Thanks. It should be fixed now.

Anders
