### ISSUE TITLE
correct command sequence to get completions in file that is altered and saved?

### ISSUE THREAD

**Issue by ville-h** [Andersbakken/rtags#744]
file:
```
void function() {
}


auto main() -> int {
    func
}
```
run:
```
rc --synchronous-completions --code-complete-at /home/ville/projects/test/src/main.cxx:6:5: | grep func
```
receive the completion suggestion as expected.

Change the file and save to disk:
```
void function() {
}


void function(int) {
}


auto main() -> int {
    func
}
```
run:
```
rc --synchronous-completions --code-complete-at /home/ville/projects/test/src/main.cxx:10:5: | grep func
```
no completions seem to be returned.
```
rc --reindex
```
reports one file dirtied but rerunning the command still returns no results. Restarting rdm and running the command gives results including the new overload.

So what is the correct sequence of operations to get completions updated when a file is written to disk?

**Comment by Andersbakken** [comment]
Sorry about the delay. I can reproduce the issue but I don't quite understand what's going wrong yet. I'll try to get back to you soon.

**Comment by ville-h** [comment]
That's fine, summer holidays and whatnot. Great that you can reproduce the problem at least. Had any luck determining the cause?

**Comment by Andersbakken** [comment]
Well. Summer is over and I think I have a good fix. I think this might
positively impact current emacs completion systems as well. It seems to
boil down needing to call reparse when the source code has changed which
isn't even the most unreasonably thing ever.

Can you verify that it works now for you?

Anders

**Comment by ville-h** [comment]
Appears to work now and returned both overloads as expected. Thanks for the fix.
