### ISSUE TITLE
rtags-find-symbol-at-point jumps to a wrong location

### ISSUE THREAD

**Issue by azuk** [Andersbakken/rtags#751]
Consider the following example:
```
struct Poro {
    Poro(int a, int b, int c, int d)
    {
    }
};

struct Kala {
    Kala(const Poro& poro, int a, int b)
    {
    }
};

int main(int argc, char** argv)
{
    static Kala lahna(Poro(0, 0, 0, 0),
        2,
        4);
    return 0;
}
```
If I move cursor over `Kala` on line `static Kala lahna...` and use `rtags-find-symbol-at-point`, it jumps to the constructor of `Poro` on the second line. I'd expect it to jump to the `struct Kala {` line.

rtags 8180200. clang cb51a665b0dad7308b0dd4edf668048ce0eb5242.

**Comment by Andersbakken** [comment]
Interesting. That's definitely a bug. I'll try to fix it. Thanks

Anders

**Comment by Andersbakken** [comment]
Should be fixed now. Thanks.

**Comment by dubnde** [comment]
thanks very much. Very helpful
