### ISSUE TITLE
Recent completion changes broke rtags-ac.el.

### ISSUE THREAD

**Issue by toojays** [Andersbakken/rtags#752]
I just updated to 016b7a87 and now auto-complete is failing with:

```
Error running timer `ac-update-greedy': (void-variable rtags-last-completions) [2 times]
Error running timer `ac-show-menu': (void-variable rtags-last-completions)
Error running timer `ac-update-greedy': (void-variable rtags-last-completions)
```

rtags-last-completions was removed in 585b8c9.

Is everyone else using company-mode? I tried that a while ago, but liked AC better for searching/reducing the candidate list.

**Comment by Andersbakken** [comment]
Oops. I have to make that work again. I will look into it.

Anders

**Comment by cslux** [comment]
I'll close this issue. If this still happens feel free the reopen it.
