### ISSUE TITLE
rtags cmake cannot detect c++11 in gcc 4.8.2 or clang 3.6.1

### ISSUE THREAD

**Issue by okovko** [Andersbakken/rtags#753]
This issue can be closed. Ultiamtely I used gcc 4.8.2 to compile rtags, and it wasn't working because I forgot to unset LIBCLANG_LIBDIR etc from an earlier build attempt. Those env vars are used if you specify llvm-config. Thanks jhanssen!

At this point, I have also tried using gcc 4.8.2 to compile rtags and it still does not recognize c++11 support. I do not understand how this could possibly be the case. I tried compiling the test programs in CMakeFiles/CmakeError.log and they compiled just fine.

I'm compiling rtags using clang 3.6.1, linked to libc++. It refuses to compile due to failing to have c++11 support.

This test,

okovalen ~: $clangdir/bin/clang++ $CXXFLAGS $LDFLAGS -xc++ -v - << EOF
int main(){}
EOF

works just fine, where CXXFLAGS and LDFLAGS correspond to (see below) CMAKE_CXX_FLAGS_INIT and CMAKE_EXE_LINKER_FLAGS respectively.

Please and thank you for your assistance. The commands I tried and the output is below.

okovalen rtags: ~/local/bin/cmake  \
    -DCMAKE_USER_MAKE_RULES_OVERRIDE=~/clang_flags.txt \
    -DLIBCLANG_LLVM_CONFIG_EXECUTABLE=path/to/clang/bin/llvm-config \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=1 .

~/clang_flags.txt
    SET (CMAKE_C_FLAGS_INIT                "-Wall -std=c99")
    SET (CMAKE_CXX_FLAGS_INIT            "-Wall -std=c++11")
    SET (CMAKE_EXE_LINKER_FLAGS        "-nostdinc -stdlib=libc++ -lc++ -lc++abi -lm -lc -lgcc_s -lgcc -I/path/to/clang/include/c++/v1 -L/path/to/clang/lib -Wl,-rpath,-L/path/to/clang/lib")

Output:

-- Performing Test HAVE_CXX11
-- Performing Test HAVE_CXX11 - Failed
CMake Error at src/rct/rct.cmake:239 (message):
  C++11 support not detected.  rct requires a modern compiler, GCC >= 4.8 or
  Clang >= 3.2 should suffice
Call Stack (most recent call first):
  src/CMakeLists.txt:44 (include)

**Comment by okovko** [comment]
It is because GCC is 4.4.7 and it is the "Selected GCC installation." I think this means the version of libstdc++ being used is too old. I noticed another recent issue where this was a problem. Maybe it is worth adding some info text about checking the libstdc++ version as well as the version of clang.

**Comment by okovko** [comment]
Can someone tell me how to disable the test script so I can just compile this.

**Comment by jhanssen** [comment]
What's the relevant output from CMakeError.log? That should tell us the exact error message from your compiler.

If you want to try to not perform the test then you could comment out or remove the line reading

```message(FATAL_ERROR "C++11 support not detected. rct requires a modern compiler, GCC >= 4.8 or Clang >= 3.2 should suffice")```

in ```src/rct/rct.cmake```

**Comment by okovko** [comment]
Thank you for responding, I just had to take a walk because I'm at my wits' end with this.

Performing C++ SOURCE FILE Test HAVE_CXX11 failed with the following output:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 488 Change Dir: /home/okovalen/rtags/CMakeFiles/CMakeTmp                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
 489                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
 490 Run Build Command:"/usr/bin/gmake" "cmTC_385aa/fast"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
 491 /usr/bin/gmake -f CMakeFiles/cmTC_385aa.dir/build.make CMakeFiles/cmTC_385aa.dir/build                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
 492 gmake[1]: Entering directory `/home/okovalen/rtags/CMakeFiles/CMakeTmp'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
 493 Building CXX object CMakeFiles/cmTC_385aa.dir/src.cxx.o                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
 494 /opt/gcc/x86_64/4.8.2a-1/bin/g++     -std=c++11  /build/ltesdkroot/Tools/Tools/clang-tools/CLANG_TOOLS_3.9_005/include -Wall -Wextra -Wpointer-arith -Wnon-virtual-dtor -fno-rtti -std=c++11 -DHAVE_CXX11 -std=c++11   -o CMakeFiles/cmTC_385aa.dir/src.cxx.o -c /home/okovalen/rtags/CMakeFiles/CMakeTmp/src.cxx                                                                                                                                                                                                                                                                                                                                                                                         
 495 g++: warning: /build/ltesdkroot/Tools/Tools/clang-tools/CLANG_TOOLS_3.9_005/include: linker input file unused because linking not done                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
 496 Linking CXX executable cmTC_385aa                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
 497 /home/okovalen/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_385aa.dir/link.txt --verbose=1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
 498 /opt/gcc/x86_64/4.8.2a-1/bin/g++   -std=c++11  /build/ltesdkroot/Tools/Tools/clang-tools/CLANG_TOOLS_3.9_005/include -Wall -Wextra -Wpointer-arith -Wnon-virtual-dtor -fno-rtti -std=c++11 -DHAVE_CXX11 -std=c++11    CMakeFiles/cmTC_385aa.dir/src.cxx.o  -o cmTC_385aa -rdynamic                                                                                                                                                                                                                                                                                                                                                                                                                        
 499 /build/ltesdkroot/Tools/Tools/clang-tools/CLANG_TOOLS_3.9_005/include: file not recognized: Is a directory                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
 500 collect2: error: ld returned 1 exit status                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
 501 gmake[1]: *** [cmTC_385aa] Error 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
 502 gmake[1]: Leaving directory `/home/okovalen/rtags/CMakeFiles/CMakeTmp'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
 503 gmake: *** [cmTC_385aa/fast] Error 2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
 504                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
 505 Source file was:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
 506                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
 507   #include <memory>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
 508   #include <mutex>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
 509   #include <tuple>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
 510   #include <string>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
 511   #include </home/okovalen/rtags/src/rct/rct/Apply.h>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
 512                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
 513   void callTest(int, std::string) { }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
 514                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
 515   int main(int, char**) {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
 516       std::shared_ptr<int> ptr;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
 517       std::mutex mtx;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
 518       std::unique_lock<std::mutex> lock(mtx);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
 519       std::tuple<int, std::string> tpl(5, std::string("foo"));                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
 520       applyMove(std::bind(callTest, std::placeholders::_1, std::placeholders::_2), tpl);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
 521       return 0;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
 522   }

**Comment by jhanssen** [comment]
Ok, so the compile line is

```/opt/gcc/x86_64/4.8.2a-1/bin/g++     -std=c++11  /build/ltesdkroot/Tools/Tools/clang-tools/CLANG_TOOLS_3.9_005/include -Wall -Wextra -Wpointer-arith -Wnon-virtual-dtor -fno-rtti -std=c++11 -DHAVE_CXX11 -std=c++11   -o CMakeFiles/cmTC_385aa.dir/src.cxx.o -c /home/okovalen/rtags/CMakeFiles/CMakeTmp/src.cxx```

meaning it has two inputs, the first is ```/build/ltesdkroot/Tools/Tools/clang-tools/CLANG_TOOLS_3.9_005/include``` and the second is ```/home/okovalen/rtags/CMakeFiles/CMakeTmp/src.cxx```

The second one is provided by CMake and is a (presumably) valid file, but the first is not a valid file (the compiler says ```/build/ltesdkroot/Tools/Tools/clang-tools/CLANG_TOOLS_3.9_005/include: file not recognized: Is a directory```) and I'm not sure where it comes from. Do you have anything in CFLAGS/CXXFLAGS that could be misinterpreted by the compiler?

**Comment by okovko** [comment]
My CXX and CC point to g++/gcc and CXXFLAGS is just -std=c++11, LDFLAGS is empty, CFLAGS is empty. It must be getting it from an environment variable I set but I have no idea which one it is. I am using -DCMAKE_EXPORT_COMPILE_COMMANDS=1.

**Comment by jhanssen** [comment]
A couple of ideas (not sure if any of these will lead anywhere), does the output of

```env | grep ltesdkroot```

reveal anything? If not, what about

```echo | /opt/gcc/x86_64/4.8.2a-1/bin/g++ -v -E - 2>&1 | grep ltesdkroot```

**Comment by okovko** [comment]
llvm-config doesn't override LIBCLANG_LIBDIR etc, I just needed to unset those. I set them to a different clang build that didn't work, in an earlier attempt to build.

Thank you!

**Comment by okovko** [comment]
How do I install this in ~/local, though?

**Comment by Andersbakken** [comment]
Sorry about the delay. This one completely slipped through the cracks for
me.

Yeah. GCC 4.4 doesn't support c++11 so it really be used to compile RTags.

Anders
