### ISSUE TITLE
Search -I paths for -include files when parsing compilation commands.

### ISSUE THREAD

**Issue by apodolsk** [Andersbakken/rtags#755]
When parsing compilation commands, rc -c discards `-include` arguments if they can only be found in a directory added to the search path by a `-I` argument. Clang and GCC both allow such `-include` args.

For example:
`git clone https://github.com/apodolsk/rtags_include_issue`
`make -nBk | rc -c -`

This gives me the following output, where -include "1.h" is discarded after parsing:

> Source::parse ( clang -I inc -include "1.h" ./1.c -o out
) => List<String>(clang, -I, inc, -include, 1.h, ./1.c, -o, out) /mnt/tea/code/scrap/rtags/test/rtags_include_issue/
Found compiler /usr/bin/clang-3.8 for clang
Parsed Source(s) successfully: List<Source>(Source(/usr/bin/clang -ferror-limit=0 -Wall -fspell-checking -Wno-unknown-warning-option -I/mnt/tea/code/scrap/rtags/test/rtags_include_issue/inc -isystem /usr/lib/clang/3.8.0/include/ /mnt/tea/code/scrap/rtags/test/rtags_include_issue/1.c Build: /mnt/tea/code/scrap/rtags/))
Starting process for 9 476741369965 0xc765c0
job got index data message 9 476741369965 0xc765c0
[100%] 1/1 23:22:27 /mnt/tea/code/scrap/rtags/test/rtags_include_issue/1.c in 11ms. (4 syms, 6 symNames, 0 includes, 1 of 1 files, symbols: 6 of 6, 323 cursors) (10/0/1ms). (priority 0)
Jobs took 0.03s. We're using 6mb of memory. 
Output from /mnt/tea/code/scrap/rtags/test/rtags_include_issue/1.c:
CI::parse: List<String>(-ferror-limit=0, -Wall, -fspell-checking, -Wno-unknown-warning-option, -I/mnt/tea/code/scrap/rtags/test/rtags_include_issue/inc, -isystem, /usr/lib/clang/3.8.0/include/)
CI::parse loading unit: clang "-ferror-limit=0" "-Wall" "-fspell-checking" "-Wno-unknown-warning-option" "-I/mnt/tea/code/scrap/rtags/test/rtags_include_issue/inc" "-isystem" "/usr/lib/clang/3.8.0/include/" /mnt/tea/code/scrap/rtags/test/rtags_include_issue/1.c true

Changing the makefile to -include "inc/1.h" causes 1.h to be correctly forwarded to clang.

**Comment by Andersbakken** [comment]
Sorry about the delay. I actually fixed this one a couple of weeks ago. It should work now.
