### ISSUE TITLE
option -J or --load-compilation-database not present in rc

### ISSUE THREAD

**Issue by deuscovrigus** [Andersbakken/rtags#760]
I am using clang version 3.8.1 (tags/RELEASE_381/final) and llvm-3.8.1 to build the latest version of rtags and although everything built fine, i can't parse a json file since the option in the client is no longer available.
i'm guessing it's related to line 63 of RClient.cpp

The reason i'm trying to build against the latest version of clang is that sometimes the system i'm trying to install rtags on doesn't have llvm-dev or libclang-dev preinstalled on the system so I sometimes have to build the latest version of these myself. 

It would be nice if somehow rtags had a independent build system where the dependencies (clang and llvm ) were cloned and build as a submodule. This would even allow rtags to be a complete independent solution in the elpa package manager itself.

**Comment by Andersbakken** [comment]
It's not a bad idea to have rtags build llvm/clang itself. I know ycm does
that. I might try to put something together. I did check in something that
just turns on compilation database support without version testing since it
seems it's been there so long that RTags wouldn't compile against the older
versions anyway.

Anders

**Comment by deuscovrigus** [comment]
Yes, there are different schools of thought with my dev friends and co-workers between ycm and rtags. I'm pushing rtags but a lot but the vim'ers using ycm can boast an OTB, plugin manager build of ycm, whereas I just quietly sip my coffee in shame as I try to download the clang sources and manage the build myself haha

**Comment by Nephyrin** [comment]
This might not be a great idea to have on by default -- the script is downloading a hard-coded tarball over HTTP, then running it's make commands.  This was rather surprising to me when I rebuilt today.

Most distros seem to already provide an appropriate llvm-dev package -- it might be better to have this opt-in, with a cmake note pointing you at it if your environment doesn't work, with appropriate warnings.

**Comment by deuscovrigus** [comment]
llvm-dev and libclang-dev are both needed and On ubuntu lts for example ( a very popular distro) they are not provided OTB, one needs to install them and that requires root.

**Comment by Andersbakken** [comment]
It is indeed a little funky. The main reason I decided to make it default is that most distros ship with rather ancient llvm/clangs. I definitely see the point about http. I didn't even realize they hosted the tarballs without ssl. Who does that these days? I added some sha512 verification to make it a little more safe. I'll consider switching the default again. I was inspired by similar projects like irony and youcompleteme where I believe it always builds llvm/clang

**Comment by Nephyrin** [comment]
Checking the file hashes definitely makes this feel safer.  Whether it should be default is more of a philosophical question.  I had to tweak the Arch PKGBUILD, but, thinking about it more, inconveniencing package managers is probably better than inconveniencing users who are building from source, and less equipped to figure out why things failed or how to change CMAKE options.

**Comment by Gei0r** [comment]
I would prefer it if the build process defaulted to using the system libraries, because downloading and building them takes a long time and there is no progress indication.

**Comment by deuscovrigus** [comment]
I think an out of the box solution that builds the required components is ideal. Experienced users who can't stand having duplicate libraries on their system can do the extra step of passing the -DRTAGS_NO_BUILD_CLANG while the neophytes can just choose to remain sheltered from concepts such as installing the development libraries of rtags' required packages (i.e. llvm-clang-dev)

One think to note though, is that one still needs root in order to install the rtags-llvmclang after the build, as the install script attempts to install all clang libs to /usr/local/rtags-llvm clang

**Comment by Andersbakken** [comment]
I just added a configure script that I hope makes the option a little more
discoverable.

Anders

**Comment by Andersbakken** [comment]
And now I changed the default back.
