### ISSUE TITLE
"No information for symbol" on rtags-display-summary

### ISSUE THREAD

**Issue by hyOzd** [Andersbakken/rtags#761]
When I call the `rtags-display-summary` on any symbol I get a simple tooltip saying "No information for symbol". Symbols are correctly indexed because I can jump to them and they are listed in auto completion candidates. I can even see the summary information in company's tooltip!

Here is the line from rdm log when I call `rtags-display-summary`:

    /usr/local/bin/rc --current-file=/home/user/path/main.c -b --no-color --declaration-only -N -f /home/user/path/main.c:133:15: -K

I'm using the latest version of rdm that I compiled from sources.

**Comment by Andersbakken** [comment]
Can you send a simple example that reproduces this? It seems to work for
me.

Anders

**Comment by hyOzd** [comment]
I'm sorry, I have re-installed my system during this weekend. Issue seems to be gone. Most of the things in this new installation has stayed the same though. Same rtags, exact same emacs config (just copied my .emacs.d). But emacs version has changed, maybe that fixed it.

I will close the issue for now.

**Comment by Andersbakken** [comment]
I guess that's okay :-)

Reopen if you're able to repro again.

Anders
