### ISSUE TITLE
Auto-complete on classes adds extra completions that are not members 

### ISSUE THREAD

**Issue by deuscovrigus** [Andersbakken/rtags#763]
So I am on commit 2f9442d Fix issue #760. It seems this was added so long ago that RTags wouldn't work with versions that predate it anyway.

and I noticed, that although my ac-sources is defined to be just ac-source-rtags as such:
ac-sources is a variable defined in `auto-complete.el'.
Its value is (ac-source-rtags)
I get completions that are not necessarily correct as seen in this screenshot
![screenshot from 2016-08-09 12-38-50](https://cloud.githubusercontent.com/assets/1252412/17526528/a11b52a2-5e35-11e6-9c13-2c81f7e38eeb.png)

All those members seem to be generic c-functions which are non-member functions. Can these be disabled?

**Comment by Andersbakken** [comment]
Completions are completely generated by libclang itself but this is very
likely a bug. Does it happen every time? Could you send me an example that
easily reproduces it?

Anders

**Comment by deuscovrigus** [comment]
Yes, and I think I found the problem too, it seems that the using keyword on standard namespaces, includes all of the keywords in those namespaces as completion candidates, regardless of their syntactical correctness. Attached I have a header and a main file and a CMakeLists.txt and two screenshots exemplifying my claim.
![with_namespaces](https://cloud.githubusercontent.com/assets/1252412/17675167/93ed9b1a-62f6-11e6-85ac-306691c9dba1.png)
![no_namespaces](https://cloud.githubusercontent.com/assets/1252412/17675166/93e6c6c8-62f6-11e6-919b-c38ebb58049a.png)
[simple_example.zip](https://github.com/Andersbakken/rtags/files/418704/simple_example.zip)

I also am experiencing input lag on c++ sources when i'm typing which I think is the cause of including a vast list of completion candidates with every stroke, as a result of these namespace inclusions

**Comment by Andersbakken** [comment]
Interesting. I'm not actually able to reproduce this.

Which clang version are you using?

Anders

**Comment by deuscovrigus** [comment]
So the rdm exec links against the packaged clang, but I got the same behavior when linking against my 3.8 clang on my system:
ldd rdm returns
linux-vdso.so.1 =>  (0x00007fff207f6000)
        libclang.so.3.8 => /usr/local/rtags-llvmclang/lib/libclang.so.3.8 (0x00007f0aae4f8000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f0aae13d000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0aadf20000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f0aadd06000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f0aadafd000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0aad7f4000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0aad5de000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0aad214000)
        /lib64/ld-linux-x86-64.so.2 (0x0000558253299000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0aad010000)
        libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f0aacde7000)

However, I think what might be different is that i'm using a newer gcc/libc toolchain that shipped with ubuntu 16.04 as per this version

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.

Maybe this might influence the outcome? I will try on my mac to see what the situation is.

**Comment by deuscovrigus** [comment]
Well I can confirm that I can reproduce this on a different linux machine with the 4.8 gcc toolchain, clang 3.8 (provided by rtags). Any idea where I can start to debug this?

**Comment by Andersbakken** [comment]
Honestly it's very likely a clang problem but let me try to get a similar
environment set up.

Anders

**Comment by deuscovrigus** [comment]
Ok I think I have some hints. I switched to clang 3.6 (same issues). However when I use company-mode instead of auto-complete mode completions work as expected. Also there is no input keyboard delay as i type a member/ class name in my cpp sources. I have double checked, the ac-sources are ac-source-rtags and it's defined in the rtags-ac.el file that comes with rtags
So if I were to narrow it down. it's in the current state of rtags-ac.el . Let me know if I can provide further feedback.

**Comment by Andersbakken** [comment]
Sorry about the delay. That's definitely an interesting data point. I'll
take another look.

Anders

**Comment by deuscovrigus** [comment]
So far i have been happy using company-complete and I haven't checked back to see if this bug still exists. I checked out rtags 2089bd4 and auto-complete Version: 20170124.1845 and still the same behavior persists. Were you ever able to reproduce this with my simple example?

**Comment by Andersbakken** [comment]
I have not actually. I don't honestly have a an auto-complete setup in my
.emacs ready. I don't actually use company mode either but I can atleast
turn it on with a simple switch :-)

Is company-mode working out okay for you?

Anders

**Comment by deuscovrigus** [comment]
Company works great. I switched from ac since this issue appeared

**Comment by Andersbakken** [comment]
Sounds good.

Anders
