### ISSUE TITLE
Unwanted -Wswitch causes fatal errors

### ISSUE THREAD

**Issue by azuk** [Andersbakken/rtags#765]
Consider the following example:
```
enum Hip
{
    HOP,
    HAP,
    HEP
};

int main(int argc, char** argv)
{
    Hip jee = HOP;

    switch (jee)
    {
    case HOP:
        return 1;
    }
    return 0;
}

/* Local Variables: */
/* compile-command: "g++ -Werror -Wfatal-errors -march=i686 -m32 -std=c++11 -o rtags-revtest rtags-revtest.cpp" */
/* End: */
```
g++ compiles that file without problems. But I get
```
00:07:09:929: Output from /.../rtags-revtest.cpp:
/.../rtags-revtest.cpp:12:13: fatal error: enumeration values 'HAP' and 'HEP' not handled in switch [-Wswitch]
```
to rtags log.

I'm running rdm with `--no-Wall` option just in case, although it seems that should not be necessary because `IndexerJob::encode()` appears to drop `-Wall` if `-Werror` is used.

I get many of those fatal errors in my actual project and I'm wondering if they cause rtags not to parse parts of the code that would have to parsed for me to not see random problems with `rtags-find-references-at-point` etc.

**Comment by azuk** [comment]
It seems that the same problem happens also because of `-Wcomment` and `-Wlogical-op-parentheses`. These all seem to be on by default in clang but not in gcc. If the compile command uses gcc, should rtags explicitly make warning options match those of gcc, or perhaps strip -Werror and -Wfatal-errors?

I disabled some warnings and indeed `rtags-find-references-at-point` etc. work better now.

**Comment by Andersbakken** [comment]
I don't really want to maintain what set of defaults gcc has for warnings
but turning off -Werror and -Wfatal-errors by default would be okay I think.

Anders

**Comment by Andersbakken** [comment]
I think it should work now. Please reopen if you find otherwise.
