### ISSUE TITLE
Compilation error in master 

### ISSUE THREAD

**Issue by joseph-churchill** [Andersbakken/rtags#766]
It looks like String::replace(String&, String&) returns void, not a bool.

[  1%] Building CXX object src/CMakeFiles/rtags.dir/ClangIndexer.cpp.o
In file included from /tmp/rtags/src/Diagnostic.h:22:0,
                 from /tmp/rtags/src/IndexDataMessage.h:19,
                 from /tmp/rtags/src/ClangIndexer.h:22,
                 from /tmp/rtags/src/ClangIndexer.cpp:17:
/tmp/rtags/src/Sandbox.h: In instantiation of ‘bool Sandbox::decode(T&, Sandbox::ReplaceMode) [with T = String; typename std::enable_if<std::is_convertible<String, T>::value, T>::type* <anonymous> = 0u]’:
/tmp/rtags/src/Symbol.h:206:31:   required from here
/tmp/rtags/src/Sandbox.h:120:40: error: void value not ignored as it ought to be
         return t.replace(encodedRoot, r);
                                        ^
/tmp/rtags/src/Sandbox.h: In instantiation of ‘bool Sandbox::encode(T&, Sandbox::ReplaceMode) [with T = String; typename std::enable_if<std::is_convertible<String, T>::value, T>::type* <anonymous> = 0u]’:
/tmp/rtags/src/ClangIndexer.cpp:1845:46:   required from here
/tmp/rtags/src/Sandbox.h:40:40: error: void value not ignored as it ought to be
         return t.replace(r, encodedRoot);
                                        ^
/tmp/rtags/src/Sandbox.h: In instantiation of ‘bool Sandbox::encode(T&, Sandbox::ReplaceMode) [with T = Path; typename std::enable_if<std::is_convertible<String, T>::value, T>::type* <anonymous> = 0u]’:
/tmp/rtags/src/Sandbox.h:111:11:   required from ‘T Sandbox::encoded(const T&, Sandbox::ReplaceMode) [with T = Path]’
/tmp/rtags/src/ClangIndexer.cpp:1855:48:   required from here
/tmp/rtags/src/Sandbox.h:40:40: error: void value not ignored as it ought to be

**Comment by Andersbakken** [comment]
Can you make sure your rct submodule is updated? I believe I changed it a
little while back.

E.g.

git submodule update

Anders

**Comment by joseph-churchill** [comment]
Yeah, that was it. Sorry, I didn't notice there were submodules.

**Comment by Andersbakken** [comment]
No worries. Let me know if you run into any other issues.

Anders
