### ISSUE TITLE
error in process filter: Wrong type argument: number-or-marker-p, skipped

### ISSUE THREAD

**Issue by edt** [Andersbakken/rtags#767]
Hi,

I currently often get the error 'rtags-parse-check-style: Wrong type argument: number-or-marker-p, skipped'

With toggle-debug-on-error enabled I get the following message:

    Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p skipped)
      rtags-handle-check-style("/home/edt/work/tiscamera/src/gstreamer-1.0/gsttcamautoexposure.cpp" (49 2 46 skipped ""))
      rtags-parse-check-style((("/home/edt/work/tiscamera/src/gstreamer-1.0/gsttcamautoexposure.cpp" (49 2 46 skipped "") (270 13 14 error "no matching function for call to 'g_slist_append': Semantic Issue") (271 13 14 error "no matching function for call to 'g_slist_append': Semantic Issue") (272 13 14 error "no matching function for call to 'g_slist_append': Semantic Issue") (273 13 14 error "no matching function for call to 'g_slist_append': Semantic Issue") (274 13 14 error "no matching function for call to 'g_slist_append': Semantic Issue") (275 13 14 error "no matching function for call to 'g_slist_append': Semantic Issue") (276 13 14 error "no matching function for call to 'g_slist_append': Semantic Issue") (277 13 14 error "no matching function for call to 'g_slist_append': Semantic Issue") (278 13 14 error "no matching function for call to 'g_slist_append': Semantic Issue") (827 38 20 error "no matching function for call to 'g_param_spec_boolean': Semantic Issue") (834 38 20 error "no matching function for call to 'g_param_spec_boolean': Semantic Issue") (841 38 19 error "no matching function for call to 'g_param_spec_double': Semantic Issue") (848 38 19 error "no matching function for call to 'g_param_spec_double': Semantic Issue") (855 38 16 error "no matching function for call to 'g_param_spec_int': Semantic Issue") (862 37 17 error "no matching function for call to 'g_param_spec_uint': Semantic Issue") (870 37 17 error "no matching function for call to 'g_param_spec_uint': Semantic Issue") (878 37 17 error "no matching function for call to 'g_param_spec_uint': Semantic Issue") (886 37 17 error "no matching function for call to 'g_param_spec_uint': Semantic Issue") (894 38 19 error "no matching function for call to 'g_param_spec_object': Semantic Issue") (1425 78 23 error "no matching function for call to 'gst_element_get_factory': Semantic Issue") (1430 55 7 error "assigning to 'GstElement *' (aka '_GstElement *') from incompatible type 'gpointer' (aka 'void *'): Semantic Issue") (1462 27 21 error "no matching function for call to 'gst_structure_get_int': Semantic Issue") (1463 27 21 error "no matching function for call to 'gst_structure_get_int': Semantic Issue"))))
      rtags-parse-diagnostics()
      rtags-diagnostics-process-filter(#<process RTags Diagnostics> "(list 'checkstyle (cons \"/home/edt/work/tiscamera/src/gstreamer-1.0/image_sampling.c\" (list (list 184 34 nil 'fixit \"suggest braces around initialization of subobject: Semantic Issue -Wmissing-braces\") (list 184 35 nil 'fixit \"did you mean '}'?\"))))\n")

C-h v rtags-last-check-style gives the following:

    rtags-last-check-style is a variable defined in `rtags.el'.
    Its value is shown below.

    Documentation:
    Not documented as a variable.

    Value:
    (("/home/edt/work/tiscamera/src/gstreamer-1.0/gsttcamautoexposure.cpp"
      (49 2 46 skipped "")
      (270 13 14 error "no matching function for call to 'g_slist_append': Semantic Issue")
      (271 13 14 error "no matching function for call to 'g_slist_append': Semantic Issue")
      (272 13 14 error "no matching function for call to 'g_slist_append': Semantic Issue")
      (273 13 14 error "no matching function for call to 'g_slist_append': Semantic Issue")
      (274 13 14 error "no matching function for call to 'g_slist_append': Semantic Issue")
      (275 13 14 error "no matching function for call to 'g_slist_append': Semantic Issue")
      (276 13 14 error "no matching function for call to 'g_slist_append': Semantic Issue")
      (277 13 14 error "no matching function for call to 'g_slist_append': Semantic Issue")
      (278 13 14 error "no matching function for call to 'g_slist_append': Semantic Issue")
      (827 38 20 error "no matching function for call to 'g_param_spec_boolean': Semantic Issue")
      (834 38 20 error "no matching function for call to 'g_param_spec_boolean': Semantic Issue")
      (841 38 19 error "no matching function for call to 'g_param_spec_double': Semantic Issue")
      (848 38 19 error "no matching function for call to 'g_param_spec_double': Semantic Issue")
      (855 38 16 error "no matching function for call to 'g_param_spec_int': Semantic Issue")
      (862 37 17 error "no matching function for call to 'g_param_spec_uint': Semantic Issue")
      (870 37 17 error "no matching function for call to 'g_param_spec_uint': Semantic Issue")
      (878 37 17 error "no matching function for call to 'g_param_spec_uint': Semantic Issue")
      (886 37 17 error "no matching function for call to 'g_param_spec_uint': Semantic Issue")
      (894 38 19 error "no matching function for call to 'g_param_spec_object': Semantic Issue")
      (1425 78 23 error "no matching function for call to 'gst_element_get_factory': Semantic Issue")
      (1430 55 7 error "assigning to 'GstElement *' (aka '_GstElement *') from incompatible type 'gpointer' (aka 'void *'): Semantic Issue")
      (1462 27 21 error "no matching function for call to 'gst_structure_get_int': Semantic Issue")
      (1463 27 21 error "no matching function for call to 'gst_structure_get_int': Semantic Issue")))

The function I called when this stack was created was 'org-agenda'.
The cpp file in question compiles and has previously not thrown any errors.

If you require any additional information, please let me know.

**Comment by Andersbakken** [comment]
Hm. Very odd. Are you able to reproduce this reliably? I don't really see how it could happen. If you happen to be able to reproduce I would love to see the actual output diagnostics rdm sent over.

Could you run this in a terminal:

rc -m --elisp 

It will print out elisp when diagnostics are sent over. It seems like a whole field is missing in the data and I don't understand how that could happen.

**Comment by edt** [comment]
Hi,

Sorry for the late reply. Since reporting the bug I am sadly unable to replicate the bug.
I tried to replicate possible circumstances under which this bug might have occurred, but without success.

Do you have any guesses what might cause this?
Should it happen again, what information should I record?

**Comment by Andersbakken** [comment]
Just this thing:

rc -m --elisp

It will print out elisp when diagnostics are sent over. It seems like a
whole field is missing in the data and I don't understand how that could
happen


Thanks


Maybe it's been fixed. Have you updated RTags since then?

Anders

**Comment by edt** [comment]
I tried updating after a while, but only after the bug seemed to have disappeared. I will open a new bug should it reappear. Sorry for not being able to provide more info.

**Comment by Andersbakken** [comment]
No worries. Thanks

Anders
