### ISSUE TITLE
I'd like to volunteer porting rtags to windows

### ISSUE THREAD

**Issue by Gei0r** [Andersbakken/rtags#770]
There have already been some people asking if rtags can be built on windows (current answer is no), but I would venture to try to make it portable.

I would start by porting rct, which I understand to be the principal abstraction layer behind rtags. Now my question is: Could you give me some pointers on where to start or some overview what portions are currently depending on unix/posix functions?

Is an issue report actually the correct way to discuss such topics or is there a better way, like a forum or something?

**Comment by jhanssen** [comment]
The major parts of rct that you'd have to have a Windows implementation is EventLoop, Process, Thread and Path. SocketClient/SocketServer and FileSystemWatcher would also need some work though I believe Windows is mostly BSD compatible in terms of socket calls and we have a win32 FileSystemWatcher for Cygwin that you could maybe reuse most parts of.

A brief description of the other parts,

EventLoop drives the daemon, there's a select backend that you might be able to use but it's slightly less efficient than the epoll (Linux) and kqueue (BSD/OS X) backends.

Process is responsible for launching the rp processes, it needs to be able to start a process and write data to stdin and read data from stdout/stderr.

Thread uses pthread so it will need some work, we used to use std::thread but there were limitations we couldn't easily work around so we went back to pthread.

We might make assumptions about the path separator in places so maybe start out with having a base drive that all paths gets written to and then translate / to \.

An issue is the right thing but we should probably have separate issues for rct (in the rct repo) and rtags.

**Comment by Andersbakken** [comment]
Agree with everything Jan Erik says. I also wanted to point out that we're
very excited about this and would love to accept your contribution. Proper
Windows support would be a great thing for RTags. It just so happens that
neither of the maintainers actually use Windows much.

**Comment by Gei0r** [comment]
Thanks for your kind replies. Some immediate questions:

- As I understand it, rtags is using unix pipes? What for? For windows, it would probably be best to use TCP, because Windows' named pipes are a pain.
- Is EventLoop used by rtags?

**Comment by Andersbakken** [comment]
We use pipes for two things:

1) To wake up from select/epoll/kqueue in EventLoop. Windows might have
another mechanism to do this.
2) In Process, to be able to get access to stderr, stdout and stdin. This
is just how process management works in unix and there's very likely a
better way to do it on Windows.

In other words. We only use pipes as an implementation detail inside these
classes so it should be possible to replace them with something else
without impacting RTags.

We do use EventLoop.

Anders

**Comment by Gei0r** [comment]
> 1) To wake up from select/epoll/kqueue in EventLoop. Windows might have another mechanism to do this.

On what event would you want to wake up from select?

Another question: Does rtags use MemoryMonitor?

**Comment by Andersbakken** [comment]
Hi

1) Mostly when posting an event to it from another thread.
2) We do use it but if it returns 0 that's perfectly fine, at least in the
short term.

regards

Anders

**Comment by EdVanDance** [comment]
@Gei0r I saw you made some changes on rct. I would love to use this on Windows as well. Can you tell something about your progress?

**Comment by Gei0r** [comment]
Some rct classes such as Path, String, etc. are already working on my win branch. The main thing left is the Process class. I've done some preliminary work on this, such as creating some test cases.

Also, you can't create a whole lib (dll, whatever) on windows yet.

Unfortunately, I've been very busy the last half year or so, so I really fell behind on that. Maybe I can do some more work next week.

**Comment by Red-Portal** [comment]
I heard about SIO_LOOPBACK_FAST_PATH in a conference once. If you used that for a windows IPC that would probably make a significant performance boost. Thanks for your work!

**Comment by Red-Portal** [comment]
@Gei0r Hi, I'd like to help if I can. Can you provide information of your current status? Which branch of your fork is the dev branch?

**Comment by Gei0r** [comment]
So here's a little status update:

I ported the most important classes to Windows so that a rct dll can be built using mingw64 from msys2. The corresponding [pull request](https://github.com/Andersbakken/rct/pull/58) has already been merged.

The next steps are to get rtags to compile on Windows. There are still a lot of "windows-foreign" headers in there. A special headache are format strings such as `%llx` which mingw does not accept (at least there are a lot of warnings).

You can monitor the progress on my "win" branches of rct and rtags. To date, I ported `FileMap.h`, which used unix/posix-specific functions for memory mapped files.

And after everything compiles, the final step will be to ensure that it's actually working. I don't know how much work there will be required once the compilation errors are taken care of.

**Comment by Gei0r** [comment]
@Red-Portal If you want to help, that would be greatly appreciated! Here are some steps you can take:

1. Install a mingw64 build environment with msys2.
2. Clone rct and build a dll. It *should* work out of the box, but experience tells me that there will be problems. You can of course ask me for help.
3. Clone my `win` branch of rtags and start a build process. There are plenty of compiler errors ;).
4. Fix these errors. One good starting point might be the `Filter` class. It uses `fnmatch()` to filter filenames. Windows doesn't have this function, but there is a similar Windows function called `PathMatchSpec` which should be usable. Make sure the implementation supports unicode filenames! (see `MemoryMappedFile` for an example on how to manage this)
5. Another great help would be to read through classes that produce errors, figure out what they do and write comments (boring, I know :P)

Whatever you do, drop a message beforehand so we don't perform the same work twice.

Cheers,
Gei0r

**Comment by Red-Portal** [comment]
@Gei0r  Great! I'll let you know when I do anything

**Comment by Red-Portal** [comment]
@Gei0r How may I contact you? Can you give me your email address or something?

**Comment by Red-Portal** [comment]
Gei0r, I can't find the 'win' branch of your fork. Did you push it to github?

**Comment by Gei0r** [comment]
Yeah, I forgot the `--all` flag. It's [up](https://github.com/Gei0r/rtags/tree/win) now.

**Comment by Red-Portal** [comment]
@Gei0r I don't know how I should contact you directly. Maybe commenting here is fine? While fetching your repository, this error occured.

`error: no such remote ref 8c830f6cbd3a0facccee6bb3b158b441c9b51ed2
Fetched in submodule path 'src/rct', but it did not contain 8c830f6cbd3a0facccee6bb3b158b441c9b51ed2. Direct fetching of that commit failed.`

I'll try to delete and add the submodules again. Would that be a problem?

**Comment by Red-Portal** [comment]
Seems like cloning your repo with `--recursive` avoids the problem. However cloning it without `--recursive` and then calling `submodule update --init` throws that error.

**Comment by Gei0r** [comment]
My commits have a valid e-mail address, you can reach me there.

I added my repo url to the `.gitmodules` file, maybe it works now as expected? I'm not really familiar with git submodules, I'll need to read the docs to get to know how they really work.

**Comment by rmhsilva** [comment]
@Gei0r, thanks for starting this. If I have some spare time soon I'll try help out, as this would be pretty useful!

**Comment by Red-Portal** [comment]
@Gei0r @rmhsilva  My current status. I'm really sorry but my semester started, and I became waaay overcumbered than what I expected. I'm really trying to make time but seems like I won't be able to do a lot for a while. Sorry for the inconvenience.
For participating, I suggest looking at rct. There are lots of places where a Win32 implementation is required.

**Comment by Gei0r** [comment]
@Red-Portal I know how it is when the semester hits you ;). Don't feel bad. School should be your top priority.

As for rct, I suggest that we concentrate on the parts that are required for rtags. I believe all that is needed is already ported to windows.

@rmhsilva Help is always appreciated!

**Comment by Red-Portal** [comment]
@Gei0r If more people jump in, maybe we should make a telegram chatroom or something. That would make communicating easily.

**Comment by Gei0r** [comment]
@Red-Portal I think this is a good idea. I installed telegram, but I need at least one other member to create a group (apparently, one-member groups are not a thing :P).

I sent you an E-Mail with my telegram contact information. Please add me as a contact so I can create a group.

Once the group is created, I can post a group link here so that anyone interested can join.

**Comment by Gei0r** [comment]
ok here is the link to the telegram group: 
https://t.me/joinchat/AAAAAAu8Fe36bKhnWyWZeA

Anyone interested is welcome to join! 

Please be aware that the telegram chat is not end-to-end encrypted and anyone can join. Therefore, all content posted there should be considered as visible to the public.

**Comment by Gei0r** [comment]
I added [a file containing todo points](https://github.com/Gei0r/rtags/blob/win/src/windows-todo.org) for porting rtags to windows.

The file contains some starting points for anyone who wants to help. Tell us in the telegram chat before you start so that we don't have two people working on the same problem.

**Comment by henriklaxhuber** [comment]
@Gei0r Have there been any attempts to run the RTags server in WSL? I've tried getting it working but I can't figure out how to properly override `rtags-executable-find` to run something like `bash -c "<exe>"` - my knowledge of elisp is still fairly limited. Other than that I have rtags compiled and running perfectly fine in WSL.

**Comment by fourier** [comment]
What is the status of rtags on Windows?

**Comment by Gei0r** [comment]
I'm sorry to report that I've stopped my efforts of porting rtags to windows. There has been quite some progress:
- Ported rct (rtags helper library) to windows
- added test cases to rtags to evaluate it working on both windows and linux
- made rtags compile on windows (mingw)
If you're interested you can look at my [rct](https://github.com/Gei0r/rct/tree/win) and [https://github.com/Gei0r/rtags/tree/win](rtags) (`win` branch).

However, I haven't worked on it for some time and I never got rtags to work completely on windows. So the code on my branches is significantly behind the parent repos.

If anyone's looking for the functionality rtags provides on windows, I recommend the [ccls](https://github.com/MaskRay/ccls) project, which is very active and has support for windows. It uses the language server protocol (lsp), which has massive support by the programming community at large, especially from Microsoft / VS Code.
Its concepts are eerily similar to rtags' ideas, so I think rtags was really ahead of its time ;-).

**Comment by vasanthaganeshk** [comment]
Would rtags work out of box with WSL2?

**Comment by Andersbakken** [comment]
Quite possibly. I haven't tried myself but I don't really see why not to be
honest.

Anders
