### ISSUE TITLE
compilation errors in boost::mpl

### ISSUE THREAD

**Issue by mpilman** [Andersbakken/rtags#772]
I am using rtags for a while now and love it so far. I now need to use boost::mpl for some parts of my work and I get strange compiler errors I do not understand...

I compile rtags manually with clang 3.8.1 which I got from homebrew. With the same clang version I use for rtags I can compile everything without any issues. But rtags seems to do something differently as I get thousands of errors on each file (and it will give up eventually).

Here are some of the errors:

> boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:18:5: warning: typedef requires a name [-Wmissing-declarations]
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:33:9: warning: typedef requires a name [-Wmissing-declarations]
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:49:9: warning: typedef requires a name [-Wmissing-declarations]
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:67:40: error: expected an identifier or template-id after '::'
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:84:40: error: expected an identifier or template-id after '::'
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:100:103: error: expected an identifier or template-id after '::'
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:100:103: error: expected a type
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:101:49: error: 'forward_step1' (aka 'int') is not a class, namespace, or enumeration
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:101:64: error: expected a qualified name after 'typename'
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:101:64: error: unknown type name 'iterator'; did you mean 'Iterator'?
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:89:16: note: 'Iterator' declared here
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:101:83: error: 'forward_step1' (aka 'int') is not a class, namespace, or enumeration
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:101:103: error: expected a qualified name after 'typename'
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:101:103: error: expected a type
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:102:49: error: 'forward_step2' (aka 'int') is not a class, namespace, or enumeration
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:102:64: error: expected a qualified name after 'typename'
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:102:64: error: unknown type name 'iterator'; did you mean 'Iterator'?
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:89:16: note: 'Iterator' declared here
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:102:83: error: 'forward_step2' (aka 'int') is not a class, namespace, or enumeration
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:102:103: error: expected a qualified name after 'typename'
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:102:103: error: expected a type
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:103:49: error: 'forward_step3' (aka 'int') is not a class, namespace, or enumeration
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:103:64: error: expected a qualified name after 'typename'
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:103:64: error: unknown type name 'iterator'; did you mean 'Iterator'?
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:89:16: note: 'Iterator' declared here
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:103:83: error: 'forward_step3' (aka 'int') is not a class, namespace, or enumeration
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:103:103: error: expected a qualified name after 'typename'
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:103:103: error: expected a type
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:107:20: error: 'forward_step4' (aka 'int') is not a class, namespace, or enumeration
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:107:35: error: expected a qualified name after 'typename'
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:107:35: error: unknown type name 'not_last'
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:116:9: error: expected member name or ';' after declaration specifiers
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:122:50: error: 'forward_step3' (aka 'int') is not a class, namespace, or enumeration
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:122:65: error: expected a qualified name after 'typename'
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:122:65: error: unknown type name 'iterator'; did you mean 'Iterator'?
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:89:16: note: 'Iterator' declared here
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:122:84: error: use of undeclared identifier 'backward_step4'
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:122:105: error: expected a qualified name after 'typename'
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:122:105: error: expected a type
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:123:50: error: 'forward_step2' (aka 'int') is not a class, namespace, or enumeration
boost/boost/mpl/aux_/preprocessed/gcc/iter_fold_if_impl.hpp:123:65: error: expected a qualified name after 'typename'

Is this a known issue or do I do something wrong?

**Comment by Andersbakken** [comment]
Is this an opensource project that I could try for myself? 

My suspicion is that it's because these headers are gcc specific. They likely have some that works for clagn as well but it might involve passing some additional flags etc to rtags.

**Comment by mpilman** [comment]
Sadly no, I can not give you the code (it is licensed and owned by another company). The boost code it crashes in gets also included when compiling with clang and there it compiles fine. I will try to reproduce the problem with some code that I can put online...

**Comment by mpilman** [comment]
I finally found the problem and it is not rtags related... It was in fact a C macro that did some strange things. Now it seems to work fine. I am sorry for bothering here (this is not my code - so I was not aware of all macros). You can close this issue.

**Comment by Andersbakken** [comment]
No worries. I'm glad it works.

Anders
