### ISSUE TITLE
Asking for symbol info with json or elisp flag results in crash.

### ISSUE THREAD

**Issue by dvush** [Andersbakken/rtags#774]
One should also enable "--symbol-info-include-references" flag to crash rdm process.
Brief debugging shows that problem is in 'src/Symbol.cpp:340' 
```
if (toStringFlags & IncludeReferences) {
                const auto references = project->findCallers(symbol);
                if (!references.isEmpty()) {
                    Value r;
                    for (const auto &ref : references) {
                        r.push_back(toValue(ref, NullFlags));
                    }
                    ret["references"] = r;
                }
}
```
`r.push_back(toValue(ref, NullFlags));` this one creates lambda that recursively searches for reference of reference and so on.
Probably one should change `if (toStringFlags & IncludeReferences)`  to `if (flags & IncludeReferences)` in this place and other similar flag checks in this file.

**Comment by Andersbakken** [comment]
That's correct. Thanks.

Should be fixed now.

**Comment by Andersbakken** [comment]
Should be fixed now. thanks for the report.

Anders
