### ISSUE TITLE
make install tries to install lua files

### ISSUE THREAD

**Issue by Nephyrin** [Andersbakken/rtags#776]
Now that lua is bundled as a submodule, `make install` is attempting to install the lua files, leading to conflicts with the actual package:

    rtags-git: /usr/bin/lua exists in filesystem
    rtags-git: /usr/bin/luac exists in filesystem
    rtags-git: /usr/include/lauxlib.h exists in filesystem
    rtags-git: /usr/include/lua.h exists in filesystem
    rtags-git: /usr/include/lua.hpp exists in filesystem
    rtags-git: /usr/include/luaconf.h exists in filesystem
    rtags-git: /usr/include/lualib.h exists in filesystem
    rtags-git: /usr/lib/liblua.so exists in filesystem

**Comment by Nephyrin** [comment]
More complete list of unexpected files:

    /usr/lib/liblua.so
    /usr/share/lua
    /usr/share/lua/doc
    /usr/share/lua/doc/lua.css
    /usr/share/lua/doc/contents.html
    /usr/share/lua/doc/lua.1
    /usr/share/lua/doc/luac.1
    /usr/share/lua/doc/osi-certified-72x60.png
    /usr/share/lua/doc/readme.html
    /usr/share/lua/doc/manual.css
    /usr/share/lua/doc/index.css
    /usr/share/lua/doc/manual.html
    /usr/share/lua/doc/logo.gif
    /usr/share/lua/etc
    /usr/share/lua/etc/lua.ico
    /usr/share/lua/etc/lua_lang.ico
    /usr/share/lua/README.md
    /usr/bin/lua
    /usr/bin/luac
    /usr/include
    /usr/include/lua.hpp
    /usr/include/lauxlib.h
    /usr/include/lualib.h
    /usr/include/luaconf.h
    /usr/include/lua.h

**Comment by kvaneesh** [comment]
Can we make it optional. Is there a documentation on lua interface. What it is used for ? I use rtags only within emacs and I am not sure what will lua scripting be used for ?

**Comment by Andersbakken** [comment]
It's not installing anymore. I'll think about making it optional.

Anders

On Fri, Aug 26, 2016 at 10:21 AM, Aneesh Kumar K.V <notifications@github.com
