### ISSUE TITLE
Rc error output written to current buffer

### ISSUE THREAD

**Issue by ambihelical** [Andersbakken/rtags#779]
The following happens everytime I perform the following actions: 

1)  create a new .h or .cpp buffer
2)  add some text
3) wait a few seconds 
Note: at no point is the file saved on disk yet. 

 I get the following text **added to the buffer** (actual file path changed here to ==path to file==):

```
Can't open [==path to file==] for reading
unexpected option -- '--no-color'
Try 'rc --help' for more information.
```

I have rtags-set-periodic-reparse-timeout set to 2, and it seems to happen after about that interval. 

Rtags built from source at commit  c93f47f9f67878352c33d31243b5e285623554c7
rc says it is version 2.4.100
rtags emacs package version is 20160825.1435 from melpa

Here is my rtags config minus keybindings:

```
(use-package rtags
  :commands ( rtags-location-stack-back rtags-location-stack-forward )
  :init
  (progn
    (setq rtags-autostart-diagnostics t
          rtags-use-helm t
          rtags-tooltips-enabled nil
          rtags-display-current-error-as-message nil
          rtags-process-flags "--config ~/.config/rtags/config"
          rtags-completions-enabled t)
    (add-hook 'c-mode-common-hook #'rtags-start-process-unless-running)
    (add-hook 'c-mode-common-hook #'me:flycheck-rtags-setup)
    (add-hook 'company-mode-hook  #'me:company-rtags-setup))
  :config
  (progn
    (rtags-diagnostics)
    (rtags-set-periodic-reparse-timeout 2)
    (rtags-enable-standard-keybindings))
  :diminish rtags-mode
 )

```

**Comment by Andersbakken** [comment]
Weird. I can't quite seem to reproduce it but I see what's going on and I
think it should be fixed now.

Can you check after my last two fixes?

Anders

**Comment by ambihelical** [comment]
I don't get the text in the buffer anymore. But there is an error message now:

`Error running timer `rtags-reparse-file-if-needed': (wrong-type-argument stringp nil)`

**Comment by Andersbakken** [comment]
Hm. I don't seem to get that one. Can you see if you can get a stack trace
from it or maybe try to catch it in edebug?

**Comment by Andersbakken** [comment]
Strike that. I got it now. The last fix should take care of that I think.

**Comment by ambihelical** [comment]
I tried compiling HEAD but got link errors.  It looks like there were extensive WIP changes after this fix, so I'll try backing off from those tomorrow, unless you have it fixed.  Or maybe I made a stupid mistake, so tomorrow I'll try it again in any case when I'm fresher. 

Anyway the errors were:

```
librtags.a(Project.cpp.o): In function `Project::init()::{lambda()#3}::operator()() const':
/home/work/extern/rtags/src/Project.cpp:365: undefined reference to `Project::index(unsigned int, Flags<IndexerJob::Flag>)'
librtags.a(Project.cpp.o): In function `Project::init()::{lambda()#3}::operator()() const':
/home/work/extern/rtags/src/Project.cpp:365: undefined reference to `Project::index(unsigned int, Flags<IndexerJob::Flag>)'
librtags.a(Project.cpp.o): In function `Project::init()::{lambda()#3}::operator()() const':
/home/work/extern/rtags/src/Project.cpp:365: undefined reference to `Project::index(unsigned int, Flags<IndexerJob::Flag>)'
```

**Comment by ambihelical** [comment]
My previous comment is probably more related to #781, but in any case, rtags isn't compiling at the moment.

**Comment by ambihelical** [comment]
After updating the melpa package, the error seems to be gone.

**Comment by Andersbakken** [comment]
Glad to hear. Let me know if any new problems show up.
