### ISSUE TITLE
Auto-completition list is embeded in source code instead of popup list

### ISSUE THREAD

**Issue by handrake0724** [Andersbakken/rtags#780]
I have followed the instruction stated here.
I think rdm is working fine and communicating with emacs (24.5.1).
Problem is that auto-completition list like member variables is embed in the source code instead of showing in a popup window. As shown below figures, rtags is getting completion list correctly but the list is inserted into source code buffer.

![emacs tardis_003](https://cloud.githubusercontent.com/assets/18005991/18221846/9e8183d8-71c0-11e6-8288-15156a2ec5ea.png)

![emacs tardis_004](https://cloud.githubusercontent.com/assets/18005991/18221843/8f5f9034-71c0-11e6-8761-f2fca3152fd4.png)
my rtags setup is as follows:

;; company-mode
(require 'company)
(global-company-mode)

;; rtags
(require 'rtags)
(require 'company-rtags)

(add-hook 'c-mode-common-hook 'rtags-start-process-unless-running)
(add-hook 'c++-mode-common-hook 'rtags-start-process-unless-running)
(add-hook 'c++-mode-hook 'flycheck-mode)
(add-hook 'c-mode-hook 'flycheck-mode)

(setq rtags-completions-enabled t)
(eval-after-load 'company
  '(add-to-list
    'company-backends 'company-rtags))
(setq rtags-autostart-diagnostics t)
(setq rtags-use-helm t)
(rtags-enable-standard-keybindings)
(rtags-diagnostics)
(require 'flycheck-rtags)

any help would be grateful.

**Comment by handrake0724** [comment]
latest rtags (20160902.1359) + additional install of auto-complete did the magic.

**Comment by Andersbakken** [comment]
Hm. Do you have popup installed?

This sounds more like a company-problem than an rtags problem to be honest.
Does it happen with company-mode in elisp buffers as well?

Anders

**Comment by handrake0724** [comment]
Yes, popup has been installed but it did not work.
After installed auto-complete mode, I could get completion list.

**Comment by Andersbakken** [comment]
Good to hear. Let me know if you run into other problems.

Anders
