### ISSUE TITLE
rtags-create-doxygen-comment doesn't work

### ISSUE THREAD

**Issue by ambihelical** [Andersbakken/rtags#781]
Using this command always prints "Can't find symbol here", even though other "at point" commands seem to have no problem with the C and C++ methods I've tried.

rc --version -> 2.5.101
HEAD commit ->  c56307746a09429aede776ac3a8d9e3eb11dfbec
melpa version -> rtags-20160902.1059

**Comment by Andersbakken** [comment]
There were apparently a number of things wrong with this function. It seems to work for me now after some changes. Can you verify?

**Comment by ambihelical** [comment]
I tried compiling HEAD but got link errors. It looks like there were extensive WIP changes after this fix, so I'll try backing off from those tomorrow, unless you have it fixed. Or maybe I made a stupid mistake, so tomorrow I'll try it again in any case when I'm fresher.

Anyway the errors were:

```
librtags.a(Project.cpp.o): In function `Project::init()::{lambda()#3}::operator()() const':
/home/work/extern/rtags/src/Project.cpp:365: undefined reference to `Project::index(unsigned int, Flags<IndexerJob::Flag>)'
librtags.a(Project.cpp.o): In function `Project::init()::{lambda()#3}::operator()() const':
/home/work/extern/rtags/src/Project.cpp:365: undefined reference to `Project::index(unsigned int, Flags<IndexerJob::Flag>)'
librtags.a(Project.cpp.o): In function `Project::init()::{lambda()#3}::operator()() const':
/home/work/extern/rtags/src/Project.cpp:365: undefined reference to `Project::index(unsigned int, Flags<IndexerJob::Flag>)'

```

**Comment by Andersbakken** [comment]
Oops. Wrong push there. -f has arrived. It should compile and link now.

Anders

**Comment by ambihelical** [comment]
Thanks!  After adding yasnippet to my config, it expands out the comment.  
It would be great to have c++ style format comments (///) as an option, should I open an issue?

**Comment by Andersbakken** [comment]
Sure. Please do.

Anders

**Comment by ambihelical** [comment]
Done. #786.  I may give it a stab, but no promises.

**Comment by Andersbakken** [comment]
Feel free to. I think it should be relatively simple with a defcustom.

Anders
