### ISSUE TITLE
rtags compilation problem. is it related to lua?

### ISSUE THREAD

**Issue by Mafeuser** [Andersbakken/rtags#783]
Hallo rtags team.

I have trouble compiling rtags. The problem seems to be related to lua.

Compilation started at Mon Sep  5 13:35:00
```
cmake -DLIBCLANG_LLVM_CONFIG_EXECUTABLE=/usr/local/ashare/llvm/current/bin/llvm-config .. && make
-- The C compiler identification is GNU 5.2.1
-- The CXX compiler identification is GNU 5.2.1
-- Check for working C compiler: /opt/rh/devtoolset-4/root/usr/bin/cc
-- Check for working C compiler: /opt/rh/devtoolset-4/root/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/rh/devtoolset-4/root/usr/bin/c++
-- Check for working CXX compiler: /opt/rh/devtoolset-4/root/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using Clang version 3.8.1 from /usr/local/ashare/llvm/llvm-3.8.1.cslux/lib64 with CXXFLAGS -I/usr/local/ashare/llvm/llvm-3.8.1.cslux/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-- Found LibClang: /usr/local/ashare/llvm/llvm-3.8.1.cslux/lib64/libclang.so  
-- Looking for backtrace
-- Looking for backtrace - found
-- Looking for CLOCK_MONOTONIC_RAW
-- Looking for CLOCK_MONOTONIC_RAW - found
-- Looking for CLOCK_MONOTONIC
-- Looking for CLOCK_MONOTONIC - found
-- Looking for mach_absolute_time
-- Looking for mach_absolute_time - not found
-- Looking for inotify_init
-- Looking for inotify_init - found
-- Looking for kqueue
-- Looking for kqueue - not found
-- Looking for epoll_wait
-- Looking for epoll_wait - found
-- Looking for select
-- Looking for select - found
-- Looking for FD_CLOEXEC
-- Looking for FD_CLOEXEC - found
-- Looking for SO_NOSIGPIPE
-- Looking for SO_NOSIGPIPE - not found
-- Looking for MSG_NOSIGNAL
-- Looking for MSG_NOSIGNAL - found
-- Looking for GetLogicalProcessorInformation
-- Looking for GetLogicalProcessorInformation - not found
-- Looking for SCHED_IDLE
-- Looking for SCHED_IDLE - found
-- Looking for SHM_DEST
-- Looking for SHM_DEST - found
-- Performing Test HAVE_STATMTIM
-- Performing Test HAVE_STATMTIM - Success
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7") 
-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.1e") 
-- Performing Test HAVE_CXX11
-- Performing Test HAVE_CXX11 - Success
-- Performing Test HAVE_UNORDERDED_MAP_WORKING_MOVE_CONSTRUCTOR
-- Performing Test HAVE_UNORDERDED_MAP_WORKING_MOVE_CONSTRUCTOR - Success
-- 
-- The following OPTIONAL packages have been found:

 * ZLIB
 * OpenSSL
 * PkgConfig , helper tool , <https://www.freedesktop.org/wiki/Software/pkg-config/>
   We use it to get the bash completion installation path, and replace the prefix with the value of CMAKE_INSTALL_PREFIX.

-- The following REQUIRED packages have been found:

 * LibClang

-- Configuring done
-- Generating done
-- Build files have been written to: /path/to/rtags/rtags-c563077
Scanning dependencies of target lua
[  1%] Creating directories for 'lua'
[  2%] No download step for 'lua'
[  3%] No patch step for 'lua'
[  4%] No update step for 'lua'
[  5%] Performing configure step for 'lua'
CMake Error: The source directory "/path/to/rtags/src/lua" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
make[2]: *** [src/lua-prefix/src/lua-stamp/lua-configure] Error 1
make[1]: *** [src/CMakeFiles/lua.dir/all] Error 2
make: *** [all] Error 2

Compilation exited abnormally with code 2 at Mon Sep  5 13:35:02
```

because version of lua package from my system is 5.1 I've downloaded lua 5.3 binary and compiled again with 2 new flags:

```
Compilation started at Mon Sep  5 13:45:46

cmake -DLIBCLANG_LLVM_CONFIG_EXECUTABLE=/usr/local/ashare/llvm/current/bin/llvm-config -DLUA_INCLUDE_DIR=/path/to/rtags/lua-external/include -DLUA_LIBRARY=/path/to/rtags/lua-external/liblua53.a .. && make
-- The C compiler identification is GNU 5.2.1
-- The CXX compiler identification is GNU 5.2.1
-- Check for working C compiler: /opt/rh/devtoolset-4/root/usr/bin/cc
-- Check for working C compiler: /opt/rh/devtoolset-4/root/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/rh/devtoolset-4/root/usr/bin/c++
-- Check for working CXX compiler: /opt/rh/devtoolset-4/root/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using Clang version 3.8.1 from /usr/local/ashare/llvm/llvm-3.8.1.cslux/lib64 with CXXFLAGS -I/usr/local/ashare/llvm/llvm-3.8.1.cslux/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-- Found LibClang: /usr/local/ashare/llvm/llvm-3.8.1.cslux/lib64/libclang.so  
-- Looking for backtrace
-- Looking for backtrace - found
-- Looking for CLOCK_MONOTONIC_RAW
-- Looking for CLOCK_MONOTONIC_RAW - found
-- Looking for CLOCK_MONOTONIC
-- Looking for CLOCK_MONOTONIC - found
-- Looking for mach_absolute_time
-- Looking for mach_absolute_time - not found
-- Looking for inotify_init
-- Looking for inotify_init - found
-- Looking for kqueue
-- Looking for kqueue - not found
-- Looking for epoll_wait
-- Looking for epoll_wait - found
-- Looking for select
-- Looking for select - found
-- Looking for FD_CLOEXEC
-- Looking for FD_CLOEXEC - found
-- Looking for SO_NOSIGPIPE
-- Looking for SO_NOSIGPIPE - not found
-- Looking for MSG_NOSIGNAL
-- Looking for MSG_NOSIGNAL - found
-- Looking for GetLogicalProcessorInformation
-- Looking for GetLogicalProcessorInformation - not found
-- Looking for SCHED_IDLE
-- Looking for SCHED_IDLE - found
-- Looking for SHM_DEST
-- Looking for SHM_DEST - found
-- Performing Test HAVE_STATMTIM
-- Performing Test HAVE_STATMTIM - Success
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7") 
-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.1e") 
-- Performing Test HAVE_CXX11
-- Performing Test HAVE_CXX11 - Success
-- Performing Test HAVE_UNORDERDED_MAP_WORKING_MOVE_CONSTRUCTOR
-- Performing Test HAVE_UNORDERDED_MAP_WORKING_MOVE_CONSTRUCTOR - Success
-- 
-- The following OPTIONAL packages have been found:

 * ZLIB
 * OpenSSL
 * PkgConfig , helper tool , <https://www.freedesktop.org/wiki/Software/pkg-config/>
   We use it to get the bash completion installation path, and replace the prefix with the value of CMAKE_INSTALL_PREFIX.

-- The following REQUIRED packages have been found:

 * LibClang

-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    LUA_INCLUDE_DIR
    LUA_LIBRARY


-- Build files have been written to: /path/to/rtags/rtags-c563077
Scanning dependencies of target lua
[  1%] Creating directories for 'lua'
[  2%] No download step for 'lua'
[  3%] No patch step for 'lua'
[  4%] No update step for 'lua'
[  5%] Performing configure step for 'lua'
CMake Error: The source directory "/path/to/rtags/src/lua" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
make[2]: *** [src/lua-prefix/src/lua-stamp/lua-configure] Error 1
make[1]: *** [src/CMakeFiles/lua.dir/all] Error 2
make: *** [all] Error 2

Compilation exited abnormally with code 2 at Mon Sep  5 13:45:48
```

/path/to/rtags/src/lua directory is empty.

regards

**Comment by cslux** [comment]
Run "git submodule init && git submodule update", to fetch the LUA submodule, after that, you should be able to compile rtags. 

regards, 
Christian 

On September 5, 2016 1:47:03 PM GMT+02:00, Mafeuser <notifications@github.com> wrote:
>Hallo rtags team.
>
>I have trouble compiling rtags. The problem seems to be related to lua.
>
>Compilation started at Mon Sep  5 13:35:00
>```
>cmake
>-DLIBCLANG_LLVM_CONFIG_EXECUTABLE=/usr/local/ashare/llvm/current/bin/llvm-config
>.. && make
>-- The C compiler identification is GNU 5.2.1
>-- The CXX compiler identification is GNU 5.2.1
>-- Check for working C compiler: /opt/rh/devtoolset-4/root/usr/bin/cc
>-- Check for working C compiler: /opt/rh/devtoolset-4/root/usr/bin/cc
>-- works
>-- Detecting C compiler ABI info
>-- Detecting C compiler ABI info - done
>-- Detecting C compile features
>-- Detecting C compile features - done
>-- Check for working CXX compiler:
>/opt/rh/devtoolset-4/root/usr/bin/c++
>-- Check for working CXX compiler:
>/opt/rh/devtoolset-4/root/usr/bin/c++ -- works
>-- Detecting CXX compiler ABI info
>-- Detecting CXX compiler ABI info - done
>-- Detecting CXX compile features
>-- Detecting CXX compile features - done
>-- Using Clang version 3.8.1 from
>/usr/local/ashare/llvm/llvm-3.8.1.cslux/lib64 with CXXFLAGS
>-I/usr/local/ashare/llvm/llvm-3.8.1.cslux/include -D_GNU_SOURCE
>-D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
>-- Found LibClang:
>/usr/local/ashare/llvm/llvm-3.8.1.cslux/lib64/libclang.so  
>-- Looking for backtrace
>-- Looking for backtrace - found
>-- Looking for CLOCK_MONOTONIC_RAW
>-- Looking for CLOCK_MONOTONIC_RAW - found
>-- Looking for CLOCK_MONOTONIC
>-- Looking for CLOCK_MONOTONIC - found
>-- Looking for mach_absolute_time
>-- Looking for mach_absolute_time - not found
>-- Looking for inotify_init
>-- Looking for inotify_init - found
>-- Looking for kqueue
>-- Looking for kqueue - not found
>-- Looking for epoll_wait
>-- Looking for epoll_wait - found
>-- Looking for select
>-- Looking for select - found
>-- Looking for FD_CLOEXEC
>-- Looking for FD_CLOEXEC - found
>-- Looking for SO_NOSIGPIPE
>-- Looking for SO_NOSIGPIPE - not found
>-- Looking for MSG_NOSIGNAL
>-- Looking for MSG_NOSIGNAL - found
>-- Looking for GetLogicalProcessorInformation
>-- Looking for GetLogicalProcessorInformation - not found
>-- Looking for SCHED_IDLE
>-- Looking for SCHED_IDLE - found
>-- Looking for SHM_DEST
>-- Looking for SHM_DEST - found
>-- Performing Test HAVE_STATMTIM
>-- Performing Test HAVE_STATMTIM - Success
>-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7") 
>-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found
>version "1.0.1e") 
>-- Performing Test HAVE_CXX11
>-- Performing Test HAVE_CXX11 - Success
>-- Performing Test HAVE_UNORDERDED_MAP_WORKING_MOVE_CONSTRUCTOR
>-- Performing Test HAVE_UNORDERDED_MAP_WORKING_MOVE_CONSTRUCTOR -
>Success
>-- 
>-- The following OPTIONAL packages have been found:
>
> * ZLIB
> * OpenSSL
>* PkgConfig , helper tool ,
><https://www.freedesktop.org/wiki/Software/pkg-config/>
>We use it to get the bash completion installation path, and replace the
>prefix with the value of CMAKE_INSTALL_PREFIX.
>
>-- The following REQUIRED packages have been found:
>
> * LibClang
>
>-- Configuring done
>-- Generating done
>-- Build files have been written to: /path/to/rtags/rtags-c563077
>Scanning dependencies of target lua
>[  1%] Creating directories for 'lua'
>[  2%] No download step for 'lua'
>[  3%] No patch step for 'lua'
>[  4%] No update step for 'lua'
>[  5%] Performing configure step for 'lua'
>CMake Error: The source directory "/path/to/rtags/src/lua" does not
>appear to contain CMakeLists.txt.
>Specify --help for usage, or press the help button on the CMake GUI.
>make[2]: *** [src/lua-prefix/src/lua-stamp/lua-configure] Error 1
>make[1]: *** [src/CMakeFiles/lua.dir/all] Error 2
>make: *** [all] Error 2
>
>Compilation exited abnormally with code 2 at Mon Sep  5 13:35:02
>```
>
>because version of lua package from my system is 5.1 I've downloaded
>lua 5.3 binary and compiled again with 2 new flags:
>
>```
>Compilation started at Mon Sep  5 13:45:46
>
>cmake
>-DLIBCLANG_LLVM_CONFIG_EXECUTABLE=/usr/local/ashare/llvm/current/bin/llvm-config
>-DLUA_INCLUDE_DIR=/path/to/rtags/lua-external/include
>-DLUA_LIBRARY=/path/to/rtags/lua-external/liblua53.a .. && make
>-- The C compiler identification is GNU 5.2.1
>-- The CXX compiler identification is GNU 5.2.1
>-- Check for working C compiler: /opt/rh/devtoolset-4/root/usr/bin/cc
>-- Check for working C compiler: /opt/rh/devtoolset-4/root/usr/bin/cc
>-- works
>-- Detecting C compiler ABI info
>-- Detecting C compiler ABI info - done
>-- Detecting C compile features
>-- Detecting C compile features - done
>-- Check for working CXX compiler:
>/opt/rh/devtoolset-4/root/usr/bin/c++
>-- Check for working CXX compiler:
>/opt/rh/devtoolset-4/root/usr/bin/c++ -- works
>-- Detecting CXX compiler ABI info
>-- Detecting CXX compiler ABI info - done
>-- Detecting CXX compile features
>-- Detecting CXX compile features - done
>-- Using Clang version 3.8.1 from
>/usr/local/ashare/llvm/llvm-3.8.1.cslux/lib64 with CXXFLAGS
>-I/usr/local/ashare/llvm/llvm-3.8.1.cslux/include -D_GNU_SOURCE
>-D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
>-- Found LibClang:
>/usr/local/ashare/llvm/llvm-3.8.1.cslux/lib64/libclang.so  
>-- Looking for backtrace
>-- Looking for backtrace - found
>-- Looking for CLOCK_MONOTONIC_RAW
>-- Looking for CLOCK_MONOTONIC_RAW - found
>-- Looking for CLOCK_MONOTONIC
>-- Looking for CLOCK_MONOTONIC - found
>-- Looking for mach_absolute_time
>-- Looking for mach_absolute_time - not found
>-- Looking for inotify_init
>-- Looking for inotify_init - found
>-- Looking for kqueue
>-- Looking for kqueue - not found
>-- Looking for epoll_wait
>-- Looking for epoll_wait - found
>-- Looking for select
>-- Looking for select - found
>-- Looking for FD_CLOEXEC
>-- Looking for FD_CLOEXEC - found
>-- Looking for SO_NOSIGPIPE
>-- Looking for SO_NOSIGPIPE - not found
>-- Looking for MSG_NOSIGNAL
>-- Looking for MSG_NOSIGNAL - found
>-- Looking for GetLogicalProcessorInformation
>-- Looking for GetLogicalProcessorInformation - not found
>-- Looking for SCHED_IDLE
>-- Looking for SCHED_IDLE - found
>-- Looking for SHM_DEST
>-- Looking for SHM_DEST - found
>-- Performing Test HAVE_STATMTIM
>-- Performing Test HAVE_STATMTIM - Success
>-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7") 
>-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found
>version "1.0.1e") 
>-- Performing Test HAVE_CXX11
>-- Performing Test HAVE_CXX11 - Success
>-- Performing Test HAVE_UNORDERDED_MAP_WORKING_MOVE_CONSTRUCTOR
>-- Performing Test HAVE_UNORDERDED_MAP_WORKING_MOVE_CONSTRUCTOR -
>Success
>-- 
>-- The following OPTIONAL packages have been found:
>
> * ZLIB
> * OpenSSL
>* PkgConfig , helper tool ,
><https://www.freedesktop.org/wiki/Software/pkg-config/>
>We use it to get the bash completion installation path, and replace the
>prefix with the value of CMAKE_INSTALL_PREFIX.
>
>-- The following REQUIRED packages have been found:
>
> * LibClang
>
>-- Configuring done
>-- Generating done
>CMake Warning:
>  Manually-specified variables were not used by the project:
>
>    LUA_INCLUDE_DIR
>    LUA_LIBRARY
>
>
>-- Build files have been written to: /path/to/rtags/rtags-c563077
>Scanning dependencies of target lua
>[  1%] Creating directories for 'lua'
>[  2%] No download step for 'lua'
>[  3%] No patch step for 'lua'
>[  4%] No update step for 'lua'
>[  5%] Performing configure step for 'lua'
>CMake Error: The source directory "/path/to/rtags/src/lua" does not
>appear to contain CMakeLists.txt.
>Specify --help for usage, or press the help button on the CMake GUI.
>make[2]: *** [src/lua-prefix/src/lua-stamp/lua-configure] Error 1
>make[1]: *** [src/CMakeFiles/lua.dir/all] Error 2
>make: *** [all] Error 2
>
>Compilation exited abnormally with code 2 at Mon Sep  5 13:45:48
>```
>
>/path/to/rtags/src/lua directory is empty.
>
>regards
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Andersbakken/rtags/issues/783

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Mafeuser** [comment]
@cslux, it did the job! Thank You for help.

regards,

**Comment by cslux** [comment]
my pleasure

regards,
Christian
