### ISSUE TITLE
dramatic increase of definitions/references misses during code browsing.

### ISSUE THREAD

**Issue by Mafeuser** [Andersbakken/rtags#784]
Hallo rtags Team.

I'm using rtags with not that small project (~1700 files).

Since a few weeks I'm observing dramatic of misses of following functions:
rtags-find-symbol-at-point, rtags-find-references-at-point.

Problem started with rtags-801e1c2 and persists till now. The last version I've checked is rtags-c563077.

I've also reverted commit 801e1c2 from c563077 and it rtags started working again.

This is my revert:
Unstaged changes (1)
modified   src/rdm.cpp

```
@@ -311,7 +311,7 @@ int main(int argc, char** argv)
     serverOpts.rpConnectTimeout = DEFAULT_RP_CONNECT_TIMEOUT;
     serverOpts.rpConnectAttempts = DEFAULT_RP_CONNECT_ATTEMPTS;
     serverOpts.maxFileMapScopeCacheSize = DEFAULT_RDM_MAX_FILE_MAP_CACHE_SIZE;
-    serverOpts.errorLimit = DEFAULT_ERROR_LIMIT;
+    //serverOpts.errorLimit = DEFAULT_ERROR_LIMIT;
     serverOpts.rpNiceValue = INT_MIN;
     serverOpts.options = Server::Wall|Server::SpellChecking;
     serverOpts.maxCrashCount = DEFAULT_MAX_CRASH_COUNT;
```

regards

**Comment by Andersbakken** [comment]
Hi

Are you by any chance seeing a lot of errors reported by RTags during
parsing?

You can change the error limit to unlimited by putting this in your ~/.rdmrc

--error-limit 0

I wonder if maybe this is hitting a lot of people though. I should possibly
change it back or at least make it higher than 50. Can you check if this
remedies the situation for you?

Anders

**Comment by Mafeuser** [comment]
yes, there are many errors. huge amount comes from:
/opt/rh/devtoolset-4/root/usr/lib/gcc/x86_64-redhat-linux/5.2.1/include/........

adding '--error-limit=0' to command line of rdm did the job.

I couldn't manage through ~/.rdm file.

regards

**Comment by Andersbakken** [comment]
It needs to be ~/.rdmrc not ~/.rdm btw. Does that work?

Anders

**Comment by Mafeuser** [comment]
yes, that works too. sorry for the noise about ~/.rdm.

**Comment by Andersbakken** [comment]
No problem. I'll consider if the limit should be upped or set to unlimited.

Anders
