### ISSUE TITLE
RTags.el uses 100% CPU for minutes at a time when opening a large (644k) header file

### ISSUE THREAD

**Issue by jlargentaye** [Andersbakken/rtags#790]
I sometimes need to look at huge (~644k bytes, ~20k lines) header files that describe hardware. When doing so, Emacs freezes up for minutes at a time. ^G is ineffective. System profiler shows that Emacs is busy executing Elisp code. Emacs Lisp CPU profiler shows its 98% in RTags code. Memory usage is nothing out of the ordinary.

In fact, just putting focus on the already-opened buffer is enough to send Emacs in a tizzy.

I'm not sure how I can provide a useful test case. I can't provide any of the header files that expose this issue (they're very proprietary), and I'm not sure how to generate one that could expose it. Hopefully the attached profiler is a useful first step?

```
- rtags-diagnostics-process-filter                             134207  99%
 - rtags-parse-diagnostics                                     134207  99%
  - rtags-parse-check-style                                    134198  99%
   - rtags-handle-check-style                                  129695  95%
    - rtags-offset                                              44286  32%
     - rtags-point-multibyte                                    41959  30%
        rtags-buffer-is-multibyte                                   1   0%
      rtags-goto-line-col                                       42810  31%
      rtags-goto-offset                                         42169  31%
      looking-back                                                  7   0%
     rtags-overlays-remove                                         54   0%
   - rtags-really-find-buffer                                       1   0%
    - file-truename                                                 1   0%
     - file-truename                                                1   0%
      - file-truename                                               1   0%
       - file-truename                                              1   0%
          file-truename                                             1   0%
    byte-code                                                       8   0%

```

If you know how to load an Profiler-Report mode buffer, which the doc claims is saveable but just looks like gibberish:
[emacs-profiler-rtags.txt](https://github.com/Andersbakken/rtags/files/462947/emacs-profiler-rtags.txt)

**Comment by jlargentaye** [comment]
Hm, this doesn't manifest when opening the same file in a brand new Emacs session.

**Comment by Andersbakken** [comment]
Very likely it's due to diagnostics.

Do you have rtags-autostart-diagnostics set to t?

If so, can you try to set it to nil and see if that helps?

There's probably something we could do if this is the case.

Anders

On Thu, Sep 8, 2016 at 5:26 PM, John de Largentaye <notifications@github.com

**Comment by jlargentaye** [comment]
I forgot to mentioned that in a brand new Emacs session, rtags keybindings aren't enabled yet (I suppose I failed to initialize them properly in my .emacs). If they aren't, is rtags still working in the background to analyze opened files?

rtags-autostart-diagnostics is nil in this new session. I don't recall setting it in the last session, but it's possible. I'll verify again when the problem manifests itself again.

**Comment by Andersbakken** [comment]
Hi John

autostart diagnostics only gets a chance to do its thing when an rtags
function is called.

The best thing might be to use this feature I didn't realize we had
called rtags-diagnostics-suspended

do a:
 M-: (setq rtags-diagnostics-suspended t) <ENTER>

Then check if things work better.

Anders

On Fri, Sep 9, 2016 at 4:46 PM, John de Largentaye <notifications@github.com

**Comment by cslux** [comment]
Please reopen this issue if it still happens.
