### ISSUE TITLE
Process::handleOutput, buffer too big, dropping data - is ths an issue

### ISSUE THREAD

**Issue by schnoberts1** [Andersbakken/rtags#795]
Hi, 

When running rdm with verbose logging I see a lot, i.e. 1000's, of these messages as it processes my files (23,000 entries in the compilation database). 

e.g 

Process::handleOutput, buffer too big, dropping data
Process::handleOutput, buffer too big, dropping data
Process::handleOutput, buffer too big, dropping data
Process::handleOutput, buffer too big, dropping data
Process::handleOutput, buffer too big, dropping data
Process::handleOutput, buffer too big, dropping data
Process::handleOutput, buffer too big, dropping data
Process::handleOutput, buffer too big, dropping data
Process::handleOutput, buffer too big, dropping data
Process::handleOutput, buffer too big, dropping data
job got index data message 3291 2400886718471 0x3d507d0
[ 58%] 1125/1925 12:44:48 /ssd/prod/Enterprise/VC/libgcquotesymbol/gCombinedQuoteSymbolCache.cpp in 37219ms. (393 syms, 241 symNames, 5 includes, 1 of 1357 files, symbols: 570 of 88034, 88692 cursors, 195899 bytes written) (7048/18218/2ms) (dirty). (priority 1)
job got index data message 3297 2430951489543 0x53ef390
[ 58%] 1126/1925 12:44:48 /ssd/prod/Enterprise/VC/libtbut/AsyncBufferedFile.cpp in 19779ms. (314 syms, 322 symNames, 6 includes, 1 of 949 files, symbols: 386 of 57455, 58025 cursors, 168308 bytes written) (3738/4246/1ms) (dirty). (priority 1)
Process::handleOutput, buffer too big, dropping data
Process::handleOutput, buffer too big, dropping data
Process::handleOutput, buffer too big, dropping data
Process::handleOutput, buffer too big, dropping data
Process::handleOutput, buffer too big, dropping data
Process::handleOutput, buffer too big, dropping data
Process::handleOutput, buffer too big, dropping data
Process::handleOutput, buffer too big, dropping data
Process::handleOutput, buffer too big, dropping data

Is this going to effect the operation of rtags or can I safely ignore the log messages? 

Thanks, 

Andy

BTW: rtags is great, thank you for building it.

**Comment by Andersbakken** [comment]
Hi Andy

RTags still runs fine, it only concerns output to stderr/stdout but it's of
course not ideal. I'll up the limit from 16 megs of backlog per process to
256 megs and hopefully that's big enough. :-)

Glad you like it. Let us know if you run into other issues.

Anders

**Comment by schnoberts1** [comment]
That's great. I'll close this.
