### ISSUE TITLE
confused for the result from 'rc --has-filemanager' with different arguments

### ISSUE THREAD

**Issue by sunlin7** [Andersbakken/rtags#798]
hi Anders,

I made a project, and try `rc --has-filemanager` without argument or with different arguments, the output really make me confused, please see the follow snapshot, there is ".../**tmp**/..." in project path, and current path is **"/tmp"**, 
```
/tmp$ rc -w
/home/sunline/tmp/clang-parse/ <=
/tmp$ rc --has-filemanager 
0
/tmp$ rc --has-filemanager /tmp
1
/tmp$ rc --has-filemanager /tmp/
0
```
It seems that the `rc --has-filemanager` will simply match the path string but didn't take care the absolute path.  
It should be better that `rc --has-filemanager` pass the full path to server, and the server always match the full path.
Best Regards

**Comment by Andersbakken** [comment]
Hi

That is indeed weird behavior.

Should be fixed now.

Thanks

Anders

**Comment by sunlin7** [comment]
I work like a charm now, thank you.
