### ISSUE TITLE
rtags installation in ubuntu 14.04 throws error

### ISSUE THREAD

**Issue by vikigenius** [Andersbakken/rtags#804]
I executed the following commands:

`git clone --recursive https://github.com/Andersbakken/rtags.git`
`cd rtags`
`cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 .`
`make`

This throws an error:

Loading 00debian-vars...
Loading /etc/emacs/site-start.d/50autoconf.el (source)...
Loading /etc/emacs/site-start.d/50cmake-data.el (source)...
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
Loading debian-ispell...
Loading /etc/emacs/site-start.d/50global.el (source)...
Symbol's function definition is void: with-eval-after-load
make[2]: *** [src/company-rtags.elc] Error 255
make[1]: *** [src/CMakeFiles/emacs_byte_compile_company-rtags.el.dir/all] Error 2
make: *** [all] Error 2

I have emacs 24.3.1
Can someone help or atleast give an idea what is causing this error?

**Comment by Andersbakken** [comment]
Weird. This function should be part of the emacs base to the best of my
knowledge.

Can you try the following:

$ emacs -q
C-h f with-eval-after-load <ret>

And see if it finds the function?

regards

Anders

**Comment by vikigenius** [comment]
Hi, i upgraded my emacs from 24.3 to 24.4 and now it works, looks like 
**with-eval-after-load** is available only from emacs 24.4, you should use the alternate **eval-after-load** to support older emacs or update your doc to say supported emacs is >= 24.4 not 24.3,

the below stackoverflow answer mentions that with-eval-after-load was introduced in emacs 24.4:
http://stackoverflow.com/a/21880276/4126652

**Comment by billkozbi** [comment]
Unfortunately it caught me too. **with-eval-after-load** is not available in emacs 24.3 which I have on my company server and I cannot upgrade it. I think I have to git pull revision which didn't use it yet.

**Comment by Andersbakken** [comment]
I tried to fix this by moving the helm stuff into rtags-helm. Can you see if this fixes the problem for you?

**Comment by billkozbi** [comment]
Now I have problem with building rtags:
_1. Cannot open load file: rtags-helm
2. 'class LogOutput' has no member vlog_

**Comment by Andersbakken** [comment]
The first issue should be fixed with a git pull

For the second I think you need to do a git submodule update

Let me know if this works.

Anders

**Comment by billkozbi** [comment]
It works now. Thanks!

**Comment by Andersbakken** [comment]
Good to hear. Thanks.

Anders
