### ISSUE TITLE
Recover from "Failed to open /path/to/rtags-cache/../fileid/symbols" file

### ISSUE THREAD

**Issue by dscole** [Andersbakken/rtags#806]
I think there is some bug and I'll try my best to explain what's going on, even though I'm not 100% clear on it myself. Here goes.

1. I have a project "project_name" and it's fully indexed into rtags and everything is working properly.
2. I now want to add a new file to the project file.cpp, so I create it and started editing it.
3. While editing, I accidentally hit ```rtags-find-symbol-at-point```.
4. Obviously rtags doesn't know about this file, so I see in the log this: ```Failed to open /path/to/rtags-cache/_project_name_/11549/symbols /path/to/file/file.cpp (2) 87```
5. I want to remedy the situation, so I add the relevant compile command to the compile_commands.json file and tell rtags to reload it via ```rc -J .```.
6. rtags completely ignores this and subsequent calls to ```rtags-find-symbol-at-point``` yield the same error in the log file. Retrying using an explicit ```rc -c -``` and pasting the command doesn't help.

Now I have no way (or at least I don't know of one) of recovering from this error other that wiping out the whole cache. I think that if I had a way of telling rtags something like ```rc --forget-about-this-file /path/to/file/file.cpp``` I'd be able to reindex it and continue working happily. 
Another thing that bothered me about this issue is that the log doesn't really print a whole lot about what's going on. I remember in earlier rtags version the log used to be very verbose and it was much easier to see whats going on. Now when I try to load a compile_commands.json file, if no file is getting reindexed, the log shows absolutely no indication it received any request to load a new compile_commands.json file.

My current version is 2e676e1a0dada6a49fc454b5b29710bc30b28b70

Any help would be very much appreciated.

**Comment by Andersbakken** [comment]
Hi

This is weird. Are you able to reliably reproduce this? I wasn't able to.

It tried the following:

- make an example project with one file
- Add another file to the project
- Try to rtags-find-symbol-at-point in the new file without having told
rtags about it (Failed to open etc...)
- Add the file to compile_commands.json
- File was indexed and navigation worked

I believe I've actually seen what you describe though but I haven't found a
way to reproduce it.

Anders

**Comment by dscole** [comment]
I'll try to reproduce it with a toy example today.

**Comment by dscole** [comment]
I was having some other issues as well, so I ended up pulling latest and the issue seems to have gone away. I'll open a new ticket if I see the issue again

**Comment by dscole** [comment]
I started using --validate-file-maps so I think that helps too.
