### ISSUE TITLE
Issues with getopt_long() in CommandLine::parse()

### ISSUE THREAD

**Issue by stunpix** [Andersbakken/rtags#814]
I see last commits like a76980b6 and 20f45f30. Are there any reasons behind these changes?

I'm asking because I'm debugging rtags code (I still can't get to work realpath option from issue #807) and I've found some issues with getopt_long().

I've prepared a patch, but patched files were modified, so I put my fixes here. 😉

**Issue 1**

GNU `getopt()` and `getopt_long()` are using private structure to store some data (pointers, states, etc.) between calls. If options/strings for `getopt()` are allocated on heap and then they freed once between `getopt()` calls, getopt will try to access this freed memory by dereferencing stored pointers from previous call. I've used Valgrind&gdb with getopt sources to catch this.

Since some data could be freed between `parse()` calls this leads to unpredicted behavior inside `getopt()`. For example I figured out that rdm sometimes wouldn't recognize options or even sees garbage instead of them.

My fix was to initialize getopt before parsing loop:

```cpp
#ifdef __GNU_LIBRARY__
    // WORKAROUND
    // Setting "optind" to 0 triggers initialization of getopt private
    // structure (holds pointers on data between calls). This helps
    // to avoid possible memory violation, because data passed to getopt_long()
    // could be freed between parse() calls.
    optind = 0;
#else
    // "optind" is used between getopt() calls to get next argument for parsing and should be
    // initialized before each parsing loop.
    optind = 1;
#endif

    while (ret == Parse_Exec) {
        ...
    }
```

This is undocumented feature. With this fix Valgrind no longer reporting about memory violation.

**Issue 2**

`getopt_long()` results should be interpreted in this way: 0 is returned for long options, -1 for the end of options and a character code for short options (with '?' and ':' for special cases). At the moment `parse()` uses `idx` to identify long options:

```cpp
const Option<T> *opt = (idx == -1 ? shortOptions.value(c) : longOptions.value(idx));
```

This could lead to parsing errors and it should replaced with:

```cpp
const Option<T> *opt = (c ? shortOptions.value(c) : longOptions.value(idx));
```

Hope this will help.

**Comment by stunpix** [comment]
I see you've fixed second issue in 96345eb. Nice. 👍

Looking forward you apply patch for first issue with `optind`. Here is paragraph about `optind` from [getopt doc](http://man7.org/linux/man-pages/man3/getopt.3.html):

> The variable optind is the index of the next element to be processed in argv. The system initializes this value to 1.  The caller can reset it to 1 to restart scanning of the same argv, or when scanning a new argument vector.

Due to bug in gnu `getopt` and `getopt_long` it should be initialized with 0 for each argument parsing cycle.

**Comment by stunpix** [comment]
Command line parser has been rewritten, issue no longer relevant. Thanks!

**Comment by Andersbakken** [comment]
My pleasure. getopt really is kinda archaic at this point.

Anders
