### ISSUE TITLE
Rtags-references-tree-mode has to be entered twice

### ISSUE THREAD

**Issue by sphaerophoria** [Andersbakken/rtags#816]
Currently if I start (rtags-references-tree), (rtags-references-tree-expand-current) will do nothing unless I manually start (rtags-references-tree-mode) again myself. My elisp is not so great so I haven't managed to track down the issue myself. I'm using the latest el files (I believe last edited on September 26). I'm not sure when the issue started.

**Comment by Andersbakken** [comment]
Hm. That's odd. It seems to work for me.

Most likely an error happens along the way that prevents the rest of the
function from getting called.

Can you do:

M-x toggle-debug-on-error

Then make it happen again and check if you get some output in a buffer
called *backtrace* (or something like that).

Anders

**Comment by sphaerophoria** [comment]
I don't see anything particularly interesting. Available buffers show no output. 

I checked *Messages* *RTags Log* and no other buffers were open.

**Comment by Andersbakken** [comment]
Can you try to step through the rtags-references-tree defun with edebug and
see if anything throws an error or something else noteworthy happens?

regards

Anders

**Comment by sphaerophoria** [comment]
Sorry it's taken so long to get back to you, haven't had much time to dig into it.

Looks to me like it's a problem with the entries being inserted into the rtags buffer. When I expand the tree rc is being invoked and seems to return the correct information (at least what shows up in the minibuffer looks like calls to the function I want to see).

**Comment by sphaerophoria** [comment]
Unfortunately I lost the environment where this was happening. It seems to work fine on the new one

**Comment by Andersbakken** [comment]
Lets hope it never happens to anyone ever again :-)

Please reopen if it does.

Anders
