### ISSUE TITLE
gcc-rtags-wrapper.sh no longer works

### ISSUE THREAD

**Issue by brucestephens** [Andersbakken/rtags#817]
I think some recent change in parsing has broken it, so now it's expected that the compile command line should be a single argument after `--compile`, whereas `gcc-rtags-wrapper.sh` passes the command as separate arguments. (Not sure which is better; I'd guess the previous behaviour would be easier to get right in the presence of arguments containing spaces.)

**Comment by Andersbakken** [comment]
Hi Bruce

It should be working again now. I committed several busted versions of the
argument parsing over the last week.

Can you check if it's started working again?

regards

Anders

**Comment by brucestephens** [comment]
Yes, looks OK again now, thanks!

**Comment by Andersbakken** [comment]
Glad to hear.

Anders
