### ISSUE TITLE
rtags only works without rtags-completions-enabled

### ISSUE THREAD

**Issue by danluu** [Andersbakken/rtags#818]
Rtags works fine for me unless I set

```
(setq rtags-completions-enabled t)
```

If I do that, commands like `rtags-find-symbol` all return `RTags: no result`.

Do you have any suggestions for how I might debug this?

**Comment by Andersbakken** [comment]
Hi Dan

I can't reproduce this personally.

To debug I would try the following:

(setq rtags-rc-log-enabled t)

Try the command with and without rtags-completions-enabled

The *RTags Log* buffer should contain the actual commands run.

Then try both on the command line and check if they produce different
output.

Anders

**Comment by danluu** [comment]
Thanks! In both cases below, I'm running `rtags-find-symbol-at-point` on a `IDocument`.

If I'm reading the right part of the log, in the working state, `*RTags Log* displays:
~~~
**********************************
1476048453: /usr/local/bin/rc --current-file=/Users/visualstudio/dev/BitFunnel/src/Mocks/src/PrimeFactorsDocument.cpp --no-color -f /Users/visualstudio/dev/BitFunnel/src/Mocks/src/PrimeFactorsDocument.cpp:65:22:
**********************************
1476048453: /usr/local/bin/rc --current-file=/Users/visualstudio/dev/BitFunnel/src/Mocks/src/PrimeFactorsDocument.cpp --no-color --current-project
~~~

In the bad state, we get:
~~~
**********************************
1476049154: /usr/local/bin/rc --current-file=/Users/visualstudio/dev/BitFunnel/src/Mocks/src/PrimeFactorsDocument.cpp -b --no-color -f /Users/visualstudio/dev/BitFunnel/src/Mocks/src/PrimeFactorsDocument.cpp:65:27:
**********************************
1476049154: /usr/local/bin/rc --current-file=/Users/visualstudio/dev/BitFunnel/src/Mocks/src/PrimeFactorsDocument.cpp -b --no-color -F IDocument --definition-only -M 1 --dependency-filter /Users/visualstudio/dev/BitFunnel/src/Mocks/src/PrimeFactorsDocument.cpp --wildcard-symbol-names
**********************************
1476049154: /usr/local/bin/rc --current-file=/Users/visualstudio/dev/BitFunnel/src/Mocks/src/PrimeFactorsDocument.cpp -b --no-color -F IDocument -M 1 --dependency-filter /Users/visualstudio/dev/BitFunnel/src/Mocks/src/PrimeFactorsDocument.cpp --wildcard-symbol-names
~~~

I don't really understand rtags, but if I'm reading this correctly, `find-symbol-at-point` initially runs the same command in both cases. It looks like I was at a slightly different cursor position the second time, but the failure or success of the command seems to be independent of cursor position.

Anyway, after running the initial command, what follows is different. Is that expected behavior?

**Comment by Andersbakken** [comment]
Hi Dan

It does appear that the location that's being used as input is different
and this is likely the cause of the problem.

Can you check what location your cursor was supposed to be on?

E.g.

Column 27 or column 22.

Is there by any chance any unicode in this source file?

The commands that come after are actually a result of the first command
failing. We fall back to trying to find the symbol by name.

Anders

**Comment by danluu** [comment]
I believe both locations are correct, since both locations are "inside" the symbol. If you have to be at the start of the symbol or something like that, I can re-run both commands with my cursor at the start of the symbol.

There shouldn't be Unicode in the document, and `file` claims the file is ASCII text.
~~~
file src/Mocks/src/PrimeFactorsDocument.cpp
src/Mocks/src/PrimeFactorsDocument.cpp: c program text, ASCII text
~~~

**Comment by AriaFallah** [comment]
I'm having the same exact issue as above with similar output in the log

Broken
```
**********************************
1478232841: /usr/local/bin/rc --current-file=/Users/Developer/workspace/projects/qsv/include/qsv/file.hpp -b --no-color -f /Users/Developer/workspace/projects/qsv/include/qsv/file.hpp:11:24:
**********************************
1478232841: /usr/local/bin/rc --current-file=/Users/Developer/workspace/projects/qsv/include/qsv/file.hpp -b --no-color -F get_file --definition-only -M 1 --dependency-filter /Users/Developer/workspace/projects/qsv/include/qsv/file.hpp --wildcard-symbol-names
**********************************
1478232841: /usr/local/bin/rc --current-file=/Users/Developer/workspace/projects/qsv/include/qsv/file.hpp -b --no-color -F get_file -M 1 --dependency-filter /Users/Developer/workspace/projects/qsv/include/qsv/file.hpp --wildcard-symbol-names
```

Working:

```
**********************************
1478232849: /usr/local/bin/rc --current-file=/Users/Developer/workspace/projects/qsv/include/qsv/file.hpp --no-color -f /Users/Developer/workspace/projects/qsv/include/qsv/file.hpp:11:24:
**********************************
1478232849: /usr/local/bin/rc --current-file=/Users/Developer/workspace/projects/qsv/include/qsv/file.hpp --no-color --current-project
```

The code is just really simple as well

```cpp
#ifndef FILE_H
#define FILE_H

#include <string>
#include <fstream>

class File {
public:
  File(std::string filename);
  ~File();
  const std::ifstream& get_file() const;
private:
  std::ifstream m_file;
};

#endif
```

```cpp
#include <stdexcept>
#include "qsv/file.hpp"

File::File(std::string filename): m_file(filename) {
  if (!m_file.good()) {
    throw std::runtime_error("There was an error opening this file!");
  }
}

File::~File() {
  m_file.close();
}

const std::ifstream& File::get_file() const {
  return m_file;
}
```

My `.emacs.d` is very similar to what's specified here: http://syamajala.github.io/c-ide.html

**Comment by dmakarov** [comment]
I have the same issue.  Adding `(setq rtags-completions-enabled t)` breaks rtags, i.e. `No results` on any query.

**Comment by Andersbakken** [comment]
This is very strange. What version of libclang are you running against?

Anders

**Comment by dmakarov** [comment]
I have llvm 3.9 installed
```
$ brew info llvm
llvm: stable 3.9.0 (bottled), HEAD [keg-only]
```
unless libclang uses different versioning, it should be 3.9.0.

However, why would it matter what libclang version is used?  As I added in the comment, the problem is that `-b` option is not followed by an argument representing a completion location in the `rc` command line when `rtags-completions-enabled` is set to `t`.

**Comment by Andersbakken** [comment]
-b doesn't take an argument. It's a hint to RTags that completions are currently enabled and as such RTags should "warm them up" for the active translation units. It might be interesting to apply this patch and see if it fixes it however. 
```
--- a/src/RClient.cpp
+++ b/src/RClient.cpp
@@ -489,7 +489,7 @@ CommandLineParser::ParseStatus RClient::parse(size_t argc, char **argv)
             mQueryFlags |= QueryMessage::CodeCompleteNoWait;
             break; }
         case CodeCompletionEnabled: {
-            mQueryFlags |= QueryMessage::CodeCompletionEnabled;
+            // mQueryFlags |= QueryMessage::CodeCompletionEnabled;
             break; }
         case Autotest: {
             mFlags |= Flag_Autotest;
```

**Comment by dmakarov** [comment]
This problem appears to be solved, even without the patch. I just verified with rtags 2.7.  It might be because previously rtags Homebrew package got out of sync with the emacs rtags package.  I believe older version of rc complained about -b not being followed by an argument.  Perhaps, this has changed few releases back, but since rtgas didn't update in Homebrew for some time (remember failing tests because of projects unders /tmp not being indexed) it didn't work with the newer versions of emacs rtags.

I have another problem with rtags 2.7 though.  For some reason `rc` almost always exits with non-zero exit code, even on successful queries.  So Emacs reports `No results` on almost every rtags operation, but still works correctly, i.e. the symbols, that are looked up, are found and the cursor is placed in the correct locations.  I don't know if this should be reported as an issue, or this is something you are already aware of.

**Comment by Andersbakken** [comment]
Hi

I can't seem to reproduce this actually. Can you reproduce this in a small example?

What operations are you doing? Does it happen with rtags-find-symbol-at-point for example?

**Comment by dmakarov** [comment]
Yes, it does happen for `rtags-find-symbol-at-point`.  When I look at the log buffer after executing `rtags-find-symbol-at-point` there are the following commands:
```
1482135077: /usr/local/bin/rc --current-file=/path/smth.cpp -b -z -f /path/smth.cpp:492:24:
```
and several others.  When I run the above command from shell prompt, I get exit code 1:
```
$ /usr/local/bin/rc --current-file=/path/smth.cpp -b -z -f /path/smth.cpp:492:24:
$ echo $?
1
```

**Comment by cslux** [comment]
Indeed, sorry! I can't reproduce this either. Can you provide these informations please:

- Clang/LLVM version
- Emacs version
- GCC version
- OS (`lsb_release`)
- Your rtags configuration setup. 

Please also test your configuration when started emacs like this `emacs -Q`.

Thanks!

**Comment by cslux** [comment]
@dmakarov 
> I have another problem with rtags 2.7 though. For some reason rc almost always exits with non-zero exit code, even on successful queries. So Emacs reports No results on almost every rtags operation, but still works correctly, i.e. the symbols, that are looked up, are found and the cursor is placed in the correct locations. I don't know if this should be reported as an issue, or this is something you are already aware of.

If this still valid with the latest RTags revision, please open a new issue. Thanks!

**Comment by cslux** [comment]
@danluu Have you tried it already with the latest revision of RTags https://github.com/Andersbakken/rtags/commit/b6f578173e53df2d4c4560ae82087e377a4aa080, if not, can try it, and report back if it works now for you? Thanks!

Christian

**Comment by cslux** [comment]
If this still is valid, let me no it, and I will reopen this issue.

**Comment by danluu** [comment]
Unfortunately, I don't have a great way to repro this (I haven't used rtags for a while and don't have it set up on any machine/VM I'm using now). Sorry!

**Comment by cslux** [comment]
No problem! If you will try it one day or another, and it still happens, just
reopen this issue.

Thanks!
Christian
