### ISSUE TITLE
Fail HAVE_CXX11 test with clang compiler

### ISSUE THREAD

**Issue by handrake0724** [Andersbakken/rtags#824]
in line 224 of src/rct/rct.cmake, clang compiler does not pass HAVE_CXX11 test.
Although cmake have found that I have clang 3.8.1, it complains 
`
-- Performing Test HAVE_CXX11
-- Performing Test HAVE_CXX11 - Failed
CMake Error at src/rct/rct.cmake:244 (message):
  C++11 support not detected.  rct requires a modern compiler, GCC >= 4.8 or
  Clang >= 3.2 should suffice
Call Stack (most recent call first):
  src/CMakeLists.txt:83 (include)
`

I have compile the testing code in the line 224 of src/rct/rct.cmake with the following command with success
`clang++ -I. have_cxx11.cpp -std=c++11 -stdlib=libc++`
where -I. flag could be changed in order to direct src/rct/Apply.h
but, with -stdlib=libstdc++, compilation has failed.

in CMakeFiles/CMakeError.log, the test code is compiled without -stdlib=libc++ (looks like system default setting?).

For a workaround, the test code was commented out and all the compilation worked perfectly and rdm, rc works fine.

I am worndering if the failure of the test is due to bug

**Comment by Andersbakken** [comment]
Hi

Are you by any chance running clang on linux?

Can you try the following:

cmake "-DCMAKE_CXX_FLAGS=-std=c++11" /path/to/rtags

And see if it fixes it?

regards

Anders

**Comment by handrake0724** [comment]
No, it does not work. 
The error message is as follows:

>
-- The C compiler identification is Clang 3.8.1
-- The CXX compiler identification is Clang 3.8.1
-- Check for working C compiler: /opt/clang/3.8.1/bin/clang
-- Check for working C compiler: /opt/clang/3.8.1/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /opt/clang/3.8.1/bin/clang++
-- Check for working CXX compiler: /opt/clang/3.8.1/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Using Clang version 3.8.1 from /opt/clang/3.8.1/lib with CXXFLAGS -I/opt/clang/3.8.1/include -D__TBB_CPP -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
CMake Error at src/rct/rct.cmake:244 (message):
  C++11 support not detected.  rct requires a modern compiler, GCC >= 4.8 or
  Clang >= 3.2 should suffice
Call Stack (most recent call first):
  src/CMakeLists.txt:83 (include)
>

CMakeError is as follows:


Performing C++ SOURCE FILE Test HAVE_CXX11 failed with the following output:
Change Dir: /opt/src/rtags/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_cb9b5/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_cb9b5.dir/build.make CMakeFiles/cmTC_cb9b5.dir/build
gmake[1]: Entering directory '/opt/src/rtags/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_cb9b5.dir/src.cxx.o
/opt/clang/3.8.1/bin/clang++     -I/opt/clang/3.8.1/include -D__TBB_CPP -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Wall -Wextra -Wpointer-arith -Wnon-virtual-dtor -std=c++11 -DHAVE_CXX11 -std=c++11   -o CMakeFiles/cmTC_cb9b5.dir/src.cxx.o -c /opt/src/rtags/build/CMakeFiles/CMakeTmp/src.cxx
Linking CXX executable cmTC_cb9b5
/opt/cmake/3.6.1/bin/cmake -E cmake_link_script CMakeFiles/cmTC_cb9b5.dir/link.txt --verbose=1
/opt/clang/3.8.1/bin/clang++    -I/opt/clang/3.8.1/include -D__TBB_CPP -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Wall -Wextra -Wpointer-arith -Wnon-virtual-dtor -std=c++11 -DHAVE_CXX11 -std=c++11    CMakeFiles/cmTC_cb9b5.dir/src.cxx.o  -o cmTC_cb9b5 -rdynamic
CMakeFiles/cmTC_cb9b5.dir/src.cxx.o: In function 'main':
/opt/src/rtags/build/CMakeFiles/CMakeTmp/src.cxx:(.text+0xbb): undefined reference to 'std::__1::mutex::lock()'
/opt/src/rtags/build/CMakeFiles/CMakeTmp/src.cxx:(.text+0x145): undefined reference to 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__init(char const*, unsigned long)'
/opt/src/rtags/build/CMakeFiles/CMakeTmp/src.cxx:(.text+0x315): undefined reference to 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()'
/opt/src/rtags/build/CMakeFiles/CMakeTmp/src.cxx:(.text+0x322): undefined reference to 'std::__1::placeholders::_2'
/opt/src/rtags/build/CMakeFiles/CMakeTmp/src.cxx:(.text+0x32c): undefined reference to 'std::__1::placeholders::_1'
/opt/src/rtags/build/CMakeFiles/CMakeTmp/src.cxx:(.text+0x4f5): undefined reference to 'std::__1::mutex::unlock()'
/opt/src/rtags/build/CMakeFiles/CMakeTmp/src.cxx:(.text+0x501): undefined reference to 'std::__1::mutex::~mutex()'
/opt/src/rtags/build/CMakeFiles/CMakeTmp/src.cxx:(.text+0x594): undefined reference to 'std::__1::mutex::unlock()'
/opt/src/rtags/build/CMakeFiles/CMakeTmp/src.cxx:(.text+0x5a5): undefined reference to 'std::__1::mutex::~mutex()'
CMakeFiles/cmTC_cb9b5.dir/src.cxx.o: In function 'std::__1::shared_ptr<int>::~shared_ptr()':
/opt/src/rtags/build/CMakeFiles/CMakeTmp/src.cxx:(.text._ZNSt3__110shared_ptrIiED2Ev[_ZNSt3__110shared_ptrIiED2Ev]+0x28): undefined reference to 'std::__1::__shared_weak_count::__release_shared()'
CMakeFiles/cmTC_cb9b5.dir/src.cxx.o: In function 'std::__1::__tuple_leaf<1ul, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, false>::~__tuple_leaf()':
/opt/src/rtags/build/CMakeFiles/CMakeTmp/src.cxx:(.text._ZNSt3__112__tuple_leafILm1ENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEELb0EED2Ev[_ZNSt3__112__tuple_leafILm1ENS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEELb0EED2Ev]+0x11): undefined reference to 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()'
CMakeFiles/cmTC_cb9b5.dir/src.cxx.o: In function '_ZN9ApplyMoveILm0EE9applyMoveINSt3__16__bindIRFviNS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEEJRNS2_12placeholders4__phILi1EEERNSD_ILi2EEEEEENS2_5tupleIJiS9_EEEJiS9_EEEDTclclgssr3stdE7forwardIT_Efp_Espclgssr3stdE7forwardIT1_Efp1_EEEOSL_OT0_DpOSM_':
/opt/src/rtags/build/CMakeFiles/CMakeTmp/src.cxx:(.text._ZN9ApplyMoveILm0EE9applyMoveINSt3__16__bindIRFviNS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEEJRNS2_12placeholders4__phILi1EEERNSD_ILi2EEEEEENS2_5tupleIJiS9_EEEJiS9_EEEDTclclgssr3stdE7forwardIT_Efp_Espclgssr3stdE7forwardIT1_Efp1_EEEOSL_OT0_DpOSM_[_ZN9ApplyMoveILm0EE9applyMoveINSt3__16__bindIRFviNS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEEJRNS2_12placeholders4__phILi1EEERNSD_ILi2EEEEEENS2_5tupleIJiS9_EEEJiS9_EEEDTclclgssr3stdE7forwardIT_Efp_Espclgssr3stdE7forwardIT1_Efp1_EEEOSL_OT0_DpOSM_]+0x3c6): undefined reference to 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()'
/opt/src/rtags/build/CMakeFiles/CMakeTmp/src.cxx:(.text._ZN9ApplyMoveILm0EE9applyMoveINSt3__16__bindIRFviNS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEEJRNS2_12placeholders4__phILi1EEERNSD_ILi2EEEEEENS2_5tupleIJiS9_EEEJiS9_EEEDTclclgssr3stdE7forwardIT_Efp_Espclgssr3stdE7forwardIT1_Efp1_EEEOSL_OT0_DpOSM_[_ZN9ApplyMoveILm0EE9applyMoveINSt3__16__bindIRFviNS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEEJRNS2_12placeholders4__phILi1EEERNSD_ILi2EEEEEENS2_5tupleIJiS9_EEEJiS9_EEEDTclclgssr3stdE7forwardIT_Efp_Espclgssr3stdE7forwardIT1_Efp1_EEEOSL_OT0_DpOSM_]+0x3de): undefined reference to 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()'
clang-3.8: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[1]: *** [cmTC_cb9b5] Error 1
gmake[1]: Leaving directory '/opt/src/rtags/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_cb9b5/fast] Error 2

Source file was:

  #include <memory>
  #include <mutex>
  #include <tuple>
  #include <string>
  #include </opt/src/rtags/src/rct/rct/Apply.h>

  void callTest(int, std::string) { }

  int main(int, char**) {
      std::shared_ptr<int> ptr;
      std::mutex mtx;
      std::unique_lock<std::mutex> lock(mtx);
      std::tuple<int, std::string> tpl(5, std::string("foo"));
      applyMove(std::bind(callTest, std::placeholders::_1, std::placeholders::_2), tpl);
      return 0;
  }

**Comment by Andersbakken** [comment]
I should have said:

cmake "-DCMAKE_CXX_FLAGS=- stdlib=libstdc++" /path/to/rtags

Can you try that one as well?

regards

Anders

**Comment by handrake0724** [comment]
It does not work.

I have tried 
   cmake "-DCMAKE_CXX_FLAGS=- stdlib=libstdc++" /path/to/rtags
and 
   cmake "-DCMAKE_CXX_FLAGS=- stdlib=libc++" /path/to/rtags

but still got the following error:
-- Using Clang version 3.8.1 from /opt/clang/3.8.1/lib with CXXFLAGS -I/opt/clang/3.8.1/include -D__TBB_CPP -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
CMake Error at src/rct/rct.cmake:244 (message):
  C++11 support not detected.  rct requires a modern compiler, GCC >= 4.8 or
  Clang >= 3.2 should suffice
Call Stack (most recent call first):
  src/CMakeLists.txt:83 (include)

**Comment by handrake0724** [comment]
Instead of doing
   cmake "-DCMAKE_CXX_FLAGS=- stdlib=libstdc++" /path/to/rtags
,
   cmake "-DCMAKE_CXX_FLAGS=- stdlib=libc++" /path/to/rtags
works.

Thanks.

**Comment by Andersbakken** [comment]
Ah. Of course. My bad.

Glad to hear it works.

Anders
