### ISSUE TITLE
Failed to Parse Clang When Compiling OpenCV

### ISSUE THREAD

**Issue by dukebw** [Andersbakken/rtags#825]
Hi,

When compiling OpenCV I am running into the following error from rtags ( I am using the wrapper scripts),

Failed to parse clang "-fsigned-char" "-W" "-Wall" "-Werror=return-type" "-Werror=non-virtual-dtor" "-Werror=address" "-Werror=sequence-point" "-Wformat" "-Werror=format-security" "-Wmissing-declarations" "-Wundef" "-Winit-self" "-Wpointer-arith" "-Wshadow" "-Wsign-promo" "-Wno-narrowing" "-Wno-delete-non-virtual-dtor" "-Wno-comment" "-fdiagnostics-show-option" "-Wno-long-long" "-pthread" "-fomit-frame-pointer" "-msse" "-msse2" "-mno-avx" "-msse3" "-mno-ssse3" "-mno-sse4.1" "-mno-sse4.2" "-ffunction-sections" "-fvisibility=hidden" "-fvisibility-inlines-hidden" "-O3" "-fPIC" "-Winvalid-pch" "-c" "-ferror-limit=50" "-Wall" "-fspell-checking" "-Wno-unknown-warning-option" "-DCVAPI_EXPORTS" "-D__OPENCV_BUILD=1" "-I/home/bduke/work/opencv/3rdparty/ippicv/unpack/ippicv_lnx/include" "-I/home/bduke/work/opencv/build" "-I/home/bduke/work/opencv/modules/core/include" "-I/home/bduke/work/opencv/modules/core/src" "-I/home/bduke/work/opencv/build/modules/core" "-I/home/bduke/work/opencv/3rdparty/include/opencl/1.2" "-include" "/home/bduke/work/opencv/build/modules/core/precomp.hpp" "-isystem" "/usr/lib64/clang/3.8.0/include/" /home/bduke/work/opencv/modules/core/src/persistence.cpp

I have attached the full log. Is there any other debug information I could add?

[rtags-log-opencv.txt](https://github.com/Andersbakken/rtags/files/529443/rtags-log-opencv.txt)

**Comment by Andersbakken** [comment]
Hi

Can you try to run that command line from the terminal and see if it
succeeds? Normally this problem happens when the source file doesn't
actually exist. It could also be an intermittent problem during a git pull
etc where the file briefly doesn't exist.

regards

Anders

**Comment by dukebw** [comment]
Hi Anders,

You're right, it looks like Clang can't find a file:

error: no suitable precompiled header file found in directory '/home/bduke/work/opencv/build/modules/core/precomp.hpp.gch'

Thank you!
