### ISSUE TITLE
rc -U  behaves weirdly with decltype

### ISSUE THREAD

**Issue by RedBeard0531** [Andersbakken/rtags#826]
Test file:
```cpp
int a;
decltype(a) b;
```

rc -U <location of b>:
```
<location of b>:	decltype(a) b;
SymbolName: decltypeb
Kind: VarDecl
Type: decltype(a)
SymbolLength: 1
Range: 3:1-3:14
Linkage: External
Definition
Usr: c:@b
```

Note that type isn't resolved and SymbolName is all weird. Somehow SymbolLength is correct though.

**Comment by Andersbakken** [comment]
I've mostly fixed it. At least it doesn't butcher the symbolname as badly anymore. There's no very simple API to resolve to the actual underlying type though I could piece it together with some work.

**Comment by RedBeard0531** [comment]
I'm still seeing the same output even after upgrading to e1abfb1.

**Comment by RedBeard0531** [comment]
Correction: it now says: `SymbolName: decltype(a) b` which is still kinda weird.

ycmd's GetType functionality seems to be able to correctly resolve it and outputs `decltype(a) => b`. It may be worth looking into how they do it.

**Comment by RedBeard0531** [comment]
It doesn't look like they are doing anything complicated: https://github.com/Valloric/ycmd/blob/89aebcc/cpp/ycm/ClangCompleter/TranslationUnit.cpp#L245-L300. I think it basically boils down to calling clang_getCanonicalType on the type cursor.

**Comment by Andersbakken** [comment]
It does seem like clang_getCanonicalType is the key.

It should now resolve the type completely.

Can you see if this looks good?

regards

Anders

**Comment by RedBeard0531** [comment]
Yeah, seems to work well now. Thanks for fixing. I like that it is able to show both the "friendly" typedef name and what it actually resolves to in cases using complex typedef logic for metaprogramming. The only odd thing I see now is that the following shows the type of b as "int => int", but that doesn't really matter. 

```cpp
int a;
auto b = a;
```

**Comment by Andersbakken** [comment]
Ah. That's easily fixed though.

Thanks again.

Anders
