### ISSUE TITLE
"Unknown damned auto" logged for conditional expressions

### ISSUE THREAD

**Issue by RedBeard0531** [Andersbakken/rtags#829]
Saving a file with:

``` cpp
auto var = true ? 0 : 1;
//   ^     ^
//   6     12
```

results in a log message like:

```
Unknown damned auto!!! VarDecl cursor var def c:@var FILE:LINE:6 ConditionalOperator other FILE:LINE:12
```

rc -U gives the correct type for var, but the log message seems like a "file an issue if you see this" kind of thing.

**Comment by Andersbakken** [comment]
It should be fixed now. I had all this outrageous code to try to resolve
autos to their proper type but it seems in current versions
clang_getCanonicalType just does it for us.

Anders

**Comment by RedBeard0531** [comment]
Seems fixed. Thanks.
