### ISSUE TITLE
"make -nk | rc -c -" doesn't work.

### ISSUE THREAD

**Issue by comatose** [Andersbakken/rtags#830]
Precisely, "rc -c -" seems not to accept build commands from stdin.
rdm complains with a message "Nothing looks like a compiler".
Meanwhile, "make -nk | xargs rc -c" works perfect.

**Comment by Andersbakken** [comment]
Ah. Thanks.

It seems this one broke a week or two back. It should be fixed now. Can you
verify?

Anders

**Comment by Andersbakken** [comment]
Please reopen if it isn't fixed.

**Comment by comatose** [comment]
I've just verified that it works now.
Thanks!

**Comment by Andersbakken** [comment]
Glad to hear. Thanks

Anders
