### ISSUE TITLE
error: no member named 'vlog' in 'LogOutput'

### ISSUE THREAD

**Issue by handrake0724** [Andersbakken/rtags#831]
I have updated rtags recently with submodules and got the following errors:

rtags/src/Project.cpp:723:37: error: no member named
      'vlog' in 'LogOutput'; did you mean 'log'? output->vlog("<?xml version=\"1.0\" encoding...

rtags/src/rct/rct/Log.h:85:24: note: 'log' declared here
inline void LogOutput::log(const char *format, ...)
                       ^
rtags/src/Project.cpp:726:37: error: no member named
      'vlog' in 'LogOutput'; did you mean 'log'? output->vlog("(list 'progress %d %d)", idx, ...

**Comment by handrake0724** [comment]
it looks
output->log instead of output->log

**Comment by Andersbakken** [comment]
I had to rename to make it resolve the overloads correctly. You need to do:

git submodule update

Anders

**Comment by Andersbakken** [comment]
I think you need to do a git submodule update

regards

Anders

**Comment by handrake0724** [comment]
It works. Thanks.
