### ISSUE TITLE
Compilation fails on master

### ISSUE THREAD

**Issue by aport** [Andersbakken/rtags#833]
```
Scanning dependencies of target rtags
[  1%] Building CXX object src/CMakeFiles/rtags.dir/ClangIndexer.cpp.o
/home/aporter/Downloads/rtags/src/ClangIndexer.cpp: In member function ‘bool ClangIndexer::exec(const String&)’:
/home/aport/Downloads/rtags/src/ClangIndexer.cpp:134:9: error: ‘setRealPathEnabled’ is not a member of ‘Path’
         Path::setRealPathEnabled(false);
         ^

```

**Comment by cslux** [comment]
The class **Path** is part of the submodule `rtc`, you need to run `git submodule update` with, eventually, a `git submodule init` before, Than, you can compile rtags. See the [README](https://github.com/Andersbakken/rtags/blob/master/README.org) for further steps.

regards,
Christian

**Comment by aport** [comment]
Hi Christian,

Thanks for the response. The README does not contain this step, or any information about submodules aside from the initial `--recursive` flag during the clone instruction.

I guess this is my own fault, mercurial manages subrepositories automatically and I didn't know it's a manual process in git.

Anyway, it's all working now so I'll close this.

Thanks again.

**Comment by Andersbakken** [comment]
I think we maybe should add some cmake step that checks for the existence
of rct and outputs something appropriate if it can't be found.

Anders
