### ISSUE TITLE
Resolve "Type: <bound member function type>" in symbol-info

### ISSUE THREAD

**Issue by RedBeard0531** [Andersbakken/rtags#837]
``` cpp
struct Foo {
    void func(int i = 1, int j = 2) {}
};

void test() {
    Foo().func(3);
}
```

Current output at call site:

```
SymbolName: func
Kind: MemberRefExpr
Type: <bound member function type>
SymbolLength: 4
Range: 6:5-6:15
Arguments: 3, 
```

I think it should give the type of the called function (`void (int, int)` in this case). I often want to know the return type of a function at the call site and that is currently possible for free-functions but not for members. The follow-location command goes to the correct function definition so it should be able to resolve it's type.

This case should also be improved by #836.

**Comment by Andersbakken** [comment]
Should be fixed now. Not sure how to get the default arguments displayed yet.
