### ISSUE TITLE
Flush log output after each line

### ISSUE THREAD

**Issue by RedBeard0531** [Andersbakken/rtags#842]
RDM logs are automatically flushed at EOL when writing to a terminal. This doesn't happen when writing to a non-tty stdout, such as when running as a systemd service. In that mode, it will only flush stdout once the buffer is full which may not happen for a long time. This is problematic when using journalctl --user --follow to see when a reindex finishes. It will never output the final line unless enough commands are run to fill the output buffer.

**Comment by Andersbakken** [comment]
Sorry about the long delay. How are you logging in this circumstance. Is it
with --log-file or by redirecting stdout?

I guess adding a switch to flush after each line might be the way to go but
I just want to make sure the option does the right thing.

Anders

**Comment by RedBeard0531** [comment]
I am using the following systemd unit file which by default has all stdout and stderr sent to the systemd journal:

```ini
[Unit]
Description=RTags daemon

Requires=rdm.socket

[Service]
Type=simple
ExecStart=/usr/bin/rdm -j12
Nice=19
CPUSchedulingPolicy=batch
```

**Comment by Andersbakken** [comment]
Hi Mathias

Sorry about the long delay. I just added something that I think should take
care of it. Can you try?

The option is:

$ rdm --log-flush

Anders

**Comment by RedBeard0531** [comment]
Seems to be working. Thanks.
