### ISSUE TITLE
Source::parse No file for cc -c -m64

### ISSUE THREAD

**Issue by kvaneesh** [Andersbakken/rtags#846]
I started finding this recently. 

The output with rdm --verbose looks like this and the file /tmp/mm/init-mm.c is present 

Source::parse No file for cc -c -m64 -Wp,-MD,mm/.init-mm.o.d -nostdinc -isystem /usr/lib/gcc-cross/powerpc-linux-gnu/5/include -I/tmp/arch/powerpc/include -I/tmp/arch/powerpc/include/generated/uapi -I/tmp/arch/powerpc/include/generated -I/tmp/include -I/tmp/arch/powerpc/include/uapi -I/tmp/include/uapi -I/tmp/include/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -I/tmp/arch/powerpc -DHAVE_AS_ATHIGH=1 -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -msoft-float -pipe -I/tmp/arch/powerpc -mtraceback=no -mcall-aixdesc -mcmodel=medium -mno-pointers-to-nested-functions -mcpu=power7 -mno-altivec -mno-vsx -mno-spe -mspe=no -funit-at-a-time -fno-dwarf2-cfi-asm -mno-string -Wa,-maltivec -mbig-endian -fno-delete-null-pointer-checks -Wno-maybe-uninitialized -O2 --param=allow-store-data-races=0 -Wframe-larger-than=2048 -fno-stack-protector -Wno-unused-but-set-variable -fomit-frame-pointer -fno-var-tracking-assignments -g -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Werror=incompatible-pointer-types -DCC_HAVE_ASM_GOTO -DKBUILD_BASENAME="init_mm" -DKBUILD_MODNAME="init_mm" -o mm/.tmp_init-mm.o /tmp/mm/init-mm.c

For now rdm doesn't seem to parse any file.

**Comment by kvaneesh** [comment]
This is the stack for rdm

(gdb) bt
#0  0x00007ffff5c36e23 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84
#1  0x000000000089b619 in EventLoop::exec (this=0xd49fb0, timeoutTime=-1)
    at /home/opensource/sources/rtags/src/rct/rct/EventLoop.cpp:890
#2  0x0000000000752fa0 in main (argc=2, argv=0x7fffffffdcd8) at /home/opensource/sources/rtags/src/rdm.cpp:818

**Comment by mineo** [comment]
This is most likely fixed by https://github.com/Andersbakken/rtags/pull/840.

**Comment by kvaneesh** [comment]
I updated the branch and this fixed the issue. Thanks
