### ISSUE TITLE
distinction between member function and static function

### ISSUE THREAD

**Issue by handrake0724** [Andersbakken/rtags#851]
I have a class which has member functions and static functions as follows:

class argList {
public:
 const  fileName& caseName() const;
 static void addNote(const string&);
}

in the source code, auto completion is triggered by . and shows both member functions and static functions like
  caseName()
  addNote()

I think static functions should not be shown by .

**Comment by Andersbakken** [comment]
I completely agree but we don't really have enough information to easily
remove those candidates. I think this should be filed as a bug against
libclang TBH.

regards

Anders

**Comment by Smjert** [comment]
Sorry, just out of curiosity, why it's not possible?
If you have the CXXMethodDecl class representing the function, can't you check for isStatic()?

**Comment by Andersbakken** [comment]
The issue is that at that level we only have the CXCursorKind. We can't
really get the actual cursor from the completion API:

http://clang.llvm.org/doxygen/group__CINDEX__CODE__COMPLET.html

I'm sure clang itself has the information but just doesn't currently expose
it in the c api.

Anders

**Comment by Smjert** [comment]
Ah, was seeing in the doc that they also have a todo for it, so that they then return a full cursor.
Thanks for the clarifications :).

**Comment by RedBeard0531** [comment]
While rarely used in practice, member access notation is a legal way to refer to static members: http://en.cppreference.com/w/cpp/language/static

> To refer to a static member m of class T, two forms may be used: qualified name T::m or member access expression E.m or E->m, where E is an expression that evaluates to T or T* respectively.

I think clang is actually doing the right thing by including them (since it is a legal expansion) but sorting them last since it probably isn't what you want.

**Comment by handrake0724** [comment]
Thanks for the good information RedBeard0531.
