### ISSUE TITLE
rdm crashed error

### ISSUE THREAD

**Issue by realwakka** [Andersbakken/rtags#852]
Source::parse Nothing looks like a compiler
Failed to compile /usr/bin/CC List<String>(-x, c, -c, /tmp/rtags-compiler-check-a2TcpP.cc, -o, /tmp/rtags-compiler-check-a2TcpP.cc.out)
with ENV:
List<String>(SHELL=/usr/local/bin/bash, TERM=xterm-256color, SSH_CLIENT=192.168.10.50 42346 22, OLDPWD=/home/sidong/office, SSH_TTY=/dev/pts/3, LC_ALL=en_US.UTF-8, USER=sidong, ENV=/home/sidong/.shrc, PAGER=more, PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/home/sidong/bin, MAIL=/var/mail/sidong, LOCALE=en_US.UTF-8, BLOCKSIZE=K, PWD=/home/sidong/office/build/debug, EDITOR=vi, SHLVL=1, HOME=/home/sidong, LOGNAME=sidong, SSH_CONNECTION=192.168.10.50 42346 192.168.10.49 22, _=/usr/local/bin/rc)
stderr:

stdout:

Assertion failed: (proc.isFinished()), function isCompiler, file /home/sidong/rtags/src/Source.cpp, line 389.
Caught signal 6

I'm using freebsd 11
when I compile with "ninja -t commands | rc -c -" in my project, rdm crashed.
I think there is an error Source.cc::isCompiler function.

**Comment by Andersbakken** [comment]
Hi

Does it happen every time you run this command? I can't seem to reproduce
it here. I wonder if this possibly only happens on FreeBSD. I don't have a
setup for BSD at this point.

I can't offhand really see this could happen.

regards

Anders

**Comment by Andersbakken** [comment]
Strike that. I can reproduce it on mac. I'm on it.

Thanks for the report.

Anders

**Comment by Andersbakken** [comment]
Should be fixed now. Thanks.

Anders
