### ISSUE TITLE
Switch between symbol's declaration and definition?

### ISSUE THREAD

**Issue by handrake0724** [Andersbakken/rtags#856]
In rtags, is it possible to naviate between symbol's declaration and definition?
rtags-find-symbol-at-point always goes to declaration.

**Comment by Andersbakken** [comment]
Hi

Generally doing rtags-find-symbol-at-point behaves like this:

If you're on the definition: go to declaration
If you're on the declaration: go to definition
If you're on a reference: go to definition, failing that go to declaration

Are you finding that this is not the case? Can you reproduce in a small
example?

regards

Anders
