### ISSUE TITLE
Language server support

### ISSUE THREAD

**Issue by kvaneesh** [Andersbakken/rtags#857]
There is work happening to get different language indexer to work with common protocol. The details can be found at https://github.com/Microsoft/language-server-protocol . The emacs support for the client side is here https://github.com/sourcegraph/emacs-lsp/blob/master/lsp-mode.el . I am perfectly happy with what we have now. Just wondering whether the above is of any interest.

**Comment by Andersbakken** [comment]
Hi Aneesh

Sorry about the delay. It is definitely interesting but I am not convinced
there's much upside for RTags to fit into this. For one thing we have way
more types of commands and messages than what the elisp currently supports.

Thanks for the heads up though. It's very much relevant to RTags.

Anders

**Comment by teto** [comment]
LSP solves a real problem and has spurred quite a few projects in the limited timeframe it has existed. As RTags is already split into a client/server mode it's a perfect candidate for it. 
The real gain is in client support: it shoulw allow rtags to be queried from many more clients as a single LSP client would be needed across all languages with LSP support (see a list here http://langserver.org/)
There seems to be support for additionnal types of commands via: 
`ClientCapabilities.experimental`.
The easy way would be to have a proxy server that converts LSP request into Rtags and so forth. It could be an external project but in-house LSP support might be nice as well. It could mean removal of `rc` binary so it's not only code addition.

**Comment by Andersbakken** [comment]
The proxy support is appealing. I certainly wouldn't mind having support
for it. I'm just worried about giving up ease of development/functionality
for it. A proxy server done right should prevent these issues from being a
problem. I'd absolutely be receptive for code contributions that add this
support either inside rtags or on the outside.

Anders

**Comment by HighCommander4** [comment]
> Currently LSP is stuck with cquery or ccls.

Don't forget [clangd](https://clang.llvm.org/extra/clangd.html).
