### ISSUE TITLE
Fails on indirect buffers

### ISSUE THREAD

**Issue by Nephyrin** [Andersbakken/rtags#859]
Using `clone-indirect-buffer-other-window` (`C-x 4 c` by default) is very useful for working in multiple points in the same file, but rtags fails on the indirect buffer.

Quick googling suggests `buffer-base-buffer` will give a base buffer's base buffer, which will allow discovering the original file name.  It returns nil if this buffer is not an indirect buffer.

**Comment by Andersbakken** [comment]
Should be fixed now.
