### ISSUE TITLE
rc exits with 1 under /tmp directory

### ISSUE THREAD

**Issue by vladshablinsky** [Andersbakken/rtags#860]
Hi, I'm trying to run `rc` with `src` directory under `/tmp` directory.

```bash
$ tree /tmp
/tmp
└── src
    ├── README
    └── foo.c
$ cat /tmp/src/foo.c
void zaphod() {
}

void beeblebrox() {
  zaphod();
}
$ readlink /tmp
private/tmp
$ rdm -L log
```

And this step fails:

```
$ echo "clang -c /tmp/src/foo.c" | rc -c
```

But if I move the `src` somewhere else, it works fine.
Any ideas on how to fix this? I'm running macOS 10.12.

**Comment by Andersbakken** [comment]
Heh. We actually explicitly avoid indexing things inside /tmp

I believe I added that to avoid things like autoconf tests getting indexed.
I'll see if I can add an option to disable this behavior.

Anders

**Comment by dmakarov** [comment]
@Andersbakken this seems to be a big issue.  Since the version 2.3_1 released about a month ago, rtags hasn't been updated in Homebrew because the updated version doesn't pass the tests. The net result is that currently Homebrew version of rtags quickly becomes out of sync with the latest rtags emacs package, and renders rtags homebrew and emacs packages unusable, unless one is willing to install --HEAD version of rtags.

**Comment by Andersbakken** [comment]
Ah. Interesting. I actually have a switch for this already.

If you run:

$ rdm --help | grep exclude-filter

You can see the default exclude filter. Is there a simple way to modify
homebrew's tests? I actually don't really have anything to do with the
packaging of rtags in homebrew so I don't really know how to add a
parameter. In short I would say that the homebrew test should pass:

$ rdm --exclude-filter ""

Maybe the whole filter isn't that useful but I think I had some problems
where files that were part of configure time tests were indexed.

Anders

**Comment by vladshablinsky** [comment]
Thanks @Andersbakken! Maybe I should have dug the `rdm` help more. 🙂
Now tests are fixed!

**Comment by Andersbakken** [comment]
There's a ton of non-obvious switches in there so I don't blame you :-)

Awesome. Thanks

Anders
