### ISSUE TITLE
rtags-symbol-type

### ISSUE THREAD

**Issue by jchhk** [Andersbakken/rtags#861]
I updated rtags today to the current version and now rtags-symbol-type is no londer working.
No matter what project I get 'RTags: type not found'.
I have rebuild the database and recompiled my projects. All other rtags features seem to work like autocompletion and jumping to definitions.

I had a look in the elisp file to get down to the problem, although my elisp knowledge is not good. symbol-type relies symbol-info-internal. Calling rtags-symbol-info interactively does not produce any output. 

Any suggestions? Thanks!

**Comment by Andersbakken** [comment]
Hi

Sorry about the long delay. I can't seem to reproduce this. It works fine
for me.

Can you make sure you're up-to-date first (I've made some recent changes)
and then try this on the command line:

rc --elisp -U /Users/abakken/dev/rtags/src/Project.cpp:2416:5:

And send me the output. Replace the path to the file is replaced with an
appropriate path in your own project.

Anders

**Comment by jchhk** [comment]
Hi Anders,

thank's for spending your time on my issue.
The problem is present in rtags release 2.7 (rc --version reports 2.5.104)
and the current head in master commit df25eb25c4d8db6b2ceea106d067e50d56e22bd7 (rc --version reports 2.5.106)

_rc --elisp -f  src/main.cpp:124:38_
results in
**projects/Steuerung/src/main.cpp:97:27:  int main(int argc, char **argv)**
whereas 

**rc --elisp -U  src/main.cpp:124:38**
yields an exception

__terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error                                                                                                                                                    
Aborted (core dumped)__     

I hope that helps.

Jan

**Comment by Andersbakken** [comment]
Ah. I see what it is. Your gcc version doesn't support regexes. gcc version
< 4.9 doesn't properly support std::regex and we use that in the argument
parsing for -U. Any chance you'd be able to upgrade your gcc?

Anders

**Comment by jchhk** [comment]
Hi Anders,

you are right, I use gcc 4.8.4 and upgrading to 6.2 solved the problem. Anyway, before trying gcc6 I also used clang3.9 and the problem remained. I there a known problem with clang, too? 

Thank you!
