### ISSUE TITLE
Disable automatic completion with rtags.el

### ISSUE THREAD

**Issue by sdeber** [Andersbakken/rtags#863]
I am using Emacs + Company mode + rtags for C++. What happens is that every time I type something new, Rtags/Company will try to do some completion with the typed string. At the backend, it was calling this command "--synchronous-completions --code-complete-prefix XXX --elisp". How can I disable this feature? I just want Rtags to perform completion when I ask it to do so. 

I have tried to disable the auto completion/idle completion, etc in Company mode, but Rtags still tries to auto-complete things.

**Comment by Andersbakken** [comment]
Hi

I was able to make it not do this by customizing these two company settings:

 '(company-begin-commands nil)
 '(company-idle-delay nil)

Can you try that?

regards

Anders

**Comment by sdeber** [comment]
Thanks, that solves the problem.

**Comment by Andersbakken** [comment]
Glad to hear that.

Anders
