### ISSUE TITLE
rdm/rc can't find includes error when parsing with compile_commands.json

### ISSUE THREAD

**Issue by enzochiau** [Andersbakken/rtags#865]
I have a project use CMAKE to generate a compile_commands.json. When I run `rc -J <my json file path>`, I get load of errors such as can't find "stdarg.h", "stddef.h" etc and there's no members of bla bla.

Does anyone know how to fix this, thanks?

My Environment:
Default installed GCC: 4.8.5
GCC in JSON file: 6.1.0 (Installed at /opt/mmm/gcc-6.1.0)

CMake can generate proper binary files with error. (I think that means the compile_commands.json should be correct)

Work flow:
1. Start rdm :     rdm &
2. Generate JSON:     cmake -Bbuild -H. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
3. run rc:                       rc -J build

**Comment by Andersbakken** [comment]
Hi

Are you by any chance building a 32 bit app on a 64-bit system? If so, make
sure you install g++-multilib (or something like that).

If this is not the case I think clang will tell you what includepaths it's
using if you run: clang -v

Can you check if stdarg.h is in one of those dirs listed?

Anders

**Comment by enzochiau** [comment]
Thanks Andersbakken:

Here's the output of "clang -v":

    clang version 4.0.0 (trunk 287093)
    Target: x86_64-unknown-linux-gnu  
    Thread model: posix
    InstalledDir: /usr/local/bin
    Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.2  
    Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.5
    Selected GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.5
    Candidate multilib: .;@m64
    Candidate multilib: 32;@m32
    Selected multilib: .;@m64


Here are the two error messags:

    /usr/include/unistd.h:226:10: fatal error: 'stddef.h' file not found
    /usr/include/wchar.h:39:11: fatal error: 'stdarg.h' file not found


And here's the result of "locate xxx":

    /usr/include/linux/stddef.h
    /usr/lib/gcc/x86_64-redhat-linux/4.8.2/include/stddef.h
    /usr/local/lib/clang/4.0.0/include/stddef.h

    /usr/include/c++/4.8.2/tr1/stdarg.h
    /usr/lib/gcc/x86_64-redhat-linux/4.8.2/include/cross-stdarg.h
    /usr/lib/gcc/x86_64-redhat-linux/4.8.2/include/stdarg.h
    /usr/local/lib/clang/4.0.0/include/stdarg.h

I know the gcc-6.1.0 which is the one is used to compile the design is not listed here because it is a standard installation. But the full path of the binary and include paths for that version are in `compile_commands.json`. Dosen't rtags take that into account?

**Comment by Andersbakken** [comment]
Sorry about the delay.

I think this is an issue of rtags not knowing where your libclang resides,
possibly because we're making some assumptions that do not hold true for
clang 4.0.0.

Can you check what the defines CLANG_INCLUDE and CLANG_VERSION are set to
during compilation of RTags? (They're passed with -D on the command line)

Anders

**Comment by enzochiau** [comment]
To be honest, I have no idea what is CLANG_INCLUDE and CLANG_VERSION are. Tried to `echo` them. They are all empty. 

I tried to add "-DLIBCLANG_LLVM_CONFIG_EXECUTABLE=`which llvm-config`" to the `cmake` command line. I got the same error messages.


Another question, if I use `rc -J compile_commands.json`, isn't should use the include path from there? If it is not, then what's that JSON file for?

**Comment by Andersbakken** [comment]
These variables are used to locate where certain compiler specific headers
reside (things like stddef.h) and they can't be picked up from
compile_commands.json

If they're empty that's likely problematic.

It should use the include paths from compile_commands.json but these
headers are meant to be found in includepaths that are not specified there.

Did you clean out your build dir before rebuilding when specifying -
DLIBCLANG_LLVM_CONFIG_EXECUTABLE

CMake caches a lot of things.

Anders

**Comment by enzochiau** [comment]
I have done a clean build and I still have these errors:

    /usr/include/stdio.h:33:11: fatal error: 'stddef.h' file not found
    /usr/include/wchar.h:39:11: fatal error: 'stdarg.h' file not found

**Comment by Andersbakken** [comment]
Hi Enzo

Can you send me the output of the clean build?

Also, can you send me the output of these commands:

$ llvm-config --version
3.9.0
$ llvm-config --libdir
/usr/local/Cellar/llvm/3.9.0/lib

We make some assumptions about how clang is installed based on this.

I also think you can get by this by putting this in your ~/.rdmrc:
-I /usr/local/lib/clang/4.0.0/include/

Anders

**Comment by enzochiau** [comment]
$ llvm-config --version

    4.0.0.svn

$ llvm-config --libdir

    /usr/local/lib

Updated ~/.rdmrc:

    -I /usr/local/lib/clang/4.0.0/include


Now I have new error:

    /../lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/cstdio:120:11: error: no member named 'gets' in the global namespace

**Comment by Andersbakken** [comment]
I think there's something going on with your clang installation. Can you
see if you can compile a simple c++11 program with the clang binary from
your install?

regards

Anders

**Comment by Artem-B** [comment]
I've ran into the same problem. rdm 2.8 starts with empty include path. rdm 2.4 built with the same libclang was handling includes correctly. I've ended up manually added -isystem paths reported by my clang installation. The paths are printed by 'clang -v -x c -c -o /dev/null /dev/null':
```
...
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /usr/local/bin/../lib/clang/3.9.0/include
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
```
