### ISSUE TITLE
Dump declarations/definition symbols from file

### ISSUE THREAD

**Issue by jacobdufault** [Andersbakken/rtags#869]
Is there a way to dump all declaration/definition symbols from a file, for example, to create an outline view or similar?

**Comment by Andersbakken** [comment]
There is.

If you want it on the command line you can do something like this:

/Users/abakken/dev/rtags/bin/rc
--current-file=/Users/abakken/dev/rtags/src/FollowLocationJob.cpp
--path-filter=/Users/abakken/dev/rtags/src/FollowLocationJob.cpp
--kind-filter
-references,-vardecl,-parmdecl,-inclusiondirective,-*literal*,-enumconstantdecl,-classdecl-,-structdecl-,-classtemplate-,-statements,-lambdaexpr
 --wildcard-symbol-names --find-symbols

If you want it in elisp, take a look at rtags-imenu

Anders

**Comment by jacobdufault** [comment]
Perfect, that works very well, thanks.

**Comment by Andersbakken** [comment]
Glad to hear.

Anders
