### ISSUE TITLE
Command to show doxygen documentation of a symbol

### ISSUE THREAD

**Issue by dpelle** [Andersbakken/rtags#870]
Would it be possible for rtags to have a comment to show doxygen documentation (if any) of a symbol?

Note the the documentation may not always reside where the symbol is declared. For example, for a derived method, the documentation may be in the declaration of the method in the base class.

**Comment by Andersbakken** [comment]
Hi Dominique

We already have something for this actually but it didn't walk up the base
classes for virtual functions until now :-)

Basically to get the doxygen comment you can do:

(rtags-get-summary-text)

If you want only the comment you can do:

(rtags-symbol-info-internal :piece 'briefComment)

or

(rtags-symbol-info-internal :piece 'xmlComment)

Hope that works.

Anders
