### ISSUE TITLE
Is it possible to list which classes extend/implement another one?

### ISSUE THREAD

**Issue by tsmarques** [Andersbakken/rtags#874]
For instance

`class SuperClass {...};`

and

`class DerivedClass : public SuperClass {...};`

Is it possible to know that `DerivedClass` inherits from `SuperClass`? I see that `--find-virtuals` only finds functions' implementations

Thank you!

**Comment by Andersbakken** [comment]
Hi Tiago

It is indeed. M-x rtags-print-class-hierarchy  <ret>

or rc --class-hierarchy <location>

Anders

On Fri, Dec 16, 2016 at 11:28 AM, Tiago Sá Marques <notifications@github.com

**Comment by tsmarques** [comment]
I searched `man rc` and couldn't find anything, but then I forgot to check emacs's functions.

Thank you!

**Comment by Andersbakken** [comment]
My pleasure. Let me know if you have issues with it.

Anders
