### ISSUE TITLE
Support XDG basedir

### ISSUE THREAD

**Issue by ambihelical** [Andersbakken/rtags#877]
I think it would be good if rtags support XDG basedir specification (https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html).  

I pushed a branch with the code changes needed here: https://github.com/ambihelical/rtags/tree/xdg-basedir-support .  No documentation changes have been made yet.
Basically the approach is that if any existing configuration files exist, they are used, otherwise the XDG locations are used, although there may be bugs...  

Since this is a relatively intrusive change, I'm opening this bug for discussion on the merits of doing this at all, what else is needed, and any other feedback.

**Comment by Andersbakken** [comment]
Hi

I merged it in from your branch and it seems to work. Thanks.
