### ISSUE TITLE
rtags.el fails silently if version not in sync with rdm/rc

### ISSUE THREAD

**Issue by jlargentaye** [Andersbakken/rtags#879]
I was using rtags.el via ELPA (specifically, Melpa), with a 'system' rtags (rc/rdm) from MacPorts (this is on OS X). After a routine package update, some rtags commands in Emacs, such as rtags-find-symbol-at-point, started failing silently. That is, nothing happened and no error was reported. After some unsuccesful ELisp debugging, I finally realized that the system RTags was a different version than rtags.el. Since MacPorts didn't have an updated version, I compiled rc/rdm from source. This fixed the problem.

Could there be a version check in rtags.el to ensure it's talking to a version of rc that it's expecting?

**Comment by Andersbakken** [comment]
Hi John

I can see that being annoying :-)

I put something in that should prevent it. Thanks for the suggestion.

Anders

**Comment by jlargentaye** [comment]
Thanks! :)
