### ISSUE TITLE
rc --references doesn't support --json output mode

### ISSUE THREAD

**Issue by RedBeard0531** [Andersbakken/rtags#880]
I was trying to implement something like the emacs plugin's reference tree in vim and ran into this limitation. It already supports `--elisp` so I assume it is already set up to provide structured output. Alternatively, it would be even simpler to implement what I want if `--references` had a mode or an alternative query operator that would find references to the function containing a given location.

On a related note, it would be nice if there was a direct, top-level query for the location and containing function of a given location.

**Comment by Andersbakken** [comment]
Hi. Glad to hear it. I've fixed the json issue.

I also added a rather ludicrous query format for --symbol-info that allows you to do this.

I'm aware that the interface for this stuff is pretty outlandish and I would like to change it at some point but you can do something like this now:

Example usage:

$ rc --symbol-info /Users/abakken/dev/rtags/src/Symbol.cpp:28:13:@cf,cfl,location -K --json | json_pp
{
   "location" : "/Users/abakken/dev/rtags/src/Symbol.cpp:28:13:",
   "cf" : "const char *linkageSpelling(CXLinkageKind)",
   "cfl" : "/Users/abakken/dev/rtags/src/Symbol.cpp:26:27:"
}

Does this work out for you?

**Comment by RedBeard0531** [comment]
Thanks for the quick turnaround. I'll give it a shot next week. That looks like it will make it really easy to write a command that populates the location list with all references to the function the cursor is in. Mashing that will recursively walk the reference graph.

**Comment by Andersbakken** [comment]
I think it should give you the tools you need. Let me know if it falls
short in any way.

**Comment by RedBeard0531** [comment]
Seems to work well, thanks. When testing at the shell, I was a bit surprised that it didn't work in the default output format without --json, but using the command with vim's json parser worked just fine.

Currently all my changes to the vim-rtags plugin only live in my home dir, but I'll try to get them pushed to github sometime this month so others can use them.

**Comment by Andersbakken** [comment]
Awesome. Thanks. Let me know if there's any other features vim-rtags could
use.

Anders
