### ISSUE TITLE
rtags.el unable to find any results

### ISSUE THREAD

**Issue by sriramkswamy** [Andersbakken/rtags#896]
I'm on a Mac OS X 10.11.6 system and have installed rtags via homebrew. I tried running in both Emacs versions 25.1 and 26.0.5. I followed the *exact* procedure illustrated in [Quickstart](https://github.com/Andersbakken/rtags#tldr-quickstart) (except for building rtags, which I have from homebrew) and I get `RTags: No results` when I use `rtags-find-symbol` by keeping my cursor on `Server::instance` in `rdm.cpp`. My `rdm --version` is 2.5.111.

Here's the `RTags Log` -

```
**********************************
1485029032: --set-buffers files: /Users/sriramkswamy/Downloads/rtags/src/rdm.cpp
**********************************
1485029032: /usr/local/bin/rc --silent-query --silent -z --verify-version=119 --set-buffers -
**********************************
1485029047: /usr/local/bin/rc --current-file=/Users/sriramkswamy/Downloads/rtags/src/rdm.cpp -z --verify-version=119 -F instance --wildcard-symbol-names
**********************************
1485029049: --set-buffers files: /Users/sriramkswamy/Downloads/rtags/src/rdm.cpp
**********************************
1485029049: /usr/local/bin/rc --silent-query --silent -z --verify-version=119 --set-buffers -
```

I saw issue #818 and even disabled my completions.

Since I also use rtags with Vim, I think the problem isn't with the server/client because it functions perfectly with Vim. Please let me know if you need any more information.

**Comment by Andersbakken** [comment]
Can you try it on the command line first to see if the file is indexed?

E.g.

$ rc -f /Users/abakken/dev/rtags/src/rdm.cpp:73:34:
src/Server.h:55:20:         static Server *instance() { return sInstance; }

Anders

**Comment by sriramkswamy** [comment]
Yes, that gives the result as expected.

**Comment by Andersbakken** [comment]
Interesting. Can you try the whole line (found in *RTags Log*) that didn't
work? E.g. with verify-version and all that as well?

Anders

**Comment by sriramkswamy** [comment]
You mean this try a command like this?

```
rc --current-file=/Users/sriramkswamy/Downloads/rtags/src/rdm.cpp -z --verify-version=119 -F instance --wildcard-symbol-names
```

I get an error saying `--verify-version` is an invalid argument.

**Comment by Andersbakken** [comment]
Yeah.

I would like you to find the the command in your log that has a: -f (note
the lowercase) as well and see if that one works.

Anders

**Comment by sriramkswamy** [comment]
Alright. I'm just outlining the steps I did and the corresponding logs and commands

1. As soon as I opened the file `src/rdm.cpp`, the following was my log
```
**********************************
1485107881: --set-buffers files: /Users/sriramkswamy/Downloads/rtags/src/rdm.cpp
**********************************
1485107881: /usr/local/bin/rc --silent-query --silent -z --verify-version=119 --set-buffers -
**********************************
1485107966: /usr/local/bin/rc --current-file=/Users/sriramkswamy/Downloads/rtags/src/ -z --verify-version=119 --is-indexing
**********************************
1485107967: --set-buffers files: /Users/sriramkswamy/Downloads/rtags/src/rdm.cpp
**********************************
1485107967: /usr/local/bin/rc --silent-query --silent -z --verify-version=119 --set-buffers -
```

2. After keeping my point on 73:34, I tried the command `(rtags-find-symbol-at-point)`. My log is as follows
```
**********************************
1485108038: /usr/local/bin/rc --current-file=/Users/sriramkswamy/Downloads/rtags/src/rdm.cpp -z --verify-version=119 -f /Users/sriramkswamy/Downloads/rtags/src/rdm.cpp:73:35: --all-targets
**********************************
1485108038: /usr/local/bin/rc --current-file=/Users/sriramkswamy/Downloads/rtags/src/rdm.cpp -z --verify-version=119 -F instance --definition-only -M 1 --dependency-filter /Users/sriramkswamy/Downloads/rtags/src/rdm.cpp
**********************************
1485108038: /usr/local/bin/rc --current-file=/Users/sriramkswamy/Downloads/rtags/src/rdm.cpp -z --verify-version=119 -F instance -M 1 --dependency-filter /Users/sriramkswamy/Downloads/rtags/src/rdm.cpp
```

3. Now, I tried the same command in the terminal
```
rc --current-file=/Users/sriramkswamy/Downloads/rtags/src/rdm.cpp -z --verify-version=119 -f /Users/sriramkswamy/Downloads/rtags/src/rdm.cpp:73:35: --all-targets
```
I got the following message
```
Couldn't parse argument --verify-version=119
Try 'rc --help' for more information.
```

4. So, I tried it without the `--verify-version` argument like so
```
rc --current-file=/Users/sriramkswamy/Downloads/rtags/src/rdm.cpp -z -f /Users/sriramkswamy/Downloads/rtags/src/rdm.cpp:73:35: --all-targets
```
Now, it returned what is expected
```
src/Server.h:55:20:	    static Server *instance() { return sInstance; }
```

5. Knowing this, I commented out the following line from `rtags-call-rc` function in `rtags.el`
```
(push (format "--verify-version=%d" rtags-protocol-version) arguments)
```
Then, I byte-compiled it and loaded it again. Now, calling any `rtags-*` command gives me the correct result.

6. I evaluated the variable `rtags-protocol-version` and I get 119 to be the result and `rc --version` gives 2.5.111 to be the version. I'm not sure if this is a problem since `--verify-version` itself doesn't seem to an argument for `rc`.

This is all the information I could gather. Let me know if you need anything more.

**Comment by aafomin** [comment]
Got the same issue. Generally speaking, it's not a bug.
The last rtags release 6ac7740 doesn't have `--verify-version` option yet, but if one uses bleeding-edge (e.g. from MELPA) `rtags.el`, it results in a wrong `rc` invocation.
Looks like @sriramkswamy's case as well as mine.
