### ISSUE TITLE
rp process consumes a lot of memory

### ISSUE THREAD

**Issue by dpelle** [Andersbakken/rtags#897]
'rp' process is taking a lot of memory to index. Is there anything that can be done
about this, besides running less of them in parallel?

Here is a snapshot of what "top" on Linux reported:

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                    
18160 dope      22   2 9744532 8.090g   9832 S   0.3 25.8   4:25.01 rp                                                                                                                                         
18139 dope      22   2 8984628 7.524g   6080 S   6.0 24.0   4:25.16 rp                                                                                                                                         
18127 dope      22   2 7043808 5.812g   5572 S  37.5 18.5   4:41.42 rp      
```

The 3 rp processes use a lot of memory.  I have 32 Gb of RAM and yet at some
point my machine swapped.  The above 3 rp processes were the main
memory hog,  using 8GB + 7.5GB + 5.8GB = ~21.3 of RAM (resident memory)
according to top. That seems excessive.

I'm hoping that there is room for memory optimizations in rtags.  In the mean
time, I reduced the number of 'rp' processes I run in parallel, from 3 to 2.

I'm compiling c++ code which has templates. I suppose that long symbol
names with templates may contribute to memory usage (a guess). If more
information is needed from my, I could to profile memory use.

More info:

$ rc --version
2.5.109

$ rdm --version
2.5.109

**Comment by cslux** [comment]
@dpelle You seem to have a pretty old version installed, any chance you can install a more recent version and try it again? The latest released version is 2.9.

regards,
Christian

**Comment by chep** [comment]
I have the same problem. When I save a file, rp is started. It uses 100% of the CPU for a while (compiling I think) and then stay here using ~0.8G per instance. I need to kill it when I want to compile to avoid oom.

**Comment by Andersbakken** [comment]
Ah. This is kinda by design actually. We’re keeping the processes around
because reparsing is way faster.

You can opt out of this behavior by doing this:

rdm --daemon=false

Or do this:

echo --daemon=false >> ~/.rdmrc

Anders

**Comment by chep** [comment]
Thanks it works. Now I only have rdm running. It also consumes a lot of memory and grows continually but I think this is #1278.
