### ISSUE TITLE
Compilation fails with Clang, works with g++

### ISSUE THREAD

**Issue by alexey-sidelnikov** [Andersbakken/rtags#898]
On Ubuntu 14.04 with Clang 3.4 and CMake 3.3.2, rtags is only compilable with CXX_COMPILER set to g++. If CXX_COMPILER is Clang, Symbol.cpp gives an error on line 79:
"return type 'const String' must match previous return type 'String' when lambda expression has unspecified explicit return type"

**Comment by Andersbakken** [comment]
I believe this is fixed now.

**Comment by kangjoni76** [comment]
@Andersbakken Cmake exe linker flags ```` -lstdc++```` isn't appropriate for cmake cxx compiler is clang++ with libc++ part at this 
````
set(RTAGS_LIBRARIES ${RTAGS_LIBRARIES} -lstdc++ ${RCT_LIBRARIES})
````
in https://github.com/Andersbakken/rtags/blob/master/src/CMakeLists.txt

I've run above case with only remove ````-lstdc++ ```` part .
The cmake cxx flags ````-stdlib=libc++```` does handle at right job implicitly without any adding ldflags such as  ```` -lc++ -lc++abi```` . A simple check CMAKE_CXX_COMPILER_ID should suffice for most use case.

**Comment by Andersbakken** [comment]
Hi

Feel like whipping up a little PR for this?

Anders
