### ISSUE TITLE
Cache database into memory to reduce query time.

### ISSUE THREAD

**Issue by skt041959** [Andersbakken/rtags#901]
Hi developer,

Since I must store the database files in a NFS filesystem, that IO actions consume too much time.
Could you please make the rdm read databases into caches at restore stage?
Thank you.

**Comment by aaptel** [comment]
you can use a tmpfs disk as a workaround (filesystem in memory), you will lose the content after a reboot however. unless you script something to backup/restore on shutdown/startup of rdm or the computer.

https://www.jamescoyle.net/how-to/943-create-a-ram-disk-in-linux

**Comment by skt041959** [comment]
@aaptel Thank you! Maybe it is the most convenient way.

**Comment by Andersbakken** [comment]
Sorry about the delay. I kinda think the ramdisk might be the best way. We
used to use an in-memory database but fragmentation would often cause rdm
to balloon to several gigs worth of memory use on mid-size to large
projects.

Anders
