### ISSUE TITLE
rc slow/ hangs when calling rtags-find-symbol

### ISSUE THREAD

**Issue by deuscovrigus** [Andersbakken/rtags#903]
I have been having an issue lately after updating to the latest commit. Find symbol at point takes a long time and the rc call seems to hang as well as emacs becoming unusable until the call is complete or I press C-g. I'm talking about 180s to 200s per call.  Once I wait that long the definitions are followed through fairly fast unless I don't use rdm for a while. As far as I can tell it seems like rdm goes in sleep mode and then it takes time to load the search database. It sounds a little honky but I don't have enough information at this point

So I am mainly looking for ways to debug and see why rc hangs. I think I enabled rdm in verbose mode. 
Like here is an example of a call that lasts a long time
Here's an example how rc is being invoked via rtags-find-symbol-at-point
/usr/local/bin/rc --current-file=/home/prj/janus/src/net/vsi/train_with_pose_jittering.hxx -b -z --verify-version=119 -f /home/prj/janus/src/net/vsi/train_with_pose_jittering.hxx:95:16: --all-targets

Eventually it does find it but after like 300s. After that, searches are fast again.
Any ideas how I might be able to debug this or get some insights?
I've been using rdm for a while now and I love it but this issue has gotten me a bit frustrated.

**Comment by quicknir** [comment]
I had similar issues. I didn't quite follow Andersbakken's explanation, but basically it seems like the server has to communicate stuff to the client all the time, and when they don't talk for a while a backlog builds up and it takes a while to send that information over. Try running rdm with the option `--poll-timer 5`. This basically forces this communication every 5 seconds. This helped me.

**Comment by Andersbakken** [comment]
Tbh I think this is because of slow filesystem access. The poll timer
business basically ocassionally stats and mmaps the entire db to try to
warm up the file system caches etc.

If you can reliably reproduce this (even if you have to wait some hours
first it would be interesting to stick a bunch of prints in  and see where
the time is spent. My guess is the mmap. If rdm is indeed churning away at
something in userland I'd love to be able to fix that.

Anders

**Comment by deuscovrigus** [comment]
So I am using the poll-timer 5 and after idling 40m the jump to point and completions are still snappy.
Unfortunately you will need to hold my hand and tell me the source lines that I need to instrument/time where mmap is called . I would love to help and do this experiment on my system.

**Comment by deuscovrigus** [comment]
I've been experimenting with the behaviour for the past couple of days on the latest commit 2089bd4 and although i start rdm --poll-timer=5 issues remain unchanged. So after a period of not using a project , a rc code complete call can take up to 5 minutes before it becomes snappy again again the same rc call is instant. This is really annoying and I don't recall this behavior in the past.  Is there a specific function I need to instrument?

I was looking at line 1422 of Project.cpp:
   auto symbols = openSymbols(location.fileId());
Do I understand correctly that you suspect that the underlying call to openFileMap on line 99 of Project.h might be the culprit ?

**Comment by deuscovrigus** [comment]
I've been doing some instrumentation on the FollowLocationJob::execute() method of FollowLocationJob.cpp file
I timed the Symbol symbol = project()->findSymbol(location, &idx); 
whenever this function is called I timed  the line auto symbols = openSymbols(location.fileId());

And finally back into FollowLocationJob::execute()  I timed the line 
  auto targets = project()->findTargets(symbol).toList();

After a long wait of rdm these are the results of a rc call:

 retrieved file map in 5.38e-05 s ( called by findSymbol)
 find Symbol took 9.0367e-05 s (findSymbol in FollowJobLocation::execute())
  target retrieval and sorting took 100.224 s (findTargets(symbol).toList()) 
 target writing took 0.000173022 s for 1 targets (writeTarget() )

So the target retrieval took 100s, after a long idle time, however another rc call at the same location produces:

retrieved file map in 4.6661e-05 s
 find Symbol took 8.0361e-05 s
 target retrieval and sorting took 0.226799 s
 target writing took 0.000131124 s for 1 targets

So, something inside findTargets slows it down after a long wait. I suspect something in findByUsr but i'm not sure.

**Comment by Andersbakken** [comment]
Yeah. findByUsr is a possible culprit since it sometimes has to open every
file in the project to see which usrs match and not. We could maybe
construct some index after a little time of idleness. It's odd that it's
changed recently though. I don't think I've made any changes in that
general area lately.

Anders

**Comment by deuscovrigus** [comment]
Ok so after an idle time of a few days i let rdm sleep and a findSymbolJob was broken down like this:
(I decided to instrument findByUsr)
find by Usr took 217.057 s
 find targets took 217.192 s
 target sorting took 1.947e-06 s
 target writing took 0.0136353 s for 1 targets

Repeating the same call (after the file system got warmed up) yields:

find by Usr took 0.17356 s
 find targets took 0.201646 s
 target sorting took 1.522e-06 s
 target writing took 6.5951e-05 s for 1 targets

Ok so this behavior doesn't happen on my OS X because I suspect I have my rtags cache on an ssd rather than my ubuntu system which is on a spinning disc. Also, unlike the project on the mac, I work with deep networks implemented in dlib (http://dlib.net/) where deep networks C++ types are heavily templated , using recursive template instantiation , sometimes with a depth of 52 . One example of such a deep network is here on line 55 (although not as deep as the ones i'm using )
https://github.com/davisking/dlib/blob/master/examples/dnn_imagenet_train_ex.cpp

I did notice that the slow down occured since I worked on this project. Also, clang gave a warning when parsing the project files on increasing the template instantiation depth. I don't know if this is related or not but it's a noteworthy difference from my setup in the past.

**Comment by deuscovrigus** [comment]
Ok after another run of instrumenting I noticed that the slowest part of findByUsr  is the dependency search part which gets called when the cursor is over a templated type/function/class in my project with a recursive depth of 100+ (i.e.
```
  if (ret.isEmpty() || (!filtered.isNull() && ret.size() == 1 && ret.begin()->location == filtered)) {
        for (const auto &dep : mDependencies) {
```
Here, it seems that all possible source files that instantiate / specialize a template are included in mDependencies and loading all of them takes about 200ish seconds on the first call of followJobLocation::execute() and then it's pretty much 0.2 s , after the filesystem got warmed up.

Is there any way to keep this mDependencies list in memory somehow or to have it refreshed more often?

I would rather sacrifice memory than wait 3-4 minutes for a call.

**Comment by Andersbakken** [comment]
Hi

Sorry about the delay. Good debugging job :-)

I have to dig into that code to remember exactly why we needed to look
through all files for templates like that. I'll try to take a peek at that
logic again.

Anders

**Comment by deuscovrigus** [comment]
Just some quick updates, putting the cache on an SSD, and poll-timer=300 seemed to alleviate this issue on my end. However, for a spinning disk with a heavily templated project, all files that specialize/instantiate templates will be opened/refreshed when followJobLocation::execute() is triggered by having a cursor over code that has template arguments.  Maybe this can be improved?

**Comment by Andersbakken** [comment]
So I'm not 100% sure this is fixed but I'm hoping it's at least better. Do you have a chance to check one of these days?

**Comment by deuscovrigus** [comment]
Just checked out and reindexed my projects. I'll leave it idle for a while to see if the refresh on a template symbol will be faster. I switched my cache on the spinning disk to simulate my previous setup.

**Comment by Andersbakken** [comment]
Thanks. Much appreciated.

Anders

**Comment by deuscovrigus** [comment]
Ok so the search is much speedier however, not all definitions are found if calling rtags on a symbol found in a header, hxx or hpp. For example in the project file https://github.com/davisking/dlib/blob/master/dlib/any/any_function_impl.h:511,
A jump to the definition scoped_ptr produces no results when using a rtags build at 843dd06.
I reverted to  2089bd4 and , although the search is slow ( findByUsr probably looks through all files containing template instantiations across the entire projects), the correct definition is found. I'm thinking now whether it is possible at all to look for a templated class definition without looking through all possible source files that instantiate templates.

**Comment by quicknir** [comment]
> I'm thinking now whether it is possible at all to look for a templated class definition without looking through all possible source files that instantiate templates.

I'm not sure if I really follow this or not, but if there is a primary definition then it should be possible to find it in exactly the way as other symbols. From the perspective of goto definition, a declaration for `template <class T> struct Foo;`, and its corresponding primary definition, should not be much different than for a non-template struct. It's only once you start adding specializations that things become completely borked.

Also that link you posted is broken for me.

**Comment by deuscovrigus** [comment]
I updated the link. You are right about the template declaration and its primary definition should be pretty clear. In any case, right now go to definition on template members and classes declared in headers doesn't work for me
