### ISSUE TITLE
Support for ivy

### ISSUE THREAD

**Issue by jbeigel** [Andersbakken/rtags#910]
Are there plans to add ivy support, i.e. helm-ivy as an alternative to rtags-helm?

**Comment by Andersbakken** [comment]
Hi Johannes

Sorry about the delay.

We don't have any current plans but certainly wouldn't mind. I personally
don't use either helm or ivy so I'm not entirely sure what goes into making
rtags support ivy. (the helm support came about through some
contributions). We'd gladly accept contributions in this area. Are you
familiar with what goes into adding ivy support?

Anders

**Comment by jbeigel** [comment]
Hi,

I tried to implement a minimal solution and created a pull request.

Johannes

**Comment by Andersbakken** [comment]
I merged the request. Thanks.
