### ISSUE TITLE
Require GCC 4.9 or higher, or use boost::regex

### ISSUE THREAD

**Issue by yurikhan** [Andersbakken/rtags#914]
The code attempts to use `std::regex` in many places. Before GCC 4.9, this compiles but fails at runtime, either by throwing exceptions, or by returning wrong results.

**Comment by aleloi** [comment]
I can confirm that I have run in to the same problem. Running `rc --symbol-info` after compiling with libraries from old GCC crashes at runtime. See also Andersbakken/rtags#912

**Comment by yurikhan** [comment]
Okay, I recompiled with #912 and cannot reproduce my crashes any more.
