### ISSUE TITLE
rc -w / --current-project reports incorrect result

### ISSUE THREAD

**Issue by jlargentaye** [Andersbakken/rtags#917]
I have three projects (each with with their own compile-commands.json loaded via rc -J):

    $ rc -w
    /Volumes/cswork/a/ <=
    /Volumes/cswork/c/
    /Volumes/cswork/b/

However, rc is always reporting /a/ as the current project, whichever the PWD or --current-file:

    $ cd /Volumes/cswork/c
    $ pwd
    /Volumes/cswork/c
    $ rc -w 
    /Volumes/cswork/a/ <=
    /Volumes/cswork/c/
    /Volumes/cswork/b/
    $ rc --current-file /Volumes/cswork/c/target/tests/crc/crc_test_main.c --current-project
    /Volumes/cswork/a/

**Comment by cslux** [comment]
If you want switch project from the *cmd* use the flag `-w`, in your case:

```
$ rc -w /Volumes/cswork/c/
```
