### ISSUE TITLE
rtags-compile-file should execute in the correct directory

### ISSUE THREAD

**Issue by dzhu** [Andersbakken/rtags#918]
I have a CMake project using an out-of-source build. Running `rtags-compile-file` from Emacs executes the correct command, but with the working directory set to the directory that the source file is in, rather then the build directory, so `.o` files appear next to the source.

**Comment by Andersbakken** [comment]
Good point. I also seemed to have stripped out the -o argument previously. Both things should work now I think. 

Thanks for the report.
