### ISSUE TITLE
Couldn't parse argument --load-compilation-database

### ISSUE THREAD

**Issue by joshua-schwartz-netapp** [Andersbakken/rtags#920]
I just installed rtags on Monday and I'm getting the following error:

```
$ ls -l compile_commands.json
-rw-rw-r-- 1 jbschwar jbschwar 1078157 Mar 15 14:44 compile_commands.json
```
```
$ rc --load-compilation-database .
Couldn't parse argument --load-compilation-database
Try 'rc --help' for more information.
```

```
$ rc --version
2.8.116
```

Note that rc -J works just fine, only the long argument version seems to be broken.  This is inconvenient for me though because my organzation uses --load-compilation-database in the provided way to generate the rtags index for our build system.

**Comment by cslux** [comment]
@joshua-schwartz-netapp The man pages are out of date. It's `--load-compile-commands` now.

regards,
Christian
