### ISSUE TITLE
Emacs functionality sensitive on trailing slash to --project-root

### ISSUE THREAD

**Issue by helixhorned** [Andersbakken/rtags#923]
When passing a path to `rc -J --project-root` that does not contain a trailing slash, navigation in Emacs (for example `rtags-find-symbol-at-point`) does not work. Instead of opening the proper file, it wil open a new empty buffer. Adding a trailing slash to the `--project-root` argument makes everything work fine.

As far as I can see, this was introduced between tags `v2.7` and `v2.8`. It may be the case that this is only an issue of the Elisp code as there was a large rewrite of the relevant functinality in `rtags.el` between those tags. I haven't bisected further, though.

**Comment by helixhorned** [comment]
Example to reproduce: try `C-c r .` on the `resolveAuto` declaration in `RTags.h`.

**Comment by Andersbakken** [comment]
Thanks. Should be fixed now. Note that you need to remove and recreate your existing project.
