### ISSUE TITLE
Ability to limit number of concurrent rp processes

### ISSUE THREAD

**Issue by hessryanm** [Andersbakken/rtags#925]
Similar to #924 I have issues with rtags taking too many system resources while compiling.

For me, I have 4-9 rp processes, each often taking up to 80+% of my cpu (according to my activity monitor).  Is there any way to limit this to like 2?

**Comment by Andersbakken** [comment]
Hi

Sure thing. You can run rdm with -j 2

E.g. 

$ rdm -j 2

or 
$ cat ~/.rdmrc
-j 2 

Anders

**Comment by hessryanm** [comment]
Thanks!  I saw this option in the --help for the rdm binary, but when I added "--job-count" to the plist, it didn't do anything.  Adding it to .rdmrc worked though!  I'm not sure if that was an issue with the plist or the long option.
