### ISSUE TITLE
RPATH config in src/CMakeLists.txt

### ISSUE THREAD

**Issue by kastiglione** [Andersbakken/rtags#926]
I noticed the resulting binaries had an rpath that looked strange, it was `:` (colon) followed a path to the rtags `lib` dir.

I found in `src/CMakeLists.txt` that `CMAKE_INSTALL_RPATH` is being set like so:

```cmake
set(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_RPATH}:${CMAKE_INSTALL_PREFIX}/lib")
```

If `CMAKE_INSTALL_RPATH` is empty, then this results in the `:` prefixed path I saw. On macOS, I don't think such a value is a valid rpath. Also, the documentation for `CMAKE_INSTALL_RPATH` says it's:

>  A semicolon-separated list

I'm not a cmake expert, but I think this means `CMAKE_INSTALL_RPATH` may need to be set like this:

```cmake
list(APPEND CMAKE_INSTALL_RPATH ${CMAKE_INSTALL_PREFIX}/lib)
```

thanks for rtags!

**Comment by Andersbakken** [comment]
We don't really need an rpath at all anymore since we're now building only static libs.

**Comment by kastiglione** [comment]
I actually like the use of rpath. In my setup, I copy libclang.dylib to `${CMAKE_INSTALL_PREFIX}/lib` which the rtags binaries were already referencing. This gives me a self contained install.

**Comment by Andersbakken** [comment]
Ah. I can bring it bring it back.

Anders
