### ISSUE TITLE
Following TLDR Quickstart: `rtags-find-symbol-at-point` errors: "Can't find rc"

### ISSUE THREAD

**Issue by ackalker** [Andersbakken/rtags#927]
Using Void Linux x86_64 (glibc), Emacs 25.1.1.
Following the TLDR Quickstart to the letter, I get stuck at the last step:

> Call `rtags-find-symbol-at-point`
> 
>   `M-x rtags-find-symbol-at-point RET`

(note: I had to manually move point to be in `Server::instance()`, I guess that the Quickstart and the actual position in the source have drifted apart somewhat.)

This produces the message `Can't find rc` in the minibuffer.
As per the Quickstart, I've built RTags from source, and so the directory containing `rc` is not (yet) on my `$PATH`.

I tried: `M-x set-variable RET rtags-path RET "./bin/" RET` and retried the last step, but to no avail: the same error: `Can't find rc`.

Next, I exited Emacs, then in the shell in which I built RTags and from which I started Emacs, I did:
```sh
$ export PATH=$(pwd)/bin:$PATH
```
and redid all the steps involving Emacs. This worked, location was now on the definition of `Server::instance()`.

Perhaps this workaround (or a better one) could be added to the Quickstart. Thanks in advance.

**Comment by cslux** [comment]
Sorry for the late reply.

Interesting, I tried it several times, the days back when I updated the README, must had `rc` in the PATH environment variable.

> I tried: M-x set-variable RET rtags-path RET "./bin/" RET and retried the last step, but to no avail: the same error: Can't find rc.

You provided the wrong path, either relative or absolute when you in the buffer `rdm.cpp` you would have to set it to _"../bin"_.

I have updated the README.

Thanks for the report!

regards,
Christian
