### ISSUE TITLE
README.org: Hook `c-mode-common-hook` is too broad, `c++-mode-common-hook` not used by Emacs at all

### ISSUE THREAD

**Issue by ackalker** [Andersbakken/rtags#928]
The text mentions the following snippet to start `rdm` unless it is already running:
```elisp
(add-hook 'c-mode-common-hook 'rtags-start-process-unless-running)
(add-hook 'c++-mode-common-hook 'rtags-start-process-unless-running)
```
From `describe-variable` and [this page](https://www.gnu.org/software/emacs/manual/html_node/ccmode/CC-Hooks.html) in the Emacs manual, I gather that `c-mode-common-hook` applies to **all** languages supported by CC Mode, which include Java, IDL, Pike and AWK, and that `c++-mode-common-hook` isn't used at all.
If the intent is to limit to only the subset of languages which RTags supports, I think it is better to use:
```elisp
(add-hook 'c-mode-hook 'rtags-start-process-unless-running)
(add-hook 'c++-mode-hook 'rtags-start-process-unless-running)
(add-hook 'objc-mode-hook 'rtags-start-process-unless-running)
```

**Comment by cslux** [comment]
Good point @ackalker. 

This also affects `flycheck-rtags.el`

**Comment by Andersbakken** [comment]
Thanks. Fixed now.
