### ISSUE TITLE
Display location stack as list

### ISSUE THREAD

**Issue by kastiglione** [Andersbakken/rtags#929]
I find moving backward/forward through the location stack can be too granular at times. My feature request is to have some way to show the location stack as a list in a frame, showing filename, line number, and function if applicable. From this list you could directly go back to the desired location.

**Comment by Andersbakken** [comment]
I just added something. It's called rtags-location-stack-visualize. 

Let me know what you think. I'm confident it has some usability issues but it's a start.

**Comment by kastiglione** [comment]
Thanks! I'll check it out
