### ISSUE TITLE
Byte compiler errors when updating from MELPA

### ISSUE THREAD

**Issue by ackalker** [Andersbakken/rtags#930]
- Emacs 25.1.1 on Void Linux x86_64 (glibc)
- `use-package` installed from MELPA; `use-package-always-ensure` set to `t`, `use-package-always-defer` set to `t`
- `autocomplete` *not* installed
- `company` installed from MELPA using `use-package`
- `helm` installed from MELPA using `use-package`
- `ivy` *not* installed
- RTags C++ part built from source, `rtags` package installed from MELPA using `use-package`

I got the following byte-compiler errors when I tried to update `rtags` from MELPA today:
```
Leaving directory ‘/home/miki/.emacs.d/elpa/rtags-20170323.2309’

Compiling file /home/miki/.emacs.d/elpa/rtags-20170323.2309/company-rtags.el at Sun Mar 26 18:24:07 2017
Entering directory ‘/home/miki/.emacs.d/elpa/rtags-20170323.2309/’

Compiling file /home/miki/.emacs.d/elpa/rtags-20170323.2309/flycheck-rtags.el at Sun Mar 26 18:24:07 2017

Compiling file /home/miki/.emacs.d/elpa/rtags-20170323.2309/rtags-ac.el at Sun Mar 26 18:24:07 2017

Compiling file /home/miki/.emacs.d/elpa/rtags-20170323.2309/rtags-helm.el at Sun Mar 26 18:24:07 2017

Compiling file /home/miki/.emacs.d/elpa/rtags-20170323.2309/rtags-ivy.el at Sun Mar 26 18:24:07 2017

Compiling file /home/miki/.emacs.d/elpa/rtags-20170323.2309/rtags.el at Sun Mar 26 18:24:08 2017

Compiling no file at Sun Mar 26 18:24:08 2017
Error (bytecomp): Cannot open load file: No such file or directory, auto-complete
Error (bytecomp): Cannot open load file: No such file or directory, ivy
```
`rtags` appears to work correctly, but after the package update Emacs suggests me that `rtags` package is no longer needed can be autoremoved. When I follow that suggestion as an experiment, `rtags` gets installed from MELPA again at the next start of Emacs, and the cycle repeats.
I'm not sure, but I guess the autoremove suggestion happens because `rtags` somehow wasn't registered correctly because of the byte-compile errors.

**Comment by ackalker** [comment]
Note: recent version of `package` somehow collects byte-compile messages in a buffer which it displays at the end of updates. I find that the messages are often incomplete or contains strange messages like the `Compiling no file ...` above.

**Comment by cslux** [comment]
We should put `rtags-helm.el, rtags-ivy.el, rtags-ac.el, flycheck-rtags.el and company-rtags.el` in sperate MELPA package.

**Comment by cslux** [comment]
@Andersbakken I have renamed some files and the variables and functions (https://github.com/cslux/rtags/commit/08b57b49d4844423e8a72990ae43d00854a390c6), to follow the emacs naming convention, and to prepare for to MELPA split https://github.com/cslux/melpa/commit/0c6d30acf6c960c161b4e69402fbe48e55e14df2.

Is this ok with you?

This will break the setup of the people who are using one of the effecting files:
  - rtags-ac.el   -> ac-rtags.el
  - rtags-ivy.el   -> ivy-rtags.el
  - rtags-helm.el   -> ac-rtags.el

But should be easily to fix by search and replace.

Chris

**Comment by cslux** [comment]
Done! Will probably take 1-3 days until the packages are available in MELPA.

**Comment by Andersbakken** [comment]
Cool. Thanks.

**Comment by cslux** [comment]
The melpa maintainer have merged the PR. The packages should be available in about 12-24 hours via the MELPA repository.

Cheers

**Comment by douglarek** [comment]
After the package update Emacs suggests me that rtags package is no longer needed can be autoremoved? anyone got it ? Emacs 25.2
