### ISSUE TITLE
rtags-update when open elisp file on mac

### ISSUE THREAD

**Issue by dubnde** [Andersbakken/rtags#931]
I am seeing `rtags-update` running and freezing emacs whenever I start emacs on my mac. I do not really know what causes it but just loading the package causes this. Even without configuring anything in the package.

I need some help on how to go about debugging the issue. I have the same configuration on a `ubuntu` machine and I do not see the issue. Any help on how I can go about debugging the issue as emacs freezes?

**Comment by dubnde** [comment]
Updated and don't see issue anymore

**Comment by Andersbakken** [comment]
Sounds good. Let me know if it starts happening again.

Anders
