### ISSUE TITLE
Not possible to build the project from release tarball because rct is not included

### ISSUE THREAD

**Issue by gerddie** [Andersbakken/rtags#935]
*src/CMakeLists.txt* expects that the sub-project *rct* is located in the according sub-directory, but this is empty in the release tarball. 

Building from tagged releases is of interest for integration in Distributions, and providing an option to use an installed version of *rct* (and tag a release there) would probably be the best approach to resolve this issue.

**Comment by Andersbakken** [comment]
Yeah. It's a bit of a pain in the ass. I suppose we could make rct into something like a system library but it seems like github should have a better system for submodules in this regard. I'll see what I can do.

**Comment by Andersbakken** [comment]
We do have release tarballs here btw:

https://andersbakken.github.io/rtags-releases/rtags-2.9.tar.bz2

Anders

**Comment by gerddie** [comment]
That link doesn't seem to work, and on https://github.com/Andersbakken/rtags-releases I only see unversioned tarballs.

**Comment by Andersbakken** [comment]
Odd. It works for me.

Note that you need to check out the gh-pages branch to see the contents for
github.io.

Anders

**Comment by gerddie** [comment]
I seen, but then  the URL for a direct download is actually https://github.com/Andersbakken/rtags-releases/blob/gh-pages/rtags-2.9.tar.bz2 
thanks anyway.

**Comment by Andersbakken** [comment]
I don't know what differs in our setups but the url I gave you works
perfectly for me whereas the blob one sends to an html page. This page has
a download button that points right back to the url we're actually using. I
wonder if this could be some browser thing you have set up. Can you try
this in a terminal and see what it says:

curl -v https://andersbakken.github.io/rtags-releases/rtags-2.9.tar.bz2 >
/dev/null

I get this:

  % Total    % Received % Xferd  Average Speed   Time    Time     Time
 Current
                                 Dload  Upload   Total   Spent    Left
 Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--
  0*   Trying 151.101.128.133...
* TCP_NODELAY set
* Connected to andersbakken.github.io (151.101.128.133) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: www.github.com
* Server certificate: DigiCert SHA2 High Assurance Server CA
* Server certificate: DigiCert High Assurance EV Root CA
> GET /rtags-releases/rtags-2.9.tar.bz2 HTTP/1.1
> Host: andersbakken.github.io
> User-Agent: curl/7.51.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: GitHub.com
< Content-Type: application/x-bzip2
< Last-Modified: Mon, 03 Apr 2017 17:00:33 GMT
< Access-Control-Allow-Origin: *
< Expires: Tue, 04 Apr 2017 17:25:32 GMT
< Cache-Control: max-age=600
< X-GitHub-Request-Id: BA7E:243D:3B1C320:50E9899:58E3D4B4
< Content-Length: 3300678
< Accept-Ranges: bytes
< Date: Tue, 04 Apr 2017 17:18:20 GMT
< Via: 1.1 varnish
< Age: 168
< Connection: keep-alive
< X-Served-By: cache-sjc3640-SJC
< X-Cache: HIT
< X-Cache-Hits: 1
< X-Timer: S1491326300.547988,VS0,VE4
< Vary: Accept-Encoding
< X-Fastly-Request-ID: 56520d6daa62184457ff5e63fee915b2b12b8cdd
<
{ [2160 bytes data]
* Curl_http_done: called premature == 0
100 3223k  100 3223k    0     0  21.3M      0 --:--:-- --:--:-- --:--:--
21.4M
* Connection #0 to host andersbakken.github.io left intact

Anders

**Comment by gerddie** [comment]
Now it actually works. could have been my internet connection, sometimes it has hiccups.

**Comment by Andersbakken** [comment]
Glad to hear.

Thanks.

Anders
