### ISSUE TITLE
 fatal error: 'float.h' file not found

### ISSUE THREAD

**Issue by wood9366** [Andersbakken/rtags#940]
I update rtags to version 737b4e82c97a46f3f9fc318b8cb888f93b3af9bc.
Build rtags with llvm 4.0.0 which installed by brew on macOS 10.12.4.

The command I used to generate makefile for rtags project is:

> cmake -DLIBCLANG_LLVM_CONFIG_EXECUTABLE=/usr/local/opt/llvm/bin/llvm-config -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl ..

I check the version of rc and rdm, both are 2.9.117.

After that, I'd like to build index for rtags project for test.
I got this:

> [  1%] 1/67 19:43:52 ~/code/rtags/src/ClassHierarchyJob.cpp in 3275ms. (442 syms, 765 symNames, 14 includes, 3 of 668 files, symbols: 822 of 39919, 40386 cursors, 328420 bytes written, 667 queried 124ms) (3048/218/5ms). (priority 0)
> [  3%] 2/67 19:43:52 ~/code/rtags/src/CompletionThread.cpp in 3306ms. (1532 syms, 1397 symNames, 22 includes, 3 of 669 files, symbols: 2214 of 41332, 42962 cursors, 892685 bytes written, 668 queried 108ms) (3052/227/15ms). (priority 0)
> Output from /Users/liyang/code/rtags/src/ClassHierarchyJob.cpp:
> /usr/local/opt/llvm/include/c++/v1/float.h:69:15: fatal error: 'float.h' file not found
> 
> Output from /Users/liyang/code/rtags/src/CompletionThread.cpp:
> /usr/local/opt/llvm/include/c++/v1/float.h:69:15: fatal error: 'float.h' file not found
> 
> [  4%] 3/67 19:43:52 ~/code/rtags/src/ClangThread.cpp in 3433ms. (3978 syms, 4333 symNames, 77 includes, 14 of 667 files, symbols: 5908 of 44756, 47204 cursors, 2323847 bytes written, 666 queried 138ms) (3026/321/54ms). (priority 0)
> [  6%] 4/67 19:43:52 ~/code/rtags/src/rc.cpp in 3458ms. (7423 syms, 7695 symNames, 82 includes, 14 of 272 files, symbols: 11661 of 28541, 34209 cursors, 6706838 bytes written, 271 queried 115ms) (2853/441/115ms). (priority 0)
> Output from /Users/liyang/code/rtags/src/ClangThread.cpp:
> /usr/local/opt/llvm/include/c++/v1/float.h:69:15: fatal error: 'float.h' file not found
> 
> [  7%] 5/67 19:43:52 ~/code/rtags/src/rp.cpp in 3829ms. (1131 syms, 1421 symNames, 30 includes, 5 of 670 files, symbols: 1886 of 40988, 42007 cursors, 794137 bytes written, 669 queried 37ms) (3651/159/11ms). (priority 0)
> Output from /Users/liyang/code/rtags/src/rp.cpp:
> /usr/local/opt/llvm/include/c++/v1/float.h:69:15: fatal error: 'float.h' file not found
> 
> [  9%] 6/67 19:43:54 ~/code/rtags/src/CompilerManager.cpp in 6134ms. (75732 syms, 81483 symNames, 413 includes, 98 of 274 files, symbols: 99772 of 111377, 136365 cursors, 56520868 bytes written, 273 queried 162ms) (2193/2820/648ms). (priority 0)
> [ 10%] 7/67 19:43:55 ~/code/rtags/src/DependenciesJob.cpp in 3078ms. (58 syms, 82 symNames, 7 includes, 2 of 669 files, symbols: 62 of 39215, 39598 cursors, 43073 bytes written, 2 queried 2ms) (3000/74/2ms). (priority 0)
> Output from /Users/liyang/code/rtags/src/DependenciesJob.cpp:
> /usr/local/opt/llvm/include/c++/v1/float.h:69:15: fatal error: 'float.h' file not found
> 
> [ 12%] 8/67 19:43:55 ~/code/rtags/src/FindFileJob.cpp in 2969ms. (154 syms, 225 symNames, 9 includes, 2 of 669 files, symbols: 190 of 39343, 39808 cursors, 109458 bytes written, 2 queried 3ms) (2880/78/8ms). (priority 0)
> [ 13%] 9/67 19:43:55 ~/code/rtags/src/FileManager.cpp in 3112ms. (484 syms, 461 symNames, 16 includes, 5 of 670 files, symbols: 647 of 39745, 40470 cursors, 257641 bytes written, 4 queried 11ms) (2997/96/7ms). (priority 0)
> Output from /Users/liyang/code/rtags/src/FindFileJob.cpp:
> /usr/local/opt/llvm/include/c++/v1/float.h:69:15: fatal error: 'float.h' file not found
> 
> Output from /Users/liyang/code/rtags/src/FileManager.cpp:
> /usr/local/opt/llvm/include/c++/v1/float.h:69:15: fatal error: 'float.h' file not found
> 
> [ 15%] 10/67 19:43:55 ~/code/rtags/src/FindSymbolsJob.cpp in 2999ms. (111 syms, 133 symNames, 8 includes, 2 of 668 files, symbols: 122 of 39269, 39684 cursors, 73420 bytes written, 1 queried 4ms) (2900/88/9ms). (priority 0)
> Output from /Users/liyang/code/rtags/src/FindSymbolsJob.cpp:
> /usr/local/opt/llvm/include/c++/v1/float.h:69:15: fatal error: 'float.h' file not found
> ...

Did I missing something? How should I fix this?

**Comment by Andersbakken** [comment]
I can actually reproduce this myself with clang 4.0.0.

I'll try to look into it.

Anders

**Comment by jojojames** [comment]
+1

Thanks for reporting this.

**Comment by kthelgason** [comment]
I also run into this issue, specifically with ObjC++ files. Will gladly help debug.

**Comment by tillt** [comment]
This appears to be a regression of LLVM 4 on macOS.
See https://bugs.llvm.org//show_bug.cgi?id=31504

One (nasty) way of fixing this is patching `/usr/local/Cellar/llvm/4.0.0_1/lib/clang/4.0.0/include/float.h` (note this is the brew default location, your milage may vary)

```
34,35c34
< #if (defined(__APPLE__) || (defined(__MINGW32__) || defined(_MSC_VER))) && \
<     __STDC_HOSTED__ && __has_include_next(<float.h>)
---
> #if ((defined(__MINGW32__) || defined(_MSC_VER))) && __STDC_HOSTED__ && __has_include_next(<float.h>)
```

**Comment by kthelgason** [comment]
The llvm bug states that this only affects systems running Snow Leopard and
older, I'm seeing this on the latest version of MacOS.

**Comment by tillt** [comment]
@kthelgason true and just like you describe, it seems to hit macOS 10.12.4 as well -- I am pretty sure it is not rtags at fault.

**Comment by kthelgason** [comment]
I'm sure you're right, this is probably an LLVM issue.

**Comment by tillt** [comment]
Ow see
https://github.com/Andersbakken/rtags/commit/15f986beb0c253a309364e4bd502bf0d0d57e747

**Comment by kthelgason** [comment]
I built rtags from source and can verify that I no longer see this error.

**Comment by wood9366** [comment]
I built rtags with verison 18c6aa5b00451abf9dd34df60cb5b35e7d0866a6.
The error is gone. I close this bug. Thanks.
