### ISSUE TITLE
When i executed "rtags-find-symbol-at-point", I showed error message.

### ISSUE THREAD

**Issue by jongyoungcha** [Andersbakken/rtags#942]
I executed "rtags-find-find-symbol-at-point" which is a feature of rtags.
(that feature is binded at C-c r .)

And I received follow message.
![image](https://cloud.githubusercontent.com/assets/7163653/24916095/2076373e-1f14-11e7-906a-d20078ac3136.png)
the error message is "No buffer named "Protocol version mismatchProtocol version mismatchProtocol version mismatch"

That time the function under my cursor is printf().

I executed follow commands.
![image](https://cloud.githubusercontent.com/assets/7163653/24916790/2812fcaa-1f16-11e7-863a-1da6e08e0edf.png)

And this is my environments.
- os version
![image](https://cloud.githubusercontent.com/assets/7163653/24916890/71701dec-1f16-11e7-98a8-65425e0dc291.png)

- rdm, rc version
![image](https://cloud.githubusercontent.com/assets/7163653/24917038/dccc4304-1f16-11e7-8fe8-7816a323f1b0.png)

- cmake version
![image](https://cloud.githubusercontent.com/assets/7163653/24917414/15b0fde4-1f18-11e7-9e59-47c49a059d74.png)

- clang version
![image](https://cloud.githubusercontent.com/assets/7163653/24917521/74290c86-1f18-11e7-8f0b-6dbfb6da2686.png)

- rtags version
rtags was installed today with melpa

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

- My init.el contents about rtags.
![image](https://cloud.githubusercontent.com/assets/7163653/24917195/571e8be4-1f17-11e7-8372-30a1ba4d2af5.png)

If inform me why the message showed, i'll highly appreciate your cooperation.

**Comment by Andersbakken** [comment]
It seems like there's a mismatch between your rtags.el and your install of
rtags. Can you make sure you're up-to-date on both the package.el side and
the native build?

Anders

**Comment by jongyoungcha** [comment]
Just download rtags source code with git. After that builded and installed it with cmake,  That time almost maybe a month ago.

That time I used spacemacs. But now I using GNU emacs.

So, that rtags binary is likely to be old version.

Now I find in OS X, there is the way whose I can install rtags with homebrew through github manual.

I'll install newest rtags binary with homebrew and recheck the isssue will be comming. 

Thank you.

**Comment by jongyoungcha** [comment]
Oh, Sorry after I installed newest rtags binaries with brew, The error messages have disappeared.

Thanks, Have a good day  :-)
