### ISSUE TITLE
-DMACRO= translated to -DMACRO

### ISSUE THREAD

**Issue by jcornwall** [Andersbakken/rtags#944]
When compile_commands.json contains a definition "-DMACRO=" rdm translates it to "-DMACRO" for libclang. "-DMACRO" is equivalent to "-DMACRO=1" which instructs clang to insert a 1 in place of the macro, leading to compile errors.

**Comment by Andersbakken** [comment]
Thanks. Should be fixed now with a1d1a5e2f7e331f0174da8d485a16f38b7164a46
