### ISSUE TITLE
RTags project root with .projectile

### ISSUE THREAD

**Issue by jojojames** [Andersbakken/rtags#945]
Hey,

I was wondering how the project root heuristic was working. I'd like to think a .projectile file being in a directory would give it precedence over even .git.

Looking at Rtags.cpp,

```    if (mode == SourceRoot) {
        const Entry before[] = {
            { ".git", Flags<FindAncestorFlag>() },
            { ".svn", Flags<FindAncestorFlag>() },
            { ".bzr", Flags<FindAncestorFlag>() },
            { ".tup", Flags<FindAncestorFlag>() },
            { "GTAGS", Flags<FindAncestorFlag>() },
            { "configure", Flags<FindAncestorFlag>() },
            { "CMakeLists.txt", Flags<FindAncestorFlag>() },
            { "*.pro", Wildcard },
            { "scons.1", Flags<FindAncestorFlag>() },
            { "*.scons", Wildcard },
            { "SConstruct", Flags<FindAncestorFlag>() },
            { "autogen.*", Wildcard },
            { "GNUMakefile*", Wildcard },
            { "INSTALL*", Wildcard },
            { "README*", Wildcard },
            { 0, Flags<FindAncestorFlag>() }
        };
```

I see a list of potential checks here but not sure how it works.

Reading the README,

```
Essentially it will look for certain files/dirs (like configure/CMakeLists.txt/scons.1/.git) etc to try to determine the likely project root for each source file. For generated source files that end up in the build directory we try to find the source root based on similar heuristics around config.status/CMakeCache.txt etc. Usually this works out reasonably well. If it doesn’t for you, you can pass --project-root /path/to/the/project/root to rc.
```

I have a CMakeLists file in a directory but it still seems like Rtags marks the .git directory as the root.

File directory goes

[Root with .git folder] 
-> [Server code with .projectile]                    
 -> [Client code with .projectile/CMakeLists.txt]

Rtags marks the .git folder as the root when it caches the directory.

I'd like for it to mark the the folder with .projectile (even CMakeLists.txt would be good). This could just be a configuration issue on my part.

**Comment by Andersbakken** [comment]
Seems reasonable. I haven't used projectile so it didn't occur to me to include it but we will always support another elisp project :-)

**Comment by jojojames** [comment]
Awesome, thanks!

**Comment by jojojames** [comment]
I'm wondering what the expected root is if the directory looks like this.

Repo (Contains .git)
 -> RandomFolder
      -> ProjectFolder (Contains .projectile)
      -> AnotherProjectFolder (Containas .projectile)

-w seems to return the path containing .git.

**Comment by Andersbakken** [comment]
Currently we take the shortest path that matches. I can see how .projectile
file maybe should take precedence however.

I just added some code for that. Can you see if this works the way you
expect?

Anders

**Comment by jojojames** [comment]
Hmnn, building rtags again, I get an error like this.

Assertion failed: (static_cast<bool>(flags & NoValue) == val.isEmpty()), function Define, file /Users/james/.emacs.d/fork/rtags/src/Source.h, line 302.

**Comment by Andersbakken** [comment]
Sorry about the long delay. I got that one too. The assertion was just
plain wrong. I've removed it now.

Anders

**Comment by jojojames** [comment]
Works for me.
