### ISSUE TITLE
Installing Rtags in user defined directory

### ISSUE THREAD

**Issue by jojojames** [Andersbakken/rtags#946]
Hi,

I'm wondering if it makes sense to set Rtags the install in a user directory if possible.

Upgrading Rtags from ELPA causes the binary to get wiped (maybe we want this?) so you have to reinstall after upgrading.

Thanks!

**Comment by ackalker** [comment]
Please have a look at the way in which [`irony-mode`](https://github.com/Sarcasm/irony-mode) handles installation of its server, in particular the (customizable) variables `irony-server-install-prefix` and `irony-user-dir`.

This will also make modifying shell PATH to include RTags bin directory simpler and more reliable.
Currently I'm using:
```sh
export PATH=$PATH:$(echo ${HOME}/.emacs.d/elpa/rtags-*/rtags-*/bin)
```
If RTags server installation would work similar to `irony-mode`, I could reduce this to:
```sh
export PATH=$PATH:${HOME}/.emacs.d/rtags/bin
```

**Comment by Andersbakken** [comment]
That makes a lot of sense actually. RTags doesn't need the server wiped for an upgrade so I can see why it would be annoying to have to rebuild between upgrades. i'll see what I can do.

**Comment by Andersbakken** [comment]
Should be fixed now

**Comment by ackalker** [comment]
Thanks for fixing this! :-)

**Comment by jojojames** [comment]
When I set something like this,
```
  (setq rtags-install-path
        (format "%sservers/%s/rtags/"
                user-emacs-directory emacs-major-version))
```

Rtags will not be able to find the rtags-install sh script.

**Comment by Andersbakken** [comment]
I think that should be fixed now. Can you try again?

**Comment by jojojames** [comment]
Works for me.

**Comment by Andersbakken** [comment]
I think it should be fixed now. I had to expand ~ to home and make sure I
mkdir'ed recursively.

Thank.

Anders
