### ISSUE TITLE
Specifying paths to rtags 

### ISSUE THREAD

**Issue by amneetb** [Andersbakken/rtags#950]
I installed rtags using brew on Mac OSX sierra, which installed llvm as its dependency. I have a custom compile_commands.json for my project. When I run the command rc -J ., I get several fatal errors related to standard c,cpp files. I tried including some paths by greping location of standard files like math.h on my system too. What additional paths should I add?

This is how I am running rdm 

% rdm --clean-slate -I/usr/local/Cellar/gcc/6.2.0/include/c++/6.2.0/ -I/usr/local/Cellar/gcc/6.2.0/include/c++/6.2.0/x86_64-apple-darwin16.1.0/ -s/usr/local/Cellar/gcc/6.2.0/include/c++/6.2.0/ -s/usr/local/Cellar/llvm/4.0.0_1/lib/clang/4.0.0/include/ 

I am getting errors like:

Running with 8 jobs, using args: -ferror-limit=50 -Wall -fspell-checking -Wno-unknown-warning-option
Includepaths: -I/usr/local/Cellar/gcc/6.2.0/include/c++/6.2.0/ -I/usr/local/Cellar/gcc/6.2.0/include/c++/6.2.0/x86_64-apple-darwin16.1.0/ -isystem /usr/local/Cellar/gcc/6.2.0/include/c++/6.2.0/ -isystem /usr/local/Cellar/llvm/4.0.0_1/lib/clang/4.0.0/include/ -isystem /usr/local/Cellar/llvm/4.0.0_1/lib/clang/4.0.0/include/
[  0%] 1/332 20:57:36 ~/Projects/HPC4MFG_LBNL/lib/ChomboCellAverageEB/lib/src/AMRElliptic/AMRNodeOp.cpp in 1277ms. (4403 syms, 5659 symNames, 128 includes, 17 of 235 files, symbols: 5895 of 16011, 17440 cursors, 4555338 bytes written, 234 queried 153ms) (847/351/47ms). (priority 0)
[  1%] 2/332 20:57:36 ~/Projects/HPC4MFG_LBNL/lib/ChomboCellAverageEB/lib/src/AMRElliptic/BackwardEuler.cpp in 1378ms. (9703 syms, 14844 symNames, 64 includes, 16 of 224 files, symbols: 12084 of 21186, 24832 cursors, 7683749 bytes written, 223 queried 132ms) (839/384/85ms). (priority 0)
[  1%] 3/332 20:57:36 ~/Projects/HPC4MFG_LBNL/lib/ChomboCellAverageEB/lib/src/AMRElliptic/LevelTGA.cpp in 1385ms. (7182 syms, 6968 symNames, 128 includes, 16 of 237 files, symbols: 8984 of 18489, 21255 cursors, 5257817 bytes written, 236 queried 138ms) (842/436/58ms). (priority 0)
Output from /Users/amneetb/Projects/HPC4MFG_LBNL/lib/ChomboCellAverageEB/lib/src/AMRElliptic/AMRNodeOp.cpp:
/usr/local/opt/llvm/include/c++/v1/stdio.h:108:15: fatal error: 'stdio.h' file not found

[100%] 331/332 20:58:22 ~/Projects/HPC4MFG_LBNL/toolkit/utilities/MomentUtilities.cpp in 869ms. (1201 syms, 750 symNames, 33 includes, 18 of 286 files, symbols: 1365 of 13477, 14102 cursors, 988726 bytes written, 17 queried 30ms) (770/54/25ms). (priority 0)
[100%] 332/332 20:58:22 ~/Projects/HPC4MFG_LBNL/toolkit/utilities/PoissonCoefficients.cpp in 695ms. (81 syms, 46 symNames, 3 includes, 1 of 275 files, symbols: 85 of 12463, 12860 cursors, 47686 bytes written, 17 queried 3ms) (675/16/1ms). (priority 0)
Jobs took 47.57s, (avg 0.14s). We're using 0mb of memory. 
Output from /Users/amneetb/Projects/HPC4MFG_LBNL/toolkit/utilities/MomentUtilities.cpp:
/usr/local/opt/llvm/include/c++/v1/stdlib.h:94:15: fatal error: 'stdlib.h' file not found
handleInclude failed 0x0 inclusion directive include stdlib.h /usr/local/opt/llvm/include/c++/v1/stdlib.h:94:1
handleInclude failed 0x0 inclusion directive include string.h /usr/local/opt/llvm/include/c++/v1/string.h:61:1
handleInclude failed 0x0 inclusion directive include wchar.h /usr/local/opt/llvm/include/c++/v1/wchar.h:119:1
handleInclude failed 0x0 inclusion directive include stdint.h /usr/local/opt/llvm/include/c++/v1/stdint.h:119:1
handleInclude failed 0x0 inclusion directive include locale.h /usr/local/opt/llvm/include/c++/v1/locale.h:43:1
handleInclude failed 0x0 inclusion directive include ctype.h /usr/local/opt/llvm/include/c++/v1/ctype.h:39:1
handleInclude failed 0x0 inclusion directive include pthread.h /usr/local/Cellar/gcc/6.2.0/include/c++/6.2.0/x86_64-apple-darwin16.1.0/bits/gthr-default.h:35:1
handleInclude failed 0x0 inclusion directive include stdio.h /usr/local/opt/llvm/include/c++/v1/stdio.h:108:1
handleInclude failed 0x0 inclusion directive include errno.h /usr/local/opt/llvm/include/c++/v1/errno.h:32:1
handleInclude failed 0x0 inclusion directive include wctype.h /usr/local/opt/llvm/include/c++/v1/wctype.h:54:1
handleInclude failed 0x0 inclusion directive include math.h /usr/local/opt/llvm/include/c++/v1/math.h:301:1
handleInclude failed 0x0 inclusion directive include sys/time.h /Users/amneetb/Projects/HPC4MFG_LBNL/lib/ChomboCellAverageEB/lib/src/BaseTools/CH_Counters.H:14:1
handleInclude failed 0x0 inclusion directive include sys/types.h /Users/amneetb/Softwares/HDF5Parallel/include/H5public.h:40:1
handleInclude failed 0x0 inclusion directive include limits.h /usr/local/opt/llvm/include/c++/v1/limits.h:58:1
handleInclude failed 0x0 inclusion directive include limits.h /usr/local/opt/llvm/include/c++/v1/limits.h:62:1
handleInclude failed 0x0 inclusion directive include inttypes.h /usr/local/opt/llvm/include/c++/v1/inttypes.h:247:1
handleInclude failed 0x0 inclusion directive include sys/types.h /Users/amneetb/Softwares/HDF5Parallel/include/H5Gpublic.h:30:1
handleInclude failed 0x0 inclusion directive include float.h /usr/local/opt/llvm/include/c++/v1/float.h:69:1

Output from /Users/amneetb/Projects/HPC4MFG_LBNL/toolkit/utilities/PoissonCoefficients.cpp:
/usr/local/opt/llvm/include/c++/v1/wchar.h:119:15: fatal error: 'wchar.h' file not found

**Comment by Andersbakken** [comment]
Sorry about the delay. I'll try to look into it.

**Comment by Andersbakken** [comment]
I think I've figured it out. This is basically a bug in 4.0.0 of llvm which I've worked around in newer versions of rtags. I'm not entirely clear on what it takes for home brew to pick up a new version of rtags. I believe bumping the version (which I just did) might help. I should probably know this :-) 

In short, the homebrew version of rtags is lagging behind mainline rtags by a little and the version in homebrew has a bug. Hopefully my last push will lead to homebrew getting a newer version.

**Comment by amneetb** [comment]
If I do 
% brew upgrade rtags

I get :
Updating Homebrew...
Error: rtags 2.9_1 already installed

**Comment by progician** [comment]
I have built rtags from source at the latest, and this still happens against also the latest clang.

**Comment by gramanas** [comment]
I get the same error `handleInclude failed (nil) inclusion directive include stddef.h /usr/include/wchar.h:52:1` but I also get a `/usr/include/qt4/QtCore/qglobal.h:45:10: fatal error: 'stddef.h' file not found` error. Now in Arch Linux (witch I have atm) `stddef.h` is under `/usr/include/linux/stddef.h` while rtags searches for it at `/usr/include/stddef.h`

I tried `ln -s` the `stddef.h` to where rtags searches for it and when I do that suddenly the rdm output starts going crazy with errors like this: `/usr/include/stdlib.h:338:4: error: unknown type name 'size_t'; did you mean 'ssize_t'?` If I remove the symlink the errors go away and I am back to the previous problem. 

I reinstalled rtags and it seems to work now, so I guess somehow it got confused after indexing a couple of huge c++ projects.?

**Comment by Andersbakken** [comment]
stddef.h needs to be found in clang's own includepath. This problem is
normally caused by some sort of non-standard installation of libclang. We
have some heuristics to to find the includepath that contains stddef.h
inside of libclang but these may or may not be correct depending on how
clang is built.

**Comment by Frydac** [comment]
Just FYI (maybe helpful for ppl searching):
Had this same issue after updating my Manjaro distro (Arch based). I had installed rtags using yaourt.
Probably did the wrong thing for updating my whole system, and after that I had this issue.
But after reinstalling rtags (using yaourt again), it works like its former self.

Thx a lot for this project!

**Comment by hessryanm** [comment]
I am having this same issue now on os x mojave:

`handleInclude failed 0x0 inclusion directive include string.h /usr/local/opt/llvm/include/c++/v1/string.h:61:1`

LLVM version 10.0.0, rtags version 2.21.126.  It worked fine before upgrading to Mojave, and now it doesn't function.  I just this morning downloaded rtags from source and built it.
