### ISSUE TITLE
rdm crashes on startup with deserialization error when used in sandbox mode

### ISSUE THREAD

**Issue by klichota-9ld** [Andersbakken/rtags#951]
I have encountered a problem when using rdm in sandbox mode - on first run the rdm works, but after shutting down and restarting it crashes in deserialization with segfault.

I have tracked it down to missing serialization of compileCommands() and compileCommandsFileId in sandbox mode - they are not serialized in sandbox mode, but always deserialized.

The following patch should fix that, if my understanding is correct.
[rtags-serialization-fix.diff.txt](https://github.com/Andersbakken/rtags/files/946724/rtags-serialization-fix.diff.txt)

**Comment by Andersbakken** [comment]
Thanks. I applied the patch.
