### ISSUE TITLE
use rtags with bazel

### ISSUE THREAD

**Issue by suteng** [Andersbakken/rtags#952]
Any tool to generate compile commands when using bazel build system?

**Comment by cslux** [comment]
@suteng I'm aware of two possibilities:

1) https://github.com/rizsotto/Bear
2) Write an extra_action for bazel https://gist.github.com/bsilver8192/0115ee5d040bb601e3b7

Christian

**Comment by dubnde** [comment]
3. [intercept-build](https://pypi.python.org/pypi/scan-build)
