### ISSUE TITLE
Feature Request: Expose project parsing status to elisp

### ISSUE THREAD

**Issue by Nephyrin** [Andersbakken/rtags#953]
Full-reparses can take 30m+ with our giant codebase.  I often glance at rdm in a tmux pane to determine how-parsed my project is - relevant when querying callsites or other data that might not be complete.

It would be useful to have a cached `(rtags-project-status)` call that would be easy to stick in the modeline or similar.  Just the parsed/remaining values rdm's status outputs would be plenty.

(And thanks, yet again, for this awesome project!)

**Comment by Andersbakken** [comment]
We actually kinda have something like this (though it had some bugs). Anyway, in master you should be able to do this:

(add-to-list 'global-mode-string '(:eval (rtags-modeline)))
(add-hook 'rtags-diagnostics-hook (function force-mode-line-update))

You can access these poorly named variables to do your own notification system:

rtags-remaining-jobs ;; integer with count of remaining jobs for all projects
rtags-last-index  ;; the first number in rdm's output 
rtags-last-total ;; the second number in rdm's output, these last two are project local

You have to run rdm with the --progress for this to work.

**Comment by Nephyrin** [comment]
Aha! Not sure how I missed that, I was looking for variables named status or similar rather than modeline. With the latest sync this does indeed work well. Thanks!

**Comment by Andersbakken** [comment]
Glad to hear.

Anders
