### ISSUE TITLE
Typing delay and hanging with completions enabled

### ISSUE THREAD

**Issue by ekmecic** [Andersbakken/rtags#956]
First of all I'd like to thank Anders and the rest of the contributors for RTags, it's the best C/C++ editor plugin I've tried and it's been a great help!

## Please mark appropriately
 - [x] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [x] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

## Problem description
Significant typing delay and hanging (>1s) while typing in C/C++ buffers with completions enabled.

### Expected behavior
Less delay while typing (<0.2s) like other emacs plugins.
No hanging while typing.

### Actual behavior
This issue happens most frequently in header files, although it also happens in `.cpp` files at times.
It comes and goes, sometimes RTags is perfectly responsive but I've found that I get significant typing delay and hanging.
Emacs sends completion requests as I'm typing, which causes to hang for seconds at a time while rdm takes usually a whole second to return completions candidates.

I've removed all plugins except RTags and company in my emacs config, disabled font-locking, put the compilation database on a ramdisk, played with company-mode and rtags settings, tried different computers to no avail.
The issue happens in both my own projects (mid-sized with Qt libraries) as well as the RTags source tree.
[Here's a profiler report](https://gist.github.com/ekmecic/d863216ab943719f46d131cce8ec6756) from a session, as well as [rdm output](https://gist.github.com/ekmecic/249164b43398a32d22ee4a857292c403) from a session where I type a comment in an RTags header file. Here's a [second, more verbose example of rdm output](https://gist.github.com/ekmecic/0cb162cd8ff2bb44d7a98583c14c3203). It performed better in this case, taking ~0.4s on average to fetch completions whereas it usually takes 1 second. 

I think the problem of RTags looking for completions in comments could be avoided by not searching for completions in comments but I don't have any ideas about the general sluggishness.
I'd be happy to work on a fix for the comment problem but I'd appreciate some mentorship since I'm pretty bad with elisp.
I'd also be happy to provide any more information or help in other ways if needed!

## Environment
- OS: Linux
- LLVM/Clang: 4.0.0 (this happened in 3.* clang releases too)

Edit: added some more details and reworked the issue to follow the new format.

**Comment by jojojames** [comment]
+1

I think a quick start is to profile 

https://github.com/Andersbakken/rtags/blob/master/src/company-rtags.el

```
    (prefix
     (and buffer-file-name
          (memq major-mode rtags-supported-major-modes)
          (rtags-is-indexed)
          (company-rtags--prefix)))
    (candidates
     (let ((pos (rtags-calculate-completion-point)))
       (when pos
         (setq company-rtags-last-completion-prefix (if (> (length arg) 0) arg))
         (setq company-rtags-last-completion-prefix-type (company-rtags--prefix-type))
         (setq company-rtags-last-completion-location (rtags-current-location pos t))
         (company-rtags-completions-calculate-maxwidth)
(company-rtags--candidates))))
```

Might be the prefix check though I haven't had the time to try it out. company-ycmd and company-irony are much faster with respect to typing latency.

**Comment by jojojames** [comment]
Benchmarks

```
this->|

(benchmark 1 '(company-ycmd 'prefix))
"Elapsed time: 0.000052s"
(benchmark 1 '(company-rtags 'prefix))
"Elapsed time: 0.012118s"

(benchmark 1 '(company-ycmd 'candidates ""))
"Elapsed time: 0.024160s"

(benchmark 1 '(company-rtags 'candidates ""))
"Elapsed time: 0.895601s"
```

**Comment by mikeandmore** [comment]
I confirm this issue. I wonder if this is related to the synchronous completion mode? I think rtags does not do async completion since commit 585b8c9e3dceb2d5cf8737ba2b21361a076d5aac. Later ea6f05fe34498bbd3b57cf529bb40f03ca4e2c74 tries to add an option called `--code-complete-no-wait`, it was never finished and got removed finally in 5d0ecdf244a4258afe912dbaf8da7f53cf2f1bb3.

**Comment by mikeandmore** [comment]
v2.3 seems to work well without any delay.

**Comment by mikeandmore** [comment]
I created a PR to fix this issue for company-mode.

**Comment by cslux** [comment]
Thanks @mikeandmore. @ekmecic @jojojames Is it better now?

**Comment by ekmecic** [comment]
Works great, thank you very much @mikeandmore!

**Comment by jojojames** [comment]
candidates lookup is fast but prefix lookup is still slow which may cause a noticeable typing delay.

```
(benchmark 1 '(company-rtags 'prefix))
"Elapsed time: 0.014407s"

(benchmark 1 '(company-rtags 'candidates ""))
"Elapsed time: 0.001425s"
```

**Comment by tianyu-bai** [comment]
The newest company-rtags.el package and rtags.el package still has hanging when I input the code. 
Should I recompile the whole project? I just replace the company-rtags.el and rtags.el in my emacs.

I hope the answer.
Thanks.
