### ISSUE TITLE
company-rtags completion fails due to undefined function caadr

### ISSUE THREAD

**Issue by p-t-g** [Andersbakken/rtags#957]
### Please mark appropriate
 - [ ] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [x] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description
company-rtags--make-candidates fails because caadr function is not defined. The error in minibuffer is: Company: backend company-rtags error "Symbol's function definition is void: caadr" with args (candidates )

#### Expected behavior
Expected behavior is that the function is defined. And completions works.

#### Actual behavior
Completions fails due to undefined function

### Environment
- Your operating system:
Ubuntu 14.04 x86_64

- Emacs version
24.3.1

- LLVM/Clang version:
3.9.1

**Comment by cslux** [comment]
`caadr` is part of `cl-lib.el`, it `cl-lib.el` gets loaded by `rtags.el`. How did you install `RTags` and which version do you have installed?

**Comment by p-t-g** [comment]
I basically just followed the instructions. 

I installed cl-lib using melpa and it seems happy now.

Thanks!

**Comment by cslux** [comment]
That's interesting, it shouldn't be neccessary to install `cl-lib.el` through MELPA, `cl-lib.el` comes bundled with Emacs. Did you install the deb package `emacs-el`? The package `emacs-el` contains the `cl-lib` Emacs Lisp file under usr/share/emacs/24.3/lisp/emacs-lisp`.

https://launchpad.net/~cassou/+archive/ubuntu/emacs/+packages

Christian

**Comment by p-t-g** [comment]
Yeah, I realized after the fact. cl-lib.elc is part of the distribution and it's in /usr/share/emacs/24.3/list/emacs-list/cl-lib.elc. The thing in melpa is some kind of compatibility backport. 

Anyway, I removed the additional package, and put `(require 'cl)` before `(require 'rtags)` in `.emacs` and completion started working again.  

Thanks for your help.
