### ISSUE TITLE
rtags-package-install-path errors in Emacs 24.3

### ISSUE THREAD

**Issue by cslux** [Andersbakken/rtags#958]
### Please mark appropriate
 - [ ] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [x] rtags.el

### Problem description
`rtags-package-install-path` fails in Emacs 24.3 because `package-alist` is not a struct nor does `package-desc-dir` exist.

#### Expected behavior
`rtags-pacakge-install-path` returns install path of `rtags.el`.

#### Possible solution
Check `load-path` for the installation path (preferred), or use `package--dir` defined in `package.el` but it's marked as "private". 

### Environment
- Emacs version:
  24.3

**Comment by Andersbakken** [comment]
Thanks. Can you check that the current solution works in 24.3?

**Comment by cslux** [comment]
Yes, it works @Andersbakken!

**Comment by jojojames** [comment]
Do we need a "/" appended to the path?

Emacs isn't able to find rtags for me without this.

```
(defun rtags-executable-find (exe)
  (cond ((and rtags-tramp-enabled (tramp-tramp-file-p default-directory)) exe)
        ;; for tramp let's rely on `tramp-remote-path`, so if You have some *debug*
        ;; directory to store RTags binaries, just put it to `tramp-remote-path`
        (rtags-path
         (or
          (let ((file (expand-file-name exe rtags-path)))
            (and (file-executable-p file) file))
          (let ((file (expand-file-name exe (concat rtags-path "/bin/"))))
            (and (file-executable-p file) file))))
        ((let* ((install-path (rtags-package-install-path))
                (file (and install-path (concat install-path "/rtags-" rtags-package-version "/bin/" exe))))
           (and file (file-executable-p file) file)))
        (t (executable-find exe))))
```

Note the "/rtags-"

**Comment by Andersbakken** [comment]
I can't reproduce it being a problem but I added the extra slash. Couldn't hurt.
