### ISSUE TITLE
"diagnose" command on an error-less file outputs a malformed XML

### ISSUE THREAD

**Issue by dawagner** [Andersbakken/rtags#959]
### Please mark appropriate
 - [x] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description
`--diagnose` command on a file that doesn't contain any error produces a malformed XML.

#### Expected behavior
```
$ rc --absolute-path --diagnose /some/File.cpp --synchronous-diagnostics
<?xml version="1.0" encoding="utf-8"?>
  <checkstyle>
    <file name="/some/File.cpp">
    </file>
  </checkstyle>
```

#### Actual behavior
```
$ rc --absolute-path --diagnose someFile.cpp --synchronous-diagnostics
<?xml version="1.0" encoding="utf-8"?>
  <checkstyle>
    <file name="someFile.cpp">
    </file>
    </file>
  </checkstyle>
```

### Environment
- Your operating system: Fedora 25

- LLVM/Clang version: 4.0

**Comment by Andersbakken** [comment]
Tnanks. Should work now.

**Comment by dawagner** [comment]
Yes, it does :)
