### ISSUE TITLE
rtags-compilation-flags no longer works

### ISSUE THREAD

**Issue by Nephyrin** [Andersbakken/rtags#961]
### Please mark appropriate
 - [x] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [x] rtags.el

### Problem description
`rtags-compilation-flags` returns nil - it looks like it invokes `rc --source` which is not a recognized command

#### Expected behavior
Compilation flags

#### Actual behavior
nil

### Environment
- Your operating system:
Linux

- LLVM/Clang version:
4.0

**Comment by Andersbakken** [comment]
Should work now.

**Comment by Andersbakken** [comment]
Thanks
