### ISSUE TITLE
rtags-select-other-window keeps splitting new windows

### ISSUE THREAD

**Issue by arnab-basu** [Andersbakken/rtags#966]
### Please mark appropriate
 - [ ] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [X] rtags.el

### Problem description
rtags-select-other-window keeps creating a new split window

#### Expected behavior
rtags-select-other-window should use an already existing window, ideally it should be possible to specify a window to open the file

#### Actual behavior
A new split keeps getting created every time

### Environment
- Your operating system: Linux

- LLVM/Clang version:

### Feature request

Describe the feature we should add to **RTags**.

**Comment by Andersbakken** [comment]
Sorry about the delay. I can't seem to reproduce this however. Are you saying that you get more and more windows opened up if you back to the *RTags* window and hit <RET>?

**Comment by arnab-basu** [comment]
My turn to apologise for the delay. I'm new to Emacs and I'm using spacemacs in evil mode. I want to create this layout:

![emacsmockup](https://cloud.githubusercontent.com/assets/28657874/26520504/91412a5e-42f1-11e7-9fd0-c1f2aba82a08.png)

I want RTags to always open in a window in the location labelled 'RTags' and I want it to always open source files in the window in the location labelled 'Code' when I press 'enter' on a result in the RTags window.

Currently I am facing the following issues:

1. If the RTags window does not exist, it does not always create one, it sometimes takes over one of the existing eshell windows

2. When I press enter in the RTags window [I have the following configured in .emacs (define-key evil-normal-state-map (kbd "RET") 'rtags-select-other-window) ] it opens the source file in a random window, sometimes in the other eshell window, sometimes in the code window, sometimes it splits another window.

Can you help me to configure this?

Thanks

**Comment by Andersbakken** [comment]
This is likely quite a bit of work. I understand why you would want this. I
wonder if you could achieve something by defadvicing select-window or
something like that. The code that would need to be modified in rtags is
likely due for a rewrite so I'd hesitate recommending defadvicing
rtags-select and rtags-goto-location but you could possibly achieve
something with that.

I'll think about it and see if I can come up with something but it will
probably take more time than I have to spend on it at this moment.

Anders

**Comment by Pass3nger** [comment]
> I'll think about it and see if I can come up with something 

Please no. All that user configuarationish code blow, often seen in other packages, just cripple the idea of emacs and actually burden the user.

Here we go: in **rtags.el** 

Replace `(switch-to-buffer-other-window buffer-or-name)` in **rtags-switch-to-buffer** with `(progn
	  (select-window (window-at 239 69))
	  (switch-to-buffer buffer-or-name))`

Replace `(other-window 1)` in **rtags-select** with `(select-window (window-at 0 0))`

Don't forget to provide your own coordinates in _window-at_. Also comment out those lines in rtags.el  which remove / shrink windows. Byte compile. Done. 

Works like a charm for me.
