### ISSUE TITLE
Would be nice to suspend/clear_suspended during compile mode

### ISSUE THREAD

**Issue by wberrier** [Andersbakken/rtags#967]
### Please mark appropriate
 - [ ] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [x] rtags.el

### Problem description
I common workflow is to checkout updated source, and then execute an emacs compile command.  Since there are so many source file changes, rdm triggers a bunch of rp files, greatly slowing down the build.

#### Expected behavior
It would be nice if all files were suspended while a compilation is running, and then the suspended files were cleared after the compilation command has been run.

#### Actual behavior
Slow build

### Feature request

Do this automatically, or provide some hooks that would allow doing this.

I tried using the compilation-start-hook and compilation-finish-function hooks to call rtags-suspend-all-files and rtags-clear-suspended-files, but when run from those hooks the commands seem to get ignored.  This is probably because it's not being run from a buffer context where rtags applies?  That's my guess.

Suggestions?

**Comment by Andersbakken** [comment]
Good idea. There were indeed bugs in rtags.el making these functions only work when called from a file buffer (for no good reason). 

I fixed those and also added rtags-suspend-during-compilation which can be set to enable the behavior you're looking for. Note that rtags will start jobs immediately when you modify the files and those will be allowed to finish. Let me know if this works out for you.

**Comment by wberrier** [comment]
This worked out great, thanks!

**Comment by Andersbakken** [comment]
Glad to hear.

Anders
