### ISSUE TITLE
Error during validation

### ISSUE THREAD

**Issue by quicknir** [Andersbakken/rtags#968]
### Please mark appropriate
 - [x] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description
I see many, many messages as follows in the log of rdm:

Error during validation: <prefix-path>/boost/1.61.0/include/boost/atomic/detail/lockpool.hpp (2) 87 <datadir>/<project name>/2285/symnames

What does this message mean? 

### Environment
- rhel6, clang 3.8.1

- LLVM/Clang version:

**Comment by Andersbakken** [comment]
This happens to me too but I haven't quite found a way to nail down what actually goes wrong. In short it means that files that were supposed to be stored in the DB are missing. I'm semi-actively working on figuring out what is going wrong so if you have a surefire way to reproduce this situation I would love to hear about it.

**Comment by quicknir** [comment]
This happens to me on completely fresh indexes. Also, I'm now seeing things like:

Output from foo.cpp
error: error reading foo.cpp
Failed to parse <argument list>

This actually was not happening before. If you have a good idea what commits may have introduced this issue that would be helpful, otherwise I may do a very slow binary search (one iteration per day or two, hah) in order to try to find it.

**Comment by Andersbakken** [comment]
Can't say I would know what commit introduced it though I am seeing more of
the error during validation things myself too. I'll try to investigate.

In short it means that a file in the database that was supposed to be
present seems to missing. It should lead to a reindexing of the dependent
files (e.g. if you foobar.h's DB-files are missing foobar.cpp should get
reindexed. I suspect this happens sometimes when it really shouldn't
though.

Anders

**Comment by Andersbakken** [comment]
There's a chance 3b3ace901f53827daef81d4c13658ec4feb318b4 fixes this (or at least improves it).

**Comment by quicknir** [comment]
I pulled to head and rebuilt and started reindexing, I'm getting error during validation on basically every file, even on a clean index, to the point where the majority of the content in the tail of the logfile is just Error during validation.

**Comment by Andersbakken** [comment]
Does it keep happening though? If you let it finish, then restart rdm?

**Comment by quicknir** [comment]
Hmmm, so I did the following steps. I let it finish indexing. I verify that goto definition works. Then I kill the process. Then I restart it. The output log shows nothing except restoring project. I verify goto definition works. Still clean. Then I change a file, it does some re-indexing but does *not* show any error during validation. Though I only changed one file, so maybe it is some specific edge case, but at least this shows it is not totally endemic.

So in practice the only real effect I can prove here (since I didn't do any benchmarking and it doesn't feel slower) is that the first index through the log is extremely polluted, to the point where it makes it quite a bit more annoying to track down real issues. So I guess it is hard to argue that this is high priority, but perhaps it is still worth resolving as I think these log messages do actually add negative value in the particular situation of a fresh index.

As always thanks for your time.

**Comment by Andersbakken** [comment]
I believe this problem has been somewhat mitigated by some changes I made a month ago or so. Closing for now.

**Comment by quicknir** [comment]
I will pull and rebuild and comment on this thread either way. Thanks as always!

**Comment by Andersbakken** [comment]
Thanks.

**Comment by nickenchev** [comment]
Ran "rdm -C"
Index project on clean index using "rc -J ."
Getting errors like these: "Error during validation: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/_types/_int64_t.h No such file or directory (2) 87 /Users/nenchev/.cache/rtags/_Users_nenchev_Developer_projects_boiler_/90/symnames"

The header file exists, not sure whats going on here. This is happening for all of these system headers etc.

**Comment by xguerin** [comment]
I'm getting the same type of errors. My volumes are mounted on NFS, could that create such a behavior?

**Comment by xinquanatcolezhu** [comment]
I think this error still happens with the latest stable release 

`rdm --version
2.18.120
`
`
87 /home/AD/xinquan.zhu/.cache/rtags/_home_AD_xinquan.zhu_oms_/867/symnames
Error during validation: /opt/rh/devtoolset-7/root/usr/include/c++/7/typeinfo (2) 87 /home/AD/xinquan.zhu/.cache/rtags/_home_AD_xinquan.zhu_oms_/836/symnames
Error during validation: /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/stl_pair.h (2) 87 /home/AD/xinquan.zhu/.cache/rtags/_home_AD_xinquan.zhu_oms_/794/symnames
Error during validation: /opt/rh/devtoolset-7/root/usr/include/c++/7/ext/numeric_traits.h (2) 87 /home/AD/xinquan.zhu/.cache/rtags/_home_AD_xinquan.zhu_oms_/793/symnames
Error during validation: /opt/rh/devtoolset-7/root/usr/include/c++/7/cstdio (2) 87 /home/AD/xinquan.zhu/.cache/rtags/_home_AD_xinquan.zhu_oms_/827/symnames
Error during validation: /opt/rh/devtoolset-7/root/usr/include/c++/7/ext/string_conversions.h (2) 87 /home/AD/xinquan.zhu/.cache/rtags/_home_AD_xinquan.zhu_oms_/825/symnames
Error during validation: /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/hash_bytes.h (2) 87 /home/AD/xinquan.zhu/.cache/rtags/_home_AD_xinquan.zhu_oms_/823/symnames
Error during validation: /opt/rh/devtoolset-7/root/usr/include/c++/7/limits (2) 87 /home/AD/xinquan.zhu/.cache/rtags/_home_AD_xinquan.zhu_oms_/821/symnames
Error during validation: /opt/rh/devtoolset-7/root/usr/include/c++/7/string_view (2) 87 /home/AD/xinquan.zhu/.cache/rtags/_home_AD_xinquan.zhu_oms_/820/symnames
`

**Comment by sinny-sama** [comment]
lately, after switching from desktop (fedora 26) to laptop (fedora 28, rtags git master compiled the same way as before) i noticed rtags not working at all.
spent 1-2 days trying to get it to work - like trying older git tags (down to 2015) or different llvm/clang versions - nothing helped
and one of the most obvious problems at the moment  was "Error during revalidation" spam on every file

long story short, decreasing number of worker processes from implicit 8 down to 1 completely got rid of the messages. idea for doing so came from quick glance at the code - i noticed some notion of file locking while "validating" file.

rtags is still not working for me - just started showing little signs of life, but that is for another issue

**Comment by cslux** [comment]
@sinny-sama That's unfortunate to hear! I use Fedora too (27) and I'm not facing that issue.

Could you please provide a small example and a step by step instruction how parsed the project with RTags. 

Thank you!
