### ISSUE TITLE
Way to check if file is indexed by rtags?

### ISSUE THREAD

**Issue by quicknir** [Andersbakken/rtags#969]
### Feature request

I'd like to write a hook so that when a C++ buffer starts, it sets a goto definition handler that is either rtags, or a different one, depending on whether the current file is handled by rtags (or if rdm is not running but that can already be checked). Is there a function that I can call to see if rtags has indexed a specific filename? Specifying the full path preferably so it is not possible to get confused between files with the same name.

**Comment by tsmarques** [comment]
I think `rtags-is-indexed` at `rtags.el` does what you want, for the current buffer.

**Comment by quicknir** [comment]
Ah yes I thought there was one but had trouble finding it. Thanks!
