### ISSUE TITLE
rdm is taking a lot of resources on large project

### ISSUE THREAD

**Issue by Martinsos** [Andersbakken/rtags#971]
Thanks for this awesome project!

I am using rtags on c++ project that has about 15k files, through emacs.
I noticed that when I modify and save one of core files in the project, rdm always spins up (I assume to update the index) and takes all my CPUs for a few seconds, then stops. I would rather have it do this in the background, with smaller number of CPUs. Also, I do not really need it to re-index the whole thing all the time, I would rather have it do it occasionally, either every so or on-demand. Is there any way to do this?

### Environment
- Your operating system: Archlinux 4.10.16
- LLVM/Clang version: 4.0.0

**Comment by Martinsos** [comment]
I am thinking about using irony-mode for auto-complete and flycheck, since it is fast and works well for those things, while using rdm for finding definitions, references, and other cool stuff that it offers and irony-mode can not do.

I think in that case a good option may be to have rdm not reindex everything on file change - instead, I would run reindexing manually from time to time. Do you have any advice on how to do that? How can I manually tell rdm to do reindexing? I have not found any commands for that, either in rdm, rc or elisp.

Also, how big problem do you think it will be if reindexing is run only from time to time? I guess most of the things should work fine? I am especially interested in "find/follow symbol" functionality. When would you recommend running it?

**Comment by apmanol** [comment]
You can use rdm with
`--rp-nice-value|-a [arg]`
and of course limit the number of cores used with -j

**Comment by schultzern** [comment]
I have the same problem! Did you find any solutions?

For example: When I checkout a branch with minor changes, rdm re-indexes the source code and uses all my CPU for about 30 min... I'm using rtags with atom and the source code consists of 35k files.

**Comment by Martinsos** [comment]
@schultzern not yet unfortunately! Currently I run it with `-j 2`, limiting how much of CPU it uses, so at least it is not on 100%. However, my codebase is not as big as yours - 30 minutes is really long!
I guess those minor changes happened in files that a large portion of codebase depends on?
I plan on waiting some more for author to explain how he would use rtags on such bigger projects, I see no other way to figure this out without trying to understand internal mechanisms of rtags.

**Comment by schultzern** [comment]
@Martinsos I went with _-j 4_ to avoid 100 %. So thanks for that tip.
Yes, when I edit files that a large part of the code base rely on its usually takes a while. And also if I switch branch in git. 

I'm also curious about what `--rp-nice-value|-a`, `--silent`, `--watch-sources-only` does.

**Comment by Andersbakken** [comment]
Sorry about the long delay. 

In short rdm will reindex every file that has been dirtied. We maintain a dependency graph for every header/source so if you touch a header that tons of files will depend on we will index a bunch of files. 

There are a couple of ways to deal with this situation:

You could suspend the project so nothing will reindex. If you just want to check out a different branch and check something and then go back this could be a good tool.

E.g.

rc --suspend all
git checkout otherbranch
git checkout originalbranch
rc --suspend clear

--watch-sources-only just means that dependencies (headers) won't be monitored for changes which might help but is more useful when you're on mac or freebsd which has a lower ceiling of number of watched files. 

setting --rp-nice-value to something will call nice(3) with this value inside of rp (the process that indexes the files) which also might be useful.

**Comment by schultzern** [comment]
@Andersbakken Thanks! Appreciate the feedback. The _rc --suspend all_ is nifty and has been quite useful for when I just need to check something on a different branch.
