### ISSUE TITLE
Can I have live flycheck with flycheck-rtags?

### ISSUE THREAD

**Issue by Martinsos** [Andersbakken/rtags#973]
Is there any way to get flycheck-rtags to work live? Currently it highlights problems only after buffer is saved.

This is part from my init file:
```
(req-package flycheck-rtags
  :require flycheck rtags
  :config
  (progn
    ;; ensure that we use only rtags checking
    ;; https://github.com/Andersbakken/rtags#optional-1
    (defun setup-flycheck-rtags ()
      (flycheck-select-checker 'rtags)
      (setq-local flycheck-highlighting-mode nil) ;; RTags creates more accurate overlays.
      (setq-local flycheck-check-syntax-automatically nil)
      )
    (add-hook 'c-mode-hook #'setup-flycheck-rtags)
    (add-hook 'c++-mode-hook #'setup-flycheck-rtags)
    ))
```

I tried removing the line with `flycheck-check-syntax-automatically`, I tried setting it to `t`, and I tried removing the whole optional part, however only thing that I achieved was for flycheck to stop working completely.
Thanks for any help!

**Comment by Martinsos** [comment]
I actually just found that this was solved with https://github.com/Andersbakken/rtags/issues/793, so I am closing the issue! Sorry for the trouble.

**Comment by Andersbakken** [comment]
No worries.
