### ISSUE TITLE
Multiple compile_commands.json for one project

### ISSUE THREAD

**Issue by abuszta** [Andersbakken/rtags#975]
This is rtags (rdm/rc/rp) related question.

I have project which is built for multiple platforms. I have multiple build directories generated from CMake. Let's assume that they have different defines/includes/compile flags and maybe some additional files, so I need to index them separately. For each build directory I generate compile_commands.json. Is it possible to select which build directory to use? I saw --build-index option but looking at the code I'm not sure if it is doing what I'm expecting ("For sources with multiple builds, use the arg'th." - which one is arg'th? Order in which I added them using rc -J build_dir?)

**Comment by Andersbakken** [comment]
Hehe. That's kinda cryptic isn't it?

The current approach to this problem (which I also have on my codebase at
work) is to merge the two builds into one.

In short, if you add both compile_commands.json to the same project (which
should just happen if you just do rc -J on both of them) RTags will use a
heuristic to determine if the file needs to be indexed twice. E.g. if it
has different compile flags and try to merge the results.

There are likely some shortcomings (and I would like to know about them)
but this is the current approach to that problem.

--build-index is currently only used for things like preprocess-file,
completion and such things. Not for building the general database.

Anders

**Comment by abuszta** [comment]
Ok, let me describe first use case for which I have clear reproduction scenario right now:

Application is built for desktop macOS and Android. In one of the files I'm including system header (e.g. vector). Both toolchains will use different standard libraries locations, so rdm for --follow-location option should return multiple paths to this system header?  Currently it shows only one:

main.cpp:
```
#include <vector>
int main(int argc, char *argv[])
{
    std::vector<int> a;
    return 0;
}
```

CMakeLists.txt:
```
add_executable(main main.cpp)
```

Commands to reproduce
```
mkdir build-android && cd build-android
cmake .. -DCMAKE_SYSTEM_NAME=ANDROID -DCMAKE_ANDROID_NDK=/opt/android-ndk-r14b/ -DCMAKE_EXPORT_COMPILE_COMMANDS=YES -GNinja
rc -J .
cd ..
mkdir build-osx && cd build-osx
cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=YES -GNinja
rc -J .
cd ..
rc --current-file=main.cpp -f main.cpp:1:15 -K --all-targets
```

Output:
```
/opt/android-ndk-r14b/sources/cxx-stl/gnu-libstdc++/4.9/include/vector:1:1:    // <vector> -*- C++ -*-
```

**Comment by Andersbakken** [comment]
I noticed that when I tried a small example myself.

I think it should be fixed with this last patch.

Note that rtags-multiple-targets must be t (which is the default).

Anders
