### ISSUE TITLE
rtags-taglist: Symbol's value as variable is void: functions

### ISSUE THREAD

**Issue by vibrys** [Andersbakken/rtags#977]
### Please mark appropriate
   - [* ] rtags.el

### Problem description
message from subject is produced.

#### Expected behavior
correct result should appear instead of error message.

### Environment
- Your operating system:
ubuntu 16.04/centos7

- LLVM/Clang version:
4.0.0

### workaround:
when I set lexical-binding to nil, then rtags-taglist works correct.

**Comment by cslux** [comment]
Should be fixed!

**Comment by vibrys** [comment]
works! thanks
