### ISSUE TITLE
I wonder rtags's coding style 

### ISSUE THREAD

**Issue by realwakka** [Andersbakken/rtags#979]
### Please mark appropriate
 - [*] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

I tried write code but I don't know coding style for rtags.
for example, some class member like FileFileJob::mPattern has rule "m~" but some class's member variable ReferenceJob::localtions don't follow the rule.
is there any lint for rtags? or I can make lint for contributing rtags.

**Comment by Andersbakken** [comment]
Hehe. It seems like it's not 100% consistent. Mostly I always use the m
prefix when variables are private.

E.g. Server::Options are meant not to have the m prefix.

I fixed the ReferencesJob.cpp

If you to contribute a linter for the coding style that would be much
appreciated. I think it's mostly consistent and where it isn't I'd like it
to be.

Anders

**Comment by realwakka** [comment]
I want to contribute a linter. but I don't know which is better for rtags.
there is many kinds of c++ linter. for example clang-format, cpplint for google style guide, cppcheck...
can you choose one for me?

**Comment by Andersbakken** [comment]
Hi

I just added a little section on the coding style in the readme.

I honestly have only used clang-format but I was never able to configure it
to my satisfaction.

I currently use this:

{ BasedOnStyle: Mozilla, BreakBeforeBraces: Linux,
ConstructorInitializerAllOnOneLineOrOnePerLine: false,
ConstructorInitializerIndentWidth: 2,
BreakConstructorInitializersBeforeComma: false, PointerBindsToType: false,
PointerAlignment: Right, NamespaceIndentation: None,
AllowAllParametersOfDeclarationOnNextLine: false,
AllowShortFunctionsOnASingleLine: false, ExperimentalAutoDetectBinPacking:
true, ColumnLimit: 140, IndentWidth: 4 }

But like I said, it's not that close to what I want. Ideally I'd like the
linter to mostly not complain about/correct Server.cpp.

Anders
