### ISSUE TITLE
rdm command crashes on OS X Sierra (daemon never starts)

### ISSUE THREAD

**Issue by nilanjan** [Andersbakken/rtags#986]
### Please mark appropriate
 - [x ] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description
Prompt$ ] /usr/local/bin/rdm -v --launchd --inactivity-timeout 300 --log-file ~/Library/Logs/rtags.launchd.log
Couldn't open temp file $HOME/.rtags/crash.dump.tmp for write (2)

rdm daemon never starts.

### Environment
- Your operating system:
OS X Sierra

### Feature request
No

**Comment by Andersbakken** [comment]
This most likely happens because rdm isn't allowed to write to that location but failing to write this file doesn't actually matter very much so I made this a non-fatal error. I suspect you need to fix the permissions on your data dir though.
