### ISSUE TITLE
Automation build

### ISSUE THREAD

**Issue by myrgy** [Andersbakken/rtags#995]
### Please mark appropriate
 - [x ] rtags (rdm/rc/rp)

### Problem description
It might be nice to have automation build on Travis CI.
In addition I think it worth to build packages for different OS
for example I built rmp for Fedora <https://copr.fedorainfracloud.org/coprs/myrgy/rtags/>

**Comment by Andersbakken** [comment]
I'm assuming this means that Travis would retain tarballs/debs/rpms etc for the builds or something like that?

Definitely would be. I don't entirely know how to do it but I should try to get to it. If someone feels like contributing something that would be greatly appreciated.

**Comment by myrgy** [comment]
so, coprs can solve issue of preparing/installing rpm on different systems.
But fortunately it's not able to prepare srpm. On the other hand coprs able to download SRPM from external storrage or as another solution - clone repository with source code (but I didn't find submodules support). In second case we need to organize repository to follow SRPM structere.

So, I think that we can create configuration to prepare SRPM on TravisCI and then trigger build on COPR build server. As a result all users will be able to install latest version.

P.S. I'll try to create Travis build to generate SRPM.

**Comment by Andersbakken** [comment]
Would love to see a PR for this. Thanks

Anders

**Comment by myrgy** [comment]
yep, will try to do it. I'm very busy now.
btw, I was impressed that rtags has macports package!
that great!

**Comment by Andersbakken** [comment]
Sounds good. Let me know when/if you have something you'd like merged. I
don't actually manage any of the packages but I'm glad that people do. I
swear by brew myself but I used macports for many years. It's a good system.

Anders

On Fri, Jul 14, 2017 at 3:32 AM, Alexander Dalshov <notifications@github.com

**Comment by myrgy** [comment]
@Andersbakken , I found that now we have rtags install like in irony-clang - that's great feature and I think my proposal is useless.
It doesn't make any sense to implement this build. Rtags is distributed via MELPA.
