### ISSUE TITLE
rtags-find-references-current-file and symbols-current-file do not work as advertised

### ISSUE THREAD

**Issue by jhferris** [Andersbakken/rtags#998]
### Please mark appropriate
 - [ ] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [* ] rtags.el

### Problem description
rtags-find-references-current-file should (I assume) only return results in the current file. It currently does not for me. 

I think I have fixed them in: https://github.com/Andersbakken/rtags/pull/997

#### Expected behavior
See problem description

#### Actual behavior
see problem description

### Environment
- Your operating system:
Linux

- LLVM/Clang version:
llvm-3.4, emacs24
### Feature request

Describe the feature we should add to **RTags**.

**Comment by Andersbakken** [comment]
Seems like the pull request takes care of this. Thanks again.
